Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=36,
            module='odoo',
            names=[
                alias(name='api', asname=None),
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=65,
            end_col_offset=49,
            name='PosConfig',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=16,
                    end_lineno=7,
                    end_col_offset=28,
                    value=Name(lineno=7, col_offset=16, end_lineno=7, end_col_offset=22, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=27,
                    targets=[Name(lineno=8, col_offset=4, end_lineno=8, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=8, col_offset=15, end_lineno=8, end_col_offset=27, value='pos.config', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=10,
                    col_offset=4,
                    end_lineno=10,
                    end_col_offset=114,
                    targets=[Name(lineno=10, col_offset=4, end_lineno=10, end_col_offset=19, id='iface_splitbill', ctx=Store())],
                    value=Call(
                        lineno=10,
                        col_offset=22,
                        end_lineno=10,
                        end_col_offset=114,
                        func=Attribute(
                            lineno=10,
                            col_offset=22,
                            end_lineno=10,
                            end_col_offset=36,
                            value=Name(lineno=10, col_offset=22, end_lineno=10, end_col_offset=28, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=10,
                                col_offset=37,
                                end_lineno=10,
                                end_col_offset=60,
                                arg='string',
                                value=Constant(lineno=10, col_offset=44, end_lineno=10, end_col_offset=60, value='Bill Splitting', kind=None),
                            ),
                            keyword(
                                lineno=10,
                                col_offset=62,
                                end_lineno=10,
                                end_col_offset=113,
                                arg='help',
                                value=Constant(lineno=10, col_offset=67, end_lineno=10, end_col_offset=113, value='Enables Bill Splitting in the Point of Sale.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=11,
                    col_offset=4,
                    end_lineno=11,
                    end_col_offset=109,
                    targets=[Name(lineno=11, col_offset=4, end_lineno=11, end_col_offset=19, id='iface_printbill', ctx=Store())],
                    value=Call(
                        lineno=11,
                        col_offset=22,
                        end_lineno=11,
                        end_col_offset=109,
                        func=Attribute(
                            lineno=11,
                            col_offset=22,
                            end_lineno=11,
                            end_col_offset=36,
                            value=Name(lineno=11, col_offset=22, end_lineno=11, end_col_offset=28, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=11,
                                col_offset=37,
                                end_lineno=11,
                                end_col_offset=59,
                                arg='string',
                                value=Constant(lineno=11, col_offset=44, end_lineno=11, end_col_offset=59, value='Bill Printing', kind=None),
                            ),
                            keyword(
                                lineno=11,
                                col_offset=61,
                                end_lineno=11,
                                end_col_offset=108,
                                arg='help',
                                value=Constant(lineno=11, col_offset=66, end_lineno=11, end_col_offset=108, value='Allows to print the Bill before payment.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=12,
                    col_offset=4,
                    end_lineno=12,
                    end_col_offset=118,
                    targets=[Name(lineno=12, col_offset=4, end_lineno=12, end_col_offset=25, id='iface_orderline_notes', ctx=Store())],
                    value=Call(
                        lineno=12,
                        col_offset=28,
                        end_lineno=12,
                        end_col_offset=118,
                        func=Attribute(
                            lineno=12,
                            col_offset=28,
                            end_lineno=12,
                            end_col_offset=42,
                            value=Name(lineno=12, col_offset=28, end_lineno=12, end_col_offset=34, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=12,
                                col_offset=43,
                                end_lineno=12,
                                end_col_offset=66,
                                arg='string',
                                value=Constant(lineno=12, col_offset=50, end_lineno=12, end_col_offset=66, value='Internal Notes', kind=None),
                            ),
                            keyword(
                                lineno=12,
                                col_offset=68,
                                end_lineno=12,
                                end_col_offset=117,
                                arg='help',
                                value=Constant(lineno=12, col_offset=73, end_lineno=12, end_col_offset=117, value='Allow custom internal notes on Orderlines.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=13,
                    col_offset=4,
                    end_lineno=13,
                    end_col_offset=156,
                    targets=[Name(lineno=13, col_offset=4, end_lineno=13, end_col_offset=13, id='floor_ids', ctx=Store())],
                    value=Call(
                        lineno=13,
                        col_offset=16,
                        end_lineno=13,
                        end_col_offset=156,
                        func=Attribute(
                            lineno=13,
                            col_offset=16,
                            end_lineno=13,
                            end_col_offset=31,
                            value=Name(lineno=13, col_offset=16, end_lineno=13, end_col_offset=22, id='fields', ctx=Load()),
                            attr='One2many',
                            ctx=Load(),
                        ),
                        args=[
                            Constant(lineno=13, col_offset=32, end_lineno=13, end_col_offset=50, value='restaurant.floor', kind=None),
                            Constant(lineno=13, col_offset=52, end_lineno=13, end_col_offset=67, value='pos_config_id', kind=None),
                        ],
                        keywords=[
                            keyword(
                                lineno=13,
                                col_offset=69,
                                end_lineno=13,
                                end_col_offset=95,
                                arg='string',
                                value=Constant(lineno=13, col_offset=76, end_lineno=13, end_col_offset=95, value='Restaurant Floors', kind=None),
                            ),
                            keyword(
                                lineno=13,
                                col_offset=97,
                                end_lineno=13,
                                end_col_offset=155,
                                arg='help',
                                value=Constant(lineno=13, col_offset=102, end_lineno=13, end_col_offset=155, value='The restaurant floors served by this point of sale.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=14,
                    col_offset=4,
                    end_lineno=14,
                    end_col_offset=134,
                    targets=[Name(lineno=14, col_offset=4, end_lineno=14, end_col_offset=15, id='printer_ids', ctx=Store())],
                    value=Call(
                        lineno=14,
                        col_offset=18,
                        end_lineno=14,
                        end_col_offset=134,
                        func=Attribute(
                            lineno=14,
                            col_offset=18,
                            end_lineno=14,
                            end_col_offset=34,
                            value=Name(lineno=14, col_offset=18, end_lineno=14, end_col_offset=24, id='fields', ctx=Load()),
                            attr='Many2many',
                            ctx=Load(),
                        ),
                        args=[
                            Constant(lineno=14, col_offset=35, end_lineno=14, end_col_offset=55, value='restaurant.printer', kind=None),
                            Constant(lineno=14, col_offset=57, end_lineno=14, end_col_offset=81, value='pos_config_printer_rel', kind=None),
                            Constant(lineno=14, col_offset=83, end_lineno=14, end_col_offset=94, value='config_id', kind=None),
                            Constant(lineno=14, col_offset=96, end_lineno=14, end_col_offset=108, value='printer_id', kind=None),
                        ],
                        keywords=[
                            keyword(
                                lineno=14,
                                col_offset=110,
                                end_lineno=14,
                                end_col_offset=133,
                                arg='string',
                                value=Constant(lineno=14, col_offset=117, end_lineno=14, end_col_offset=133, value='Order Printers', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=15,
                    col_offset=4,
                    end_lineno=15,
                    end_col_offset=59,
                    targets=[Name(lineno=15, col_offset=4, end_lineno=15, end_col_offset=23, id='is_table_management', ctx=Store())],
                    value=Call(
                        lineno=15,
                        col_offset=26,
                        end_lineno=15,
                        end_col_offset=59,
                        func=Attribute(
                            lineno=15,
                            col_offset=26,
                            end_lineno=15,
                            end_col_offset=40,
                            value=Name(lineno=15, col_offset=26, end_lineno=15, end_col_offset=32, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=15, col_offset=41, end_lineno=15, end_col_offset=58, value='Floors & Tables', kind=None)],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=16,
                    col_offset=4,
                    end_lineno=16,
                    end_col_offset=54,
                    targets=[Name(lineno=16, col_offset=4, end_lineno=16, end_col_offset=20, id='is_order_printer', ctx=Store())],
                    value=Call(
                        lineno=16,
                        col_offset=23,
                        end_lineno=16,
                        end_col_offset=54,
                        func=Attribute(
                            lineno=16,
                            col_offset=23,
                            end_lineno=16,
                            end_col_offset=37,
                            value=Name(lineno=16, col_offset=23, end_lineno=16, end_col_offset=29, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=16, col_offset=38, end_lineno=16, end_col_offset=53, value='Order Printer', kind=None)],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=17,
                    col_offset=4,
                    end_lineno=17,
                    end_col_offset=189,
                    targets=[Name(lineno=17, col_offset=4, end_lineno=17, end_col_offset=25, id='set_tip_after_payment', ctx=Store())],
                    value=Call(
                        lineno=17,
                        col_offset=28,
                        end_lineno=17,
                        end_col_offset=189,
                        func=Attribute(
                            lineno=17,
                            col_offset=28,
                            end_lineno=17,
                            end_col_offset=42,
                            value=Name(lineno=17, col_offset=28, end_lineno=17, end_col_offset=34, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=17, col_offset=43, end_lineno=17, end_col_offset=66, value='Set Tip After Payment', kind=None)],
                        keywords=[
                            keyword(
                                lineno=17,
                                col_offset=68,
                                end_lineno=17,
                                end_col_offset=188,
                                arg='help',
                                value=Constant(lineno=17, col_offset=73, end_lineno=17, end_col_offset=188, value='Adjust the amount authorized by payment terminals to add a tip after the customers left or at the end of the day.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=18,
                    col_offset=4,
                    end_lineno=18,
                    end_col_offset=56,
                    targets=[Name(lineno=18, col_offset=4, end_lineno=18, end_col_offset=25, id='module_pos_restaurant', ctx=Store())],
                    value=Call(
                        lineno=18,
                        col_offset=28,
                        end_lineno=18,
                        end_col_offset=56,
                        func=Attribute(
                            lineno=18,
                            col_offset=28,
                            end_lineno=18,
                            end_col_offset=42,
                            value=Name(lineno=18, col_offset=28, end_lineno=18, end_col_offset=34, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=18,
                                col_offset=43,
                                end_lineno=18,
                                end_col_offset=55,
                                arg='default',
                                value=Constant(lineno=18, col_offset=51, end_lineno=18, end_col_offset=55, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=21,
                    col_offset=4,
                    end_lineno=27,
                    end_col_offset=44,
                    name='_onchange_module_pos_restaurant',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=21, col_offset=40, end_lineno=21, end_col_offset=44, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        If(
                            lineno=22,
                            col_offset=8,
                            end_lineno=27,
                            end_col_offset=44,
                            test=UnaryOp(
                                lineno=22,
                                col_offset=11,
                                end_lineno=22,
                                end_col_offset=41,
                                op=Not(),
                                operand=Attribute(
                                    lineno=22,
                                    col_offset=15,
                                    end_lineno=22,
                                    end_col_offset=41,
                                    value=Name(lineno=22, col_offset=15, end_lineno=22, end_col_offset=19, id='self', ctx=Load()),
                                    attr='module_pos_restaurant',
                                    ctx=Load(),
                                ),
                            ),
                            body=[
                                Expr(
                                    lineno=23,
                                    col_offset=12,
                                    end_lineno=27,
                                    end_col_offset=44,
                                    value=Call(
                                        lineno=23,
                                        col_offset=12,
                                        end_lineno=27,
                                        end_col_offset=44,
                                        func=Attribute(
                                            lineno=23,
                                            col_offset=12,
                                            end_lineno=23,
                                            end_col_offset=23,
                                            value=Name(lineno=23, col_offset=12, end_lineno=23, end_col_offset=16, id='self', ctx=Load()),
                                            attr='update',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Dict(
                                                lineno=23,
                                                col_offset=24,
                                                end_lineno=27,
                                                end_col_offset=43,
                                                keys=[
                                                    Constant(lineno=23, col_offset=25, end_lineno=23, end_col_offset=42, value='iface_printbill', kind=None),
                                                    Constant(lineno=24, col_offset=12, end_lineno=24, end_col_offset=29, value='iface_splitbill', kind=None),
                                                    Constant(lineno=25, col_offset=12, end_lineno=25, end_col_offset=30, value='is_order_printer', kind=None),
                                                    Constant(lineno=26, col_offset=12, end_lineno=26, end_col_offset=33, value='is_table_management', kind=None),
                                                    Constant(lineno=27, col_offset=12, end_lineno=27, end_col_offset=35, value='iface_orderline_notes', kind=None),
                                                ],
                                                values=[
                                                    Constant(lineno=23, col_offset=44, end_lineno=23, end_col_offset=49, value=False, kind=None),
                                                    Constant(lineno=24, col_offset=31, end_lineno=24, end_col_offset=36, value=False, kind=None),
                                                    Constant(lineno=25, col_offset=32, end_lineno=25, end_col_offset=37, value=False, kind=None),
                                                    Constant(lineno=26, col_offset=35, end_lineno=26, end_col_offset=40, value=False, kind=None),
                                                    Constant(lineno=27, col_offset=37, end_lineno=27, end_col_offset=42, value=False, kind=None),
                                                ],
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                ),
                            ],
                            orelse=[],
                        ),
                    ],
                    decorator_list=[
                        Call(
                            lineno=20,
                            col_offset=5,
                            end_lineno=20,
                            end_col_offset=42,
                            func=Attribute(
                                lineno=20,
                                col_offset=5,
                                end_lineno=20,
                                end_col_offset=17,
                                value=Name(lineno=20, col_offset=5, end_lineno=20, end_col_offset=8, id='api', ctx=Load()),
                                attr='onchange',
                                ctx=Load(),
                            ),
                            args=[Constant(lineno=20, col_offset=18, end_lineno=20, end_col_offset=41, value='module_pos_restaurant', kind=None)],
                            keywords=[],
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=30,
                    col_offset=4,
                    end_lineno=32,
                    end_col_offset=46,
                    name='_onchange_iface_tipproduct',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=30, col_offset=35, end_lineno=30, end_col_offset=39, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        If(
                            lineno=31,
                            col_offset=8,
                            end_lineno=32,
                            end_col_offset=46,
                            test=UnaryOp(
                                lineno=31,
                                col_offset=11,
                                end_lineno=31,
                                end_col_offset=36,
                                op=Not(),
                                operand=Attribute(
                                    lineno=31,
                                    col_offset=15,
                                    end_lineno=31,
                                    end_col_offset=36,
                                    value=Name(lineno=31, col_offset=15, end_lineno=31, end_col_offset=19, id='self', ctx=Load()),
                                    attr='iface_tipproduct',
                                    ctx=Load(),
                                ),
                            ),
                            body=[
                                Assign(
                                    lineno=32,
                                    col_offset=12,
                                    end_lineno=32,
                                    end_col_offset=46,
                                    targets=[
                                        Attribute(
                                            lineno=32,
                                            col_offset=12,
                                            end_lineno=32,
                                            end_col_offset=38,
                                            value=Name(lineno=32, col_offset=12, end_lineno=32, end_col_offset=16, id='self', ctx=Load()),
                                            attr='set_tip_after_payment',
                                            ctx=Store(),
                                        ),
                                    ],
                                    value=Constant(lineno=32, col_offset=41, end_lineno=32, end_col_offset=46, value=False, kind=None),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[],
                        ),
                    ],
                    decorator_list=[
                        Call(
                            lineno=29,
                            col_offset=5,
                            end_lineno=29,
                            end_col_offset=37,
                            func=Attribute(
                                lineno=29,
                                col_offset=5,
                                end_lineno=29,
                                end_col_offset=17,
                                value=Name(lineno=29, col_offset=5, end_lineno=29, end_col_offset=8, id='api', ctx=Load()),
                                attr='onchange',
                                ctx=Load(),
                            ),
                            args=[Constant(lineno=29, col_offset=18, end_lineno=29, end_col_offset=36, value='iface_tipproduct', kind=None)],
                            keywords=[],
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=34,
                    col_offset=4,
                    end_lineno=38,
                    end_col_offset=51,
                    name='_force_http',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=34, col_offset=20, end_lineno=34, end_col_offset=24, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=35,
                            col_offset=8,
                            end_lineno=35,
                            end_col_offset=103,
                            targets=[Name(lineno=35, col_offset=8, end_lineno=35, end_col_offset=21, id='enforce_https', ctx=Store())],
                            value=Call(
                                lineno=35,
                                col_offset=24,
                                end_lineno=35,
                                end_col_offset=103,
                                func=Attribute(
                                    lineno=35,
                                    col_offset=24,
                                    end_lineno=35,
                                    end_col_offset=72,
                                    value=Call(
                                        lineno=35,
                                        col_offset=24,
                                        end_lineno=35,
                                        end_col_offset=62,
                                        func=Attribute(
                                            lineno=35,
                                            col_offset=24,
                                            end_lineno=35,
                                            end_col_offset=60,
                                            value=Subscript(
                                                lineno=35,
                                                col_offset=24,
                                                end_lineno=35,
                                                end_col_offset=55,
                                                value=Attribute(
                                                    lineno=35,
                                                    col_offset=24,
                                                    end_lineno=35,
                                                    end_col_offset=32,
                                                    value=Name(lineno=35, col_offset=24, end_lineno=35, end_col_offset=28, id='self', ctx=Load()),
                                                    attr='env',
                                                    ctx=Load(),
                                                ),
                                                slice=Constant(lineno=35, col_offset=33, end_lineno=35, end_col_offset=54, value='ir.config_parameter', kind=None),
                                                ctx=Load(),
                                            ),
                                            attr='sudo',
                                            ctx=Load(),
                                        ),
                                        args=[],
                                        keywords=[],
                                    ),
                                    attr='get_param',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=35, col_offset=73, end_lineno=35, end_col_offset=102, value='point_of_sale.enforce_https', kind=None)],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        If(
                            lineno=36,
                            col_offset=8,
                            end_lineno=37,
                            end_col_offset=23,
                            test=BoolOp(
                                lineno=36,
                                col_offset=11,
                                end_lineno=36,
                                end_col_offset=102,
                                op=And(),
                                values=[
                                    UnaryOp(
                                        lineno=36,
                                        col_offset=11,
                                        end_lineno=36,
                                        end_col_offset=28,
                                        op=Not(),
                                        operand=Name(lineno=36, col_offset=15, end_lineno=36, end_col_offset=28, id='enforce_https', ctx=Load()),
                                    ),
                                    Call(
                                        lineno=36,
                                        col_offset=33,
                                        end_lineno=36,
                                        end_col_offset=102,
                                        func=Attribute(
                                            lineno=36,
                                            col_offset=33,
                                            end_lineno=36,
                                            end_col_offset=58,
                                            value=Attribute(
                                                lineno=36,
                                                col_offset=33,
                                                end_lineno=36,
                                                end_col_offset=49,
                                                value=Name(lineno=36, col_offset=33, end_lineno=36, end_col_offset=37, id='self', ctx=Load()),
                                                attr='printer_ids',
                                                ctx=Load(),
                                            ),
                                            attr='filtered',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Lambda(
                                                lineno=36,
                                                col_offset=59,
                                                end_lineno=36,
                                                end_col_offset=101,
                                                args=arguments(
                                                    posonlyargs=[],
                                                    args=[arg(lineno=36, col_offset=66, end_lineno=36, end_col_offset=68, arg='pt', annotation=None, type_comment=None)],
                                                    vararg=None,
                                                    kwonlyargs=[],
                                                    kw_defaults=[],
                                                    kwarg=None,
                                                    defaults=[],
                                                ),
                                                body=Compare(
                                                    lineno=36,
                                                    col_offset=70,
                                                    end_lineno=36,
                                                    end_col_offset=101,
                                                    left=Attribute(
                                                        lineno=36,
                                                        col_offset=70,
                                                        end_lineno=36,
                                                        end_col_offset=85,
                                                        value=Name(lineno=36, col_offset=70, end_lineno=36, end_col_offset=72, id='pt', ctx=Load()),
                                                        attr='printer_type',
                                                        ctx=Load(),
                                                    ),
                                                    ops=[Eq()],
                                                    comparators=[Constant(lineno=36, col_offset=89, end_lineno=36, end_col_offset=101, value='epson_epos', kind=None)],
                                                ),
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                ],
                            ),
                            body=[
                                Return(
                                    lineno=37,
                                    col_offset=12,
                                    end_lineno=37,
                                    end_col_offset=23,
                                    value=Constant(lineno=37, col_offset=19, end_lineno=37, end_col_offset=23, value=True, kind=None),
                                ),
                            ],
                            orelse=[],
                        ),
                        Return(
                            lineno=38,
                            col_offset=8,
                            end_lineno=38,
                            end_col_offset=51,
                            value=Call(
                                lineno=38,
                                col_offset=15,
                                end_lineno=38,
                                end_col_offset=51,
                                func=Attribute(
                                    lineno=38,
                                    col_offset=15,
                                    end_lineno=38,
                                    end_col_offset=49,
                                    value=Call(
                                        lineno=38,
                                        col_offset=15,
                                        end_lineno=38,
                                        end_col_offset=37,
                                        func=Name(lineno=38, col_offset=15, end_lineno=38, end_col_offset=20, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=38, col_offset=21, end_lineno=38, end_col_offset=30, id='PosConfig', ctx=Load()),
                                            Name(lineno=38, col_offset=32, end_lineno=38, end_col_offset=36, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='_force_http',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=40,
                    col_offset=4,
                    end_lineno=52,
                    end_col_offset=21,
                    name='get_tables_order_count',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=40, col_offset=31, end_lineno=40, end_col_offset=35, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=41,
                            col_offset=8,
                            end_lineno=41,
                            end_col_offset=23,
                            value=Constant(lineno=41, col_offset=8, end_lineno=41, end_col_offset=23, value='         ', kind=None),
                        ),
                        Expr(
                            lineno=42,
                            col_offset=8,
                            end_lineno=42,
                            end_col_offset=25,
                            value=Call(
                                lineno=42,
                                col_offset=8,
                                end_lineno=42,
                                end_col_offset=25,
                                func=Attribute(
                                    lineno=42,
                                    col_offset=8,
                                    end_lineno=42,
                                    end_col_offset=23,
                                    value=Name(lineno=42, col_offset=8, end_lineno=42, end_col_offset=12, id='self', ctx=Load()),
                                    attr='ensure_one',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=43,
                            col_offset=8,
                            end_lineno=43,
                            end_col_offset=98,
                            targets=[Name(lineno=43, col_offset=8, end_lineno=43, end_col_offset=14, id='tables', ctx=Store())],
                            value=Call(
                                lineno=43,
                                col_offset=17,
                                end_lineno=43,
                                end_col_offset=98,
                                func=Attribute(
                                    lineno=43,
                                    col_offset=17,
                                    end_lineno=43,
                                    end_col_offset=52,
                                    value=Subscript(
                                        lineno=43,
                                        col_offset=17,
                                        end_lineno=43,
                                        end_col_offset=45,
                                        value=Attribute(
                                            lineno=43,
                                            col_offset=17,
                                            end_lineno=43,
                                            end_col_offset=25,
                                            value=Name(lineno=43, col_offset=17, end_lineno=43, end_col_offset=21, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=43, col_offset=26, end_lineno=43, end_col_offset=44, value='restaurant.table', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='search',
                                    ctx=Load(),
                                ),
                                args=[
                                    List(
                                        lineno=43,
                                        col_offset=53,
                                        end_lineno=43,
                                        end_col_offset=97,
                                        elts=[
                                            Tuple(
                                                lineno=43,
                                                col_offset=54,
                                                end_lineno=43,
                                                end_col_offset=96,
                                                elts=[
                                                    Constant(lineno=43, col_offset=55, end_lineno=43, end_col_offset=79, value='floor_id.pos_config_id', kind=None),
                                                    Constant(lineno=43, col_offset=81, end_lineno=43, end_col_offset=85, value='in', kind=None),
                                                    Attribute(
                                                        lineno=43,
                                                        col_offset=87,
                                                        end_lineno=43,
                                                        end_col_offset=95,
                                                        value=Name(lineno=43, col_offset=87, end_lineno=43, end_col_offset=91, id='self', ctx=Load()),
                                                        attr='ids',
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=44,
                            col_offset=8,
                            end_lineno=44,
                            end_col_offset=74,
                            targets=[Name(lineno=44, col_offset=8, end_lineno=44, end_col_offset=14, id='domain', ctx=Store())],
                            value=List(
                                lineno=44,
                                col_offset=17,
                                end_lineno=44,
                                end_col_offset=74,
                                elts=[
                                    Tuple(
                                        lineno=44,
                                        col_offset=18,
                                        end_lineno=44,
                                        end_col_offset=41,
                                        elts=[
                                            Constant(lineno=44, col_offset=19, end_lineno=44, end_col_offset=26, value='state', kind=None),
                                            Constant(lineno=44, col_offset=28, end_lineno=44, end_col_offset=31, value='=', kind=None),
                                            Constant(lineno=44, col_offset=33, end_lineno=44, end_col_offset=40, value='draft', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                    Tuple(
                                        lineno=44,
                                        col_offset=43,
                                        end_lineno=44,
                                        end_col_offset=73,
                                        elts=[
                                            Constant(lineno=44, col_offset=44, end_lineno=44, end_col_offset=54, value='table_id', kind=None),
                                            Constant(lineno=44, col_offset=56, end_lineno=44, end_col_offset=60, value='in', kind=None),
                                            Attribute(
                                                lineno=44,
                                                col_offset=62,
                                                end_lineno=44,
                                                end_col_offset=72,
                                                value=Name(lineno=44, col_offset=62, end_lineno=44, end_col_offset=68, id='tables', ctx=Load()),
                                                attr='ids',
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=46,
                            col_offset=8,
                            end_lineno=46,
                            end_col_offset=88,
                            targets=[Name(lineno=46, col_offset=8, end_lineno=46, end_col_offset=19, id='order_stats', ctx=Store())],
                            value=Call(
                                lineno=46,
                                col_offset=22,
                                end_lineno=46,
                                end_col_offset=88,
                                func=Attribute(
                                    lineno=46,
                                    col_offset=22,
                                    end_lineno=46,
                                    end_col_offset=54,
                                    value=Subscript(
                                        lineno=46,
                                        col_offset=22,
                                        end_lineno=46,
                                        end_col_offset=43,
                                        value=Attribute(
                                            lineno=46,
                                            col_offset=22,
                                            end_lineno=46,
                                            end_col_offset=30,
                                            value=Name(lineno=46, col_offset=22, end_lineno=46, end_col_offset=26, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=46, col_offset=31, end_lineno=46, end_col_offset=42, value='pos.order', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='read_group',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=46, col_offset=55, end_lineno=46, end_col_offset=61, id='domain', ctx=Load()),
                                    List(
                                        lineno=46,
                                        col_offset=63,
                                        end_lineno=46,
                                        end_col_offset=75,
                                        elts=[Constant(lineno=46, col_offset=64, end_lineno=46, end_col_offset=74, value='table_id', kind=None)],
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=46, col_offset=77, end_lineno=46, end_col_offset=87, value='table_id', kind=None),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=47,
                            col_offset=8,
                            end_lineno=47,
                            end_col_offset=87,
                            targets=[Name(lineno=47, col_offset=8, end_lineno=47, end_col_offset=18, id='orders_map', ctx=Store())],
                            value=Call(
                                lineno=47,
                                col_offset=21,
                                end_lineno=47,
                                end_col_offset=87,
                                func=Name(lineno=47, col_offset=21, end_lineno=47, end_col_offset=25, id='dict', ctx=Load()),
                                args=[
                                    GeneratorExp(
                                        lineno=47,
                                        col_offset=25,
                                        end_lineno=47,
                                        end_col_offset=87,
                                        elt=Tuple(
                                            lineno=47,
                                            col_offset=26,
                                            end_lineno=47,
                                            end_col_offset=65,
                                            elts=[
                                                Subscript(
                                                    lineno=47,
                                                    col_offset=27,
                                                    end_lineno=47,
                                                    end_col_offset=43,
                                                    value=Subscript(
                                                        lineno=47,
                                                        col_offset=27,
                                                        end_lineno=47,
                                                        end_col_offset=40,
                                                        value=Name(lineno=47, col_offset=27, end_lineno=47, end_col_offset=28, id='s', ctx=Load()),
                                                        slice=Constant(lineno=47, col_offset=29, end_lineno=47, end_col_offset=39, value='table_id', kind=None),
                                                        ctx=Load(),
                                                    ),
                                                    slice=Constant(lineno=47, col_offset=41, end_lineno=47, end_col_offset=42, value=0, kind=None),
                                                    ctx=Load(),
                                                ),
                                                Subscript(
                                                    lineno=47,
                                                    col_offset=45,
                                                    end_lineno=47,
                                                    end_col_offset=64,
                                                    value=Name(lineno=47, col_offset=45, end_lineno=47, end_col_offset=46, id='s', ctx=Load()),
                                                    slice=Constant(lineno=47, col_offset=47, end_lineno=47, end_col_offset=63, value='table_id_count', kind=None),
                                                    ctx=Load(),
                                                ),
                                            ],
                                            ctx=Load(),
                                        ),
                                        generators=[
                                            comprehension(
                                                target=Name(lineno=47, col_offset=70, end_lineno=47, end_col_offset=71, id='s', ctx=Store()),
                                                iter=Name(lineno=47, col_offset=75, end_lineno=47, end_col_offset=86, id='order_stats', ctx=Load()),
                                                ifs=[],
                                                is_async=0,
                                            ),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=49,
                            col_offset=8,
                            end_lineno=49,
                            end_col_offset=19,
                            targets=[Name(lineno=49, col_offset=8, end_lineno=49, end_col_offset=14, id='result', ctx=Store())],
                            value=List(lineno=49, col_offset=17, end_lineno=49, end_col_offset=19, elts=[], ctx=Load()),
                            type_comment=None,
                        ),
                        For(
                            lineno=50,
                            col_offset=8,
                            end_lineno=51,
                            end_col_offset=82,
                            target=Name(lineno=50, col_offset=12, end_lineno=50, end_col_offset=17, id='table', ctx=Store()),
                            iter=Name(lineno=50, col_offset=21, end_lineno=50, end_col_offset=27, id='tables', ctx=Load()),
                            body=[
                                Expr(
                                    lineno=51,
                                    col_offset=12,
                                    end_lineno=51,
                                    end_col_offset=82,
                                    value=Call(
                                        lineno=51,
                                        col_offset=12,
                                        end_lineno=51,
                                        end_col_offset=82,
                                        func=Attribute(
                                            lineno=51,
                                            col_offset=12,
                                            end_lineno=51,
                                            end_col_offset=25,
                                            value=Name(lineno=51, col_offset=12, end_lineno=51, end_col_offset=18, id='result', ctx=Load()),
                                            attr='append',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Dict(
                                                lineno=51,
                                                col_offset=26,
                                                end_lineno=51,
                                                end_col_offset=81,
                                                keys=[
                                                    Constant(lineno=51, col_offset=27, end_lineno=51, end_col_offset=31, value='id', kind=None),
                                                    Constant(lineno=51, col_offset=43, end_lineno=51, end_col_offset=51, value='orders', kind=None),
                                                ],
                                                values=[
                                                    Attribute(
                                                        lineno=51,
                                                        col_offset=33,
                                                        end_lineno=51,
                                                        end_col_offset=41,
                                                        value=Name(lineno=51, col_offset=33, end_lineno=51, end_col_offset=38, id='table', ctx=Load()),
                                                        attr='id',
                                                        ctx=Load(),
                                                    ),
                                                    Call(
                                                        lineno=51,
                                                        col_offset=53,
                                                        end_lineno=51,
                                                        end_col_offset=80,
                                                        func=Attribute(
                                                            lineno=51,
                                                            col_offset=53,
                                                            end_lineno=51,
                                                            end_col_offset=67,
                                                            value=Name(lineno=51, col_offset=53, end_lineno=51, end_col_offset=63, id='orders_map', ctx=Load()),
                                                            attr='get',
                                                            ctx=Load(),
                                                        ),
                                                        args=[
                                                            Attribute(
                                                                lineno=51,
                                                                col_offset=68,
                                                                end_lineno=51,
                                                                end_col_offset=76,
                                                                value=Name(lineno=51, col_offset=68, end_lineno=51, end_col_offset=73, id='table', ctx=Load()),
                                                                attr='id',
                                                                ctx=Load(),
                                                            ),
                                                            Constant(lineno=51, col_offset=78, end_lineno=51, end_col_offset=79, value=0, kind=None),
                                                        ],
                                                        keywords=[],
                                                    ),
                                                ],
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                ),
                            ],
                            orelse=[],
                            type_comment=None,
                        ),
                        Return(
                            lineno=52,
                            col_offset=8,
                            end_lineno=52,
                            end_col_offset=21,
                            value=Name(lineno=52, col_offset=15, end_lineno=52, end_col_offset=21, id='result', ctx=Load()),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=54,
                    col_offset=4,
                    end_lineno=58,
                    end_col_offset=29,
                    name='_get_forbidden_change_fields',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=54, col_offset=37, end_lineno=54, end_col_offset=41, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=55,
                            col_offset=8,
                            end_lineno=55,
                            end_col_offset=78,
                            targets=[Name(lineno=55, col_offset=8, end_lineno=55, end_col_offset=22, id='forbidden_keys', ctx=Store())],
                            value=Call(
                                lineno=55,
                                col_offset=25,
                                end_lineno=55,
                                end_col_offset=78,
                                func=Attribute(
                                    lineno=55,
                                    col_offset=25,
                                    end_lineno=55,
                                    end_col_offset=76,
                                    value=Call(
                                        lineno=55,
                                        col_offset=25,
                                        end_lineno=55,
                                        end_col_offset=47,
                                        func=Name(lineno=55, col_offset=25, end_lineno=55, end_col_offset=30, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=55, col_offset=31, end_lineno=55, end_col_offset=40, id='PosConfig', ctx=Load()),
                                            Name(lineno=55, col_offset=42, end_lineno=55, end_col_offset=46, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='_get_forbidden_change_fields',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=56,
                            col_offset=8,
                            end_lineno=56,
                            end_col_offset=52,
                            value=Call(
                                lineno=56,
                                col_offset=8,
                                end_lineno=56,
                                end_col_offset=52,
                                func=Attribute(
                                    lineno=56,
                                    col_offset=8,
                                    end_lineno=56,
                                    end_col_offset=29,
                                    value=Name(lineno=56, col_offset=8, end_lineno=56, end_col_offset=22, id='forbidden_keys', ctx=Load()),
                                    attr='append',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=56, col_offset=30, end_lineno=56, end_col_offset=51, value='is_table_management', kind=None)],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=57,
                            col_offset=8,
                            end_lineno=57,
                            end_col_offset=42,
                            value=Call(
                                lineno=57,
                                col_offset=8,
                                end_lineno=57,
                                end_col_offset=42,
                                func=Attribute(
                                    lineno=57,
                                    col_offset=8,
                                    end_lineno=57,
                                    end_col_offset=29,
                                    value=Name(lineno=57, col_offset=8, end_lineno=57, end_col_offset=22, id='forbidden_keys', ctx=Load()),
                                    attr='append',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=57, col_offset=30, end_lineno=57, end_col_offset=41, value='floor_ids', kind=None)],
                                keywords=[],
                            ),
                        ),
                        Return(
                            lineno=58,
                            col_offset=8,
                            end_lineno=58,
                            end_col_offset=29,
                            value=Name(lineno=58, col_offset=15, end_lineno=58, end_col_offset=29, id='forbidden_keys', ctx=Load()),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=60,
                    col_offset=4,
                    end_lineno=65,
                    end_col_offset=49,
                    name='write',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=60, col_offset=14, end_lineno=60, end_col_offset=18, arg='self', annotation=None, type_comment=None),
                            arg(lineno=60, col_offset=20, end_lineno=60, end_col_offset=24, arg='vals', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        If(
                            lineno=61,
                            col_offset=8,
                            end_lineno=62,
                            end_col_offset=43,
                            test=BoolOp(
                                lineno=61,
                                col_offset=12,
                                end_lineno=61,
                                end_col_offset=82,
                                op=And(),
                                values=[
                                    Compare(
                                        lineno=61,
                                        col_offset=12,
                                        end_lineno=61,
                                        end_col_offset=41,
                                        left=Constant(lineno=61, col_offset=12, end_lineno=61, end_col_offset=33, value='is_table_management', kind=None),
                                        ops=[In()],
                                        comparators=[Name(lineno=61, col_offset=37, end_lineno=61, end_col_offset=41, id='vals', ctx=Load())],
                                    ),
                                    Compare(
                                        lineno=61,
                                        col_offset=46,
                                        end_lineno=61,
                                        end_col_offset=82,
                                        left=Subscript(
                                            lineno=61,
                                            col_offset=46,
                                            end_lineno=61,
                                            end_col_offset=73,
                                            value=Name(lineno=61, col_offset=46, end_lineno=61, end_col_offset=50, id='vals', ctx=Load()),
                                            slice=Constant(lineno=61, col_offset=51, end_lineno=61, end_col_offset=72, value='is_table_management', kind=None),
                                            ctx=Load(),
                                        ),
                                        ops=[Eq()],
                                        comparators=[Constant(lineno=61, col_offset=77, end_lineno=61, end_col_offset=82, value=False, kind=None)],
                                    ),
                                ],
                            ),
                            body=[
                                Assign(
                                    lineno=62,
                                    col_offset=12,
                                    end_lineno=62,
                                    end_col_offset=43,
                                    targets=[
                                        Subscript(
                                            lineno=62,
                                            col_offset=12,
                                            end_lineno=62,
                                            end_col_offset=29,
                                            value=Name(lineno=62, col_offset=12, end_lineno=62, end_col_offset=16, id='vals', ctx=Load()),
                                            slice=Constant(lineno=62, col_offset=17, end_lineno=62, end_col_offset=28, value='floor_ids', kind=None),
                                            ctx=Store(),
                                        ),
                                    ],
                                    value=List(
                                        lineno=62,
                                        col_offset=32,
                                        end_lineno=62,
                                        end_col_offset=43,
                                        elts=[
                                            Tuple(
                                                lineno=62,
                                                col_offset=33,
                                                end_lineno=62,
                                                end_col_offset=42,
                                                elts=[
                                                    Constant(lineno=62, col_offset=34, end_lineno=62, end_col_offset=35, value=5, kind=None),
                                                    Constant(lineno=62, col_offset=37, end_lineno=62, end_col_offset=38, value=0, kind=None),
                                                    Constant(lineno=62, col_offset=40, end_lineno=62, end_col_offset=41, value=0, kind=None),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[],
                        ),
                        If(
                            lineno=63,
                            col_offset=8,
                            end_lineno=64,
                            end_col_offset=45,
                            test=BoolOp(
                                lineno=63,
                                col_offset=12,
                                end_lineno=63,
                                end_col_offset=76,
                                op=And(),
                                values=[
                                    Compare(
                                        lineno=63,
                                        col_offset=12,
                                        end_lineno=63,
                                        end_col_offset=38,
                                        left=Constant(lineno=63, col_offset=12, end_lineno=63, end_col_offset=30, value='is_order_printer', kind=None),
                                        ops=[In()],
                                        comparators=[Name(lineno=63, col_offset=34, end_lineno=63, end_col_offset=38, id='vals', ctx=Load())],
                                    ),
                                    Compare(
                                        lineno=63,
                                        col_offset=43,
                                        end_lineno=63,
                                        end_col_offset=76,
                                        left=Subscript(
                                            lineno=63,
                                            col_offset=43,
                                            end_lineno=63,
                                            end_col_offset=67,
                                            value=Name(lineno=63, col_offset=43, end_lineno=63, end_col_offset=47, id='vals', ctx=Load()),
                                            slice=Constant(lineno=63, col_offset=48, end_lineno=63, end_col_offset=66, value='is_order_printer', kind=None),
                                            ctx=Load(),
                                        ),
                                        ops=[Eq()],
                                        comparators=[Constant(lineno=63, col_offset=71, end_lineno=63, end_col_offset=76, value=False, kind=None)],
                                    ),
                                ],
                            ),
                            body=[
                                Assign(
                                    lineno=64,
                                    col_offset=12,
                                    end_lineno=64,
                                    end_col_offset=45,
                                    targets=[
                                        Subscript(
                                            lineno=64,
                                            col_offset=12,
                                            end_lineno=64,
                                            end_col_offset=31,
                                            value=Name(lineno=64, col_offset=12, end_lineno=64, end_col_offset=16, id='vals', ctx=Load()),
                                            slice=Constant(lineno=64, col_offset=17, end_lineno=64, end_col_offset=30, value='printer_ids', kind=None),
                                            ctx=Store(),
                                        ),
                                    ],
                                    value=List(
                                        lineno=64,
                                        col_offset=34,
                                        end_lineno=64,
                                        end_col_offset=45,
                                        elts=[
                                            Tuple(
                                                lineno=64,
                                                col_offset=35,
                                                end_lineno=64,
                                                end_col_offset=44,
                                                elts=[
                                                    Constant(lineno=64, col_offset=36, end_lineno=64, end_col_offset=37, value=5, kind=None),
                                                    Constant(lineno=64, col_offset=39, end_lineno=64, end_col_offset=40, value=0, kind=None),
                                                    Constant(lineno=64, col_offset=42, end_lineno=64, end_col_offset=43, value=0, kind=None),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[],
                        ),
                        Return(
                            lineno=65,
                            col_offset=8,
                            end_lineno=65,
                            end_col_offset=49,
                            value=Call(
                                lineno=65,
                                col_offset=15,
                                end_lineno=65,
                                end_col_offset=49,
                                func=Attribute(
                                    lineno=65,
                                    col_offset=15,
                                    end_lineno=65,
                                    end_col_offset=43,
                                    value=Call(
                                        lineno=65,
                                        col_offset=15,
                                        end_lineno=65,
                                        end_col_offset=37,
                                        func=Name(lineno=65, col_offset=15, end_lineno=65, end_col_offset=20, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=65, col_offset=21, end_lineno=65, end_col_offset=30, id='PosConfig', ctx=Load()),
                                            Name(lineno=65, col_offset=32, end_lineno=65, end_col_offset=36, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='write',
                                    ctx=Load(),
                                ),
                                args=[Name(lineno=65, col_offset=44, end_lineno=65, end_col_offset=48, id='vals', ctx=Load())],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
