Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=46,
            module='datetime',
            names=[
                alias(name='datetime', asname=None),
                alias(name='timedelta', asname=None),
                alias(name='time', asname=None),
            ],
            level=0,
        ),
        ImportFrom(
            lineno=5,
            col_offset=0,
            end_lineno=5,
            end_col_offset=30,
            module='pytz',
            names=[
                alias(name='timezone', asname=None),
                alias(name='utc', asname=None),
            ],
            level=0,
        ),
        ImportFrom(
            lineno=7,
            col_offset=0,
            end_lineno=7,
            end_col_offset=23,
            module='odoo',
            names=[alias(name='fields', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=8,
            col_offset=0,
            end_lineno=8,
            end_col_offset=54,
            module='odoo.addons.mrp.tests.common',
            names=[alias(name='TestMrpCommon', asname=None)],
            level=0,
        ),
        ClassDef(
            lineno=11,
            col_offset=0,
            end_lineno=71,
            end_col_offset=89,
            name='TestOee',
            bases=[Name(lineno=11, col_offset=14, end_lineno=11, end_col_offset=27, id='TestMrpCommon', ctx=Load())],
            keywords=[],
            body=[
                FunctionDef(
                    lineno=12,
                    col_offset=4,
                    end_lineno=19,
                    end_col_offset=10,
                    name='create_productivity_line',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=12, col_offset=33, end_lineno=12, end_col_offset=37, arg='self', annotation=None, type_comment=None),
                            arg(lineno=12, col_offset=39, end_lineno=12, end_col_offset=50, arg='loss_reason', annotation=None, type_comment=None),
                            arg(lineno=12, col_offset=52, end_lineno=12, end_col_offset=62, arg='date_start', annotation=None, type_comment=None),
                            arg(lineno=12, col_offset=70, end_lineno=12, end_col_offset=78, arg='date_end', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[
                            Constant(lineno=12, col_offset=63, end_lineno=12, end_col_offset=68, value=False, kind=None),
                            Constant(lineno=12, col_offset=79, end_lineno=12, end_col_offset=84, value=False, kind=None),
                        ],
                    ),
                    body=[
                        Return(
                            lineno=13,
                            col_offset=8,
                            end_lineno=19,
                            end_col_offset=10,
                            value=Call(
                                lineno=13,
                                col_offset=15,
                                end_lineno=19,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=13,
                                    col_offset=15,
                                    end_lineno=13,
                                    end_col_offset=61,
                                    value=Subscript(
                                        lineno=13,
                                        col_offset=15,
                                        end_lineno=13,
                                        end_col_offset=54,
                                        value=Attribute(
                                            lineno=13,
                                            col_offset=15,
                                            end_lineno=13,
                                            end_col_offset=23,
                                            value=Name(lineno=13, col_offset=15, end_lineno=13, end_col_offset=19, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=13, col_offset=24, end_lineno=13, end_col_offset=53, value='mrp.workcenter.productivity', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=13,
                                        col_offset=62,
                                        end_lineno=19,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=14, col_offset=12, end_lineno=14, end_col_offset=27, value='workcenter_id', kind=None),
                                            Constant(lineno=15, col_offset=12, end_lineno=15, end_col_offset=24, value='date_start', kind=None),
                                            Constant(lineno=16, col_offset=12, end_lineno=16, end_col_offset=22, value='date_end', kind=None),
                                            Constant(lineno=17, col_offset=12, end_lineno=17, end_col_offset=21, value='loss_id', kind=None),
                                            Constant(lineno=18, col_offset=12, end_lineno=18, end_col_offset=25, value='description', kind=None),
                                        ],
                                        values=[
                                            Attribute(
                                                lineno=14,
                                                col_offset=29,
                                                end_lineno=14,
                                                end_col_offset=49,
                                                value=Attribute(
                                                    lineno=14,
                                                    col_offset=29,
                                                    end_lineno=14,
                                                    end_col_offset=46,
                                                    value=Name(lineno=14, col_offset=29, end_lineno=14, end_col_offset=33, id='self', ctx=Load()),
                                                    attr='workcenter_1',
                                                    ctx=Load(),
                                                ),
                                                attr='id',
                                                ctx=Load(),
                                            ),
                                            Name(lineno=15, col_offset=26, end_lineno=15, end_col_offset=36, id='date_start', ctx=Load()),
                                            Name(lineno=16, col_offset=24, end_lineno=16, end_col_offset=32, id='date_end', ctx=Load()),
                                            Attribute(
                                                lineno=17,
                                                col_offset=23,
                                                end_lineno=17,
                                                end_col_offset=37,
                                                value=Name(lineno=17, col_offset=23, end_lineno=17, end_col_offset=34, id='loss_reason', ctx=Load()),
                                                attr='id',
                                                ctx=Load(),
                                            ),
                                            Attribute(
                                                lineno=18,
                                                col_offset=27,
                                                end_lineno=18,
                                                end_col_offset=43,
                                                value=Name(lineno=18, col_offset=27, end_lineno=18, end_col_offset=38, id='loss_reason', ctx=Load()),
                                                attr='name',
                                                ctx=Load(),
                                            ),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=21,
                    col_offset=4,
                    end_lineno=71,
                    end_col_offset=89,
                    name='test_wrokcenter_oee',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=21, col_offset=28, end_lineno=21, end_col_offset=32, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=22,
                            col_offset=8,
                            end_lineno=22,
                            end_col_offset=42,
                            value=Constant(lineno=22, col_offset=8, end_lineno=22, end_col_offset=42, value='  Test case workcenter oee. ', kind=None),
                        ),
                        Assign(
                            lineno=23,
                            col_offset=8,
                            end_lineno=23,
                            end_col_offset=45,
                            targets=[Name(lineno=23, col_offset=8, end_lineno=23, end_col_offset=11, id='day', ctx=Store())],
                            value=Call(
                                lineno=23,
                                col_offset=14,
                                end_lineno=23,
                                end_col_offset=45,
                                func=Attribute(
                                    lineno=23,
                                    col_offset=14,
                                    end_lineno=23,
                                    end_col_offset=27,
                                    value=Name(lineno=23, col_offset=14, end_lineno=23, end_col_offset=22, id='datetime', ctx=Load()),
                                    attr='date',
                                    ctx=Load(),
                                ),
                                args=[
                                    Call(
                                        lineno=23,
                                        col_offset=28,
                                        end_lineno=23,
                                        end_col_offset=44,
                                        func=Attribute(
                                            lineno=23,
                                            col_offset=28,
                                            end_lineno=23,
                                            end_col_offset=42,
                                            value=Name(lineno=23, col_offset=28, end_lineno=23, end_col_offset=36, id='datetime', ctx=Load()),
                                            attr='today',
                                            ctx=Load(),
                                        ),
                                        args=[],
                                        keywords=[],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        If(
                            lineno=25,
                            col_offset=8,
                            end_lineno=26,
                            end_col_offset=36,
                            test=Compare(
                                lineno=25,
                                col_offset=11,
                                end_lineno=25,
                                end_col_offset=34,
                                left=Call(
                                    lineno=25,
                                    col_offset=11,
                                    end_lineno=25,
                                    end_col_offset=24,
                                    func=Attribute(
                                        lineno=25,
                                        col_offset=11,
                                        end_lineno=25,
                                        end_col_offset=22,
                                        value=Name(lineno=25, col_offset=11, end_lineno=25, end_col_offset=14, id='day', ctx=Load()),
                                        attr='weekday',
                                        ctx=Load(),
                                    ),
                                    args=[],
                                    keywords=[],
                                ),
                                ops=[In()],
                                comparators=[
                                    Tuple(
                                        lineno=25,
                                        col_offset=28,
                                        end_lineno=25,
                                        end_col_offset=34,
                                        elts=[
                                            Constant(lineno=25, col_offset=29, end_lineno=25, end_col_offset=30, value=5, kind=None),
                                            Constant(lineno=25, col_offset=32, end_lineno=25, end_col_offset=33, value=6, kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                            ),
                            body=[
                                AugAssign(
                                    lineno=26,
                                    col_offset=12,
                                    end_lineno=26,
                                    end_col_offset=36,
                                    target=Name(lineno=26, col_offset=12, end_lineno=26, end_col_offset=15, id='day', ctx=Store()),
                                    op=Sub(),
                                    value=Call(
                                        lineno=26,
                                        col_offset=19,
                                        end_lineno=26,
                                        end_col_offset=36,
                                        func=Name(lineno=26, col_offset=19, end_lineno=26, end_col_offset=28, id='timedelta', ctx=Load()),
                                        args=[],
                                        keywords=[
                                            keyword(
                                                lineno=26,
                                                col_offset=29,
                                                end_lineno=26,
                                                end_col_offset=35,
                                                arg='days',
                                                value=Constant(lineno=26, col_offset=34, end_lineno=26, end_col_offset=35, value=2, kind=None),
                                            ),
                                        ],
                                    ),
                                ),
                            ],
                            orelse=[],
                        ),
                        Assign(
                            lineno=28,
                            col_offset=8,
                            end_lineno=28,
                            end_col_offset=64,
                            targets=[Name(lineno=28, col_offset=8, end_lineno=28, end_col_offset=10, id='tz', ctx=Store())],
                            value=Call(
                                lineno=28,
                                col_offset=13,
                                end_lineno=28,
                                end_col_offset=64,
                                func=Name(lineno=28, col_offset=13, end_lineno=28, end_col_offset=21, id='timezone', ctx=Load()),
                                args=[
                                    Attribute(
                                        lineno=28,
                                        col_offset=22,
                                        end_lineno=28,
                                        end_col_offset=63,
                                        value=Attribute(
                                            lineno=28,
                                            col_offset=22,
                                            end_lineno=28,
                                            end_col_offset=60,
                                            value=Attribute(
                                                lineno=28,
                                                col_offset=22,
                                                end_lineno=28,
                                                end_col_offset=39,
                                                value=Name(lineno=28, col_offset=22, end_lineno=28, end_col_offset=26, id='self', ctx=Load()),
                                                attr='workcenter_1',
                                                ctx=Load(),
                                            ),
                                            attr='resource_calendar_id',
                                            ctx=Load(),
                                        ),
                                        attr='tz',
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        FunctionDef(
                            lineno=30,
                            col_offset=8,
                            end_lineno=33,
                            end_col_offset=13,
                            name='time_to_string_utc_datetime',
                            args=arguments(
                                posonlyargs=[],
                                args=[arg(lineno=30, col_offset=40, end_lineno=30, end_col_offset=44, arg='time', annotation=None, type_comment=None)],
                                vararg=None,
                                kwonlyargs=[],
                                kw_defaults=[],
                                kwarg=None,
                                defaults=[],
                            ),
                            body=[
                                Return(
                                    lineno=31,
                                    col_offset=12,
                                    end_lineno=33,
                                    end_col_offset=13,
                                    value=Call(
                                        lineno=31,
                                        col_offset=19,
                                        end_lineno=33,
                                        end_col_offset=13,
                                        func=Attribute(
                                            lineno=31,
                                            col_offset=19,
                                            end_lineno=31,
                                            end_col_offset=44,
                                            value=Attribute(
                                                lineno=31,
                                                col_offset=19,
                                                end_lineno=31,
                                                end_col_offset=34,
                                                value=Name(lineno=31, col_offset=19, end_lineno=31, end_col_offset=25, id='fields', ctx=Load()),
                                                attr='Datetime',
                                                ctx=Load(),
                                            ),
                                            attr='to_string',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Call(
                                                lineno=32,
                                                col_offset=16,
                                                end_lineno=32,
                                                end_col_offset=72,
                                                func=Attribute(
                                                    lineno=32,
                                                    col_offset=16,
                                                    end_lineno=32,
                                                    end_col_offset=67,
                                                    value=Call(
                                                        lineno=32,
                                                        col_offset=16,
                                                        end_lineno=32,
                                                        end_col_offset=56,
                                                        func=Attribute(
                                                            lineno=32,
                                                            col_offset=16,
                                                            end_lineno=32,
                                                            end_col_offset=27,
                                                            value=Name(lineno=32, col_offset=16, end_lineno=32, end_col_offset=18, id='tz', ctx=Load()),
                                                            attr='localize',
                                                            ctx=Load(),
                                                        ),
                                                        args=[
                                                            Call(
                                                                lineno=32,
                                                                col_offset=28,
                                                                end_lineno=32,
                                                                end_col_offset=55,
                                                                func=Attribute(
                                                                    lineno=32,
                                                                    col_offset=28,
                                                                    end_lineno=32,
                                                                    end_col_offset=44,
                                                                    value=Name(lineno=32, col_offset=28, end_lineno=32, end_col_offset=36, id='datetime', ctx=Load()),
                                                                    attr='combine',
                                                                    ctx=Load(),
                                                                ),
                                                                args=[
                                                                    Name(lineno=32, col_offset=45, end_lineno=32, end_col_offset=48, id='day', ctx=Load()),
                                                                    Name(lineno=32, col_offset=50, end_lineno=32, end_col_offset=54, id='time', ctx=Load()),
                                                                ],
                                                                keywords=[],
                                                            ),
                                                        ],
                                                        keywords=[],
                                                    ),
                                                    attr='astimezone',
                                                    ctx=Load(),
                                                ),
                                                args=[Name(lineno=32, col_offset=68, end_lineno=32, end_col_offset=71, id='utc', ctx=Load())],
                                                keywords=[],
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                ),
                            ],
                            decorator_list=[],
                            returns=None,
                            type_comment=None,
                        ),
                        Assign(
                            lineno=35,
                            col_offset=8,
                            end_lineno=35,
                            end_col_offset=66,
                            targets=[Name(lineno=35, col_offset=8, end_lineno=35, end_col_offset=18, id='start_time', ctx=Store())],
                            value=Call(
                                lineno=35,
                                col_offset=21,
                                end_lineno=35,
                                end_col_offset=66,
                                func=Name(lineno=35, col_offset=21, end_lineno=35, end_col_offset=48, id='time_to_string_utc_datetime', ctx=Load()),
                                args=[
                                    Call(
                                        lineno=35,
                                        col_offset=49,
                                        end_lineno=35,
                                        end_col_offset=65,
                                        func=Name(lineno=35, col_offset=49, end_lineno=35, end_col_offset=53, id='time', ctx=Load()),
                                        args=[
                                            Constant(lineno=35, col_offset=54, end_lineno=35, end_col_offset=56, value=10, kind=None),
                                            Constant(lineno=35, col_offset=58, end_lineno=35, end_col_offset=60, value=43, kind=None),
                                            Constant(lineno=35, col_offset=62, end_lineno=35, end_col_offset=64, value=22, kind=None),
                                        ],
                                        keywords=[],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=36,
                            col_offset=8,
                            end_lineno=36,
                            end_col_offset=64,
                            targets=[Name(lineno=36, col_offset=8, end_lineno=36, end_col_offset=16, id='end_time', ctx=Store())],
                            value=Call(
                                lineno=36,
                                col_offset=19,
                                end_lineno=36,
                                end_col_offset=64,
                                func=Name(lineno=36, col_offset=19, end_lineno=36, end_col_offset=46, id='time_to_string_utc_datetime', ctx=Load()),
                                args=[
                                    Call(
                                        lineno=36,
                                        col_offset=47,
                                        end_lineno=36,
                                        end_col_offset=63,
                                        func=Name(lineno=36, col_offset=47, end_lineno=36, end_col_offset=51, id='time', ctx=Load()),
                                        args=[
                                            Constant(lineno=36, col_offset=52, end_lineno=36, end_col_offset=54, value=10, kind=None),
                                            Constant(lineno=36, col_offset=56, end_lineno=36, end_col_offset=58, value=56, kind=None),
                                            Constant(lineno=36, col_offset=60, end_lineno=36, end_col_offset=62, value=22, kind=None),
                                        ],
                                        keywords=[],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=38,
                            col_offset=8,
                            end_lineno=38,
                            end_col_offset=94,
                            value=Call(
                                lineno=38,
                                col_offset=8,
                                end_lineno=38,
                                end_col_offset=94,
                                func=Attribute(
                                    lineno=38,
                                    col_offset=8,
                                    end_lineno=38,
                                    end_col_offset=37,
                                    value=Name(lineno=38, col_offset=8, end_lineno=38, end_col_offset=12, id='self', ctx=Load()),
                                    attr='create_productivity_line',
                                    ctx=Load(),
                                ),
                                args=[
                                    Call(
                                        lineno=38,
                                        col_offset=38,
                                        end_lineno=38,
                                        end_col_offset=71,
                                        func=Attribute(
                                            lineno=38,
                                            col_offset=38,
                                            end_lineno=38,
                                            end_col_offset=50,
                                            value=Attribute(
                                                lineno=38,
                                                col_offset=38,
                                                end_lineno=38,
                                                end_col_offset=46,
                                                value=Name(lineno=38, col_offset=38, end_lineno=38, end_col_offset=42, id='self', ctx=Load()),
                                                attr='env',
                                                ctx=Load(),
                                            ),
                                            attr='ref',
                                            ctx=Load(),
                                        ),
                                        args=[Constant(lineno=38, col_offset=51, end_lineno=38, end_col_offset=70, value='mrp.block_reason7', kind=None)],
                                        keywords=[],
                                    ),
                                    Name(lineno=38, col_offset=73, end_lineno=38, end_col_offset=83, id='start_time', ctx=Load()),
                                    Name(lineno=38, col_offset=85, end_lineno=38, end_col_offset=93, id='end_time', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=42,
                            col_offset=8,
                            end_lineno=42,
                            end_col_offset=65,
                            targets=[Name(lineno=42, col_offset=8, end_lineno=42, end_col_offset=18, id='start_time', ctx=Store())],
                            value=Call(
                                lineno=42,
                                col_offset=21,
                                end_lineno=42,
                                end_col_offset=65,
                                func=Name(lineno=42, col_offset=21, end_lineno=42, end_col_offset=48, id='time_to_string_utc_datetime', ctx=Load()),
                                args=[
                                    Call(
                                        lineno=42,
                                        col_offset=49,
                                        end_lineno=42,
                                        end_col_offset=64,
                                        func=Name(lineno=42, col_offset=49, end_lineno=42, end_col_offset=53, id='time', ctx=Load()),
                                        args=[
                                            Constant(lineno=42, col_offset=54, end_lineno=42, end_col_offset=56, value=10, kind=None),
                                            Constant(lineno=42, col_offset=58, end_lineno=42, end_col_offset=60, value=47, kind=None),
                                            Constant(lineno=42, col_offset=62, end_lineno=42, end_col_offset=63, value=8, kind=None),
                                        ],
                                        keywords=[],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=43,
                            col_offset=8,
                            end_lineno=43,
                            end_col_offset=112,
                            targets=[Name(lineno=43, col_offset=8, end_lineno=43, end_col_offset=33, id='workcenter_productivity_1', ctx=Store())],
                            value=Call(
                                lineno=43,
                                col_offset=36,
                                end_lineno=43,
                                end_col_offset=112,
                                func=Attribute(
                                    lineno=43,
                                    col_offset=36,
                                    end_lineno=43,
                                    end_col_offset=65,
                                    value=Name(lineno=43, col_offset=36, end_lineno=43, end_col_offset=40, id='self', ctx=Load()),
                                    attr='create_productivity_line',
                                    ctx=Load(),
                                ),
                                args=[
                                    Call(
                                        lineno=43,
                                        col_offset=66,
                                        end_lineno=43,
                                        end_col_offset=99,
                                        func=Attribute(
                                            lineno=43,
                                            col_offset=66,
                                            end_lineno=43,
                                            end_col_offset=78,
                                            value=Attribute(
                                                lineno=43,
                                                col_offset=66,
                                                end_lineno=43,
                                                end_col_offset=74,
                                                value=Name(lineno=43, col_offset=66, end_lineno=43, end_col_offset=70, id='self', ctx=Load()),
                                                attr='env',
                                                ctx=Load(),
                                            ),
                                            attr='ref',
                                            ctx=Load(),
                                        ),
                                        args=[Constant(lineno=43, col_offset=79, end_lineno=43, end_col_offset=98, value='mrp.block_reason0', kind=None)],
                                        keywords=[],
                                    ),
                                    Name(lineno=43, col_offset=101, end_lineno=43, end_col_offset=111, id='start_time', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=44,
                            col_offset=8,
                            end_lineno=44,
                            end_col_offset=106,
                            value=Call(
                                lineno=44,
                                col_offset=8,
                                end_lineno=44,
                                end_col_offset=106,
                                func=Attribute(
                                    lineno=44,
                                    col_offset=8,
                                    end_lineno=44,
                                    end_col_offset=24,
                                    value=Name(lineno=44, col_offset=8, end_lineno=44, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=44,
                                        col_offset=25,
                                        end_lineno=44,
                                        end_col_offset=56,
                                        value=Attribute(
                                            lineno=44,
                                            col_offset=25,
                                            end_lineno=44,
                                            end_col_offset=42,
                                            value=Name(lineno=44, col_offset=25, end_lineno=44, end_col_offset=29, id='self', ctx=Load()),
                                            attr='workcenter_1',
                                            ctx=Load(),
                                        ),
                                        attr='working_state',
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=44, col_offset=58, end_lineno=44, end_col_offset=67, value='blocked', kind=None),
                                    Constant(lineno=44, col_offset=69, end_lineno=44, end_col_offset=105, value='Wrong working state of workcenter.', kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=47,
                            col_offset=8,
                            end_lineno=47,
                            end_col_offset=64,
                            targets=[Name(lineno=47, col_offset=8, end_lineno=47, end_col_offset=16, id='end_time', ctx=Store())],
                            value=Call(
                                lineno=47,
                                col_offset=19,
                                end_lineno=47,
                                end_col_offset=64,
                                func=Name(lineno=47, col_offset=19, end_lineno=47, end_col_offset=46, id='time_to_string_utc_datetime', ctx=Load()),
                                args=[
                                    Call(
                                        lineno=47,
                                        col_offset=47,
                                        end_lineno=47,
                                        end_col_offset=63,
                                        func=Name(lineno=47, col_offset=47, end_lineno=47, end_col_offset=51, id='time', ctx=Load()),
                                        args=[
                                            Constant(lineno=47, col_offset=52, end_lineno=47, end_col_offset=54, value=10, kind=None),
                                            Constant(lineno=47, col_offset=56, end_lineno=47, end_col_offset=58, value=48, kind=None),
                                            Constant(lineno=47, col_offset=60, end_lineno=47, end_col_offset=62, value=39, kind=None),
                                        ],
                                        keywords=[],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=48,
                            col_offset=8,
                            end_lineno=48,
                            end_col_offset=63,
                            value=Call(
                                lineno=48,
                                col_offset=8,
                                end_lineno=48,
                                end_col_offset=63,
                                func=Attribute(
                                    lineno=48,
                                    col_offset=8,
                                    end_lineno=48,
                                    end_col_offset=39,
                                    value=Name(lineno=48, col_offset=8, end_lineno=48, end_col_offset=33, id='workcenter_productivity_1', ctx=Load()),
                                    attr='write',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=48,
                                        col_offset=40,
                                        end_lineno=48,
                                        end_col_offset=62,
                                        keys=[Constant(lineno=48, col_offset=41, end_lineno=48, end_col_offset=51, value='date_end', kind=None)],
                                        values=[Name(lineno=48, col_offset=53, end_lineno=48, end_col_offset=61, id='end_time', ctx=Load())],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=49,
                            col_offset=8,
                            end_lineno=49,
                            end_col_offset=105,
                            value=Call(
                                lineno=49,
                                col_offset=8,
                                end_lineno=49,
                                end_col_offset=105,
                                func=Attribute(
                                    lineno=49,
                                    col_offset=8,
                                    end_lineno=49,
                                    end_col_offset=24,
                                    value=Name(lineno=49, col_offset=8, end_lineno=49, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=49,
                                        col_offset=25,
                                        end_lineno=49,
                                        end_col_offset=56,
                                        value=Attribute(
                                            lineno=49,
                                            col_offset=25,
                                            end_lineno=49,
                                            end_col_offset=42,
                                            value=Name(lineno=49, col_offset=25, end_lineno=49, end_col_offset=29, id='self', ctx=Load()),
                                            attr='workcenter_1',
                                            ctx=Load(),
                                        ),
                                        attr='working_state',
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=49, col_offset=58, end_lineno=49, end_col_offset=66, value='normal', kind=None),
                                    Constant(lineno=49, col_offset=68, end_lineno=49, end_col_offset=104, value='Wrong working state of workcenter.', kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=52,
                            col_offset=8,
                            end_lineno=52,
                            end_col_offset=66,
                            targets=[Name(lineno=52, col_offset=8, end_lineno=52, end_col_offset=18, id='start_time', ctx=Store())],
                            value=Call(
                                lineno=52,
                                col_offset=21,
                                end_lineno=52,
                                end_col_offset=66,
                                func=Name(lineno=52, col_offset=21, end_lineno=52, end_col_offset=48, id='time_to_string_utc_datetime', ctx=Load()),
                                args=[
                                    Call(
                                        lineno=52,
                                        col_offset=49,
                                        end_lineno=52,
                                        end_col_offset=65,
                                        func=Name(lineno=52, col_offset=49, end_lineno=52, end_col_offset=53, id='time', ctx=Load()),
                                        args=[
                                            Constant(lineno=52, col_offset=54, end_lineno=52, end_col_offset=56, value=10, kind=None),
                                            Constant(lineno=52, col_offset=58, end_lineno=52, end_col_offset=60, value=48, kind=None),
                                            Constant(lineno=52, col_offset=62, end_lineno=52, end_col_offset=64, value=38, kind=None),
                                        ],
                                        keywords=[],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=53,
                            col_offset=8,
                            end_lineno=53,
                            end_col_offset=64,
                            targets=[Name(lineno=53, col_offset=8, end_lineno=53, end_col_offset=16, id='end_time', ctx=Store())],
                            value=Call(
                                lineno=53,
                                col_offset=19,
                                end_lineno=53,
                                end_col_offset=64,
                                func=Name(lineno=53, col_offset=19, end_lineno=53, end_col_offset=46, id='time_to_string_utc_datetime', ctx=Load()),
                                args=[
                                    Call(
                                        lineno=53,
                                        col_offset=47,
                                        end_lineno=53,
                                        end_col_offset=63,
                                        func=Name(lineno=53, col_offset=47, end_lineno=53, end_col_offset=51, id='time', ctx=Load()),
                                        args=[
                                            Constant(lineno=53, col_offset=52, end_lineno=53, end_col_offset=54, value=10, kind=None),
                                            Constant(lineno=53, col_offset=56, end_lineno=53, end_col_offset=58, value=49, kind=None),
                                            Constant(lineno=53, col_offset=60, end_lineno=53, end_col_offset=62, value=58, kind=None),
                                        ],
                                        keywords=[],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=54,
                            col_offset=8,
                            end_lineno=54,
                            end_col_offset=94,
                            value=Call(
                                lineno=54,
                                col_offset=8,
                                end_lineno=54,
                                end_col_offset=94,
                                func=Attribute(
                                    lineno=54,
                                    col_offset=8,
                                    end_lineno=54,
                                    end_col_offset=37,
                                    value=Name(lineno=54, col_offset=8, end_lineno=54, end_col_offset=12, id='self', ctx=Load()),
                                    attr='create_productivity_line',
                                    ctx=Load(),
                                ),
                                args=[
                                    Call(
                                        lineno=54,
                                        col_offset=38,
                                        end_lineno=54,
                                        end_col_offset=71,
                                        func=Attribute(
                                            lineno=54,
                                            col_offset=38,
                                            end_lineno=54,
                                            end_col_offset=50,
                                            value=Attribute(
                                                lineno=54,
                                                col_offset=38,
                                                end_lineno=54,
                                                end_col_offset=46,
                                                value=Name(lineno=54, col_offset=38, end_lineno=54, end_col_offset=42, id='self', ctx=Load()),
                                                attr='env',
                                                ctx=Load(),
                                            ),
                                            attr='ref',
                                            ctx=Load(),
                                        ),
                                        args=[Constant(lineno=54, col_offset=51, end_lineno=54, end_col_offset=70, value='mrp.block_reason5', kind=None)],
                                        keywords=[],
                                    ),
                                    Name(lineno=54, col_offset=73, end_lineno=54, end_col_offset=83, id='start_time', ctx=Load()),
                                    Name(lineno=54, col_offset=85, end_lineno=54, end_col_offset=93, id='end_time', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=56,
                            col_offset=8,
                            end_lineno=56,
                            end_col_offset=66,
                            targets=[Name(lineno=56, col_offset=8, end_lineno=56, end_col_offset=18, id='start_time', ctx=Store())],
                            value=Call(
                                lineno=56,
                                col_offset=21,
                                end_lineno=56,
                                end_col_offset=66,
                                func=Name(lineno=56, col_offset=21, end_lineno=56, end_col_offset=48, id='time_to_string_utc_datetime', ctx=Load()),
                                args=[
                                    Call(
                                        lineno=56,
                                        col_offset=49,
                                        end_lineno=56,
                                        end_col_offset=65,
                                        func=Name(lineno=56, col_offset=49, end_lineno=56, end_col_offset=53, id='time', ctx=Load()),
                                        args=[
                                            Constant(lineno=56, col_offset=54, end_lineno=56, end_col_offset=56, value=10, kind=None),
                                            Constant(lineno=56, col_offset=58, end_lineno=56, end_col_offset=60, value=50, kind=None),
                                            Constant(lineno=56, col_offset=62, end_lineno=56, end_col_offset=64, value=22, kind=None),
                                        ],
                                        keywords=[],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=57,
                            col_offset=8,
                            end_lineno=57,
                            end_col_offset=64,
                            targets=[Name(lineno=57, col_offset=8, end_lineno=57, end_col_offset=16, id='end_time', ctx=Store())],
                            value=Call(
                                lineno=57,
                                col_offset=19,
                                end_lineno=57,
                                end_col_offset=64,
                                func=Name(lineno=57, col_offset=19, end_lineno=57, end_col_offset=46, id='time_to_string_utc_datetime', ctx=Load()),
                                args=[
                                    Call(
                                        lineno=57,
                                        col_offset=47,
                                        end_lineno=57,
                                        end_col_offset=63,
                                        func=Name(lineno=57, col_offset=47, end_lineno=57, end_col_offset=51, id='time', ctx=Load()),
                                        args=[
                                            Constant(lineno=57, col_offset=52, end_lineno=57, end_col_offset=54, value=10, kind=None),
                                            Constant(lineno=57, col_offset=56, end_lineno=57, end_col_offset=58, value=53, kind=None),
                                            Constant(lineno=57, col_offset=60, end_lineno=57, end_col_offset=62, value=22, kind=None),
                                        ],
                                        keywords=[],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=58,
                            col_offset=8,
                            end_lineno=58,
                            end_col_offset=94,
                            value=Call(
                                lineno=58,
                                col_offset=8,
                                end_lineno=58,
                                end_col_offset=94,
                                func=Attribute(
                                    lineno=58,
                                    col_offset=8,
                                    end_lineno=58,
                                    end_col_offset=37,
                                    value=Name(lineno=58, col_offset=8, end_lineno=58, end_col_offset=12, id='self', ctx=Load()),
                                    attr='create_productivity_line',
                                    ctx=Load(),
                                ),
                                args=[
                                    Call(
                                        lineno=58,
                                        col_offset=38,
                                        end_lineno=58,
                                        end_col_offset=71,
                                        func=Attribute(
                                            lineno=58,
                                            col_offset=38,
                                            end_lineno=58,
                                            end_col_offset=50,
                                            value=Attribute(
                                                lineno=58,
                                                col_offset=38,
                                                end_lineno=58,
                                                end_col_offset=46,
                                                value=Name(lineno=58, col_offset=38, end_lineno=58, end_col_offset=42, id='self', ctx=Load()),
                                                attr='env',
                                                ctx=Load(),
                                            ),
                                            attr='ref',
                                            ctx=Load(),
                                        ),
                                        args=[Constant(lineno=58, col_offset=51, end_lineno=58, end_col_offset=70, value='mrp.block_reason4', kind=None)],
                                        keywords=[],
                                    ),
                                    Name(lineno=58, col_offset=73, end_lineno=58, end_col_offset=83, id='start_time', ctx=Load()),
                                    Name(lineno=58, col_offset=85, end_lineno=58, end_col_offset=93, id='end_time', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=61,
                            col_offset=8,
                            end_lineno=61,
                            end_col_offset=69,
                            targets=[Name(lineno=61, col_offset=8, end_lineno=61, end_col_offset=28, id='blocked_time_in_hour', ctx=Store())],
                            value=Call(
                                lineno=61,
                                col_offset=31,
                                end_lineno=61,
                                end_col_offset=69,
                                func=Name(lineno=61, col_offset=31, end_lineno=61, end_col_offset=36, id='round', ctx=Load()),
                                args=[
                                    BinOp(
                                        lineno=61,
                                        col_offset=38,
                                        end_lineno=61,
                                        end_col_offset=64,
                                        left=BinOp(
                                            lineno=61,
                                            col_offset=39,
                                            end_lineno=61,
                                            end_col_offset=56,
                                            left=BinOp(
                                                lineno=61,
                                                col_offset=39,
                                                end_lineno=61,
                                                end_col_offset=49,
                                                left=Constant(lineno=61, col_offset=39, end_lineno=61, end_col_offset=43, value=1.33, kind=None),
                                                op=Add(),
                                                right=Constant(lineno=61, col_offset=46, end_lineno=61, end_col_offset=49, value=3.0, kind=None),
                                            ),
                                            op=Add(),
                                            right=Constant(lineno=61, col_offset=52, end_lineno=61, end_col_offset=56, value=1.52, kind=None),
                                        ),
                                        op=Div(),
                                        right=Constant(lineno=61, col_offset=60, end_lineno=61, end_col_offset=64, value=60.0, kind=None),
                                    ),
                                    Constant(lineno=61, col_offset=67, end_lineno=61, end_col_offset=68, value=2, kind=None),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=63,
                            col_offset=8,
                            end_lineno=63,
                            end_col_offset=57,
                            targets=[Name(lineno=63, col_offset=8, end_lineno=63, end_col_offset=31, id='productive_time_in_hour', ctx=Store())],
                            value=Call(
                                lineno=63,
                                col_offset=34,
                                end_lineno=63,
                                end_col_offset=57,
                                func=Name(lineno=63, col_offset=34, end_lineno=63, end_col_offset=39, id='round', ctx=Load()),
                                args=[
                                    BinOp(
                                        lineno=63,
                                        col_offset=41,
                                        end_lineno=63,
                                        end_col_offset=52,
                                        left=Constant(lineno=63, col_offset=41, end_lineno=63, end_col_offset=45, value=13.0, kind=None),
                                        op=Div(),
                                        right=Constant(lineno=63, col_offset=48, end_lineno=63, end_col_offset=52, value=60.0, kind=None),
                                    ),
                                    Constant(lineno=63, col_offset=55, end_lineno=63, end_col_offset=56, value=2, kind=None),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=66,
                            col_offset=8,
                            end_lineno=66,
                            end_col_offset=113,
                            value=Call(
                                lineno=66,
                                col_offset=8,
                                end_lineno=66,
                                end_col_offset=113,
                                func=Attribute(
                                    lineno=66,
                                    col_offset=8,
                                    end_lineno=66,
                                    end_col_offset=24,
                                    value=Name(lineno=66, col_offset=8, end_lineno=66, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=66,
                                        col_offset=25,
                                        end_lineno=66,
                                        end_col_offset=55,
                                        value=Attribute(
                                            lineno=66,
                                            col_offset=25,
                                            end_lineno=66,
                                            end_col_offset=42,
                                            value=Name(lineno=66, col_offset=25, end_lineno=66, end_col_offset=29, id='self', ctx=Load()),
                                            attr='workcenter_1',
                                            ctx=Load(),
                                        ),
                                        attr='blocked_time',
                                        ctx=Load(),
                                    ),
                                    Name(lineno=66, col_offset=57, end_lineno=66, end_col_offset=77, id='blocked_time_in_hour', ctx=Load()),
                                    Constant(lineno=66, col_offset=79, end_lineno=66, end_col_offset=112, value='Wrong block time on workcenter.', kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=67,
                            col_offset=8,
                            end_lineno=67,
                            end_col_offset=124,
                            value=Call(
                                lineno=67,
                                col_offset=8,
                                end_lineno=67,
                                end_col_offset=124,
                                func=Attribute(
                                    lineno=67,
                                    col_offset=8,
                                    end_lineno=67,
                                    end_col_offset=24,
                                    value=Name(lineno=67, col_offset=8, end_lineno=67, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=67,
                                        col_offset=25,
                                        end_lineno=67,
                                        end_col_offset=58,
                                        value=Attribute(
                                            lineno=67,
                                            col_offset=25,
                                            end_lineno=67,
                                            end_col_offset=42,
                                            value=Name(lineno=67, col_offset=25, end_lineno=67, end_col_offset=29, id='self', ctx=Load()),
                                            attr='workcenter_1',
                                            ctx=Load(),
                                        ),
                                        attr='productive_time',
                                        ctx=Load(),
                                    ),
                                    Name(lineno=67, col_offset=60, end_lineno=67, end_col_offset=83, id='productive_time_in_hour', ctx=Load()),
                                    Constant(lineno=67, col_offset=85, end_lineno=67, end_col_offset=123, value='Wrong productive time on workcenter.', kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=70,
                            col_offset=8,
                            end_lineno=70,
                            end_col_offset=117,
                            targets=[Name(lineno=70, col_offset=8, end_lineno=70, end_col_offset=20, id='computed_oee', ctx=Store())],
                            value=Call(
                                lineno=70,
                                col_offset=23,
                                end_lineno=70,
                                end_col_offset=117,
                                func=Name(lineno=70, col_offset=23, end_lineno=70, end_col_offset=28, id='round', ctx=Load()),
                                args=[
                                    BinOp(
                                        lineno=70,
                                        col_offset=30,
                                        end_lineno=70,
                                        end_col_offset=112,
                                        left=BinOp(
                                            lineno=70,
                                            col_offset=31,
                                            end_lineno=70,
                                            end_col_offset=62,
                                            left=Name(lineno=70, col_offset=31, end_lineno=70, end_col_offset=54, id='productive_time_in_hour', ctx=Load()),
                                            op=Mult(),
                                            right=Constant(lineno=70, col_offset=57, end_lineno=70, end_col_offset=62, value=100.0, kind=None),
                                        ),
                                        op=Div(),
                                        right=BinOp(
                                            lineno=70,
                                            col_offset=65,
                                            end_lineno=70,
                                            end_col_offset=111,
                                            left=Name(lineno=70, col_offset=65, end_lineno=70, end_col_offset=88, id='productive_time_in_hour', ctx=Load()),
                                            op=Add(),
                                            right=Name(lineno=70, col_offset=91, end_lineno=70, end_col_offset=111, id='blocked_time_in_hour', ctx=Load()),
                                        ),
                                    ),
                                    Constant(lineno=70, col_offset=115, end_lineno=70, end_col_offset=116, value=2, kind=None),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=71,
                            col_offset=8,
                            end_lineno=71,
                            end_col_offset=89,
                            value=Call(
                                lineno=71,
                                col_offset=8,
                                end_lineno=71,
                                end_col_offset=89,
                                func=Attribute(
                                    lineno=71,
                                    col_offset=8,
                                    end_lineno=71,
                                    end_col_offset=24,
                                    value=Name(lineno=71, col_offset=8, end_lineno=71, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=71,
                                        col_offset=25,
                                        end_lineno=71,
                                        end_col_offset=46,
                                        value=Attribute(
                                            lineno=71,
                                            col_offset=25,
                                            end_lineno=71,
                                            end_col_offset=42,
                                            value=Name(lineno=71, col_offset=25, end_lineno=71, end_col_offset=29, id='self', ctx=Load()),
                                            attr='workcenter_1',
                                            ctx=Load(),
                                        ),
                                        attr='oee',
                                        ctx=Load(),
                                    ),
                                    Name(lineno=71, col_offset=48, end_lineno=71, end_col_offset=60, id='computed_oee', ctx=Load()),
                                    Constant(lineno=71, col_offset=62, end_lineno=71, end_col_offset=88, value='Wrong oee on workcenter.', kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
