Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=29,
            module='odoo.tests',
            names=[alias(name='tagged', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=5,
            col_offset=0,
            end_lineno=5,
            end_col_offset=45,
            module='odoo.tests.common',
            names=[alias(name='TransactionCase', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=6,
            col_offset=0,
            end_lineno=6,
            end_col_offset=43,
            module='odoo.tools',
            names=[alias(name='transpile_javascript', asname=None)],
            level=0,
        ),
        ClassDef(
            lineno=10,
            col_offset=0,
            end_lineno=418,
            end_col_offset=49,
            name='TestJsTranspiler',
            bases=[Name(lineno=10, col_offset=23, end_lineno=10, end_col_offset=38, id='TransactionCase', ctx=Load())],
            keywords=[],
            body=[
                Assign(
                    lineno=11,
                    col_offset=4,
                    end_lineno=11,
                    end_col_offset=18,
                    targets=[Name(lineno=11, col_offset=4, end_lineno=11, end_col_offset=11, id='maxDiff', ctx=Store())],
                    value=Constant(lineno=11, col_offset=14, end_lineno=11, end_col_offset=18, value=None, kind=None),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=13,
                    col_offset=4,
                    end_lineno=29,
                    end_col_offset=49,
                    name='test_01_alias',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=13, col_offset=22, end_lineno=13, end_col_offset=26, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=14,
                            col_offset=8,
                            end_lineno=14,
                            end_col_offset=80,
                            targets=[Name(lineno=14, col_offset=8, end_lineno=14, end_col_offset=21, id='input_content', ctx=Store())],
                            value=Constant(lineno=14, col_offset=24, end_lineno=14, end_col_offset=80, value='/** @odoo-module alias=test_assetsbundle.Alias **/', kind=None),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=15,
                            col_offset=8,
                            end_lineno=15,
                            end_col_offset=94,
                            targets=[Name(lineno=15, col_offset=8, end_lineno=15, end_col_offset=14, id='result', ctx=Store())],
                            value=Call(
                                lineno=15,
                                col_offset=17,
                                end_lineno=15,
                                end_col_offset=94,
                                func=Name(lineno=15, col_offset=17, end_lineno=15, end_col_offset=37, id='transpile_javascript', ctx=Load()),
                                args=[
                                    Constant(lineno=15, col_offset=38, end_lineno=15, end_col_offset=78, value='/test_assetsbundle/static/src/alias.js', kind=None),
                                    Name(lineno=15, col_offset=80, end_lineno=15, end_col_offset=93, id='input_content', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=17,
                            col_offset=8,
                            end_lineno=27,
                            end_col_offset=3,
                            targets=[Name(lineno=17, col_offset=8, end_lineno=17, end_col_offset=23, id='expected_result', ctx=Store())],
                            value=Constant(lineno=17, col_offset=26, end_lineno=27, end_col_offset=3, value='odoo.define(\'@test_assetsbundle/alias\', async function (require) {\n\'use strict\';\nlet __exports = {};\n/** @odoo-module alias=test_assetsbundle.Alias **/\nreturn __exports;\n});\n\nodoo.define(`test_assetsbundle.Alias`, async function(require) {\n                        return require(\'@test_assetsbundle/alias\')[Symbol.for("default")];\n                        });\n', kind=None),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=29,
                            col_offset=8,
                            end_lineno=29,
                            end_col_offset=49,
                            value=Call(
                                lineno=29,
                                col_offset=8,
                                end_lineno=29,
                                end_col_offset=49,
                                func=Attribute(
                                    lineno=29,
                                    col_offset=8,
                                    end_lineno=29,
                                    end_col_offset=24,
                                    value=Name(lineno=29, col_offset=8, end_lineno=29, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=29, col_offset=25, end_lineno=29, end_col_offset=31, id='result', ctx=Load()),
                                    Name(lineno=29, col_offset=33, end_lineno=29, end_col_offset=48, id='expected_result', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=31,
                    col_offset=4,
                    end_lineno=81,
                    end_col_offset=49,
                    name='test_02_default',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=31, col_offset=24, end_lineno=31, end_col_offset=28, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=32,
                            col_offset=8,
                            end_lineno=32,
                            end_col_offset=94,
                            targets=[Name(lineno=32, col_offset=8, end_lineno=32, end_col_offset=21, id='input_content', ctx=Store())],
                            value=Constant(lineno=32, col_offset=24, end_lineno=32, end_col_offset=94, value='/** @odoo-module alias=test_assetsbundle.Alias default=False **/', kind=None),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=33,
                            col_offset=8,
                            end_lineno=33,
                            end_col_offset=94,
                            targets=[Name(lineno=33, col_offset=8, end_lineno=33, end_col_offset=14, id='result', ctx=Store())],
                            value=Call(
                                lineno=33,
                                col_offset=17,
                                end_lineno=33,
                                end_col_offset=94,
                                func=Name(lineno=33, col_offset=17, end_lineno=33, end_col_offset=37, id='transpile_javascript', ctx=Load()),
                                args=[
                                    Constant(lineno=33, col_offset=38, end_lineno=33, end_col_offset=78, value='/test_assetsbundle/static/src/alias.js', kind=None),
                                    Name(lineno=33, col_offset=80, end_lineno=33, end_col_offset=93, id='input_content', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=35,
                            col_offset=8,
                            end_lineno=45,
                            end_col_offset=3,
                            targets=[Name(lineno=35, col_offset=8, end_lineno=35, end_col_offset=23, id='expected_result', ctx=Store())],
                            value=Constant(lineno=35, col_offset=26, end_lineno=45, end_col_offset=3, value="odoo.define('@test_assetsbundle/alias', async function (require) {\n'use strict';\nlet __exports = {};\n/** @odoo-module alias=test_assetsbundle.Alias default=False **/\nreturn __exports;\n});\n\nodoo.define(`test_assetsbundle.Alias`, async function(require) {\n                        return require('@test_assetsbundle/alias');\n                        });\n", kind=None),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=47,
                            col_offset=8,
                            end_lineno=47,
                            end_col_offset=49,
                            value=Call(
                                lineno=47,
                                col_offset=8,
                                end_lineno=47,
                                end_col_offset=49,
                                func=Attribute(
                                    lineno=47,
                                    col_offset=8,
                                    end_lineno=47,
                                    end_col_offset=24,
                                    value=Name(lineno=47, col_offset=8, end_lineno=47, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=47, col_offset=25, end_lineno=47, end_col_offset=31, id='result', ctx=Load()),
                                    Name(lineno=47, col_offset=33, end_lineno=47, end_col_offset=48, id='expected_result', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=49,
                            col_offset=8,
                            end_lineno=49,
                            end_col_offset=90,
                            targets=[Name(lineno=49, col_offset=8, end_lineno=49, end_col_offset=21, id='input_content', ctx=Store())],
                            value=Constant(lineno=49, col_offset=24, end_lineno=49, end_col_offset=90, value='/** @odoo-module alias=test_assetsbundle.Alias default=0 **/', kind=None),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=50,
                            col_offset=8,
                            end_lineno=50,
                            end_col_offset=94,
                            targets=[Name(lineno=50, col_offset=8, end_lineno=50, end_col_offset=14, id='result', ctx=Store())],
                            value=Call(
                                lineno=50,
                                col_offset=17,
                                end_lineno=50,
                                end_col_offset=94,
                                func=Name(lineno=50, col_offset=17, end_lineno=50, end_col_offset=37, id='transpile_javascript', ctx=Load()),
                                args=[
                                    Constant(lineno=50, col_offset=38, end_lineno=50, end_col_offset=78, value='/test_assetsbundle/static/src/alias.js', kind=None),
                                    Name(lineno=50, col_offset=80, end_lineno=50, end_col_offset=93, id='input_content', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=52,
                            col_offset=8,
                            end_lineno=62,
                            end_col_offset=3,
                            targets=[Name(lineno=52, col_offset=8, end_lineno=52, end_col_offset=23, id='expected_result', ctx=Store())],
                            value=Constant(lineno=52, col_offset=26, end_lineno=62, end_col_offset=3, value="odoo.define('@test_assetsbundle/alias', async function (require) {\n'use strict';\nlet __exports = {};\n/** @odoo-module alias=test_assetsbundle.Alias default=0 **/\nreturn __exports;\n});\n\nodoo.define(`test_assetsbundle.Alias`, async function(require) {\n                        return require('@test_assetsbundle/alias');\n                        });\n", kind=None),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=64,
                            col_offset=8,
                            end_lineno=64,
                            end_col_offset=49,
                            value=Call(
                                lineno=64,
                                col_offset=8,
                                end_lineno=64,
                                end_col_offset=49,
                                func=Attribute(
                                    lineno=64,
                                    col_offset=8,
                                    end_lineno=64,
                                    end_col_offset=24,
                                    value=Name(lineno=64, col_offset=8, end_lineno=64, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=64, col_offset=25, end_lineno=64, end_col_offset=31, id='result', ctx=Load()),
                                    Name(lineno=64, col_offset=33, end_lineno=64, end_col_offset=48, id='expected_result', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=66,
                            col_offset=8,
                            end_lineno=66,
                            end_col_offset=94,
                            targets=[Name(lineno=66, col_offset=8, end_lineno=66, end_col_offset=21, id='input_content', ctx=Store())],
                            value=Constant(lineno=66, col_offset=24, end_lineno=66, end_col_offset=94, value='/** @odoo-module alias=test_assetsbundle.Alias default=false **/', kind=None),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=67,
                            col_offset=8,
                            end_lineno=67,
                            end_col_offset=94,
                            targets=[Name(lineno=67, col_offset=8, end_lineno=67, end_col_offset=14, id='result', ctx=Store())],
                            value=Call(
                                lineno=67,
                                col_offset=17,
                                end_lineno=67,
                                end_col_offset=94,
                                func=Name(lineno=67, col_offset=17, end_lineno=67, end_col_offset=37, id='transpile_javascript', ctx=Load()),
                                args=[
                                    Constant(lineno=67, col_offset=38, end_lineno=67, end_col_offset=78, value='/test_assetsbundle/static/src/alias.js', kind=None),
                                    Name(lineno=67, col_offset=80, end_lineno=67, end_col_offset=93, id='input_content', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=69,
                            col_offset=8,
                            end_lineno=79,
                            end_col_offset=3,
                            targets=[Name(lineno=69, col_offset=8, end_lineno=69, end_col_offset=23, id='expected_result', ctx=Store())],
                            value=Constant(lineno=69, col_offset=26, end_lineno=79, end_col_offset=3, value="odoo.define('@test_assetsbundle/alias', async function (require) {\n'use strict';\nlet __exports = {};\n/** @odoo-module alias=test_assetsbundle.Alias default=false **/\nreturn __exports;\n});\n\nodoo.define(`test_assetsbundle.Alias`, async function(require) {\n                        return require('@test_assetsbundle/alias');\n                        });\n", kind=None),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=81,
                            col_offset=8,
                            end_lineno=81,
                            end_col_offset=49,
                            value=Call(
                                lineno=81,
                                col_offset=8,
                                end_lineno=81,
                                end_col_offset=49,
                                func=Attribute(
                                    lineno=81,
                                    col_offset=8,
                                    end_lineno=81,
                                    end_col_offset=24,
                                    value=Name(lineno=81, col_offset=8, end_lineno=81, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=81, col_offset=25, end_lineno=81, end_col_offset=31, id='result', ctx=Load()),
                                    Name(lineno=81, col_offset=33, end_lineno=81, end_col_offset=48, id='expected_result', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=83,
                    col_offset=4,
                    end_lineno=113,
                    end_col_offset=49,
                    name='test_03_classes',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=83, col_offset=24, end_lineno=83, end_col_offset=28, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=84,
                            col_offset=8,
                            end_lineno=93,
                            end_col_offset=3,
                            targets=[Name(lineno=84, col_offset=8, end_lineno=84, end_col_offset=21, id='input_content', ctx=Store())],
                            value=Constant(lineno=84, col_offset=24, end_lineno=93, end_col_offset=3, value='export default class Nice {}\n\nclass Vehicule {}\n\nexport class Car extends Vehicule {}\n\nexport class Boat extends Vehicule {}\n\nexport const Ferrari = class Ferrari extends Car {};\n', kind=None),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=94,
                            col_offset=8,
                            end_lineno=94,
                            end_col_offset=96,
                            targets=[Name(lineno=94, col_offset=8, end_lineno=94, end_col_offset=14, id='result', ctx=Store())],
                            value=Call(
                                lineno=94,
                                col_offset=17,
                                end_lineno=94,
                                end_col_offset=96,
                                func=Name(lineno=94, col_offset=17, end_lineno=94, end_col_offset=37, id='transpile_javascript', ctx=Load()),
                                args=[
                                    Constant(lineno=94, col_offset=38, end_lineno=94, end_col_offset=80, value='/test_assetsbundle/static/src/classes.js', kind=None),
                                    Name(lineno=94, col_offset=82, end_lineno=94, end_col_offset=95, id='input_content', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=96,
                            col_offset=8,
                            end_lineno=111,
                            end_col_offset=3,
                            targets=[Name(lineno=96, col_offset=8, end_lineno=96, end_col_offset=23, id='expected_result', ctx=Store())],
                            value=Constant(lineno=96, col_offset=26, end_lineno=111, end_col_offset=3, value='odoo.define(\'@test_assetsbundle/classes\', async function (require) {\n\'use strict\';\nlet __exports = {};\nconst Nice = __exports[Symbol.for("default")] = class Nice {}\n\nclass Vehicule {}\n\nconst Car = __exports.Car = class Car extends Vehicule {}\n\nconst Boat = __exports.Boat = class Boat extends Vehicule {}\n\nconst Ferrari = __exports.Ferrari = class Ferrari extends Car {};\n\nreturn __exports;\n});\n', kind=None),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=113,
                            col_offset=8,
                            end_lineno=113,
                            end_col_offset=49,
                            value=Call(
                                lineno=113,
                                col_offset=8,
                                end_lineno=113,
                                end_col_offset=49,
                                func=Attribute(
                                    lineno=113,
                                    col_offset=8,
                                    end_lineno=113,
                                    end_col_offset=24,
                                    value=Name(lineno=113, col_offset=8, end_lineno=113, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=113, col_offset=25, end_lineno=113, end_col_offset=31, id='result', ctx=Load()),
                                    Name(lineno=113, col_offset=33, end_lineno=113, end_col_offset=48, id='expected_result', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=115,
                    col_offset=4,
                    end_lineno=187,
                    end_col_offset=49,
                    name='test_04_comments',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=115, col_offset=25, end_lineno=115, end_col_offset=29, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=116,
                            col_offset=8,
                            end_lineno=146,
                            end_col_offset=3,
                            targets=[Name(lineno=116, col_offset=8, end_lineno=116, end_col_offset=21, id='input_content', ctx=Store())],
                            value=Constant(lineno=116, col_offset=24, end_lineno=146, end_col_offset=3, value='/**\n * This is a comment\n */\n\n/**\n * This isn\'t a string\n */\nexport class Test {\n  // This is a comment in a class\n}\n\n/* cool comment */ const a = 5; /* another cool comment */\n\nconst b = 5; // hello\n\n// another one\n\nconst y = "this is a /* nice string and should be kept */";\nconst z = "this is a /* nice string and should be kept";\nexport const x = "this is a // nice string and should be kept";\nconst w = "this is a */ nice string and should be kept";\n\n// This isn\'t a string\n/*\n  comments\n */\nconst aaa = "keep!";\n/*\n  comments\n */\n', kind=None),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=147,
                            col_offset=8,
                            end_lineno=147,
                            end_col_offset=97,
                            targets=[Name(lineno=147, col_offset=8, end_lineno=147, end_col_offset=14, id='result', ctx=Store())],
                            value=Call(
                                lineno=147,
                                col_offset=17,
                                end_lineno=147,
                                end_col_offset=97,
                                func=Name(lineno=147, col_offset=17, end_lineno=147, end_col_offset=37, id='transpile_javascript', ctx=Load()),
                                args=[
                                    Constant(lineno=147, col_offset=38, end_lineno=147, end_col_offset=81, value='/test_assetsbundle/static/src/comments.js', kind=None),
                                    Name(lineno=147, col_offset=83, end_lineno=147, end_col_offset=96, id='input_content', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=149,
                            col_offset=8,
                            end_lineno=185,
                            end_col_offset=3,
                            targets=[Name(lineno=149, col_offset=8, end_lineno=149, end_col_offset=23, id='expected_result', ctx=Store())],
                            value=Constant(lineno=149, col_offset=26, end_lineno=185, end_col_offset=3, value='odoo.define(\'@test_assetsbundle/comments\', async function (require) {\n\'use strict\';\nlet __exports = {};\n/**\n * This is a comment\n */\n\n/**\n * This isn\'t a string\n */\nconst Test = __exports.Test = class Test {\n  // This is a comment in a class\n}\n\n/* cool comment */ const a = 5; /* another cool comment */\n\nconst b = 5; // hello\n\n// another one\n\nconst y = "this is a /* nice string and should be kept */";\nconst z = "this is a /* nice string and should be kept";\nconst x = __exports.x = "this is a // nice string and should be kept";\nconst w = "this is a */ nice string and should be kept";\n\n// This isn\'t a string\n/*\n  comments\n */\nconst aaa = "keep!";\n/*\n  comments\n */\n\nreturn __exports;\n});\n', kind=None),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=187,
                            col_offset=8,
                            end_lineno=187,
                            end_col_offset=49,
                            value=Call(
                                lineno=187,
                                col_offset=8,
                                end_lineno=187,
                                end_col_offset=49,
                                func=Attribute(
                                    lineno=187,
                                    col_offset=8,
                                    end_lineno=187,
                                    end_col_offset=24,
                                    value=Name(lineno=187, col_offset=8, end_lineno=187, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=187, col_offset=25, end_lineno=187, end_col_offset=31, id='result', ctx=Load()),
                                    Name(lineno=187, col_offset=33, end_lineno=187, end_col_offset=48, id='expected_result', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=189,
                    col_offset=4,
                    end_lineno=233,
                    end_col_offset=49,
                    name='test_05_functions',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=189, col_offset=26, end_lineno=189, end_col_offset=30, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=190,
                            col_offset=8,
                            end_lineno=206,
                            end_col_offset=3,
                            targets=[Name(lineno=190, col_offset=8, end_lineno=190, end_col_offset=21, id='input_content', ctx=Store())],
                            value=Constant(lineno=190, col_offset=24, end_lineno=206, end_col_offset=3, value='export function sayHello() {\n  console.log("Hello");\n}\n\nexport function sayHelloWorld() {\n  console.log("Hello world");\n}\n\nexport async function sayAsyncHello() {\n  console.log("Hello Async");\n}\n\n\nexport default function sayHelloDefault() {\n  console.log("Hello Default");\n}\n', kind=None),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=207,
                            col_offset=8,
                            end_lineno=207,
                            end_col_offset=98,
                            targets=[Name(lineno=207, col_offset=8, end_lineno=207, end_col_offset=14, id='result', ctx=Store())],
                            value=Call(
                                lineno=207,
                                col_offset=17,
                                end_lineno=207,
                                end_col_offset=98,
                                func=Name(lineno=207, col_offset=17, end_lineno=207, end_col_offset=37, id='transpile_javascript', ctx=Load()),
                                args=[
                                    Constant(lineno=207, col_offset=38, end_lineno=207, end_col_offset=82, value='/test_assetsbundle/static/src/functions.js', kind=None),
                                    Name(lineno=207, col_offset=84, end_lineno=207, end_col_offset=97, id='input_content', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=209,
                            col_offset=8,
                            end_lineno=231,
                            end_col_offset=3,
                            targets=[Name(lineno=209, col_offset=8, end_lineno=209, end_col_offset=23, id='expected_result', ctx=Store())],
                            value=Constant(lineno=209, col_offset=26, end_lineno=231, end_col_offset=3, value='odoo.define(\'@test_assetsbundle/functions\', async function (require) {\n\'use strict\';\nlet __exports = {};\nconst sayHello = __exports.sayHello = function sayHello() {\n  console.log("Hello");\n}\n\nconst sayHelloWorld = __exports.sayHelloWorld = function sayHelloWorld() {\n  console.log("Hello world");\n}\n\nconst sayAsyncHello = __exports.sayAsyncHello = async function sayAsyncHello() {\n  console.log("Hello Async");\n}\n\n\nconst sayHelloDefault = __exports[Symbol.for("default")] = function sayHelloDefault() {\n  console.log("Hello Default");\n}\n\nreturn __exports;\n});\n', kind=None),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=233,
                            col_offset=8,
                            end_lineno=233,
                            end_col_offset=49,
                            value=Call(
                                lineno=233,
                                col_offset=8,
                                end_lineno=233,
                                end_col_offset=49,
                                func=Attribute(
                                    lineno=233,
                                    col_offset=8,
                                    end_lineno=233,
                                    end_col_offset=24,
                                    value=Name(lineno=233, col_offset=8, end_lineno=233, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=233, col_offset=25, end_lineno=233, end_col_offset=31, id='result', ctx=Load()),
                                    Name(lineno=233, col_offset=33, end_lineno=233, end_col_offset=48, id='expected_result', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=235,
                    col_offset=4,
                    end_lineno=299,
                    end_col_offset=49,
                    name='test_06_import',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=235, col_offset=23, end_lineno=235, end_col_offset=27, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=236,
                            col_offset=8,
                            end_lineno=262,
                            end_col_offset=3,
                            targets=[Name(lineno=236, col_offset=8, end_lineno=236, end_col_offset=21, id='input_content', ctx=Store())],
                            value=Constant(lineno=236, col_offset=24, end_lineno=262, end_col_offset=3, value='/**\n * import { Dialog, Notification } from "../src/Dialog";\n */\nimport { Line1 } from "../src/Dialog";\nimport { Line2, Notification } from "../src/Dialog";\nimport { Line3, Notification } from "Dialog";\nimport { Line4, Notification } from "@tests/Dialog";\nimport { Line5, Notification } from "./Dialog";\nimport { Line6, Notification } from \'../src/Dialog\'\nimport Line7  from "../src/Dialog";\nimport  Line8  from \'../src/Dialog\';\n\nimport Line9  from "test.Dialog";\nimport  { Line10, Notification }  from \'test.Dialog2\';\n\nimport * as Line11 from "test.Dialog";\nimport "test.Dialog";\n\nimport Line12  from "@test.Dialog"; //HELLO\nimport {Line13}  from "@test.Dialog" //HELLO\n\n\nconst test = `import { Line14, Notification } from "../src/Dialog";`\n\nimport Line15 from "test/Dialog";\nimport Line16 from "test.Dialog.error";\n', kind=None),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=263,
                            col_offset=8,
                            end_lineno=263,
                            end_col_offset=95,
                            targets=[Name(lineno=263, col_offset=8, end_lineno=263, end_col_offset=14, id='result', ctx=Store())],
                            value=Call(
                                lineno=263,
                                col_offset=17,
                                end_lineno=263,
                                end_col_offset=95,
                                func=Name(lineno=263, col_offset=17, end_lineno=263, end_col_offset=37, id='transpile_javascript', ctx=Load()),
                                args=[
                                    Constant(lineno=263, col_offset=38, end_lineno=263, end_col_offset=79, value='/test_assetsbundle/static/src/import.js', kind=None),
                                    Name(lineno=263, col_offset=81, end_lineno=263, end_col_offset=94, id='input_content', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=265,
                            col_offset=8,
                            end_lineno=297,
                            end_col_offset=3,
                            targets=[Name(lineno=265, col_offset=8, end_lineno=265, end_col_offset=23, id='expected_result', ctx=Store())],
                            value=Constant(lineno=265, col_offset=26, end_lineno=297, end_col_offset=3, value='odoo.define(\'@test_assetsbundle/import\', async function (require) {\n\'use strict\';\nlet __exports = {};\n/**\n * import { Dialog, Notification } from "../src/Dialog";\n */\nconst { Line1 } = require("@test_assetsbundle/Dialog");\nconst { Line2, Notification } = require("@test_assetsbundle/Dialog");\nconst { Line3, Notification } = require("Dialog");\nconst { Line4, Notification } = require("@tests/Dialog");\nconst { Line5, Notification } = require("@test_assetsbundle/Dialog");\nconst { Line6, Notification } = require("@test_assetsbundle/Dialog")\nconst Line7 = require("@test_assetsbundle/Dialog")[Symbol.for("default")];\nconst Line8 = require("@test_assetsbundle/Dialog")[Symbol.for("default")];\n\nconst Line9 = require("test.Dialog");\nconst { Line10, Notification } = require(\'test.Dialog2\');\n\nconst Line11 = require("test.Dialog");\nrequire("test.Dialog");\n\nconst Line12 = require("@test.Dialog")[Symbol.for("default")]; //HELLO\nconst {Line13} = require("@test.Dialog") //HELLO\n\n\nconst test = `import { Line14, Notification } from "../src/Dialog";`\n\nconst Line15 = require("test/Dialog");\nconst Line16 = require("test.Dialog.error");\n\nreturn __exports;\n});\n', kind=None),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=299,
                            col_offset=8,
                            end_lineno=299,
                            end_col_offset=49,
                            value=Call(
                                lineno=299,
                                col_offset=8,
                                end_lineno=299,
                                end_col_offset=49,
                                func=Attribute(
                                    lineno=299,
                                    col_offset=8,
                                    end_lineno=299,
                                    end_col_offset=24,
                                    value=Name(lineno=299, col_offset=8, end_lineno=299, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=299, col_offset=25, end_lineno=299, end_col_offset=31, id='result', ctx=Load()),
                                    Name(lineno=299, col_offset=33, end_lineno=299, end_col_offset=48, id='expected_result', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=301,
                    col_offset=4,
                    end_lineno=325,
                    end_col_offset=49,
                    name='test_07_index',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=301, col_offset=22, end_lineno=301, end_col_offset=26, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=302,
                            col_offset=8,
                            end_lineno=308,
                            end_col_offset=26,
                            targets=[Name(lineno=302, col_offset=8, end_lineno=302, end_col_offset=21, id='input_content', ctx=Store())],
                            value=Constant(lineno=302, col_offset=24, end_lineno=308, end_col_offset=26, value='export const a = 5;\n\nimport * as b from "@tests/dir";\n\nimport c from "@tests/dir/index/";\n\nimport d from "@tests";', kind=None),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=309,
                            col_offset=8,
                            end_lineno=309,
                            end_col_offset=94,
                            targets=[Name(lineno=309, col_offset=8, end_lineno=309, end_col_offset=14, id='result', ctx=Store())],
                            value=Call(
                                lineno=309,
                                col_offset=17,
                                end_lineno=309,
                                end_col_offset=94,
                                func=Name(lineno=309, col_offset=17, end_lineno=309, end_col_offset=37, id='transpile_javascript', ctx=Load()),
                                args=[
                                    Constant(lineno=309, col_offset=38, end_lineno=309, end_col_offset=78, value='/test_assetsbundle/static/src/index.js', kind=None),
                                    Name(lineno=309, col_offset=80, end_lineno=309, end_col_offset=93, id='input_content', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=311,
                            col_offset=8,
                            end_lineno=323,
                            end_col_offset=3,
                            targets=[Name(lineno=311, col_offset=8, end_lineno=311, end_col_offset=23, id='expected_result', ctx=Store())],
                            value=Constant(lineno=311, col_offset=26, end_lineno=323, end_col_offset=3, value='odoo.define(\'@test_assetsbundle\', async function (require) {\n\'use strict\';\nlet __exports = {};\nconst a = __exports.a = 5;\n\nconst b = require("@tests/dir");\n\nconst c = require("@tests/dir")[Symbol.for("default")];\n\nconst d = require("@tests")[Symbol.for("default")];\nreturn __exports;\n});\n', kind=None),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=325,
                            col_offset=8,
                            end_lineno=325,
                            end_col_offset=49,
                            value=Call(
                                lineno=325,
                                col_offset=8,
                                end_lineno=325,
                                end_col_offset=49,
                                func=Attribute(
                                    lineno=325,
                                    col_offset=8,
                                    end_lineno=325,
                                    end_col_offset=24,
                                    value=Name(lineno=325, col_offset=8, end_lineno=325, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=325, col_offset=25, end_lineno=325, end_col_offset=31, id='result', ctx=Load()),
                                    Name(lineno=325, col_offset=33, end_lineno=325, end_col_offset=48, id='expected_result', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=327,
                    col_offset=4,
                    end_lineno=383,
                    end_col_offset=49,
                    name='test_08_list',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=327, col_offset=21, end_lineno=327, end_col_offset=25, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=328,
                            col_offset=8,
                            end_lineno=350,
                            end_col_offset=3,
                            targets=[Name(lineno=328, col_offset=8, end_lineno=328, end_col_offset=21, id='input_content', ctx=Store())],
                            value=Constant(lineno=328, col_offset=24, end_lineno=350, end_col_offset=3, value='export {a, b};\n\nexport {a as aa, b, c as cc};\nexport {a, aReallyVeryLongNameWithSomeExtra}\nexport {\n        a,\n        aReallyVeryLongNameWithSomeExtra,\n        }\nexport {\n        a,\n        aReallyVeryLongNameWithSomeExtra\n        }\n\n\nexport {a, aReallyVeryLongNameWithSomeExtra /* a comment must not cause catastrophic backtracking, even if not supported */};\n\nexport {c, d} from "@tests/Dialog";\nexport {e} from "../src/Dialog";\n\nexport {c as cc, d, e as ee} from "@tests/Dialog";\n\nexport * from "@tests/Dialog";\n', kind=None),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=351,
                            col_offset=8,
                            end_lineno=351,
                            end_col_offset=93,
                            targets=[Name(lineno=351, col_offset=8, end_lineno=351, end_col_offset=14, id='result', ctx=Store())],
                            value=Call(
                                lineno=351,
                                col_offset=17,
                                end_lineno=351,
                                end_col_offset=93,
                                func=Name(lineno=351, col_offset=17, end_lineno=351, end_col_offset=37, id='transpile_javascript', ctx=Load()),
                                args=[
                                    Constant(lineno=351, col_offset=38, end_lineno=351, end_col_offset=77, value='/test_assetsbundle/static/src/list.js', kind=None),
                                    Name(lineno=351, col_offset=79, end_lineno=351, end_col_offset=92, id='input_content', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=353,
                            col_offset=8,
                            end_lineno=381,
                            end_col_offset=3,
                            targets=[Name(lineno=353, col_offset=8, end_lineno=353, end_col_offset=23, id='expected_result', ctx=Store())],
                            value=Constant(lineno=353, col_offset=26, end_lineno=381, end_col_offset=3, value='odoo.define(\'@test_assetsbundle/list\', async function (require) {\n\'use strict\';\nlet __exports = {};\nObject.assign(__exports, {a,  b});\n\nObject.assign(__exports, {aa: a,  b, cc:  c});\nObject.assign(__exports, {a,  aReallyVeryLongNameWithSomeExtra})\nObject.assign(__exports, {\n        a, \n        aReallyVeryLongNameWithSomeExtra, \n        })\nObject.assign(__exports, {\n        a, \n        aReallyVeryLongNameWithSomeExtra\n        })\n\n\nexport {a, aReallyVeryLongNameWithSomeExtra /* a comment must not cause catastrophic backtracking, even if not supported */};\n\n{const {c, d} = require("@tests/Dialog");Object.assign(__exports, {c,  d})};\n{const {e} = require("@test_assetsbundle/Dialog");Object.assign(__exports, {e})};\n\n{const {c, d, e} = require("@tests/Dialog");Object.assign(__exports, {cc: c,  d, ee:  e})};\n\nObject.assign(__exports, require("@tests/Dialog"));\n\nreturn __exports;\n});\n', kind=None),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=383,
                            col_offset=8,
                            end_lineno=383,
                            end_col_offset=49,
                            value=Call(
                                lineno=383,
                                col_offset=8,
                                end_lineno=383,
                                end_col_offset=49,
                                func=Attribute(
                                    lineno=383,
                                    col_offset=8,
                                    end_lineno=383,
                                    end_col_offset=24,
                                    value=Name(lineno=383, col_offset=8, end_lineno=383, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=383, col_offset=25, end_lineno=383, end_col_offset=31, id='result', ctx=Load()),
                                    Name(lineno=383, col_offset=33, end_lineno=383, end_col_offset=48, id='expected_result', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=386,
                    col_offset=4,
                    end_lineno=418,
                    end_col_offset=49,
                    name='test_09_variables',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=386, col_offset=26, end_lineno=386, end_col_offset=30, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=387,
                            col_offset=8,
                            end_lineno=397,
                            end_col_offset=3,
                            targets=[Name(lineno=387, col_offset=8, end_lineno=387, end_col_offset=21, id='input_content', ctx=Store())],
                            value=Constant(lineno=387, col_offset=24, end_lineno=397, end_col_offset=3, value='export const v = 5;\n\nconst a = 12;\nconst b = 15;\n\nexport { a, b };\n\nexport default 100;\n\nexport default a;\n', kind=None),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=398,
                            col_offset=8,
                            end_lineno=398,
                            end_col_offset=98,
                            targets=[Name(lineno=398, col_offset=8, end_lineno=398, end_col_offset=14, id='result', ctx=Store())],
                            value=Call(
                                lineno=398,
                                col_offset=17,
                                end_lineno=398,
                                end_col_offset=98,
                                func=Name(lineno=398, col_offset=17, end_lineno=398, end_col_offset=37, id='transpile_javascript', ctx=Load()),
                                args=[
                                    Constant(lineno=398, col_offset=38, end_lineno=398, end_col_offset=82, value='/test_assetsbundle/static/src/variables.js', kind=None),
                                    Name(lineno=398, col_offset=84, end_lineno=398, end_col_offset=97, id='input_content', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=400,
                            col_offset=8,
                            end_lineno=416,
                            end_col_offset=3,
                            targets=[Name(lineno=400, col_offset=8, end_lineno=400, end_col_offset=23, id='expected_result', ctx=Store())],
                            value=Constant(lineno=400, col_offset=26, end_lineno=416, end_col_offset=3, value='odoo.define(\'@test_assetsbundle/variables\', async function (require) {\n\'use strict\';\nlet __exports = {};\nconst v = __exports.v = 5;\n\nconst a = 12;\nconst b = 15;\n\nObject.assign(__exports, { a,  b });\n\n__exports[Symbol.for("default")] = 100;\n\n__exports[Symbol.for("default")] = a;\n\nreturn __exports;\n});\n', kind=None),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=418,
                            col_offset=8,
                            end_lineno=418,
                            end_col_offset=49,
                            value=Call(
                                lineno=418,
                                col_offset=8,
                                end_lineno=418,
                                end_col_offset=49,
                                func=Attribute(
                                    lineno=418,
                                    col_offset=8,
                                    end_lineno=418,
                                    end_col_offset=24,
                                    value=Name(lineno=418, col_offset=8, end_lineno=418, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=418, col_offset=25, end_lineno=418, end_col_offset=31, id='result', ctx=Load()),
                                    Name(lineno=418, col_offset=33, end_lineno=418, end_col_offset=48, id='expected_result', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[
                Call(
                    lineno=9,
                    col_offset=1,
                    end_lineno=9,
                    end_col_offset=38,
                    func=Name(lineno=9, col_offset=1, end_lineno=9, end_col_offset=7, id='tagged', ctx=Load()),
                    args=[
                        Constant(lineno=9, col_offset=8, end_lineno=9, end_col_offset=22, value='post_install', kind=None),
                        Constant(lineno=9, col_offset=24, end_lineno=9, end_col_offset=37, value='-at_install', kind=None),
                    ],
                    keywords=[],
                ),
            ],
        ),
    ],
    type_ignores=[],
)
