Module(
    body=[
        Import(
            lineno=1,
            col_offset=0,
            end_lineno=1,
            end_col_offset=10,
            names=[alias(name='ast', asname=None)],
        ),
        Import(
            lineno=2,
            col_offset=0,
            end_lineno=2,
            end_col_offset=16,
            names=[alias(name='itertools', asname=None)],
        ),
        Import(
            lineno=3,
            col_offset=0,
            end_lineno=3,
            end_col_offset=9,
            names=[alias(name='os', asname=None)],
        ),
        ImportFrom(
            lineno=5,
            col_offset=0,
            end_lineno=5,
            end_col_offset=23,
            module=None,
            names=[alias(name='lint_case', asname=None)],
            level=1,
        ),
        ClassDef(
            lineno=8,
            col_offset=0,
            end_lineno=25,
            end_col_offset=13,
            name='OnchangeChecker',
            bases=[
                Attribute(
                    lineno=8,
                    col_offset=22,
                    end_lineno=8,
                    end_col_offset=43,
                    value=Name(lineno=8, col_offset=22, end_lineno=8, end_col_offset=31, id='lint_case', ctx=Load()),
                    attr='NodeVisitor',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                FunctionDef(
                    lineno=9,
                    col_offset=4,
                    end_lineno=15,
                    end_col_offset=20,
                    name='matches_onchange',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=9, col_offset=25, end_lineno=9, end_col_offset=29, arg='self', annotation=None, type_comment=None),
                            arg(lineno=9, col_offset=31, end_lineno=9, end_col_offset=35, arg='node', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        If(
                            lineno=10,
                            col_offset=8,
                            end_lineno=14,
                            end_col_offset=49,
                            test=Call(
                                lineno=10,
                                col_offset=11,
                                end_lineno=10,
                                end_col_offset=37,
                                func=Name(lineno=10, col_offset=11, end_lineno=10, end_col_offset=21, id='isinstance', ctx=Load()),
                                args=[
                                    Name(lineno=10, col_offset=22, end_lineno=10, end_col_offset=26, id='node', ctx=Load()),
                                    Attribute(
                                        lineno=10,
                                        col_offset=28,
                                        end_lineno=10,
                                        end_col_offset=36,
                                        value=Name(lineno=10, col_offset=28, end_lineno=10, end_col_offset=31, id='ast', ctx=Load()),
                                        attr='Call',
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                            body=[
                                If(
                                    lineno=11,
                                    col_offset=12,
                                    end_lineno=12,
                                    end_col_offset=51,
                                    test=Call(
                                        lineno=11,
                                        col_offset=15,
                                        end_lineno=11,
                                        end_col_offset=51,
                                        func=Name(lineno=11, col_offset=15, end_lineno=11, end_col_offset=25, id='isinstance', ctx=Load()),
                                        args=[
                                            Attribute(
                                                lineno=11,
                                                col_offset=26,
                                                end_lineno=11,
                                                end_col_offset=35,
                                                value=Name(lineno=11, col_offset=26, end_lineno=11, end_col_offset=30, id='node', ctx=Load()),
                                                attr='func',
                                                ctx=Load(),
                                            ),
                                            Attribute(
                                                lineno=11,
                                                col_offset=37,
                                                end_lineno=11,
                                                end_col_offset=50,
                                                value=Name(lineno=11, col_offset=37, end_lineno=11, end_col_offset=40, id='ast', ctx=Load()),
                                                attr='Attribute',
                                                ctx=Load(),
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                    body=[
                                        Return(
                                            lineno=12,
                                            col_offset=16,
                                            end_lineno=12,
                                            end_col_offset=51,
                                            value=Compare(
                                                lineno=12,
                                                col_offset=23,
                                                end_lineno=12,
                                                end_col_offset=51,
                                                left=Attribute(
                                                    lineno=12,
                                                    col_offset=23,
                                                    end_lineno=12,
                                                    end_col_offset=37,
                                                    value=Attribute(
                                                        lineno=12,
                                                        col_offset=23,
                                                        end_lineno=12,
                                                        end_col_offset=32,
                                                        value=Name(lineno=12, col_offset=23, end_lineno=12, end_col_offset=27, id='node', ctx=Load()),
                                                        attr='func',
                                                        ctx=Load(),
                                                    ),
                                                    attr='attr',
                                                    ctx=Load(),
                                                ),
                                                ops=[Eq()],
                                                comparators=[Constant(lineno=12, col_offset=41, end_lineno=12, end_col_offset=51, value='onchange', kind=None)],
                                            ),
                                        ),
                                    ],
                                    orelse=[],
                                ),
                                If(
                                    lineno=13,
                                    col_offset=12,
                                    end_lineno=14,
                                    end_col_offset=49,
                                    test=Call(
                                        lineno=13,
                                        col_offset=15,
                                        end_lineno=13,
                                        end_col_offset=46,
                                        func=Name(lineno=13, col_offset=15, end_lineno=13, end_col_offset=25, id='isinstance', ctx=Load()),
                                        args=[
                                            Attribute(
                                                lineno=13,
                                                col_offset=26,
                                                end_lineno=13,
                                                end_col_offset=35,
                                                value=Name(lineno=13, col_offset=26, end_lineno=13, end_col_offset=30, id='node', ctx=Load()),
                                                attr='func',
                                                ctx=Load(),
                                            ),
                                            Attribute(
                                                lineno=13,
                                                col_offset=37,
                                                end_lineno=13,
                                                end_col_offset=45,
                                                value=Name(lineno=13, col_offset=37, end_lineno=13, end_col_offset=40, id='ast', ctx=Load()),
                                                attr='Name',
                                                ctx=Load(),
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                    body=[
                                        Return(
                                            lineno=14,
                                            col_offset=16,
                                            end_lineno=14,
                                            end_col_offset=49,
                                            value=Compare(
                                                lineno=14,
                                                col_offset=23,
                                                end_lineno=14,
                                                end_col_offset=49,
                                                left=Attribute(
                                                    lineno=14,
                                                    col_offset=23,
                                                    end_lineno=14,
                                                    end_col_offset=35,
                                                    value=Attribute(
                                                        lineno=14,
                                                        col_offset=23,
                                                        end_lineno=14,
                                                        end_col_offset=32,
                                                        value=Name(lineno=14, col_offset=23, end_lineno=14, end_col_offset=27, id='node', ctx=Load()),
                                                        attr='func',
                                                        ctx=Load(),
                                                    ),
                                                    attr='id',
                                                    ctx=Load(),
                                                ),
                                                ops=[Eq()],
                                                comparators=[Constant(lineno=14, col_offset=39, end_lineno=14, end_col_offset=49, value='onchange', kind=None)],
                                            ),
                                        ),
                                    ],
                                    orelse=[],
                                ),
                            ],
                            orelse=[],
                        ),
                        Return(
                            lineno=15,
                            col_offset=8,
                            end_lineno=15,
                            end_col_offset=20,
                            value=Constant(lineno=15, col_offset=15, end_lineno=15, end_col_offset=20, value=False, kind=None),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=17,
                    col_offset=4,
                    end_lineno=25,
                    end_col_offset=13,
                    name='visit_FunctionDef',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=17, col_offset=26, end_lineno=17, end_col_offset=30, arg='self', annotation=None, type_comment=None),
                            arg(lineno=17, col_offset=32, end_lineno=17, end_col_offset=36, arg='node', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=18,
                            col_offset=8,
                            end_lineno=18,
                            end_col_offset=95,
                            targets=[Name(lineno=18, col_offset=8, end_lineno=18, end_col_offset=14, id='walker', ctx=Store())],
                            value=IfExp(
                                lineno=18,
                                col_offset=17,
                                end_lineno=18,
                                end_col_offset=95,
                                test=Call(
                                    lineno=18,
                                    col_offset=35,
                                    end_lineno=18,
                                    end_col_offset=87,
                                    func=Name(lineno=18, col_offset=35, end_lineno=18, end_col_offset=38, id='any', ctx=Load()),
                                    args=[
                                        Call(
                                            lineno=18,
                                            col_offset=39,
                                            end_lineno=18,
                                            end_col_offset=86,
                                            func=Name(lineno=18, col_offset=39, end_lineno=18, end_col_offset=42, id='map', ctx=Load()),
                                            args=[
                                                Attribute(
                                                    lineno=18,
                                                    col_offset=43,
                                                    end_lineno=18,
                                                    end_col_offset=64,
                                                    value=Name(lineno=18, col_offset=43, end_lineno=18, end_col_offset=47, id='self', ctx=Load()),
                                                    attr='matches_onchange',
                                                    ctx=Load(),
                                                ),
                                                Attribute(
                                                    lineno=18,
                                                    col_offset=66,
                                                    end_lineno=18,
                                                    end_col_offset=85,
                                                    value=Name(lineno=18, col_offset=66, end_lineno=18, end_col_offset=70, id='node', ctx=Load()),
                                                    attr='decorator_list',
                                                    ctx=Load(),
                                                ),
                                            ],
                                            keywords=[],
                                        ),
                                    ],
                                    keywords=[],
                                ),
                                body=Call(
                                    lineno=18,
                                    col_offset=17,
                                    end_lineno=18,
                                    end_col_offset=31,
                                    func=Attribute(
                                        lineno=18,
                                        col_offset=17,
                                        end_lineno=18,
                                        end_col_offset=25,
                                        value=Name(lineno=18, col_offset=17, end_lineno=18, end_col_offset=20, id='ast', ctx=Load()),
                                        attr='walk',
                                        ctx=Load(),
                                    ),
                                    args=[Name(lineno=18, col_offset=26, end_lineno=18, end_col_offset=30, id='node', ctx=Load())],
                                    keywords=[],
                                ),
                                orelse=List(lineno=18, col_offset=93, end_lineno=18, end_col_offset=95, elts=[], ctx=Load()),
                            ),
                            type_comment=None,
                        ),
                        Return(
                            lineno=21,
                            col_offset=8,
                            end_lineno=25,
                            end_col_offset=13,
                            value=Call(
                                lineno=21,
                                col_offset=15,
                                end_lineno=25,
                                end_col_offset=13,
                                func=Attribute(
                                    lineno=21,
                                    col_offset=15,
                                    end_lineno=21,
                                    end_col_offset=31,
                                    value=Name(lineno=21, col_offset=15, end_lineno=21, end_col_offset=24, id='itertools', ctx=Load()),
                                    attr='islice',
                                    ctx=Load(),
                                ),
                                args=[
                                    GeneratorExp(
                                        lineno=21,
                                        col_offset=32,
                                        end_lineno=25,
                                        end_col_offset=9,
                                        elt=Name(lineno=22, col_offset=12, end_lineno=22, end_col_offset=13, id='n', ctx=Load()),
                                        generators=[
                                            comprehension(
                                                target=Name(lineno=22, col_offset=18, end_lineno=22, end_col_offset=19, id='n', ctx=Store()),
                                                iter=Name(lineno=22, col_offset=23, end_lineno=22, end_col_offset=29, id='walker', ctx=Load()),
                                                ifs=[
                                                    BoolOp(
                                                        lineno=23,
                                                        col_offset=15,
                                                        end_lineno=24,
                                                        end_col_offset=90,
                                                        op=Or(),
                                                        values=[
                                                            BoolOp(
                                                                lineno=23,
                                                                col_offset=15,
                                                                end_lineno=23,
                                                                end_col_offset=81,
                                                                op=And(),
                                                                values=[
                                                                    Call(
                                                                        lineno=23,
                                                                        col_offset=15,
                                                                        end_lineno=23,
                                                                        end_col_offset=61,
                                                                        func=Name(lineno=23, col_offset=15, end_lineno=23, end_col_offset=25, id='isinstance', ctx=Load()),
                                                                        args=[
                                                                            Name(lineno=23, col_offset=26, end_lineno=23, end_col_offset=27, id='n', ctx=Load()),
                                                                            Call(
                                                                                lineno=23,
                                                                                col_offset=29,
                                                                                end_lineno=23,
                                                                                end_col_offset=60,
                                                                                func=Name(lineno=23, col_offset=29, end_lineno=23, end_col_offset=36, id='getattr', ctx=Load()),
                                                                                args=[
                                                                                    Name(lineno=23, col_offset=37, end_lineno=23, end_col_offset=40, id='ast', ctx=Load()),
                                                                                    Constant(lineno=23, col_offset=42, end_lineno=23, end_col_offset=47, value='Str', kind=None),
                                                                                    Call(
                                                                                        lineno=23,
                                                                                        col_offset=49,
                                                                                        end_lineno=23,
                                                                                        end_col_offset=59,
                                                                                        func=Name(lineno=23, col_offset=49, end_lineno=23, end_col_offset=53, id='type', ctx=Load()),
                                                                                        args=[Constant(lineno=23, col_offset=54, end_lineno=23, end_col_offset=58, value=None, kind=None)],
                                                                                        keywords=[],
                                                                                    ),
                                                                                ],
                                                                                keywords=[],
                                                                            ),
                                                                        ],
                                                                        keywords=[],
                                                                    ),
                                                                    Compare(
                                                                        lineno=23,
                                                                        col_offset=66,
                                                                        end_lineno=23,
                                                                        end_col_offset=81,
                                                                        left=Attribute(
                                                                            lineno=23,
                                                                            col_offset=66,
                                                                            end_lineno=23,
                                                                            end_col_offset=69,
                                                                            value=Name(lineno=23, col_offset=66, end_lineno=23, end_col_offset=67, id='n', ctx=Load()),
                                                                            attr='s',
                                                                            ctx=Load(),
                                                                        ),
                                                                        ops=[Eq()],
                                                                        comparators=[Constant(lineno=23, col_offset=73, end_lineno=23, end_col_offset=81, value='domain', kind=None)],
                                                                    ),
                                                                ],
                                                            ),
                                                            BoolOp(
                                                                lineno=24,
                                                                col_offset=15,
                                                                end_lineno=24,
                                                                end_col_offset=90,
                                                                op=And(),
                                                                values=[
                                                                    Call(
                                                                        lineno=24,
                                                                        col_offset=15,
                                                                        end_lineno=24,
                                                                        end_col_offset=66,
                                                                        func=Name(lineno=24, col_offset=15, end_lineno=24, end_col_offset=25, id='isinstance', ctx=Load()),
                                                                        args=[
                                                                            Name(lineno=24, col_offset=26, end_lineno=24, end_col_offset=27, id='n', ctx=Load()),
                                                                            Call(
                                                                                lineno=24,
                                                                                col_offset=29,
                                                                                end_lineno=24,
                                                                                end_col_offset=65,
                                                                                func=Name(lineno=24, col_offset=29, end_lineno=24, end_col_offset=36, id='getattr', ctx=Load()),
                                                                                args=[
                                                                                    Name(lineno=24, col_offset=37, end_lineno=24, end_col_offset=40, id='ast', ctx=Load()),
                                                                                    Constant(lineno=24, col_offset=42, end_lineno=24, end_col_offset=52, value='Constant', kind=None),
                                                                                    Call(
                                                                                        lineno=24,
                                                                                        col_offset=54,
                                                                                        end_lineno=24,
                                                                                        end_col_offset=64,
                                                                                        func=Name(lineno=24, col_offset=54, end_lineno=24, end_col_offset=58, id='type', ctx=Load()),
                                                                                        args=[Constant(lineno=24, col_offset=59, end_lineno=24, end_col_offset=63, value=None, kind=None)],
                                                                                        keywords=[],
                                                                                    ),
                                                                                ],
                                                                                keywords=[],
                                                                            ),
                                                                        ],
                                                                        keywords=[],
                                                                    ),
                                                                    Compare(
                                                                        lineno=24,
                                                                        col_offset=71,
                                                                        end_lineno=24,
                                                                        end_col_offset=90,
                                                                        left=Attribute(
                                                                            lineno=24,
                                                                            col_offset=71,
                                                                            end_lineno=24,
                                                                            end_col_offset=78,
                                                                            value=Name(lineno=24, col_offset=71, end_lineno=24, end_col_offset=72, id='n', ctx=Load()),
                                                                            attr='value',
                                                                            ctx=Load(),
                                                                        ),
                                                                        ops=[Eq()],
                                                                        comparators=[Constant(lineno=24, col_offset=82, end_lineno=24, end_col_offset=90, value='domain', kind=None)],
                                                                    ),
                                                                ],
                                                            ),
                                                        ],
                                                    ),
                                                ],
                                                is_async=0,
                                            ),
                                        ],
                                    ),
                                    Constant(lineno=25, col_offset=11, end_lineno=25, end_col_offset=12, value=1, kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
        ClassDef(
            lineno=28,
            col_offset=0,
            end_lineno=48,
            end_col_offset=9,
            name='TestOnchangeDomains',
            bases=[
                Attribute(
                    lineno=28,
                    col_offset=26,
                    end_lineno=28,
                    end_col_offset=44,
                    value=Name(lineno=28, col_offset=26, end_lineno=28, end_col_offset=35, id='lint_case', ctx=Load()),
                    attr='LintCase',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Expr(
                    lineno=29,
                    col_offset=4,
                    end_lineno=32,
                    end_col_offset=7,
                    value=Constant(lineno=29, col_offset=4, end_lineno=32, end_col_offset=7, value=" Would ideally have been a pylint module but that's slow as molasses\n    (takes minutes to run, and can blow up entirely depending on the pylint\n    version)\n    ", kind=None),
                ),
                FunctionDef(
                    lineno=33,
                    col_offset=4,
                    end_lineno=48,
                    end_col_offset=9,
                    name='test_forbid_domains_in_onchanges',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=33, col_offset=41, end_lineno=33, end_col_offset=45, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=34,
                            col_offset=8,
                            end_lineno=36,
                            end_col_offset=11,
                            value=Constant(lineno=34, col_offset=8, end_lineno=36, end_col_offset=11, value=' Dynamic domains (returning a domain from an onchange) are deprecated\n        and should not be used in "standard" Odoo anymore\n        ', kind=None),
                        ),
                        Assign(
                            lineno=37,
                            col_offset=8,
                            end_lineno=37,
                            end_col_offset=35,
                            targets=[Name(lineno=37, col_offset=8, end_lineno=37, end_col_offset=15, id='checker', ctx=Store())],
                            value=Call(
                                lineno=37,
                                col_offset=18,
                                end_lineno=37,
                                end_col_offset=35,
                                func=Name(lineno=37, col_offset=18, end_lineno=37, end_col_offset=33, id='OnchangeChecker', ctx=Load()),
                                args=[],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=38,
                            col_offset=8,
                            end_lineno=38,
                            end_col_offset=15,
                            targets=[Name(lineno=38, col_offset=8, end_lineno=38, end_col_offset=10, id='rs', ctx=Store())],
                            value=List(lineno=38, col_offset=13, end_lineno=38, end_col_offset=15, elts=[], ctx=Load()),
                            type_comment=None,
                        ),
                        For(
                            lineno=39,
                            col_offset=8,
                            end_lineno=42,
                            end_col_offset=85,
                            target=Name(lineno=39, col_offset=12, end_lineno=39, end_col_offset=16, id='path', ctx=Store()),
                            iter=Call(
                                lineno=39,
                                col_offset=20,
                                end_lineno=39,
                                end_col_offset=50,
                                func=Attribute(
                                    lineno=39,
                                    col_offset=20,
                                    end_lineno=39,
                                    end_col_offset=42,
                                    value=Name(lineno=39, col_offset=20, end_lineno=39, end_col_offset=24, id='self', ctx=Load()),
                                    attr='iter_module_files',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=39, col_offset=43, end_lineno=39, end_col_offset=49, value='*.py', kind=None)],
                                keywords=[],
                            ),
                            body=[
                                With(
                                    lineno=40,
                                    col_offset=12,
                                    end_lineno=41,
                                    end_col_offset=45,
                                    items=[
                                        withitem(
                                            context_expr=Call(
                                                lineno=40,
                                                col_offset=17,
                                                end_lineno=40,
                                                end_col_offset=33,
                                                func=Name(lineno=40, col_offset=17, end_lineno=40, end_col_offset=21, id='open', ctx=Load()),
                                                args=[
                                                    Name(lineno=40, col_offset=22, end_lineno=40, end_col_offset=26, id='path', ctx=Load()),
                                                    Constant(lineno=40, col_offset=28, end_lineno=40, end_col_offset=32, value='rb', kind=None),
                                                ],
                                                keywords=[],
                                            ),
                                            optional_vars=Name(lineno=40, col_offset=37, end_lineno=40, end_col_offset=38, id='f', ctx=Store()),
                                        ),
                                    ],
                                    body=[
                                        Assign(
                                            lineno=41,
                                            col_offset=16,
                                            end_lineno=41,
                                            end_col_offset=45,
                                            targets=[Name(lineno=41, col_offset=16, end_lineno=41, end_col_offset=17, id='t', ctx=Store())],
                                            value=Call(
                                                lineno=41,
                                                col_offset=20,
                                                end_lineno=41,
                                                end_col_offset=45,
                                                func=Attribute(
                                                    lineno=41,
                                                    col_offset=20,
                                                    end_lineno=41,
                                                    end_col_offset=29,
                                                    value=Name(lineno=41, col_offset=20, end_lineno=41, end_col_offset=23, id='ast', ctx=Load()),
                                                    attr='parse',
                                                    ctx=Load(),
                                                ),
                                                args=[
                                                    Call(
                                                        lineno=41,
                                                        col_offset=30,
                                                        end_lineno=41,
                                                        end_col_offset=38,
                                                        func=Attribute(
                                                            lineno=41,
                                                            col_offset=30,
                                                            end_lineno=41,
                                                            end_col_offset=36,
                                                            value=Name(lineno=41, col_offset=30, end_lineno=41, end_col_offset=31, id='f', ctx=Load()),
                                                            attr='read',
                                                            ctx=Load(),
                                                        ),
                                                        args=[],
                                                        keywords=[],
                                                    ),
                                                    Name(lineno=41, col_offset=40, end_lineno=41, end_col_offset=44, id='path', ctx=Load()),
                                                ],
                                                keywords=[],
                                            ),
                                            type_comment=None,
                                        ),
                                    ],
                                    type_comment=None,
                                ),
                                Expr(
                                    lineno=42,
                                    col_offset=12,
                                    end_lineno=42,
                                    end_col_offset=85,
                                    value=Call(
                                        lineno=42,
                                        col_offset=12,
                                        end_lineno=42,
                                        end_col_offset=85,
                                        func=Attribute(
                                            lineno=42,
                                            col_offset=12,
                                            end_lineno=42,
                                            end_col_offset=21,
                                            value=Name(lineno=42, col_offset=12, end_lineno=42, end_col_offset=14, id='rs', ctx=Load()),
                                            attr='extend',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Call(
                                                lineno=42,
                                                col_offset=22,
                                                end_lineno=42,
                                                end_col_offset=84,
                                                func=Name(lineno=42, col_offset=22, end_lineno=42, end_col_offset=25, id='zip', ctx=Load()),
                                                args=[
                                                    Call(
                                                        lineno=42,
                                                        col_offset=26,
                                                        end_lineno=42,
                                                        end_col_offset=65,
                                                        func=Attribute(
                                                            lineno=42,
                                                            col_offset=26,
                                                            end_lineno=42,
                                                            end_col_offset=42,
                                                            value=Name(lineno=42, col_offset=26, end_lineno=42, end_col_offset=35, id='itertools', ctx=Load()),
                                                            attr='repeat',
                                                            ctx=Load(),
                                                        ),
                                                        args=[
                                                            Call(
                                                                lineno=42,
                                                                col_offset=43,
                                                                end_lineno=42,
                                                                end_col_offset=64,
                                                                func=Attribute(
                                                                    lineno=42,
                                                                    col_offset=43,
                                                                    end_lineno=42,
                                                                    end_col_offset=58,
                                                                    value=Attribute(
                                                                        lineno=42,
                                                                        col_offset=43,
                                                                        end_lineno=42,
                                                                        end_col_offset=50,
                                                                        value=Name(lineno=42, col_offset=43, end_lineno=42, end_col_offset=45, id='os', ctx=Load()),
                                                                        attr='path',
                                                                        ctx=Load(),
                                                                    ),
                                                                    attr='relpath',
                                                                    ctx=Load(),
                                                                ),
                                                                args=[Name(lineno=42, col_offset=59, end_lineno=42, end_col_offset=63, id='path', ctx=Load())],
                                                                keywords=[],
                                                            ),
                                                        ],
                                                        keywords=[],
                                                    ),
                                                    Call(
                                                        lineno=42,
                                                        col_offset=67,
                                                        end_lineno=42,
                                                        end_col_offset=83,
                                                        func=Attribute(
                                                            lineno=42,
                                                            col_offset=67,
                                                            end_lineno=42,
                                                            end_col_offset=80,
                                                            value=Name(lineno=42, col_offset=67, end_lineno=42, end_col_offset=74, id='checker', ctx=Load()),
                                                            attr='visit',
                                                            ctx=Load(),
                                                        ),
                                                        args=[Name(lineno=42, col_offset=81, end_lineno=42, end_col_offset=82, id='t', ctx=Load())],
                                                        keywords=[],
                                                    ),
                                                ],
                                                keywords=[],
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                ),
                            ],
                            orelse=[],
                            type_comment=None,
                        ),
                        Expr(
                            lineno=44,
                            col_offset=8,
                            end_lineno=44,
                            end_col_offset=35,
                            value=Call(
                                lineno=44,
                                col_offset=8,
                                end_lineno=44,
                                end_col_offset=35,
                                func=Attribute(
                                    lineno=44,
                                    col_offset=8,
                                    end_lineno=44,
                                    end_col_offset=15,
                                    value=Name(lineno=44, col_offset=8, end_lineno=44, end_col_offset=10, id='rs', ctx=Load()),
                                    attr='sort',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[
                                    keyword(
                                        lineno=44,
                                        col_offset=16,
                                        end_lineno=44,
                                        end_col_offset=34,
                                        arg='key',
                                        value=Lambda(
                                            lineno=44,
                                            col_offset=20,
                                            end_lineno=44,
                                            end_col_offset=34,
                                            args=arguments(
                                                posonlyargs=[],
                                                args=[arg(lineno=44, col_offset=27, end_lineno=44, end_col_offset=28, arg='t', annotation=None, type_comment=None)],
                                                vararg=None,
                                                kwonlyargs=[],
                                                kw_defaults=[],
                                                kwarg=None,
                                                defaults=[],
                                            ),
                                            body=Subscript(
                                                lineno=44,
                                                col_offset=30,
                                                end_lineno=44,
                                                end_col_offset=34,
                                                value=Name(lineno=44, col_offset=30, end_lineno=44, end_col_offset=31, id='t', ctx=Load()),
                                                slice=Constant(lineno=44, col_offset=32, end_lineno=44, end_col_offset=33, value=0, kind=None),
                                                ctx=Load(),
                                            ),
                                        ),
                                    ),
                                ],
                            ),
                        ),
                        Assert(
                            lineno=45,
                            col_offset=8,
                            end_lineno=48,
                            end_col_offset=9,
                            test=UnaryOp(
                                lineno=45,
                                col_offset=15,
                                end_lineno=45,
                                end_col_offset=21,
                                op=Not(),
                                operand=Name(lineno=45, col_offset=19, end_lineno=45, end_col_offset=21, id='rs', ctx=Load()),
                            ),
                            msg=BinOp(
                                lineno=45,
                                col_offset=23,
                                end_lineno=48,
                                end_col_offset=9,
                                left=Constant(lineno=45, col_offset=23, end_lineno=45, end_col_offset=59, value='probable domains in onchanges at\n', kind=None),
                                op=Add(),
                                right=Call(
                                    lineno=45,
                                    col_offset=62,
                                    end_lineno=48,
                                    end_col_offset=9,
                                    func=Attribute(
                                        lineno=45,
                                        col_offset=62,
                                        end_lineno=45,
                                        end_col_offset=71,
                                        value=Constant(lineno=45, col_offset=62, end_lineno=45, end_col_offset=66, value='\n', kind=None),
                                        attr='join',
                                        ctx=Load(),
                                    ),
                                    args=[
                                        GeneratorExp(
                                            lineno=45,
                                            col_offset=71,
                                            end_lineno=48,
                                            end_col_offset=9,
                                            elt=BinOp(
                                                lineno=46,
                                                col_offset=12,
                                                end_lineno=46,
                                                end_col_offset=43,
                                                left=Constant(lineno=46, col_offset=12, end_lineno=46, end_col_offset=21, value='- %s:%d', kind=None),
                                                op=Mod(),
                                                right=Tuple(
                                                    lineno=46,
                                                    col_offset=24,
                                                    end_lineno=46,
                                                    end_col_offset=43,
                                                    elts=[
                                                        Name(lineno=46, col_offset=25, end_lineno=46, end_col_offset=29, id='path', ctx=Load()),
                                                        Attribute(
                                                            lineno=46,
                                                            col_offset=31,
                                                            end_lineno=46,
                                                            end_col_offset=42,
                                                            value=Name(lineno=46, col_offset=31, end_lineno=46, end_col_offset=35, id='node', ctx=Load()),
                                                            attr='lineno',
                                                            ctx=Load(),
                                                        ),
                                                    ],
                                                    ctx=Load(),
                                                ),
                                            ),
                                            generators=[
                                                comprehension(
                                                    target=Tuple(
                                                        lineno=47,
                                                        col_offset=16,
                                                        end_lineno=47,
                                                        end_col_offset=26,
                                                        elts=[
                                                            Name(lineno=47, col_offset=16, end_lineno=47, end_col_offset=20, id='path', ctx=Store()),
                                                            Name(lineno=47, col_offset=22, end_lineno=47, end_col_offset=26, id='node', ctx=Store()),
                                                        ],
                                                        ctx=Store(),
                                                    ),
                                                    iter=Name(lineno=47, col_offset=30, end_lineno=47, end_col_offset=32, id='rs', ctx=Load()),
                                                    ifs=[],
                                                    is_async=0,
                                                ),
                                            ],
                                        ),
                                    ],
                                    keywords=[],
                                ),
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
