Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=36,
            module='odoo',
            names=[
                alias(name='api', asname=None),
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=19,
            end_col_offset=90,
            name='StockReplenishmentInfo',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=29,
                    end_lineno=7,
                    end_col_offset=50,
                    value=Name(lineno=7, col_offset=29, end_lineno=7, end_col_offset=35, id='models', ctx=Load()),
                    attr='TransientModel',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=41,
                    targets=[Name(lineno=8, col_offset=4, end_lineno=8, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=8, col_offset=15, end_lineno=8, end_col_offset=41, value='stock.replenishment.info', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=9,
                    col_offset=4,
                    end_lineno=9,
                    end_col_offset=61,
                    targets=[Name(lineno=9, col_offset=4, end_lineno=9, end_col_offset=16, id='_description', ctx=Store())],
                    value=Constant(lineno=9, col_offset=19, end_lineno=9, end_col_offset=61, value='Stock supplier replenishment information', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=11,
                    col_offset=4,
                    end_lineno=11,
                    end_col_offset=74,
                    targets=[Name(lineno=11, col_offset=4, end_lineno=11, end_col_offset=19, id='supplierinfo_id', ctx=Store())],
                    value=Call(
                        lineno=11,
                        col_offset=22,
                        end_lineno=11,
                        end_col_offset=74,
                        func=Attribute(
                            lineno=11,
                            col_offset=22,
                            end_lineno=11,
                            end_col_offset=37,
                            value=Name(lineno=11, col_offset=22, end_lineno=11, end_col_offset=28, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=11,
                                col_offset=38,
                                end_lineno=11,
                                end_col_offset=73,
                                arg='related',
                                value=Constant(lineno=11, col_offset=46, end_lineno=11, end_col_offset=73, value='orderpoint_id.supplier_id', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=12,
                    col_offset=4,
                    end_lineno=14,
                    end_col_offset=19,
                    targets=[Name(lineno=12, col_offset=4, end_lineno=12, end_col_offset=20, id='supplierinfo_ids', ctx=Store())],
                    value=Call(
                        lineno=12,
                        col_offset=23,
                        end_lineno=14,
                        end_col_offset=19,
                        func=Attribute(
                            lineno=12,
                            col_offset=23,
                            end_lineno=12,
                            end_col_offset=39,
                            value=Name(lineno=12, col_offset=23, end_lineno=12, end_col_offset=29, id='fields', ctx=Load()),
                            attr='Many2many',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=13, col_offset=8, end_lineno=13, end_col_offset=30, value='product.supplierinfo', kind=None)],
                        keywords=[
                            keyword(
                                lineno=13,
                                col_offset=32,
                                end_lineno=13,
                                end_col_offset=67,
                                arg='compute',
                                value=Constant(lineno=13, col_offset=40, end_lineno=13, end_col_offset=67, value='_compute_supplierinfo_ids', kind=None),
                            ),
                            keyword(
                                lineno=14,
                                col_offset=8,
                                end_lineno=14,
                                end_col_offset=18,
                                arg='store',
                                value=Constant(lineno=14, col_offset=14, end_lineno=14, end_col_offset=18, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=17,
                    col_offset=4,
                    end_lineno=19,
                    end_col_offset=90,
                    name='_compute_supplierinfo_ids',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=17, col_offset=34, end_lineno=17, end_col_offset=38, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        For(
                            lineno=18,
                            col_offset=8,
                            end_lineno=19,
                            end_col_offset=90,
                            target=Name(lineno=18, col_offset=12, end_lineno=18, end_col_offset=30, id='replenishment_info', ctx=Store()),
                            iter=Name(lineno=18, col_offset=34, end_lineno=18, end_col_offset=38, id='self', ctx=Load()),
                            body=[
                                Assign(
                                    lineno=19,
                                    col_offset=12,
                                    end_lineno=19,
                                    end_col_offset=90,
                                    targets=[
                                        Attribute(
                                            lineno=19,
                                            col_offset=12,
                                            end_lineno=19,
                                            end_col_offset=47,
                                            value=Name(lineno=19, col_offset=12, end_lineno=19, end_col_offset=30, id='replenishment_info', ctx=Load()),
                                            attr='supplierinfo_ids',
                                            ctx=Store(),
                                        ),
                                    ],
                                    value=Attribute(
                                        lineno=19,
                                        col_offset=50,
                                        end_lineno=19,
                                        end_col_offset=90,
                                        value=Attribute(
                                            lineno=19,
                                            col_offset=50,
                                            end_lineno=19,
                                            end_col_offset=79,
                                            value=Name(lineno=19, col_offset=50, end_lineno=19, end_col_offset=68, id='replenishment_info', ctx=Load()),
                                            attr='product_id',
                                            ctx=Load(),
                                        ),
                                        attr='seller_ids',
                                        ctx=Load(),
                                    ),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[],
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[
                        Call(
                            lineno=16,
                            col_offset=5,
                            end_lineno=16,
                            end_col_offset=33,
                            func=Attribute(
                                lineno=16,
                                col_offset=5,
                                end_lineno=16,
                                end_col_offset=16,
                                value=Name(lineno=16, col_offset=5, end_lineno=16, end_col_offset=8, id='api', ctx=Load()),
                                attr='depends',
                                ctx=Load(),
                            ),
                            args=[Constant(lineno=16, col_offset=17, end_lineno=16, end_col_offset=32, value='orderpoint_id', kind=None)],
                            keywords=[],
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
