Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=39,
            module='odoo',
            names=[
                alias(name='_', asname=None),
                alias(name='api', asname=None),
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
            ],
            level=0,
        ),
        Assign(
            lineno=7,
            col_offset=0,
            end_lineno=12,
            end_col_offset=1,
            targets=[Name(lineno=7, col_offset=0, end_lineno=7, end_col_offset=10, id='FUEL_TYPES', ctx=Store())],
            value=List(
                lineno=7,
                col_offset=13,
                end_lineno=12,
                end_col_offset=1,
                elts=[
                    Tuple(
                        lineno=8,
                        col_offset=4,
                        end_lineno=8,
                        end_col_offset=28,
                        elts=[
                            Constant(lineno=8, col_offset=5, end_lineno=8, end_col_offset=15, value='gasoline', kind=None),
                            Constant(lineno=8, col_offset=17, end_lineno=8, end_col_offset=27, value='Gasoline', kind=None),
                        ],
                        ctx=Load(),
                    ),
                    Tuple(
                        lineno=8,
                        col_offset=30,
                        end_lineno=8,
                        end_col_offset=50,
                        elts=[
                            Constant(lineno=8, col_offset=31, end_lineno=8, end_col_offset=39, value='diesel', kind=None),
                            Constant(lineno=8, col_offset=41, end_lineno=8, end_col_offset=49, value='Diesel', kind=None),
                        ],
                        ctx=Load(),
                    ),
                    Tuple(
                        lineno=8,
                        col_offset=52,
                        end_lineno=8,
                        end_col_offset=66,
                        elts=[
                            Constant(lineno=8, col_offset=53, end_lineno=8, end_col_offset=58, value='lpg', kind=None),
                            Constant(lineno=8, col_offset=60, end_lineno=8, end_col_offset=65, value='LPG', kind=None),
                        ],
                        ctx=Load(),
                    ),
                    Tuple(
                        lineno=9,
                        col_offset=4,
                        end_lineno=9,
                        end_col_offset=28,
                        elts=[
                            Constant(lineno=9, col_offset=5, end_lineno=9, end_col_offset=15, value='electric', kind=None),
                            Constant(lineno=9, col_offset=17, end_lineno=9, end_col_offset=27, value='Electric', kind=None),
                        ],
                        ctx=Load(),
                    ),
                    Tuple(
                        lineno=9,
                        col_offset=30,
                        end_lineno=9,
                        end_col_offset=50,
                        elts=[
                            Constant(lineno=9, col_offset=31, end_lineno=9, end_col_offset=39, value='hybrid', kind=None),
                            Constant(lineno=9, col_offset=41, end_lineno=9, end_col_offset=49, value='Hybrid', kind=None),
                        ],
                        ctx=Load(),
                    ),
                    Tuple(
                        lineno=9,
                        col_offset=52,
                        end_lineno=9,
                        end_col_offset=102,
                        elts=[
                            Constant(lineno=9, col_offset=53, end_lineno=9, end_col_offset=76, value='plug_in_hybrid_diesel', kind=None),
                            Constant(lineno=9, col_offset=78, end_lineno=9, end_col_offset=101, value='Plug-in Hybrid Diesel', kind=None),
                        ],
                        ctx=Load(),
                    ),
                    Tuple(
                        lineno=10,
                        col_offset=4,
                        end_lineno=10,
                        end_col_offset=58,
                        elts=[
                            Constant(lineno=10, col_offset=5, end_lineno=10, end_col_offset=30, value='plug_in_hybrid_gasoline', kind=None),
                            Constant(lineno=10, col_offset=32, end_lineno=10, end_col_offset=57, value='Plug-in Hybrid Gasoline', kind=None),
                        ],
                        ctx=Load(),
                    ),
                    Tuple(
                        lineno=10,
                        col_offset=60,
                        end_lineno=10,
                        end_col_offset=108,
                        elts=[
                            Constant(lineno=10, col_offset=61, end_lineno=10, end_col_offset=83, value='full_hybrid_gasoline', kind=None),
                            Constant(lineno=10, col_offset=85, end_lineno=10, end_col_offset=107, value='Full Hybrid Gasoline', kind=None),
                        ],
                        ctx=Load(),
                    ),
                    Tuple(
                        lineno=11,
                        col_offset=4,
                        end_lineno=11,
                        end_col_offset=18,
                        elts=[
                            Constant(lineno=11, col_offset=5, end_lineno=11, end_col_offset=10, value='cng', kind=None),
                            Constant(lineno=11, col_offset=12, end_lineno=11, end_col_offset=17, value='CNG', kind=None),
                        ],
                        ctx=Load(),
                    ),
                    Tuple(
                        lineno=11,
                        col_offset=20,
                        end_lineno=11,
                        end_col_offset=44,
                        elts=[
                            Constant(lineno=11, col_offset=21, end_lineno=11, end_col_offset=31, value='hydrogen', kind=None),
                            Constant(lineno=11, col_offset=33, end_lineno=11, end_col_offset=43, value='Hydrogen', kind=None),
                        ],
                        ctx=Load(),
                    ),
                ],
                ctx=Load(),
            ),
            type_comment=None,
        ),
        ClassDef(
            lineno=14,
            col_offset=0,
            end_lineno=69,
            end_col_offset=19,
            name='FleetVehicleModel',
            bases=[
                Attribute(
                    lineno=14,
                    col_offset=24,
                    end_lineno=14,
                    end_col_offset=36,
                    value=Name(lineno=14, col_offset=24, end_lineno=14, end_col_offset=30, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=15,
                    col_offset=4,
                    end_lineno=15,
                    end_col_offset=33,
                    targets=[Name(lineno=15, col_offset=4, end_lineno=15, end_col_offset=9, id='_name', ctx=Store())],
                    value=Constant(lineno=15, col_offset=12, end_lineno=15, end_col_offset=33, value='fleet.vehicle.model', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=16,
                    col_offset=4,
                    end_lineno=16,
                    end_col_offset=39,
                    targets=[Name(lineno=16, col_offset=4, end_lineno=16, end_col_offset=16, id='_description', ctx=Store())],
                    value=Constant(lineno=16, col_offset=19, end_lineno=16, end_col_offset=39, value='Model of a vehicle', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=17,
                    col_offset=4,
                    end_lineno=17,
                    end_col_offset=23,
                    targets=[Name(lineno=17, col_offset=4, end_lineno=17, end_col_offset=10, id='_order', ctx=Store())],
                    value=Constant(lineno=17, col_offset=13, end_lineno=17, end_col_offset=23, value='name asc', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=19,
                    col_offset=4,
                    end_lineno=19,
                    end_col_offset=51,
                    targets=[Name(lineno=19, col_offset=4, end_lineno=19, end_col_offset=8, id='name', ctx=Store())],
                    value=Call(
                        lineno=19,
                        col_offset=11,
                        end_lineno=19,
                        end_col_offset=51,
                        func=Attribute(
                            lineno=19,
                            col_offset=11,
                            end_lineno=19,
                            end_col_offset=22,
                            value=Name(lineno=19, col_offset=11, end_lineno=19, end_col_offset=17, id='fields', ctx=Load()),
                            attr='Char',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=19, col_offset=23, end_lineno=19, end_col_offset=35, value='Model name', kind=None)],
                        keywords=[
                            keyword(
                                lineno=19,
                                col_offset=37,
                                end_lineno=19,
                                end_col_offset=50,
                                arg='required',
                                value=Constant(lineno=19, col_offset=46, end_lineno=19, end_col_offset=50, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=20,
                    col_offset=4,
                    end_lineno=20,
                    end_col_offset=126,
                    targets=[Name(lineno=20, col_offset=4, end_lineno=20, end_col_offset=12, id='brand_id', ctx=Store())],
                    value=Call(
                        lineno=20,
                        col_offset=15,
                        end_lineno=20,
                        end_col_offset=126,
                        func=Attribute(
                            lineno=20,
                            col_offset=15,
                            end_lineno=20,
                            end_col_offset=30,
                            value=Name(lineno=20, col_offset=15, end_lineno=20, end_col_offset=21, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[
                            Constant(lineno=20, col_offset=31, end_lineno=20, end_col_offset=58, value='fleet.vehicle.model.brand', kind=None),
                            Constant(lineno=20, col_offset=60, end_lineno=20, end_col_offset=74, value='Manufacturer', kind=None),
                        ],
                        keywords=[
                            keyword(
                                lineno=20,
                                col_offset=76,
                                end_lineno=20,
                                end_col_offset=89,
                                arg='required',
                                value=Constant(lineno=20, col_offset=85, end_lineno=20, end_col_offset=89, value=True, kind=None),
                            ),
                            keyword(
                                lineno=20,
                                col_offset=91,
                                end_lineno=20,
                                end_col_offset=125,
                                arg='help',
                                value=Constant(lineno=20, col_offset=96, end_lineno=20, end_col_offset=125, value='Manufacturer of the vehicle', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=21,
                    col_offset=4,
                    end_lineno=21,
                    end_col_offset=77,
                    targets=[Name(lineno=21, col_offset=4, end_lineno=21, end_col_offset=15, id='category_id', ctx=Store())],
                    value=Call(
                        lineno=21,
                        col_offset=18,
                        end_lineno=21,
                        end_col_offset=77,
                        func=Attribute(
                            lineno=21,
                            col_offset=18,
                            end_lineno=21,
                            end_col_offset=33,
                            value=Name(lineno=21, col_offset=18, end_lineno=21, end_col_offset=24, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[
                            Constant(lineno=21, col_offset=34, end_lineno=21, end_col_offset=64, value='fleet.vehicle.model.category', kind=None),
                            Constant(lineno=21, col_offset=66, end_lineno=21, end_col_offset=76, value='Category', kind=None),
                        ],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=22,
                    col_offset=4,
                    end_lineno=22,
                    end_col_offset=120,
                    targets=[Name(lineno=22, col_offset=4, end_lineno=22, end_col_offset=11, id='vendors', ctx=Store())],
                    value=Call(
                        lineno=22,
                        col_offset=14,
                        end_lineno=22,
                        end_col_offset=120,
                        func=Attribute(
                            lineno=22,
                            col_offset=14,
                            end_lineno=22,
                            end_col_offset=30,
                            value=Name(lineno=22, col_offset=14, end_lineno=22, end_col_offset=20, id='fields', ctx=Load()),
                            attr='Many2many',
                            ctx=Load(),
                        ),
                        args=[
                            Constant(lineno=22, col_offset=31, end_lineno=22, end_col_offset=44, value='res.partner', kind=None),
                            Constant(lineno=22, col_offset=46, end_lineno=22, end_col_offset=75, value='fleet_vehicle_model_vendors', kind=None),
                            Constant(lineno=22, col_offset=77, end_lineno=22, end_col_offset=87, value='model_id', kind=None),
                            Constant(lineno=22, col_offset=89, end_lineno=22, end_col_offset=101, value='partner_id', kind=None),
                        ],
                        keywords=[
                            keyword(
                                lineno=22,
                                col_offset=103,
                                end_lineno=22,
                                end_col_offset=119,
                                arg='string',
                                value=Constant(lineno=22, col_offset=110, end_lineno=22, end_col_offset=119, value='Vendors', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=23,
                    col_offset=4,
                    end_lineno=23,
                    end_col_offset=73,
                    targets=[Name(lineno=23, col_offset=4, end_lineno=23, end_col_offset=13, id='image_128', ctx=Store())],
                    value=Call(
                        lineno=23,
                        col_offset=16,
                        end_lineno=23,
                        end_col_offset=73,
                        func=Attribute(
                            lineno=23,
                            col_offset=16,
                            end_lineno=23,
                            end_col_offset=28,
                            value=Name(lineno=23, col_offset=16, end_lineno=23, end_col_offset=22, id='fields', ctx=Load()),
                            attr='Image',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=23,
                                col_offset=29,
                                end_lineno=23,
                                end_col_offset=57,
                                arg='related',
                                value=Constant(lineno=23, col_offset=37, end_lineno=23, end_col_offset=57, value='brand_id.image_128', kind=None),
                            ),
                            keyword(
                                lineno=23,
                                col_offset=59,
                                end_lineno=23,
                                end_col_offset=72,
                                arg='readonly',
                                value=Constant(lineno=23, col_offset=68, end_lineno=23, end_col_offset=72, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=24,
                    col_offset=4,
                    end_lineno=24,
                    end_col_offset=41,
                    targets=[Name(lineno=24, col_offset=4, end_lineno=24, end_col_offset=10, id='active', ctx=Store())],
                    value=Call(
                        lineno=24,
                        col_offset=13,
                        end_lineno=24,
                        end_col_offset=41,
                        func=Attribute(
                            lineno=24,
                            col_offset=13,
                            end_lineno=24,
                            end_col_offset=27,
                            value=Name(lineno=24, col_offset=13, end_lineno=24, end_col_offset=19, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=24,
                                col_offset=28,
                                end_lineno=24,
                                end_col_offset=40,
                                arg='default',
                                value=Constant(lineno=24, col_offset=36, end_lineno=24, end_col_offset=40, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=25,
                    col_offset=4,
                    end_lineno=25,
                    end_col_offset=101,
                    targets=[Name(lineno=25, col_offset=4, end_lineno=25, end_col_offset=16, id='vehicle_type', ctx=Store())],
                    value=Call(
                        lineno=25,
                        col_offset=19,
                        end_lineno=25,
                        end_col_offset=101,
                        func=Attribute(
                            lineno=25,
                            col_offset=19,
                            end_lineno=25,
                            end_col_offset=35,
                            value=Name(lineno=25, col_offset=19, end_lineno=25, end_col_offset=25, id='fields', ctx=Load()),
                            attr='Selection',
                            ctx=Load(),
                        ),
                        args=[
                            List(
                                lineno=25,
                                col_offset=36,
                                end_lineno=25,
                                end_col_offset=70,
                                elts=[
                                    Tuple(
                                        lineno=25,
                                        col_offset=37,
                                        end_lineno=25,
                                        end_col_offset=51,
                                        elts=[
                                            Constant(lineno=25, col_offset=38, end_lineno=25, end_col_offset=43, value='car', kind=None),
                                            Constant(lineno=25, col_offset=45, end_lineno=25, end_col_offset=50, value='Car', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                    Tuple(
                                        lineno=25,
                                        col_offset=53,
                                        end_lineno=25,
                                        end_col_offset=69,
                                        elts=[
                                            Constant(lineno=25, col_offset=54, end_lineno=25, end_col_offset=60, value='bike', kind=None),
                                            Constant(lineno=25, col_offset=62, end_lineno=25, end_col_offset=68, value='Bike', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                ctx=Load(),
                            ),
                        ],
                        keywords=[
                            keyword(
                                lineno=25,
                                col_offset=72,
                                end_lineno=25,
                                end_col_offset=85,
                                arg='default',
                                value=Constant(lineno=25, col_offset=80, end_lineno=25, end_col_offset=85, value='car', kind=None),
                            ),
                            keyword(
                                lineno=25,
                                col_offset=87,
                                end_lineno=25,
                                end_col_offset=100,
                                arg='required',
                                value=Constant(lineno=25, col_offset=96, end_lineno=25, end_col_offset=100, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=26,
                    col_offset=4,
                    end_lineno=26,
                    end_col_offset=144,
                    targets=[Name(lineno=26, col_offset=4, end_lineno=26, end_col_offset=16, id='transmission', ctx=Store())],
                    value=Call(
                        lineno=26,
                        col_offset=19,
                        end_lineno=26,
                        end_col_offset=144,
                        func=Attribute(
                            lineno=26,
                            col_offset=19,
                            end_lineno=26,
                            end_col_offset=35,
                            value=Name(lineno=26, col_offset=19, end_lineno=26, end_col_offset=25, id='fields', ctx=Load()),
                            attr='Selection',
                            ctx=Load(),
                        ),
                        args=[
                            List(
                                lineno=26,
                                col_offset=36,
                                end_lineno=26,
                                end_col_offset=86,
                                elts=[
                                    Tuple(
                                        lineno=26,
                                        col_offset=37,
                                        end_lineno=26,
                                        end_col_offset=57,
                                        elts=[
                                            Constant(lineno=26, col_offset=38, end_lineno=26, end_col_offset=46, value='manual', kind=None),
                                            Constant(lineno=26, col_offset=48, end_lineno=26, end_col_offset=56, value='Manual', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                    Tuple(
                                        lineno=26,
                                        col_offset=59,
                                        end_lineno=26,
                                        end_col_offset=85,
                                        elts=[
                                            Constant(lineno=26, col_offset=60, end_lineno=26, end_col_offset=71, value='automatic', kind=None),
                                            Constant(lineno=26, col_offset=73, end_lineno=26, end_col_offset=84, value='Automatic', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                ctx=Load(),
                            ),
                            Constant(lineno=26, col_offset=88, end_lineno=26, end_col_offset=102, value='Transmission', kind=None),
                        ],
                        keywords=[
                            keyword(
                                lineno=26,
                                col_offset=104,
                                end_lineno=26,
                                end_col_offset=143,
                                arg='help',
                                value=Constant(lineno=26, col_offset=109, end_lineno=26, end_col_offset=143, value='Transmission Used by the vehicle', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=27,
                    col_offset=4,
                    end_lineno=27,
                    end_col_offset=68,
                    targets=[Name(lineno=27, col_offset=4, end_lineno=27, end_col_offset=17, id='vehicle_count', ctx=Store())],
                    value=Call(
                        lineno=27,
                        col_offset=20,
                        end_lineno=27,
                        end_col_offset=68,
                        func=Attribute(
                            lineno=27,
                            col_offset=20,
                            end_lineno=27,
                            end_col_offset=34,
                            value=Name(lineno=27, col_offset=20, end_lineno=27, end_col_offset=26, id='fields', ctx=Load()),
                            attr='Integer',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=27,
                                col_offset=35,
                                end_lineno=27,
                                end_col_offset=67,
                                arg='compute',
                                value=Constant(lineno=27, col_offset=43, end_lineno=27, end_col_offset=67, value='_compute_vehicle_count', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=28,
                    col_offset=4,
                    end_lineno=28,
                    end_col_offset=33,
                    targets=[Name(lineno=28, col_offset=4, end_lineno=28, end_col_offset=14, id='model_year', ctx=Store())],
                    value=Call(
                        lineno=28,
                        col_offset=17,
                        end_lineno=28,
                        end_col_offset=33,
                        func=Attribute(
                            lineno=28,
                            col_offset=17,
                            end_lineno=28,
                            end_col_offset=31,
                            value=Name(lineno=28, col_offset=17, end_lineno=28, end_col_offset=23, id='fields', ctx=Load()),
                            attr='Integer',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=29,
                    col_offset=4,
                    end_lineno=29,
                    end_col_offset=25,
                    targets=[Name(lineno=29, col_offset=4, end_lineno=29, end_col_offset=9, id='color', ctx=Store())],
                    value=Call(
                        lineno=29,
                        col_offset=12,
                        end_lineno=29,
                        end_col_offset=25,
                        func=Attribute(
                            lineno=29,
                            col_offset=12,
                            end_lineno=29,
                            end_col_offset=23,
                            value=Name(lineno=29, col_offset=12, end_lineno=29, end_col_offset=18, id='fields', ctx=Load()),
                            attr='Char',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=30,
                    col_offset=4,
                    end_lineno=30,
                    end_col_offset=49,
                    targets=[Name(lineno=30, col_offset=4, end_lineno=30, end_col_offset=9, id='seats', ctx=Store())],
                    value=Call(
                        lineno=30,
                        col_offset=12,
                        end_lineno=30,
                        end_col_offset=49,
                        func=Attribute(
                            lineno=30,
                            col_offset=12,
                            end_lineno=30,
                            end_col_offset=26,
                            value=Name(lineno=30, col_offset=12, end_lineno=30, end_col_offset=18, id='fields', ctx=Load()),
                            attr='Integer',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=30,
                                col_offset=27,
                                end_lineno=30,
                                end_col_offset=48,
                                arg='string',
                                value=Constant(lineno=30, col_offset=34, end_lineno=30, end_col_offset=48, value='Seats Number', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=31,
                    col_offset=4,
                    end_lineno=31,
                    end_col_offset=49,
                    targets=[Name(lineno=31, col_offset=4, end_lineno=31, end_col_offset=9, id='doors', ctx=Store())],
                    value=Call(
                        lineno=31,
                        col_offset=12,
                        end_lineno=31,
                        end_col_offset=49,
                        func=Attribute(
                            lineno=31,
                            col_offset=12,
                            end_lineno=31,
                            end_col_offset=26,
                            value=Name(lineno=31, col_offset=12, end_lineno=31, end_col_offset=18, id='fields', ctx=Load()),
                            attr='Integer',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=31,
                                col_offset=27,
                                end_lineno=31,
                                end_col_offset=48,
                                arg='string',
                                value=Constant(lineno=31, col_offset=34, end_lineno=31, end_col_offset=48, value='Doors Number', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=32,
                    col_offset=4,
                    end_lineno=32,
                    end_col_offset=72,
                    targets=[Name(lineno=32, col_offset=4, end_lineno=32, end_col_offset=16, id='trailer_hook', ctx=Store())],
                    value=Call(
                        lineno=32,
                        col_offset=19,
                        end_lineno=32,
                        end_col_offset=72,
                        func=Attribute(
                            lineno=32,
                            col_offset=19,
                            end_lineno=32,
                            end_col_offset=33,
                            value=Name(lineno=32, col_offset=19, end_lineno=32, end_col_offset=25, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=32,
                                col_offset=34,
                                end_lineno=32,
                                end_col_offset=47,
                                arg='default',
                                value=Constant(lineno=32, col_offset=42, end_lineno=32, end_col_offset=47, value=False, kind=None),
                            ),
                            keyword(
                                lineno=32,
                                col_offset=49,
                                end_lineno=32,
                                end_col_offset=71,
                                arg='string',
                                value=Constant(lineno=32, col_offset=56, end_lineno=32, end_col_offset=71, value='Trailer Hitch', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=33,
                    col_offset=4,
                    end_lineno=33,
                    end_col_offset=47,
                    targets=[Name(lineno=33, col_offset=4, end_lineno=33, end_col_offset=15, id='default_co2', ctx=Store())],
                    value=Call(
                        lineno=33,
                        col_offset=18,
                        end_lineno=33,
                        end_col_offset=47,
                        func=Attribute(
                            lineno=33,
                            col_offset=18,
                            end_lineno=33,
                            end_col_offset=30,
                            value=Name(lineno=33, col_offset=18, end_lineno=33, end_col_offset=24, id='fields', ctx=Load()),
                            attr='Float',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=33, col_offset=31, end_lineno=33, end_col_offset=46, value='CO2 Emissions', kind=None)],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=34,
                    col_offset=4,
                    end_lineno=34,
                    end_col_offset=32,
                    targets=[Name(lineno=34, col_offset=4, end_lineno=34, end_col_offset=16, id='co2_standard', ctx=Store())],
                    value=Call(
                        lineno=34,
                        col_offset=19,
                        end_lineno=34,
                        end_col_offset=32,
                        func=Attribute(
                            lineno=34,
                            col_offset=19,
                            end_lineno=34,
                            end_col_offset=30,
                            value=Name(lineno=34, col_offset=19, end_lineno=34, end_col_offset=25, id='fields', ctx=Load()),
                            attr='Char',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=35,
                    col_offset=4,
                    end_lineno=35,
                    end_col_offset=83,
                    targets=[Name(lineno=35, col_offset=4, end_lineno=35, end_col_offset=21, id='default_fuel_type', ctx=Store())],
                    value=Call(
                        lineno=35,
                        col_offset=24,
                        end_lineno=35,
                        end_col_offset=83,
                        func=Attribute(
                            lineno=35,
                            col_offset=24,
                            end_lineno=35,
                            end_col_offset=40,
                            value=Name(lineno=35, col_offset=24, end_lineno=35, end_col_offset=30, id='fields', ctx=Load()),
                            attr='Selection',
                            ctx=Load(),
                        ),
                        args=[
                            Name(lineno=35, col_offset=41, end_lineno=35, end_col_offset=51, id='FUEL_TYPES', ctx=Load()),
                            Constant(lineno=35, col_offset=53, end_lineno=35, end_col_offset=64, value='Fuel Type', kind=None),
                        ],
                        keywords=[
                            keyword(
                                lineno=35,
                                col_offset=66,
                                end_lineno=35,
                                end_col_offset=82,
                                arg='default',
                                value=Constant(lineno=35, col_offset=74, end_lineno=35, end_col_offset=82, value='diesel', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=36,
                    col_offset=4,
                    end_lineno=36,
                    end_col_offset=35,
                    targets=[Name(lineno=36, col_offset=4, end_lineno=36, end_col_offset=9, id='power', ctx=Store())],
                    value=Call(
                        lineno=36,
                        col_offset=12,
                        end_lineno=36,
                        end_col_offset=35,
                        func=Attribute(
                            lineno=36,
                            col_offset=12,
                            end_lineno=36,
                            end_col_offset=26,
                            value=Name(lineno=36, col_offset=12, end_lineno=36, end_col_offset=18, id='fields', ctx=Load()),
                            attr='Integer',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=36, col_offset=27, end_lineno=36, end_col_offset=34, value='Power', kind=None)],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=37,
                    col_offset=4,
                    end_lineno=37,
                    end_col_offset=33,
                    targets=[Name(lineno=37, col_offset=4, end_lineno=37, end_col_offset=14, id='horsepower', ctx=Store())],
                    value=Call(
                        lineno=37,
                        col_offset=17,
                        end_lineno=37,
                        end_col_offset=33,
                        func=Attribute(
                            lineno=37,
                            col_offset=17,
                            end_lineno=37,
                            end_col_offset=31,
                            value=Name(lineno=37, col_offset=17, end_lineno=37, end_col_offset=23, id='fields', ctx=Load()),
                            attr='Integer',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=38,
                    col_offset=4,
                    end_lineno=38,
                    end_col_offset=56,
                    targets=[Name(lineno=38, col_offset=4, end_lineno=38, end_col_offset=18, id='horsepower_tax', ctx=Store())],
                    value=Call(
                        lineno=38,
                        col_offset=21,
                        end_lineno=38,
                        end_col_offset=56,
                        func=Attribute(
                            lineno=38,
                            col_offset=21,
                            end_lineno=38,
                            end_col_offset=33,
                            value=Name(lineno=38, col_offset=21, end_lineno=38, end_col_offset=27, id='fields', ctx=Load()),
                            attr='Float',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=38, col_offset=34, end_lineno=38, end_col_offset=55, value='Horsepower Taxation', kind=None)],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=39,
                    col_offset=4,
                    end_lineno=39,
                    end_col_offset=55,
                    targets=[Name(lineno=39, col_offset=4, end_lineno=39, end_col_offset=23, id='electric_assistance', ctx=Store())],
                    value=Call(
                        lineno=39,
                        col_offset=26,
                        end_lineno=39,
                        end_col_offset=55,
                        func=Attribute(
                            lineno=39,
                            col_offset=26,
                            end_lineno=39,
                            end_col_offset=40,
                            value=Name(lineno=39, col_offset=26, end_lineno=39, end_col_offset=32, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=39,
                                col_offset=41,
                                end_lineno=39,
                                end_col_offset=54,
                                arg='default',
                                value=Constant(lineno=39, col_offset=49, end_lineno=39, end_col_offset=54, value=False, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=42,
                    col_offset=4,
                    end_lineno=49,
                    end_col_offset=18,
                    name='name_get',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=42, col_offset=17, end_lineno=42, end_col_offset=21, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=43,
                            col_offset=8,
                            end_lineno=43,
                            end_col_offset=16,
                            targets=[Name(lineno=43, col_offset=8, end_lineno=43, end_col_offset=11, id='res', ctx=Store())],
                            value=List(lineno=43, col_offset=14, end_lineno=43, end_col_offset=16, elts=[], ctx=Load()),
                            type_comment=None,
                        ),
                        For(
                            lineno=44,
                            col_offset=8,
                            end_lineno=48,
                            end_col_offset=41,
                            target=Name(lineno=44, col_offset=12, end_lineno=44, end_col_offset=18, id='record', ctx=Store()),
                            iter=Name(lineno=44, col_offset=22, end_lineno=44, end_col_offset=26, id='self', ctx=Load()),
                            body=[
                                Assign(
                                    lineno=45,
                                    col_offset=12,
                                    end_lineno=45,
                                    end_col_offset=30,
                                    targets=[Name(lineno=45, col_offset=12, end_lineno=45, end_col_offset=16, id='name', ctx=Store())],
                                    value=Attribute(
                                        lineno=45,
                                        col_offset=19,
                                        end_lineno=45,
                                        end_col_offset=30,
                                        value=Name(lineno=45, col_offset=19, end_lineno=45, end_col_offset=25, id='record', ctx=Load()),
                                        attr='name',
                                        ctx=Load(),
                                    ),
                                    type_comment=None,
                                ),
                                If(
                                    lineno=46,
                                    col_offset=12,
                                    end_lineno=47,
                                    end_col_offset=56,
                                    test=Attribute(
                                        lineno=46,
                                        col_offset=15,
                                        end_lineno=46,
                                        end_col_offset=35,
                                        value=Attribute(
                                            lineno=46,
                                            col_offset=15,
                                            end_lineno=46,
                                            end_col_offset=30,
                                            value=Name(lineno=46, col_offset=15, end_lineno=46, end_col_offset=21, id='record', ctx=Load()),
                                            attr='brand_id',
                                            ctx=Load(),
                                        ),
                                        attr='name',
                                        ctx=Load(),
                                    ),
                                    body=[
                                        Assign(
                                            lineno=47,
                                            col_offset=16,
                                            end_lineno=47,
                                            end_col_offset=56,
                                            targets=[Name(lineno=47, col_offset=16, end_lineno=47, end_col_offset=20, id='name', ctx=Store())],
                                            value=BinOp(
                                                lineno=47,
                                                col_offset=23,
                                                end_lineno=47,
                                                end_col_offset=56,
                                                left=BinOp(
                                                    lineno=47,
                                                    col_offset=23,
                                                    end_lineno=47,
                                                    end_col_offset=49,
                                                    left=Attribute(
                                                        lineno=47,
                                                        col_offset=23,
                                                        end_lineno=47,
                                                        end_col_offset=43,
                                                        value=Attribute(
                                                            lineno=47,
                                                            col_offset=23,
                                                            end_lineno=47,
                                                            end_col_offset=38,
                                                            value=Name(lineno=47, col_offset=23, end_lineno=47, end_col_offset=29, id='record', ctx=Load()),
                                                            attr='brand_id',
                                                            ctx=Load(),
                                                        ),
                                                        attr='name',
                                                        ctx=Load(),
                                                    ),
                                                    op=Add(),
                                                    right=Constant(lineno=47, col_offset=46, end_lineno=47, end_col_offset=49, value='/', kind=None),
                                                ),
                                                op=Add(),
                                                right=Name(lineno=47, col_offset=52, end_lineno=47, end_col_offset=56, id='name', ctx=Load()),
                                            ),
                                            type_comment=None,
                                        ),
                                    ],
                                    orelse=[],
                                ),
                                Expr(
                                    lineno=48,
                                    col_offset=12,
                                    end_lineno=48,
                                    end_col_offset=41,
                                    value=Call(
                                        lineno=48,
                                        col_offset=12,
                                        end_lineno=48,
                                        end_col_offset=41,
                                        func=Attribute(
                                            lineno=48,
                                            col_offset=12,
                                            end_lineno=48,
                                            end_col_offset=22,
                                            value=Name(lineno=48, col_offset=12, end_lineno=48, end_col_offset=15, id='res', ctx=Load()),
                                            attr='append',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Tuple(
                                                lineno=48,
                                                col_offset=23,
                                                end_lineno=48,
                                                end_col_offset=40,
                                                elts=[
                                                    Attribute(
                                                        lineno=48,
                                                        col_offset=24,
                                                        end_lineno=48,
                                                        end_col_offset=33,
                                                        value=Name(lineno=48, col_offset=24, end_lineno=48, end_col_offset=30, id='record', ctx=Load()),
                                                        attr='id',
                                                        ctx=Load(),
                                                    ),
                                                    Name(lineno=48, col_offset=35, end_lineno=48, end_col_offset=39, id='name', ctx=Load()),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                ),
                            ],
                            orelse=[],
                            type_comment=None,
                        ),
                        Return(
                            lineno=49,
                            col_offset=8,
                            end_lineno=49,
                            end_col_offset=18,
                            value=Name(lineno=49, col_offset=15, end_lineno=49, end_col_offset=18, id='res', ctx=Load()),
                        ),
                    ],
                    decorator_list=[
                        Call(
                            lineno=41,
                            col_offset=5,
                            end_lineno=41,
                            end_col_offset=36,
                            func=Attribute(
                                lineno=41,
                                col_offset=5,
                                end_lineno=41,
                                end_col_offset=16,
                                value=Name(lineno=41, col_offset=5, end_lineno=41, end_col_offset=8, id='api', ctx=Load()),
                                attr='depends',
                                ctx=Load(),
                            ),
                            args=[
                                Constant(lineno=41, col_offset=17, end_lineno=41, end_col_offset=23, value='name', kind=None),
                                Constant(lineno=41, col_offset=25, end_lineno=41, end_col_offset=35, value='brand_id', kind=None),
                            ],
                            keywords=[],
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=51,
                    col_offset=4,
                    end_lineno=57,
                    end_col_offset=65,
                    name='_compute_vehicle_count',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=51, col_offset=31, end_lineno=51, end_col_offset=35, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=52,
                            col_offset=8,
                            end_lineno=54,
                            end_col_offset=9,
                            targets=[Name(lineno=52, col_offset=8, end_lineno=52, end_col_offset=13, id='group', ctx=Store())],
                            value=Call(
                                lineno=52,
                                col_offset=16,
                                end_lineno=54,
                                end_col_offset=9,
                                func=Attribute(
                                    lineno=52,
                                    col_offset=16,
                                    end_lineno=52,
                                    end_col_offset=52,
                                    value=Subscript(
                                        lineno=52,
                                        col_offset=16,
                                        end_lineno=52,
                                        end_col_offset=41,
                                        value=Attribute(
                                            lineno=52,
                                            col_offset=16,
                                            end_lineno=52,
                                            end_col_offset=24,
                                            value=Name(lineno=52, col_offset=16, end_lineno=52, end_col_offset=20, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=52, col_offset=25, end_lineno=52, end_col_offset=40, value='fleet.vehicle', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='read_group',
                                    ctx=Load(),
                                ),
                                args=[
                                    List(
                                        lineno=53,
                                        col_offset=12,
                                        end_lineno=53,
                                        end_col_offset=42,
                                        elts=[
                                            Tuple(
                                                lineno=53,
                                                col_offset=13,
                                                end_lineno=53,
                                                end_col_offset=41,
                                                elts=[
                                                    Constant(lineno=53, col_offset=14, end_lineno=53, end_col_offset=24, value='model_id', kind=None),
                                                    Constant(lineno=53, col_offset=26, end_lineno=53, end_col_offset=30, value='in', kind=None),
                                                    Attribute(
                                                        lineno=53,
                                                        col_offset=32,
                                                        end_lineno=53,
                                                        end_col_offset=40,
                                                        value=Name(lineno=53, col_offset=32, end_lineno=53, end_col_offset=36, id='self', ctx=Load()),
                                                        attr='ids',
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                    List(
                                        lineno=53,
                                        col_offset=44,
                                        end_lineno=53,
                                        end_col_offset=62,
                                        elts=[
                                            Constant(lineno=53, col_offset=45, end_lineno=53, end_col_offset=49, value='id', kind=None),
                                            Constant(lineno=53, col_offset=51, end_lineno=53, end_col_offset=61, value='model_id', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[
                                    keyword(
                                        lineno=53,
                                        col_offset=64,
                                        end_lineno=53,
                                        end_col_offset=82,
                                        arg='groupby',
                                        value=Constant(lineno=53, col_offset=72, end_lineno=53, end_col_offset=82, value='model_id', kind=None),
                                    ),
                                    keyword(
                                        lineno=53,
                                        col_offset=84,
                                        end_lineno=53,
                                        end_col_offset=94,
                                        arg='lazy',
                                        value=Constant(lineno=53, col_offset=89, end_lineno=53, end_col_offset=94, value=False, kind=None),
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=55,
                            col_offset=8,
                            end_lineno=55,
                            end_col_offset=84,
                            targets=[Name(lineno=55, col_offset=8, end_lineno=55, end_col_offset=22, id='count_by_model', ctx=Store())],
                            value=DictComp(
                                lineno=55,
                                col_offset=25,
                                end_lineno=55,
                                end_col_offset=84,
                                key=Subscript(
                                    lineno=55,
                                    col_offset=26,
                                    end_lineno=55,
                                    end_col_offset=46,
                                    value=Subscript(
                                        lineno=55,
                                        col_offset=26,
                                        end_lineno=55,
                                        end_col_offset=43,
                                        value=Name(lineno=55, col_offset=26, end_lineno=55, end_col_offset=31, id='entry', ctx=Load()),
                                        slice=Constant(lineno=55, col_offset=32, end_lineno=55, end_col_offset=42, value='model_id', kind=None),
                                        ctx=Load(),
                                    ),
                                    slice=Constant(lineno=55, col_offset=44, end_lineno=55, end_col_offset=45, value=0, kind=None),
                                    ctx=Load(),
                                ),
                                value=Subscript(
                                    lineno=55,
                                    col_offset=48,
                                    end_lineno=55,
                                    end_col_offset=64,
                                    value=Name(lineno=55, col_offset=48, end_lineno=55, end_col_offset=53, id='entry', ctx=Load()),
                                    slice=Constant(lineno=55, col_offset=54, end_lineno=55, end_col_offset=63, value='__count', kind=None),
                                    ctx=Load(),
                                ),
                                generators=[
                                    comprehension(
                                        target=Name(lineno=55, col_offset=69, end_lineno=55, end_col_offset=74, id='entry', ctx=Store()),
                                        iter=Name(lineno=55, col_offset=78, end_lineno=55, end_col_offset=83, id='group', ctx=Load()),
                                        ifs=[],
                                        is_async=0,
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                        For(
                            lineno=56,
                            col_offset=8,
                            end_lineno=57,
                            end_col_offset=65,
                            target=Name(lineno=56, col_offset=12, end_lineno=56, end_col_offset=17, id='model', ctx=Store()),
                            iter=Name(lineno=56, col_offset=21, end_lineno=56, end_col_offset=25, id='self', ctx=Load()),
                            body=[
                                Assign(
                                    lineno=57,
                                    col_offset=12,
                                    end_lineno=57,
                                    end_col_offset=65,
                                    targets=[
                                        Attribute(
                                            lineno=57,
                                            col_offset=12,
                                            end_lineno=57,
                                            end_col_offset=31,
                                            value=Name(lineno=57, col_offset=12, end_lineno=57, end_col_offset=17, id='model', ctx=Load()),
                                            attr='vehicle_count',
                                            ctx=Store(),
                                        ),
                                    ],
                                    value=Call(
                                        lineno=57,
                                        col_offset=34,
                                        end_lineno=57,
                                        end_col_offset=65,
                                        func=Attribute(
                                            lineno=57,
                                            col_offset=34,
                                            end_lineno=57,
                                            end_col_offset=52,
                                            value=Name(lineno=57, col_offset=34, end_lineno=57, end_col_offset=48, id='count_by_model', ctx=Load()),
                                            attr='get',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Attribute(
                                                lineno=57,
                                                col_offset=53,
                                                end_lineno=57,
                                                end_col_offset=61,
                                                value=Name(lineno=57, col_offset=53, end_lineno=57, end_col_offset=58, id='model', ctx=Load()),
                                                attr='id',
                                                ctx=Load(),
                                            ),
                                            Constant(lineno=57, col_offset=63, end_lineno=57, end_col_offset=64, value=0, kind=None),
                                        ],
                                        keywords=[],
                                    ),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[],
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=59,
                    col_offset=4,
                    end_lineno=69,
                    end_col_offset=19,
                    name='action_model_vehicle',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=59, col_offset=29, end_lineno=59, end_col_offset=33, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=60,
                            col_offset=8,
                            end_lineno=60,
                            end_col_offset=25,
                            value=Call(
                                lineno=60,
                                col_offset=8,
                                end_lineno=60,
                                end_col_offset=25,
                                func=Attribute(
                                    lineno=60,
                                    col_offset=8,
                                    end_lineno=60,
                                    end_col_offset=23,
                                    value=Name(lineno=60, col_offset=8, end_lineno=60, end_col_offset=12, id='self', ctx=Load()),
                                    attr='ensure_one',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=61,
                            col_offset=8,
                            end_lineno=67,
                            end_col_offset=9,
                            targets=[Name(lineno=61, col_offset=8, end_lineno=61, end_col_offset=12, id='view', ctx=Store())],
                            value=Dict(
                                lineno=61,
                                col_offset=15,
                                end_lineno=67,
                                end_col_offset=9,
                                keys=[
                                    Constant(lineno=62, col_offset=12, end_lineno=62, end_col_offset=18, value='type', kind=None),
                                    Constant(lineno=63, col_offset=12, end_lineno=63, end_col_offset=23, value='view_mode', kind=None),
                                    Constant(lineno=64, col_offset=12, end_lineno=64, end_col_offset=23, value='res_model', kind=None),
                                    Constant(lineno=65, col_offset=12, end_lineno=65, end_col_offset=18, value='name', kind=None),
                                    Constant(lineno=66, col_offset=12, end_lineno=66, end_col_offset=21, value='context', kind=None),
                                ],
                                values=[
                                    Constant(lineno=62, col_offset=20, end_lineno=62, end_col_offset=43, value='ir.actions.act_window', kind=None),
                                    Constant(lineno=63, col_offset=25, end_lineno=63, end_col_offset=43, value='kanban,tree,form', kind=None),
                                    Constant(lineno=64, col_offset=25, end_lineno=64, end_col_offset=40, value='fleet.vehicle', kind=None),
                                    Call(
                                        lineno=65,
                                        col_offset=20,
                                        end_lineno=65,
                                        end_col_offset=33,
                                        func=Name(lineno=65, col_offset=20, end_lineno=65, end_col_offset=21, id='_', ctx=Load()),
                                        args=[Constant(lineno=65, col_offset=22, end_lineno=65, end_col_offset=32, value='Vehicles', kind=None)],
                                        keywords=[],
                                    ),
                                    Dict(
                                        lineno=66,
                                        col_offset=23,
                                        end_lineno=66,
                                        end_col_offset=88,
                                        keys=[
                                            Constant(lineno=66, col_offset=24, end_lineno=66, end_col_offset=49, value='search_default_model_id', kind=None),
                                            Constant(lineno=66, col_offset=60, end_lineno=66, end_col_offset=78, value='default_model_id', kind=None),
                                        ],
                                        values=[
                                            Attribute(
                                                lineno=66,
                                                col_offset=51,
                                                end_lineno=66,
                                                end_col_offset=58,
                                                value=Name(lineno=66, col_offset=51, end_lineno=66, end_col_offset=55, id='self', ctx=Load()),
                                                attr='id',
                                                ctx=Load(),
                                            ),
                                            Attribute(
                                                lineno=66,
                                                col_offset=80,
                                                end_lineno=66,
                                                end_col_offset=87,
                                                value=Name(lineno=66, col_offset=80, end_lineno=66, end_col_offset=84, id='self', ctx=Load()),
                                                attr='id',
                                                ctx=Load(),
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                        Return(
                            lineno=69,
                            col_offset=8,
                            end_lineno=69,
                            end_col_offset=19,
                            value=Name(lineno=69, col_offset=15, end_lineno=69, end_col_offset=19, id='view', ctx=Load()),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
