Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=31,
            module='odoo',
            names=[
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=11,
            end_col_offset=136,
            name='DeliveryCarrier',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=22,
                    end_lineno=7,
                    end_col_offset=34,
                    value=Name(lineno=7, col_offset=22, end_lineno=7, end_col_offset=28, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=30,
                    targets=[Name(lineno=8, col_offset=4, end_lineno=8, end_col_offset=9, id='_name', ctx=Store())],
                    value=Constant(lineno=8, col_offset=12, end_lineno=8, end_col_offset=30, value='delivery.carrier', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=9,
                    col_offset=4,
                    end_lineno=9,
                    end_col_offset=68,
                    targets=[Name(lineno=9, col_offset=4, end_lineno=9, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=List(
                        lineno=9,
                        col_offset=15,
                        end_lineno=9,
                        end_col_offset=68,
                        elts=[
                            Constant(lineno=9, col_offset=16, end_lineno=9, end_col_offset=34, value='delivery.carrier', kind=None),
                            Constant(lineno=9, col_offset=36, end_lineno=9, end_col_offset=67, value='website.published.multi.mixin', kind=None),
                        ],
                        ctx=Load(),
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=11,
                    col_offset=4,
                    end_lineno=11,
                    end_col_offset=136,
                    targets=[Name(lineno=11, col_offset=4, end_lineno=11, end_col_offset=23, id='website_description', ctx=Store())],
                    value=Call(
                        lineno=11,
                        col_offset=26,
                        end_lineno=11,
                        end_col_offset=136,
                        func=Attribute(
                            lineno=11,
                            col_offset=26,
                            end_lineno=11,
                            end_col_offset=37,
                            value=Name(lineno=11, col_offset=26, end_lineno=11, end_col_offset=32, id='fields', ctx=Load()),
                            attr='Text',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=11,
                                col_offset=38,
                                end_lineno=11,
                                end_col_offset=75,
                                arg='related',
                                value=Constant(lineno=11, col_offset=46, end_lineno=11, end_col_offset=75, value='product_id.description_sale', kind=None),
                            ),
                            keyword(
                                lineno=11,
                                col_offset=77,
                                end_lineno=11,
                                end_col_offset=119,
                                arg='string',
                                value=Constant(lineno=11, col_offset=84, end_lineno=11, end_col_offset=119, value='Description for Online Quotations', kind=None),
                            ),
                            keyword(
                                lineno=11,
                                col_offset=121,
                                end_lineno=11,
                                end_col_offset=135,
                                arg='readonly',
                                value=Constant(lineno=11, col_offset=130, end_lineno=11, end_col_offset=135, value=False, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
