Module(
    body=[
        Expr(
            value=Constant(value=' ESC/POS Commands (Constants) ', kind=None),
        ),
        Assign(
            targets=[Name(id='ESC', ctx=Store())],
            value=Constant(value='\x1b', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='CTL_LF', ctx=Store())],
            value=Constant(value='\n', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='CTL_FF', ctx=Store())],
            value=Constant(value='\x0c', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='CTL_CR', ctx=Store())],
            value=Constant(value='\r', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='CTL_HT', ctx=Store())],
            value=Constant(value='\t', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='CTL_VT', ctx=Store())],
            value=Constant(value='\x0b', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='DLE_EOT_PRINTER', ctx=Store())],
            value=Constant(value='\x10\x04\x01', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='DLE_EOT_OFFLINE', ctx=Store())],
            value=Constant(value='\x10\x04\x02', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='DLE_EOT_ERROR', ctx=Store())],
            value=Constant(value='\x10\x04\x03', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='DLE_EOT_PAPER', ctx=Store())],
            value=Constant(value='\x10\x04\x04', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='HW_INIT', ctx=Store())],
            value=Constant(value='\x1b@', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='HW_SELECT', ctx=Store())],
            value=Constant(value='\x1b=\x01', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='HW_RESET', ctx=Store())],
            value=Constant(value='\x1b?\n\x00', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='_CASH_DRAWER', ctx=Store())],
            value=Lambda(
                args=arguments(
                    posonlyargs=[],
                    args=[
                        arg(arg='m', annotation=None, type_comment=None),
                        arg(arg='t1', annotation=None, type_comment=None),
                        arg(arg='t2', annotation=None, type_comment=None),
                    ],
                    vararg=None,
                    kwonlyargs=[],
                    kw_defaults=[],
                    kwarg=None,
                    defaults=[
                        Constant(value='', kind=None),
                        Constant(value='', kind=None),
                    ],
                ),
                body=BinOp(
                    left=BinOp(
                        left=BinOp(
                            left=BinOp(
                                left=Name(id='ESC', ctx=Load()),
                                op=Add(),
                                right=Constant(value='p', kind=None),
                            ),
                            op=Add(),
                            right=Name(id='m', ctx=Load()),
                        ),
                        op=Add(),
                        right=Call(
                            func=Name(id='chr', ctx=Load()),
                            args=[Name(id='t1', ctx=Load())],
                            keywords=[],
                        ),
                    ),
                    op=Add(),
                    right=Call(
                        func=Name(id='chr', ctx=Load()),
                        args=[Name(id='t2', ctx=Load())],
                        keywords=[],
                    ),
                ),
            ),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='CD_KICK_2', ctx=Store())],
            value=Call(
                func=Name(id='_CASH_DRAWER', ctx=Load()),
                args=[
                    Constant(value='\x00', kind=None),
                    Constant(value=50, kind=None),
                    Constant(value=50, kind=None),
                ],
                keywords=[],
            ),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='CD_KICK_5', ctx=Store())],
            value=Call(
                func=Name(id='_CASH_DRAWER', ctx=Load()),
                args=[
                    Constant(value='\x01', kind=None),
                    Constant(value=50, kind=None),
                    Constant(value=50, kind=None),
                ],
                keywords=[],
            ),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='PAPER_FULL_CUT', ctx=Store())],
            value=Constant(value='\x1dV\x00', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='PAPER_PART_CUT', ctx=Store())],
            value=Constant(value='\x1dV\x01', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_NORMAL', ctx=Store())],
            value=Constant(value='\x1b!\x00', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_2HEIGHT', ctx=Store())],
            value=Constant(value='\x1b!\x10', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_2WIDTH', ctx=Store())],
            value=Constant(value='\x1b! ', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_DOUBLE', ctx=Store())],
            value=Constant(value='\x1b!0', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_UNDERL_OFF', ctx=Store())],
            value=Constant(value='\x1b-\x00', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_UNDERL_ON', ctx=Store())],
            value=Constant(value='\x1b-\x01', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_UNDERL2_ON', ctx=Store())],
            value=Constant(value='\x1b-\x02', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_BOLD_OFF', ctx=Store())],
            value=Constant(value='\x1bE\x00', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_BOLD_ON', ctx=Store())],
            value=Constant(value='\x1bE\x01', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_FONT_A', ctx=Store())],
            value=Constant(value='\x1bM\x00', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_FONT_B', ctx=Store())],
            value=Constant(value='\x1bM\x01', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ALIGN_LT', ctx=Store())],
            value=Constant(value='\x1ba\x00', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ALIGN_CT', ctx=Store())],
            value=Constant(value='\x1ba\x01', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ALIGN_RT', ctx=Store())],
            value=Constant(value='\x1ba\x02', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_COLOR_BLACK', ctx=Store())],
            value=Constant(value='\x1br\x00', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_COLOR_RED', ctx=Store())],
            value=Constant(value='\x1br\x01', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC437', ctx=Store())],
            value=Constant(value='\x1bt\x00', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_KATAKANA', ctx=Store())],
            value=Constant(value='\x1bt\x01', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC850', ctx=Store())],
            value=Constant(value='\x1bt\x02', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC860', ctx=Store())],
            value=Constant(value='\x1bt\x03', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC863', ctx=Store())],
            value=Constant(value='\x1bt\x04', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC865', ctx=Store())],
            value=Constant(value='\x1bt\x05', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_KANJI6', ctx=Store())],
            value=Constant(value='\x1bt\x06', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_KANJI7', ctx=Store())],
            value=Constant(value='\x1bt\x07', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_KANJI8', ctx=Store())],
            value=Constant(value='\x1bt\x08', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC851', ctx=Store())],
            value=Constant(value='\x1bt\x0b', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC853', ctx=Store())],
            value=Constant(value='\x1bt\x0c', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC857', ctx=Store())],
            value=Constant(value='\x1bt\r', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC737', ctx=Store())],
            value=Constant(value='\x1bt\x0e', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_8859_7', ctx=Store())],
            value=Constant(value='\x1bt\x0f', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_WPC1252', ctx=Store())],
            value=Constant(value='\x1bt\x10', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC866', ctx=Store())],
            value=Constant(value='\x1bt\x11', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC852', ctx=Store())],
            value=Constant(value='\x1bt\x12', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC858', ctx=Store())],
            value=Constant(value='\x1bt\x13', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_KU42', ctx=Store())],
            value=Constant(value='\x1bt\x14', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_TIS11', ctx=Store())],
            value=Constant(value='\x1bt\x15', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_TIS18', ctx=Store())],
            value=Constant(value='\x1bt\x1a', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_TCVN3', ctx=Store())],
            value=Constant(value='\x1bt\x1e', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_TCVN3B', ctx=Store())],
            value=Constant(value='\x1bt\x1f', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC720', ctx=Store())],
            value=Constant(value='\x1bt ', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_WPC775', ctx=Store())],
            value=Constant(value='\x1bt!', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC855', ctx=Store())],
            value=Constant(value='\x1bt"', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC861', ctx=Store())],
            value=Constant(value='\x1bt#', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC862', ctx=Store())],
            value=Constant(value='\x1bt$', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC864', ctx=Store())],
            value=Constant(value='\x1bt%', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC869', ctx=Store())],
            value=Constant(value='\x1bt&', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC936', ctx=Store())],
            value=Constant(value='\x1c!\x00', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_8859_2', ctx=Store())],
            value=Constant(value="\x1bt'", kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_8859_9', ctx=Store())],
            value=Constant(value='\x1bt(', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC1098', ctx=Store())],
            value=Constant(value='\x1bt)', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC1118', ctx=Store())],
            value=Constant(value='\x1bt*', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC1119', ctx=Store())],
            value=Constant(value='\x1bt+', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_PC1125', ctx=Store())],
            value=Constant(value='\x1bt,', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_WPC1250', ctx=Store())],
            value=Constant(value='\x1bt-', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_WPC1251', ctx=Store())],
            value=Constant(value='\x1bt.', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_WPC1253', ctx=Store())],
            value=Constant(value='\x1bt/', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_WPC1254', ctx=Store())],
            value=Constant(value='\x1bt0', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_WPC1255', ctx=Store())],
            value=Constant(value='\x1bt1', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_WPC1256', ctx=Store())],
            value=Constant(value='\x1bt2', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_WPC1257', ctx=Store())],
            value=Constant(value='\x1bt3', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_WPC1258', ctx=Store())],
            value=Constant(value='\x1bt4', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_KZ1048', ctx=Store())],
            value=Constant(value='\x1bt5', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='TXT_ENC_KATAKANA_MAP', ctx=Store())],
            value=Dict(
                keys=[
                    Constant(value='ï½¡', kind=None),
                    Constant(value='ï½¢', kind=None),
                    Constant(value='ï½£', kind=None),
                    Constant(value='ï½¤', kind=None),
                    Constant(value='ï½¥', kind=None),
                    Constant(value='ï½¦', kind=None),
                    Constant(value='ï½§', kind=None),
                    Constant(value='ï½¨', kind=None),
                    Constant(value='ï½©', kind=None),
                    Constant(value='ï½ª', kind=None),
                    Constant(value='ï½«', kind=None),
                    Constant(value='ï½¬', kind=None),
                    Constant(value='ï½\xad', kind=None),
                    Constant(value='ï½®', kind=None),
                    Constant(value='ï½¯', kind=None),
                    Constant(value='ï½°', kind=None),
                    Constant(value='ï½±', kind=None),
                    Constant(value='ï½²', kind=None),
                    Constant(value='ï½³', kind=None),
                    Constant(value='ï½´', kind=None),
                    Constant(value='ï½µ', kind=None),
                    Constant(value='ï½¶', kind=None),
                    Constant(value='ï½·', kind=None),
                    Constant(value='ï½¸', kind=None),
                    Constant(value='ï½¹', kind=None),
                    Constant(value='ï½º', kind=None),
                    Constant(value='ï½»', kind=None),
                    Constant(value='ï½¼', kind=None),
                    Constant(value='ï½½', kind=None),
                    Constant(value='ï½¾', kind=None),
                    Constant(value='ï½¿', kind=None),
                    Constant(value='ï¾\x80', kind=None),
                    Constant(value='ï¾\x81', kind=None),
                    Constant(value='ï¾\x82', kind=None),
                    Constant(value='ï¾\x83', kind=None),
                    Constant(value='ï¾\x84', kind=None),
                    Constant(value='ï¾\x85', kind=None),
                    Constant(value='ï¾\x86', kind=None),
                    Constant(value='ï¾\x87', kind=None),
                    Constant(value='ï¾\x88', kind=None),
                    Constant(value='ï¾\x89', kind=None),
                    Constant(value='ï¾\x8a', kind=None),
                    Constant(value='ï¾\x8b', kind=None),
                    Constant(value='ï¾\x8c', kind=None),
                    Constant(value='ï¾\x8d', kind=None),
                    Constant(value='ï¾\x8e', kind=None),
                    Constant(value='ï¾\x8f', kind=None),
                    Constant(value='ï¾\x90', kind=None),
                    Constant(value='ï¾\x91', kind=None),
                    Constant(value='ï¾\x92', kind=None),
                    Constant(value='ï¾\x93', kind=None),
                    Constant(value='ï¾\x94', kind=None),
                    Constant(value='ï¾\x95', kind=None),
                    Constant(value='ï¾\x96', kind=None),
                    Constant(value='ï¾\x97', kind=None),
                    Constant(value='ï¾\x98', kind=None),
                    Constant(value='ï¾\x99', kind=None),
                    Constant(value='ï¾\x9a', kind=None),
                    Constant(value='ï¾\x9b', kind=None),
                    Constant(value='ï¾\x9c', kind=None),
                    Constant(value='ï¾\x9d', kind=None),
                    Constant(value='ï¾\x9e', kind=None),
                    Constant(value='ï¾\x9f', kind=None),
                ],
                values=[
                    Constant(value='¡', kind=None),
                    Constant(value='¢', kind=None),
                    Constant(value='£', kind=None),
                    Constant(value='¤', kind=None),
                    Constant(value='¥', kind=None),
                    Constant(value='¦', kind=None),
                    Constant(value='§', kind=None),
                    Constant(value='¨', kind=None),
                    Constant(value='©', kind=None),
                    Constant(value='ª', kind=None),
                    Constant(value='«', kind=None),
                    Constant(value='¬', kind=None),
                    Constant(value='\xad', kind=None),
                    Constant(value='®', kind=None),
                    Constant(value='¯', kind=None),
                    Constant(value='°', kind=None),
                    Constant(value='±', kind=None),
                    Constant(value='²', kind=None),
                    Constant(value='³', kind=None),
                    Constant(value='´', kind=None),
                    Constant(value='µ', kind=None),
                    Constant(value='¶', kind=None),
                    Constant(value='·', kind=None),
                    Constant(value='¸', kind=None),
                    Constant(value='¹', kind=None),
                    Constant(value='º', kind=None),
                    Constant(value='»', kind=None),
                    Constant(value='¼', kind=None),
                    Constant(value='½', kind=None),
                    Constant(value='¾', kind=None),
                    Constant(value='¿', kind=None),
                    Constant(value='À', kind=None),
                    Constant(value='Á', kind=None),
                    Constant(value='Â', kind=None),
                    Constant(value='Ã', kind=None),
                    Constant(value='Ä', kind=None),
                    Constant(value='Å', kind=None),
                    Constant(value='Æ', kind=None),
                    Constant(value='Ç', kind=None),
                    Constant(value='È', kind=None),
                    Constant(value='É', kind=None),
                    Constant(value='Ê', kind=None),
                    Constant(value='Ë', kind=None),
                    Constant(value='Ì', kind=None),
                    Constant(value='Í', kind=None),
                    Constant(value='Î', kind=None),
                    Constant(value='Ï', kind=None),
                    Constant(value='Ð', kind=None),
                    Constant(value='Ñ', kind=None),
                    Constant(value='Ò', kind=None),
                    Constant(value='Ó', kind=None),
                    Constant(value='Ô', kind=None),
                    Constant(value='Õ', kind=None),
                    Constant(value='Ö', kind=None),
                    Constant(value='×', kind=None),
                    Constant(value='Ø', kind=None),
                    Constant(value='Ù', kind=None),
                    Constant(value='Ú', kind=None),
                    Constant(value='Û', kind=None),
                    Constant(value='Ü', kind=None),
                    Constant(value='Ý', kind=None),
                    Constant(value='Þ', kind=None),
                    Constant(value='ß', kind=None),
                ],
            ),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='BARCODE_TXT_OFF', ctx=Store())],
            value=Constant(value='\x1dH\x00', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='BARCODE_TXT_ABV', ctx=Store())],
            value=Constant(value='\x1dH\x01', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='BARCODE_TXT_BLW', ctx=Store())],
            value=Constant(value='\x1dH\x02', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='BARCODE_TXT_BTH', ctx=Store())],
            value=Constant(value='\x1dH\x03', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='BARCODE_FONT_A', ctx=Store())],
            value=Constant(value='\x1df\x00', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='BARCODE_FONT_B', ctx=Store())],
            value=Constant(value='\x1df\x01', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='BARCODE_HEIGHT', ctx=Store())],
            value=Constant(value='\x1dhd', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='BARCODE_WIDTH', ctx=Store())],
            value=Constant(value='\x1dw\x03', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='BARCODE_UPC_A', ctx=Store())],
            value=Constant(value='\x1dk\x00', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='BARCODE_UPC_E', ctx=Store())],
            value=Constant(value='\x1dk\x01', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='BARCODE_EAN13', ctx=Store())],
            value=Constant(value='\x1dk\x02', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='BARCODE_EAN8', ctx=Store())],
            value=Constant(value='\x1dk\x03', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='BARCODE_CODE39', ctx=Store())],
            value=Constant(value='\x1dk\x04', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='BARCODE_ITF', ctx=Store())],
            value=Constant(value='\x1dk\x05', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='BARCODE_NW7', ctx=Store())],
            value=Constant(value='\x1dk\x06', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='S_RASTER_N', ctx=Store())],
            value=Constant(value='\x1dv0\x00', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='S_RASTER_2W', ctx=Store())],
            value=Constant(value='\x1dv0\x01', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='S_RASTER_2H', ctx=Store())],
            value=Constant(value='\x1dv0\x02', kind=None),
            type_comment=None,
        ),
        Assign(
            targets=[Name(id='S_RASTER_Q', ctx=Store())],
            value=Constant(value='\x1dv0\x03', kind=None),
            type_comment=None,
        ),
    ],
    type_ignores=[],
)
