Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=36,
            module='odoo',
            names=[
                alias(name='api', asname=None),
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=36,
            end_col_offset=45,
            name='PosConfig',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=16,
                    end_lineno=7,
                    end_col_offset=28,
                    value=Name(lineno=7, col_offset=16, end_lineno=7, end_col_offset=22, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=27,
                    targets=[Name(lineno=8, col_offset=4, end_lineno=8, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=8, col_offset=15, end_lineno=8, end_col_offset=27, value='pos.config', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=10,
                    col_offset=4,
                    end_lineno=10,
                    end_col_offset=54,
                    targets=[Name(lineno=10, col_offset=4, end_lineno=10, end_col_offset=17, id='use_gift_card', ctx=Store())],
                    value=Call(
                        lineno=10,
                        col_offset=20,
                        end_lineno=10,
                        end_col_offset=54,
                        func=Attribute(
                            lineno=10,
                            col_offset=20,
                            end_lineno=10,
                            end_col_offset=34,
                            value=Name(lineno=10, col_offset=20, end_lineno=10, end_col_offset=26, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=10,
                                col_offset=35,
                                end_lineno=10,
                                end_col_offset=53,
                                arg='string',
                                value=Constant(lineno=10, col_offset=42, end_lineno=10, end_col_offset=53, value='Gift Card', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=12,
                    col_offset=4,
                    end_lineno=16,
                    end_col_offset=5,
                    targets=[Name(lineno=12, col_offset=4, end_lineno=12, end_col_offset=24, id='gift_card_product_id', ctx=Store())],
                    value=Call(
                        lineno=12,
                        col_offset=27,
                        end_lineno=16,
                        end_col_offset=5,
                        func=Attribute(
                            lineno=12,
                            col_offset=27,
                            end_lineno=12,
                            end_col_offset=42,
                            value=Name(lineno=12, col_offset=27, end_lineno=12, end_col_offset=33, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=13, col_offset=8, end_lineno=13, end_col_offset=25, value='product.product', kind=None)],
                        keywords=[
                            keyword(
                                lineno=14,
                                col_offset=8,
                                end_lineno=14,
                                end_col_offset=34,
                                arg='string',
                                value=Constant(lineno=14, col_offset=15, end_lineno=14, end_col_offset=34, value='Gift Card Product', kind=None),
                            ),
                            keyword(
                                lineno=15,
                                col_offset=8,
                                end_lineno=15,
                                end_col_offset=70,
                                arg='help',
                                value=Constant(lineno=15, col_offset=13, end_lineno=15, end_col_offset=70, value='This product is used as reference on customer receipts.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=18,
                    col_offset=4,
                    end_lineno=27,
                    end_col_offset=5,
                    targets=[Name(lineno=18, col_offset=4, end_lineno=18, end_col_offset=22, id='gift_card_settings', ctx=Store())],
                    value=Call(
                        lineno=18,
                        col_offset=25,
                        end_lineno=27,
                        end_col_offset=5,
                        func=Attribute(
                            lineno=18,
                            col_offset=25,
                            end_lineno=18,
                            end_col_offset=41,
                            value=Name(lineno=18, col_offset=25, end_lineno=18, end_col_offset=31, id='fields', ctx=Load()),
                            attr='Selection',
                            ctx=Load(),
                        ),
                        args=[
                            List(
                                lineno=19,
                                col_offset=8,
                                end_lineno=23,
                                end_col_offset=9,
                                elts=[
                                    Tuple(
                                        lineno=20,
                                        col_offset=12,
                                        end_lineno=20,
                                        end_col_offset=68,
                                        elts=[
                                            Constant(lineno=20, col_offset=13, end_lineno=20, end_col_offset=25, value='create_set', kind=None),
                                            Constant(lineno=20, col_offset=27, end_lineno=20, end_col_offset=67, value='Generate a new barcode and set a price', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                    Tuple(
                                        lineno=21,
                                        col_offset=12,
                                        end_lineno=21,
                                        end_col_offset=68,
                                        elts=[
                                            Constant(lineno=21, col_offset=13, end_lineno=21, end_col_offset=23, value='scan_set', kind=None),
                                            Constant(lineno=21, col_offset=25, end_lineno=21, end_col_offset=67, value='Scan an existing barcode and set a price', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                    Tuple(
                                        lineno=22,
                                        col_offset=12,
                                        end_lineno=22,
                                        end_col_offset=75,
                                        elts=[
                                            Constant(lineno=22, col_offset=13, end_lineno=22, end_col_offset=23, value='scan_use', kind=None),
                                            Constant(lineno=22, col_offset=25, end_lineno=22, end_col_offset=74, value='Scan an existing barcode with an existing price', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                ctx=Load(),
                            ),
                        ],
                        keywords=[
                            keyword(
                                lineno=24,
                                col_offset=8,
                                end_lineno=24,
                                end_col_offset=36,
                                arg='string',
                                value=Constant(lineno=24, col_offset=15, end_lineno=24, end_col_offset=36, value='Gift Cards settings', kind=None),
                            ),
                            keyword(
                                lineno=25,
                                col_offset=8,
                                end_lineno=25,
                                end_col_offset=28,
                                arg='default',
                                value=Constant(lineno=25, col_offset=16, end_lineno=25, end_col_offset=28, value='create_set', kind=None),
                            ),
                            keyword(
                                lineno=26,
                                col_offset=8,
                                end_lineno=26,
                                end_col_offset=63,
                                arg='help',
                                value=Constant(lineno=26, col_offset=13, end_lineno=26, end_col_offset=63, value='Defines the way you want to set your gift cards.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=30,
                    col_offset=4,
                    end_lineno=36,
                    end_col_offset=45,
                    name='_onchange_giftproduct',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=30, col_offset=30, end_lineno=30, end_col_offset=34, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        If(
                            lineno=31,
                            col_offset=8,
                            end_lineno=36,
                            end_col_offset=45,
                            test=Attribute(
                                lineno=31,
                                col_offset=11,
                                end_lineno=31,
                                end_col_offset=29,
                                value=Name(lineno=31, col_offset=11, end_lineno=31, end_col_offset=15, id='self', ctx=Load()),
                                attr='use_gift_card',
                                ctx=Load(),
                            ),
                            body=[
                                Assign(
                                    lineno=32,
                                    col_offset=12,
                                    end_lineno=34,
                                    end_col_offset=13,
                                    targets=[
                                        Attribute(
                                            lineno=32,
                                            col_offset=12,
                                            end_lineno=32,
                                            end_col_offset=37,
                                            value=Name(lineno=32, col_offset=12, end_lineno=32, end_col_offset=16, id='self', ctx=Load()),
                                            attr='gift_card_product_id',
                                            ctx=Store(),
                                        ),
                                    ],
                                    value=Call(
                                        lineno=32,
                                        col_offset=40,
                                        end_lineno=34,
                                        end_col_offset=13,
                                        func=Attribute(
                                            lineno=32,
                                            col_offset=40,
                                            end_lineno=32,
                                            end_col_offset=52,
                                            value=Attribute(
                                                lineno=32,
                                                col_offset=40,
                                                end_lineno=32,
                                                end_col_offset=48,
                                                value=Name(lineno=32, col_offset=40, end_lineno=32, end_col_offset=44, id='self', ctx=Load()),
                                                attr='env',
                                                ctx=Load(),
                                            ),
                                            attr='ref',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Constant(lineno=33, col_offset=16, end_lineno=33, end_col_offset=54, value='gift_card.pay_with_gift_card_product', kind=None),
                                            Constant(lineno=33, col_offset=56, end_lineno=33, end_col_offset=61, value=False, kind=None),
                                        ],
                                        keywords=[],
                                    ),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[
                                Assign(
                                    lineno=36,
                                    col_offset=12,
                                    end_lineno=36,
                                    end_col_offset=45,
                                    targets=[
                                        Attribute(
                                            lineno=36,
                                            col_offset=12,
                                            end_lineno=36,
                                            end_col_offset=37,
                                            value=Name(lineno=36, col_offset=12, end_lineno=36, end_col_offset=16, id='self', ctx=Load()),
                                            attr='gift_card_product_id',
                                            ctx=Store(),
                                        ),
                                    ],
                                    value=Constant(lineno=36, col_offset=40, end_lineno=36, end_col_offset=45, value=False, kind=None),
                                    type_comment=None,
                                ),
                            ],
                        ),
                    ],
                    decorator_list=[
                        Call(
                            lineno=29,
                            col_offset=5,
                            end_lineno=29,
                            end_col_offset=34,
                            func=Attribute(
                                lineno=29,
                                col_offset=5,
                                end_lineno=29,
                                end_col_offset=17,
                                value=Name(lineno=29, col_offset=5, end_lineno=29, end_col_offset=8, id='api', ctx=Load()),
                                attr='onchange',
                                ctx=Load(),
                            ),
                            args=[Constant(lineno=29, col_offset=18, end_lineno=29, end_col_offset=33, value='use_gift_card', kind=None)],
                            keywords=[],
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
