Module(
    body=[
        ImportFrom(
            lineno=3,
            col_offset=0,
            end_lineno=3,
            end_col_offset=28,
            module='odoo',
            names=[
                alias(name='api', asname=None),
                alias(name='models', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=6,
            col_offset=0,
            end_lineno=26,
            end_col_offset=24,
            name='PaymentAcquirer',
            bases=[
                Attribute(
                    lineno=6,
                    col_offset=22,
                    end_lineno=6,
                    end_col_offset=34,
                    value=Name(lineno=6, col_offset=22, end_lineno=6, end_col_offset=28, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=33,
                    targets=[Name(lineno=8, col_offset=4, end_lineno=8, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=8, col_offset=15, end_lineno=8, end_col_offset=33, value='payment.acquirer', kind=None),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=11,
                    col_offset=4,
                    end_lineno=26,
                    end_col_offset=24,
                    name='_get_compatible_acquirers',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=11, col_offset=34, end_lineno=11, end_col_offset=38, arg='self', annotation=None, type_comment=None)],
                        vararg=arg(lineno=11, col_offset=41, end_lineno=11, end_col_offset=45, arg='args', annotation=None, type_comment=None),
                        kwonlyargs=[arg(lineno=11, col_offset=47, end_lineno=11, end_col_offset=57, arg='website_id', annotation=None, type_comment=None)],
                        kw_defaults=[Constant(lineno=11, col_offset=58, end_lineno=11, end_col_offset=62, value=None, kind=None)],
                        kwarg=arg(lineno=11, col_offset=66, end_lineno=11, end_col_offset=72, arg='kwargs', annotation=None, type_comment=None),
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=12,
                            col_offset=8,
                            end_lineno=20,
                            end_col_offset=11,
                            value=Constant(lineno=12, col_offset=8, end_lineno=20, end_col_offset=11, value=' Override of payment to only return acquirers matching website-specific criteria.\n\n        In addition to the base criteria, the website must either not be set or be the same as the\n        one provided in the kwargs.\n\n        :param int website_id: The provided website, as a `website` id\n        :return: The compatible acquirers\n        :rtype: recordset of `payment.acquirer`\n        ', kind=None),
                        ),
                        Assign(
                            lineno=21,
                            col_offset=8,
                            end_lineno=21,
                            end_col_offset=93,
                            targets=[Name(lineno=21, col_offset=8, end_lineno=21, end_col_offset=17, id='acquirers', ctx=Store())],
                            value=Call(
                                lineno=21,
                                col_offset=20,
                                end_lineno=21,
                                end_col_offset=93,
                                func=Attribute(
                                    lineno=21,
                                    col_offset=20,
                                    end_lineno=21,
                                    end_col_offset=53,
                                    value=Call(
                                        lineno=21,
                                        col_offset=20,
                                        end_lineno=21,
                                        end_col_offset=27,
                                        func=Name(lineno=21, col_offset=20, end_lineno=21, end_col_offset=25, id='super', ctx=Load()),
                                        args=[],
                                        keywords=[],
                                    ),
                                    attr='_get_compatible_acquirers',
                                    ctx=Load(),
                                ),
                                args=[
                                    Starred(
                                        lineno=21,
                                        col_offset=54,
                                        end_lineno=21,
                                        end_col_offset=59,
                                        value=Name(lineno=21, col_offset=55, end_lineno=21, end_col_offset=59, id='args', ctx=Load()),
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[
                                    keyword(
                                        lineno=21,
                                        col_offset=61,
                                        end_lineno=21,
                                        end_col_offset=82,
                                        arg='website_id',
                                        value=Name(lineno=21, col_offset=72, end_lineno=21, end_col_offset=82, id='website_id', ctx=Load()),
                                    ),
                                    keyword(
                                        lineno=21,
                                        col_offset=84,
                                        end_lineno=21,
                                        end_col_offset=92,
                                        arg=None,
                                        value=Name(lineno=21, col_offset=86, end_lineno=21, end_col_offset=92, id='kwargs', ctx=Load()),
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                        If(
                            lineno=22,
                            col_offset=8,
                            end_lineno=25,
                            end_col_offset=13,
                            test=Name(lineno=22, col_offset=11, end_lineno=22, end_col_offset=21, id='website_id', ctx=Load()),
                            body=[
                                Assign(
                                    lineno=23,
                                    col_offset=12,
                                    end_lineno=25,
                                    end_col_offset=13,
                                    targets=[Name(lineno=23, col_offset=12, end_lineno=23, end_col_offset=21, id='acquirers', ctx=Store())],
                                    value=Call(
                                        lineno=23,
                                        col_offset=24,
                                        end_lineno=25,
                                        end_col_offset=13,
                                        func=Attribute(
                                            lineno=23,
                                            col_offset=24,
                                            end_lineno=23,
                                            end_col_offset=42,
                                            value=Name(lineno=23, col_offset=24, end_lineno=23, end_col_offset=33, id='acquirers', ctx=Load()),
                                            attr='filtered',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Lambda(
                                                lineno=24,
                                                col_offset=16,
                                                end_lineno=24,
                                                end_col_offset=75,
                                                args=arguments(
                                                    posonlyargs=[],
                                                    args=[arg(lineno=24, col_offset=23, end_lineno=24, end_col_offset=24, arg='a', annotation=None, type_comment=None)],
                                                    vararg=None,
                                                    kwonlyargs=[],
                                                    kw_defaults=[],
                                                    kwarg=None,
                                                    defaults=[],
                                                ),
                                                body=BoolOp(
                                                    lineno=24,
                                                    col_offset=26,
                                                    end_lineno=24,
                                                    end_col_offset=75,
                                                    op=Or(),
                                                    values=[
                                                        UnaryOp(
                                                            lineno=24,
                                                            col_offset=26,
                                                            end_lineno=24,
                                                            end_col_offset=42,
                                                            op=Not(),
                                                            operand=Attribute(
                                                                lineno=24,
                                                                col_offset=30,
                                                                end_lineno=24,
                                                                end_col_offset=42,
                                                                value=Name(lineno=24, col_offset=30, end_lineno=24, end_col_offset=31, id='a', ctx=Load()),
                                                                attr='website_id',
                                                                ctx=Load(),
                                                            ),
                                                        ),
                                                        Compare(
                                                            lineno=24,
                                                            col_offset=46,
                                                            end_lineno=24,
                                                            end_col_offset=75,
                                                            left=Attribute(
                                                                lineno=24,
                                                                col_offset=46,
                                                                end_lineno=24,
                                                                end_col_offset=61,
                                                                value=Attribute(
                                                                    lineno=24,
                                                                    col_offset=46,
                                                                    end_lineno=24,
                                                                    end_col_offset=58,
                                                                    value=Name(lineno=24, col_offset=46, end_lineno=24, end_col_offset=47, id='a', ctx=Load()),
                                                                    attr='website_id',
                                                                    ctx=Load(),
                                                                ),
                                                                attr='id',
                                                                ctx=Load(),
                                                            ),
                                                            ops=[Eq()],
                                                            comparators=[Name(lineno=24, col_offset=65, end_lineno=24, end_col_offset=75, id='website_id', ctx=Load())],
                                                        ),
                                                    ],
                                                ),
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[],
                        ),
                        Return(
                            lineno=26,
                            col_offset=8,
                            end_lineno=26,
                            end_col_offset=24,
                            value=Name(lineno=26, col_offset=15, end_lineno=26, end_col_offset=24, id='acquirers', ctx=Load()),
                        ),
                    ],
                    decorator_list=[
                        Attribute(
                            lineno=10,
                            col_offset=5,
                            end_lineno=10,
                            end_col_offset=14,
                            value=Name(lineno=10, col_offset=5, end_lineno=10, end_col_offset=8, id='api', ctx=Load()),
                            attr='model',
                            ctx=Load(),
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
