Module(
    body=[
        ImportFrom(
            lineno=2,
            col_offset=0,
            end_lineno=2,
            end_col_offset=39,
            module='odoo',
            names=[
                alias(name='api', asname=None),
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
                alias(name='_', asname=None),
            ],
            level=0,
        ),
        ImportFrom(
            lineno=3,
            col_offset=0,
            end_lineno=3,
            end_col_offset=43,
            module='odoo.exceptions',
            names=[alias(name='ValidationError', asname=None)],
            level=0,
        ),
        ClassDef(
            lineno=6,
            col_offset=0,
            end_lineno=24,
            end_col_offset=164,
            name='AccountAccountTag',
            bases=[
                Attribute(
                    lineno=6,
                    col_offset=24,
                    end_lineno=6,
                    end_col_offset=36,
                    value=Name(lineno=6, col_offset=24, end_lineno=6, end_col_offset=30, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=7,
                    col_offset=4,
                    end_lineno=7,
                    end_col_offset=33,
                    targets=[Name(lineno=7, col_offset=4, end_lineno=7, end_col_offset=9, id='_name', ctx=Store())],
                    value=Constant(lineno=7, col_offset=12, end_lineno=7, end_col_offset=33, value='account.account.tag', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=32,
                    targets=[Name(lineno=8, col_offset=4, end_lineno=8, end_col_offset=16, id='_description', ctx=Store())],
                    value=Constant(lineno=8, col_offset=19, end_lineno=8, end_col_offset=32, value='Account Tag', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=10,
                    col_offset=4,
                    end_lineno=10,
                    end_col_offset=49,
                    targets=[Name(lineno=10, col_offset=4, end_lineno=10, end_col_offset=8, id='name', ctx=Store())],
                    value=Call(
                        lineno=10,
                        col_offset=11,
                        end_lineno=10,
                        end_col_offset=49,
                        func=Attribute(
                            lineno=10,
                            col_offset=11,
                            end_lineno=10,
                            end_col_offset=22,
                            value=Name(lineno=10, col_offset=11, end_lineno=10, end_col_offset=17, id='fields', ctx=Load()),
                            attr='Char',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=10, col_offset=23, end_lineno=10, end_col_offset=33, value='Tag Name', kind=None)],
                        keywords=[
                            keyword(
                                lineno=10,
                                col_offset=35,
                                end_lineno=10,
                                end_col_offset=48,
                                arg='required',
                                value=Constant(lineno=10, col_offset=44, end_lineno=10, end_col_offset=48, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=11,
                    col_offset=4,
                    end_lineno=11,
                    end_col_offset=145,
                    targets=[Name(lineno=11, col_offset=4, end_lineno=11, end_col_offset=17, id='applicability', ctx=Store())],
                    value=Call(
                        lineno=11,
                        col_offset=20,
                        end_lineno=11,
                        end_col_offset=145,
                        func=Attribute(
                            lineno=11,
                            col_offset=20,
                            end_lineno=11,
                            end_col_offset=36,
                            value=Name(lineno=11, col_offset=20, end_lineno=11, end_col_offset=26, id='fields', ctx=Load()),
                            attr='Selection',
                            ctx=Load(),
                        ),
                        args=[
                            List(
                                lineno=11,
                                col_offset=37,
                                end_lineno=11,
                                end_col_offset=109,
                                elts=[
                                    Tuple(
                                        lineno=11,
                                        col_offset=38,
                                        end_lineno=11,
                                        end_col_offset=62,
                                        elts=[
                                            Constant(lineno=11, col_offset=39, end_lineno=11, end_col_offset=49, value='accounts', kind=None),
                                            Constant(lineno=11, col_offset=51, end_lineno=11, end_col_offset=61, value='Accounts', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                    Tuple(
                                        lineno=11,
                                        col_offset=64,
                                        end_lineno=11,
                                        end_col_offset=82,
                                        elts=[
                                            Constant(lineno=11, col_offset=65, end_lineno=11, end_col_offset=72, value='taxes', kind=None),
                                            Constant(lineno=11, col_offset=74, end_lineno=11, end_col_offset=81, value='Taxes', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                    Tuple(
                                        lineno=11,
                                        col_offset=84,
                                        end_lineno=11,
                                        end_col_offset=108,
                                        elts=[
                                            Constant(lineno=11, col_offset=85, end_lineno=11, end_col_offset=95, value='products', kind=None),
                                            Constant(lineno=11, col_offset=97, end_lineno=11, end_col_offset=107, value='Products', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                ctx=Load(),
                            ),
                        ],
                        keywords=[
                            keyword(
                                lineno=11,
                                col_offset=111,
                                end_lineno=11,
                                end_col_offset=124,
                                arg='required',
                                value=Constant(lineno=11, col_offset=120, end_lineno=11, end_col_offset=124, value=True, kind=None),
                            ),
                            keyword(
                                lineno=11,
                                col_offset=126,
                                end_lineno=11,
                                end_col_offset=144,
                                arg='default',
                                value=Constant(lineno=11, col_offset=134, end_lineno=11, end_col_offset=144, value='accounts', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=12,
                    col_offset=4,
                    end_lineno=12,
                    end_col_offset=41,
                    targets=[Name(lineno=12, col_offset=4, end_lineno=12, end_col_offset=9, id='color', ctx=Store())],
                    value=Call(
                        lineno=12,
                        col_offset=12,
                        end_lineno=12,
                        end_col_offset=41,
                        func=Attribute(
                            lineno=12,
                            col_offset=12,
                            end_lineno=12,
                            end_col_offset=26,
                            value=Name(lineno=12, col_offset=12, end_lineno=12, end_col_offset=18, id='fields', ctx=Load()),
                            attr='Integer',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=12, col_offset=27, end_lineno=12, end_col_offset=40, value='Color Index', kind=None)],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=13,
                    col_offset=4,
                    end_lineno=13,
                    end_col_offset=114,
                    targets=[Name(lineno=13, col_offset=4, end_lineno=13, end_col_offset=10, id='active', ctx=Store())],
                    value=Call(
                        lineno=13,
                        col_offset=13,
                        end_lineno=13,
                        end_col_offset=114,
                        func=Attribute(
                            lineno=13,
                            col_offset=13,
                            end_lineno=13,
                            end_col_offset=27,
                            value=Name(lineno=13, col_offset=13, end_lineno=13, end_col_offset=19, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=13,
                                col_offset=28,
                                end_lineno=13,
                                end_col_offset=40,
                                arg='default',
                                value=Constant(lineno=13, col_offset=36, end_lineno=13, end_col_offset=40, value=True, kind=None),
                            ),
                            keyword(
                                lineno=13,
                                col_offset=42,
                                end_lineno=13,
                                end_col_offset=113,
                                arg='help',
                                value=Constant(lineno=13, col_offset=47, end_lineno=13, end_col_offset=113, value='Set active to false to hide the Account Tag without removing it.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=14,
                    col_offset=4,
                    end_lineno=14,
                    end_col_offset=198,
                    targets=[Name(lineno=14, col_offset=4, end_lineno=14, end_col_offset=23, id='tax_report_line_ids', ctx=Store())],
                    value=Call(
                        lineno=14,
                        col_offset=26,
                        end_lineno=14,
                        end_col_offset=198,
                        func=Attribute(
                            lineno=14,
                            col_offset=26,
                            end_lineno=14,
                            end_col_offset=42,
                            value=Name(lineno=14, col_offset=26, end_lineno=14, end_col_offset=32, id='fields', ctx=Load()),
                            attr='Many2many',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=14,
                                col_offset=43,
                                end_lineno=14,
                                end_col_offset=68,
                                arg='string',
                                value=Constant(lineno=14, col_offset=50, end_lineno=14, end_col_offset=68, value='Tax Report Lines', kind=None),
                            ),
                            keyword(
                                lineno=14,
                                col_offset=70,
                                end_lineno=14,
                                end_col_offset=108,
                                arg='comodel_name',
                                value=Constant(lineno=14, col_offset=83, end_lineno=14, end_col_offset=108, value='account.tax.report.line', kind=None),
                            ),
                            keyword(
                                lineno=14,
                                col_offset=110,
                                end_lineno=14,
                                end_col_offset=153,
                                arg='relation',
                                value=Constant(lineno=14, col_offset=119, end_lineno=14, end_col_offset=153, value='account_tax_report_line_tags_rel', kind=None),
                            ),
                            keyword(
                                lineno=14,
                                col_offset=155,
                                end_lineno=14,
                                end_col_offset=197,
                                arg='help',
                                value=Constant(lineno=14, col_offset=160, end_lineno=14, end_col_offset=197, value='The tax report lines using this tag', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=15,
                    col_offset=4,
                    end_lineno=15,
                    end_col_offset=192,
                    targets=[Name(lineno=15, col_offset=4, end_lineno=15, end_col_offset=14, id='tax_negate', ctx=Store())],
                    value=Call(
                        lineno=15,
                        col_offset=17,
                        end_lineno=15,
                        end_col_offset=192,
                        func=Attribute(
                            lineno=15,
                            col_offset=17,
                            end_lineno=15,
                            end_col_offset=31,
                            value=Name(lineno=15, col_offset=17, end_lineno=15, end_col_offset=23, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=15,
                                col_offset=32,
                                end_lineno=15,
                                end_col_offset=59,
                                arg='string',
                                value=Constant(lineno=15, col_offset=39, end_lineno=15, end_col_offset=59, value='Negate Tax Balance', kind=None),
                            ),
                            keyword(
                                lineno=15,
                                col_offset=61,
                                end_lineno=15,
                                end_col_offset=191,
                                arg='help',
                                value=Constant(lineno=15, col_offset=66, end_lineno=15, end_col_offset=191, value='Check this box to negate the absolute value of the balance of the lines associated with this tag in tax report computation.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=16,
                    col_offset=4,
                    end_lineno=16,
                    end_col_offset=150,
                    targets=[Name(lineno=16, col_offset=4, end_lineno=16, end_col_offset=14, id='country_id', ctx=Store())],
                    value=Call(
                        lineno=16,
                        col_offset=17,
                        end_lineno=16,
                        end_col_offset=150,
                        func=Attribute(
                            lineno=16,
                            col_offset=17,
                            end_lineno=16,
                            end_col_offset=32,
                            value=Name(lineno=16, col_offset=17, end_lineno=16, end_col_offset=23, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=16,
                                col_offset=33,
                                end_lineno=16,
                                end_col_offset=49,
                                arg='string',
                                value=Constant(lineno=16, col_offset=40, end_lineno=16, end_col_offset=49, value='Country', kind=None),
                            ),
                            keyword(
                                lineno=16,
                                col_offset=51,
                                end_lineno=16,
                                end_col_offset=77,
                                arg='comodel_name',
                                value=Constant(lineno=16, col_offset=64, end_lineno=16, end_col_offset=77, value='res.country', kind=None),
                            ),
                            keyword(
                                lineno=16,
                                col_offset=79,
                                end_lineno=16,
                                end_col_offset=149,
                                arg='help',
                                value=Constant(lineno=16, col_offset=84, end_lineno=16, end_col_offset=149, value='Country for which this tag is available, when applied on taxes.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=19,
                    col_offset=4,
                    end_lineno=24,
                    end_col_offset=164,
                    name='_get_tax_tags',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=19, col_offset=22, end_lineno=19, end_col_offset=26, arg='self', annotation=None, type_comment=None),
                            arg(lineno=19, col_offset=28, end_lineno=19, end_col_offset=36, arg='tag_name', annotation=None, type_comment=None),
                            arg(lineno=19, col_offset=38, end_lineno=19, end_col_offset=48, arg='country_id', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=20,
                            col_offset=8,
                            end_lineno=22,
                            end_col_offset=11,
                            value=Constant(lineno=20, col_offset=8, end_lineno=22, end_col_offset=11, value=' Returns all the tax tags corresponding to the tag name given in parameter\n        in the specified country.\n        ', kind=None),
                        ),
                        Assign(
                            lineno=23,
                            col_offset=8,
                            end_lineno=23,
                            end_col_offset=95,
                            targets=[Name(lineno=23, col_offset=8, end_lineno=23, end_col_offset=24, id='escaped_tag_name', ctx=Store())],
                            value=Call(
                                lineno=23,
                                col_offset=27,
                                end_lineno=23,
                                end_col_offset=95,
                                func=Attribute(
                                    lineno=23,
                                    col_offset=27,
                                    end_lineno=23,
                                    end_col_offset=84,
                                    value=Call(
                                        lineno=23,
                                        col_offset=27,
                                        end_lineno=23,
                                        end_col_offset=76,
                                        func=Attribute(
                                            lineno=23,
                                            col_offset=27,
                                            end_lineno=23,
                                            end_col_offset=65,
                                            value=Call(
                                                lineno=23,
                                                col_offset=27,
                                                end_lineno=23,
                                                end_col_offset=57,
                                                func=Attribute(
                                                    lineno=23,
                                                    col_offset=27,
                                                    end_lineno=23,
                                                    end_col_offset=43,
                                                    value=Name(lineno=23, col_offset=27, end_lineno=23, end_col_offset=35, id='tag_name', ctx=Load()),
                                                    attr='replace',
                                                    ctx=Load(),
                                                ),
                                                args=[
                                                    Constant(lineno=23, col_offset=44, end_lineno=23, end_col_offset=48, value='\\', kind=None),
                                                    Constant(lineno=23, col_offset=50, end_lineno=23, end_col_offset=56, value='\\\\', kind=None),
                                                ],
                                                keywords=[],
                                            ),
                                            attr='replace',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Constant(lineno=23, col_offset=66, end_lineno=23, end_col_offset=69, value='%', kind=None),
                                            Constant(lineno=23, col_offset=71, end_lineno=23, end_col_offset=75, value='\\%', kind=None),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='replace',
                                    ctx=Load(),
                                ),
                                args=[
                                    Constant(lineno=23, col_offset=85, end_lineno=23, end_col_offset=88, value='_', kind=None),
                                    Constant(lineno=23, col_offset=90, end_lineno=23, end_col_offset=94, value='\\_', kind=None),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Return(
                            lineno=24,
                            col_offset=8,
                            end_lineno=24,
                            end_col_offset=164,
                            value=Call(
                                lineno=24,
                                col_offset=15,
                                end_lineno=24,
                                end_col_offset=164,
                                func=Attribute(
                                    lineno=24,
                                    col_offset=15,
                                    end_lineno=24,
                                    end_col_offset=53,
                                    value=Subscript(
                                        lineno=24,
                                        col_offset=15,
                                        end_lineno=24,
                                        end_col_offset=46,
                                        value=Attribute(
                                            lineno=24,
                                            col_offset=15,
                                            end_lineno=24,
                                            end_col_offset=23,
                                            value=Name(lineno=24, col_offset=15, end_lineno=24, end_col_offset=19, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=24, col_offset=24, end_lineno=24, end_col_offset=45, value='account.account.tag', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='search',
                                    ctx=Load(),
                                ),
                                args=[
                                    List(
                                        lineno=24,
                                        col_offset=54,
                                        end_lineno=24,
                                        end_col_offset=163,
                                        elts=[
                                            Tuple(
                                                lineno=24,
                                                col_offset=55,
                                                end_lineno=24,
                                                end_col_offset=96,
                                                elts=[
                                                    Constant(lineno=24, col_offset=56, end_lineno=24, end_col_offset=62, value='name', kind=None),
                                                    Constant(lineno=24, col_offset=64, end_lineno=24, end_col_offset=71, value='=like', kind=None),
                                                    BinOp(
                                                        lineno=24,
                                                        col_offset=73,
                                                        end_lineno=24,
                                                        end_col_offset=95,
                                                        left=Constant(lineno=24, col_offset=73, end_lineno=24, end_col_offset=76, value='_', kind=None),
                                                        op=Add(),
                                                        right=Name(lineno=24, col_offset=79, end_lineno=24, end_col_offset=95, id='escaped_tag_name', ctx=Load()),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                            Tuple(
                                                lineno=24,
                                                col_offset=98,
                                                end_lineno=24,
                                                end_col_offset=129,
                                                elts=[
                                                    Constant(lineno=24, col_offset=99, end_lineno=24, end_col_offset=111, value='country_id', kind=None),
                                                    Constant(lineno=24, col_offset=113, end_lineno=24, end_col_offset=116, value='=', kind=None),
                                                    Name(lineno=24, col_offset=118, end_lineno=24, end_col_offset=128, id='country_id', ctx=Load()),
                                                ],
                                                ctx=Load(),
                                            ),
                                            Tuple(
                                                lineno=24,
                                                col_offset=131,
                                                end_lineno=24,
                                                end_col_offset=162,
                                                elts=[
                                                    Constant(lineno=24, col_offset=132, end_lineno=24, end_col_offset=147, value='applicability', kind=None),
                                                    Constant(lineno=24, col_offset=149, end_lineno=24, end_col_offset=152, value='=', kind=None),
                                                    Constant(lineno=24, col_offset=154, end_lineno=24, end_col_offset=161, value='taxes', kind=None),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[
                        Attribute(
                            lineno=18,
                            col_offset=5,
                            end_lineno=18,
                            end_col_offset=14,
                            value=Name(lineno=18, col_offset=5, end_lineno=18, end_col_offset=8, id='api', ctx=Load()),
                            attr='model',
                            ctx=Load(),
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
