Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=31,
            module='odoo',
            names=[
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=25,
            end_col_offset=59,
            name='ResPartner',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=17,
                    end_lineno=7,
                    end_col_offset=29,
                    value=Name(lineno=7, col_offset=17, end_lineno=7, end_col_offset=23, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=28,
                    targets=[Name(lineno=8, col_offset=4, end_lineno=8, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=8, col_offset=15, end_lineno=8, end_col_offset=28, value='res.partner', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=10,
                    col_offset=4,
                    end_lineno=13,
                    end_col_offset=64,
                    targets=[Name(lineno=10, col_offset=4, end_lineno=10, end_col_offset=32, id='property_stock_subcontractor', ctx=Store())],
                    value=Call(
                        lineno=10,
                        col_offset=35,
                        end_lineno=13,
                        end_col_offset=64,
                        func=Attribute(
                            lineno=10,
                            col_offset=35,
                            end_lineno=10,
                            end_col_offset=50,
                            value=Name(lineno=10, col_offset=35, end_lineno=10, end_col_offset=41, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=11, col_offset=8, end_lineno=11, end_col_offset=24, value='stock.location', kind=None)],
                        keywords=[
                            keyword(
                                lineno=11,
                                col_offset=26,
                                end_lineno=11,
                                end_col_offset=57,
                                arg='string',
                                value=Constant(lineno=11, col_offset=33, end_lineno=11, end_col_offset=57, value='Subcontractor Location', kind=None),
                            ),
                            keyword(
                                lineno=11,
                                col_offset=59,
                                end_lineno=11,
                                end_col_offset=81,
                                arg='company_dependent',
                                value=Constant(lineno=11, col_offset=77, end_lineno=11, end_col_offset=81, value=True, kind=None),
                            ),
                            keyword(
                                lineno=12,
                                col_offset=8,
                                end_lineno=13,
                                end_col_offset=63,
                                arg='help',
                                value=Constant(lineno=12, col_offset=13, end_lineno=13, end_col_offset=63, value='The stock location used as source and destination when sending        goods to this contact during a subcontracting process.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=14,
                    col_offset=4,
                    end_lineno=15,
                    end_col_offset=79,
                    targets=[Name(lineno=14, col_offset=4, end_lineno=14, end_col_offset=20, id='is_subcontractor', ctx=Store())],
                    value=Call(
                        lineno=14,
                        col_offset=23,
                        end_lineno=15,
                        end_col_offset=79,
                        func=Attribute(
                            lineno=14,
                            col_offset=23,
                            end_lineno=14,
                            end_col_offset=37,
                            value=Name(lineno=14, col_offset=23, end_lineno=14, end_col_offset=29, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=15,
                                col_offset=8,
                                end_lineno=15,
                                end_col_offset=30,
                                arg='string',
                                value=Constant(lineno=15, col_offset=15, end_lineno=15, end_col_offset=30, value='Subcontractor', kind=None),
                            ),
                            keyword(
                                lineno=15,
                                col_offset=32,
                                end_lineno=15,
                                end_col_offset=43,
                                arg='store',
                                value=Constant(lineno=15, col_offset=38, end_lineno=15, end_col_offset=43, value=False, kind=None),
                            ),
                            keyword(
                                lineno=15,
                                col_offset=45,
                                end_lineno=15,
                                end_col_offset=78,
                                arg='search',
                                value=Constant(lineno=15, col_offset=52, end_lineno=15, end_col_offset=78, value='_search_is_subcontractor', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=17,
                    col_offset=4,
                    end_lineno=25,
                    end_col_offset=59,
                    name='_search_is_subcontractor',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=17, col_offset=33, end_lineno=17, end_col_offset=37, arg='self', annotation=None, type_comment=None),
                            arg(lineno=17, col_offset=39, end_lineno=17, end_col_offset=47, arg='operator', annotation=None, type_comment=None),
                            arg(lineno=17, col_offset=49, end_lineno=17, end_col_offset=54, arg='value', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assert(
                            lineno=18,
                            col_offset=8,
                            end_lineno=18,
                            end_col_offset=98,
                            test=BoolOp(
                                lineno=18,
                                col_offset=15,
                                end_lineno=18,
                                end_col_offset=71,
                                op=And(),
                                values=[
                                    Compare(
                                        lineno=18,
                                        col_offset=15,
                                        end_lineno=18,
                                        end_col_offset=44,
                                        left=Name(lineno=18, col_offset=15, end_lineno=18, end_col_offset=23, id='operator', ctx=Load()),
                                        ops=[In()],
                                        comparators=[
                                            Tuple(
                                                lineno=18,
                                                col_offset=27,
                                                end_lineno=18,
                                                end_col_offset=44,
                                                elts=[
                                                    Constant(lineno=18, col_offset=28, end_lineno=18, end_col_offset=31, value='=', kind=None),
                                                    Constant(lineno=18, col_offset=33, end_lineno=18, end_col_offset=37, value='!=', kind=None),
                                                    Constant(lineno=18, col_offset=39, end_lineno=18, end_col_offset=43, value='<>', kind=None),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                    ),
                                    Compare(
                                        lineno=18,
                                        col_offset=49,
                                        end_lineno=18,
                                        end_col_offset=71,
                                        left=Name(lineno=18, col_offset=49, end_lineno=18, end_col_offset=54, id='value', ctx=Load()),
                                        ops=[In()],
                                        comparators=[
                                            Tuple(
                                                lineno=18,
                                                col_offset=58,
                                                end_lineno=18,
                                                end_col_offset=71,
                                                elts=[
                                                    Constant(lineno=18, col_offset=59, end_lineno=18, end_col_offset=63, value=True, kind=None),
                                                    Constant(lineno=18, col_offset=65, end_lineno=18, end_col_offset=70, value=False, kind=None),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                            msg=Constant(lineno=18, col_offset=73, end_lineno=18, end_col_offset=98, value='Operation not supported', kind=None),
                        ),
                        Assign(
                            lineno=19,
                            col_offset=8,
                            end_lineno=20,
                            end_col_offset=65,
                            targets=[Name(lineno=19, col_offset=8, end_lineno=19, end_col_offset=25, id='subcontractor_ids', ctx=Store())],
                            value=Attribute(
                                lineno=19,
                                col_offset=28,
                                end_lineno=20,
                                end_col_offset=65,
                                value=Attribute(
                                    lineno=19,
                                    col_offset=28,
                                    end_lineno=20,
                                    end_col_offset=61,
                                    value=Call(
                                        lineno=19,
                                        col_offset=28,
                                        end_lineno=20,
                                        end_col_offset=43,
                                        func=Attribute(
                                            lineno=19,
                                            col_offset=28,
                                            end_lineno=19,
                                            end_col_offset=54,
                                            value=Subscript(
                                                lineno=19,
                                                col_offset=28,
                                                end_lineno=19,
                                                end_col_offset=47,
                                                value=Attribute(
                                                    lineno=19,
                                                    col_offset=28,
                                                    end_lineno=19,
                                                    end_col_offset=36,
                                                    value=Name(lineno=19, col_offset=28, end_lineno=19, end_col_offset=32, id='self', ctx=Load()),
                                                    attr='env',
                                                    ctx=Load(),
                                                ),
                                                slice=Constant(lineno=19, col_offset=37, end_lineno=19, end_col_offset=46, value='mrp.bom', kind=None),
                                                ctx=Load(),
                                            ),
                                            attr='search',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            List(
                                                lineno=20,
                                                col_offset=12,
                                                end_lineno=20,
                                                end_col_offset=42,
                                                elts=[
                                                    Tuple(
                                                        lineno=20,
                                                        col_offset=13,
                                                        end_lineno=20,
                                                        end_col_offset=41,
                                                        elts=[
                                                            Constant(lineno=20, col_offset=14, end_lineno=20, end_col_offset=20, value='type', kind=None),
                                                            Constant(lineno=20, col_offset=22, end_lineno=20, end_col_offset=25, value='=', kind=None),
                                                            Constant(lineno=20, col_offset=27, end_lineno=20, end_col_offset=40, value='subcontract', kind=None),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='subcontractor_ids',
                                    ctx=Load(),
                                ),
                                attr='ids',
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        If(
                            lineno=21,
                            col_offset=8,
                            end_lineno=24,
                            end_col_offset=38,
                            test=BoolOp(
                                lineno=21,
                                col_offset=11,
                                end_lineno=21,
                                end_col_offset=95,
                                op=Or(),
                                values=[
                                    BoolOp(
                                        lineno=21,
                                        col_offset=12,
                                        end_lineno=21,
                                        end_col_offset=45,
                                        op=And(),
                                        values=[
                                            Compare(
                                                lineno=21,
                                                col_offset=12,
                                                end_lineno=21,
                                                end_col_offset=27,
                                                left=Name(lineno=21, col_offset=12, end_lineno=21, end_col_offset=20, id='operator', ctx=Load()),
                                                ops=[Eq()],
                                                comparators=[Constant(lineno=21, col_offset=24, end_lineno=21, end_col_offset=27, value='=', kind=None)],
                                            ),
                                            Compare(
                                                lineno=21,
                                                col_offset=32,
                                                end_lineno=21,
                                                end_col_offset=45,
                                                left=Name(lineno=21, col_offset=32, end_lineno=21, end_col_offset=37, id='value', ctx=Load()),
                                                ops=[Is()],
                                                comparators=[Constant(lineno=21, col_offset=41, end_lineno=21, end_col_offset=45, value=True, kind=None)],
                                            ),
                                        ],
                                    ),
                                    BoolOp(
                                        lineno=21,
                                        col_offset=51,
                                        end_lineno=21,
                                        end_col_offset=94,
                                        op=And(),
                                        values=[
                                            Compare(
                                                lineno=21,
                                                col_offset=51,
                                                end_lineno=21,
                                                end_col_offset=75,
                                                left=Name(lineno=21, col_offset=51, end_lineno=21, end_col_offset=59, id='operator', ctx=Load()),
                                                ops=[In()],
                                                comparators=[
                                                    Tuple(
                                                        lineno=21,
                                                        col_offset=63,
                                                        end_lineno=21,
                                                        end_col_offset=75,
                                                        elts=[
                                                            Constant(lineno=21, col_offset=64, end_lineno=21, end_col_offset=68, value='<>', kind=None),
                                                            Constant(lineno=21, col_offset=70, end_lineno=21, end_col_offset=74, value='!=', kind=None),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                ],
                                            ),
                                            Compare(
                                                lineno=21,
                                                col_offset=80,
                                                end_lineno=21,
                                                end_col_offset=94,
                                                left=Name(lineno=21, col_offset=80, end_lineno=21, end_col_offset=85, id='value', ctx=Load()),
                                                ops=[Is()],
                                                comparators=[Constant(lineno=21, col_offset=89, end_lineno=21, end_col_offset=94, value=False, kind=None)],
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                            body=[
                                Assign(
                                    lineno=22,
                                    col_offset=12,
                                    end_lineno=22,
                                    end_col_offset=34,
                                    targets=[Name(lineno=22, col_offset=12, end_lineno=22, end_col_offset=27, id='search_operator', ctx=Store())],
                                    value=Constant(lineno=22, col_offset=30, end_lineno=22, end_col_offset=34, value='in', kind=None),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[
                                Assign(
                                    lineno=24,
                                    col_offset=12,
                                    end_lineno=24,
                                    end_col_offset=38,
                                    targets=[Name(lineno=24, col_offset=12, end_lineno=24, end_col_offset=27, id='search_operator', ctx=Store())],
                                    value=Constant(lineno=24, col_offset=30, end_lineno=24, end_col_offset=38, value='not in', kind=None),
                                    type_comment=None,
                                ),
                            ],
                        ),
                        Return(
                            lineno=25,
                            col_offset=8,
                            end_lineno=25,
                            end_col_offset=59,
                            value=List(
                                lineno=25,
                                col_offset=15,
                                end_lineno=25,
                                end_col_offset=59,
                                elts=[
                                    Tuple(
                                        lineno=25,
                                        col_offset=16,
                                        end_lineno=25,
                                        end_col_offset=58,
                                        elts=[
                                            Constant(lineno=25, col_offset=17, end_lineno=25, end_col_offset=21, value='id', kind=None),
                                            Name(lineno=25, col_offset=23, end_lineno=25, end_col_offset=38, id='search_operator', ctx=Load()),
                                            Name(lineno=25, col_offset=40, end_lineno=25, end_col_offset=57, id='subcontractor_ids', ctx=Load()),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                ctx=Load(),
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
