Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=39,
            module='odoo',
            names=[
                alias(name='api', asname=None),
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
                alias(name='_', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=37,
            end_col_offset=72,
            name='ResCompany',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=17,
                    end_lineno=7,
                    end_col_offset=29,
                    value=Name(lineno=7, col_offset=17, end_lineno=7, end_col_offset=23, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=28,
                    targets=[Name(lineno=8, col_offset=4, end_lineno=8, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=8, col_offset=15, end_lineno=8, end_col_offset=28, value='res.company', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=10,
                    col_offset=4,
                    end_lineno=10,
                    end_col_offset=66,
                    targets=[Name(lineno=10, col_offset=4, end_lineno=10, end_col_offset=30, id='subcontracting_location_id', ctx=Store())],
                    value=Call(
                        lineno=10,
                        col_offset=33,
                        end_lineno=10,
                        end_col_offset=66,
                        func=Attribute(
                            lineno=10,
                            col_offset=33,
                            end_lineno=10,
                            end_col_offset=48,
                            value=Name(lineno=10, col_offset=33, end_lineno=10, end_col_offset=39, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=10, col_offset=49, end_lineno=10, end_col_offset=65, value='stock.location', kind=None)],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=13,
                    col_offset=4,
                    end_lineno=16,
                    end_col_offset=76,
                    name='create_missing_subcontracting_location',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=13, col_offset=47, end_lineno=13, end_col_offset=51, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=14,
                            col_offset=8,
                            end_lineno=15,
                            end_col_offset=57,
                            targets=[Name(lineno=14, col_offset=8, end_lineno=14, end_col_offset=42, id='company_without_subcontracting_loc', ctx=Store())],
                            value=Call(
                                lineno=14,
                                col_offset=45,
                                end_lineno=15,
                                end_col_offset=57,
                                func=Attribute(
                                    lineno=14,
                                    col_offset=45,
                                    end_lineno=14,
                                    end_col_offset=75,
                                    value=Subscript(
                                        lineno=14,
                                        col_offset=45,
                                        end_lineno=14,
                                        end_col_offset=68,
                                        value=Attribute(
                                            lineno=14,
                                            col_offset=45,
                                            end_lineno=14,
                                            end_col_offset=53,
                                            value=Name(lineno=14, col_offset=45, end_lineno=14, end_col_offset=49, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=14, col_offset=54, end_lineno=14, end_col_offset=67, value='res.company', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='search',
                                    ctx=Load(),
                                ),
                                args=[
                                    List(
                                        lineno=15,
                                        col_offset=12,
                                        end_lineno=15,
                                        end_col_offset=56,
                                        elts=[
                                            Tuple(
                                                lineno=15,
                                                col_offset=13,
                                                end_lineno=15,
                                                end_col_offset=55,
                                                elts=[
                                                    Constant(lineno=15, col_offset=14, end_lineno=15, end_col_offset=42, value='subcontracting_location_id', kind=None),
                                                    Constant(lineno=15, col_offset=44, end_lineno=15, end_col_offset=47, value='=', kind=None),
                                                    Constant(lineno=15, col_offset=49, end_lineno=15, end_col_offset=54, value=False, kind=None),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=16,
                            col_offset=8,
                            end_lineno=16,
                            end_col_offset=76,
                            value=Call(
                                lineno=16,
                                col_offset=8,
                                end_lineno=16,
                                end_col_offset=76,
                                func=Attribute(
                                    lineno=16,
                                    col_offset=8,
                                    end_lineno=16,
                                    end_col_offset=74,
                                    value=Name(lineno=16, col_offset=8, end_lineno=16, end_col_offset=42, id='company_without_subcontracting_loc', ctx=Load()),
                                    attr='_create_subcontracting_location',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[
                        Attribute(
                            lineno=12,
                            col_offset=5,
                            end_lineno=12,
                            end_col_offset=14,
                            value=Name(lineno=12, col_offset=5, end_lineno=12, end_col_offset=8, id='api', ctx=Load()),
                            attr='model',
                            ctx=Load(),
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=18,
                    col_offset=4,
                    end_lineno=20,
                    end_col_offset=46,
                    name='_create_per_company_locations',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=18, col_offset=38, end_lineno=18, end_col_offset=42, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=19,
                            col_offset=8,
                            end_lineno=19,
                            end_col_offset=63,
                            value=Call(
                                lineno=19,
                                col_offset=8,
                                end_lineno=19,
                                end_col_offset=63,
                                func=Attribute(
                                    lineno=19,
                                    col_offset=8,
                                    end_lineno=19,
                                    end_col_offset=61,
                                    value=Call(
                                        lineno=19,
                                        col_offset=8,
                                        end_lineno=19,
                                        end_col_offset=31,
                                        func=Name(lineno=19, col_offset=8, end_lineno=19, end_col_offset=13, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=19, col_offset=14, end_lineno=19, end_col_offset=24, id='ResCompany', ctx=Load()),
                                            Name(lineno=19, col_offset=26, end_lineno=19, end_col_offset=30, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='_create_per_company_locations',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=20,
                            col_offset=8,
                            end_lineno=20,
                            end_col_offset=46,
                            value=Call(
                                lineno=20,
                                col_offset=8,
                                end_lineno=20,
                                end_col_offset=46,
                                func=Attribute(
                                    lineno=20,
                                    col_offset=8,
                                    end_lineno=20,
                                    end_col_offset=44,
                                    value=Name(lineno=20, col_offset=8, end_lineno=20, end_col_offset=12, id='self', ctx=Load()),
                                    attr='_create_subcontracting_location',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=22,
                    col_offset=4,
                    end_lineno=37,
                    end_col_offset=72,
                    name='_create_subcontracting_location',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=22, col_offset=40, end_lineno=22, end_col_offset=44, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=23,
                            col_offset=8,
                            end_lineno=23,
                            end_col_offset=98,
                            targets=[Name(lineno=23, col_offset=8, end_lineno=23, end_col_offset=23, id='parent_location', ctx=Store())],
                            value=Call(
                                lineno=23,
                                col_offset=26,
                                end_lineno=23,
                                end_col_offset=98,
                                func=Attribute(
                                    lineno=23,
                                    col_offset=26,
                                    end_lineno=23,
                                    end_col_offset=38,
                                    value=Attribute(
                                        lineno=23,
                                        col_offset=26,
                                        end_lineno=23,
                                        end_col_offset=34,
                                        value=Name(lineno=23, col_offset=26, end_lineno=23, end_col_offset=30, id='self', ctx=Load()),
                                        attr='env',
                                        ctx=Load(),
                                    ),
                                    attr='ref',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=23, col_offset=39, end_lineno=23, end_col_offset=71, value='stock.stock_location_locations', kind=None)],
                                keywords=[
                                    keyword(
                                        lineno=23,
                                        col_offset=73,
                                        end_lineno=23,
                                        end_col_offset=97,
                                        arg='raise_if_not_found',
                                        value=Constant(lineno=23, col_offset=92, end_lineno=23, end_col_offset=97, value=False, kind=None),
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                        For(
                            lineno=24,
                            col_offset=8,
                            end_lineno=37,
                            end_col_offset=72,
                            target=Name(lineno=24, col_offset=12, end_lineno=24, end_col_offset=19, id='company', ctx=Store()),
                            iter=Name(lineno=24, col_offset=23, end_lineno=24, end_col_offset=27, id='self', ctx=Load()),
                            body=[
                                Assign(
                                    lineno=25,
                                    col_offset=12,
                                    end_lineno=30,
                                    end_col_offset=14,
                                    targets=[Name(lineno=25, col_offset=12, end_lineno=25, end_col_offset=35, id='subcontracting_location', ctx=Store())],
                                    value=Call(
                                        lineno=25,
                                        col_offset=38,
                                        end_lineno=30,
                                        end_col_offset=14,
                                        func=Attribute(
                                            lineno=25,
                                            col_offset=38,
                                            end_lineno=25,
                                            end_col_offset=71,
                                            value=Subscript(
                                                lineno=25,
                                                col_offset=38,
                                                end_lineno=25,
                                                end_col_offset=64,
                                                value=Attribute(
                                                    lineno=25,
                                                    col_offset=38,
                                                    end_lineno=25,
                                                    end_col_offset=46,
                                                    value=Name(lineno=25, col_offset=38, end_lineno=25, end_col_offset=42, id='self', ctx=Load()),
                                                    attr='env',
                                                    ctx=Load(),
                                                ),
                                                slice=Constant(lineno=25, col_offset=47, end_lineno=25, end_col_offset=63, value='stock.location', kind=None),
                                                ctx=Load(),
                                            ),
                                            attr='create',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Dict(
                                                lineno=25,
                                                col_offset=72,
                                                end_lineno=30,
                                                end_col_offset=13,
                                                keys=[
                                                    Constant(lineno=26, col_offset=16, end_lineno=26, end_col_offset=22, value='name', kind=None),
                                                    Constant(lineno=27, col_offset=16, end_lineno=27, end_col_offset=23, value='usage', kind=None),
                                                    Constant(lineno=28, col_offset=16, end_lineno=28, end_col_offset=29, value='location_id', kind=None),
                                                    Constant(lineno=29, col_offset=16, end_lineno=29, end_col_offset=28, value='company_id', kind=None),
                                                ],
                                                values=[
                                                    Call(
                                                        lineno=26,
                                                        col_offset=24,
                                                        end_lineno=26,
                                                        end_col_offset=52,
                                                        func=Name(lineno=26, col_offset=24, end_lineno=26, end_col_offset=25, id='_', ctx=Load()),
                                                        args=[Constant(lineno=26, col_offset=26, end_lineno=26, end_col_offset=51, value='Subcontracting Location', kind=None)],
                                                        keywords=[],
                                                    ),
                                                    Constant(lineno=27, col_offset=25, end_lineno=27, end_col_offset=35, value='internal', kind=None),
                                                    Attribute(
                                                        lineno=28,
                                                        col_offset=31,
                                                        end_lineno=28,
                                                        end_col_offset=49,
                                                        value=Name(lineno=28, col_offset=31, end_lineno=28, end_col_offset=46, id='parent_location', ctx=Load()),
                                                        attr='id',
                                                        ctx=Load(),
                                                    ),
                                                    Attribute(
                                                        lineno=29,
                                                        col_offset=30,
                                                        end_lineno=29,
                                                        end_col_offset=40,
                                                        value=Name(lineno=29, col_offset=30, end_lineno=29, end_col_offset=37, id='company', ctx=Load()),
                                                        attr='id',
                                                        ctx=Load(),
                                                    ),
                                                ],
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                    type_comment=None,
                                ),
                                Expr(
                                    lineno=31,
                                    col_offset=12,
                                    end_lineno=36,
                                    end_col_offset=13,
                                    value=Call(
                                        lineno=31,
                                        col_offset=12,
                                        end_lineno=36,
                                        end_col_offset=13,
                                        func=Attribute(
                                            lineno=31,
                                            col_offset=12,
                                            end_lineno=31,
                                            end_col_offset=48,
                                            value=Subscript(
                                                lineno=31,
                                                col_offset=12,
                                                end_lineno=31,
                                                end_col_offset=35,
                                                value=Attribute(
                                                    lineno=31,
                                                    col_offset=12,
                                                    end_lineno=31,
                                                    end_col_offset=20,
                                                    value=Name(lineno=31, col_offset=12, end_lineno=31, end_col_offset=16, id='self', ctx=Load()),
                                                    attr='env',
                                                    ctx=Load(),
                                                ),
                                                slice=Constant(lineno=31, col_offset=21, end_lineno=31, end_col_offset=34, value='ir.property', kind=None),
                                                ctx=Load(),
                                            ),
                                            attr='_set_default',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Constant(lineno=32, col_offset=16, end_lineno=32, end_col_offset=46, value='property_stock_subcontractor', kind=None),
                                            Constant(lineno=33, col_offset=16, end_lineno=33, end_col_offset=29, value='res.partner', kind=None),
                                            Name(lineno=34, col_offset=16, end_lineno=34, end_col_offset=39, id='subcontracting_location', ctx=Load()),
                                            Name(lineno=35, col_offset=16, end_lineno=35, end_col_offset=23, id='company', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                ),
                                Assign(
                                    lineno=37,
                                    col_offset=12,
                                    end_lineno=37,
                                    end_col_offset=72,
                                    targets=[
                                        Attribute(
                                            lineno=37,
                                            col_offset=12,
                                            end_lineno=37,
                                            end_col_offset=46,
                                            value=Name(lineno=37, col_offset=12, end_lineno=37, end_col_offset=19, id='company', ctx=Load()),
                                            attr='subcontracting_location_id',
                                            ctx=Store(),
                                        ),
                                    ],
                                    value=Name(lineno=37, col_offset=49, end_lineno=37, end_col_offset=72, id='subcontracting_location', ctx=Load()),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[],
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
