Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=60,
            module='odoo.addons.mail.tests.common',
            names=[alias(name='mail_new_test_user', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=5,
            col_offset=0,
            end_lineno=5,
            end_col_offset=60,
            module='odoo.tests.common',
            names=[
                alias(name='TransactionCase', asname=None),
                alias(name='users', asname=None),
                alias(name='warmup', asname=None),
            ],
            level=0,
        ),
        ImportFrom(
            lineno=6,
            col_offset=0,
            end_lineno=6,
            end_col_offset=29,
            module='odoo.tests',
            names=[alias(name='tagged', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=7,
            col_offset=0,
            end_lineno=7,
            end_col_offset=34,
            module='odoo.tools',
            names=[alias(name='mute_logger', asname=None)],
            level=0,
        ),
        ClassDef(
            lineno=10,
            col_offset=0,
            end_lineno=36,
            end_col_offset=52,
            name='TestMassMailPerformanceBase',
            bases=[Name(lineno=10, col_offset=34, end_lineno=10, end_col_offset=49, id='TransactionCase', ctx=Load())],
            keywords=[],
            body=[
                FunctionDef(
                    lineno=12,
                    col_offset=4,
                    end_lineno=36,
                    end_col_offset=52,
                    name='setUp',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=12, col_offset=14, end_lineno=12, end_col_offset=18, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=13,
                            col_offset=8,
                            end_lineno=13,
                            end_col_offset=56,
                            value=Call(
                                lineno=13,
                                col_offset=8,
                                end_lineno=13,
                                end_col_offset=56,
                                func=Attribute(
                                    lineno=13,
                                    col_offset=8,
                                    end_lineno=13,
                                    end_col_offset=54,
                                    value=Call(
                                        lineno=13,
                                        col_offset=8,
                                        end_lineno=13,
                                        end_col_offset=48,
                                        func=Name(lineno=13, col_offset=8, end_lineno=13, end_col_offset=13, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=13, col_offset=14, end_lineno=13, end_col_offset=41, id='TestMassMailPerformanceBase', ctx=Load()),
                                            Name(lineno=13, col_offset=43, end_lineno=13, end_col_offset=47, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='setUp',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=15,
                            col_offset=8,
                            end_lineno=18,
                            end_col_offset=62,
                            targets=[
                                Attribute(
                                    lineno=15,
                                    col_offset=8,
                                    end_lineno=15,
                                    end_col_offset=26,
                                    value=Name(lineno=15, col_offset=8, end_lineno=15, end_col_offset=12, id='self', ctx=Load()),
                                    attr='user_employee',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=15,
                                col_offset=29,
                                end_lineno=18,
                                end_col_offset=62,
                                func=Name(lineno=15, col_offset=29, end_lineno=15, end_col_offset=47, id='mail_new_test_user', ctx=Load()),
                                args=[
                                    Attribute(
                                        lineno=16,
                                        col_offset=12,
                                        end_lineno=16,
                                        end_col_offset=20,
                                        value=Name(lineno=16, col_offset=12, end_lineno=16, end_col_offset=16, id='self', ctx=Load()),
                                        attr='env',
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[
                                    keyword(
                                        lineno=16,
                                        col_offset=22,
                                        end_lineno=16,
                                        end_col_offset=33,
                                        arg='login',
                                        value=Constant(lineno=16, col_offset=28, end_lineno=16, end_col_offset=33, value='emp', kind=None),
                                    ),
                                    keyword(
                                        lineno=17,
                                        col_offset=12,
                                        end_lineno=17,
                                        end_col_offset=36,
                                        arg='groups',
                                        value=Constant(lineno=17, col_offset=19, end_lineno=17, end_col_offset=36, value='base.group_user', kind=None),
                                    ),
                                    keyword(
                                        lineno=18,
                                        col_offset=12,
                                        end_lineno=18,
                                        end_col_offset=34,
                                        arg='name',
                                        value=Constant(lineno=18, col_offset=17, end_lineno=18, end_col_offset=34, value='Ernest Employee', kind=None),
                                    ),
                                    keyword(
                                        lineno=18,
                                        col_offset=36,
                                        end_lineno=18,
                                        end_col_offset=61,
                                        arg='notification_type',
                                        value=Constant(lineno=18, col_offset=54, end_lineno=18, end_col_offset=61, value='inbox', kind=None),
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=20,
                            col_offset=8,
                            end_lineno=23,
                            end_col_offset=62,
                            targets=[
                                Attribute(
                                    lineno=20,
                                    col_offset=8,
                                    end_lineno=20,
                                    end_col_offset=27,
                                    value=Name(lineno=20, col_offset=8, end_lineno=20, end_col_offset=12, id='self', ctx=Load()),
                                    attr='user_marketing',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=20,
                                col_offset=30,
                                end_lineno=23,
                                end_col_offset=62,
                                func=Name(lineno=20, col_offset=30, end_lineno=20, end_col_offset=48, id='mail_new_test_user', ctx=Load()),
                                args=[
                                    Attribute(
                                        lineno=21,
                                        col_offset=12,
                                        end_lineno=21,
                                        end_col_offset=20,
                                        value=Name(lineno=21, col_offset=12, end_lineno=21, end_col_offset=16, id='self', ctx=Load()),
                                        attr='env',
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[
                                    keyword(
                                        lineno=21,
                                        col_offset=22,
                                        end_lineno=21,
                                        end_col_offset=39,
                                        arg='login',
                                        value=Constant(lineno=21, col_offset=28, end_lineno=21, end_col_offset=39, value='marketing', kind=None),
                                    ),
                                    keyword(
                                        lineno=22,
                                        col_offset=12,
                                        end_lineno=22,
                                        end_col_offset=73,
                                        arg='groups',
                                        value=Constant(lineno=22, col_offset=19, end_lineno=22, end_col_offset=73, value='base.group_user,mass_mailing.group_mass_mailing_user', kind=None),
                                    ),
                                    keyword(
                                        lineno=23,
                                        col_offset=12,
                                        end_lineno=23,
                                        end_col_offset=36,
                                        arg='name',
                                        value=Constant(lineno=23, col_offset=17, end_lineno=23, end_col_offset=36, value='Martial Marketing', kind=None),
                                    ),
                                    keyword(
                                        lineno=23,
                                        col_offset=38,
                                        end_lineno=23,
                                        end_col_offset=61,
                                        arg='signature',
                                        value=Constant(lineno=23, col_offset=48, end_lineno=23, end_col_offset=61, value='--\nMartial', kind=None),
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=26,
                            col_offset=8,
                            end_lineno=26,
                            end_col_offset=41,
                            targets=[
                                Attribute(
                                    lineno=26,
                                    col_offset=8,
                                    end_lineno=26,
                                    end_col_offset=25,
                                    value=Name(lineno=26, col_offset=8, end_lineno=26, end_col_offset=12, id='self', ctx=Load()),
                                    attr='alias_domain',
                                    ctx=Store(),
                                ),
                            ],
                            value=Constant(lineno=26, col_offset=28, end_lineno=26, end_col_offset=41, value='example.com', kind=None),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=27,
                            col_offset=8,
                            end_lineno=27,
                            end_col_offset=45,
                            targets=[
                                Attribute(
                                    lineno=27,
                                    col_offset=8,
                                    end_lineno=27,
                                    end_col_offset=27,
                                    value=Name(lineno=27, col_offset=8, end_lineno=27, end_col_offset=12, id='self', ctx=Load()),
                                    attr='alias_catchall',
                                    ctx=Store(),
                                ),
                            ],
                            value=Constant(lineno=27, col_offset=30, end_lineno=27, end_col_offset=45, value='catchall.test', kind=None),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=28,
                            col_offset=8,
                            end_lineno=28,
                            end_col_offset=41,
                            targets=[
                                Attribute(
                                    lineno=28,
                                    col_offset=8,
                                    end_lineno=28,
                                    end_col_offset=25,
                                    value=Name(lineno=28, col_offset=8, end_lineno=28, end_col_offset=12, id='self', ctx=Load()),
                                    attr='alias_bounce',
                                    ctx=Store(),
                                ),
                            ],
                            value=Constant(lineno=28, col_offset=28, end_lineno=28, end_col_offset=41, value='bounce.test', kind=None),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=29,
                            col_offset=8,
                            end_lineno=29,
                            end_col_offset=43,
                            targets=[
                                Attribute(
                                    lineno=29,
                                    col_offset=8,
                                    end_lineno=29,
                                    end_col_offset=25,
                                    value=Name(lineno=29, col_offset=8, end_lineno=29, end_col_offset=12, id='self', ctx=Load()),
                                    attr='default_from',
                                    ctx=Store(),
                                ),
                            ],
                            value=Constant(lineno=29, col_offset=28, end_lineno=29, end_col_offset=43, value='notifications', kind=None),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=30,
                            col_offset=8,
                            end_lineno=30,
                            end_col_offset=89,
                            value=Call(
                                lineno=30,
                                col_offset=8,
                                end_lineno=30,
                                end_col_offset=89,
                                func=Attribute(
                                    lineno=30,
                                    col_offset=8,
                                    end_lineno=30,
                                    end_col_offset=49,
                                    value=Subscript(
                                        lineno=30,
                                        col_offset=8,
                                        end_lineno=30,
                                        end_col_offset=39,
                                        value=Attribute(
                                            lineno=30,
                                            col_offset=8,
                                            end_lineno=30,
                                            end_col_offset=16,
                                            value=Name(lineno=30, col_offset=8, end_lineno=30, end_col_offset=12, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=30, col_offset=17, end_lineno=30, end_col_offset=38, value='ir.config_parameter', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='set_param',
                                    ctx=Load(),
                                ),
                                args=[
                                    Constant(lineno=30, col_offset=50, end_lineno=30, end_col_offset=69, value='mail.bounce.alias', kind=None),
                                    Attribute(
                                        lineno=30,
                                        col_offset=71,
                                        end_lineno=30,
                                        end_col_offset=88,
                                        value=Name(lineno=30, col_offset=71, end_lineno=30, end_col_offset=75, id='self', ctx=Load()),
                                        attr='alias_bounce',
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=31,
                            col_offset=8,
                            end_lineno=31,
                            end_col_offset=92,
                            value=Call(
                                lineno=31,
                                col_offset=8,
                                end_lineno=31,
                                end_col_offset=92,
                                func=Attribute(
                                    lineno=31,
                                    col_offset=8,
                                    end_lineno=31,
                                    end_col_offset=49,
                                    value=Subscript(
                                        lineno=31,
                                        col_offset=8,
                                        end_lineno=31,
                                        end_col_offset=39,
                                        value=Attribute(
                                            lineno=31,
                                            col_offset=8,
                                            end_lineno=31,
                                            end_col_offset=16,
                                            value=Name(lineno=31, col_offset=8, end_lineno=31, end_col_offset=12, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=31, col_offset=17, end_lineno=31, end_col_offset=38, value='ir.config_parameter', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='set_param',
                                    ctx=Load(),
                                ),
                                args=[
                                    Constant(lineno=31, col_offset=50, end_lineno=31, end_col_offset=72, value='mail.catchall.domain', kind=None),
                                    Attribute(
                                        lineno=31,
                                        col_offset=74,
                                        end_lineno=31,
                                        end_col_offset=91,
                                        value=Name(lineno=31, col_offset=74, end_lineno=31, end_col_offset=78, id='self', ctx=Load()),
                                        attr='alias_domain',
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=32,
                            col_offset=8,
                            end_lineno=32,
                            end_col_offset=93,
                            value=Call(
                                lineno=32,
                                col_offset=8,
                                end_lineno=32,
                                end_col_offset=93,
                                func=Attribute(
                                    lineno=32,
                                    col_offset=8,
                                    end_lineno=32,
                                    end_col_offset=49,
                                    value=Subscript(
                                        lineno=32,
                                        col_offset=8,
                                        end_lineno=32,
                                        end_col_offset=39,
                                        value=Attribute(
                                            lineno=32,
                                            col_offset=8,
                                            end_lineno=32,
                                            end_col_offset=16,
                                            value=Name(lineno=32, col_offset=8, end_lineno=32, end_col_offset=12, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=32, col_offset=17, end_lineno=32, end_col_offset=38, value='ir.config_parameter', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='set_param',
                                    ctx=Load(),
                                ),
                                args=[
                                    Constant(lineno=32, col_offset=50, end_lineno=32, end_col_offset=71, value='mail.catchall.alias', kind=None),
                                    Attribute(
                                        lineno=32,
                                        col_offset=73,
                                        end_lineno=32,
                                        end_col_offset=92,
                                        value=Name(lineno=32, col_offset=73, end_lineno=32, end_col_offset=77, id='self', ctx=Load()),
                                        attr='alias_catchall',
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=33,
                            col_offset=8,
                            end_lineno=33,
                            end_col_offset=89,
                            value=Call(
                                lineno=33,
                                col_offset=8,
                                end_lineno=33,
                                end_col_offset=89,
                                func=Attribute(
                                    lineno=33,
                                    col_offset=8,
                                    end_lineno=33,
                                    end_col_offset=49,
                                    value=Subscript(
                                        lineno=33,
                                        col_offset=8,
                                        end_lineno=33,
                                        end_col_offset=39,
                                        value=Attribute(
                                            lineno=33,
                                            col_offset=8,
                                            end_lineno=33,
                                            end_col_offset=16,
                                            value=Name(lineno=33, col_offset=8, end_lineno=33, end_col_offset=12, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=33, col_offset=17, end_lineno=33, end_col_offset=38, value='ir.config_parameter', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='set_param',
                                    ctx=Load(),
                                ),
                                args=[
                                    Constant(lineno=33, col_offset=50, end_lineno=33, end_col_offset=69, value='mail.default.from', kind=None),
                                    Attribute(
                                        lineno=33,
                                        col_offset=71,
                                        end_lineno=33,
                                        end_col_offset=88,
                                        value=Name(lineno=33, col_offset=71, end_lineno=33, end_col_offset=75, id='self', ctx=Load()),
                                        attr='default_from',
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=36,
                            col_offset=8,
                            end_lineno=36,
                            end_col_offset=52,
                            value=Call(
                                lineno=36,
                                col_offset=8,
                                end_lineno=36,
                                end_col_offset=52,
                                func=Attribute(
                                    lineno=36,
                                    col_offset=8,
                                    end_lineno=36,
                                    end_col_offset=18,
                                    value=Name(lineno=36, col_offset=8, end_lineno=36, end_col_offset=12, id='self', ctx=Load()),
                                    attr='patch',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=36,
                                        col_offset=19,
                                        end_lineno=36,
                                        end_col_offset=36,
                                        value=Attribute(
                                            lineno=36,
                                            col_offset=19,
                                            end_lineno=36,
                                            end_col_offset=27,
                                            value=Name(lineno=36, col_offset=19, end_lineno=36, end_col_offset=23, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        attr='registry',
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=36, col_offset=38, end_lineno=36, end_col_offset=45, value='ready', kind=None),
                                    Constant(lineno=36, col_offset=47, end_lineno=36, end_col_offset=51, value=True, kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
        ClassDef(
            lineno=40,
            col_offset=0,
            end_lineno=68,
            end_col_offset=47,
            name='TestMassMailPerformance',
            bases=[Name(lineno=40, col_offset=30, end_lineno=40, end_col_offset=57, id='TestMassMailPerformanceBase', ctx=Load())],
            keywords=[],
            body=[
                FunctionDef(
                    lineno=42,
                    col_offset=4,
                    end_lineno=48,
                    end_col_offset=69,
                    name='setUp',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=42, col_offset=14, end_lineno=42, end_col_offset=18, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=43,
                            col_offset=8,
                            end_lineno=43,
                            end_col_offset=52,
                            value=Call(
                                lineno=43,
                                col_offset=8,
                                end_lineno=43,
                                end_col_offset=52,
                                func=Attribute(
                                    lineno=43,
                                    col_offset=8,
                                    end_lineno=43,
                                    end_col_offset=50,
                                    value=Call(
                                        lineno=43,
                                        col_offset=8,
                                        end_lineno=43,
                                        end_col_offset=44,
                                        func=Name(lineno=43, col_offset=8, end_lineno=43, end_col_offset=13, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=43, col_offset=14, end_lineno=43, end_col_offset=37, id='TestMassMailPerformance', ctx=Load()),
                                            Name(lineno=43, col_offset=39, end_lineno=43, end_col_offset=43, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='setUp',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=44,
                            col_offset=8,
                            end_lineno=47,
                            end_col_offset=32,
                            targets=[Name(lineno=44, col_offset=8, end_lineno=44, end_col_offset=14, id='values', ctx=Store())],
                            value=ListComp(
                                lineno=44,
                                col_offset=17,
                                end_lineno=47,
                                end_col_offset=32,
                                elt=Dict(
                                    lineno=44,
                                    col_offset=18,
                                    end_lineno=47,
                                    end_col_offset=9,
                                    keys=[
                                        Constant(lineno=45, col_offset=12, end_lineno=45, end_col_offset=18, value='name', kind=None),
                                        Constant(lineno=46, col_offset=12, end_lineno=46, end_col_offset=24, value='email_from', kind=None),
                                    ],
                                    values=[
                                        BinOp(
                                            lineno=45,
                                            col_offset=20,
                                            end_lineno=45,
                                            end_col_offset=38,
                                            left=Constant(lineno=45, col_offset=20, end_lineno=45, end_col_offset=34, value='Recipient %s', kind=None),
                                            op=Mod(),
                                            right=Name(lineno=45, col_offset=37, end_lineno=45, end_col_offset=38, id='x', ctx=Load()),
                                        ),
                                        BinOp(
                                            lineno=46,
                                            col_offset=26,
                                            end_lineno=46,
                                            end_col_offset=62,
                                            left=Constant(lineno=46, col_offset=26, end_lineno=46, end_col_offset=58, value='Recipient <rec.%s@example.com>', kind=None),
                                            op=Mod(),
                                            right=Name(lineno=46, col_offset=61, end_lineno=46, end_col_offset=62, id='x', ctx=Load()),
                                        ),
                                    ],
                                ),
                                generators=[
                                    comprehension(
                                        target=Name(lineno=47, col_offset=14, end_lineno=47, end_col_offset=15, id='x', ctx=Store()),
                                        iter=Call(
                                            lineno=47,
                                            col_offset=19,
                                            end_lineno=47,
                                            end_col_offset=31,
                                            func=Name(lineno=47, col_offset=19, end_lineno=47, end_col_offset=24, id='range', ctx=Load()),
                                            args=[
                                                Constant(lineno=47, col_offset=25, end_lineno=47, end_col_offset=26, value=0, kind=None),
                                                Constant(lineno=47, col_offset=28, end_lineno=47, end_col_offset=30, value=50, kind=None),
                                            ],
                                            keywords=[],
                                        ),
                                        ifs=[],
                                        is_async=0,
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=48,
                            col_offset=8,
                            end_lineno=48,
                            end_col_offset=69,
                            targets=[
                                Attribute(
                                    lineno=48,
                                    col_offset=8,
                                    end_lineno=48,
                                    end_col_offset=20,
                                    value=Name(lineno=48, col_offset=8, end_lineno=48, end_col_offset=12, id='self', ctx=Load()),
                                    attr='mm_recs',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=48,
                                col_offset=23,
                                end_lineno=48,
                                end_col_offset=69,
                                func=Attribute(
                                    lineno=48,
                                    col_offset=23,
                                    end_lineno=48,
                                    end_col_offset=61,
                                    value=Subscript(
                                        lineno=48,
                                        col_offset=23,
                                        end_lineno=48,
                                        end_col_offset=54,
                                        value=Attribute(
                                            lineno=48,
                                            col_offset=23,
                                            end_lineno=48,
                                            end_col_offset=31,
                                            value=Name(lineno=48, col_offset=23, end_lineno=48, end_col_offset=27, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=48, col_offset=32, end_lineno=48, end_col_offset=53, value='mailing.performance', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[Name(lineno=48, col_offset=62, end_lineno=48, end_col_offset=68, id='values', ctx=Load())],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=53,
                    col_offset=4,
                    end_lineno=68,
                    end_col_offset=47,
                    name='test_send_mailing',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=53, col_offset=26, end_lineno=53, end_col_offset=30, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=54,
                            col_offset=8,
                            end_lineno=61,
                            end_col_offset=10,
                            targets=[Name(lineno=54, col_offset=8, end_lineno=54, end_col_offset=15, id='mailing', ctx=Store())],
                            value=Call(
                                lineno=54,
                                col_offset=18,
                                end_lineno=61,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=54,
                                    col_offset=18,
                                    end_lineno=54,
                                    end_col_offset=52,
                                    value=Subscript(
                                        lineno=54,
                                        col_offset=18,
                                        end_lineno=54,
                                        end_col_offset=45,
                                        value=Attribute(
                                            lineno=54,
                                            col_offset=18,
                                            end_lineno=54,
                                            end_col_offset=26,
                                            value=Name(lineno=54, col_offset=18, end_lineno=54, end_col_offset=22, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=54, col_offset=27, end_lineno=54, end_col_offset=44, value='mailing.mailing', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=54,
                                        col_offset=53,
                                        end_lineno=61,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=55, col_offset=12, end_lineno=55, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=56, col_offset=12, end_lineno=56, end_col_offset=21, value='subject', kind=None),
                                            Constant(lineno=57, col_offset=12, end_lineno=57, end_col_offset=23, value='body_html', kind=None),
                                            Constant(lineno=58, col_offset=12, end_lineno=58, end_col_offset=27, value='reply_to_mode', kind=None),
                                            Constant(lineno=59, col_offset=12, end_lineno=59, end_col_offset=30, value='mailing_model_id', kind=None),
                                            Constant(lineno=60, col_offset=12, end_lineno=60, end_col_offset=28, value='mailing_domain', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=55, col_offset=20, end_lineno=55, end_col_offset=26, value='Test', kind=None),
                                            Constant(lineno=56, col_offset=23, end_lineno=56, end_col_offset=29, value='Test', kind=None),
                                            Constant(lineno=57, col_offset=25, end_lineno=57, end_col_offset=174, value='<p>Hello <a role="button" href="https://www.example.com/foo/bar?baz=qux">quux</a><a role="button" href="/unsubscribe_from_list">Unsubscribe</a></p>', kind=None),
                                            Constant(lineno=58, col_offset=29, end_lineno=58, end_col_offset=34, value='new', kind=None),
                                            Call(
                                                lineno=59,
                                                col_offset=32,
                                                end_lineno=59,
                                                end_col_offset=87,
                                                func=Attribute(
                                                    lineno=59,
                                                    col_offset=32,
                                                    end_lineno=59,
                                                    end_col_offset=40,
                                                    value=Name(lineno=59, col_offset=32, end_lineno=59, end_col_offset=36, id='self', ctx=Load()),
                                                    attr='ref',
                                                    ctx=Load(),
                                                ),
                                                args=[Constant(lineno=59, col_offset=41, end_lineno=59, end_col_offset=86, value='test_mass_mailing.model_mailing_performance', kind=None)],
                                                keywords=[],
                                            ),
                                            List(
                                                lineno=60,
                                                col_offset=30,
                                                end_lineno=60,
                                                end_col_offset=62,
                                                elts=[
                                                    Tuple(
                                                        lineno=60,
                                                        col_offset=31,
                                                        end_lineno=60,
                                                        end_col_offset=61,
                                                        elts=[
                                                            Constant(lineno=60, col_offset=32, end_lineno=60, end_col_offset=36, value='id', kind=None),
                                                            Constant(lineno=60, col_offset=38, end_lineno=60, end_col_offset=42, value='in', kind=None),
                                                            Attribute(
                                                                lineno=60,
                                                                col_offset=44,
                                                                end_lineno=60,
                                                                end_col_offset=60,
                                                                value=Attribute(
                                                                    lineno=60,
                                                                    col_offset=44,
                                                                    end_lineno=60,
                                                                    end_col_offset=56,
                                                                    value=Name(lineno=60, col_offset=44, end_lineno=60, end_col_offset=48, id='self', ctx=Load()),
                                                                    attr='mm_recs',
                                                                    ctx=Load(),
                                                                ),
                                                                attr='ids',
                                                                ctx=Load(),
                                                            ),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        With(
                            lineno=64,
                            col_offset=8,
                            end_lineno=65,
                            end_col_offset=38,
                            items=[
                                withitem(
                                    context_expr=Call(
                                        lineno=64,
                                        col_offset=13,
                                        end_lineno=64,
                                        end_col_offset=67,
                                        func=Attribute(
                                            lineno=64,
                                            col_offset=13,
                                            end_lineno=64,
                                            end_col_offset=34,
                                            value=Name(lineno=64, col_offset=13, end_lineno=64, end_col_offset=17, id='self', ctx=Load()),
                                            attr='assertQueryCount',
                                            ctx=Load(),
                                        ),
                                        args=[],
                                        keywords=[
                                            keyword(
                                                lineno=64,
                                                col_offset=35,
                                                end_lineno=64,
                                                end_col_offset=50,
                                                arg='__system__',
                                                value=Constant(lineno=64, col_offset=46, end_lineno=64, end_col_offset=50, value=1669, kind=None),
                                            ),
                                            keyword(
                                                lineno=64,
                                                col_offset=52,
                                                end_lineno=64,
                                                end_col_offset=66,
                                                arg='marketing',
                                                value=Constant(lineno=64, col_offset=62, end_lineno=64, end_col_offset=66, value=1669, kind=None),
                                            ),
                                        ],
                                    ),
                                    optional_vars=None,
                                ),
                            ],
                            body=[
                                Expr(
                                    lineno=65,
                                    col_offset=12,
                                    end_lineno=65,
                                    end_col_offset=38,
                                    value=Call(
                                        lineno=65,
                                        col_offset=12,
                                        end_lineno=65,
                                        end_col_offset=38,
                                        func=Attribute(
                                            lineno=65,
                                            col_offset=12,
                                            end_lineno=65,
                                            end_col_offset=36,
                                            value=Name(lineno=65, col_offset=12, end_lineno=65, end_col_offset=19, id='mailing', ctx=Load()),
                                            attr='action_send_mail',
                                            ctx=Load(),
                                        ),
                                        args=[],
                                        keywords=[],
                                    ),
                                ),
                            ],
                            type_comment=None,
                        ),
                        Expr(
                            lineno=67,
                            col_offset=8,
                            end_lineno=67,
                            end_col_offset=42,
                            value=Call(
                                lineno=67,
                                col_offset=8,
                                end_lineno=67,
                                end_col_offset=42,
                                func=Attribute(
                                    lineno=67,
                                    col_offset=8,
                                    end_lineno=67,
                                    end_col_offset=24,
                                    value=Name(lineno=67, col_offset=8, end_lineno=67, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=67,
                                        col_offset=25,
                                        end_lineno=67,
                                        end_col_offset=37,
                                        value=Name(lineno=67, col_offset=25, end_lineno=67, end_col_offset=32, id='mailing', ctx=Load()),
                                        attr='sent',
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=67, col_offset=39, end_lineno=67, end_col_offset=41, value=50, kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=68,
                            col_offset=8,
                            end_lineno=68,
                            end_col_offset=47,
                            value=Call(
                                lineno=68,
                                col_offset=8,
                                end_lineno=68,
                                end_col_offset=47,
                                func=Attribute(
                                    lineno=68,
                                    col_offset=8,
                                    end_lineno=68,
                                    end_col_offset=24,
                                    value=Name(lineno=68, col_offset=8, end_lineno=68, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=68,
                                        col_offset=25,
                                        end_lineno=68,
                                        end_col_offset=42,
                                        value=Name(lineno=68, col_offset=25, end_lineno=68, end_col_offset=32, id='mailing', ctx=Load()),
                                        attr='delivered',
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=68, col_offset=44, end_lineno=68, end_col_offset=46, value=50, kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[
                        Call(
                            lineno=50,
                            col_offset=5,
                            end_lineno=50,
                            end_col_offset=37,
                            func=Name(lineno=50, col_offset=5, end_lineno=50, end_col_offset=10, id='users', ctx=Load()),
                            args=[
                                Constant(lineno=50, col_offset=11, end_lineno=50, end_col_offset=23, value='__system__', kind=None),
                                Constant(lineno=50, col_offset=25, end_lineno=50, end_col_offset=36, value='marketing', kind=None),
                            ],
                            keywords=[],
                        ),
                        Name(lineno=51, col_offset=5, end_lineno=51, end_col_offset=11, id='warmup', ctx=Load()),
                        Call(
                            lineno=52,
                            col_offset=5,
                            end_lineno=52,
                            end_col_offset=89,
                            func=Name(lineno=52, col_offset=5, end_lineno=52, end_col_offset=16, id='mute_logger', ctx=Load()),
                            args=[
                                Constant(lineno=52, col_offset=17, end_lineno=52, end_col_offset=52, value='odoo.addons.mail.models.mail_mail', kind=None),
                                Constant(lineno=52, col_offset=54, end_lineno=52, end_col_offset=74, value='odoo.models.unlink', kind=None),
                                Constant(lineno=52, col_offset=76, end_lineno=52, end_col_offset=88, value='odoo.tests', kind=None),
                            ],
                            keywords=[],
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[
                Call(
                    lineno=39,
                    col_offset=1,
                    end_lineno=39,
                    end_col_offset=27,
                    func=Name(lineno=39, col_offset=1, end_lineno=39, end_col_offset=7, id='tagged', ctx=Load()),
                    args=[Constant(lineno=39, col_offset=8, end_lineno=39, end_col_offset=26, value='mail_performance', kind=None)],
                    keywords=[],
                ),
            ],
        ),
        ClassDef(
            lineno=72,
            col_offset=0,
            end_lineno=108,
            end_col_offset=47,
            name='TestMassMailBlPerformance',
            bases=[Name(lineno=72, col_offset=32, end_lineno=72, end_col_offset=59, id='TestMassMailPerformanceBase', ctx=Load())],
            keywords=[],
            body=[
                FunctionDef(
                    lineno=74,
                    col_offset=4,
                    end_lineno=88,
                    end_col_offset=57,
                    name='setUp',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=74, col_offset=14, end_lineno=74, end_col_offset=18, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=75,
                            col_offset=8,
                            end_lineno=76,
                            end_col_offset=85,
                            value=Constant(lineno=75, col_offset=8, end_lineno=76, end_col_offset=85, value=' In this setup we prepare 20 blacklist entries. We therefore add\n        20 recipients compared to first test in order to have comparable results. ', kind=None),
                        ),
                        Expr(
                            lineno=77,
                            col_offset=8,
                            end_lineno=77,
                            end_col_offset=54,
                            value=Call(
                                lineno=77,
                                col_offset=8,
                                end_lineno=77,
                                end_col_offset=54,
                                func=Attribute(
                                    lineno=77,
                                    col_offset=8,
                                    end_lineno=77,
                                    end_col_offset=52,
                                    value=Call(
                                        lineno=77,
                                        col_offset=8,
                                        end_lineno=77,
                                        end_col_offset=46,
                                        func=Name(lineno=77, col_offset=8, end_lineno=77, end_col_offset=13, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=77, col_offset=14, end_lineno=77, end_col_offset=39, id='TestMassMailBlPerformance', ctx=Load()),
                                            Name(lineno=77, col_offset=41, end_lineno=77, end_col_offset=45, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='setUp',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=78,
                            col_offset=8,
                            end_lineno=81,
                            end_col_offset=32,
                            targets=[Name(lineno=78, col_offset=8, end_lineno=78, end_col_offset=14, id='values', ctx=Store())],
                            value=ListComp(
                                lineno=78,
                                col_offset=17,
                                end_lineno=81,
                                end_col_offset=32,
                                elt=Dict(
                                    lineno=78,
                                    col_offset=18,
                                    end_lineno=81,
                                    end_col_offset=9,
                                    keys=[
                                        Constant(lineno=79, col_offset=12, end_lineno=79, end_col_offset=18, value='name', kind=None),
                                        Constant(lineno=80, col_offset=12, end_lineno=80, end_col_offset=24, value='email_from', kind=None),
                                    ],
                                    values=[
                                        BinOp(
                                            lineno=79,
                                            col_offset=20,
                                            end_lineno=79,
                                            end_col_offset=38,
                                            left=Constant(lineno=79, col_offset=20, end_lineno=79, end_col_offset=34, value='Recipient %s', kind=None),
                                            op=Mod(),
                                            right=Name(lineno=79, col_offset=37, end_lineno=79, end_col_offset=38, id='x', ctx=Load()),
                                        ),
                                        BinOp(
                                            lineno=80,
                                            col_offset=26,
                                            end_lineno=80,
                                            end_col_offset=62,
                                            left=Constant(lineno=80, col_offset=26, end_lineno=80, end_col_offset=58, value='Recipient <rec.%s@example.com>', kind=None),
                                            op=Mod(),
                                            right=Name(lineno=80, col_offset=61, end_lineno=80, end_col_offset=62, id='x', ctx=Load()),
                                        ),
                                    ],
                                ),
                                generators=[
                                    comprehension(
                                        target=Name(lineno=81, col_offset=14, end_lineno=81, end_col_offset=15, id='x', ctx=Store()),
                                        iter=Call(
                                            lineno=81,
                                            col_offset=19,
                                            end_lineno=81,
                                            end_col_offset=31,
                                            func=Name(lineno=81, col_offset=19, end_lineno=81, end_col_offset=24, id='range', ctx=Load()),
                                            args=[
                                                Constant(lineno=81, col_offset=25, end_lineno=81, end_col_offset=26, value=0, kind=None),
                                                Constant(lineno=81, col_offset=28, end_lineno=81, end_col_offset=30, value=62, kind=None),
                                            ],
                                            keywords=[],
                                        ),
                                        ifs=[],
                                        is_async=0,
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=82,
                            col_offset=8,
                            end_lineno=82,
                            end_col_offset=79,
                            targets=[
                                Attribute(
                                    lineno=82,
                                    col_offset=8,
                                    end_lineno=82,
                                    end_col_offset=20,
                                    value=Name(lineno=82, col_offset=8, end_lineno=82, end_col_offset=12, id='self', ctx=Load()),
                                    attr='mm_recs',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=82,
                                col_offset=23,
                                end_lineno=82,
                                end_col_offset=79,
                                func=Attribute(
                                    lineno=82,
                                    col_offset=23,
                                    end_lineno=82,
                                    end_col_offset=71,
                                    value=Subscript(
                                        lineno=82,
                                        col_offset=23,
                                        end_lineno=82,
                                        end_col_offset=64,
                                        value=Attribute(
                                            lineno=82,
                                            col_offset=23,
                                            end_lineno=82,
                                            end_col_offset=31,
                                            value=Name(lineno=82, col_offset=23, end_lineno=82, end_col_offset=27, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=82, col_offset=32, end_lineno=82, end_col_offset=63, value='mailing.performance.blacklist', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[Name(lineno=82, col_offset=72, end_lineno=82, end_col_offset=78, id='values', ctx=Load())],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        For(
                            lineno=84,
                            col_offset=8,
                            end_lineno=87,
                            end_col_offset=14,
                            target=Name(lineno=84, col_offset=12, end_lineno=84, end_col_offset=13, id='x', ctx=Store()),
                            iter=Call(
                                lineno=84,
                                col_offset=17,
                                end_lineno=84,
                                end_col_offset=29,
                                func=Name(lineno=84, col_offset=17, end_lineno=84, end_col_offset=22, id='range', ctx=Load()),
                                args=[
                                    Constant(lineno=84, col_offset=23, end_lineno=84, end_col_offset=24, value=1, kind=None),
                                    Constant(lineno=84, col_offset=26, end_lineno=84, end_col_offset=28, value=13, kind=None),
                                ],
                                keywords=[],
                            ),
                            body=[
                                Expr(
                                    lineno=85,
                                    col_offset=12,
                                    end_lineno=87,
                                    end_col_offset=14,
                                    value=Call(
                                        lineno=85,
                                        col_offset=12,
                                        end_lineno=87,
                                        end_col_offset=14,
                                        func=Attribute(
                                            lineno=85,
                                            col_offset=12,
                                            end_lineno=85,
                                            end_col_offset=45,
                                            value=Subscript(
                                                lineno=85,
                                                col_offset=12,
                                                end_lineno=85,
                                                end_col_offset=38,
                                                value=Attribute(
                                                    lineno=85,
                                                    col_offset=12,
                                                    end_lineno=85,
                                                    end_col_offset=20,
                                                    value=Name(lineno=85, col_offset=12, end_lineno=85, end_col_offset=16, id='self', ctx=Load()),
                                                    attr='env',
                                                    ctx=Load(),
                                                ),
                                                slice=Constant(lineno=85, col_offset=21, end_lineno=85, end_col_offset=37, value='mail.blacklist', kind=None),
                                                ctx=Load(),
                                            ),
                                            attr='create',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Dict(
                                                lineno=85,
                                                col_offset=46,
                                                end_lineno=87,
                                                end_col_offset=13,
                                                keys=[Constant(lineno=86, col_offset=16, end_lineno=86, end_col_offset=23, value='email', kind=None)],
                                                values=[
                                                    BinOp(
                                                        lineno=86,
                                                        col_offset=25,
                                                        end_lineno=86,
                                                        end_col_offset=55,
                                                        left=Constant(lineno=86, col_offset=25, end_lineno=86, end_col_offset=45, value='rec.%s@example.com', kind=None),
                                                        op=Mod(),
                                                        right=BinOp(
                                                            lineno=86,
                                                            col_offset=49,
                                                            end_lineno=86,
                                                            end_col_offset=54,
                                                            left=Name(lineno=86, col_offset=49, end_lineno=86, end_col_offset=50, id='x', ctx=Load()),
                                                            op=Mult(),
                                                            right=Constant(lineno=86, col_offset=53, end_lineno=86, end_col_offset=54, value=5, kind=None),
                                                        ),
                                                    ),
                                                ],
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                ),
                            ],
                            orelse=[],
                            type_comment=None,
                        ),
                        Expr(
                            lineno=88,
                            col_offset=8,
                            end_lineno=88,
                            end_col_offset=57,
                            value=Call(
                                lineno=88,
                                col_offset=8,
                                end_lineno=88,
                                end_col_offset=57,
                                func=Attribute(
                                    lineno=88,
                                    col_offset=8,
                                    end_lineno=88,
                                    end_col_offset=55,
                                    value=Subscript(
                                        lineno=88,
                                        col_offset=8,
                                        end_lineno=88,
                                        end_col_offset=49,
                                        value=Attribute(
                                            lineno=88,
                                            col_offset=8,
                                            end_lineno=88,
                                            end_col_offset=16,
                                            value=Name(lineno=88, col_offset=8, end_lineno=88, end_col_offset=12, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=88, col_offset=17, end_lineno=88, end_col_offset=48, value='mailing.performance.blacklist', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='flush',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=93,
                    col_offset=4,
                    end_lineno=108,
                    end_col_offset=47,
                    name='test_send_mailing_w_bl',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=93, col_offset=31, end_lineno=93, end_col_offset=35, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=94,
                            col_offset=8,
                            end_lineno=101,
                            end_col_offset=10,
                            targets=[Name(lineno=94, col_offset=8, end_lineno=94, end_col_offset=15, id='mailing', ctx=Store())],
                            value=Call(
                                lineno=94,
                                col_offset=18,
                                end_lineno=101,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=94,
                                    col_offset=18,
                                    end_lineno=94,
                                    end_col_offset=52,
                                    value=Subscript(
                                        lineno=94,
                                        col_offset=18,
                                        end_lineno=94,
                                        end_col_offset=45,
                                        value=Attribute(
                                            lineno=94,
                                            col_offset=18,
                                            end_lineno=94,
                                            end_col_offset=26,
                                            value=Name(lineno=94, col_offset=18, end_lineno=94, end_col_offset=22, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=94, col_offset=27, end_lineno=94, end_col_offset=44, value='mailing.mailing', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=94,
                                        col_offset=53,
                                        end_lineno=101,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=95, col_offset=12, end_lineno=95, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=96, col_offset=12, end_lineno=96, end_col_offset=21, value='subject', kind=None),
                                            Constant(lineno=97, col_offset=12, end_lineno=97, end_col_offset=23, value='body_html', kind=None),
                                            Constant(lineno=98, col_offset=12, end_lineno=98, end_col_offset=27, value='reply_to_mode', kind=None),
                                            Constant(lineno=99, col_offset=12, end_lineno=99, end_col_offset=30, value='mailing_model_id', kind=None),
                                            Constant(lineno=100, col_offset=12, end_lineno=100, end_col_offset=28, value='mailing_domain', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=95, col_offset=20, end_lineno=95, end_col_offset=26, value='Test', kind=None),
                                            Constant(lineno=96, col_offset=23, end_lineno=96, end_col_offset=29, value='Test', kind=None),
                                            Constant(lineno=97, col_offset=25, end_lineno=97, end_col_offset=174, value='<p>Hello <a role="button" href="https://www.example.com/foo/bar?baz=qux">quux</a><a role="button" href="/unsubscribe_from_list">Unsubscribe</a></p>', kind=None),
                                            Constant(lineno=98, col_offset=29, end_lineno=98, end_col_offset=34, value='new', kind=None),
                                            Call(
                                                lineno=99,
                                                col_offset=32,
                                                end_lineno=99,
                                                end_col_offset=97,
                                                func=Attribute(
                                                    lineno=99,
                                                    col_offset=32,
                                                    end_lineno=99,
                                                    end_col_offset=40,
                                                    value=Name(lineno=99, col_offset=32, end_lineno=99, end_col_offset=36, id='self', ctx=Load()),
                                                    attr='ref',
                                                    ctx=Load(),
                                                ),
                                                args=[Constant(lineno=99, col_offset=41, end_lineno=99, end_col_offset=96, value='test_mass_mailing.model_mailing_performance_blacklist', kind=None)],
                                                keywords=[],
                                            ),
                                            List(
                                                lineno=100,
                                                col_offset=30,
                                                end_lineno=100,
                                                end_col_offset=62,
                                                elts=[
                                                    Tuple(
                                                        lineno=100,
                                                        col_offset=31,
                                                        end_lineno=100,
                                                        end_col_offset=61,
                                                        elts=[
                                                            Constant(lineno=100, col_offset=32, end_lineno=100, end_col_offset=36, value='id', kind=None),
                                                            Constant(lineno=100, col_offset=38, end_lineno=100, end_col_offset=42, value='in', kind=None),
                                                            Attribute(
                                                                lineno=100,
                                                                col_offset=44,
                                                                end_lineno=100,
                                                                end_col_offset=60,
                                                                value=Attribute(
                                                                    lineno=100,
                                                                    col_offset=44,
                                                                    end_lineno=100,
                                                                    end_col_offset=56,
                                                                    value=Name(lineno=100, col_offset=44, end_lineno=100, end_col_offset=48, id='self', ctx=Load()),
                                                                    attr='mm_recs',
                                                                    ctx=Load(),
                                                                ),
                                                                attr='ids',
                                                                ctx=Load(),
                                                            ),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        With(
                            lineno=104,
                            col_offset=8,
                            end_lineno=105,
                            end_col_offset=38,
                            items=[
                                withitem(
                                    context_expr=Call(
                                        lineno=104,
                                        col_offset=13,
                                        end_lineno=104,
                                        end_col_offset=67,
                                        func=Attribute(
                                            lineno=104,
                                            col_offset=13,
                                            end_lineno=104,
                                            end_col_offset=34,
                                            value=Name(lineno=104, col_offset=13, end_lineno=104, end_col_offset=17, id='self', ctx=Load()),
                                            attr='assertQueryCount',
                                            ctx=Load(),
                                        ),
                                        args=[],
                                        keywords=[
                                            keyword(
                                                lineno=104,
                                                col_offset=35,
                                                end_lineno=104,
                                                end_col_offset=50,
                                                arg='__system__',
                                                value=Constant(lineno=104, col_offset=46, end_lineno=104, end_col_offset=50, value=1959, kind=None),
                                            ),
                                            keyword(
                                                lineno=104,
                                                col_offset=52,
                                                end_lineno=104,
                                                end_col_offset=66,
                                                arg='marketing',
                                                value=Constant(lineno=104, col_offset=62, end_lineno=104, end_col_offset=66, value=1959, kind=None),
                                            ),
                                        ],
                                    ),
                                    optional_vars=None,
                                ),
                            ],
                            body=[
                                Expr(
                                    lineno=105,
                                    col_offset=12,
                                    end_lineno=105,
                                    end_col_offset=38,
                                    value=Call(
                                        lineno=105,
                                        col_offset=12,
                                        end_lineno=105,
                                        end_col_offset=38,
                                        func=Attribute(
                                            lineno=105,
                                            col_offset=12,
                                            end_lineno=105,
                                            end_col_offset=36,
                                            value=Name(lineno=105, col_offset=12, end_lineno=105, end_col_offset=19, id='mailing', ctx=Load()),
                                            attr='action_send_mail',
                                            ctx=Load(),
                                        ),
                                        args=[],
                                        keywords=[],
                                    ),
                                ),
                            ],
                            type_comment=None,
                        ),
                        Expr(
                            lineno=107,
                            col_offset=8,
                            end_lineno=107,
                            end_col_offset=42,
                            value=Call(
                                lineno=107,
                                col_offset=8,
                                end_lineno=107,
                                end_col_offset=42,
                                func=Attribute(
                                    lineno=107,
                                    col_offset=8,
                                    end_lineno=107,
                                    end_col_offset=24,
                                    value=Name(lineno=107, col_offset=8, end_lineno=107, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=107,
                                        col_offset=25,
                                        end_lineno=107,
                                        end_col_offset=37,
                                        value=Name(lineno=107, col_offset=25, end_lineno=107, end_col_offset=32, id='mailing', ctx=Load()),
                                        attr='sent',
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=107, col_offset=39, end_lineno=107, end_col_offset=41, value=50, kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=108,
                            col_offset=8,
                            end_lineno=108,
                            end_col_offset=47,
                            value=Call(
                                lineno=108,
                                col_offset=8,
                                end_lineno=108,
                                end_col_offset=47,
                                func=Attribute(
                                    lineno=108,
                                    col_offset=8,
                                    end_lineno=108,
                                    end_col_offset=24,
                                    value=Name(lineno=108, col_offset=8, end_lineno=108, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=108,
                                        col_offset=25,
                                        end_lineno=108,
                                        end_col_offset=42,
                                        value=Name(lineno=108, col_offset=25, end_lineno=108, end_col_offset=32, id='mailing', ctx=Load()),
                                        attr='delivered',
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=108, col_offset=44, end_lineno=108, end_col_offset=46, value=50, kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[
                        Call(
                            lineno=90,
                            col_offset=5,
                            end_lineno=90,
                            end_col_offset=37,
                            func=Name(lineno=90, col_offset=5, end_lineno=90, end_col_offset=10, id='users', ctx=Load()),
                            args=[
                                Constant(lineno=90, col_offset=11, end_lineno=90, end_col_offset=23, value='__system__', kind=None),
                                Constant(lineno=90, col_offset=25, end_lineno=90, end_col_offset=36, value='marketing', kind=None),
                            ],
                            keywords=[],
                        ),
                        Name(lineno=91, col_offset=5, end_lineno=91, end_col_offset=11, id='warmup', ctx=Load()),
                        Call(
                            lineno=92,
                            col_offset=5,
                            end_lineno=92,
                            end_col_offset=89,
                            func=Name(lineno=92, col_offset=5, end_lineno=92, end_col_offset=16, id='mute_logger', ctx=Load()),
                            args=[
                                Constant(lineno=92, col_offset=17, end_lineno=92, end_col_offset=52, value='odoo.addons.mail.models.mail_mail', kind=None),
                                Constant(lineno=92, col_offset=54, end_lineno=92, end_col_offset=74, value='odoo.models.unlink', kind=None),
                                Constant(lineno=92, col_offset=76, end_lineno=92, end_col_offset=88, value='odoo.tests', kind=None),
                            ],
                            keywords=[],
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[
                Call(
                    lineno=71,
                    col_offset=1,
                    end_lineno=71,
                    end_col_offset=27,
                    func=Name(lineno=71, col_offset=1, end_lineno=71, end_col_offset=7, id='tagged', ctx=Load()),
                    args=[Constant(lineno=71, col_offset=8, end_lineno=71, end_col_offset=26, value='mail_performance', kind=None)],
                    keywords=[],
                ),
            ],
        ),
    ],
    type_ignores=[],
)
