Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=43,
            module='odoo',
            names=[
                alias(name='api', asname=None),
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
                alias(name='tools', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=43,
            end_col_offset=12,
            name='ImLivechatReportOperator',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=31,
                    end_lineno=7,
                    end_col_offset=43,
                    value=Name(lineno=7, col_offset=31, end_lineno=7, end_col_offset=37, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Expr(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=51,
                    value=Constant(lineno=8, col_offset=4, end_lineno=8, end_col_offset=51, value=' Livechat Support Report on the Operator ', kind=None),
                ),
                Assign(
                    lineno=10,
                    col_offset=4,
                    end_lineno=10,
                    end_col_offset=41,
                    targets=[Name(lineno=10, col_offset=4, end_lineno=10, end_col_offset=9, id='_name', ctx=Store())],
                    value=Constant(lineno=10, col_offset=12, end_lineno=10, end_col_offset=41, value='im_livechat.report.operator', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=11,
                    col_offset=4,
                    end_lineno=11,
                    end_col_offset=53,
                    targets=[Name(lineno=11, col_offset=4, end_lineno=11, end_col_offset=16, id='_description', ctx=Store())],
                    value=Constant(lineno=11, col_offset=19, end_lineno=11, end_col_offset=53, value='Livechat Support Operator Report', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=12,
                    col_offset=4,
                    end_lineno=12,
                    end_col_offset=46,
                    targets=[Name(lineno=12, col_offset=4, end_lineno=12, end_col_offset=10, id='_order', ctx=Store())],
                    value=Constant(lineno=12, col_offset=13, end_lineno=12, end_col_offset=46, value='livechat_channel_id, partner_id', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=13,
                    col_offset=4,
                    end_lineno=13,
                    end_col_offset=17,
                    targets=[Name(lineno=13, col_offset=4, end_lineno=13, end_col_offset=9, id='_auto', ctx=Store())],
                    value=Constant(lineno=13, col_offset=12, end_lineno=13, end_col_offset=17, value=False, kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=15,
                    col_offset=4,
                    end_lineno=15,
                    end_col_offset=74,
                    targets=[Name(lineno=15, col_offset=4, end_lineno=15, end_col_offset=14, id='partner_id', ctx=Store())],
                    value=Call(
                        lineno=15,
                        col_offset=17,
                        end_lineno=15,
                        end_col_offset=74,
                        func=Attribute(
                            lineno=15,
                            col_offset=17,
                            end_lineno=15,
                            end_col_offset=32,
                            value=Name(lineno=15, col_offset=17, end_lineno=15, end_col_offset=23, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[
                            Constant(lineno=15, col_offset=33, end_lineno=15, end_col_offset=46, value='res.partner', kind=None),
                            Constant(lineno=15, col_offset=48, end_lineno=15, end_col_offset=58, value='Operator', kind=None),
                        ],
                        keywords=[
                            keyword(
                                lineno=15,
                                col_offset=60,
                                end_lineno=15,
                                end_col_offset=73,
                                arg='readonly',
                                value=Constant(lineno=15, col_offset=69, end_lineno=15, end_col_offset=73, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=16,
                    col_offset=4,
                    end_lineno=16,
                    end_col_offset=90,
                    targets=[Name(lineno=16, col_offset=4, end_lineno=16, end_col_offset=23, id='livechat_channel_id', ctx=Store())],
                    value=Call(
                        lineno=16,
                        col_offset=26,
                        end_lineno=16,
                        end_col_offset=90,
                        func=Attribute(
                            lineno=16,
                            col_offset=26,
                            end_lineno=16,
                            end_col_offset=41,
                            value=Name(lineno=16, col_offset=26, end_lineno=16, end_col_offset=32, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[
                            Constant(lineno=16, col_offset=42, end_lineno=16, end_col_offset=63, value='im_livechat.channel', kind=None),
                            Constant(lineno=16, col_offset=65, end_lineno=16, end_col_offset=74, value='Channel', kind=None),
                        ],
                        keywords=[
                            keyword(
                                lineno=16,
                                col_offset=76,
                                end_lineno=16,
                                end_col_offset=89,
                                arg='readonly',
                                value=Constant(lineno=16, col_offset=85, end_lineno=16, end_col_offset=89, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=17,
                    col_offset=4,
                    end_lineno=17,
                    end_col_offset=117,
                    targets=[Name(lineno=17, col_offset=4, end_lineno=17, end_col_offset=15, id='nbr_channel', ctx=Store())],
                    value=Call(
                        lineno=17,
                        col_offset=18,
                        end_lineno=17,
                        end_col_offset=117,
                        func=Attribute(
                            lineno=17,
                            col_offset=18,
                            end_lineno=17,
                            end_col_offset=32,
                            value=Name(lineno=17, col_offset=18, end_lineno=17, end_col_offset=24, id='fields', ctx=Load()),
                            attr='Integer',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=17, col_offset=33, end_lineno=17, end_col_offset=48, value='# of Sessions', kind=None)],
                        keywords=[
                            keyword(
                                lineno=17,
                                col_offset=50,
                                end_lineno=17,
                                end_col_offset=63,
                                arg='readonly',
                                value=Constant(lineno=17, col_offset=59, end_lineno=17, end_col_offset=63, value=True, kind=None),
                            ),
                            keyword(
                                lineno=17,
                                col_offset=65,
                                end_lineno=17,
                                end_col_offset=85,
                                arg='group_operator',
                                value=Constant(lineno=17, col_offset=80, end_lineno=17, end_col_offset=85, value='sum', kind=None),
                            ),
                            keyword(
                                lineno=17,
                                col_offset=87,
                                end_lineno=17,
                                end_col_offset=116,
                                arg='help',
                                value=Constant(lineno=17, col_offset=92, end_lineno=17, end_col_offset=116, value='Number of conversation', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=18,
                    col_offset=4,
                    end_lineno=18,
                    end_col_offset=79,
                    targets=[Name(lineno=18, col_offset=4, end_lineno=18, end_col_offset=14, id='channel_id', ctx=Store())],
                    value=Call(
                        lineno=18,
                        col_offset=17,
                        end_lineno=18,
                        end_col_offset=79,
                        func=Attribute(
                            lineno=18,
                            col_offset=17,
                            end_lineno=18,
                            end_col_offset=32,
                            value=Name(lineno=18, col_offset=17, end_lineno=18, end_col_offset=23, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[
                            Constant(lineno=18, col_offset=33, end_lineno=18, end_col_offset=47, value='mail.channel', kind=None),
                            Constant(lineno=18, col_offset=49, end_lineno=18, end_col_offset=63, value='Conversation', kind=None),
                        ],
                        keywords=[
                            keyword(
                                lineno=18,
                                col_offset=65,
                                end_lineno=18,
                                end_col_offset=78,
                                arg='readonly',
                                value=Constant(lineno=18, col_offset=74, end_lineno=18, end_col_offset=78, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=19,
                    col_offset=4,
                    end_lineno=19,
                    end_col_offset=111,
                    targets=[Name(lineno=19, col_offset=4, end_lineno=19, end_col_offset=14, id='start_date', ctx=Store())],
                    value=Call(
                        lineno=19,
                        col_offset=17,
                        end_lineno=19,
                        end_col_offset=111,
                        func=Attribute(
                            lineno=19,
                            col_offset=17,
                            end_lineno=19,
                            end_col_offset=32,
                            value=Name(lineno=19, col_offset=17, end_lineno=19, end_col_offset=23, id='fields', ctx=Load()),
                            attr='Datetime',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=19, col_offset=33, end_lineno=19, end_col_offset=56, value='Start Date of session', kind=None)],
                        keywords=[
                            keyword(
                                lineno=19,
                                col_offset=58,
                                end_lineno=19,
                                end_col_offset=71,
                                arg='readonly',
                                value=Constant(lineno=19, col_offset=67, end_lineno=19, end_col_offset=71, value=True, kind=None),
                            ),
                            keyword(
                                lineno=19,
                                col_offset=73,
                                end_lineno=19,
                                end_col_offset=110,
                                arg='help',
                                value=Constant(lineno=19, col_offset=78, end_lineno=19, end_col_offset=110, value='Start date of the conversation', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=20,
                    col_offset=4,
                    end_lineno=20,
                    end_col_offset=165,
                    targets=[Name(lineno=20, col_offset=4, end_lineno=20, end_col_offset=18, id='time_to_answer', ctx=Store())],
                    value=Call(
                        lineno=20,
                        col_offset=21,
                        end_lineno=20,
                        end_col_offset=165,
                        func=Attribute(
                            lineno=20,
                            col_offset=21,
                            end_lineno=20,
                            end_col_offset=33,
                            value=Name(lineno=20, col_offset=21, end_lineno=20, end_col_offset=27, id='fields', ctx=Load()),
                            attr='Float',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=20, col_offset=34, end_lineno=20, end_col_offset=50, value='Time to answer', kind=None)],
                        keywords=[
                            keyword(
                                lineno=20,
                                col_offset=52,
                                end_lineno=20,
                                end_col_offset=66,
                                arg='digits',
                                value=Tuple(
                                    lineno=20,
                                    col_offset=59,
                                    end_lineno=20,
                                    end_col_offset=66,
                                    elts=[
                                        Constant(lineno=20, col_offset=60, end_lineno=20, end_col_offset=62, value=16, kind=None),
                                        Constant(lineno=20, col_offset=64, end_lineno=20, end_col_offset=65, value=2, kind=None),
                                    ],
                                    ctx=Load(),
                                ),
                            ),
                            keyword(
                                lineno=20,
                                col_offset=68,
                                end_lineno=20,
                                end_col_offset=81,
                                arg='readonly',
                                value=Constant(lineno=20, col_offset=77, end_lineno=20, end_col_offset=81, value=True, kind=None),
                            ),
                            keyword(
                                lineno=20,
                                col_offset=83,
                                end_lineno=20,
                                end_col_offset=103,
                                arg='group_operator',
                                value=Constant(lineno=20, col_offset=98, end_lineno=20, end_col_offset=103, value='avg', kind=None),
                            ),
                            keyword(
                                lineno=20,
                                col_offset=105,
                                end_lineno=20,
                                end_col_offset=164,
                                arg='help',
                                value=Constant(lineno=20, col_offset=110, end_lineno=20, end_col_offset=164, value='Average time to give the first answer to the visitor', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=21,
                    col_offset=4,
                    end_lineno=21,
                    end_col_offset=150,
                    targets=[Name(lineno=21, col_offset=4, end_lineno=21, end_col_offset=12, id='duration', ctx=Store())],
                    value=Call(
                        lineno=21,
                        col_offset=15,
                        end_lineno=21,
                        end_col_offset=150,
                        func=Attribute(
                            lineno=21,
                            col_offset=15,
                            end_lineno=21,
                            end_col_offset=27,
                            value=Name(lineno=21, col_offset=15, end_lineno=21, end_col_offset=21, id='fields', ctx=Load()),
                            attr='Float',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=21, col_offset=28, end_lineno=21, end_col_offset=46, value='Average duration', kind=None)],
                        keywords=[
                            keyword(
                                lineno=21,
                                col_offset=48,
                                end_lineno=21,
                                end_col_offset=62,
                                arg='digits',
                                value=Tuple(
                                    lineno=21,
                                    col_offset=55,
                                    end_lineno=21,
                                    end_col_offset=62,
                                    elts=[
                                        Constant(lineno=21, col_offset=56, end_lineno=21, end_col_offset=58, value=16, kind=None),
                                        Constant(lineno=21, col_offset=60, end_lineno=21, end_col_offset=61, value=2, kind=None),
                                    ],
                                    ctx=Load(),
                                ),
                            ),
                            keyword(
                                lineno=21,
                                col_offset=64,
                                end_lineno=21,
                                end_col_offset=77,
                                arg='readonly',
                                value=Constant(lineno=21, col_offset=73, end_lineno=21, end_col_offset=77, value=True, kind=None),
                            ),
                            keyword(
                                lineno=21,
                                col_offset=79,
                                end_lineno=21,
                                end_col_offset=99,
                                arg='group_operator',
                                value=Constant(lineno=21, col_offset=94, end_lineno=21, end_col_offset=99, value='avg', kind=None),
                            ),
                            keyword(
                                lineno=21,
                                col_offset=101,
                                end_lineno=21,
                                end_col_offset=149,
                                arg='help',
                                value=Constant(lineno=21, col_offset=106, end_lineno=21, end_col_offset=149, value='Duration of the conversation (in seconds)', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=23,
                    col_offset=4,
                    end_lineno=43,
                    end_col_offset=12,
                    name='init',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=23, col_offset=13, end_lineno=23, end_col_offset=17, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=25,
                            col_offset=8,
                            end_lineno=25,
                            end_col_offset=77,
                            value=Call(
                                lineno=25,
                                col_offset=8,
                                end_lineno=25,
                                end_col_offset=77,
                                func=Attribute(
                                    lineno=25,
                                    col_offset=8,
                                    end_lineno=25,
                                    end_col_offset=33,
                                    value=Name(lineno=25, col_offset=8, end_lineno=25, end_col_offset=13, id='tools', ctx=Load()),
                                    attr='drop_view_if_exists',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=25,
                                        col_offset=34,
                                        end_lineno=25,
                                        end_col_offset=45,
                                        value=Attribute(
                                            lineno=25,
                                            col_offset=34,
                                            end_lineno=25,
                                            end_col_offset=42,
                                            value=Name(lineno=25, col_offset=34, end_lineno=25, end_col_offset=38, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        attr='cr',
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=25, col_offset=47, end_lineno=25, end_col_offset=76, value='im_livechat_report_operator', kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=26,
                            col_offset=8,
                            end_lineno=43,
                            end_col_offset=12,
                            value=Call(
                                lineno=26,
                                col_offset=8,
                                end_lineno=43,
                                end_col_offset=12,
                                func=Attribute(
                                    lineno=26,
                                    col_offset=8,
                                    end_lineno=26,
                                    end_col_offset=27,
                                    value=Attribute(
                                        lineno=26,
                                        col_offset=8,
                                        end_lineno=26,
                                        end_col_offset=19,
                                        value=Attribute(
                                            lineno=26,
                                            col_offset=8,
                                            end_lineno=26,
                                            end_col_offset=16,
                                            value=Name(lineno=26, col_offset=8, end_lineno=26, end_col_offset=12, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        attr='cr',
                                        ctx=Load(),
                                    ),
                                    attr='execute',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=26, col_offset=28, end_lineno=43, end_col_offset=11, value="\n            CREATE OR REPLACE VIEW im_livechat_report_operator AS (\n                SELECT\n                    row_number() OVER () AS id,\n                    C.livechat_operator_id AS partner_id,\n                    C.livechat_channel_id AS livechat_channel_id,\n                    COUNT(DISTINCT C.id) AS nbr_channel,\n                    C.id AS channel_id,\n                    C.create_date AS start_date,\n                    EXTRACT('epoch' FROM MAX(M.create_date) - MIN(M.create_date)) AS duration,\n                    EXTRACT('epoch' FROM MIN(MO.create_date) - MIN(M.create_date)) AS time_to_answer\n                FROM mail_channel C\n                    JOIN mail_message M ON M.res_id = C.id AND M.model = 'mail.channel'\n                    LEFT JOIN mail_message MO ON (MO.res_id = C.id AND M.model = 'mail.channel' AND MO.author_id = C.livechat_operator_id)\n                WHERE C.livechat_channel_id IS NOT NULL\n                GROUP BY C.id, C.livechat_operator_id\n            )\n        ", kind=None)],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
