Module(
    body=[
        ImportFrom(
            lineno=2,
            col_offset=0,
            end_lineno=2,
            end_col_offset=29,
            module='odoo.tests',
            names=[alias(name='common', asname=None)],
            level=0,
        ),
        ClassDef(
            lineno=5,
            col_offset=0,
            end_lineno=63,
            end_col_offset=11,
            name='TestEmptyDate',
            bases=[
                Attribute(
                    lineno=5,
                    col_offset=20,
                    end_lineno=5,
                    end_col_offset=42,
                    value=Name(lineno=5, col_offset=20, end_lineno=5, end_col_offset=26, id='common', ctx=Load()),
                    attr='TransactionCase',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Expr(
                    lineno=6,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=7,
                    value=Constant(lineno=6, col_offset=4, end_lineno=8, end_col_offset=7, value=' Test what happens when grouping on date fields and getting a "false"\n    grouping value\n    ', kind=None),
                ),
                FunctionDef(
                    lineno=9,
                    col_offset=4,
                    end_lineno=11,
                    end_col_offset=56,
                    name='setUp',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=9, col_offset=14, end_lineno=9, end_col_offset=18, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=10,
                            col_offset=8,
                            end_lineno=10,
                            end_col_offset=42,
                            value=Call(
                                lineno=10,
                                col_offset=8,
                                end_lineno=10,
                                end_col_offset=42,
                                func=Attribute(
                                    lineno=10,
                                    col_offset=8,
                                    end_lineno=10,
                                    end_col_offset=40,
                                    value=Call(
                                        lineno=10,
                                        col_offset=8,
                                        end_lineno=10,
                                        end_col_offset=34,
                                        func=Name(lineno=10, col_offset=8, end_lineno=10, end_col_offset=13, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=10, col_offset=14, end_lineno=10, end_col_offset=27, id='TestEmptyDate', ctx=Load()),
                                            Name(lineno=10, col_offset=29, end_lineno=10, end_col_offset=33, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='setUp',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=11,
                            col_offset=8,
                            end_lineno=11,
                            end_col_offset=56,
                            targets=[
                                Attribute(
                                    lineno=11,
                                    col_offset=8,
                                    end_lineno=11,
                                    end_col_offset=18,
                                    value=Name(lineno=11, col_offset=8, end_lineno=11, end_col_offset=12, id='self', ctx=Load()),
                                    attr='Model',
                                    ctx=Store(),
                                ),
                            ],
                            value=Subscript(
                                lineno=11,
                                col_offset=21,
                                end_lineno=11,
                                end_col_offset=56,
                                value=Attribute(
                                    lineno=11,
                                    col_offset=21,
                                    end_lineno=11,
                                    end_col_offset=29,
                                    value=Name(lineno=11, col_offset=21, end_lineno=11, end_col_offset=25, id='self', ctx=Load()),
                                    attr='env',
                                    ctx=Load(),
                                ),
                                slice=Constant(lineno=11, col_offset=30, end_lineno=11, end_col_offset=55, value='test_read_group.on_date', kind=None),
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=13,
                    col_offset=4,
                    end_lineno=26,
                    end_col_offset=11,
                    name='test_empty_only',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=13, col_offset=24, end_lineno=13, end_col_offset=28, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=14,
                            col_offset=8,
                            end_lineno=14,
                            end_col_offset=39,
                            value=Call(
                                lineno=14,
                                col_offset=8,
                                end_lineno=14,
                                end_col_offset=39,
                                func=Attribute(
                                    lineno=14,
                                    col_offset=8,
                                    end_lineno=14,
                                    end_col_offset=25,
                                    value=Attribute(
                                        lineno=14,
                                        col_offset=8,
                                        end_lineno=14,
                                        end_col_offset=18,
                                        value=Name(lineno=14, col_offset=8, end_lineno=14, end_col_offset=12, id='self', ctx=Load()),
                                        attr='Model',
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=14,
                                        col_offset=26,
                                        end_lineno=14,
                                        end_col_offset=38,
                                        keys=[Constant(lineno=14, col_offset=27, end_lineno=14, end_col_offset=34, value='value', kind=None)],
                                        values=[Constant(lineno=14, col_offset=36, end_lineno=14, end_col_offset=37, value=1, kind=None)],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=15,
                            col_offset=8,
                            end_lineno=15,
                            end_col_offset=39,
                            value=Call(
                                lineno=15,
                                col_offset=8,
                                end_lineno=15,
                                end_col_offset=39,
                                func=Attribute(
                                    lineno=15,
                                    col_offset=8,
                                    end_lineno=15,
                                    end_col_offset=25,
                                    value=Attribute(
                                        lineno=15,
                                        col_offset=8,
                                        end_lineno=15,
                                        end_col_offset=18,
                                        value=Name(lineno=15, col_offset=8, end_lineno=15, end_col_offset=12, id='self', ctx=Load()),
                                        attr='Model',
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=15,
                                        col_offset=26,
                                        end_lineno=15,
                                        end_col_offset=38,
                                        keys=[Constant(lineno=15, col_offset=27, end_lineno=15, end_col_offset=34, value='value', kind=None)],
                                        values=[Constant(lineno=15, col_offset=36, end_lineno=15, end_col_offset=37, value=2, kind=None)],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=16,
                            col_offset=8,
                            end_lineno=16,
                            end_col_offset=39,
                            value=Call(
                                lineno=16,
                                col_offset=8,
                                end_lineno=16,
                                end_col_offset=39,
                                func=Attribute(
                                    lineno=16,
                                    col_offset=8,
                                    end_lineno=16,
                                    end_col_offset=25,
                                    value=Attribute(
                                        lineno=16,
                                        col_offset=8,
                                        end_lineno=16,
                                        end_col_offset=18,
                                        value=Name(lineno=16, col_offset=8, end_lineno=16, end_col_offset=12, id='self', ctx=Load()),
                                        attr='Model',
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=16,
                                        col_offset=26,
                                        end_lineno=16,
                                        end_col_offset=38,
                                        keys=[Constant(lineno=16, col_offset=27, end_lineno=16, end_col_offset=34, value='value', kind=None)],
                                        values=[Constant(lineno=16, col_offset=36, end_lineno=16, end_col_offset=37, value=3, kind=None)],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=18,
                            col_offset=8,
                            end_lineno=18,
                            end_col_offset=79,
                            targets=[Name(lineno=18, col_offset=8, end_lineno=18, end_col_offset=10, id='gb', ctx=Store())],
                            value=Call(
                                lineno=18,
                                col_offset=13,
                                end_lineno=18,
                                end_col_offset=79,
                                func=Attribute(
                                    lineno=18,
                                    col_offset=13,
                                    end_lineno=18,
                                    end_col_offset=34,
                                    value=Attribute(
                                        lineno=18,
                                        col_offset=13,
                                        end_lineno=18,
                                        end_col_offset=23,
                                        value=Name(lineno=18, col_offset=13, end_lineno=18, end_col_offset=17, id='self', ctx=Load()),
                                        attr='Model',
                                        ctx=Load(),
                                    ),
                                    attr='read_group',
                                    ctx=Load(),
                                ),
                                args=[
                                    List(lineno=18, col_offset=35, end_lineno=18, end_col_offset=37, elts=[], ctx=Load()),
                                    List(
                                        lineno=18,
                                        col_offset=39,
                                        end_lineno=18,
                                        end_col_offset=56,
                                        elts=[
                                            Constant(lineno=18, col_offset=40, end_lineno=18, end_col_offset=46, value='date', kind=None),
                                            Constant(lineno=18, col_offset=48, end_lineno=18, end_col_offset=55, value='value', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                    List(
                                        lineno=18,
                                        col_offset=58,
                                        end_lineno=18,
                                        end_col_offset=66,
                                        elts=[Constant(lineno=18, col_offset=59, end_lineno=18, end_col_offset=65, value='date', kind=None)],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[
                                    keyword(
                                        lineno=18,
                                        col_offset=68,
                                        end_lineno=18,
                                        end_col_offset=78,
                                        arg='lazy',
                                        value=Constant(lineno=18, col_offset=73, end_lineno=18, end_col_offset=78, value=False, kind=None),
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=20,
                            col_offset=8,
                            end_lineno=26,
                            end_col_offset=11,
                            value=Call(
                                lineno=20,
                                col_offset=8,
                                end_lineno=26,
                                end_col_offset=11,
                                func=Attribute(
                                    lineno=20,
                                    col_offset=8,
                                    end_lineno=20,
                                    end_col_offset=24,
                                    value=Name(lineno=20, col_offset=8, end_lineno=20, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=20, col_offset=25, end_lineno=20, end_col_offset=27, id='gb', ctx=Load()),
                                    List(
                                        lineno=20,
                                        col_offset=29,
                                        end_lineno=26,
                                        end_col_offset=10,
                                        elts=[
                                            Dict(
                                                lineno=20,
                                                col_offset=30,
                                                end_lineno=26,
                                                end_col_offset=9,
                                                keys=[
                                                    Constant(lineno=21, col_offset=12, end_lineno=21, end_col_offset=21, value='__count', kind=None),
                                                    Constant(lineno=22, col_offset=12, end_lineno=22, end_col_offset=22, value='__domain', kind=None),
                                                    Constant(lineno=23, col_offset=12, end_lineno=23, end_col_offset=21, value='__range', kind=None),
                                                    Constant(lineno=24, col_offset=12, end_lineno=24, end_col_offset=18, value='date', kind=None),
                                                    Constant(lineno=25, col_offset=12, end_lineno=25, end_col_offset=19, value='value', kind=None),
                                                ],
                                                values=[
                                                    Constant(lineno=21, col_offset=23, end_lineno=21, end_col_offset=24, value=3, kind=None),
                                                    List(
                                                        lineno=22,
                                                        col_offset=24,
                                                        end_lineno=22,
                                                        end_col_offset=46,
                                                        elts=[
                                                            Tuple(
                                                                lineno=22,
                                                                col_offset=25,
                                                                end_lineno=22,
                                                                end_col_offset=45,
                                                                elts=[
                                                                    Constant(lineno=22, col_offset=26, end_lineno=22, end_col_offset=32, value='date', kind=None),
                                                                    Constant(lineno=22, col_offset=34, end_lineno=22, end_col_offset=37, value='=', kind=None),
                                                                    Constant(lineno=22, col_offset=39, end_lineno=22, end_col_offset=44, value=False, kind=None),
                                                                ],
                                                                ctx=Load(),
                                                            ),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                    Dict(
                                                        lineno=23,
                                                        col_offset=23,
                                                        end_lineno=23,
                                                        end_col_offset=38,
                                                        keys=[Constant(lineno=23, col_offset=24, end_lineno=23, end_col_offset=30, value='date', kind=None)],
                                                        values=[Constant(lineno=23, col_offset=32, end_lineno=23, end_col_offset=37, value=False, kind=None)],
                                                    ),
                                                    Constant(lineno=24, col_offset=20, end_lineno=24, end_col_offset=25, value=False, kind=None),
                                                    Constant(lineno=25, col_offset=21, end_lineno=25, end_col_offset=22, value=6, kind=None),
                                                ],
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=28,
                    col_offset=4,
                    end_lineno=41,
                    end_col_offset=11,
                    name='test_empty_by_span',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=28, col_offset=27, end_lineno=28, end_col_offset=31, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=29,
                            col_offset=8,
                            end_lineno=29,
                            end_col_offset=39,
                            value=Call(
                                lineno=29,
                                col_offset=8,
                                end_lineno=29,
                                end_col_offset=39,
                                func=Attribute(
                                    lineno=29,
                                    col_offset=8,
                                    end_lineno=29,
                                    end_col_offset=25,
                                    value=Attribute(
                                        lineno=29,
                                        col_offset=8,
                                        end_lineno=29,
                                        end_col_offset=18,
                                        value=Name(lineno=29, col_offset=8, end_lineno=29, end_col_offset=12, id='self', ctx=Load()),
                                        attr='Model',
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=29,
                                        col_offset=26,
                                        end_lineno=29,
                                        end_col_offset=38,
                                        keys=[Constant(lineno=29, col_offset=27, end_lineno=29, end_col_offset=34, value='value', kind=None)],
                                        values=[Constant(lineno=29, col_offset=36, end_lineno=29, end_col_offset=37, value=1, kind=None)],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=30,
                            col_offset=8,
                            end_lineno=30,
                            end_col_offset=39,
                            value=Call(
                                lineno=30,
                                col_offset=8,
                                end_lineno=30,
                                end_col_offset=39,
                                func=Attribute(
                                    lineno=30,
                                    col_offset=8,
                                    end_lineno=30,
                                    end_col_offset=25,
                                    value=Attribute(
                                        lineno=30,
                                        col_offset=8,
                                        end_lineno=30,
                                        end_col_offset=18,
                                        value=Name(lineno=30, col_offset=8, end_lineno=30, end_col_offset=12, id='self', ctx=Load()),
                                        attr='Model',
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=30,
                                        col_offset=26,
                                        end_lineno=30,
                                        end_col_offset=38,
                                        keys=[Constant(lineno=30, col_offset=27, end_lineno=30, end_col_offset=34, value='value', kind=None)],
                                        values=[Constant(lineno=30, col_offset=36, end_lineno=30, end_col_offset=37, value=2, kind=None)],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=31,
                            col_offset=8,
                            end_lineno=31,
                            end_col_offset=39,
                            value=Call(
                                lineno=31,
                                col_offset=8,
                                end_lineno=31,
                                end_col_offset=39,
                                func=Attribute(
                                    lineno=31,
                                    col_offset=8,
                                    end_lineno=31,
                                    end_col_offset=25,
                                    value=Attribute(
                                        lineno=31,
                                        col_offset=8,
                                        end_lineno=31,
                                        end_col_offset=18,
                                        value=Name(lineno=31, col_offset=8, end_lineno=31, end_col_offset=12, id='self', ctx=Load()),
                                        attr='Model',
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=31,
                                        col_offset=26,
                                        end_lineno=31,
                                        end_col_offset=38,
                                        keys=[Constant(lineno=31, col_offset=27, end_lineno=31, end_col_offset=34, value='value', kind=None)],
                                        values=[Constant(lineno=31, col_offset=36, end_lineno=31, end_col_offset=37, value=3, kind=None)],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=33,
                            col_offset=8,
                            end_lineno=33,
                            end_col_offset=87,
                            targets=[Name(lineno=33, col_offset=8, end_lineno=33, end_col_offset=10, id='gb', ctx=Store())],
                            value=Call(
                                lineno=33,
                                col_offset=13,
                                end_lineno=33,
                                end_col_offset=87,
                                func=Attribute(
                                    lineno=33,
                                    col_offset=13,
                                    end_lineno=33,
                                    end_col_offset=34,
                                    value=Attribute(
                                        lineno=33,
                                        col_offset=13,
                                        end_lineno=33,
                                        end_col_offset=23,
                                        value=Name(lineno=33, col_offset=13, end_lineno=33, end_col_offset=17, id='self', ctx=Load()),
                                        attr='Model',
                                        ctx=Load(),
                                    ),
                                    attr='read_group',
                                    ctx=Load(),
                                ),
                                args=[
                                    List(lineno=33, col_offset=35, end_lineno=33, end_col_offset=37, elts=[], ctx=Load()),
                                    List(
                                        lineno=33,
                                        col_offset=39,
                                        end_lineno=33,
                                        end_col_offset=56,
                                        elts=[
                                            Constant(lineno=33, col_offset=40, end_lineno=33, end_col_offset=46, value='date', kind=None),
                                            Constant(lineno=33, col_offset=48, end_lineno=33, end_col_offset=55, value='value', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                    List(
                                        lineno=33,
                                        col_offset=58,
                                        end_lineno=33,
                                        end_col_offset=74,
                                        elts=[Constant(lineno=33, col_offset=59, end_lineno=33, end_col_offset=73, value='date:quarter', kind=None)],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[
                                    keyword(
                                        lineno=33,
                                        col_offset=76,
                                        end_lineno=33,
                                        end_col_offset=86,
                                        arg='lazy',
                                        value=Constant(lineno=33, col_offset=81, end_lineno=33, end_col_offset=86, value=False, kind=None),
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=35,
                            col_offset=8,
                            end_lineno=41,
                            end_col_offset=11,
                            value=Call(
                                lineno=35,
                                col_offset=8,
                                end_lineno=41,
                                end_col_offset=11,
                                func=Attribute(
                                    lineno=35,
                                    col_offset=8,
                                    end_lineno=35,
                                    end_col_offset=24,
                                    value=Name(lineno=35, col_offset=8, end_lineno=35, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=35, col_offset=25, end_lineno=35, end_col_offset=27, id='gb', ctx=Load()),
                                    List(
                                        lineno=35,
                                        col_offset=29,
                                        end_lineno=41,
                                        end_col_offset=10,
                                        elts=[
                                            Dict(
                                                lineno=35,
                                                col_offset=30,
                                                end_lineno=41,
                                                end_col_offset=9,
                                                keys=[
                                                    Constant(lineno=36, col_offset=12, end_lineno=36, end_col_offset=21, value='__count', kind=None),
                                                    Constant(lineno=37, col_offset=12, end_lineno=37, end_col_offset=22, value='__domain', kind=None),
                                                    Constant(lineno=38, col_offset=12, end_lineno=38, end_col_offset=21, value='__range', kind=None),
                                                    Constant(lineno=39, col_offset=12, end_lineno=39, end_col_offset=26, value='date:quarter', kind=None),
                                                    Constant(lineno=40, col_offset=12, end_lineno=40, end_col_offset=19, value='value', kind=None),
                                                ],
                                                values=[
                                                    Constant(lineno=36, col_offset=23, end_lineno=36, end_col_offset=24, value=3, kind=None),
                                                    List(
                                                        lineno=37,
                                                        col_offset=24,
                                                        end_lineno=37,
                                                        end_col_offset=46,
                                                        elts=[
                                                            Tuple(
                                                                lineno=37,
                                                                col_offset=25,
                                                                end_lineno=37,
                                                                end_col_offset=45,
                                                                elts=[
                                                                    Constant(lineno=37, col_offset=26, end_lineno=37, end_col_offset=32, value='date', kind=None),
                                                                    Constant(lineno=37, col_offset=34, end_lineno=37, end_col_offset=37, value='=', kind=None),
                                                                    Constant(lineno=37, col_offset=39, end_lineno=37, end_col_offset=44, value=False, kind=None),
                                                                ],
                                                                ctx=Load(),
                                                            ),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                    Dict(
                                                        lineno=38,
                                                        col_offset=23,
                                                        end_lineno=38,
                                                        end_col_offset=38,
                                                        keys=[Constant(lineno=38, col_offset=24, end_lineno=38, end_col_offset=30, value='date', kind=None)],
                                                        values=[Constant(lineno=38, col_offset=32, end_lineno=38, end_col_offset=37, value=False, kind=None)],
                                                    ),
                                                    Constant(lineno=39, col_offset=28, end_lineno=39, end_col_offset=33, value=False, kind=None),
                                                    Constant(lineno=40, col_offset=21, end_lineno=40, end_col_offset=22, value=6, kind=None),
                                                ],
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=43,
                    col_offset=4,
                    end_lineno=63,
                    end_col_offset=11,
                    name='test_mixed',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=43, col_offset=19, end_lineno=43, end_col_offset=23, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=44,
                            col_offset=8,
                            end_lineno=44,
                            end_col_offset=54,
                            value=Call(
                                lineno=44,
                                col_offset=8,
                                end_lineno=44,
                                end_col_offset=54,
                                func=Attribute(
                                    lineno=44,
                                    col_offset=8,
                                    end_lineno=44,
                                    end_col_offset=25,
                                    value=Attribute(
                                        lineno=44,
                                        col_offset=8,
                                        end_lineno=44,
                                        end_col_offset=18,
                                        value=Name(lineno=44, col_offset=8, end_lineno=44, end_col_offset=12, id='self', ctx=Load()),
                                        attr='Model',
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=44,
                                        col_offset=26,
                                        end_lineno=44,
                                        end_col_offset=53,
                                        keys=[
                                            Constant(lineno=44, col_offset=27, end_lineno=44, end_col_offset=33, value='date', kind=None),
                                            Constant(lineno=44, col_offset=42, end_lineno=44, end_col_offset=49, value='value', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=44, col_offset=35, end_lineno=44, end_col_offset=40, value=False, kind=None),
                                            Constant(lineno=44, col_offset=51, end_lineno=44, end_col_offset=52, value=1, kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=45,
                            col_offset=8,
                            end_lineno=45,
                            end_col_offset=54,
                            value=Call(
                                lineno=45,
                                col_offset=8,
                                end_lineno=45,
                                end_col_offset=54,
                                func=Attribute(
                                    lineno=45,
                                    col_offset=8,
                                    end_lineno=45,
                                    end_col_offset=25,
                                    value=Attribute(
                                        lineno=45,
                                        col_offset=8,
                                        end_lineno=45,
                                        end_col_offset=18,
                                        value=Name(lineno=45, col_offset=8, end_lineno=45, end_col_offset=12, id='self', ctx=Load()),
                                        attr='Model',
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=45,
                                        col_offset=26,
                                        end_lineno=45,
                                        end_col_offset=53,
                                        keys=[
                                            Constant(lineno=45, col_offset=27, end_lineno=45, end_col_offset=33, value='date', kind=None),
                                            Constant(lineno=45, col_offset=42, end_lineno=45, end_col_offset=49, value='value', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=45, col_offset=35, end_lineno=45, end_col_offset=40, value=False, kind=None),
                                            Constant(lineno=45, col_offset=51, end_lineno=45, end_col_offset=52, value=2, kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=46,
                            col_offset=8,
                            end_lineno=46,
                            end_col_offset=61,
                            value=Call(
                                lineno=46,
                                col_offset=8,
                                end_lineno=46,
                                end_col_offset=61,
                                func=Attribute(
                                    lineno=46,
                                    col_offset=8,
                                    end_lineno=46,
                                    end_col_offset=25,
                                    value=Attribute(
                                        lineno=46,
                                        col_offset=8,
                                        end_lineno=46,
                                        end_col_offset=18,
                                        value=Name(lineno=46, col_offset=8, end_lineno=46, end_col_offset=12, id='self', ctx=Load()),
                                        attr='Model',
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=46,
                                        col_offset=26,
                                        end_lineno=46,
                                        end_col_offset=60,
                                        keys=[
                                            Constant(lineno=46, col_offset=27, end_lineno=46, end_col_offset=33, value='date', kind=None),
                                            Constant(lineno=46, col_offset=49, end_lineno=46, end_col_offset=56, value='value', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=46, col_offset=35, end_lineno=46, end_col_offset=47, value='1916-12-18', kind=None),
                                            Constant(lineno=46, col_offset=58, end_lineno=46, end_col_offset=59, value=3, kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=47,
                            col_offset=8,
                            end_lineno=47,
                            end_col_offset=61,
                            value=Call(
                                lineno=47,
                                col_offset=8,
                                end_lineno=47,
                                end_col_offset=61,
                                func=Attribute(
                                    lineno=47,
                                    col_offset=8,
                                    end_lineno=47,
                                    end_col_offset=25,
                                    value=Attribute(
                                        lineno=47,
                                        col_offset=8,
                                        end_lineno=47,
                                        end_col_offset=18,
                                        value=Name(lineno=47, col_offset=8, end_lineno=47, end_col_offset=12, id='self', ctx=Load()),
                                        attr='Model',
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=47,
                                        col_offset=26,
                                        end_lineno=47,
                                        end_col_offset=60,
                                        keys=[
                                            Constant(lineno=47, col_offset=27, end_lineno=47, end_col_offset=33, value='date', kind=None),
                                            Constant(lineno=47, col_offset=49, end_lineno=47, end_col_offset=56, value='value', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=47, col_offset=35, end_lineno=47, end_col_offset=47, value='1916-12-18', kind=None),
                                            Constant(lineno=47, col_offset=58, end_lineno=47, end_col_offset=59, value=4, kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=49,
                            col_offset=8,
                            end_lineno=49,
                            end_col_offset=79,
                            targets=[Name(lineno=49, col_offset=8, end_lineno=49, end_col_offset=10, id='gb', ctx=Store())],
                            value=Call(
                                lineno=49,
                                col_offset=13,
                                end_lineno=49,
                                end_col_offset=79,
                                func=Attribute(
                                    lineno=49,
                                    col_offset=13,
                                    end_lineno=49,
                                    end_col_offset=34,
                                    value=Attribute(
                                        lineno=49,
                                        col_offset=13,
                                        end_lineno=49,
                                        end_col_offset=23,
                                        value=Name(lineno=49, col_offset=13, end_lineno=49, end_col_offset=17, id='self', ctx=Load()),
                                        attr='Model',
                                        ctx=Load(),
                                    ),
                                    attr='read_group',
                                    ctx=Load(),
                                ),
                                args=[
                                    List(lineno=49, col_offset=35, end_lineno=49, end_col_offset=37, elts=[], ctx=Load()),
                                    List(
                                        lineno=49,
                                        col_offset=39,
                                        end_lineno=49,
                                        end_col_offset=56,
                                        elts=[
                                            Constant(lineno=49, col_offset=40, end_lineno=49, end_col_offset=46, value='date', kind=None),
                                            Constant(lineno=49, col_offset=48, end_lineno=49, end_col_offset=55, value='value', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                    List(
                                        lineno=49,
                                        col_offset=58,
                                        end_lineno=49,
                                        end_col_offset=66,
                                        elts=[Constant(lineno=49, col_offset=59, end_lineno=49, end_col_offset=65, value='date', kind=None)],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[
                                    keyword(
                                        lineno=49,
                                        col_offset=68,
                                        end_lineno=49,
                                        end_col_offset=78,
                                        arg='lazy',
                                        value=Constant(lineno=49, col_offset=73, end_lineno=49, end_col_offset=78, value=False, kind=None),
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=51,
                            col_offset=8,
                            end_lineno=63,
                            end_col_offset=11,
                            value=Call(
                                lineno=51,
                                col_offset=8,
                                end_lineno=63,
                                end_col_offset=11,
                                func=Attribute(
                                    lineno=51,
                                    col_offset=8,
                                    end_lineno=51,
                                    end_col_offset=32,
                                    value=Name(lineno=51, col_offset=8, end_lineno=51, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertSequenceEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Call(
                                        lineno=51,
                                        col_offset=33,
                                        end_lineno=51,
                                        end_col_offset=74,
                                        func=Name(lineno=51, col_offset=33, end_lineno=51, end_col_offset=39, id='sorted', ctx=Load()),
                                        args=[Name(lineno=51, col_offset=40, end_lineno=51, end_col_offset=42, id='gb', ctx=Load())],
                                        keywords=[
                                            keyword(
                                                lineno=51,
                                                col_offset=44,
                                                end_lineno=51,
                                                end_col_offset=73,
                                                arg='key',
                                                value=Lambda(
                                                    lineno=51,
                                                    col_offset=48,
                                                    end_lineno=51,
                                                    end_col_offset=73,
                                                    args=arguments(
                                                        posonlyargs=[],
                                                        args=[arg(lineno=51, col_offset=55, end_lineno=51, end_col_offset=56, arg='r', annotation=None, type_comment=None)],
                                                        vararg=None,
                                                        kwonlyargs=[],
                                                        kw_defaults=[],
                                                        kwarg=None,
                                                        defaults=[],
                                                    ),
                                                    body=BoolOp(
                                                        lineno=51,
                                                        col_offset=58,
                                                        end_lineno=51,
                                                        end_col_offset=73,
                                                        op=Or(),
                                                        values=[
                                                            Subscript(
                                                                lineno=51,
                                                                col_offset=58,
                                                                end_lineno=51,
                                                                end_col_offset=67,
                                                                value=Name(lineno=51, col_offset=58, end_lineno=51, end_col_offset=59, id='r', ctx=Load()),
                                                                slice=Constant(lineno=51, col_offset=60, end_lineno=51, end_col_offset=66, value='date', kind=None),
                                                                ctx=Load(),
                                                            ),
                                                            Constant(lineno=51, col_offset=71, end_lineno=51, end_col_offset=73, value='', kind=None),
                                                        ],
                                                    ),
                                                ),
                                            ),
                                        ],
                                    ),
                                    List(
                                        lineno=51,
                                        col_offset=76,
                                        end_lineno=63,
                                        end_col_offset=10,
                                        elts=[
                                            Dict(
                                                lineno=51,
                                                col_offset=77,
                                                end_lineno=57,
                                                end_col_offset=9,
                                                keys=[
                                                    Constant(lineno=52, col_offset=12, end_lineno=52, end_col_offset=21, value='__count', kind=None),
                                                    Constant(lineno=53, col_offset=12, end_lineno=53, end_col_offset=22, value='__domain', kind=None),
                                                    Constant(lineno=54, col_offset=12, end_lineno=54, end_col_offset=21, value='__range', kind=None),
                                                    Constant(lineno=55, col_offset=12, end_lineno=55, end_col_offset=18, value='date', kind=None),
                                                    Constant(lineno=56, col_offset=12, end_lineno=56, end_col_offset=19, value='value', kind=None),
                                                ],
                                                values=[
                                                    Constant(lineno=52, col_offset=23, end_lineno=52, end_col_offset=24, value=2, kind=None),
                                                    List(
                                                        lineno=53,
                                                        col_offset=24,
                                                        end_lineno=53,
                                                        end_col_offset=46,
                                                        elts=[
                                                            Tuple(
                                                                lineno=53,
                                                                col_offset=25,
                                                                end_lineno=53,
                                                                end_col_offset=45,
                                                                elts=[
                                                                    Constant(lineno=53, col_offset=26, end_lineno=53, end_col_offset=32, value='date', kind=None),
                                                                    Constant(lineno=53, col_offset=34, end_lineno=53, end_col_offset=37, value='=', kind=None),
                                                                    Constant(lineno=53, col_offset=39, end_lineno=53, end_col_offset=44, value=False, kind=None),
                                                                ],
                                                                ctx=Load(),
                                                            ),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                    Dict(
                                                        lineno=54,
                                                        col_offset=23,
                                                        end_lineno=54,
                                                        end_col_offset=38,
                                                        keys=[Constant(lineno=54, col_offset=24, end_lineno=54, end_col_offset=30, value='date', kind=None)],
                                                        values=[Constant(lineno=54, col_offset=32, end_lineno=54, end_col_offset=37, value=False, kind=None)],
                                                    ),
                                                    Constant(lineno=55, col_offset=20, end_lineno=55, end_col_offset=25, value=False, kind=None),
                                                    Constant(lineno=56, col_offset=21, end_lineno=56, end_col_offset=22, value=3, kind=None),
                                                ],
                                            ),
                                            Dict(
                                                lineno=57,
                                                col_offset=11,
                                                end_lineno=63,
                                                end_col_offset=9,
                                                keys=[
                                                    Constant(lineno=58, col_offset=12, end_lineno=58, end_col_offset=21, value='__count', kind=None),
                                                    Constant(lineno=59, col_offset=12, end_lineno=59, end_col_offset=22, value='__domain', kind=None),
                                                    Constant(lineno=60, col_offset=12, end_lineno=60, end_col_offset=21, value='__range', kind=None),
                                                    Constant(lineno=61, col_offset=12, end_lineno=61, end_col_offset=18, value='date', kind=None),
                                                    Constant(lineno=62, col_offset=12, end_lineno=62, end_col_offset=19, value='value', kind=None),
                                                ],
                                                values=[
                                                    Constant(lineno=58, col_offset=23, end_lineno=58, end_col_offset=24, value=2, kind=None),
                                                    List(
                                                        lineno=59,
                                                        col_offset=24,
                                                        end_lineno=59,
                                                        end_col_offset=88,
                                                        elts=[
                                                            Constant(lineno=59, col_offset=25, end_lineno=59, end_col_offset=28, value='&', kind=None),
                                                            Tuple(
                                                                lineno=59,
                                                                col_offset=30,
                                                                end_lineno=59,
                                                                end_col_offset=58,
                                                                elts=[
                                                                    Constant(lineno=59, col_offset=31, end_lineno=59, end_col_offset=37, value='date', kind=None),
                                                                    Constant(lineno=59, col_offset=39, end_lineno=59, end_col_offset=43, value='>=', kind=None),
                                                                    Constant(lineno=59, col_offset=45, end_lineno=59, end_col_offset=57, value='1916-12-01', kind=None),
                                                                ],
                                                                ctx=Load(),
                                                            ),
                                                            Tuple(
                                                                lineno=59,
                                                                col_offset=60,
                                                                end_lineno=59,
                                                                end_col_offset=87,
                                                                elts=[
                                                                    Constant(lineno=59, col_offset=61, end_lineno=59, end_col_offset=67, value='date', kind=None),
                                                                    Constant(lineno=59, col_offset=69, end_lineno=59, end_col_offset=72, value='<', kind=None),
                                                                    Constant(lineno=59, col_offset=74, end_lineno=59, end_col_offset=86, value='1917-01-01', kind=None),
                                                                ],
                                                                ctx=Load(),
                                                            ),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                    Dict(
                                                        lineno=60,
                                                        col_offset=23,
                                                        end_lineno=60,
                                                        end_col_offset=75,
                                                        keys=[Constant(lineno=60, col_offset=24, end_lineno=60, end_col_offset=30, value='date', kind=None)],
                                                        values=[
                                                            Dict(
                                                                lineno=60,
                                                                col_offset=32,
                                                                end_lineno=60,
                                                                end_col_offset=74,
                                                                keys=[
                                                                    Constant(lineno=60, col_offset=33, end_lineno=60, end_col_offset=39, value='from', kind=None),
                                                                    Constant(lineno=60, col_offset=55, end_lineno=60, end_col_offset=59, value='to', kind=None),
                                                                ],
                                                                values=[
                                                                    Constant(lineno=60, col_offset=41, end_lineno=60, end_col_offset=53, value='1916-12-01', kind=None),
                                                                    Constant(lineno=60, col_offset=61, end_lineno=60, end_col_offset=73, value='1917-01-01', kind=None),
                                                                ],
                                                            ),
                                                        ],
                                                    ),
                                                    Constant(lineno=61, col_offset=20, end_lineno=61, end_col_offset=35, value='December 1916', kind=None),
                                                    Constant(lineno=62, col_offset=21, end_lineno=62, end_col_offset=22, value=7, kind=None),
                                                ],
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
