Module(
    body=[
        ImportFrom(
            lineno=3,
            col_offset=0,
            end_lineno=3,
            end_col_offset=126,
            module='odoo.addons.stock_account.tests.test_anglo_saxon_valuation_reconciliation_common',
            names=[alias(name='ValuationReconciliationTestCommon', asname=None)],
            level=0,
        ),
        ClassDef(
            lineno=6,
            col_offset=0,
            end_lineno=50,
            end_col_offset=96,
            name='TestStockLandedCostsCommon',
            bases=[Name(lineno=6, col_offset=33, end_lineno=6, end_col_offset=66, id='ValuationReconciliationTestCommon', ctx=Load())],
            keywords=[],
            body=[
                FunctionDef(
                    lineno=9,
                    col_offset=4,
                    end_lineno=50,
                    end_col_offset=96,
                    name='setUpClass',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=9, col_offset=19, end_lineno=9, end_col_offset=22, arg='cls', annotation=None, type_comment=None),
                            arg(lineno=9, col_offset=24, end_lineno=9, end_col_offset=42, arg='chart_template_ref', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[Constant(lineno=9, col_offset=43, end_lineno=9, end_col_offset=47, value=None, kind=None)],
                    ),
                    body=[
                        Expr(
                            lineno=10,
                            col_offset=8,
                            end_lineno=10,
                            end_col_offset=65,
                            value=Call(
                                lineno=10,
                                col_offset=8,
                                end_lineno=10,
                                end_col_offset=65,
                                func=Attribute(
                                    lineno=10,
                                    col_offset=8,
                                    end_lineno=10,
                                    end_col_offset=26,
                                    value=Call(
                                        lineno=10,
                                        col_offset=8,
                                        end_lineno=10,
                                        end_col_offset=15,
                                        func=Name(lineno=10, col_offset=8, end_lineno=10, end_col_offset=13, id='super', ctx=Load()),
                                        args=[],
                                        keywords=[],
                                    ),
                                    attr='setUpClass',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[
                                    keyword(
                                        lineno=10,
                                        col_offset=27,
                                        end_lineno=10,
                                        end_col_offset=64,
                                        arg='chart_template_ref',
                                        value=Name(lineno=10, col_offset=46, end_lineno=10, end_col_offset=64, id='chart_template_ref', ctx=Load()),
                                    ),
                                ],
                            ),
                        ),
                        Assign(
                            lineno=13,
                            col_offset=8,
                            end_lineno=13,
                            end_col_offset=48,
                            targets=[
                                Attribute(
                                    lineno=13,
                                    col_offset=8,
                                    end_lineno=13,
                                    end_col_offset=19,
                                    value=Name(lineno=13, col_offset=8, end_lineno=13, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='Product',
                                    ctx=Store(),
                                ),
                            ],
                            value=Subscript(
                                lineno=13,
                                col_offset=22,
                                end_lineno=13,
                                end_col_offset=48,
                                value=Attribute(
                                    lineno=13,
                                    col_offset=22,
                                    end_lineno=13,
                                    end_col_offset=29,
                                    value=Name(lineno=13, col_offset=22, end_lineno=13, end_col_offset=25, id='cls', ctx=Load()),
                                    attr='env',
                                    ctx=Load(),
                                ),
                                slice=Constant(lineno=13, col_offset=30, end_lineno=13, end_col_offset=47, value='product.product', kind=None),
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=14,
                            col_offset=8,
                            end_lineno=14,
                            end_col_offset=46,
                            targets=[
                                Attribute(
                                    lineno=14,
                                    col_offset=8,
                                    end_lineno=14,
                                    end_col_offset=19,
                                    value=Name(lineno=14, col_offset=8, end_lineno=14, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='Picking',
                                    ctx=Store(),
                                ),
                            ],
                            value=Subscript(
                                lineno=14,
                                col_offset=22,
                                end_lineno=14,
                                end_col_offset=46,
                                value=Attribute(
                                    lineno=14,
                                    col_offset=22,
                                    end_lineno=14,
                                    end_col_offset=29,
                                    value=Name(lineno=14, col_offset=22, end_lineno=14, end_col_offset=25, id='cls', ctx=Load()),
                                    attr='env',
                                    ctx=Load(),
                                ),
                                slice=Constant(lineno=14, col_offset=30, end_lineno=14, end_col_offset=45, value='stock.picking', kind=None),
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=15,
                            col_offset=8,
                            end_lineno=15,
                            end_col_offset=40,
                            targets=[
                                Attribute(
                                    lineno=15,
                                    col_offset=8,
                                    end_lineno=15,
                                    end_col_offset=16,
                                    value=Name(lineno=15, col_offset=8, end_lineno=15, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='Move',
                                    ctx=Store(),
                                ),
                            ],
                            value=Subscript(
                                lineno=15,
                                col_offset=19,
                                end_lineno=15,
                                end_col_offset=40,
                                value=Attribute(
                                    lineno=15,
                                    col_offset=19,
                                    end_lineno=15,
                                    end_col_offset=26,
                                    value=Name(lineno=15, col_offset=19, end_lineno=15, end_col_offset=22, id='cls', ctx=Load()),
                                    attr='env',
                                    ctx=Load(),
                                ),
                                slice=Constant(lineno=15, col_offset=27, end_lineno=15, end_col_offset=39, value='stock.move', kind=None),
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=16,
                            col_offset=8,
                            end_lineno=16,
                            end_col_offset=53,
                            targets=[
                                Attribute(
                                    lineno=16,
                                    col_offset=8,
                                    end_lineno=16,
                                    end_col_offset=22,
                                    value=Name(lineno=16, col_offset=8, end_lineno=16, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='LandedCost',
                                    ctx=Store(),
                                ),
                            ],
                            value=Subscript(
                                lineno=16,
                                col_offset=25,
                                end_lineno=16,
                                end_col_offset=53,
                                value=Attribute(
                                    lineno=16,
                                    col_offset=25,
                                    end_lineno=16,
                                    end_col_offset=32,
                                    value=Name(lineno=16, col_offset=25, end_lineno=16, end_col_offset=28, id='cls', ctx=Load()),
                                    attr='env',
                                    ctx=Load(),
                                ),
                                slice=Constant(lineno=16, col_offset=33, end_lineno=16, end_col_offset=52, value='stock.landed.cost', kind=None),
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=17,
                            col_offset=8,
                            end_lineno=17,
                            end_col_offset=57,
                            targets=[
                                Attribute(
                                    lineno=17,
                                    col_offset=8,
                                    end_lineno=17,
                                    end_col_offset=20,
                                    value=Name(lineno=17, col_offset=8, end_lineno=17, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='CostLine',
                                    ctx=Store(),
                                ),
                            ],
                            value=Subscript(
                                lineno=17,
                                col_offset=23,
                                end_lineno=17,
                                end_col_offset=57,
                                value=Attribute(
                                    lineno=17,
                                    col_offset=23,
                                    end_lineno=17,
                                    end_col_offset=30,
                                    value=Name(lineno=17, col_offset=23, end_lineno=17, end_col_offset=26, id='cls', ctx=Load()),
                                    attr='env',
                                    ctx=Load(),
                                ),
                                slice=Constant(lineno=17, col_offset=31, end_lineno=17, end_col_offset=56, value='stock.landed.cost.lines', kind=None),
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=19,
                            col_offset=8,
                            end_lineno=19,
                            end_col_offset=61,
                            targets=[
                                Attribute(
                                    lineno=19,
                                    col_offset=8,
                                    end_lineno=19,
                                    end_col_offset=21,
                                    value=Name(lineno=19, col_offset=8, end_lineno=19, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='warehouse',
                                    ctx=Store(),
                                ),
                            ],
                            value=Subscript(
                                lineno=19,
                                col_offset=24,
                                end_lineno=19,
                                end_col_offset=61,
                                value=Attribute(
                                    lineno=19,
                                    col_offset=24,
                                    end_lineno=19,
                                    end_col_offset=40,
                                    value=Name(lineno=19, col_offset=24, end_lineno=19, end_col_offset=27, id='cls', ctx=Load()),
                                    attr='company_data',
                                    ctx=Load(),
                                ),
                                slice=Constant(lineno=19, col_offset=41, end_lineno=19, end_col_offset=60, value='default_warehouse', kind=None),
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=20,
                            col_offset=8,
                            end_lineno=20,
                            end_col_offset=88,
                            targets=[
                                Attribute(
                                    lineno=20,
                                    col_offset=8,
                                    end_lineno=20,
                                    end_col_offset=23,
                                    value=Name(lineno=20, col_offset=8, end_lineno=20, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='supplier_id',
                                    ctx=Store(),
                                ),
                            ],
                            value=Attribute(
                                lineno=20,
                                col_offset=26,
                                end_lineno=20,
                                end_col_offset=88,
                                value=Call(
                                    lineno=20,
                                    col_offset=26,
                                    end_lineno=20,
                                    end_col_offset=85,
                                    func=Attribute(
                                        lineno=20,
                                        col_offset=26,
                                        end_lineno=20,
                                        end_col_offset=55,
                                        value=Subscript(
                                            lineno=20,
                                            col_offset=26,
                                            end_lineno=20,
                                            end_col_offset=48,
                                            value=Attribute(
                                                lineno=20,
                                                col_offset=26,
                                                end_lineno=20,
                                                end_col_offset=33,
                                                value=Name(lineno=20, col_offset=26, end_lineno=20, end_col_offset=29, id='cls', ctx=Load()),
                                                attr='env',
                                                ctx=Load(),
                                            ),
                                            slice=Constant(lineno=20, col_offset=34, end_lineno=20, end_col_offset=47, value='res.partner', kind=None),
                                            ctx=Load(),
                                        ),
                                        attr='create',
                                        ctx=Load(),
                                    ),
                                    args=[
                                        Dict(
                                            lineno=20,
                                            col_offset=56,
                                            end_lineno=20,
                                            end_col_offset=84,
                                            keys=[Constant(lineno=20, col_offset=57, end_lineno=20, end_col_offset=63, value='name', kind=None)],
                                            values=[Constant(lineno=20, col_offset=65, end_lineno=20, end_col_offset=83, value='My Test Supplier', kind=None)],
                                        ),
                                    ],
                                    keywords=[],
                                ),
                                attr='id',
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=21,
                            col_offset=8,
                            end_lineno=21,
                            end_col_offset=88,
                            targets=[
                                Attribute(
                                    lineno=21,
                                    col_offset=8,
                                    end_lineno=21,
                                    end_col_offset=23,
                                    value=Name(lineno=21, col_offset=8, end_lineno=21, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='customer_id',
                                    ctx=Store(),
                                ),
                            ],
                            value=Attribute(
                                lineno=21,
                                col_offset=26,
                                end_lineno=21,
                                end_col_offset=88,
                                value=Call(
                                    lineno=21,
                                    col_offset=26,
                                    end_lineno=21,
                                    end_col_offset=85,
                                    func=Attribute(
                                        lineno=21,
                                        col_offset=26,
                                        end_lineno=21,
                                        end_col_offset=55,
                                        value=Subscript(
                                            lineno=21,
                                            col_offset=26,
                                            end_lineno=21,
                                            end_col_offset=48,
                                            value=Attribute(
                                                lineno=21,
                                                col_offset=26,
                                                end_lineno=21,
                                                end_col_offset=33,
                                                value=Name(lineno=21, col_offset=26, end_lineno=21, end_col_offset=29, id='cls', ctx=Load()),
                                                attr='env',
                                                ctx=Load(),
                                            ),
                                            slice=Constant(lineno=21, col_offset=34, end_lineno=21, end_col_offset=47, value='res.partner', kind=None),
                                            ctx=Load(),
                                        ),
                                        attr='create',
                                        ctx=Load(),
                                    ),
                                    args=[
                                        Dict(
                                            lineno=21,
                                            col_offset=56,
                                            end_lineno=21,
                                            end_col_offset=84,
                                            keys=[Constant(lineno=21, col_offset=57, end_lineno=21, end_col_offset=63, value='name', kind=None)],
                                            values=[Constant(lineno=21, col_offset=65, end_lineno=21, end_col_offset=83, value='My Test Customer', kind=None)],
                                        ),
                                    ],
                                    keywords=[],
                                ),
                                attr='id',
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=22,
                            col_offset=8,
                            end_lineno=22,
                            end_col_offset=83,
                            targets=[
                                Attribute(
                                    lineno=22,
                                    col_offset=8,
                                    end_lineno=22,
                                    end_col_offset=32,
                                    value=Name(lineno=22, col_offset=8, end_lineno=22, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='supplier_location_id',
                                    ctx=Store(),
                                ),
                            ],
                            value=Attribute(
                                lineno=22,
                                col_offset=35,
                                end_lineno=22,
                                end_col_offset=83,
                                value=Call(
                                    lineno=22,
                                    col_offset=35,
                                    end_lineno=22,
                                    end_col_offset=80,
                                    func=Attribute(
                                        lineno=22,
                                        col_offset=35,
                                        end_lineno=22,
                                        end_col_offset=46,
                                        value=Attribute(
                                            lineno=22,
                                            col_offset=35,
                                            end_lineno=22,
                                            end_col_offset=42,
                                            value=Name(lineno=22, col_offset=35, end_lineno=22, end_col_offset=38, id='cls', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        attr='ref',
                                        ctx=Load(),
                                    ),
                                    args=[Constant(lineno=22, col_offset=47, end_lineno=22, end_col_offset=79, value='stock.stock_location_suppliers', kind=None)],
                                    keywords=[],
                                ),
                                attr='id',
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=23,
                            col_offset=8,
                            end_lineno=23,
                            end_col_offset=83,
                            targets=[
                                Attribute(
                                    lineno=23,
                                    col_offset=8,
                                    end_lineno=23,
                                    end_col_offset=32,
                                    value=Name(lineno=23, col_offset=8, end_lineno=23, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='customer_location_id',
                                    ctx=Store(),
                                ),
                            ],
                            value=Attribute(
                                lineno=23,
                                col_offset=35,
                                end_lineno=23,
                                end_col_offset=83,
                                value=Call(
                                    lineno=23,
                                    col_offset=35,
                                    end_lineno=23,
                                    end_col_offset=80,
                                    func=Attribute(
                                        lineno=23,
                                        col_offset=35,
                                        end_lineno=23,
                                        end_col_offset=46,
                                        value=Attribute(
                                            lineno=23,
                                            col_offset=35,
                                            end_lineno=23,
                                            end_col_offset=42,
                                            value=Name(lineno=23, col_offset=35, end_lineno=23, end_col_offset=38, id='cls', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        attr='ref',
                                        ctx=Load(),
                                    ),
                                    args=[Constant(lineno=23, col_offset=47, end_lineno=23, end_col_offset=79, value='stock.stock_location_customers', kind=None)],
                                    keywords=[],
                                ),
                                attr='id',
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=24,
                            col_offset=8,
                            end_lineno=24,
                            end_col_offset=55,
                            targets=[
                                Attribute(
                                    lineno=24,
                                    col_offset=8,
                                    end_lineno=24,
                                    end_col_offset=21,
                                    value=Name(lineno=24, col_offset=8, end_lineno=24, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='categ_all',
                                    ctx=Store(),
                                ),
                            ],
                            value=Attribute(
                                lineno=24,
                                col_offset=24,
                                end_lineno=24,
                                end_col_offset=55,
                                value=Name(lineno=24, col_offset=24, end_lineno=24, end_col_offset=27, id='cls', ctx=Load()),
                                attr='stock_account_product_categ',
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=25,
                            col_offset=8,
                            end_lineno=25,
                            end_col_offset=75,
                            targets=[
                                Attribute(
                                    lineno=25,
                                    col_offset=8,
                                    end_lineno=25,
                                    end_col_offset=28,
                                    value=Name(lineno=25, col_offset=8, end_lineno=25, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='expenses_journal',
                                    ctx=Store(),
                                ),
                            ],
                            value=Subscript(
                                lineno=25,
                                col_offset=31,
                                end_lineno=25,
                                end_col_offset=75,
                                value=Attribute(
                                    lineno=25,
                                    col_offset=31,
                                    end_lineno=25,
                                    end_col_offset=47,
                                    value=Name(lineno=25, col_offset=31, end_lineno=25, end_col_offset=34, id='cls', ctx=Load()),
                                    attr='company_data',
                                    ctx=Load(),
                                ),
                                slice=Constant(lineno=25, col_offset=48, end_lineno=25, end_col_offset=74, value='default_journal_purchase', kind=None),
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=26,
                            col_offset=8,
                            end_lineno=30,
                            end_col_offset=10,
                            targets=[
                                Attribute(
                                    lineno=26,
                                    col_offset=8,
                                    end_lineno=26,
                                    end_col_offset=25,
                                    value=Name(lineno=26, col_offset=8, end_lineno=26, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='stock_journal',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=26,
                                col_offset=28,
                                end_lineno=30,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=26,
                                    col_offset=28,
                                    end_lineno=26,
                                    end_col_offset=61,
                                    value=Subscript(
                                        lineno=26,
                                        col_offset=28,
                                        end_lineno=26,
                                        end_col_offset=54,
                                        value=Attribute(
                                            lineno=26,
                                            col_offset=28,
                                            end_lineno=26,
                                            end_col_offset=35,
                                            value=Name(lineno=26, col_offset=28, end_lineno=26, end_col_offset=31, id='cls', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=26, col_offset=36, end_lineno=26, end_col_offset=53, value='account.journal', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=26,
                                        col_offset=62,
                                        end_lineno=30,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=27, col_offset=12, end_lineno=27, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=28, col_offset=12, end_lineno=28, end_col_offset=18, value='code', kind=None),
                                            Constant(lineno=29, col_offset=12, end_lineno=29, end_col_offset=18, value='type', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=27, col_offset=20, end_lineno=27, end_col_offset=35, value='Stock Journal', kind=None),
                                            Constant(lineno=28, col_offset=20, end_lineno=28, end_col_offset=29, value='STJTEST', kind=None),
                                            Constant(lineno=29, col_offset=20, end_lineno=29, end_col_offset=29, value='general', kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=32,
                            col_offset=8,
                            end_lineno=38,
                            end_col_offset=42,
                            targets=[
                                Attribute(
                                    lineno=32,
                                    col_offset=8,
                                    end_lineno=32,
                                    end_col_offset=32,
                                    value=Name(lineno=32, col_offset=8, end_lineno=32, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='product_refrigerator',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=32,
                                col_offset=35,
                                end_lineno=38,
                                end_col_offset=42,
                                func=Attribute(
                                    lineno=32,
                                    col_offset=35,
                                    end_lineno=32,
                                    end_col_offset=53,
                                    value=Attribute(
                                        lineno=32,
                                        col_offset=35,
                                        end_lineno=32,
                                        end_col_offset=46,
                                        value=Name(lineno=32, col_offset=35, end_lineno=32, end_col_offset=38, id='cls', ctx=Load()),
                                        attr='Product',
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=32,
                                        col_offset=54,
                                        end_lineno=38,
                                        end_col_offset=41,
                                        keys=[
                                            Constant(lineno=33, col_offset=12, end_lineno=33, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=34, col_offset=12, end_lineno=34, end_col_offset=18, value='type', kind=None),
                                            Constant(lineno=35, col_offset=12, end_lineno=35, end_col_offset=28, value='standard_price', kind=None),
                                            Constant(lineno=36, col_offset=12, end_lineno=36, end_col_offset=20, value='weight', kind=None),
                                            Constant(lineno=37, col_offset=12, end_lineno=37, end_col_offset=20, value='volume', kind=None),
                                            Constant(lineno=38, col_offset=12, end_lineno=38, end_col_offset=22, value='categ_id', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=33, col_offset=20, end_lineno=33, end_col_offset=34, value='Refrigerator', kind=None),
                                            Constant(lineno=34, col_offset=20, end_lineno=34, end_col_offset=29, value='product', kind=None),
                                            Constant(lineno=35, col_offset=30, end_lineno=35, end_col_offset=33, value=1.0, kind=None),
                                            Constant(lineno=36, col_offset=22, end_lineno=36, end_col_offset=24, value=10, kind=None),
                                            Constant(lineno=37, col_offset=22, end_lineno=37, end_col_offset=23, value=1, kind=None),
                                            Attribute(
                                                lineno=38,
                                                col_offset=24,
                                                end_lineno=38,
                                                end_col_offset=40,
                                                value=Attribute(
                                                    lineno=38,
                                                    col_offset=24,
                                                    end_lineno=38,
                                                    end_col_offset=37,
                                                    value=Name(lineno=38, col_offset=24, end_lineno=38, end_col_offset=27, id='cls', ctx=Load()),
                                                    attr='categ_all',
                                                    ctx=Load(),
                                                ),
                                                attr='id',
                                                ctx=Load(),
                                            ),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=39,
                            col_offset=8,
                            end_lineno=45,
                            end_col_offset=42,
                            targets=[
                                Attribute(
                                    lineno=39,
                                    col_offset=8,
                                    end_lineno=39,
                                    end_col_offset=24,
                                    value=Name(lineno=39, col_offset=8, end_lineno=39, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='product_oven',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=39,
                                col_offset=27,
                                end_lineno=45,
                                end_col_offset=42,
                                func=Attribute(
                                    lineno=39,
                                    col_offset=27,
                                    end_lineno=39,
                                    end_col_offset=45,
                                    value=Attribute(
                                        lineno=39,
                                        col_offset=27,
                                        end_lineno=39,
                                        end_col_offset=38,
                                        value=Name(lineno=39, col_offset=27, end_lineno=39, end_col_offset=30, id='cls', ctx=Load()),
                                        attr='Product',
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=39,
                                        col_offset=46,
                                        end_lineno=45,
                                        end_col_offset=41,
                                        keys=[
                                            Constant(lineno=40, col_offset=12, end_lineno=40, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=41, col_offset=12, end_lineno=41, end_col_offset=18, value='type', kind=None),
                                            Constant(lineno=42, col_offset=12, end_lineno=42, end_col_offset=28, value='standard_price', kind=None),
                                            Constant(lineno=43, col_offset=12, end_lineno=43, end_col_offset=20, value='weight', kind=None),
                                            Constant(lineno=44, col_offset=12, end_lineno=44, end_col_offset=20, value='volume', kind=None),
                                            Constant(lineno=45, col_offset=12, end_lineno=45, end_col_offset=22, value='categ_id', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=40, col_offset=20, end_lineno=40, end_col_offset=36, value='Microwave Oven', kind=None),
                                            Constant(lineno=41, col_offset=20, end_lineno=41, end_col_offset=29, value='product', kind=None),
                                            Constant(lineno=42, col_offset=30, end_lineno=42, end_col_offset=33, value=1.0, kind=None),
                                            Constant(lineno=43, col_offset=22, end_lineno=43, end_col_offset=24, value=20, kind=None),
                                            Constant(lineno=44, col_offset=22, end_lineno=44, end_col_offset=25, value=1.5, kind=None),
                                            Attribute(
                                                lineno=45,
                                                col_offset=24,
                                                end_lineno=45,
                                                end_col_offset=40,
                                                value=Attribute(
                                                    lineno=45,
                                                    col_offset=24,
                                                    end_lineno=45,
                                                    end_col_offset=37,
                                                    value=Name(lineno=45, col_offset=24, end_lineno=45, end_col_offset=27, id='cls', ctx=Load()),
                                                    attr='categ_all',
                                                    ctx=Load(),
                                                ),
                                                attr='id',
                                                ctx=Load(),
                                            ),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=47,
                            col_offset=8,
                            end_lineno=47,
                            end_col_offset=88,
                            targets=[
                                Attribute(
                                    lineno=47,
                                    col_offset=8,
                                    end_lineno=47,
                                    end_col_offset=23,
                                    value=Name(lineno=47, col_offset=8, end_lineno=47, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='landed_cost',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=47,
                                col_offset=26,
                                end_lineno=47,
                                end_col_offset=88,
                                func=Attribute(
                                    lineno=47,
                                    col_offset=26,
                                    end_lineno=47,
                                    end_col_offset=44,
                                    value=Attribute(
                                        lineno=47,
                                        col_offset=26,
                                        end_lineno=47,
                                        end_col_offset=37,
                                        value=Name(lineno=47, col_offset=26, end_lineno=47, end_col_offset=29, id='cls', ctx=Load()),
                                        attr='Product',
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=47,
                                        col_offset=45,
                                        end_lineno=47,
                                        end_col_offset=87,
                                        keys=[
                                            Constant(lineno=47, col_offset=46, end_lineno=47, end_col_offset=52, value='name', kind=None),
                                            Constant(lineno=47, col_offset=69, end_lineno=47, end_col_offset=75, value='type', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=47, col_offset=54, end_lineno=47, end_col_offset=67, value='Landed Cost', kind=None),
                                            Constant(lineno=47, col_offset=77, end_lineno=47, end_col_offset=86, value='service', kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=48,
                            col_offset=8,
                            end_lineno=48,
                            end_col_offset=98,
                            targets=[
                                Attribute(
                                    lineno=48,
                                    col_offset=8,
                                    end_lineno=48,
                                    end_col_offset=30,
                                    value=Name(lineno=48, col_offset=8, end_lineno=48, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='brokerage_quantity',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=48,
                                col_offset=33,
                                end_lineno=48,
                                end_col_offset=98,
                                func=Attribute(
                                    lineno=48,
                                    col_offset=33,
                                    end_lineno=48,
                                    end_col_offset=51,
                                    value=Attribute(
                                        lineno=48,
                                        col_offset=33,
                                        end_lineno=48,
                                        end_col_offset=44,
                                        value=Name(lineno=48, col_offset=33, end_lineno=48, end_col_offset=36, id='cls', ctx=Load()),
                                        attr='Product',
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=48,
                                        col_offset=52,
                                        end_lineno=48,
                                        end_col_offset=97,
                                        keys=[
                                            Constant(lineno=48, col_offset=53, end_lineno=48, end_col_offset=59, value='name', kind=None),
                                            Constant(lineno=48, col_offset=79, end_lineno=48, end_col_offset=85, value='type', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=48, col_offset=61, end_lineno=48, end_col_offset=77, value='Brokerage Cost', kind=None),
                                            Constant(lineno=48, col_offset=87, end_lineno=48, end_col_offset=96, value='service', kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=49,
                            col_offset=8,
                            end_lineno=49,
                            end_col_offset=106,
                            targets=[
                                Attribute(
                                    lineno=49,
                                    col_offset=8,
                                    end_lineno=49,
                                    end_col_offset=33,
                                    value=Name(lineno=49, col_offset=8, end_lineno=49, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='transportation_weight',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=49,
                                col_offset=36,
                                end_lineno=49,
                                end_col_offset=106,
                                func=Attribute(
                                    lineno=49,
                                    col_offset=36,
                                    end_lineno=49,
                                    end_col_offset=54,
                                    value=Attribute(
                                        lineno=49,
                                        col_offset=36,
                                        end_lineno=49,
                                        end_col_offset=47,
                                        value=Name(lineno=49, col_offset=36, end_lineno=49, end_col_offset=39, id='cls', ctx=Load()),
                                        attr='Product',
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=49,
                                        col_offset=55,
                                        end_lineno=49,
                                        end_col_offset=105,
                                        keys=[
                                            Constant(lineno=49, col_offset=56, end_lineno=49, end_col_offset=62, value='name', kind=None),
                                            Constant(lineno=49, col_offset=87, end_lineno=49, end_col_offset=93, value='type', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=49, col_offset=64, end_lineno=49, end_col_offset=85, value='Transportation Cost', kind=None),
                                            Constant(lineno=49, col_offset=95, end_lineno=49, end_col_offset=104, value='service', kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=50,
                            col_offset=8,
                            end_lineno=50,
                            end_col_offset=96,
                            targets=[
                                Attribute(
                                    lineno=50,
                                    col_offset=8,
                                    end_lineno=50,
                                    end_col_offset=28,
                                    value=Name(lineno=50, col_offset=8, end_lineno=50, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='packaging_volume',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=50,
                                col_offset=31,
                                end_lineno=50,
                                end_col_offset=96,
                                func=Attribute(
                                    lineno=50,
                                    col_offset=31,
                                    end_lineno=50,
                                    end_col_offset=49,
                                    value=Attribute(
                                        lineno=50,
                                        col_offset=31,
                                        end_lineno=50,
                                        end_col_offset=42,
                                        value=Name(lineno=50, col_offset=31, end_lineno=50, end_col_offset=34, id='cls', ctx=Load()),
                                        attr='Product',
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=50,
                                        col_offset=50,
                                        end_lineno=50,
                                        end_col_offset=95,
                                        keys=[
                                            Constant(lineno=50, col_offset=51, end_lineno=50, end_col_offset=57, value='name', kind=None),
                                            Constant(lineno=50, col_offset=77, end_lineno=50, end_col_offset=83, value='type', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=50, col_offset=59, end_lineno=50, end_col_offset=75, value='Packaging Cost', kind=None),
                                            Constant(lineno=50, col_offset=85, end_lineno=50, end_col_offset=94, value='service', kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[Name(lineno=8, col_offset=5, end_lineno=8, end_col_offset=16, id='classmethod', ctx=Load())],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
