Module(
    body=[
        Import(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=14,
            names=[alias(name='logging', asname=None)],
        ),
        Import(
            lineno=6,
            col_offset=0,
            end_lineno=6,
            end_col_offset=15,
            names=[alias(name='requests', asname=None)],
        ),
        ImportFrom(
            lineno=8,
            col_offset=0,
            end_lineno=8,
            end_col_offset=44,
            module='odoo',
            names=[
                alias(name='api', asname=None),
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
                alias(name='_', asname=None),
                alias(name='_lt', asname=None),
            ],
            level=0,
        ),
        ImportFrom(
            lineno=9,
            col_offset=0,
            end_lineno=9,
            end_col_offset=37,
            module='odoo.exceptions',
            names=[alias(name='UserError', asname=None)],
            level=0,
        ),
        Assign(
            lineno=11,
            col_offset=0,
            end_lineno=11,
            end_col_offset=37,
            targets=[Name(lineno=11, col_offset=0, end_lineno=11, end_col_offset=7, id='_logger', ctx=Store())],
            value=Call(
                lineno=11,
                col_offset=10,
                end_lineno=11,
                end_col_offset=37,
                func=Attribute(
                    lineno=11,
                    col_offset=10,
                    end_lineno=11,
                    end_col_offset=27,
                    value=Name(lineno=11, col_offset=10, end_lineno=11, end_col_offset=17, id='logging', ctx=Load()),
                    attr='getLogger',
                    ctx=Load(),
                ),
                args=[Name(lineno=11, col_offset=28, end_lineno=11, end_col_offset=36, id='__name__', ctx=Load())],
                keywords=[],
            ),
            type_comment=None,
        ),
        Assign(
            lineno=13,
            col_offset=0,
            end_lineno=23,
            end_col_offset=1,
            targets=[Name(lineno=13, col_offset=0, end_lineno=13, end_col_offset=17, id='TWITTER_EXCEPTION', ctx=Store())],
            value=Dict(
                lineno=13,
                col_offset=20,
                end_lineno=23,
                end_col_offset=1,
                keys=[
                    Constant(lineno=14, col_offset=4, end_lineno=14, end_col_offset=7, value=304, kind=None),
                    Constant(lineno=15, col_offset=4, end_lineno=15, end_col_offset=7, value=400, kind=None),
                    Constant(lineno=16, col_offset=4, end_lineno=16, end_col_offset=7, value=401, kind=None),
                    Constant(lineno=17, col_offset=4, end_lineno=17, end_col_offset=7, value=403, kind=None),
                    Constant(lineno=18, col_offset=4, end_lineno=18, end_col_offset=7, value=429, kind=None),
                    Constant(lineno=19, col_offset=4, end_lineno=19, end_col_offset=7, value=500, kind=None),
                    Constant(lineno=20, col_offset=4, end_lineno=20, end_col_offset=7, value=502, kind=None),
                    Constant(lineno=21, col_offset=4, end_lineno=21, end_col_offset=7, value=503, kind=None),
                    Constant(lineno=22, col_offset=4, end_lineno=22, end_col_offset=7, value=504, kind=None),
                ],
                values=[
                    Call(
                        lineno=14,
                        col_offset=9,
                        end_lineno=14,
                        end_col_offset=48,
                        func=Name(lineno=14, col_offset=9, end_lineno=14, end_col_offset=12, id='_lt', ctx=Load()),
                        args=[Constant(lineno=14, col_offset=13, end_lineno=14, end_col_offset=47, value='There was no new data to return.', kind=None)],
                        keywords=[],
                    ),
                    Call(
                        lineno=15,
                        col_offset=9,
                        end_lineno=15,
                        end_col_offset=155,
                        func=Name(lineno=15, col_offset=9, end_lineno=15, end_col_offset=12, id='_lt', ctx=Load()),
                        args=[Constant(lineno=15, col_offset=13, end_lineno=15, end_col_offset=154, value='The request was invalid or cannot be otherwise served. Requests without authentication are considered invalid and will yield this response.', kind=None)],
                        keywords=[],
                    ),
                    Call(
                        lineno=16,
                        col_offset=9,
                        end_lineno=16,
                        end_col_offset=109,
                        func=Name(lineno=16, col_offset=9, end_lineno=16, end_col_offset=12, id='_lt', ctx=Load()),
                        args=[Constant(lineno=16, col_offset=13, end_lineno=16, end_col_offset=108, value='Authentication credentials were missing or incorrect. Maybe screen name tweets are protected.', kind=None)],
                        keywords=[],
                    ),
                    Call(
                        lineno=17,
                        col_offset=9,
                        end_lineno=17,
                        end_col_offset=138,
                        func=Name(lineno=17, col_offset=9, end_lineno=17, end_col_offset=12, id='_lt', ctx=Load()),
                        args=[Constant(lineno=17, col_offset=13, end_lineno=17, end_col_offset=137, value='The request is understood, but it has been refused or access is not allowed. Please check your Twitter API Key and Secret.', kind=None)],
                        keywords=[],
                    ),
                    Call(
                        lineno=18,
                        col_offset=9,
                        end_lineno=18,
                        end_col_offset=115,
                        func=Name(lineno=18, col_offset=9, end_lineno=18, end_col_offset=12, id='_lt', ctx=Load()),
                        args=[Constant(lineno=18, col_offset=13, end_lineno=18, end_col_offset=114, value='Request cannot be served due to the applications rate limit having been exhausted for the resource.', kind=None)],
                        keywords=[],
                    ),
                    Call(
                        lineno=19,
                        col_offset=9,
                        end_lineno=19,
                        end_col_offset=122,
                        func=Name(lineno=19, col_offset=9, end_lineno=19, end_col_offset=12, id='_lt', ctx=Load()),
                        args=[Constant(lineno=19, col_offset=13, end_lineno=19, end_col_offset=121, value='Twitter seems broken. Please retry later. You may consider posting an issue on Twitter forums to get help.', kind=None)],
                        keywords=[],
                    ),
                    Call(
                        lineno=20,
                        col_offset=9,
                        end_lineno=20,
                        end_col_offset=50,
                        func=Name(lineno=20, col_offset=9, end_lineno=20, end_col_offset=12, id='_lt', ctx=Load()),
                        args=[Constant(lineno=20, col_offset=13, end_lineno=20, end_col_offset=49, value='Twitter is down or being upgraded.', kind=None)],
                        keywords=[],
                    ),
                    Call(
                        lineno=21,
                        col_offset=9,
                        end_lineno=21,
                        end_col_offset=90,
                        func=Name(lineno=21, col_offset=9, end_lineno=21, end_col_offset=12, id='_lt', ctx=Load()),
                        args=[Constant(lineno=21, col_offset=13, end_lineno=21, end_col_offset=89, value='The Twitter servers are up, but overloaded with requests. Try again later.', kind=None)],
                        keywords=[],
                    ),
                    Call(
                        lineno=22,
                        col_offset=9,
                        end_lineno=22,
                        end_col_offset=136,
                        func=Name(lineno=22, col_offset=9, end_lineno=22, end_col_offset=12, id='_lt', ctx=Load()),
                        args=[Constant(lineno=22, col_offset=13, end_lineno=22, end_col_offset=135, value='The Twitter servers are up, but the request could not be serviced due to some failure within our stack. Try again later.', kind=None)],
                        keywords=[],
                    ),
                ],
            ),
            type_comment=None,
        ),
        ClassDef(
            lineno=26,
            col_offset=0,
            end_lineno=84,
            end_col_offset=18,
            name='ResConfigSettings',
            bases=[
                Attribute(
                    lineno=26,
                    col_offset=24,
                    end_lineno=26,
                    end_col_offset=45,
                    value=Name(lineno=26, col_offset=24, end_lineno=26, end_col_offset=30, id='models', ctx=Load()),
                    attr='TransientModel',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=27,
                    col_offset=4,
                    end_lineno=27,
                    end_col_offset=36,
                    targets=[Name(lineno=27, col_offset=4, end_lineno=27, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=27, col_offset=15, end_lineno=27, end_col_offset=36, value='res.config.settings', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=29,
                    col_offset=4,
                    end_lineno=32,
                    end_col_offset=77,
                    targets=[Name(lineno=29, col_offset=4, end_lineno=29, end_col_offset=19, id='twitter_api_key', ctx=Store())],
                    value=Call(
                        lineno=29,
                        col_offset=22,
                        end_lineno=32,
                        end_col_offset=77,
                        func=Attribute(
                            lineno=29,
                            col_offset=22,
                            end_lineno=29,
                            end_col_offset=33,
                            value=Name(lineno=29, col_offset=22, end_lineno=29, end_col_offset=28, id='fields', ctx=Load()),
                            attr='Char',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=30,
                                col_offset=8,
                                end_lineno=30,
                                end_col_offset=44,
                                arg='related',
                                value=Constant(lineno=30, col_offset=16, end_lineno=30, end_col_offset=44, value='website_id.twitter_api_key', kind=None),
                            ),
                            keyword(
                                lineno=30,
                                col_offset=46,
                                end_lineno=30,
                                end_col_offset=60,
                                arg='readonly',
                                value=Constant(lineno=30, col_offset=55, end_lineno=30, end_col_offset=60, value=False, kind=None),
                            ),
                            keyword(
                                lineno=31,
                                col_offset=8,
                                end_lineno=31,
                                end_col_offset=24,
                                arg='string',
                                value=Constant(lineno=31, col_offset=15, end_lineno=31, end_col_offset=24, value='API Key', kind=None),
                            ),
                            keyword(
                                lineno=32,
                                col_offset=8,
                                end_lineno=32,
                                end_col_offset=76,
                                arg='help',
                                value=Constant(lineno=32, col_offset=13, end_lineno=32, end_col_offset=76, value='Twitter API key you can get it from https://apps.twitter.com/', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=33,
                    col_offset=4,
                    end_lineno=36,
                    end_col_offset=80,
                    targets=[Name(lineno=33, col_offset=4, end_lineno=33, end_col_offset=22, id='twitter_api_secret', ctx=Store())],
                    value=Call(
                        lineno=33,
                        col_offset=25,
                        end_lineno=36,
                        end_col_offset=80,
                        func=Attribute(
                            lineno=33,
                            col_offset=25,
                            end_lineno=33,
                            end_col_offset=36,
                            value=Name(lineno=33, col_offset=25, end_lineno=33, end_col_offset=31, id='fields', ctx=Load()),
                            attr='Char',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=34,
                                col_offset=8,
                                end_lineno=34,
                                end_col_offset=47,
                                arg='related',
                                value=Constant(lineno=34, col_offset=16, end_lineno=34, end_col_offset=47, value='website_id.twitter_api_secret', kind=None),
                            ),
                            keyword(
                                lineno=34,
                                col_offset=49,
                                end_lineno=34,
                                end_col_offset=63,
                                arg='readonly',
                                value=Constant(lineno=34, col_offset=58, end_lineno=34, end_col_offset=63, value=False, kind=None),
                            ),
                            keyword(
                                lineno=35,
                                col_offset=8,
                                end_lineno=35,
                                end_col_offset=27,
                                arg='string',
                                value=Constant(lineno=35, col_offset=15, end_lineno=35, end_col_offset=27, value='API secret', kind=None),
                            ),
                            keyword(
                                lineno=36,
                                col_offset=8,
                                end_lineno=36,
                                end_col_offset=79,
                                arg='help',
                                value=Constant(lineno=36, col_offset=13, end_lineno=36, end_col_offset=79, value='Twitter API secret you can get it from https://apps.twitter.com/', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=37,
                    col_offset=4,
                    end_lineno=41,
                    end_col_offset=61,
                    targets=[Name(lineno=37, col_offset=4, end_lineno=37, end_col_offset=23, id='twitter_screen_name', ctx=Store())],
                    value=Call(
                        lineno=37,
                        col_offset=26,
                        end_lineno=41,
                        end_col_offset=61,
                        func=Attribute(
                            lineno=37,
                            col_offset=26,
                            end_lineno=37,
                            end_col_offset=37,
                            value=Name(lineno=37, col_offset=26, end_lineno=37, end_col_offset=32, id='fields', ctx=Load()),
                            attr='Char',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=38,
                                col_offset=8,
                                end_lineno=38,
                                end_col_offset=48,
                                arg='related',
                                value=Constant(lineno=38, col_offset=16, end_lineno=38, end_col_offset=48, value='website_id.twitter_screen_name', kind=None),
                            ),
                            keyword(
                                lineno=38,
                                col_offset=50,
                                end_lineno=38,
                                end_col_offset=64,
                                arg='readonly',
                                value=Constant(lineno=38, col_offset=59, end_lineno=38, end_col_offset=64, value=False, kind=None),
                            ),
                            keyword(
                                lineno=39,
                                col_offset=8,
                                end_lineno=39,
                                end_col_offset=31,
                                arg='string',
                                value=Constant(lineno=39, col_offset=15, end_lineno=39, end_col_offset=31, value='Favorites From', kind=None),
                            ),
                            keyword(
                                lineno=40,
                                col_offset=8,
                                end_lineno=41,
                                end_col_offset=60,
                                arg='help',
                                value=Constant(lineno=40, col_offset=13, end_lineno=41, end_col_offset=60, value='Screen Name of the Twitter Account from which you want to load favorites.It does not have to match the API Key/Secret.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=42,
                    col_offset=4,
                    end_lineno=42,
                    end_col_offset=80,
                    targets=[Name(lineno=42, col_offset=4, end_lineno=42, end_col_offset=22, id='twitter_server_uri', ctx=Store())],
                    value=Call(
                        lineno=42,
                        col_offset=25,
                        end_lineno=42,
                        end_col_offset=80,
                        func=Attribute(
                            lineno=42,
                            col_offset=25,
                            end_lineno=42,
                            end_col_offset=36,
                            value=Name(lineno=42, col_offset=25, end_lineno=42, end_col_offset=31, id='fields', ctx=Load()),
                            attr='Char',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=42,
                                col_offset=37,
                                end_lineno=42,
                                end_col_offset=64,
                                arg='string',
                                value=Constant(lineno=42, col_offset=44, end_lineno=42, end_col_offset=64, value='Twitter server uri', kind=None),
                            ),
                            keyword(
                                lineno=42,
                                col_offset=66,
                                end_lineno=42,
                                end_col_offset=79,
                                arg='readonly',
                                value=Constant(lineno=42, col_offset=75, end_lineno=42, end_col_offset=79, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=44,
                    col_offset=4,
                    end_lineno=48,
                    end_col_offset=62,
                    name='_get_twitter_exception_message',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=44, col_offset=39, end_lineno=44, end_col_offset=43, arg='self', annotation=None, type_comment=None),
                            arg(lineno=44, col_offset=45, end_lineno=44, end_col_offset=55, arg='error_code', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        If(
                            lineno=45,
                            col_offset=8,
                            end_lineno=48,
                            end_col_offset=62,
                            test=Compare(
                                lineno=45,
                                col_offset=11,
                                end_lineno=45,
                                end_col_offset=42,
                                left=Name(lineno=45, col_offset=11, end_lineno=45, end_col_offset=21, id='error_code', ctx=Load()),
                                ops=[In()],
                                comparators=[Name(lineno=45, col_offset=25, end_lineno=45, end_col_offset=42, id='TWITTER_EXCEPTION', ctx=Load())],
                            ),
                            body=[
                                Return(
                                    lineno=46,
                                    col_offset=12,
                                    end_lineno=46,
                                    end_col_offset=48,
                                    value=Subscript(
                                        lineno=46,
                                        col_offset=19,
                                        end_lineno=46,
                                        end_col_offset=48,
                                        value=Name(lineno=46, col_offset=19, end_lineno=46, end_col_offset=36, id='TWITTER_EXCEPTION', ctx=Load()),
                                        slice=Name(lineno=46, col_offset=37, end_lineno=46, end_col_offset=47, id='error_code', ctx=Load()),
                                        ctx=Load(),
                                    ),
                                ),
                            ],
                            orelse=[
                                Return(
                                    lineno=48,
                                    col_offset=12,
                                    end_lineno=48,
                                    end_col_offset=62,
                                    value=Call(
                                        lineno=48,
                                        col_offset=19,
                                        end_lineno=48,
                                        end_col_offset=62,
                                        func=Name(lineno=48, col_offset=19, end_lineno=48, end_col_offset=20, id='_', ctx=Load()),
                                        args=[Constant(lineno=48, col_offset=21, end_lineno=48, end_col_offset=61, value='HTTP Error: Something is misconfigured', kind=None)],
                                        keywords=[],
                                    ),
                                ),
                            ],
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=50,
                    col_offset=4,
                    end_lineno=62,
                    end_col_offset=115,
                    name='_check_twitter_authorization',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=50, col_offset=37, end_lineno=50, end_col_offset=41, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Try(
                            lineno=51,
                            col_offset=8,
                            end_lineno=62,
                            end_col_offset=115,
                            body=[
                                Expr(
                                    lineno=52,
                                    col_offset=12,
                                    end_lineno=52,
                                    end_col_offset=51,
                                    value=Call(
                                        lineno=52,
                                        col_offset=12,
                                        end_lineno=52,
                                        end_col_offset=51,
                                        func=Attribute(
                                            lineno=52,
                                            col_offset=12,
                                            end_lineno=52,
                                            end_col_offset=49,
                                            value=Attribute(
                                                lineno=52,
                                                col_offset=12,
                                                end_lineno=52,
                                                end_col_offset=27,
                                                value=Name(lineno=52, col_offset=12, end_lineno=52, end_col_offset=16, id='self', ctx=Load()),
                                                attr='website_id',
                                                ctx=Load(),
                                            ),
                                            attr='fetch_favorite_tweets',
                                            ctx=Load(),
                                        ),
                                        args=[],
                                        keywords=[],
                                    ),
                                ),
                            ],
                            handlers=[
                                ExceptHandler(
                                    lineno=54,
                                    col_offset=8,
                                    end_lineno=56,
                                    end_col_offset=152,
                                    type=Attribute(
                                        lineno=54,
                                        col_offset=15,
                                        end_lineno=54,
                                        end_col_offset=33,
                                        value=Name(lineno=54, col_offset=15, end_lineno=54, end_col_offset=23, id='requests', ctx=Load()),
                                        attr='HTTPError',
                                        ctx=Load(),
                                    ),
                                    name='e',
                                    body=[
                                        Expr(
                                            lineno=55,
                                            col_offset=12,
                                            end_lineno=55,
                                            end_col_offset=96,
                                            value=Call(
                                                lineno=55,
                                                col_offset=12,
                                                end_lineno=55,
                                                end_col_offset=96,
                                                func=Attribute(
                                                    lineno=55,
                                                    col_offset=12,
                                                    end_lineno=55,
                                                    end_col_offset=24,
                                                    value=Name(lineno=55, col_offset=12, end_lineno=55, end_col_offset=19, id='_logger', ctx=Load()),
                                                    attr='info',
                                                    ctx=Load(),
                                                ),
                                                args=[
                                                    BinOp(
                                                        lineno=55,
                                                        col_offset=25,
                                                        end_lineno=55,
                                                        end_col_offset=80,
                                                        left=Constant(lineno=55, col_offset=25, end_lineno=55, end_col_offset=34, value='%s - %s', kind=None),
                                                        op=Mod(),
                                                        right=Tuple(
                                                            lineno=55,
                                                            col_offset=37,
                                                            end_lineno=55,
                                                            end_col_offset=80,
                                                            elts=[
                                                                Attribute(
                                                                    lineno=55,
                                                                    col_offset=38,
                                                                    end_lineno=55,
                                                                    end_col_offset=60,
                                                                    value=Attribute(
                                                                        lineno=55,
                                                                        col_offset=38,
                                                                        end_lineno=55,
                                                                        end_col_offset=48,
                                                                        value=Name(lineno=55, col_offset=38, end_lineno=55, end_col_offset=39, id='e', ctx=Load()),
                                                                        attr='response',
                                                                        ctx=Load(),
                                                                    ),
                                                                    attr='status_code',
                                                                    ctx=Load(),
                                                                ),
                                                                Attribute(
                                                                    lineno=55,
                                                                    col_offset=62,
                                                                    end_lineno=55,
                                                                    end_col_offset=79,
                                                                    value=Attribute(
                                                                        lineno=55,
                                                                        col_offset=62,
                                                                        end_lineno=55,
                                                                        end_col_offset=72,
                                                                        value=Name(lineno=55, col_offset=62, end_lineno=55, end_col_offset=63, id='e', ctx=Load()),
                                                                        attr='response',
                                                                        ctx=Load(),
                                                                    ),
                                                                    attr='reason',
                                                                    ctx=Load(),
                                                                ),
                                                            ],
                                                            ctx=Load(),
                                                        ),
                                                    ),
                                                ],
                                                keywords=[
                                                    keyword(
                                                        lineno=55,
                                                        col_offset=82,
                                                        end_lineno=55,
                                                        end_col_offset=95,
                                                        arg='exc_info',
                                                        value=Constant(lineno=55, col_offset=91, end_lineno=55, end_col_offset=95, value=True, kind=None),
                                                    ),
                                                ],
                                            ),
                                        ),
                                        Raise(
                                            lineno=56,
                                            col_offset=12,
                                            end_lineno=56,
                                            end_col_offset=152,
                                            exc=Call(
                                                lineno=56,
                                                col_offset=18,
                                                end_lineno=56,
                                                end_col_offset=152,
                                                func=Name(lineno=56, col_offset=18, end_lineno=56, end_col_offset=27, id='UserError', ctx=Load()),
                                                args=[
                                                    BinOp(
                                                        lineno=56,
                                                        col_offset=28,
                                                        end_lineno=56,
                                                        end_col_offset=151,
                                                        left=BinOp(
                                                            lineno=56,
                                                            col_offset=28,
                                                            end_lineno=56,
                                                            end_col_offset=89,
                                                            left=BinOp(
                                                                lineno=56,
                                                                col_offset=28,
                                                                end_lineno=56,
                                                                end_col_offset=83,
                                                                left=Constant(lineno=56, col_offset=28, end_lineno=56, end_col_offset=37, value='%s - %s', kind=None),
                                                                op=Mod(),
                                                                right=Tuple(
                                                                    lineno=56,
                                                                    col_offset=40,
                                                                    end_lineno=56,
                                                                    end_col_offset=83,
                                                                    elts=[
                                                                        Attribute(
                                                                            lineno=56,
                                                                            col_offset=41,
                                                                            end_lineno=56,
                                                                            end_col_offset=63,
                                                                            value=Attribute(
                                                                                lineno=56,
                                                                                col_offset=41,
                                                                                end_lineno=56,
                                                                                end_col_offset=51,
                                                                                value=Name(lineno=56, col_offset=41, end_lineno=56, end_col_offset=42, id='e', ctx=Load()),
                                                                                attr='response',
                                                                                ctx=Load(),
                                                                            ),
                                                                            attr='status_code',
                                                                            ctx=Load(),
                                                                        ),
                                                                        Attribute(
                                                                            lineno=56,
                                                                            col_offset=65,
                                                                            end_lineno=56,
                                                                            end_col_offset=82,
                                                                            value=Attribute(
                                                                                lineno=56,
                                                                                col_offset=65,
                                                                                end_lineno=56,
                                                                                end_col_offset=75,
                                                                                value=Name(lineno=56, col_offset=65, end_lineno=56, end_col_offset=66, id='e', ctx=Load()),
                                                                                attr='response',
                                                                                ctx=Load(),
                                                                            ),
                                                                            attr='reason',
                                                                            ctx=Load(),
                                                                        ),
                                                                    ],
                                                                    ctx=Load(),
                                                                ),
                                                            ),
                                                            op=Add(),
                                                            right=Constant(lineno=56, col_offset=86, end_lineno=56, end_col_offset=89, value=':', kind=None),
                                                        ),
                                                        op=Add(),
                                                        right=Call(
                                                            lineno=56,
                                                            col_offset=92,
                                                            end_lineno=56,
                                                            end_col_offset=151,
                                                            func=Attribute(
                                                                lineno=56,
                                                                col_offset=92,
                                                                end_lineno=56,
                                                                end_col_offset=127,
                                                                value=Name(lineno=56, col_offset=92, end_lineno=56, end_col_offset=96, id='self', ctx=Load()),
                                                                attr='_get_twitter_exception_message',
                                                                ctx=Load(),
                                                            ),
                                                            args=[
                                                                Attribute(
                                                                    lineno=56,
                                                                    col_offset=128,
                                                                    end_lineno=56,
                                                                    end_col_offset=150,
                                                                    value=Attribute(
                                                                        lineno=56,
                                                                        col_offset=128,
                                                                        end_lineno=56,
                                                                        end_col_offset=138,
                                                                        value=Name(lineno=56, col_offset=128, end_lineno=56, end_col_offset=129, id='e', ctx=Load()),
                                                                        attr='response',
                                                                        ctx=Load(),
                                                                    ),
                                                                    attr='status_code',
                                                                    ctx=Load(),
                                                                ),
                                                            ],
                                                            keywords=[],
                                                        ),
                                                    ),
                                                ],
                                                keywords=[],
                                            ),
                                            cause=None,
                                        ),
                                    ],
                                ),
                                ExceptHandler(
                                    lineno=57,
                                    col_offset=8,
                                    end_lineno=59,
                                    end_col_offset=99,
                                    type=Name(lineno=57, col_offset=15, end_lineno=57, end_col_offset=22, id='IOError', ctx=Load()),
                                    name=None,
                                    body=[
                                        Expr(
                                            lineno=58,
                                            col_offset=12,
                                            end_lineno=58,
                                            end_col_offset=79,
                                            value=Call(
                                                lineno=58,
                                                col_offset=12,
                                                end_lineno=58,
                                                end_col_offset=79,
                                                func=Attribute(
                                                    lineno=58,
                                                    col_offset=12,
                                                    end_lineno=58,
                                                    end_col_offset=24,
                                                    value=Name(lineno=58, col_offset=12, end_lineno=58, end_col_offset=19, id='_logger', ctx=Load()),
                                                    attr='info',
                                                    ctx=Load(),
                                                ),
                                                args=[Constant(lineno=58, col_offset=25, end_lineno=58, end_col_offset=63, value='We failed to reach a twitter server.', kind=None)],
                                                keywords=[
                                                    keyword(
                                                        lineno=58,
                                                        col_offset=65,
                                                        end_lineno=58,
                                                        end_col_offset=78,
                                                        arg='exc_info',
                                                        value=Constant(lineno=58, col_offset=74, end_lineno=58, end_col_offset=78, value=True, kind=None),
                                                    ),
                                                ],
                                            ),
                                        ),
                                        Raise(
                                            lineno=59,
                                            col_offset=12,
                                            end_lineno=59,
                                            end_col_offset=99,
                                            exc=Call(
                                                lineno=59,
                                                col_offset=18,
                                                end_lineno=59,
                                                end_col_offset=99,
                                                func=Name(lineno=59, col_offset=18, end_lineno=59, end_col_offset=27, id='UserError', ctx=Load()),
                                                args=[
                                                    Call(
                                                        lineno=59,
                                                        col_offset=28,
                                                        end_lineno=59,
                                                        end_col_offset=98,
                                                        func=Name(lineno=59, col_offset=28, end_lineno=59, end_col_offset=29, id='_', ctx=Load()),
                                                        args=[Constant(lineno=59, col_offset=30, end_lineno=59, end_col_offset=97, value='Internet connection refused: We failed to reach a twitter server.', kind=None)],
                                                        keywords=[],
                                                    ),
                                                ],
                                                keywords=[],
                                            ),
                                            cause=None,
                                        ),
                                    ],
                                ),
                                ExceptHandler(
                                    lineno=60,
                                    col_offset=8,
                                    end_lineno=62,
                                    end_col_offset=115,
                                    type=Name(lineno=60, col_offset=15, end_lineno=60, end_col_offset=24, id='Exception', ctx=Load()),
                                    name=None,
                                    body=[
                                        Expr(
                                            lineno=61,
                                            col_offset=12,
                                            end_lineno=61,
                                            end_col_offset=95,
                                            value=Call(
                                                lineno=61,
                                                col_offset=12,
                                                end_lineno=61,
                                                end_col_offset=95,
                                                func=Attribute(
                                                    lineno=61,
                                                    col_offset=12,
                                                    end_lineno=61,
                                                    end_col_offset=24,
                                                    value=Name(lineno=61, col_offset=12, end_lineno=61, end_col_offset=19, id='_logger', ctx=Load()),
                                                    attr='info',
                                                    ctx=Load(),
                                                ),
                                                args=[Constant(lineno=61, col_offset=25, end_lineno=61, end_col_offset=79, value='Please double-check your Twitter API Key and Secret!', kind=None)],
                                                keywords=[
                                                    keyword(
                                                        lineno=61,
                                                        col_offset=81,
                                                        end_lineno=61,
                                                        end_col_offset=94,
                                                        arg='exc_info',
                                                        value=Constant(lineno=61, col_offset=90, end_lineno=61, end_col_offset=94, value=True, kind=None),
                                                    ),
                                                ],
                                            ),
                                        ),
                                        Raise(
                                            lineno=62,
                                            col_offset=12,
                                            end_lineno=62,
                                            end_col_offset=115,
                                            exc=Call(
                                                lineno=62,
                                                col_offset=18,
                                                end_lineno=62,
                                                end_col_offset=115,
                                                func=Name(lineno=62, col_offset=18, end_lineno=62, end_col_offset=27, id='UserError', ctx=Load()),
                                                args=[
                                                    Call(
                                                        lineno=62,
                                                        col_offset=28,
                                                        end_lineno=62,
                                                        end_col_offset=114,
                                                        func=Name(lineno=62, col_offset=28, end_lineno=62, end_col_offset=29, id='_', ctx=Load()),
                                                        args=[Constant(lineno=62, col_offset=30, end_lineno=62, end_col_offset=113, value='Twitter authorization error! Please double-check your Twitter API Key and Secret!', kind=None)],
                                                        keywords=[],
                                                    ),
                                                ],
                                                keywords=[],
                                            ),
                                            cause=None,
                                        ),
                                    ],
                                ),
                            ],
                            orelse=[],
                            finalbody=[],
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=65,
                    col_offset=4,
                    end_lineno=69,
                    end_col_offset=28,
                    name='create',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=65, col_offset=15, end_lineno=65, end_col_offset=19, arg='self', annotation=None, type_comment=None),
                            arg(lineno=65, col_offset=21, end_lineno=65, end_col_offset=25, arg='vals', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=66,
                            col_offset=8,
                            end_lineno=66,
                            end_col_offset=67,
                            targets=[Name(lineno=66, col_offset=8, end_lineno=66, end_col_offset=21, id='TwitterConfig', ctx=Store())],
                            value=Call(
                                lineno=66,
                                col_offset=24,
                                end_lineno=66,
                                end_col_offset=67,
                                func=Attribute(
                                    lineno=66,
                                    col_offset=24,
                                    end_lineno=66,
                                    end_col_offset=61,
                                    value=Call(
                                        lineno=66,
                                        col_offset=24,
                                        end_lineno=66,
                                        end_col_offset=54,
                                        func=Name(lineno=66, col_offset=24, end_lineno=66, end_col_offset=29, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=66, col_offset=30, end_lineno=66, end_col_offset=47, id='ResConfigSettings', ctx=Load()),
                                            Name(lineno=66, col_offset=49, end_lineno=66, end_col_offset=53, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[Name(lineno=66, col_offset=62, end_lineno=66, end_col_offset=66, id='vals', ctx=Load())],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        If(
                            lineno=67,
                            col_offset=8,
                            end_lineno=68,
                            end_col_offset=56,
                            test=BoolOp(
                                lineno=67,
                                col_offset=11,
                                end_lineno=67,
                                end_col_offset=107,
                                op=Or(),
                                values=[
                                    Call(
                                        lineno=67,
                                        col_offset=11,
                                        end_lineno=67,
                                        end_col_offset=38,
                                        func=Attribute(
                                            lineno=67,
                                            col_offset=11,
                                            end_lineno=67,
                                            end_col_offset=19,
                                            value=Name(lineno=67, col_offset=11, end_lineno=67, end_col_offset=15, id='vals', ctx=Load()),
                                            attr='get',
                                            ctx=Load(),
                                        ),
                                        args=[Constant(lineno=67, col_offset=20, end_lineno=67, end_col_offset=37, value='twitter_api_key', kind=None)],
                                        keywords=[],
                                    ),
                                    Call(
                                        lineno=67,
                                        col_offset=42,
                                        end_lineno=67,
                                        end_col_offset=72,
                                        func=Attribute(
                                            lineno=67,
                                            col_offset=42,
                                            end_lineno=67,
                                            end_col_offset=50,
                                            value=Name(lineno=67, col_offset=42, end_lineno=67, end_col_offset=46, id='vals', ctx=Load()),
                                            attr='get',
                                            ctx=Load(),
                                        ),
                                        args=[Constant(lineno=67, col_offset=51, end_lineno=67, end_col_offset=71, value='twitter_api_secret', kind=None)],
                                        keywords=[],
                                    ),
                                    Call(
                                        lineno=67,
                                        col_offset=76,
                                        end_lineno=67,
                                        end_col_offset=107,
                                        func=Attribute(
                                            lineno=67,
                                            col_offset=76,
                                            end_lineno=67,
                                            end_col_offset=84,
                                            value=Name(lineno=67, col_offset=76, end_lineno=67, end_col_offset=80, id='vals', ctx=Load()),
                                            attr='get',
                                            ctx=Load(),
                                        ),
                                        args=[Constant(lineno=67, col_offset=85, end_lineno=67, end_col_offset=106, value='twitter_screen_name', kind=None)],
                                        keywords=[],
                                    ),
                                ],
                            ),
                            body=[
                                Expr(
                                    lineno=68,
                                    col_offset=12,
                                    end_lineno=68,
                                    end_col_offset=56,
                                    value=Call(
                                        lineno=68,
                                        col_offset=12,
                                        end_lineno=68,
                                        end_col_offset=56,
                                        func=Attribute(
                                            lineno=68,
                                            col_offset=12,
                                            end_lineno=68,
                                            end_col_offset=54,
                                            value=Name(lineno=68, col_offset=12, end_lineno=68, end_col_offset=25, id='TwitterConfig', ctx=Load()),
                                            attr='_check_twitter_authorization',
                                            ctx=Load(),
                                        ),
                                        args=[],
                                        keywords=[],
                                    ),
                                ),
                            ],
                            orelse=[],
                        ),
                        Return(
                            lineno=69,
                            col_offset=8,
                            end_lineno=69,
                            end_col_offset=28,
                            value=Name(lineno=69, col_offset=15, end_lineno=69, end_col_offset=28, id='TwitterConfig', ctx=Load()),
                        ),
                    ],
                    decorator_list=[
                        Attribute(
                            lineno=64,
                            col_offset=5,
                            end_lineno=64,
                            end_col_offset=14,
                            value=Name(lineno=64, col_offset=5, end_lineno=64, end_col_offset=8, id='api', ctx=Load()),
                            attr='model',
                            ctx=Load(),
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=71,
                    col_offset=4,
                    end_lineno=75,
                    end_col_offset=28,
                    name='write',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=71, col_offset=14, end_lineno=71, end_col_offset=18, arg='self', annotation=None, type_comment=None),
                            arg(lineno=71, col_offset=20, end_lineno=71, end_col_offset=24, arg='vals', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=72,
                            col_offset=8,
                            end_lineno=72,
                            end_col_offset=66,
                            targets=[Name(lineno=72, col_offset=8, end_lineno=72, end_col_offset=21, id='TwitterConfig', ctx=Store())],
                            value=Call(
                                lineno=72,
                                col_offset=24,
                                end_lineno=72,
                                end_col_offset=66,
                                func=Attribute(
                                    lineno=72,
                                    col_offset=24,
                                    end_lineno=72,
                                    end_col_offset=60,
                                    value=Call(
                                        lineno=72,
                                        col_offset=24,
                                        end_lineno=72,
                                        end_col_offset=54,
                                        func=Name(lineno=72, col_offset=24, end_lineno=72, end_col_offset=29, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=72, col_offset=30, end_lineno=72, end_col_offset=47, id='ResConfigSettings', ctx=Load()),
                                            Name(lineno=72, col_offset=49, end_lineno=72, end_col_offset=53, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='write',
                                    ctx=Load(),
                                ),
                                args=[Name(lineno=72, col_offset=61, end_lineno=72, end_col_offset=65, id='vals', ctx=Load())],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        If(
                            lineno=73,
                            col_offset=8,
                            end_lineno=74,
                            end_col_offset=47,
                            test=BoolOp(
                                lineno=73,
                                col_offset=11,
                                end_lineno=73,
                                end_col_offset=107,
                                op=Or(),
                                values=[
                                    Call(
                                        lineno=73,
                                        col_offset=11,
                                        end_lineno=73,
                                        end_col_offset=38,
                                        func=Attribute(
                                            lineno=73,
                                            col_offset=11,
                                            end_lineno=73,
                                            end_col_offset=19,
                                            value=Name(lineno=73, col_offset=11, end_lineno=73, end_col_offset=15, id='vals', ctx=Load()),
                                            attr='get',
                                            ctx=Load(),
                                        ),
                                        args=[Constant(lineno=73, col_offset=20, end_lineno=73, end_col_offset=37, value='twitter_api_key', kind=None)],
                                        keywords=[],
                                    ),
                                    Call(
                                        lineno=73,
                                        col_offset=42,
                                        end_lineno=73,
                                        end_col_offset=72,
                                        func=Attribute(
                                            lineno=73,
                                            col_offset=42,
                                            end_lineno=73,
                                            end_col_offset=50,
                                            value=Name(lineno=73, col_offset=42, end_lineno=73, end_col_offset=46, id='vals', ctx=Load()),
                                            attr='get',
                                            ctx=Load(),
                                        ),
                                        args=[Constant(lineno=73, col_offset=51, end_lineno=73, end_col_offset=71, value='twitter_api_secret', kind=None)],
                                        keywords=[],
                                    ),
                                    Call(
                                        lineno=73,
                                        col_offset=76,
                                        end_lineno=73,
                                        end_col_offset=107,
                                        func=Attribute(
                                            lineno=73,
                                            col_offset=76,
                                            end_lineno=73,
                                            end_col_offset=84,
                                            value=Name(lineno=73, col_offset=76, end_lineno=73, end_col_offset=80, id='vals', ctx=Load()),
                                            attr='get',
                                            ctx=Load(),
                                        ),
                                        args=[Constant(lineno=73, col_offset=85, end_lineno=73, end_col_offset=106, value='twitter_screen_name', kind=None)],
                                        keywords=[],
                                    ),
                                ],
                            ),
                            body=[
                                Expr(
                                    lineno=74,
                                    col_offset=12,
                                    end_lineno=74,
                                    end_col_offset=47,
                                    value=Call(
                                        lineno=74,
                                        col_offset=12,
                                        end_lineno=74,
                                        end_col_offset=47,
                                        func=Attribute(
                                            lineno=74,
                                            col_offset=12,
                                            end_lineno=74,
                                            end_col_offset=45,
                                            value=Name(lineno=74, col_offset=12, end_lineno=74, end_col_offset=16, id='self', ctx=Load()),
                                            attr='_check_twitter_authorization',
                                            ctx=Load(),
                                        ),
                                        args=[],
                                        keywords=[],
                                    ),
                                ),
                            ],
                            orelse=[],
                        ),
                        Return(
                            lineno=75,
                            col_offset=8,
                            end_lineno=75,
                            end_col_offset=28,
                            value=Name(lineno=75, col_offset=15, end_lineno=75, end_col_offset=28, id='TwitterConfig', ctx=Load()),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=78,
                    col_offset=4,
                    end_lineno=84,
                    end_col_offset=18,
                    name='get_values',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=78, col_offset=19, end_lineno=78, end_col_offset=23, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=79,
                            col_offset=8,
                            end_lineno=79,
                            end_col_offset=57,
                            targets=[Name(lineno=79, col_offset=8, end_lineno=79, end_col_offset=11, id='res', ctx=Store())],
                            value=Call(
                                lineno=79,
                                col_offset=14,
                                end_lineno=79,
                                end_col_offset=57,
                                func=Attribute(
                                    lineno=79,
                                    col_offset=14,
                                    end_lineno=79,
                                    end_col_offset=55,
                                    value=Call(
                                        lineno=79,
                                        col_offset=14,
                                        end_lineno=79,
                                        end_col_offset=44,
                                        func=Name(lineno=79, col_offset=14, end_lineno=79, end_col_offset=19, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=79, col_offset=20, end_lineno=79, end_col_offset=37, id='ResConfigSettings', ctx=Load()),
                                            Name(lineno=79, col_offset=39, end_lineno=79, end_col_offset=43, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='get_values',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=80,
                            col_offset=8,
                            end_lineno=80,
                            end_col_offset=55,
                            targets=[Name(lineno=80, col_offset=8, end_lineno=80, end_col_offset=14, id='Params', ctx=Store())],
                            value=Call(
                                lineno=80,
                                col_offset=17,
                                end_lineno=80,
                                end_col_offset=55,
                                func=Attribute(
                                    lineno=80,
                                    col_offset=17,
                                    end_lineno=80,
                                    end_col_offset=53,
                                    value=Subscript(
                                        lineno=80,
                                        col_offset=17,
                                        end_lineno=80,
                                        end_col_offset=48,
                                        value=Attribute(
                                            lineno=80,
                                            col_offset=17,
                                            end_lineno=80,
                                            end_col_offset=25,
                                            value=Name(lineno=80, col_offset=17, end_lineno=80, end_col_offset=21, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=80, col_offset=26, end_lineno=80, end_col_offset=47, value='ir.config_parameter', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='sudo',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=81,
                            col_offset=8,
                            end_lineno=83,
                            end_col_offset=10,
                            value=Call(
                                lineno=81,
                                col_offset=8,
                                end_lineno=83,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=81,
                                    col_offset=8,
                                    end_lineno=81,
                                    end_col_offset=18,
                                    value=Name(lineno=81, col_offset=8, end_lineno=81, end_col_offset=11, id='res', ctx=Load()),
                                    attr='update',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=81,
                                        col_offset=19,
                                        end_lineno=83,
                                        end_col_offset=9,
                                        keys=[Constant(lineno=82, col_offset=12, end_lineno=82, end_col_offset=32, value='twitter_server_uri', kind=None)],
                                        values=[
                                            BinOp(
                                                lineno=82,
                                                col_offset=34,
                                                end_lineno=82,
                                                end_col_offset=113,
                                                left=Constant(lineno=82, col_offset=34, end_lineno=82, end_col_offset=39, value='%s/', kind=None),
                                                op=Mod(),
                                                right=Call(
                                                    lineno=82,
                                                    col_offset=42,
                                                    end_lineno=82,
                                                    end_col_offset=113,
                                                    func=Attribute(
                                                        lineno=82,
                                                        col_offset=42,
                                                        end_lineno=82,
                                                        end_col_offset=58,
                                                        value=Name(lineno=82, col_offset=42, end_lineno=82, end_col_offset=48, id='Params', ctx=Load()),
                                                        attr='get_param',
                                                        ctx=Load(),
                                                    ),
                                                    args=[Constant(lineno=82, col_offset=59, end_lineno=82, end_col_offset=73, value='web.base.url', kind=None)],
                                                    keywords=[
                                                        keyword(
                                                            lineno=82,
                                                            col_offset=75,
                                                            end_lineno=82,
                                                            end_col_offset=112,
                                                            arg='default',
                                                            value=Constant(lineno=82, col_offset=83, end_lineno=82, end_col_offset=112, value='http://yourcompany.odoo.com', kind=None),
                                                        ),
                                                    ],
                                                ),
                                            ),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Return(
                            lineno=84,
                            col_offset=8,
                            end_lineno=84,
                            end_col_offset=18,
                            value=Name(lineno=84, col_offset=15, end_lineno=84, end_col_offset=18, id='res', ctx=Load()),
                        ),
                    ],
                    decorator_list=[
                        Attribute(
                            lineno=77,
                            col_offset=5,
                            end_lineno=77,
                            end_col_offset=14,
                            value=Name(lineno=77, col_offset=5, end_lineno=77, end_col_offset=8, id='api', ctx=Load()),
                            attr='model',
                            ctx=Load(),
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
