Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=31,
            module='odoo',
            names=[
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=20,
            end_col_offset=6,
            name='BarcodeRule',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=18,
                    end_lineno=7,
                    end_col_offset=30,
                    value=Name(lineno=7, col_offset=18, end_lineno=7, end_col_offset=24, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=29,
                    targets=[Name(lineno=8, col_offset=4, end_lineno=8, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=8, col_offset=15, end_lineno=8, end_col_offset=29, value='barcode.rule', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=10,
                    col_offset=4,
                    end_lineno=20,
                    end_col_offset=6,
                    targets=[Name(lineno=10, col_offset=4, end_lineno=10, end_col_offset=8, id='type', ctx=Store())],
                    value=Call(
                        lineno=10,
                        col_offset=11,
                        end_lineno=20,
                        end_col_offset=6,
                        func=Attribute(
                            lineno=10,
                            col_offset=11,
                            end_lineno=10,
                            end_col_offset=27,
                            value=Name(lineno=10, col_offset=11, end_lineno=10, end_col_offset=17, id='fields', ctx=Load()),
                            attr='Selection',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=10,
                                col_offset=28,
                                end_lineno=15,
                                end_col_offset=5,
                                arg='selection_add',
                                value=List(
                                    lineno=10,
                                    col_offset=42,
                                    end_lineno=15,
                                    end_col_offset=5,
                                    elts=[
                                        Tuple(
                                            lineno=11,
                                            col_offset=8,
                                            end_lineno=11,
                                            end_col_offset=38,
                                            elts=[
                                                Constant(lineno=11, col_offset=9, end_lineno=11, end_col_offset=17, value='weight', kind=None),
                                                Constant(lineno=11, col_offset=19, end_lineno=11, end_col_offset=37, value='Weighted Product', kind=None),
                                            ],
                                            ctx=Load(),
                                        ),
                                        Tuple(
                                            lineno=12,
                                            col_offset=8,
                                            end_lineno=12,
                                            end_col_offset=32,
                                            elts=[
                                                Constant(lineno=12, col_offset=9, end_lineno=12, end_col_offset=19, value='location', kind=None),
                                                Constant(lineno=12, col_offset=21, end_lineno=12, end_col_offset=31, value='Location', kind=None),
                                            ],
                                            ctx=Load(),
                                        ),
                                        Tuple(
                                            lineno=13,
                                            col_offset=8,
                                            end_lineno=13,
                                            end_col_offset=22,
                                            elts=[
                                                Constant(lineno=13, col_offset=9, end_lineno=13, end_col_offset=14, value='lot', kind=None),
                                                Constant(lineno=13, col_offset=16, end_lineno=13, end_col_offset=21, value='Lot', kind=None),
                                            ],
                                            ctx=Load(),
                                        ),
                                        Tuple(
                                            lineno=14,
                                            col_offset=8,
                                            end_lineno=14,
                                            end_col_offset=30,
                                            elts=[
                                                Constant(lineno=14, col_offset=9, end_lineno=14, end_col_offset=18, value='package', kind=None),
                                                Constant(lineno=14, col_offset=20, end_lineno=14, end_col_offset=29, value='Package', kind=None),
                                            ],
                                            ctx=Load(),
                                        ),
                                    ],
                                    ctx=Load(),
                                ),
                            ),
                            keyword(
                                lineno=15,
                                col_offset=7,
                                end_lineno=20,
                                end_col_offset=5,
                                arg='ondelete',
                                value=Dict(
                                    lineno=15,
                                    col_offset=16,
                                    end_lineno=20,
                                    end_col_offset=5,
                                    keys=[
                                        Constant(lineno=16, col_offset=8, end_lineno=16, end_col_offset=16, value='weight', kind=None),
                                        Constant(lineno=17, col_offset=8, end_lineno=17, end_col_offset=18, value='location', kind=None),
                                        Constant(lineno=18, col_offset=8, end_lineno=18, end_col_offset=13, value='lot', kind=None),
                                        Constant(lineno=19, col_offset=8, end_lineno=19, end_col_offset=17, value='package', kind=None),
                                    ],
                                    values=[
                                        Constant(lineno=16, col_offset=18, end_lineno=16, end_col_offset=31, value='set default', kind=None),
                                        Constant(lineno=17, col_offset=20, end_lineno=17, end_col_offset=33, value='set default', kind=None),
                                        Constant(lineno=18, col_offset=15, end_lineno=18, end_col_offset=28, value='set default', kind=None),
                                        Constant(lineno=19, col_offset=19, end_lineno=19, end_col_offset=32, value='set default', kind=None),
                                    ],
                                ),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
