Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=39,
            module='odoo',
            names=[
                alias(name='api', asname=None),
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
                alias(name='_', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=31,
            end_col_offset=9,
            name='ProductTemplate',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=22,
                    end_lineno=7,
                    end_col_offset=34,
                    value=Name(lineno=7, col_offset=22, end_lineno=7, end_col_offset=28, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=35,
                    targets=[Name(lineno=8, col_offset=4, end_lineno=8, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=List(
                        lineno=8,
                        col_offset=15,
                        end_lineno=8,
                        end_col_offset=35,
                        elts=[Constant(lineno=8, col_offset=16, end_lineno=8, end_col_offset=34, value='product.template', kind=None)],
                        ctx=Load(),
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=10,
                    col_offset=4,
                    end_lineno=10,
                    end_col_offset=89,
                    targets=[Name(lineno=10, col_offset=4, end_lineno=10, end_col_offset=20, id='attachment_count', ctx=Store())],
                    value=Call(
                        lineno=10,
                        col_offset=23,
                        end_lineno=10,
                        end_col_offset=89,
                        func=Attribute(
                            lineno=10,
                            col_offset=23,
                            end_lineno=10,
                            end_col_offset=37,
                            value=Name(lineno=10, col_offset=23, end_lineno=10, end_col_offset=29, id='fields', ctx=Load()),
                            attr='Integer',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=10,
                                col_offset=38,
                                end_lineno=10,
                                end_col_offset=73,
                                arg='compute',
                                value=Constant(lineno=10, col_offset=46, end_lineno=10, end_col_offset=73, value='_compute_attachment_count', kind=None),
                            ),
                            keyword(
                                lineno=10,
                                col_offset=75,
                                end_lineno=10,
                                end_col_offset=88,
                                arg='string',
                                value=Constant(lineno=10, col_offset=82, end_lineno=10, end_col_offset=88, value='File', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=12,
                    col_offset=4,
                    end_lineno=16,
                    end_col_offset=87,
                    name='_compute_attachment_count',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=12, col_offset=34, end_lineno=12, end_col_offset=38, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=13,
                            col_offset=8,
                            end_lineno=13,
                            end_col_offset=185,
                            targets=[Name(lineno=13, col_offset=8, end_lineno=13, end_col_offset=23, id='attachment_data', ctx=Store())],
                            value=Call(
                                lineno=13,
                                col_offset=26,
                                end_lineno=13,
                                end_col_offset=185,
                                func=Attribute(
                                    lineno=13,
                                    col_offset=26,
                                    end_lineno=13,
                                    end_col_offset=62,
                                    value=Subscript(
                                        lineno=13,
                                        col_offset=26,
                                        end_lineno=13,
                                        end_col_offset=51,
                                        value=Attribute(
                                            lineno=13,
                                            col_offset=26,
                                            end_lineno=13,
                                            end_col_offset=34,
                                            value=Name(lineno=13, col_offset=26, end_lineno=13, end_col_offset=30, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=13, col_offset=35, end_lineno=13, end_col_offset=50, value='ir.attachment', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='read_group',
                                    ctx=Load(),
                                ),
                                args=[
                                    List(
                                        lineno=13,
                                        col_offset=63,
                                        end_lineno=13,
                                        end_col_offset=160,
                                        elts=[
                                            Tuple(
                                                lineno=13,
                                                col_offset=64,
                                                end_lineno=13,
                                                end_col_offset=94,
                                                elts=[
                                                    Constant(lineno=13, col_offset=65, end_lineno=13, end_col_offset=76, value='res_model', kind=None),
                                                    Constant(lineno=13, col_offset=78, end_lineno=13, end_col_offset=81, value='=', kind=None),
                                                    Attribute(
                                                        lineno=13,
                                                        col_offset=83,
                                                        end_lineno=13,
                                                        end_col_offset=93,
                                                        value=Name(lineno=13, col_offset=83, end_lineno=13, end_col_offset=87, id='self', ctx=Load()),
                                                        attr='_name',
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                            Tuple(
                                                lineno=13,
                                                col_offset=96,
                                                end_lineno=13,
                                                end_col_offset=122,
                                                elts=[
                                                    Constant(lineno=13, col_offset=97, end_lineno=13, end_col_offset=105, value='res_id', kind=None),
                                                    Constant(lineno=13, col_offset=107, end_lineno=13, end_col_offset=111, value='in', kind=None),
                                                    Attribute(
                                                        lineno=13,
                                                        col_offset=113,
                                                        end_lineno=13,
                                                        end_col_offset=121,
                                                        value=Name(lineno=13, col_offset=113, end_lineno=13, end_col_offset=117, id='self', ctx=Load()),
                                                        attr='ids',
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                            Tuple(
                                                lineno=13,
                                                col_offset=124,
                                                end_lineno=13,
                                                end_col_offset=159,
                                                elts=[
                                                    Constant(lineno=13, col_offset=125, end_lineno=13, end_col_offset=147, value='product_downloadable', kind=None),
                                                    Constant(lineno=13, col_offset=149, end_lineno=13, end_col_offset=152, value='=', kind=None),
                                                    Constant(lineno=13, col_offset=154, end_lineno=13, end_col_offset=158, value=True, kind=None),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                    List(
                                        lineno=13,
                                        col_offset=162,
                                        end_lineno=13,
                                        end_col_offset=172,
                                        elts=[Constant(lineno=13, col_offset=163, end_lineno=13, end_col_offset=171, value='res_id', kind=None)],
                                        ctx=Load(),
                                    ),
                                    List(
                                        lineno=13,
                                        col_offset=174,
                                        end_lineno=13,
                                        end_col_offset=184,
                                        elts=[Constant(lineno=13, col_offset=175, end_lineno=13, end_col_offset=183, value='res_id', kind=None)],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=14,
                            col_offset=8,
                            end_lineno=14,
                            end_col_offset=96,
                            targets=[Name(lineno=14, col_offset=8, end_lineno=14, end_col_offset=19, id='mapped_data', ctx=Store())],
                            value=Call(
                                lineno=14,
                                col_offset=22,
                                end_lineno=14,
                                end_col_offset=96,
                                func=Name(lineno=14, col_offset=22, end_lineno=14, end_col_offset=26, id='dict', ctx=Load()),
                                args=[
                                    ListComp(
                                        lineno=14,
                                        col_offset=27,
                                        end_lineno=14,
                                        end_col_offset=95,
                                        elt=Tuple(
                                            lineno=14,
                                            col_offset=28,
                                            end_lineno=14,
                                            end_col_offset=66,
                                            elts=[
                                                Subscript(
                                                    lineno=14,
                                                    col_offset=29,
                                                    end_lineno=14,
                                                    end_col_offset=43,
                                                    value=Name(lineno=14, col_offset=29, end_lineno=14, end_col_offset=33, id='data', ctx=Load()),
                                                    slice=Constant(lineno=14, col_offset=34, end_lineno=14, end_col_offset=42, value='res_id', kind=None),
                                                    ctx=Load(),
                                                ),
                                                Subscript(
                                                    lineno=14,
                                                    col_offset=45,
                                                    end_lineno=14,
                                                    end_col_offset=65,
                                                    value=Name(lineno=14, col_offset=45, end_lineno=14, end_col_offset=49, id='data', ctx=Load()),
                                                    slice=Constant(lineno=14, col_offset=50, end_lineno=14, end_col_offset=64, value='res_id_count', kind=None),
                                                    ctx=Load(),
                                                ),
                                            ],
                                            ctx=Load(),
                                        ),
                                        generators=[
                                            comprehension(
                                                target=Name(lineno=14, col_offset=71, end_lineno=14, end_col_offset=75, id='data', ctx=Store()),
                                                iter=Name(lineno=14, col_offset=79, end_lineno=14, end_col_offset=94, id='attachment_data', ctx=Load()),
                                                ifs=[],
                                                is_async=0,
                                            ),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        For(
                            lineno=15,
                            col_offset=8,
                            end_lineno=16,
                            end_col_offset=87,
                            target=Name(lineno=15, col_offset=12, end_lineno=15, end_col_offset=28, id='product_template', ctx=Store()),
                            iter=Name(lineno=15, col_offset=32, end_lineno=15, end_col_offset=36, id='self', ctx=Load()),
                            body=[
                                Assign(
                                    lineno=16,
                                    col_offset=12,
                                    end_lineno=16,
                                    end_col_offset=87,
                                    targets=[
                                        Attribute(
                                            lineno=16,
                                            col_offset=12,
                                            end_lineno=16,
                                            end_col_offset=45,
                                            value=Name(lineno=16, col_offset=12, end_lineno=16, end_col_offset=28, id='product_template', ctx=Load()),
                                            attr='attachment_count',
                                            ctx=Store(),
                                        ),
                                    ],
                                    value=Call(
                                        lineno=16,
                                        col_offset=48,
                                        end_lineno=16,
                                        end_col_offset=87,
                                        func=Attribute(
                                            lineno=16,
                                            col_offset=48,
                                            end_lineno=16,
                                            end_col_offset=63,
                                            value=Name(lineno=16, col_offset=48, end_lineno=16, end_col_offset=59, id='mapped_data', ctx=Load()),
                                            attr='get',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Attribute(
                                                lineno=16,
                                                col_offset=64,
                                                end_lineno=16,
                                                end_col_offset=83,
                                                value=Name(lineno=16, col_offset=64, end_lineno=16, end_col_offset=80, id='product_template', ctx=Load()),
                                                attr='id',
                                                ctx=Load(),
                                            ),
                                            Constant(lineno=16, col_offset=85, end_lineno=16, end_col_offset=86, value=0, kind=None),
                                        ],
                                        keywords=[],
                                    ),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[],
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=18,
                    col_offset=4,
                    end_lineno=31,
                    end_col_offset=9,
                    name='action_open_attachments',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=18, col_offset=32, end_lineno=18, end_col_offset=36, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=19,
                            col_offset=8,
                            end_lineno=19,
                            end_col_offset=25,
                            value=Call(
                                lineno=19,
                                col_offset=8,
                                end_lineno=19,
                                end_col_offset=25,
                                func=Attribute(
                                    lineno=19,
                                    col_offset=8,
                                    end_lineno=19,
                                    end_col_offset=23,
                                    value=Name(lineno=19, col_offset=8, end_lineno=19, end_col_offset=12, id='self', ctx=Load()),
                                    attr='ensure_one',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Return(
                            lineno=20,
                            col_offset=8,
                            end_lineno=31,
                            end_col_offset=9,
                            value=Dict(
                                lineno=20,
                                col_offset=15,
                                end_lineno=31,
                                end_col_offset=9,
                                keys=[
                                    Constant(lineno=21, col_offset=12, end_lineno=21, end_col_offset=18, value='name', kind=None),
                                    Constant(lineno=22, col_offset=12, end_lineno=22, end_col_offset=20, value='domain', kind=None),
                                    Constant(lineno=23, col_offset=12, end_lineno=23, end_col_offset=23, value='res_model', kind=None),
                                    Constant(lineno=24, col_offset=12, end_lineno=24, end_col_offset=18, value='type', kind=None),
                                    Constant(lineno=25, col_offset=12, end_lineno=25, end_col_offset=23, value='view_mode', kind=None),
                                    Constant(lineno=26, col_offset=12, end_lineno=26, end_col_offset=21, value='context', kind=None),
                                    Constant(lineno=27, col_offset=12, end_lineno=27, end_col_offset=18, value='help', kind=None),
                                ],
                                values=[
                                    Call(
                                        lineno=21,
                                        col_offset=20,
                                        end_lineno=21,
                                        end_col_offset=44,
                                        func=Name(lineno=21, col_offset=20, end_lineno=21, end_col_offset=21, id='_', ctx=Load()),
                                        args=[Constant(lineno=21, col_offset=22, end_lineno=21, end_col_offset=43, value='Digital Attachments', kind=None)],
                                        keywords=[],
                                    ),
                                    List(
                                        lineno=22,
                                        col_offset=22,
                                        end_lineno=22,
                                        end_col_offset=117,
                                        elts=[
                                            Tuple(
                                                lineno=22,
                                                col_offset=23,
                                                end_lineno=22,
                                                end_col_offset=53,
                                                elts=[
                                                    Constant(lineno=22, col_offset=24, end_lineno=22, end_col_offset=35, value='res_model', kind=None),
                                                    Constant(lineno=22, col_offset=37, end_lineno=22, end_col_offset=40, value='=', kind=None),
                                                    Attribute(
                                                        lineno=22,
                                                        col_offset=42,
                                                        end_lineno=22,
                                                        end_col_offset=52,
                                                        value=Name(lineno=22, col_offset=42, end_lineno=22, end_col_offset=46, id='self', ctx=Load()),
                                                        attr='_name',
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                            Tuple(
                                                lineno=22,
                                                col_offset=55,
                                                end_lineno=22,
                                                end_col_offset=79,
                                                elts=[
                                                    Constant(lineno=22, col_offset=56, end_lineno=22, end_col_offset=64, value='res_id', kind=None),
                                                    Constant(lineno=22, col_offset=66, end_lineno=22, end_col_offset=69, value='=', kind=None),
                                                    Attribute(
                                                        lineno=22,
                                                        col_offset=71,
                                                        end_lineno=22,
                                                        end_col_offset=78,
                                                        value=Name(lineno=22, col_offset=71, end_lineno=22, end_col_offset=75, id='self', ctx=Load()),
                                                        attr='id',
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                            Tuple(
                                                lineno=22,
                                                col_offset=81,
                                                end_lineno=22,
                                                end_col_offset=116,
                                                elts=[
                                                    Constant(lineno=22, col_offset=82, end_lineno=22, end_col_offset=104, value='product_downloadable', kind=None),
                                                    Constant(lineno=22, col_offset=106, end_lineno=22, end_col_offset=109, value='=', kind=None),
                                                    Constant(lineno=22, col_offset=111, end_lineno=22, end_col_offset=115, value=True, kind=None),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=23, col_offset=25, end_lineno=23, end_col_offset=40, value='ir.attachment', kind=None),
                                    Constant(lineno=24, col_offset=20, end_lineno=24, end_col_offset=43, value='ir.actions.act_window', kind=None),
                                    Constant(lineno=25, col_offset=25, end_lineno=25, end_col_offset=38, value='kanban,form', kind=None),
                                    BinOp(
                                        lineno=26,
                                        col_offset=23,
                                        end_lineno=26,
                                        end_col_offset=135,
                                        left=Constant(lineno=26, col_offset=23, end_lineno=26, end_col_offset=111, value="{'default_res_model': '%s','default_res_id': %d, 'default_product_downloadable': True}", kind=None),
                                        op=Mod(),
                                        right=Tuple(
                                            lineno=26,
                                            col_offset=114,
                                            end_lineno=26,
                                            end_col_offset=135,
                                            elts=[
                                                Attribute(
                                                    lineno=26,
                                                    col_offset=115,
                                                    end_lineno=26,
                                                    end_col_offset=125,
                                                    value=Name(lineno=26, col_offset=115, end_lineno=26, end_col_offset=119, id='self', ctx=Load()),
                                                    attr='_name',
                                                    ctx=Load(),
                                                ),
                                                Attribute(
                                                    lineno=26,
                                                    col_offset=127,
                                                    end_lineno=26,
                                                    end_col_offset=134,
                                                    value=Name(lineno=26, col_offset=127, end_lineno=26, end_col_offset=131, id='self', ctx=Load()),
                                                    attr='id',
                                                    ctx=Load(),
                                                ),
                                            ],
                                            ctx=Load(),
                                        ),
                                    ),
                                    Constant(lineno=27, col_offset=20, end_lineno=30, end_col_offset=19, value='\n                <p class="o_view_nocontent_smiling_face">Add attachments for this digital product</p>\n                <p>The attached files are the ones that will be purchased and sent to the customer.</p>\n                ', kind=None),
                                ],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
        ClassDef(
            lineno=34,
            col_offset=0,
            end_lineno=61,
            end_col_offset=9,
            name='Product',
            bases=[
                Attribute(
                    lineno=34,
                    col_offset=14,
                    end_lineno=34,
                    end_col_offset=26,
                    value=Name(lineno=34, col_offset=14, end_lineno=34, end_col_offset=20, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=35,
                    col_offset=4,
                    end_lineno=35,
                    end_col_offset=32,
                    targets=[Name(lineno=35, col_offset=4, end_lineno=35, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=35, col_offset=15, end_lineno=35, end_col_offset=32, value='product.product', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=37,
                    col_offset=4,
                    end_lineno=37,
                    end_col_offset=89,
                    targets=[Name(lineno=37, col_offset=4, end_lineno=37, end_col_offset=20, id='attachment_count', ctx=Store())],
                    value=Call(
                        lineno=37,
                        col_offset=23,
                        end_lineno=37,
                        end_col_offset=89,
                        func=Attribute(
                            lineno=37,
                            col_offset=23,
                            end_lineno=37,
                            end_col_offset=37,
                            value=Name(lineno=37, col_offset=23, end_lineno=37, end_col_offset=29, id='fields', ctx=Load()),
                            attr='Integer',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=37,
                                col_offset=38,
                                end_lineno=37,
                                end_col_offset=73,
                                arg='compute',
                                value=Constant(lineno=37, col_offset=46, end_lineno=37, end_col_offset=73, value='_compute_attachment_count', kind=None),
                            ),
                            keyword(
                                lineno=37,
                                col_offset=75,
                                end_lineno=37,
                                end_col_offset=88,
                                arg='string',
                                value=Constant(lineno=37, col_offset=82, end_lineno=37, end_col_offset=88, value='File', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=39,
                    col_offset=4,
                    end_lineno=44,
                    end_col_offset=131,
                    name='_compute_attachment_count',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=39, col_offset=34, end_lineno=39, end_col_offset=38, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        For(
                            lineno=40,
                            col_offset=8,
                            end_lineno=44,
                            end_col_offset=131,
                            target=Name(lineno=40, col_offset=12, end_lineno=40, end_col_offset=19, id='product', ctx=Store()),
                            iter=Name(lineno=40, col_offset=23, end_lineno=40, end_col_offset=27, id='self', ctx=Load()),
                            body=[
                                Assign(
                                    lineno=41,
                                    col_offset=12,
                                    end_lineno=44,
                                    end_col_offset=131,
                                    targets=[
                                        Attribute(
                                            lineno=41,
                                            col_offset=12,
                                            end_lineno=41,
                                            end_col_offset=36,
                                            value=Name(lineno=41, col_offset=12, end_lineno=41, end_col_offset=19, id='product', ctx=Load()),
                                            attr='attachment_count',
                                            ctx=Store(),
                                        ),
                                    ],
                                    value=Call(
                                        lineno=41,
                                        col_offset=39,
                                        end_lineno=44,
                                        end_col_offset=131,
                                        func=Attribute(
                                            lineno=41,
                                            col_offset=39,
                                            end_lineno=41,
                                            end_col_offset=77,
                                            value=Subscript(
                                                lineno=41,
                                                col_offset=39,
                                                end_lineno=41,
                                                end_col_offset=64,
                                                value=Attribute(
                                                    lineno=41,
                                                    col_offset=39,
                                                    end_lineno=41,
                                                    end_col_offset=47,
                                                    value=Name(lineno=41, col_offset=39, end_lineno=41, end_col_offset=43, id='self', ctx=Load()),
                                                    attr='env',
                                                    ctx=Load(),
                                                ),
                                                slice=Constant(lineno=41, col_offset=48, end_lineno=41, end_col_offset=63, value='ir.attachment', kind=None),
                                                ctx=Load(),
                                            ),
                                            attr='search_count',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            List(
                                                lineno=41,
                                                col_offset=78,
                                                end_lineno=44,
                                                end_col_offset=130,
                                                elts=[
                                                    Constant(lineno=42, col_offset=16, end_lineno=42, end_col_offset=19, value='|', kind=None),
                                                    Constant(lineno=43, col_offset=16, end_lineno=43, end_col_offset=19, value='&', kind=None),
                                                    Constant(lineno=43, col_offset=21, end_lineno=43, end_col_offset=24, value='&', kind=None),
                                                    Tuple(
                                                        lineno=43,
                                                        col_offset=26,
                                                        end_lineno=43,
                                                        end_col_offset=64,
                                                        elts=[
                                                            Constant(lineno=43, col_offset=27, end_lineno=43, end_col_offset=38, value='res_model', kind=None),
                                                            Constant(lineno=43, col_offset=40, end_lineno=43, end_col_offset=43, value='=', kind=None),
                                                            Constant(lineno=43, col_offset=45, end_lineno=43, end_col_offset=63, value='product.template', kind=None),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                    Tuple(
                                                        lineno=43,
                                                        col_offset=66,
                                                        end_lineno=43,
                                                        end_col_offset=109,
                                                        elts=[
                                                            Constant(lineno=43, col_offset=67, end_lineno=43, end_col_offset=75, value='res_id', kind=None),
                                                            Constant(lineno=43, col_offset=77, end_lineno=43, end_col_offset=80, value='=', kind=None),
                                                            Attribute(
                                                                lineno=43,
                                                                col_offset=82,
                                                                end_lineno=43,
                                                                end_col_offset=108,
                                                                value=Attribute(
                                                                    lineno=43,
                                                                    col_offset=82,
                                                                    end_lineno=43,
                                                                    end_col_offset=105,
                                                                    value=Name(lineno=43, col_offset=82, end_lineno=43, end_col_offset=89, id='product', ctx=Load()),
                                                                    attr='product_tmpl_id',
                                                                    ctx=Load(),
                                                                ),
                                                                attr='id',
                                                                ctx=Load(),
                                                            ),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                    Tuple(
                                                        lineno=43,
                                                        col_offset=111,
                                                        end_lineno=43,
                                                        end_col_offset=146,
                                                        elts=[
                                                            Constant(lineno=43, col_offset=112, end_lineno=43, end_col_offset=134, value='product_downloadable', kind=None),
                                                            Constant(lineno=43, col_offset=136, end_lineno=43, end_col_offset=139, value='=', kind=None),
                                                            Constant(lineno=43, col_offset=141, end_lineno=43, end_col_offset=145, value=True, kind=None),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                    Constant(lineno=44, col_offset=16, end_lineno=44, end_col_offset=19, value='&', kind=None),
                                                    Constant(lineno=44, col_offset=21, end_lineno=44, end_col_offset=24, value='&', kind=None),
                                                    Tuple(
                                                        lineno=44,
                                                        col_offset=26,
                                                        end_lineno=44,
                                                        end_col_offset=63,
                                                        elts=[
                                                            Constant(lineno=44, col_offset=27, end_lineno=44, end_col_offset=38, value='res_model', kind=None),
                                                            Constant(lineno=44, col_offset=40, end_lineno=44, end_col_offset=43, value='=', kind=None),
                                                            Constant(lineno=44, col_offset=45, end_lineno=44, end_col_offset=62, value='product.product', kind=None),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                    Tuple(
                                                        lineno=44,
                                                        col_offset=65,
                                                        end_lineno=44,
                                                        end_col_offset=92,
                                                        elts=[
                                                            Constant(lineno=44, col_offset=66, end_lineno=44, end_col_offset=74, value='res_id', kind=None),
                                                            Constant(lineno=44, col_offset=76, end_lineno=44, end_col_offset=79, value='=', kind=None),
                                                            Attribute(
                                                                lineno=44,
                                                                col_offset=81,
                                                                end_lineno=44,
                                                                end_col_offset=91,
                                                                value=Name(lineno=44, col_offset=81, end_lineno=44, end_col_offset=88, id='product', ctx=Load()),
                                                                attr='id',
                                                                ctx=Load(),
                                                            ),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                    Tuple(
                                                        lineno=44,
                                                        col_offset=94,
                                                        end_lineno=44,
                                                        end_col_offset=129,
                                                        elts=[
                                                            Constant(lineno=44, col_offset=95, end_lineno=44, end_col_offset=117, value='product_downloadable', kind=None),
                                                            Constant(lineno=44, col_offset=119, end_lineno=44, end_col_offset=122, value='=', kind=None),
                                                            Constant(lineno=44, col_offset=124, end_lineno=44, end_col_offset=128, value=True, kind=None),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[],
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=46,
                    col_offset=4,
                    end_lineno=61,
                    end_col_offset=9,
                    name='action_open_attachments',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=46, col_offset=32, end_lineno=46, end_col_offset=36, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=47,
                            col_offset=8,
                            end_lineno=47,
                            end_col_offset=25,
                            value=Call(
                                lineno=47,
                                col_offset=8,
                                end_lineno=47,
                                end_col_offset=25,
                                func=Attribute(
                                    lineno=47,
                                    col_offset=8,
                                    end_lineno=47,
                                    end_col_offset=23,
                                    value=Name(lineno=47, col_offset=8, end_lineno=47, end_col_offset=12, id='self', ctx=Load()),
                                    attr='ensure_one',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Return(
                            lineno=48,
                            col_offset=8,
                            end_lineno=61,
                            end_col_offset=9,
                            value=Dict(
                                lineno=48,
                                col_offset=15,
                                end_lineno=61,
                                end_col_offset=9,
                                keys=[
                                    Constant(lineno=49, col_offset=12, end_lineno=49, end_col_offset=18, value='name', kind=None),
                                    Constant(lineno=50, col_offset=12, end_lineno=50, end_col_offset=20, value='domain', kind=None),
                                    Constant(lineno=53, col_offset=12, end_lineno=53, end_col_offset=23, value='res_model', kind=None),
                                    Constant(lineno=54, col_offset=12, end_lineno=54, end_col_offset=18, value='type', kind=None),
                                    Constant(lineno=55, col_offset=12, end_lineno=55, end_col_offset=23, value='view_mode', kind=None),
                                    Constant(lineno=56, col_offset=12, end_lineno=56, end_col_offset=21, value='context', kind=None),
                                    Constant(lineno=57, col_offset=12, end_lineno=57, end_col_offset=18, value='help', kind=None),
                                ],
                                values=[
                                    Call(
                                        lineno=49,
                                        col_offset=20,
                                        end_lineno=49,
                                        end_col_offset=44,
                                        func=Name(lineno=49, col_offset=20, end_lineno=49, end_col_offset=21, id='_', ctx=Load()),
                                        args=[Constant(lineno=49, col_offset=22, end_lineno=49, end_col_offset=43, value='Digital Attachments', kind=None)],
                                        keywords=[],
                                    ),
                                    List(
                                        lineno=50,
                                        col_offset=22,
                                        end_lineno=52,
                                        end_col_offset=85,
                                        elts=[
                                            Tuple(
                                                lineno=50,
                                                col_offset=23,
                                                end_lineno=50,
                                                end_col_offset=58,
                                                elts=[
                                                    Constant(lineno=50, col_offset=24, end_lineno=50, end_col_offset=46, value='product_downloadable', kind=None),
                                                    Constant(lineno=50, col_offset=48, end_lineno=50, end_col_offset=51, value='=', kind=None),
                                                    Constant(lineno=50, col_offset=53, end_lineno=50, end_col_offset=57, value=True, kind=None),
                                                ],
                                                ctx=Load(),
                                            ),
                                            Constant(lineno=50, col_offset=60, end_lineno=50, end_col_offset=63, value='|', kind=None),
                                            Constant(lineno=51, col_offset=23, end_lineno=51, end_col_offset=26, value='&', kind=None),
                                            Tuple(
                                                lineno=51,
                                                col_offset=28,
                                                end_lineno=51,
                                                end_col_offset=66,
                                                elts=[
                                                    Constant(lineno=51, col_offset=29, end_lineno=51, end_col_offset=40, value='res_model', kind=None),
                                                    Constant(lineno=51, col_offset=42, end_lineno=51, end_col_offset=45, value='=', kind=None),
                                                    Constant(lineno=51, col_offset=47, end_lineno=51, end_col_offset=65, value='product.template', kind=None),
                                                ],
                                                ctx=Load(),
                                            ),
                                            Tuple(
                                                lineno=51,
                                                col_offset=68,
                                                end_lineno=51,
                                                end_col_offset=108,
                                                elts=[
                                                    Constant(lineno=51, col_offset=69, end_lineno=51, end_col_offset=77, value='res_id', kind=None),
                                                    Constant(lineno=51, col_offset=79, end_lineno=51, end_col_offset=82, value='=', kind=None),
                                                    Attribute(
                                                        lineno=51,
                                                        col_offset=84,
                                                        end_lineno=51,
                                                        end_col_offset=107,
                                                        value=Attribute(
                                                            lineno=51,
                                                            col_offset=84,
                                                            end_lineno=51,
                                                            end_col_offset=104,
                                                            value=Name(lineno=51, col_offset=84, end_lineno=51, end_col_offset=88, id='self', ctx=Load()),
                                                            attr='product_tmpl_id',
                                                            ctx=Load(),
                                                        ),
                                                        attr='id',
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                            Constant(lineno=52, col_offset=23, end_lineno=52, end_col_offset=26, value='&', kind=None),
                                            Tuple(
                                                lineno=52,
                                                col_offset=28,
                                                end_lineno=52,
                                                end_col_offset=58,
                                                elts=[
                                                    Constant(lineno=52, col_offset=29, end_lineno=52, end_col_offset=40, value='res_model', kind=None),
                                                    Constant(lineno=52, col_offset=42, end_lineno=52, end_col_offset=45, value='=', kind=None),
                                                    Attribute(
                                                        lineno=52,
                                                        col_offset=47,
                                                        end_lineno=52,
                                                        end_col_offset=57,
                                                        value=Name(lineno=52, col_offset=47, end_lineno=52, end_col_offset=51, id='self', ctx=Load()),
                                                        attr='_name',
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                            Tuple(
                                                lineno=52,
                                                col_offset=60,
                                                end_lineno=52,
                                                end_col_offset=84,
                                                elts=[
                                                    Constant(lineno=52, col_offset=61, end_lineno=52, end_col_offset=69, value='res_id', kind=None),
                                                    Constant(lineno=52, col_offset=71, end_lineno=52, end_col_offset=74, value='=', kind=None),
                                                    Attribute(
                                                        lineno=52,
                                                        col_offset=76,
                                                        end_lineno=52,
                                                        end_col_offset=83,
                                                        value=Name(lineno=52, col_offset=76, end_lineno=52, end_col_offset=80, id='self', ctx=Load()),
                                                        attr='id',
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=53, col_offset=25, end_lineno=53, end_col_offset=40, value='ir.attachment', kind=None),
                                    Constant(lineno=54, col_offset=20, end_lineno=54, end_col_offset=43, value='ir.actions.act_window', kind=None),
                                    Constant(lineno=55, col_offset=25, end_lineno=55, end_col_offset=38, value='kanban,form', kind=None),
                                    BinOp(
                                        lineno=56,
                                        col_offset=23,
                                        end_lineno=56,
                                        end_col_offset=135,
                                        left=Constant(lineno=56, col_offset=23, end_lineno=56, end_col_offset=111, value="{'default_res_model': '%s','default_res_id': %d, 'default_product_downloadable': True}", kind=None),
                                        op=Mod(),
                                        right=Tuple(
                                            lineno=56,
                                            col_offset=114,
                                            end_lineno=56,
                                            end_col_offset=135,
                                            elts=[
                                                Attribute(
                                                    lineno=56,
                                                    col_offset=115,
                                                    end_lineno=56,
                                                    end_col_offset=125,
                                                    value=Name(lineno=56, col_offset=115, end_lineno=56, end_col_offset=119, id='self', ctx=Load()),
                                                    attr='_name',
                                                    ctx=Load(),
                                                ),
                                                Attribute(
                                                    lineno=56,
                                                    col_offset=127,
                                                    end_lineno=56,
                                                    end_col_offset=134,
                                                    value=Name(lineno=56, col_offset=127, end_lineno=56, end_col_offset=131, id='self', ctx=Load()),
                                                    attr='id',
                                                    ctx=Load(),
                                                ),
                                            ],
                                            ctx=Load(),
                                        ),
                                    ),
                                    Constant(lineno=57, col_offset=20, end_lineno=60, end_col_offset=19, value='\n                <p class="o_view_nocontent_smiling_face">Add attachments for this digital product</p>\n                <p>The attached files are the ones that will be purchased and sent to the customer.</p>\n                ', kind=None),
                                ],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
