Module(
    body=[
        Expr(
            lineno=2,
            col_offset=0,
            end_lineno=2,
            end_col_offset=99,
            value=Constant(lineno=2, col_offset=0, end_lineno=2, end_col_offset=99, value='Utilities for generating, parsing and checking XML/XSD files on top of the lxml.etree module.', kind=None),
        ),
        Import(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=13,
            names=[alias(name='base64', asname=None)],
        ),
        ImportFrom(
            lineno=5,
            col_offset=0,
            end_lineno=5,
            end_col_offset=22,
            module='io',
            names=[alias(name='BytesIO', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=6,
            col_offset=0,
            end_lineno=6,
            end_col_offset=22,
            module='lxml',
            names=[alias(name='etree', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=8,
            col_offset=0,
            end_lineno=8,
            end_col_offset=37,
            module='odoo.exceptions',
            names=[alias(name='UserError', asname=None)],
            level=0,
        ),
        ClassDef(
            lineno=11,
            col_offset=0,
            end_lineno=25,
            end_col_offset=83,
            name='odoo_resolver',
            bases=[
                Attribute(
                    lineno=11,
                    col_offset=20,
                    end_lineno=11,
                    end_col_offset=34,
                    value=Name(lineno=11, col_offset=20, end_lineno=11, end_col_offset=25, id='etree', ctx=Load()),
                    attr='Resolver',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Expr(
                    lineno=12,
                    col_offset=4,
                    end_lineno=15,
                    end_col_offset=7,
                    value=Constant(lineno=12, col_offset=4, end_lineno=15, end_col_offset=7, value='Odoo specific file resolver that can be added to the XML Parser.\n\n    It will search filenames in the ir.attachments\n    ', kind=None),
                ),
                FunctionDef(
                    lineno=17,
                    col_offset=4,
                    end_lineno=19,
                    end_col_offset=22,
                    name='__init__',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=17, col_offset=17, end_lineno=17, end_col_offset=21, arg='self', annotation=None, type_comment=None),
                            arg(lineno=17, col_offset=23, end_lineno=17, end_col_offset=26, arg='env', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=18,
                            col_offset=8,
                            end_lineno=18,
                            end_col_offset=26,
                            value=Call(
                                lineno=18,
                                col_offset=8,
                                end_lineno=18,
                                end_col_offset=26,
                                func=Attribute(
                                    lineno=18,
                                    col_offset=8,
                                    end_lineno=18,
                                    end_col_offset=24,
                                    value=Call(
                                        lineno=18,
                                        col_offset=8,
                                        end_lineno=18,
                                        end_col_offset=15,
                                        func=Name(lineno=18, col_offset=8, end_lineno=18, end_col_offset=13, id='super', ctx=Load()),
                                        args=[],
                                        keywords=[],
                                    ),
                                    attr='__init__',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=19,
                            col_offset=8,
                            end_lineno=19,
                            end_col_offset=22,
                            targets=[
                                Attribute(
                                    lineno=19,
                                    col_offset=8,
                                    end_lineno=19,
                                    end_col_offset=16,
                                    value=Name(lineno=19, col_offset=8, end_lineno=19, end_col_offset=12, id='self', ctx=Load()),
                                    attr='env',
                                    ctx=Store(),
                                ),
                            ],
                            value=Name(lineno=19, col_offset=19, end_lineno=19, end_col_offset=22, id='env', ctx=Load()),
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=21,
                    col_offset=4,
                    end_lineno=25,
                    end_col_offset=83,
                    name='resolve',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=21, col_offset=16, end_lineno=21, end_col_offset=20, arg='self', annotation=None, type_comment=None),
                            arg(lineno=21, col_offset=22, end_lineno=21, end_col_offset=25, arg='url', annotation=None, type_comment=None),
                            arg(lineno=21, col_offset=27, end_lineno=21, end_col_offset=29, arg='id', annotation=None, type_comment=None),
                            arg(lineno=21, col_offset=31, end_lineno=21, end_col_offset=38, arg='context', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=22,
                            col_offset=8,
                            end_lineno=22,
                            end_col_offset=78,
                            value=Constant(lineno=22, col_offset=8, end_lineno=22, end_col_offset=78, value='Search url in ``ir.attachment`` and return the resolved content.', kind=None),
                        ),
                        Assign(
                            lineno=23,
                            col_offset=8,
                            end_lineno=23,
                            end_col_offset=75,
                            targets=[Name(lineno=23, col_offset=8, end_lineno=23, end_col_offset=18, id='attachment', ctx=Store())],
                            value=Call(
                                lineno=23,
                                col_offset=21,
                                end_lineno=23,
                                end_col_offset=75,
                                func=Attribute(
                                    lineno=23,
                                    col_offset=21,
                                    end_lineno=23,
                                    end_col_offset=53,
                                    value=Subscript(
                                        lineno=23,
                                        col_offset=21,
                                        end_lineno=23,
                                        end_col_offset=46,
                                        value=Attribute(
                                            lineno=23,
                                            col_offset=21,
                                            end_lineno=23,
                                            end_col_offset=29,
                                            value=Name(lineno=23, col_offset=21, end_lineno=23, end_col_offset=25, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=23, col_offset=30, end_lineno=23, end_col_offset=45, value='ir.attachment', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='search',
                                    ctx=Load(),
                                ),
                                args=[
                                    List(
                                        lineno=23,
                                        col_offset=54,
                                        end_lineno=23,
                                        end_col_offset=74,
                                        elts=[
                                            Tuple(
                                                lineno=23,
                                                col_offset=55,
                                                end_lineno=23,
                                                end_col_offset=73,
                                                elts=[
                                                    Constant(lineno=23, col_offset=56, end_lineno=23, end_col_offset=62, value='name', kind=None),
                                                    Constant(lineno=23, col_offset=64, end_lineno=23, end_col_offset=67, value='=', kind=None),
                                                    Name(lineno=23, col_offset=69, end_lineno=23, end_col_offset=72, id='url', ctx=Load()),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        If(
                            lineno=24,
                            col_offset=8,
                            end_lineno=25,
                            end_col_offset=83,
                            test=Name(lineno=24, col_offset=11, end_lineno=24, end_col_offset=21, id='attachment', ctx=Load()),
                            body=[
                                Return(
                                    lineno=25,
                                    col_offset=12,
                                    end_lineno=25,
                                    end_col_offset=83,
                                    value=Call(
                                        lineno=25,
                                        col_offset=19,
                                        end_lineno=25,
                                        end_col_offset=83,
                                        func=Attribute(
                                            lineno=25,
                                            col_offset=19,
                                            end_lineno=25,
                                            end_col_offset=38,
                                            value=Name(lineno=25, col_offset=19, end_lineno=25, end_col_offset=23, id='self', ctx=Load()),
                                            attr='resolve_string',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Call(
                                                lineno=25,
                                                col_offset=39,
                                                end_lineno=25,
                                                end_col_offset=73,
                                                func=Attribute(
                                                    lineno=25,
                                                    col_offset=39,
                                                    end_lineno=25,
                                                    end_col_offset=55,
                                                    value=Name(lineno=25, col_offset=39, end_lineno=25, end_col_offset=45, id='base64', ctx=Load()),
                                                    attr='b64decode',
                                                    ctx=Load(),
                                                ),
                                                args=[
                                                    Attribute(
                                                        lineno=25,
                                                        col_offset=56,
                                                        end_lineno=25,
                                                        end_col_offset=72,
                                                        value=Name(lineno=25, col_offset=56, end_lineno=25, end_col_offset=66, id='attachment', ctx=Load()),
                                                        attr='datas',
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                keywords=[],
                                            ),
                                            Name(lineno=25, col_offset=75, end_lineno=25, end_col_offset=82, id='context', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                ),
                            ],
                            orelse=[],
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
        FunctionDef(
            lineno=28,
            col_offset=0,
            end_lineno=53,
            end_col_offset=72,
            name='_check_with_xsd',
            args=arguments(
                posonlyargs=[],
                args=[
                    arg(lineno=28, col_offset=20, end_lineno=28, end_col_offset=31, arg='tree_or_str', annotation=None, type_comment=None),
                    arg(lineno=28, col_offset=33, end_lineno=28, end_col_offset=39, arg='stream', annotation=None, type_comment=None),
                    arg(lineno=28, col_offset=41, end_lineno=28, end_col_offset=44, arg='env', annotation=None, type_comment=None),
                ],
                vararg=None,
                kwonlyargs=[],
                kw_defaults=[],
                kwarg=None,
                defaults=[Constant(lineno=28, col_offset=45, end_lineno=28, end_col_offset=49, value=None, kind=None)],
            ),
            body=[
                Expr(
                    lineno=29,
                    col_offset=4,
                    end_lineno=38,
                    end_col_offset=7,
                    value=Constant(lineno=29, col_offset=4, end_lineno=38, end_col_offset=7, value='Check an XML against an XSD schema.\n\n    This will raise a UserError if the XML file is not valid according to the\n    XSD file.\n    :param tree_or_str (etree, str): representation of the tree to be checked\n    :param stream (io.IOBase, str): the byte stream used to build the XSD schema.\n        If env is given, it can also be the name of an attachment in the filestore\n    :param env (odoo.api.Environment): If it is given, it enables resolving the\n        imports of the schema in the filestore with ir.attachments.\n    ', kind=None),
                ),
                If(
                    lineno=39,
                    col_offset=4,
                    end_lineno=40,
                    end_col_offset=51,
                    test=UnaryOp(
                        lineno=39,
                        col_offset=7,
                        end_lineno=39,
                        end_col_offset=50,
                        op=Not(),
                        operand=Call(
                            lineno=39,
                            col_offset=11,
                            end_lineno=39,
                            end_col_offset=50,
                            func=Name(lineno=39, col_offset=11, end_lineno=39, end_col_offset=21, id='isinstance', ctx=Load()),
                            args=[
                                Name(lineno=39, col_offset=22, end_lineno=39, end_col_offset=33, id='tree_or_str', ctx=Load()),
                                Attribute(
                                    lineno=39,
                                    col_offset=35,
                                    end_lineno=39,
                                    end_col_offset=49,
                                    value=Name(lineno=39, col_offset=35, end_lineno=39, end_col_offset=40, id='etree', ctx=Load()),
                                    attr='_Element',
                                    ctx=Load(),
                                ),
                            ],
                            keywords=[],
                        ),
                    ),
                    body=[
                        Assign(
                            lineno=40,
                            col_offset=8,
                            end_lineno=40,
                            end_col_offset=51,
                            targets=[Name(lineno=40, col_offset=8, end_lineno=40, end_col_offset=19, id='tree_or_str', ctx=Store())],
                            value=Call(
                                lineno=40,
                                col_offset=22,
                                end_lineno=40,
                                end_col_offset=51,
                                func=Attribute(
                                    lineno=40,
                                    col_offset=22,
                                    end_lineno=40,
                                    end_col_offset=38,
                                    value=Name(lineno=40, col_offset=22, end_lineno=40, end_col_offset=27, id='etree', ctx=Load()),
                                    attr='fromstring',
                                    ctx=Load(),
                                ),
                                args=[Name(lineno=40, col_offset=39, end_lineno=40, end_col_offset=50, id='tree_or_str', ctx=Load())],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                    ],
                    orelse=[],
                ),
                Assign(
                    lineno=41,
                    col_offset=4,
                    end_lineno=41,
                    end_col_offset=30,
                    targets=[Name(lineno=41, col_offset=4, end_lineno=41, end_col_offset=10, id='parser', ctx=Store())],
                    value=Call(
                        lineno=41,
                        col_offset=13,
                        end_lineno=41,
                        end_col_offset=30,
                        func=Attribute(
                            lineno=41,
                            col_offset=13,
                            end_lineno=41,
                            end_col_offset=28,
                            value=Name(lineno=41, col_offset=13, end_lineno=41, end_col_offset=18, id='etree', ctx=Load()),
                            attr='XMLParser',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                If(
                    lineno=42,
                    col_offset=4,
                    end_lineno=48,
                    end_col_offset=64,
                    test=Name(lineno=42, col_offset=7, end_lineno=42, end_col_offset=10, id='env', ctx=Load()),
                    body=[
                        Expr(
                            lineno=43,
                            col_offset=8,
                            end_lineno=43,
                            end_col_offset=48,
                            value=Call(
                                lineno=43,
                                col_offset=8,
                                end_lineno=43,
                                end_col_offset=48,
                                func=Attribute(
                                    lineno=43,
                                    col_offset=8,
                                    end_lineno=43,
                                    end_col_offset=28,
                                    value=Attribute(
                                        lineno=43,
                                        col_offset=8,
                                        end_lineno=43,
                                        end_col_offset=24,
                                        value=Name(lineno=43, col_offset=8, end_lineno=43, end_col_offset=14, id='parser', ctx=Load()),
                                        attr='resolvers',
                                        ctx=Load(),
                                    ),
                                    attr='add',
                                    ctx=Load(),
                                ),
                                args=[
                                    Call(
                                        lineno=43,
                                        col_offset=29,
                                        end_lineno=43,
                                        end_col_offset=47,
                                        func=Name(lineno=43, col_offset=29, end_lineno=43, end_col_offset=42, id='odoo_resolver', ctx=Load()),
                                        args=[Name(lineno=43, col_offset=43, end_lineno=43, end_col_offset=46, id='env', ctx=Load())],
                                        keywords=[],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        If(
                            lineno=44,
                            col_offset=8,
                            end_lineno=48,
                            end_col_offset=64,
                            test=BoolOp(
                                lineno=44,
                                col_offset=11,
                                end_lineno=44,
                                end_col_offset=62,
                                op=And(),
                                values=[
                                    Call(
                                        lineno=44,
                                        col_offset=11,
                                        end_lineno=44,
                                        end_col_offset=34,
                                        func=Name(lineno=44, col_offset=11, end_lineno=44, end_col_offset=21, id='isinstance', ctx=Load()),
                                        args=[
                                            Name(lineno=44, col_offset=22, end_lineno=44, end_col_offset=28, id='stream', ctx=Load()),
                                            Name(lineno=44, col_offset=30, end_lineno=44, end_col_offset=33, id='str', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    Call(
                                        lineno=44,
                                        col_offset=39,
                                        end_lineno=44,
                                        end_col_offset=62,
                                        func=Attribute(
                                            lineno=44,
                                            col_offset=39,
                                            end_lineno=44,
                                            end_col_offset=54,
                                            value=Name(lineno=44, col_offset=39, end_lineno=44, end_col_offset=45, id='stream', ctx=Load()),
                                            attr='endswith',
                                            ctx=Load(),
                                        ),
                                        args=[Constant(lineno=44, col_offset=55, end_lineno=44, end_col_offset=61, value='.xsd', kind=None)],
                                        keywords=[],
                                    ),
                                ],
                            ),
                            body=[
                                Assign(
                                    lineno=45,
                                    col_offset=12,
                                    end_lineno=45,
                                    end_col_offset=77,
                                    targets=[Name(lineno=45, col_offset=12, end_lineno=45, end_col_offset=22, id='attachment', ctx=Store())],
                                    value=Call(
                                        lineno=45,
                                        col_offset=25,
                                        end_lineno=45,
                                        end_col_offset=77,
                                        func=Attribute(
                                            lineno=45,
                                            col_offset=25,
                                            end_lineno=45,
                                            end_col_offset=52,
                                            value=Subscript(
                                                lineno=45,
                                                col_offset=25,
                                                end_lineno=45,
                                                end_col_offset=45,
                                                value=Name(lineno=45, col_offset=25, end_lineno=45, end_col_offset=28, id='env', ctx=Load()),
                                                slice=Constant(lineno=45, col_offset=29, end_lineno=45, end_col_offset=44, value='ir.attachment', kind=None),
                                                ctx=Load(),
                                            ),
                                            attr='search',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            List(
                                                lineno=45,
                                                col_offset=53,
                                                end_lineno=45,
                                                end_col_offset=76,
                                                elts=[
                                                    Tuple(
                                                        lineno=45,
                                                        col_offset=54,
                                                        end_lineno=45,
                                                        end_col_offset=75,
                                                        elts=[
                                                            Constant(lineno=45, col_offset=55, end_lineno=45, end_col_offset=61, value='name', kind=None),
                                                            Constant(lineno=45, col_offset=63, end_lineno=45, end_col_offset=66, value='=', kind=None),
                                                            Name(lineno=45, col_offset=68, end_lineno=45, end_col_offset=74, id='stream', ctx=Load()),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                    type_comment=None,
                                ),
                                If(
                                    lineno=46,
                                    col_offset=12,
                                    end_lineno=47,
                                    end_col_offset=41,
                                    test=UnaryOp(
                                        lineno=46,
                                        col_offset=15,
                                        end_lineno=46,
                                        end_col_offset=29,
                                        op=Not(),
                                        operand=Name(lineno=46, col_offset=19, end_lineno=46, end_col_offset=29, id='attachment', ctx=Load()),
                                    ),
                                    body=[
                                        Raise(
                                            lineno=47,
                                            col_offset=16,
                                            end_lineno=47,
                                            end_col_offset=41,
                                            exc=Call(
                                                lineno=47,
                                                col_offset=22,
                                                end_lineno=47,
                                                end_col_offset=41,
                                                func=Name(lineno=47, col_offset=22, end_lineno=47, end_col_offset=39, id='FileNotFoundError', ctx=Load()),
                                                args=[],
                                                keywords=[],
                                            ),
                                            cause=None,
                                        ),
                                    ],
                                    orelse=[],
                                ),
                                Assign(
                                    lineno=48,
                                    col_offset=12,
                                    end_lineno=48,
                                    end_col_offset=64,
                                    targets=[Name(lineno=48, col_offset=12, end_lineno=48, end_col_offset=18, id='stream', ctx=Store())],
                                    value=Call(
                                        lineno=48,
                                        col_offset=21,
                                        end_lineno=48,
                                        end_col_offset=64,
                                        func=Name(lineno=48, col_offset=21, end_lineno=48, end_col_offset=28, id='BytesIO', ctx=Load()),
                                        args=[
                                            Call(
                                                lineno=48,
                                                col_offset=29,
                                                end_lineno=48,
                                                end_col_offset=63,
                                                func=Attribute(
                                                    lineno=48,
                                                    col_offset=29,
                                                    end_lineno=48,
                                                    end_col_offset=45,
                                                    value=Name(lineno=48, col_offset=29, end_lineno=48, end_col_offset=35, id='base64', ctx=Load()),
                                                    attr='b64decode',
                                                    ctx=Load(),
                                                ),
                                                args=[
                                                    Attribute(
                                                        lineno=48,
                                                        col_offset=46,
                                                        end_lineno=48,
                                                        end_col_offset=62,
                                                        value=Name(lineno=48, col_offset=46, end_lineno=48, end_col_offset=56, id='attachment', ctx=Load()),
                                                        attr='datas',
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                keywords=[],
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[],
                        ),
                    ],
                    orelse=[],
                ),
                Assign(
                    lineno=49,
                    col_offset=4,
                    end_lineno=49,
                    end_col_offset=68,
                    targets=[Name(lineno=49, col_offset=4, end_lineno=49, end_col_offset=14, id='xsd_schema', ctx=Store())],
                    value=Call(
                        lineno=49,
                        col_offset=17,
                        end_lineno=49,
                        end_col_offset=68,
                        func=Attribute(
                            lineno=49,
                            col_offset=17,
                            end_lineno=49,
                            end_col_offset=32,
                            value=Name(lineno=49, col_offset=17, end_lineno=49, end_col_offset=22, id='etree', ctx=Load()),
                            attr='XMLSchema',
                            ctx=Load(),
                        ),
                        args=[
                            Call(
                                lineno=49,
                                col_offset=33,
                                end_lineno=49,
                                end_col_offset=67,
                                func=Attribute(
                                    lineno=49,
                                    col_offset=33,
                                    end_lineno=49,
                                    end_col_offset=44,
                                    value=Name(lineno=49, col_offset=33, end_lineno=49, end_col_offset=38, id='etree', ctx=Load()),
                                    attr='parse',
                                    ctx=Load(),
                                ),
                                args=[Name(lineno=49, col_offset=45, end_lineno=49, end_col_offset=51, id='stream', ctx=Load())],
                                keywords=[
                                    keyword(
                                        lineno=49,
                                        col_offset=53,
                                        end_lineno=49,
                                        end_col_offset=66,
                                        arg='parser',
                                        value=Name(lineno=49, col_offset=60, end_lineno=49, end_col_offset=66, id='parser', ctx=Load()),
                                    ),
                                ],
                            ),
                        ],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Try(
                    lineno=50,
                    col_offset=4,
                    end_lineno=53,
                    end_col_offset=72,
                    body=[
                        Expr(
                            lineno=51,
                            col_offset=8,
                            end_lineno=51,
                            end_col_offset=43,
                            value=Call(
                                lineno=51,
                                col_offset=8,
                                end_lineno=51,
                                end_col_offset=43,
                                func=Attribute(
                                    lineno=51,
                                    col_offset=8,
                                    end_lineno=51,
                                    end_col_offset=30,
                                    value=Name(lineno=51, col_offset=8, end_lineno=51, end_col_offset=18, id='xsd_schema', ctx=Load()),
                                    attr='assertValid',
                                    ctx=Load(),
                                ),
                                args=[Name(lineno=51, col_offset=31, end_lineno=51, end_col_offset=42, id='tree_or_str', ctx=Load())],
                                keywords=[],
                            ),
                        ),
                    ],
                    handlers=[
                        ExceptHandler(
                            lineno=52,
                            col_offset=4,
                            end_lineno=53,
                            end_col_offset=72,
                            type=Attribute(
                                lineno=52,
                                col_offset=11,
                                end_lineno=52,
                                end_col_offset=32,
                                value=Name(lineno=52, col_offset=11, end_lineno=52, end_col_offset=16, id='etree', ctx=Load()),
                                attr='DocumentInvalid',
                                ctx=Load(),
                            ),
                            name='xml_errors',
                            body=[
                                Raise(
                                    lineno=53,
                                    col_offset=8,
                                    end_lineno=53,
                                    end_col_offset=72,
                                    exc=Call(
                                        lineno=53,
                                        col_offset=14,
                                        end_lineno=53,
                                        end_col_offset=72,
                                        func=Name(lineno=53, col_offset=14, end_lineno=53, end_col_offset=23, id='UserError', ctx=Load()),
                                        args=[
                                            Call(
                                                lineno=53,
                                                col_offset=24,
                                                end_lineno=53,
                                                end_col_offset=71,
                                                func=Attribute(
                                                    lineno=53,
                                                    col_offset=24,
                                                    end_lineno=53,
                                                    end_col_offset=33,
                                                    value=Constant(lineno=53, col_offset=24, end_lineno=53, end_col_offset=28, value='\n', kind=None),
                                                    attr='join',
                                                    ctx=Load(),
                                                ),
                                                args=[
                                                    GeneratorExp(
                                                        lineno=53,
                                                        col_offset=33,
                                                        end_lineno=53,
                                                        end_col_offset=71,
                                                        elt=Call(
                                                            lineno=53,
                                                            col_offset=34,
                                                            end_lineno=53,
                                                            end_col_offset=40,
                                                            func=Name(lineno=53, col_offset=34, end_lineno=53, end_col_offset=37, id='str', ctx=Load()),
                                                            args=[Name(lineno=53, col_offset=38, end_lineno=53, end_col_offset=39, id='e', ctx=Load())],
                                                            keywords=[],
                                                        ),
                                                        generators=[
                                                            comprehension(
                                                                target=Name(lineno=53, col_offset=45, end_lineno=53, end_col_offset=46, id='e', ctx=Store()),
                                                                iter=Attribute(
                                                                    lineno=53,
                                                                    col_offset=50,
                                                                    end_lineno=53,
                                                                    end_col_offset=70,
                                                                    value=Name(lineno=53, col_offset=50, end_lineno=53, end_col_offset=60, id='xml_errors', ctx=Load()),
                                                                    attr='error_log',
                                                                    ctx=Load(),
                                                                ),
                                                                ifs=[],
                                                                is_async=0,
                                                            ),
                                                        ],
                                                    ),
                                                ],
                                                keywords=[],
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                    cause=None,
                                ),
                            ],
                        ),
                    ],
                    orelse=[],
                    finalbody=[],
                ),
            ],
            decorator_list=[],
            returns=None,
            type_comment=None,
        ),
        FunctionDef(
            lineno=56,
            col_offset=0,
            end_lineno=74,
            end_col_offset=14,
            name='create_xml_node_chain',
            args=arguments(
                posonlyargs=[],
                args=[
                    arg(lineno=56, col_offset=26, end_lineno=56, end_col_offset=43, arg='first_parent_node', annotation=None, type_comment=None),
                    arg(lineno=56, col_offset=45, end_lineno=56, end_col_offset=55, arg='nodes_list', annotation=None, type_comment=None),
                    arg(lineno=56, col_offset=57, end_lineno=56, end_col_offset=72, arg='last_node_value', annotation=None, type_comment=None),
                ],
                vararg=None,
                kwonlyargs=[],
                kw_defaults=[],
                kwarg=None,
                defaults=[Constant(lineno=56, col_offset=73, end_lineno=56, end_col_offset=77, value=None, kind=None)],
            ),
            body=[
                Expr(
                    lineno=57,
                    col_offset=4,
                    end_lineno=65,
                    end_col_offset=7,
                    value=Constant(lineno=57, col_offset=4, end_lineno=65, end_col_offset=7, value="Generate a hierarchical chain of nodes.\n\n    Each new node being the child of the previous one based on the tags contained\n    in `nodes_list`, under the given node `first_parent_node`.\n    :param first_parent_node (etree._Element): parent of the created tree/chain\n    :param nodes_list (iterable<str>): tag names to be created\n    :param last_node_value (str): if specified, set the last node's text to this value\n    :returns (list<etree._Element>): the list of created nodes\n    ", kind=None),
                ),
                Assign(
                    lineno=66,
                    col_offset=4,
                    end_lineno=66,
                    end_col_offset=12,
                    targets=[Name(lineno=66, col_offset=4, end_lineno=66, end_col_offset=7, id='res', ctx=Store())],
                    value=List(lineno=66, col_offset=10, end_lineno=66, end_col_offset=12, elts=[], ctx=Load()),
                    type_comment=None,
                ),
                Assign(
                    lineno=67,
                    col_offset=4,
                    end_lineno=67,
                    end_col_offset=36,
                    targets=[Name(lineno=67, col_offset=4, end_lineno=67, end_col_offset=16, id='current_node', ctx=Store())],
                    value=Name(lineno=67, col_offset=19, end_lineno=67, end_col_offset=36, id='first_parent_node', ctx=Load()),
                    type_comment=None,
                ),
                For(
                    lineno=68,
                    col_offset=4,
                    end_lineno=70,
                    end_col_offset=32,
                    target=Name(lineno=68, col_offset=8, end_lineno=68, end_col_offset=11, id='tag', ctx=Store()),
                    iter=Name(lineno=68, col_offset=15, end_lineno=68, end_col_offset=25, id='nodes_list', ctx=Load()),
                    body=[
                        Assign(
                            lineno=69,
                            col_offset=8,
                            end_lineno=69,
                            end_col_offset=58,
                            targets=[Name(lineno=69, col_offset=8, end_lineno=69, end_col_offset=20, id='current_node', ctx=Store())],
                            value=Call(
                                lineno=69,
                                col_offset=23,
                                end_lineno=69,
                                end_col_offset=58,
                                func=Attribute(
                                    lineno=69,
                                    col_offset=23,
                                    end_lineno=69,
                                    end_col_offset=39,
                                    value=Name(lineno=69, col_offset=23, end_lineno=69, end_col_offset=28, id='etree', ctx=Load()),
                                    attr='SubElement',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=69, col_offset=40, end_lineno=69, end_col_offset=52, id='current_node', ctx=Load()),
                                    Name(lineno=69, col_offset=54, end_lineno=69, end_col_offset=57, id='tag', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=70,
                            col_offset=8,
                            end_lineno=70,
                            end_col_offset=32,
                            value=Call(
                                lineno=70,
                                col_offset=8,
                                end_lineno=70,
                                end_col_offset=32,
                                func=Attribute(
                                    lineno=70,
                                    col_offset=8,
                                    end_lineno=70,
                                    end_col_offset=18,
                                    value=Name(lineno=70, col_offset=8, end_lineno=70, end_col_offset=11, id='res', ctx=Load()),
                                    attr='append',
                                    ctx=Load(),
                                ),
                                args=[Name(lineno=70, col_offset=19, end_lineno=70, end_col_offset=31, id='current_node', ctx=Load())],
                                keywords=[],
                            ),
                        ),
                    ],
                    orelse=[],
                    type_comment=None,
                ),
                If(
                    lineno=72,
                    col_offset=4,
                    end_lineno=73,
                    end_col_offset=43,
                    test=Compare(
                        lineno=72,
                        col_offset=7,
                        end_lineno=72,
                        end_col_offset=34,
                        left=Name(lineno=72, col_offset=7, end_lineno=72, end_col_offset=22, id='last_node_value', ctx=Load()),
                        ops=[IsNot()],
                        comparators=[Constant(lineno=72, col_offset=30, end_lineno=72, end_col_offset=34, value=None, kind=None)],
                    ),
                    body=[
                        Assign(
                            lineno=73,
                            col_offset=8,
                            end_lineno=73,
                            end_col_offset=43,
                            targets=[
                                Attribute(
                                    lineno=73,
                                    col_offset=8,
                                    end_lineno=73,
                                    end_col_offset=25,
                                    value=Name(lineno=73, col_offset=8, end_lineno=73, end_col_offset=20, id='current_node', ctx=Load()),
                                    attr='text',
                                    ctx=Store(),
                                ),
                            ],
                            value=Name(lineno=73, col_offset=28, end_lineno=73, end_col_offset=43, id='last_node_value', ctx=Load()),
                            type_comment=None,
                        ),
                    ],
                    orelse=[],
                ),
                Return(
                    lineno=74,
                    col_offset=4,
                    end_lineno=74,
                    end_col_offset=14,
                    value=Name(lineno=74, col_offset=11, end_lineno=74, end_col_offset=14, id='res', ctx=Load()),
                ),
            ],
            decorator_list=[],
            returns=None,
            type_comment=None,
        ),
        FunctionDef(
            lineno=77,
            col_offset=0,
            end_lineno=85,
            end_col_offset=73,
            name='create_xml_node',
            args=arguments(
                posonlyargs=[],
                args=[
                    arg(lineno=77, col_offset=20, end_lineno=77, end_col_offset=31, arg='parent_node', annotation=None, type_comment=None),
                    arg(lineno=77, col_offset=33, end_lineno=77, end_col_offset=42, arg='node_name', annotation=None, type_comment=None),
                    arg(lineno=77, col_offset=44, end_lineno=77, end_col_offset=54, arg='node_value', annotation=None, type_comment=None),
                ],
                vararg=None,
                kwonlyargs=[],
                kw_defaults=[],
                kwarg=None,
                defaults=[Constant(lineno=77, col_offset=55, end_lineno=77, end_col_offset=59, value=None, kind=None)],
            ),
            body=[
                Expr(
                    lineno=78,
                    col_offset=4,
                    end_lineno=84,
                    end_col_offset=7,
                    value=Constant(lineno=78, col_offset=4, end_lineno=84, end_col_offset=7, value='Create a new node.\n\n    :param parent_node (etree._Element): parent of the created node\n    :param node_name (str): name of the created node\n    :param node_value (str): value of the created node (optional)\n    :returns (etree._Element):\n    ', kind=None),
                ),
                Return(
                    lineno=85,
                    col_offset=4,
                    end_lineno=85,
                    end_col_offset=73,
                    value=Subscript(
                        lineno=85,
                        col_offset=11,
                        end_lineno=85,
                        end_col_offset=73,
                        value=Call(
                            lineno=85,
                            col_offset=11,
                            end_lineno=85,
                            end_col_offset=70,
                            func=Name(lineno=85, col_offset=11, end_lineno=85, end_col_offset=32, id='create_xml_node_chain', ctx=Load()),
                            args=[
                                Name(lineno=85, col_offset=33, end_lineno=85, end_col_offset=44, id='parent_node', ctx=Load()),
                                List(
                                    lineno=85,
                                    col_offset=46,
                                    end_lineno=85,
                                    end_col_offset=57,
                                    elts=[Name(lineno=85, col_offset=47, end_lineno=85, end_col_offset=56, id='node_name', ctx=Load())],
                                    ctx=Load(),
                                ),
                                Name(lineno=85, col_offset=59, end_lineno=85, end_col_offset=69, id='node_value', ctx=Load()),
                            ],
                            keywords=[],
                        ),
                        slice=Constant(lineno=85, col_offset=71, end_lineno=85, end_col_offset=72, value=0, kind=None),
                        ctx=Load(),
                    ),
                ),
            ],
            decorator_list=[],
            returns=None,
            type_comment=None,
        ),
    ],
    type_ignores=[],
)
