Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=31,
            module='odoo',
            names=[
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=10,
            end_col_offset=79,
            name='Company',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=14,
                    end_lineno=7,
                    end_col_offset=26,
                    value=Name(lineno=7, col_offset=14, end_lineno=7, end_col_offset=20, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=28,
                    targets=[Name(lineno=8, col_offset=4, end_lineno=8, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=8, col_offset=15, end_lineno=8, end_col_offset=28, value='res.company', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=10,
                    col_offset=4,
                    end_lineno=10,
                    end_col_offset=79,
                    targets=[Name(lineno=10, col_offset=4, end_lineno=10, end_col_offset=24, id='invoice_is_snailmail', ctx=Store())],
                    value=Call(
                        lineno=10,
                        col_offset=27,
                        end_lineno=10,
                        end_col_offset=79,
                        func=Attribute(
                            lineno=10,
                            col_offset=27,
                            end_lineno=10,
                            end_col_offset=41,
                            value=Name(lineno=10, col_offset=27, end_lineno=10, end_col_offset=33, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=10,
                                col_offset=42,
                                end_lineno=10,
                                end_col_offset=63,
                                arg='string',
                                value=Constant(lineno=10, col_offset=49, end_lineno=10, end_col_offset=63, value='Send by Post', kind=None),
                            ),
                            keyword(
                                lineno=10,
                                col_offset=65,
                                end_lineno=10,
                                end_col_offset=78,
                                arg='default',
                                value=Constant(lineno=10, col_offset=73, end_lineno=10, end_col_offset=78, value=False, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
