Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=31,
            module='odoo',
            names=[
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=14,
            end_col_offset=96,
            name='EventRegistration',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=24,
                    end_lineno=7,
                    end_col_offset=36,
                    value=Name(lineno=7, col_offset=24, end_lineno=7, end_col_offset=30, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=32,
                    targets=[Name(lineno=8, col_offset=4, end_lineno=8, end_col_offset=9, id='_name', ctx=Store())],
                    value=Constant(lineno=8, col_offset=12, end_lineno=8, end_col_offset=32, value='event.registration', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=9,
                    col_offset=4,
                    end_lineno=9,
                    end_col_offset=37,
                    targets=[Name(lineno=9, col_offset=4, end_lineno=9, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=List(
                        lineno=9,
                        col_offset=15,
                        end_lineno=9,
                        end_col_offset=37,
                        elts=[Constant(lineno=9, col_offset=16, end_lineno=9, end_col_offset=36, value='event.registration', kind=None)],
                        ctx=Load(),
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=11,
                    col_offset=4,
                    end_lineno=11,
                    end_col_offset=90,
                    targets=[Name(lineno=11, col_offset=4, end_lineno=11, end_col_offset=14, id='visitor_id', ctx=Store())],
                    value=Call(
                        lineno=11,
                        col_offset=17,
                        end_lineno=11,
                        end_col_offset=90,
                        func=Attribute(
                            lineno=11,
                            col_offset=17,
                            end_lineno=11,
                            end_col_offset=32,
                            value=Name(lineno=11, col_offset=17, end_lineno=11, end_col_offset=23, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=11, col_offset=33, end_lineno=11, end_col_offset=50, value='website.visitor', kind=None)],
                        keywords=[
                            keyword(
                                lineno=11,
                                col_offset=52,
                                end_lineno=11,
                                end_col_offset=68,
                                arg='string',
                                value=Constant(lineno=11, col_offset=59, end_lineno=11, end_col_offset=68, value='Visitor', kind=None),
                            ),
                            keyword(
                                lineno=11,
                                col_offset=70,
                                end_lineno=11,
                                end_col_offset=89,
                                arg='ondelete',
                                value=Constant(lineno=11, col_offset=79, end_lineno=11, end_col_offset=89, value='set null', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=13,
                    col_offset=4,
                    end_lineno=14,
                    end_col_offset=96,
                    name='_get_website_registration_allowed_fields',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=13, col_offset=49, end_lineno=13, end_col_offset=53, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Return(
                            lineno=14,
                            col_offset=8,
                            end_lineno=14,
                            end_col_offset=96,
                            value=Set(
                                lineno=14,
                                col_offset=15,
                                end_lineno=14,
                                end_col_offset=96,
                                elts=[
                                    Constant(lineno=14, col_offset=16, end_lineno=14, end_col_offset=22, value='name', kind=None),
                                    Constant(lineno=14, col_offset=24, end_lineno=14, end_col_offset=31, value='phone', kind=None),
                                    Constant(lineno=14, col_offset=33, end_lineno=14, end_col_offset=40, value='email', kind=None),
                                    Constant(lineno=14, col_offset=42, end_lineno=14, end_col_offset=50, value='mobile', kind=None),
                                    Constant(lineno=14, col_offset=52, end_lineno=14, end_col_offset=62, value='event_id', kind=None),
                                    Constant(lineno=14, col_offset=64, end_lineno=14, end_col_offset=76, value='partner_id', kind=None),
                                    Constant(lineno=14, col_offset=78, end_lineno=14, end_col_offset=95, value='event_ticket_id', kind=None),
                                ],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
