Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=31,
            module='odoo.tests',
            names=[alias(name='BaseCase', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=5,
            col_offset=0,
            end_lineno=5,
            end_col_offset=60,
            module='odoo.tools.rendering_tools',
            names=[alias(name='parse_inline_template', asname=None)],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=18,
            end_col_offset=80,
            name='TestParseInlineTemplate',
            bases=[Name(lineno=7, col_offset=30, end_lineno=7, end_col_offset=38, id='BaseCase', ctx=Load())],
            keywords=[],
            body=[
                FunctionDef(
                    lineno=8,
                    col_offset=4,
                    end_lineno=10,
                    end_col_offset=70,
                    name='test_no_expression',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=8, col_offset=27, end_lineno=8, end_col_offset=31, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=9,
                            col_offset=8,
                            end_lineno=9,
                            end_col_offset=22,
                            targets=[Name(lineno=9, col_offset=8, end_lineno=9, end_col_offset=12, id='text', ctx=Store())],
                            value=Constant(lineno=9, col_offset=15, end_lineno=9, end_col_offset=22, value='a b c', kind=None),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=10,
                            col_offset=8,
                            end_lineno=10,
                            end_col_offset=70,
                            value=Call(
                                lineno=10,
                                col_offset=8,
                                end_lineno=10,
                                end_col_offset=70,
                                func=Attribute(
                                    lineno=10,
                                    col_offset=8,
                                    end_lineno=10,
                                    end_col_offset=24,
                                    value=Name(lineno=10, col_offset=8, end_lineno=10, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Call(
                                        lineno=10,
                                        col_offset=25,
                                        end_lineno=10,
                                        end_col_offset=52,
                                        func=Name(lineno=10, col_offset=25, end_lineno=10, end_col_offset=46, id='parse_inline_template', ctx=Load()),
                                        args=[Name(lineno=10, col_offset=47, end_lineno=10, end_col_offset=51, id='text', ctx=Load())],
                                        keywords=[],
                                    ),
                                    List(
                                        lineno=10,
                                        col_offset=54,
                                        end_lineno=10,
                                        end_col_offset=69,
                                        elts=[
                                            Tuple(
                                                lineno=10,
                                                col_offset=55,
                                                end_lineno=10,
                                                end_col_offset=68,
                                                elts=[
                                                    Constant(lineno=10, col_offset=56, end_lineno=10, end_col_offset=63, value='a b c', kind=None),
                                                    Constant(lineno=10, col_offset=65, end_lineno=10, end_col_offset=67, value='', kind=None),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=12,
                    col_offset=4,
                    end_lineno=14,
                    end_col_offset=68,
                    name='test_expression1',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=12, col_offset=25, end_lineno=12, end_col_offset=29, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=13,
                            col_offset=8,
                            end_lineno=13,
                            end_col_offset=24,
                            targets=[Name(lineno=13, col_offset=8, end_lineno=13, end_col_offset=12, id='text', ctx=Store())],
                            value=Constant(lineno=13, col_offset=15, end_lineno=13, end_col_offset=24, value='a {{b}}', kind=None),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=14,
                            col_offset=8,
                            end_lineno=14,
                            end_col_offset=68,
                            value=Call(
                                lineno=14,
                                col_offset=8,
                                end_lineno=14,
                                end_col_offset=68,
                                func=Attribute(
                                    lineno=14,
                                    col_offset=8,
                                    end_lineno=14,
                                    end_col_offset=24,
                                    value=Name(lineno=14, col_offset=8, end_lineno=14, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Call(
                                        lineno=14,
                                        col_offset=25,
                                        end_lineno=14,
                                        end_col_offset=52,
                                        func=Name(lineno=14, col_offset=25, end_lineno=14, end_col_offset=46, id='parse_inline_template', ctx=Load()),
                                        args=[Name(lineno=14, col_offset=47, end_lineno=14, end_col_offset=51, id='text', ctx=Load())],
                                        keywords=[],
                                    ),
                                    List(
                                        lineno=14,
                                        col_offset=54,
                                        end_lineno=14,
                                        end_col_offset=67,
                                        elts=[
                                            Tuple(
                                                lineno=14,
                                                col_offset=55,
                                                end_lineno=14,
                                                end_col_offset=66,
                                                elts=[
                                                    Constant(lineno=14, col_offset=56, end_lineno=14, end_col_offset=60, value='a ', kind=None),
                                                    Constant(lineno=14, col_offset=62, end_lineno=14, end_col_offset=65, value='b', kind=None),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=16,
                    col_offset=4,
                    end_lineno=18,
                    end_col_offset=80,
                    name='test_expression2',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=16, col_offset=25, end_lineno=16, end_col_offset=29, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=17,
                            col_offset=8,
                            end_lineno=17,
                            end_col_offset=26,
                            targets=[Name(lineno=17, col_offset=8, end_lineno=17, end_col_offset=12, id='text', ctx=Store())],
                            value=Constant(lineno=17, col_offset=15, end_lineno=17, end_col_offset=26, value='a {{b}} c', kind=None),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=18,
                            col_offset=8,
                            end_lineno=18,
                            end_col_offset=80,
                            value=Call(
                                lineno=18,
                                col_offset=8,
                                end_lineno=18,
                                end_col_offset=80,
                                func=Attribute(
                                    lineno=18,
                                    col_offset=8,
                                    end_lineno=18,
                                    end_col_offset=24,
                                    value=Name(lineno=18, col_offset=8, end_lineno=18, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Call(
                                        lineno=18,
                                        col_offset=25,
                                        end_lineno=18,
                                        end_col_offset=52,
                                        func=Name(lineno=18, col_offset=25, end_lineno=18, end_col_offset=46, id='parse_inline_template', ctx=Load()),
                                        args=[Name(lineno=18, col_offset=47, end_lineno=18, end_col_offset=51, id='text', ctx=Load())],
                                        keywords=[],
                                    ),
                                    List(
                                        lineno=18,
                                        col_offset=54,
                                        end_lineno=18,
                                        end_col_offset=79,
                                        elts=[
                                            Tuple(
                                                lineno=18,
                                                col_offset=55,
                                                end_lineno=18,
                                                end_col_offset=66,
                                                elts=[
                                                    Constant(lineno=18, col_offset=56, end_lineno=18, end_col_offset=60, value='a ', kind=None),
                                                    Constant(lineno=18, col_offset=62, end_lineno=18, end_col_offset=65, value='b', kind=None),
                                                ],
                                                ctx=Load(),
                                            ),
                                            Tuple(
                                                lineno=18,
                                                col_offset=68,
                                                end_lineno=18,
                                                end_col_offset=78,
                                                elts=[
                                                    Constant(lineno=18, col_offset=69, end_lineno=18, end_col_offset=73, value=' c', kind=None),
                                                    Constant(lineno=18, col_offset=75, end_lineno=18, end_col_offset=77, value='', kind=None),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
