Module(
    body=[
        ImportFrom(
            lineno=3,
            col_offset=0,
            end_lineno=3,
            end_col_offset=36,
            module='odoo',
            names=[
                alias(name='api', asname=None),
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=6,
            col_offset=0,
            end_lineno=23,
            end_col_offset=44,
            name='ResConfigSettings',
            bases=[
                Attribute(
                    lineno=6,
                    col_offset=24,
                    end_lineno=6,
                    end_col_offset=45,
                    value=Name(lineno=6, col_offset=24, end_lineno=6, end_col_offset=30, id='models', ctx=Load()),
                    attr='TransientModel',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=7,
                    col_offset=4,
                    end_lineno=7,
                    end_col_offset=36,
                    targets=[Name(lineno=7, col_offset=4, end_lineno=7, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=7, col_offset=15, end_lineno=7, end_col_offset=36, value='res.config.settings', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=9,
                    col_offset=4,
                    end_lineno=9,
                    end_col_offset=133,
                    targets=[Name(lineno=9, col_offset=4, end_lineno=9, end_col_offset=15, id='sale_tax_id', ctx=Store())],
                    value=Call(
                        lineno=9,
                        col_offset=18,
                        end_lineno=9,
                        end_col_offset=133,
                        func=Attribute(
                            lineno=9,
                            col_offset=18,
                            end_lineno=9,
                            end_col_offset=33,
                            value=Name(lineno=9, col_offset=18, end_lineno=9, end_col_offset=24, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=9, col_offset=34, end_lineno=9, end_col_offset=47, value='account.tax', kind=None)],
                        keywords=[
                            keyword(
                                lineno=9,
                                col_offset=49,
                                end_lineno=9,
                                end_col_offset=74,
                                arg='string',
                                value=Constant(lineno=9, col_offset=56, end_lineno=9, end_col_offset=74, value='Default Sale Tax', kind=None),
                            ),
                            keyword(
                                lineno=9,
                                col_offset=76,
                                end_lineno=9,
                                end_col_offset=116,
                                arg='related',
                                value=Constant(lineno=9, col_offset=84, end_lineno=9, end_col_offset=116, value='company_id.account_sale_tax_id', kind=None),
                            ),
                            keyword(
                                lineno=9,
                                col_offset=118,
                                end_lineno=9,
                                end_col_offset=132,
                                arg='readonly',
                                value=Constant(lineno=9, col_offset=127, end_lineno=9, end_col_offset=132, value=False, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=10,
                    col_offset=4,
                    end_lineno=10,
                    end_col_offset=182,
                    targets=[Name(lineno=10, col_offset=4, end_lineno=10, end_col_offset=22, id='module_pos_mercury', ctx=Store())],
                    value=Call(
                        lineno=10,
                        col_offset=25,
                        end_lineno=10,
                        end_col_offset=182,
                        func=Attribute(
                            lineno=10,
                            col_offset=25,
                            end_lineno=10,
                            end_col_offset=39,
                            value=Name(lineno=10, col_offset=25, end_lineno=10, end_col_offset=31, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=10,
                                col_offset=40,
                                end_lineno=10,
                                end_col_offset=72,
                                arg='string',
                                value=Constant(lineno=10, col_offset=47, end_lineno=10, end_col_offset=72, value='Vantiv Payment Terminal', kind=None),
                            ),
                            keyword(
                                lineno=10,
                                col_offset=74,
                                end_lineno=10,
                                end_col_offset=181,
                                arg='help',
                                value=Constant(lineno=10, col_offset=79, end_lineno=10, end_col_offset=181, value='The transactions are processed by Vantiv. Set your Vantiv credentials on the related payment method.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=11,
                    col_offset=4,
                    end_lineno=11,
                    end_col_offset=177,
                    targets=[Name(lineno=11, col_offset=4, end_lineno=11, end_col_offset=20, id='module_pos_adyen', ctx=Store())],
                    value=Call(
                        lineno=11,
                        col_offset=23,
                        end_lineno=11,
                        end_col_offset=177,
                        func=Attribute(
                            lineno=11,
                            col_offset=23,
                            end_lineno=11,
                            end_col_offset=37,
                            value=Name(lineno=11, col_offset=23, end_lineno=11, end_col_offset=29, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=11,
                                col_offset=38,
                                end_lineno=11,
                                end_col_offset=69,
                                arg='string',
                                value=Constant(lineno=11, col_offset=45, end_lineno=11, end_col_offset=69, value='Adyen Payment Terminal', kind=None),
                            ),
                            keyword(
                                lineno=11,
                                col_offset=71,
                                end_lineno=11,
                                end_col_offset=176,
                                arg='help',
                                value=Constant(lineno=11, col_offset=76, end_lineno=11, end_col_offset=176, value='The transactions are processed by Adyen. Set your Adyen credentials on the related payment method.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=12,
                    col_offset=4,
                    end_lineno=12,
                    end_col_offset=179,
                    targets=[Name(lineno=12, col_offset=4, end_lineno=12, end_col_offset=18, id='module_pos_six', ctx=Store())],
                    value=Call(
                        lineno=12,
                        col_offset=21,
                        end_lineno=12,
                        end_col_offset=179,
                        func=Attribute(
                            lineno=12,
                            col_offset=21,
                            end_lineno=12,
                            end_col_offset=35,
                            value=Name(lineno=12, col_offset=21, end_lineno=12, end_col_offset=27, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=12,
                                col_offset=36,
                                end_lineno=12,
                                end_col_offset=65,
                                arg='string',
                                value=Constant(lineno=12, col_offset=43, end_lineno=12, end_col_offset=65, value='Six Payment Terminal', kind=None),
                            ),
                            keyword(
                                lineno=12,
                                col_offset=67,
                                end_lineno=12,
                                end_col_offset=178,
                                arg='help',
                                value=Constant(lineno=12, col_offset=72, end_lineno=12, end_col_offset=178, value='The transactions are processed by Six. Set the IP address of the terminal on the related payment method.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=13,
                    col_offset=4,
                    end_lineno=13,
                    end_col_offset=122,
                    targets=[Name(lineno=13, col_offset=4, end_lineno=13, end_col_offset=27, id='update_stock_quantities', ctx=Store())],
                    value=Call(
                        lineno=13,
                        col_offset=30,
                        end_lineno=13,
                        end_col_offset=122,
                        func=Attribute(
                            lineno=13,
                            col_offset=30,
                            end_lineno=13,
                            end_col_offset=46,
                            value=Name(lineno=13, col_offset=30, end_lineno=13, end_col_offset=36, id='fields', ctx=Load()),
                            attr='Selection',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=13,
                                col_offset=47,
                                end_lineno=13,
                                end_col_offset=105,
                                arg='related',
                                value=Constant(lineno=13, col_offset=55, end_lineno=13, end_col_offset=105, value='company_id.point_of_sale_update_stock_quantities', kind=None),
                            ),
                            keyword(
                                lineno=13,
                                col_offset=107,
                                end_lineno=13,
                                end_col_offset=121,
                                arg='readonly',
                                value=Constant(lineno=13, col_offset=116, end_lineno=13, end_col_offset=121, value=False, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=14,
                    col_offset=4,
                    end_lineno=14,
                    end_col_offset=134,
                    targets=[Name(lineno=14, col_offset=4, end_lineno=14, end_col_offset=21, id='module_pos_coupon', ctx=Store())],
                    value=Call(
                        lineno=14,
                        col_offset=24,
                        end_lineno=14,
                        end_col_offset=134,
                        func=Attribute(
                            lineno=14,
                            col_offset=24,
                            end_lineno=14,
                            end_col_offset=38,
                            value=Name(lineno=14, col_offset=24, end_lineno=14, end_col_offset=30, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=14, col_offset=39, end_lineno=14, end_col_offset=70, value='Coupon and Promotion Programs', kind=None)],
                        keywords=[
                            keyword(
                                lineno=14,
                                col_offset=72,
                                end_lineno=14,
                                end_col_offset=133,
                                arg='help',
                                value=Constant(lineno=14, col_offset=77, end_lineno=14, end_col_offset=133, value='Allow the use of coupon and promotion programs in PoS.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=15,
                    col_offset=4,
                    end_lineno=15,
                    end_col_offset=186,
                    targets=[Name(lineno=15, col_offset=4, end_lineno=15, end_col_offset=45, id='account_default_pos_receivable_account_id', ctx=Store())],
                    value=Call(
                        lineno=15,
                        col_offset=48,
                        end_lineno=15,
                        end_col_offset=186,
                        func=Attribute(
                            lineno=15,
                            col_offset=48,
                            end_lineno=15,
                            end_col_offset=63,
                            value=Name(lineno=15, col_offset=48, end_lineno=15, end_col_offset=54, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=15,
                                col_offset=64,
                                end_lineno=15,
                                end_col_offset=105,
                                arg='string',
                                value=Constant(lineno=15, col_offset=71, end_lineno=15, end_col_offset=105, value='Default Account Receivable (PoS)', kind=None),
                            ),
                            keyword(
                                lineno=15,
                                col_offset=107,
                                end_lineno=15,
                                end_col_offset=169,
                                arg='related',
                                value=Constant(lineno=15, col_offset=115, end_lineno=15, end_col_offset=169, value='company_id.account_default_pos_receivable_account_id', kind=None),
                            ),
                            keyword(
                                lineno=15,
                                col_offset=171,
                                end_lineno=15,
                                end_col_offset=185,
                                arg='readonly',
                                value=Constant(lineno=15, col_offset=180, end_lineno=15, end_col_offset=185, value=False, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=16,
                    col_offset=4,
                    end_lineno=16,
                    end_col_offset=90,
                    targets=[Name(lineno=16, col_offset=4, end_lineno=16, end_col_offset=24, id='module_pos_gift_card', ctx=Store())],
                    value=Call(
                        lineno=16,
                        col_offset=27,
                        end_lineno=16,
                        end_col_offset=90,
                        func=Attribute(
                            lineno=16,
                            col_offset=27,
                            end_lineno=16,
                            end_col_offset=41,
                            value=Name(lineno=16, col_offset=27, end_lineno=16, end_col_offset=33, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=16, col_offset=42, end_lineno=16, end_col_offset=54, value='Gift Cards', kind=None)],
                        keywords=[
                            keyword(
                                lineno=16,
                                col_offset=56,
                                end_lineno=16,
                                end_col_offset=89,
                                arg='help',
                                value=Constant(lineno=16, col_offset=61, end_lineno=16, end_col_offset=89, value='Allow the use of gift card', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=18,
                    col_offset=4,
                    end_lineno=23,
                    end_col_offset=44,
                    name='set_values',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=18, col_offset=19, end_lineno=18, end_col_offset=23, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=19,
                            col_offset=8,
                            end_lineno=19,
                            end_col_offset=51,
                            value=Call(
                                lineno=19,
                                col_offset=8,
                                end_lineno=19,
                                end_col_offset=51,
                                func=Attribute(
                                    lineno=19,
                                    col_offset=8,
                                    end_lineno=19,
                                    end_col_offset=49,
                                    value=Call(
                                        lineno=19,
                                        col_offset=8,
                                        end_lineno=19,
                                        end_col_offset=38,
                                        func=Name(lineno=19, col_offset=8, end_lineno=19, end_col_offset=13, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=19, col_offset=14, end_lineno=19, end_col_offset=31, id='ResConfigSettings', ctx=Load()),
                                            Name(lineno=19, col_offset=33, end_lineno=19, end_col_offset=37, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='set_values',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        If(
                            lineno=20,
                            col_offset=8,
                            end_lineno=23,
                            end_col_offset=44,
                            test=UnaryOp(
                                lineno=20,
                                col_offset=11,
                                end_lineno=20,
                                end_col_offset=43,
                                op=Not(),
                                operand=Attribute(
                                    lineno=20,
                                    col_offset=15,
                                    end_lineno=20,
                                    end_col_offset=43,
                                    value=Name(lineno=20, col_offset=15, end_lineno=20, end_col_offset=19, id='self', ctx=Load()),
                                    attr='group_product_pricelist',
                                    ctx=Load(),
                                ),
                            ),
                            body=[
                                Assign(
                                    lineno=21,
                                    col_offset=12,
                                    end_lineno=21,
                                    end_col_offset=83,
                                    targets=[Name(lineno=21, col_offset=12, end_lineno=21, end_col_offset=19, id='configs', ctx=Store())],
                                    value=Call(
                                        lineno=21,
                                        col_offset=22,
                                        end_lineno=21,
                                        end_col_offset=83,
                                        func=Attribute(
                                            lineno=21,
                                            col_offset=22,
                                            end_lineno=21,
                                            end_col_offset=51,
                                            value=Subscript(
                                                lineno=21,
                                                col_offset=22,
                                                end_lineno=21,
                                                end_col_offset=44,
                                                value=Attribute(
                                                    lineno=21,
                                                    col_offset=22,
                                                    end_lineno=21,
                                                    end_col_offset=30,
                                                    value=Name(lineno=21, col_offset=22, end_lineno=21, end_col_offset=26, id='self', ctx=Load()),
                                                    attr='env',
                                                    ctx=Load(),
                                                ),
                                                slice=Constant(lineno=21, col_offset=31, end_lineno=21, end_col_offset=43, value='pos.config', kind=None),
                                                ctx=Load(),
                                            ),
                                            attr='search',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            List(
                                                lineno=21,
                                                col_offset=52,
                                                end_lineno=21,
                                                end_col_offset=82,
                                                elts=[
                                                    Tuple(
                                                        lineno=21,
                                                        col_offset=53,
                                                        end_lineno=21,
                                                        end_col_offset=81,
                                                        elts=[
                                                            Constant(lineno=21, col_offset=54, end_lineno=21, end_col_offset=69, value='use_pricelist', kind=None),
                                                            Constant(lineno=21, col_offset=71, end_lineno=21, end_col_offset=74, value='=', kind=None),
                                                            Constant(lineno=21, col_offset=76, end_lineno=21, end_col_offset=80, value=True, kind=None),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                    type_comment=None,
                                ),
                                For(
                                    lineno=22,
                                    col_offset=12,
                                    end_lineno=23,
                                    end_col_offset=44,
                                    target=Name(lineno=22, col_offset=16, end_lineno=22, end_col_offset=22, id='config', ctx=Store()),
                                    iter=Name(lineno=22, col_offset=26, end_lineno=22, end_col_offset=33, id='configs', ctx=Load()),
                                    body=[
                                        Assign(
                                            lineno=23,
                                            col_offset=16,
                                            end_lineno=23,
                                            end_col_offset=44,
                                            targets=[
                                                Attribute(
                                                    lineno=23,
                                                    col_offset=16,
                                                    end_lineno=23,
                                                    end_col_offset=36,
                                                    value=Name(lineno=23, col_offset=16, end_lineno=23, end_col_offset=22, id='config', ctx=Load()),
                                                    attr='use_pricelist',
                                                    ctx=Store(),
                                                ),
                                            ],
                                            value=Constant(lineno=23, col_offset=39, end_lineno=23, end_col_offset=44, value=False, kind=None),
                                            type_comment=None,
                                        ),
                                    ],
                                    orelse=[],
                                    type_comment=None,
                                ),
                            ],
                            orelse=[],
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
