Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=36,
            module='odoo',
            names=[
                alias(name='api', asname=None),
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=44,
            end_col_offset=88,
            name='ResConfigSettings',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=24,
                    end_lineno=7,
                    end_col_offset=45,
                    value=Name(lineno=7, col_offset=24, end_lineno=7, end_col_offset=30, id='models', ctx=Load()),
                    attr='TransientModel',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=36,
                    targets=[Name(lineno=8, col_offset=4, end_lineno=8, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=8, col_offset=15, end_lineno=8, end_col_offset=36, value='res.config.settings', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=10,
                    col_offset=4,
                    end_lineno=10,
                    end_col_offset=120,
                    targets=[Name(lineno=10, col_offset=4, end_lineno=10, end_col_offset=21, id='lock_confirmed_po', ctx=Store())],
                    value=Call(
                        lineno=10,
                        col_offset=24,
                        end_lineno=10,
                        end_col_offset=120,
                        func=Attribute(
                            lineno=10,
                            col_offset=24,
                            end_lineno=10,
                            end_col_offset=38,
                            value=Name(lineno=10, col_offset=24, end_lineno=10, end_col_offset=30, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=10, col_offset=39, end_lineno=10, end_col_offset=62, value='Lock Confirmed Orders', kind=None)],
                        keywords=[
                            keyword(
                                lineno=10,
                                col_offset=64,
                                end_lineno=10,
                                end_col_offset=119,
                                arg='default',
                                value=Lambda(
                                    lineno=10,
                                    col_offset=72,
                                    end_lineno=10,
                                    end_col_offset=119,
                                    args=arguments(
                                        posonlyargs=[],
                                        args=[arg(lineno=10, col_offset=79, end_lineno=10, end_col_offset=83, arg='self', annotation=None, type_comment=None)],
                                        vararg=None,
                                        kwonlyargs=[],
                                        kw_defaults=[],
                                        kwarg=None,
                                        defaults=[],
                                    ),
                                    body=Compare(
                                        lineno=10,
                                        col_offset=85,
                                        end_lineno=10,
                                        end_col_offset=119,
                                        left=Attribute(
                                            lineno=10,
                                            col_offset=85,
                                            end_lineno=10,
                                            end_col_offset=109,
                                            value=Attribute(
                                                lineno=10,
                                                col_offset=85,
                                                end_lineno=10,
                                                end_col_offset=101,
                                                value=Attribute(
                                                    lineno=10,
                                                    col_offset=85,
                                                    end_lineno=10,
                                                    end_col_offset=93,
                                                    value=Name(lineno=10, col_offset=85, end_lineno=10, end_col_offset=89, id='self', ctx=Load()),
                                                    attr='env',
                                                    ctx=Load(),
                                                ),
                                                attr='company',
                                                ctx=Load(),
                                            ),
                                            attr='po_lock',
                                            ctx=Load(),
                                        ),
                                        ops=[Eq()],
                                        comparators=[Constant(lineno=10, col_offset=113, end_lineno=10, end_col_offset=119, value='lock', kind=None)],
                                    ),
                                ),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=11,
                    col_offset=4,
                    end_lineno=11,
                    end_col_offset=116,
                    targets=[Name(lineno=11, col_offset=4, end_lineno=11, end_col_offset=11, id='po_lock', ctx=Store())],
                    value=Call(
                        lineno=11,
                        col_offset=14,
                        end_lineno=11,
                        end_col_offset=116,
                        func=Attribute(
                            lineno=11,
                            col_offset=14,
                            end_lineno=11,
                            end_col_offset=30,
                            value=Name(lineno=11, col_offset=14, end_lineno=11, end_col_offset=20, id='fields', ctx=Load()),
                            attr='Selection',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=11,
                                col_offset=31,
                                end_lineno=11,
                                end_col_offset=59,
                                arg='related',
                                value=Constant(lineno=11, col_offset=39, end_lineno=11, end_col_offset=59, value='company_id.po_lock', kind=None),
                            ),
                            keyword(
                                lineno=11,
                                col_offset=61,
                                end_lineno=11,
                                end_col_offset=99,
                                arg='string',
                                value=Constant(lineno=11, col_offset=68, end_lineno=11, end_col_offset=99, value='Purchase Order Modification *', kind=None),
                            ),
                            keyword(
                                lineno=11,
                                col_offset=101,
                                end_lineno=11,
                                end_col_offset=115,
                                arg='readonly',
                                value=Constant(lineno=11, col_offset=110, end_lineno=11, end_col_offset=115, value=False, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=12,
                    col_offset=4,
                    end_lineno=12,
                    end_col_offset=139,
                    targets=[Name(lineno=12, col_offset=4, end_lineno=12, end_col_offset=21, id='po_order_approval', ctx=Store())],
                    value=Call(
                        lineno=12,
                        col_offset=24,
                        end_lineno=12,
                        end_col_offset=139,
                        func=Attribute(
                            lineno=12,
                            col_offset=24,
                            end_lineno=12,
                            end_col_offset=38,
                            value=Name(lineno=12, col_offset=24, end_lineno=12, end_col_offset=30, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=12, col_offset=39, end_lineno=12, end_col_offset=64, value='Purchase Order Approval', kind=None)],
                        keywords=[
                            keyword(
                                lineno=12,
                                col_offset=66,
                                end_lineno=12,
                                end_col_offset=138,
                                arg='default',
                                value=Lambda(
                                    lineno=12,
                                    col_offset=74,
                                    end_lineno=12,
                                    end_col_offset=138,
                                    args=arguments(
                                        posonlyargs=[],
                                        args=[arg(lineno=12, col_offset=81, end_lineno=12, end_col_offset=85, arg='self', annotation=None, type_comment=None)],
                                        vararg=None,
                                        kwonlyargs=[],
                                        kw_defaults=[],
                                        kwarg=None,
                                        defaults=[],
                                    ),
                                    body=Compare(
                                        lineno=12,
                                        col_offset=87,
                                        end_lineno=12,
                                        end_col_offset=138,
                                        left=Attribute(
                                            lineno=12,
                                            col_offset=87,
                                            end_lineno=12,
                                            end_col_offset=124,
                                            value=Attribute(
                                                lineno=12,
                                                col_offset=87,
                                                end_lineno=12,
                                                end_col_offset=103,
                                                value=Attribute(
                                                    lineno=12,
                                                    col_offset=87,
                                                    end_lineno=12,
                                                    end_col_offset=95,
                                                    value=Name(lineno=12, col_offset=87, end_lineno=12, end_col_offset=91, id='self', ctx=Load()),
                                                    attr='env',
                                                    ctx=Load(),
                                                ),
                                                attr='company',
                                                ctx=Load(),
                                            ),
                                            attr='po_double_validation',
                                            ctx=Load(),
                                        ),
                                        ops=[Eq()],
                                        comparators=[Constant(lineno=12, col_offset=128, end_lineno=12, end_col_offset=138, value='two_step', kind=None)],
                                    ),
                                ),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=13,
                    col_offset=4,
                    end_lineno=13,
                    end_col_offset=134,
                    targets=[Name(lineno=13, col_offset=4, end_lineno=13, end_col_offset=24, id='po_double_validation', ctx=Store())],
                    value=Call(
                        lineno=13,
                        col_offset=27,
                        end_lineno=13,
                        end_col_offset=134,
                        func=Attribute(
                            lineno=13,
                            col_offset=27,
                            end_lineno=13,
                            end_col_offset=43,
                            value=Name(lineno=13, col_offset=27, end_lineno=13, end_col_offset=33, id='fields', ctx=Load()),
                            attr='Selection',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=13,
                                col_offset=44,
                                end_lineno=13,
                                end_col_offset=85,
                                arg='related',
                                value=Constant(lineno=13, col_offset=52, end_lineno=13, end_col_offset=85, value='company_id.po_double_validation', kind=None),
                            ),
                            keyword(
                                lineno=13,
                                col_offset=87,
                                end_lineno=13,
                                end_col_offset=117,
                                arg='string',
                                value=Constant(lineno=13, col_offset=94, end_lineno=13, end_col_offset=117, value='Levels of Approvals *', kind=None),
                            ),
                            keyword(
                                lineno=13,
                                col_offset=119,
                                end_lineno=13,
                                end_col_offset=133,
                                arg='readonly',
                                value=Constant(lineno=13, col_offset=128, end_lineno=13, end_col_offset=133, value=False, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=14,
                    col_offset=4,
                    end_lineno=14,
                    end_col_offset=178,
                    targets=[Name(lineno=14, col_offset=4, end_lineno=14, end_col_offset=31, id='po_double_validation_amount', ctx=Store())],
                    value=Call(
                        lineno=14,
                        col_offset=34,
                        end_lineno=14,
                        end_col_offset=178,
                        func=Attribute(
                            lineno=14,
                            col_offset=34,
                            end_lineno=14,
                            end_col_offset=49,
                            value=Name(lineno=14, col_offset=34, end_lineno=14, end_col_offset=40, id='fields', ctx=Load()),
                            attr='Monetary',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=14,
                                col_offset=50,
                                end_lineno=14,
                                end_col_offset=98,
                                arg='related',
                                value=Constant(lineno=14, col_offset=58, end_lineno=14, end_col_offset=98, value='company_id.po_double_validation_amount', kind=None),
                            ),
                            keyword(
                                lineno=14,
                                col_offset=100,
                                end_lineno=14,
                                end_col_offset=123,
                                arg='string',
                                value=Constant(lineno=14, col_offset=107, end_lineno=14, end_col_offset=123, value='Minimum Amount', kind=None),
                            ),
                            keyword(
                                lineno=14,
                                col_offset=125,
                                end_lineno=14,
                                end_col_offset=161,
                                arg='currency_field',
                                value=Constant(lineno=14, col_offset=140, end_lineno=14, end_col_offset=161, value='company_currency_id', kind=None),
                            ),
                            keyword(
                                lineno=14,
                                col_offset=163,
                                end_lineno=14,
                                end_col_offset=177,
                                arg='readonly',
                                value=Constant(lineno=14, col_offset=172, end_lineno=14, end_col_offset=177, value=False, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=15,
                    col_offset=4,
                    end_lineno=16,
                    end_col_offset=56,
                    targets=[Name(lineno=15, col_offset=4, end_lineno=15, end_col_offset=23, id='company_currency_id', ctx=Store())],
                    value=Call(
                        lineno=15,
                        col_offset=26,
                        end_lineno=16,
                        end_col_offset=56,
                        func=Attribute(
                            lineno=15,
                            col_offset=26,
                            end_lineno=15,
                            end_col_offset=41,
                            value=Name(lineno=15, col_offset=26, end_lineno=15, end_col_offset=32, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=15, col_offset=42, end_lineno=15, end_col_offset=56, value='res.currency', kind=None)],
                        keywords=[
                            keyword(
                                lineno=15,
                                col_offset=58,
                                end_lineno=15,
                                end_col_offset=90,
                                arg='related',
                                value=Constant(lineno=15, col_offset=66, end_lineno=15, end_col_offset=90, value='company_id.currency_id', kind=None),
                            ),
                            keyword(
                                lineno=15,
                                col_offset=92,
                                end_lineno=15,
                                end_col_offset=117,
                                arg='string',
                                value=Constant(lineno=15, col_offset=99, end_lineno=15, end_col_offset=117, value='Company Currency', kind=None),
                            ),
                            keyword(
                                lineno=15,
                                col_offset=119,
                                end_lineno=15,
                                end_col_offset=132,
                                arg='readonly',
                                value=Constant(lineno=15, col_offset=128, end_lineno=15, end_col_offset=132, value=True, kind=None),
                            ),
                            keyword(
                                lineno=16,
                                col_offset=8,
                                end_lineno=16,
                                end_col_offset=55,
                                arg='help',
                                value=Constant(lineno=16, col_offset=13, end_lineno=16, end_col_offset=55, value='Utility field to express amount currency', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=17,
                    col_offset=4,
                    end_lineno=22,
                    end_col_offset=77,
                    targets=[Name(lineno=17, col_offset=4, end_lineno=17, end_col_offset=27, id='default_purchase_method', ctx=Store())],
                    value=Call(
                        lineno=17,
                        col_offset=30,
                        end_lineno=22,
                        end_col_offset=77,
                        func=Attribute(
                            lineno=17,
                            col_offset=30,
                            end_lineno=17,
                            end_col_offset=46,
                            value=Name(lineno=17, col_offset=30, end_lineno=17, end_col_offset=36, id='fields', ctx=Load()),
                            attr='Selection',
                            ctx=Load(),
                        ),
                        args=[
                            List(
                                lineno=17,
                                col_offset=47,
                                end_lineno=20,
                                end_col_offset=9,
                                elts=[
                                    Tuple(
                                        lineno=18,
                                        col_offset=8,
                                        end_lineno=18,
                                        end_col_offset=42,
                                        elts=[
                                            Constant(lineno=18, col_offset=9, end_lineno=18, end_col_offset=19, value='purchase', kind=None),
                                            Constant(lineno=18, col_offset=21, end_lineno=18, end_col_offset=41, value='Ordered quantities', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                    Tuple(
                                        lineno=19,
                                        col_offset=8,
                                        end_lineno=19,
                                        end_col_offset=42,
                                        elts=[
                                            Constant(lineno=19, col_offset=9, end_lineno=19, end_col_offset=18, value='receive', kind=None),
                                            Constant(lineno=19, col_offset=20, end_lineno=19, end_col_offset=41, value='Received quantities', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                ctx=Load(),
                            ),
                        ],
                        keywords=[
                            keyword(
                                lineno=20,
                                col_offset=11,
                                end_lineno=20,
                                end_col_offset=32,
                                arg='string',
                                value=Constant(lineno=20, col_offset=18, end_lineno=20, end_col_offset=32, value='Bill Control', kind=None),
                            ),
                            keyword(
                                lineno=20,
                                col_offset=34,
                                end_lineno=20,
                                end_col_offset=66,
                                arg='default_model',
                                value=Constant(lineno=20, col_offset=48, end_lineno=20, end_col_offset=66, value='product.template', kind=None),
                            ),
                            keyword(
                                lineno=21,
                                col_offset=8,
                                end_lineno=22,
                                end_col_offset=57,
                                arg='help',
                                value=Constant(lineno=21, col_offset=13, end_lineno=22, end_col_offset=57, value='This default value is applied to any new product created. This can be changed in the product detail form.', kind=None),
                            ),
                            keyword(
                                lineno=22,
                                col_offset=59,
                                end_lineno=22,
                                end_col_offset=76,
                                arg='default',
                                value=Constant(lineno=22, col_offset=67, end_lineno=22, end_col_offset=76, value='receive', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=23,
                    col_offset=4,
                    end_lineno=23,
                    end_col_offset=113,
                    targets=[Name(lineno=23, col_offset=4, end_lineno=23, end_col_offset=26, id='group_warning_purchase', ctx=Store())],
                    value=Call(
                        lineno=23,
                        col_offset=29,
                        end_lineno=23,
                        end_col_offset=113,
                        func=Attribute(
                            lineno=23,
                            col_offset=29,
                            end_lineno=23,
                            end_col_offset=43,
                            value=Name(lineno=23, col_offset=29, end_lineno=23, end_col_offset=35, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=23, col_offset=44, end_lineno=23, end_col_offset=63, value='Purchase Warnings', kind=None)],
                        keywords=[
                            keyword(
                                lineno=23,
                                col_offset=65,
                                end_lineno=23,
                                end_col_offset=112,
                                arg='implied_group',
                                value=Constant(lineno=23, col_offset=79, end_lineno=23, end_col_offset=112, value='purchase.group_warning_purchase', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=24,
                    col_offset=4,
                    end_lineno=24,
                    end_col_offset=97,
                    targets=[Name(lineno=24, col_offset=4, end_lineno=24, end_col_offset=29, id='module_account_3way_match', ctx=Store())],
                    value=Call(
                        lineno=24,
                        col_offset=32,
                        end_lineno=24,
                        end_col_offset=97,
                        func=Attribute(
                            lineno=24,
                            col_offset=32,
                            end_lineno=24,
                            end_col_offset=46,
                            value=Name(lineno=24, col_offset=32, end_lineno=24, end_col_offset=38, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=24, col_offset=47, end_lineno=24, end_col_offset=96, value='3-way matching: purchases, receptions and bills', kind=None)],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=25,
                    col_offset=4,
                    end_lineno=25,
                    end_col_offset=71,
                    targets=[Name(lineno=25, col_offset=4, end_lineno=25, end_col_offset=31, id='module_purchase_requisition', ctx=Store())],
                    value=Call(
                        lineno=25,
                        col_offset=34,
                        end_lineno=25,
                        end_col_offset=71,
                        func=Attribute(
                            lineno=25,
                            col_offset=34,
                            end_lineno=25,
                            end_col_offset=48,
                            value=Name(lineno=25, col_offset=34, end_lineno=25, end_col_offset=40, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=25, col_offset=49, end_lineno=25, end_col_offset=70, value='Purchase Agreements', kind=None)],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=26,
                    col_offset=4,
                    end_lineno=26,
                    end_col_offset=74,
                    targets=[Name(lineno=26, col_offset=4, end_lineno=26, end_col_offset=34, id='module_purchase_product_matrix', ctx=Store())],
                    value=Call(
                        lineno=26,
                        col_offset=37,
                        end_lineno=26,
                        end_col_offset=74,
                        func=Attribute(
                            lineno=26,
                            col_offset=37,
                            end_lineno=26,
                            end_col_offset=51,
                            value=Name(lineno=26, col_offset=37, end_lineno=26, end_col_offset=43, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=26, col_offset=52, end_lineno=26, end_col_offset=73, value='Purchase Grid Entry', kind=None)],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=27,
                    col_offset=4,
                    end_lineno=27,
                    end_col_offset=72,
                    targets=[Name(lineno=27, col_offset=4, end_lineno=27, end_col_offset=11, id='po_lead', ctx=Store())],
                    value=Call(
                        lineno=27,
                        col_offset=14,
                        end_lineno=27,
                        end_col_offset=72,
                        func=Attribute(
                            lineno=27,
                            col_offset=14,
                            end_lineno=27,
                            end_col_offset=26,
                            value=Name(lineno=27, col_offset=14, end_lineno=27, end_col_offset=20, id='fields', ctx=Load()),
                            attr='Float',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=27,
                                col_offset=27,
                                end_lineno=27,
                                end_col_offset=55,
                                arg='related',
                                value=Constant(lineno=27, col_offset=35, end_lineno=27, end_col_offset=55, value='company_id.po_lead', kind=None),
                            ),
                            keyword(
                                lineno=27,
                                col_offset=57,
                                end_lineno=27,
                                end_col_offset=71,
                                arg='readonly',
                                value=Constant(lineno=27, col_offset=66, end_lineno=27, end_col_offset=71, value=False, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=28,
                    col_offset=4,
                    end_lineno=31,
                    end_col_offset=205,
                    targets=[Name(lineno=28, col_offset=4, end_lineno=28, end_col_offset=15, id='use_po_lead', ctx=Store())],
                    value=Call(
                        lineno=28,
                        col_offset=18,
                        end_lineno=31,
                        end_col_offset=205,
                        func=Attribute(
                            lineno=28,
                            col_offset=18,
                            end_lineno=28,
                            end_col_offset=32,
                            value=Name(lineno=28, col_offset=18, end_lineno=28, end_col_offset=24, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=29,
                                col_offset=8,
                                end_lineno=29,
                                end_col_offset=48,
                                arg='string',
                                value=Constant(lineno=29, col_offset=15, end_lineno=29, end_col_offset=48, value='Security Lead Time for Purchase', kind=None),
                            ),
                            keyword(
                                lineno=30,
                                col_offset=8,
                                end_lineno=30,
                                end_col_offset=47,
                                arg='config_parameter',
                                value=Constant(lineno=30, col_offset=25, end_lineno=30, end_col_offset=47, value='purchase.use_po_lead', kind=None),
                            ),
                            keyword(
                                lineno=31,
                                col_offset=8,
                                end_lineno=31,
                                end_col_offset=204,
                                arg='help',
                                value=Constant(lineno=31, col_offset=13, end_lineno=31, end_col_offset=204, value='Margin of error for vendor lead times. When the system generates Purchase Orders for reordering products,they will be scheduled that many days earlier to cope with unexpected vendor delays.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=33,
                    col_offset=4,
                    end_lineno=34,
                    end_col_offset=85,
                    targets=[Name(lineno=33, col_offset=4, end_lineno=33, end_col_offset=23, id='group_send_reminder', ctx=Store())],
                    value=Call(
                        lineno=33,
                        col_offset=26,
                        end_lineno=34,
                        end_col_offset=85,
                        func=Attribute(
                            lineno=33,
                            col_offset=26,
                            end_lineno=33,
                            end_col_offset=40,
                            value=Name(lineno=33, col_offset=26, end_lineno=33, end_col_offset=32, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=33, col_offset=41, end_lineno=33, end_col_offset=59, value='Receipt Reminder', kind=None)],
                        keywords=[
                            keyword(
                                lineno=33,
                                col_offset=61,
                                end_lineno=33,
                                end_col_offset=105,
                                arg='implied_group',
                                value=Constant(lineno=33, col_offset=75, end_lineno=33, end_col_offset=105, value='purchase.group_send_reminder', kind=None),
                            ),
                            keyword(
                                lineno=33,
                                col_offset=107,
                                end_lineno=33,
                                end_col_offset=119,
                                arg='default',
                                value=Constant(lineno=33, col_offset=115, end_lineno=33, end_col_offset=119, value=True, kind=None),
                            ),
                            keyword(
                                lineno=34,
                                col_offset=8,
                                end_lineno=34,
                                end_col_offset=84,
                                arg='help',
                                value=Constant(lineno=34, col_offset=13, end_lineno=34, end_col_offset=84, value='Allow automatically send email to remind your vendor the receipt date', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=37,
                    col_offset=4,
                    end_lineno=39,
                    end_col_offset=30,
                    name='_onchange_use_po_lead',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=37, col_offset=30, end_lineno=37, end_col_offset=34, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        If(
                            lineno=38,
                            col_offset=8,
                            end_lineno=39,
                            end_col_offset=30,
                            test=UnaryOp(
                                lineno=38,
                                col_offset=11,
                                end_lineno=38,
                                end_col_offset=31,
                                op=Not(),
                                operand=Attribute(
                                    lineno=38,
                                    col_offset=15,
                                    end_lineno=38,
                                    end_col_offset=31,
                                    value=Name(lineno=38, col_offset=15, end_lineno=38, end_col_offset=19, id='self', ctx=Load()),
                                    attr='use_po_lead',
                                    ctx=Load(),
                                ),
                            ),
                            body=[
                                Assign(
                                    lineno=39,
                                    col_offset=12,
                                    end_lineno=39,
                                    end_col_offset=30,
                                    targets=[
                                        Attribute(
                                            lineno=39,
                                            col_offset=12,
                                            end_lineno=39,
                                            end_col_offset=24,
                                            value=Name(lineno=39, col_offset=12, end_lineno=39, end_col_offset=16, id='self', ctx=Load()),
                                            attr='po_lead',
                                            ctx=Store(),
                                        ),
                                    ],
                                    value=Constant(lineno=39, col_offset=27, end_lineno=39, end_col_offset=30, value=0.0, kind=None),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[],
                        ),
                    ],
                    decorator_list=[
                        Call(
                            lineno=36,
                            col_offset=5,
                            end_lineno=36,
                            end_col_offset=32,
                            func=Attribute(
                                lineno=36,
                                col_offset=5,
                                end_lineno=36,
                                end_col_offset=17,
                                value=Name(lineno=36, col_offset=5, end_lineno=36, end_col_offset=8, id='api', ctx=Load()),
                                attr='onchange',
                                ctx=Load(),
                            ),
                            args=[Constant(lineno=36, col_offset=18, end_lineno=36, end_col_offset=31, value='use_po_lead', kind=None)],
                            keywords=[],
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=41,
                    col_offset=4,
                    end_lineno=44,
                    end_col_offset=88,
                    name='set_values',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=41, col_offset=19, end_lineno=41, end_col_offset=23, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=42,
                            col_offset=8,
                            end_lineno=42,
                            end_col_offset=51,
                            value=Call(
                                lineno=42,
                                col_offset=8,
                                end_lineno=42,
                                end_col_offset=51,
                                func=Attribute(
                                    lineno=42,
                                    col_offset=8,
                                    end_lineno=42,
                                    end_col_offset=49,
                                    value=Call(
                                        lineno=42,
                                        col_offset=8,
                                        end_lineno=42,
                                        end_col_offset=38,
                                        func=Name(lineno=42, col_offset=8, end_lineno=42, end_col_offset=13, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=42, col_offset=14, end_lineno=42, end_col_offset=31, id='ResConfigSettings', ctx=Load()),
                                            Name(lineno=42, col_offset=33, end_lineno=42, end_col_offset=37, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='set_values',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=43,
                            col_offset=8,
                            end_lineno=43,
                            end_col_offset=67,
                            targets=[
                                Attribute(
                                    lineno=43,
                                    col_offset=8,
                                    end_lineno=43,
                                    end_col_offset=20,
                                    value=Name(lineno=43, col_offset=8, end_lineno=43, end_col_offset=12, id='self', ctx=Load()),
                                    attr='po_lock',
                                    ctx=Store(),
                                ),
                            ],
                            value=IfExp(
                                lineno=43,
                                col_offset=23,
                                end_lineno=43,
                                end_col_offset=67,
                                test=Attribute(
                                    lineno=43,
                                    col_offset=33,
                                    end_lineno=43,
                                    end_col_offset=55,
                                    value=Name(lineno=43, col_offset=33, end_lineno=43, end_col_offset=37, id='self', ctx=Load()),
                                    attr='lock_confirmed_po',
                                    ctx=Load(),
                                ),
                                body=Constant(lineno=43, col_offset=23, end_lineno=43, end_col_offset=29, value='lock', kind=None),
                                orelse=Constant(lineno=43, col_offset=61, end_lineno=43, end_col_offset=67, value='edit', kind=None),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=44,
                            col_offset=8,
                            end_lineno=44,
                            end_col_offset=88,
                            targets=[
                                Attribute(
                                    lineno=44,
                                    col_offset=8,
                                    end_lineno=44,
                                    end_col_offset=33,
                                    value=Name(lineno=44, col_offset=8, end_lineno=44, end_col_offset=12, id='self', ctx=Load()),
                                    attr='po_double_validation',
                                    ctx=Store(),
                                ),
                            ],
                            value=IfExp(
                                lineno=44,
                                col_offset=36,
                                end_lineno=44,
                                end_col_offset=88,
                                test=Attribute(
                                    lineno=44,
                                    col_offset=50,
                                    end_lineno=44,
                                    end_col_offset=72,
                                    value=Name(lineno=44, col_offset=50, end_lineno=44, end_col_offset=54, id='self', ctx=Load()),
                                    attr='po_order_approval',
                                    ctx=Load(),
                                ),
                                body=Constant(lineno=44, col_offset=36, end_lineno=44, end_col_offset=46, value='two_step', kind=None),
                                orelse=Constant(lineno=44, col_offset=78, end_lineno=44, end_col_offset=88, value='one_step', kind=None),
                            ),
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
