Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=36,
            module='odoo',
            names=[
                alias(name='api', asname=None),
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=27,
            end_col_offset=123,
            name='Product',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=14,
                    end_lineno=7,
                    end_col_offset=26,
                    value=Name(lineno=7, col_offset=14, end_lineno=7, end_col_offset=20, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=33,
                    targets=[Name(lineno=8, col_offset=4, end_lineno=8, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=8, col_offset=15, end_lineno=8, end_col_offset=33, value='product.template', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=10,
                    col_offset=4,
                    end_lineno=10,
                    end_col_offset=88,
                    targets=[Name(lineno=10, col_offset=4, end_lineno=10, end_col_offset=14, id='membership', ctx=Store())],
                    value=Call(
                        lineno=10,
                        col_offset=17,
                        end_lineno=10,
                        end_col_offset=88,
                        func=Attribute(
                            lineno=10,
                            col_offset=17,
                            end_lineno=10,
                            end_col_offset=31,
                            value=Name(lineno=10, col_offset=17, end_lineno=10, end_col_offset=23, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=10,
                                col_offset=32,
                                end_lineno=10,
                                end_col_offset=87,
                                arg='help',
                                value=Constant(lineno=10, col_offset=37, end_lineno=10, end_col_offset=87, value='Check if the product is eligible for membership.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=11,
                    col_offset=4,
                    end_lineno=12,
                    end_col_offset=58,
                    targets=[Name(lineno=11, col_offset=4, end_lineno=11, end_col_offset=24, id='membership_date_from', ctx=Store())],
                    value=Call(
                        lineno=11,
                        col_offset=27,
                        end_lineno=12,
                        end_col_offset=58,
                        func=Attribute(
                            lineno=11,
                            col_offset=27,
                            end_lineno=11,
                            end_col_offset=38,
                            value=Name(lineno=11, col_offset=27, end_lineno=11, end_col_offset=33, id='fields', ctx=Load()),
                            attr='Date',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=11,
                                col_offset=39,
                                end_lineno=11,
                                end_col_offset=69,
                                arg='string',
                                value=Constant(lineno=11, col_offset=46, end_lineno=11, end_col_offset=69, value='Membership Start Date', kind=None),
                            ),
                            keyword(
                                lineno=12,
                                col_offset=8,
                                end_lineno=12,
                                end_col_offset=57,
                                arg='help',
                                value=Constant(lineno=12, col_offset=13, end_lineno=12, end_col_offset=57, value='Date from which membership becomes active.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=13,
                    col_offset=4,
                    end_lineno=14,
                    end_col_offset=59,
                    targets=[Name(lineno=13, col_offset=4, end_lineno=13, end_col_offset=22, id='membership_date_to', ctx=Store())],
                    value=Call(
                        lineno=13,
                        col_offset=25,
                        end_lineno=14,
                        end_col_offset=59,
                        func=Attribute(
                            lineno=13,
                            col_offset=25,
                            end_lineno=13,
                            end_col_offset=36,
                            value=Name(lineno=13, col_offset=25, end_lineno=13, end_col_offset=31, id='fields', ctx=Load()),
                            attr='Date',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=13,
                                col_offset=37,
                                end_lineno=13,
                                end_col_offset=65,
                                arg='string',
                                value=Constant(lineno=13, col_offset=44, end_lineno=13, end_col_offset=65, value='Membership End Date', kind=None),
                            ),
                            keyword(
                                lineno=14,
                                col_offset=8,
                                end_lineno=14,
                                end_col_offset=58,
                                arg='help',
                                value=Constant(lineno=14, col_offset=13, end_lineno=14, end_col_offset=58, value='Date until which membership remains active.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=16,
                    col_offset=4,
                    end_lineno=18,
                    end_col_offset=5,
                    targets=[Name(lineno=16, col_offset=4, end_lineno=16, end_col_offset=20, id='_sql_constraints', ctx=Store())],
                    value=List(
                        lineno=16,
                        col_offset=23,
                        end_lineno=18,
                        end_col_offset=5,
                        elts=[
                            Tuple(
                                lineno=17,
                                col_offset=8,
                                end_lineno=17,
                                end_col_offset=148,
                                elts=[
                                    Constant(lineno=17, col_offset=9, end_lineno=17, end_col_offset=34, value='membership_date_greater', kind=None),
                                    Constant(lineno=17, col_offset=36, end_lineno=17, end_col_offset=87, value='check(membership_date_to >= membership_date_from)', kind=None),
                                    Constant(lineno=17, col_offset=89, end_lineno=17, end_col_offset=147, value='Error ! Ending Date cannot be set before Beginning Date.', kind=None),
                                ],
                                ctx=Load(),
                            ),
                        ],
                        ctx=Load(),
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=21,
                    col_offset=4,
                    end_lineno=27,
                    end_col_offset=123,
                    name='fields_view_get',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=21, col_offset=24, end_lineno=21, end_col_offset=28, arg='self', annotation=None, type_comment=None),
                            arg(lineno=21, col_offset=30, end_lineno=21, end_col_offset=37, arg='view_id', annotation=None, type_comment=None),
                            arg(lineno=21, col_offset=44, end_lineno=21, end_col_offset=53, arg='view_type', annotation=None, type_comment=None),
                            arg(lineno=21, col_offset=62, end_lineno=21, end_col_offset=69, arg='toolbar', annotation=None, type_comment=None),
                            arg(lineno=21, col_offset=77, end_lineno=21, end_col_offset=84, arg='submenu', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[
                            Constant(lineno=21, col_offset=38, end_lineno=21, end_col_offset=42, value=None, kind=None),
                            Constant(lineno=21, col_offset=54, end_lineno=21, end_col_offset=60, value='form', kind=None),
                            Constant(lineno=21, col_offset=70, end_lineno=21, end_col_offset=75, value=False, kind=None),
                            Constant(lineno=21, col_offset=85, end_lineno=21, end_col_offset=90, value=False, kind=None),
                        ],
                    ),
                    body=[
                        If(
                            lineno=22,
                            col_offset=8,
                            end_lineno=26,
                            end_col_offset=80,
                            test=Compare(
                                lineno=22,
                                col_offset=11,
                                end_lineno=22,
                                end_col_offset=63,
                                left=Call(
                                    lineno=22,
                                    col_offset=11,
                                    end_lineno=22,
                                    end_col_offset=39,
                                    func=Attribute(
                                        lineno=22,
                                        col_offset=11,
                                        end_lineno=22,
                                        end_col_offset=28,
                                        value=Attribute(
                                            lineno=22,
                                            col_offset=11,
                                            end_lineno=22,
                                            end_col_offset=24,
                                            value=Name(lineno=22, col_offset=11, end_lineno=22, end_col_offset=15, id='self', ctx=Load()),
                                            attr='_context',
                                            ctx=Load(),
                                        ),
                                        attr='get',
                                        ctx=Load(),
                                    ),
                                    args=[Constant(lineno=22, col_offset=29, end_lineno=22, end_col_offset=38, value='product', kind=None)],
                                    keywords=[],
                                ),
                                ops=[Eq()],
                                comparators=[Constant(lineno=22, col_offset=43, end_lineno=22, end_col_offset=63, value='membership_product', kind=None)],
                            ),
                            body=[
                                If(
                                    lineno=23,
                                    col_offset=12,
                                    end_lineno=26,
                                    end_col_offset=80,
                                    test=Compare(
                                        lineno=23,
                                        col_offset=15,
                                        end_lineno=23,
                                        end_col_offset=34,
                                        left=Name(lineno=23, col_offset=15, end_lineno=23, end_col_offset=24, id='view_type', ctx=Load()),
                                        ops=[Eq()],
                                        comparators=[Constant(lineno=23, col_offset=28, end_lineno=23, end_col_offset=34, value='form', kind=None)],
                                    ),
                                    body=[
                                        Assign(
                                            lineno=24,
                                            col_offset=16,
                                            end_lineno=24,
                                            end_col_offset=80,
                                            targets=[Name(lineno=24, col_offset=16, end_lineno=24, end_col_offset=23, id='view_id', ctx=Store())],
                                            value=Attribute(
                                                lineno=24,
                                                col_offset=26,
                                                end_lineno=24,
                                                end_col_offset=80,
                                                value=Call(
                                                    lineno=24,
                                                    col_offset=26,
                                                    end_lineno=24,
                                                    end_col_offset=77,
                                                    func=Attribute(
                                                        lineno=24,
                                                        col_offset=26,
                                                        end_lineno=24,
                                                        end_col_offset=38,
                                                        value=Attribute(
                                                            lineno=24,
                                                            col_offset=26,
                                                            end_lineno=24,
                                                            end_col_offset=34,
                                                            value=Name(lineno=24, col_offset=26, end_lineno=24, end_col_offset=30, id='self', ctx=Load()),
                                                            attr='env',
                                                            ctx=Load(),
                                                        ),
                                                        attr='ref',
                                                        ctx=Load(),
                                                    ),
                                                    args=[Constant(lineno=24, col_offset=39, end_lineno=24, end_col_offset=76, value='membership.membership_products_form', kind=None)],
                                                    keywords=[],
                                                ),
                                                attr='id',
                                                ctx=Load(),
                                            ),
                                            type_comment=None,
                                        ),
                                    ],
                                    orelse=[
                                        Assign(
                                            lineno=26,
                                            col_offset=16,
                                            end_lineno=26,
                                            end_col_offset=80,
                                            targets=[Name(lineno=26, col_offset=16, end_lineno=26, end_col_offset=23, id='view_id', ctx=Store())],
                                            value=Attribute(
                                                lineno=26,
                                                col_offset=26,
                                                end_lineno=26,
                                                end_col_offset=80,
                                                value=Call(
                                                    lineno=26,
                                                    col_offset=26,
                                                    end_lineno=26,
                                                    end_col_offset=77,
                                                    func=Attribute(
                                                        lineno=26,
                                                        col_offset=26,
                                                        end_lineno=26,
                                                        end_col_offset=38,
                                                        value=Attribute(
                                                            lineno=26,
                                                            col_offset=26,
                                                            end_lineno=26,
                                                            end_col_offset=34,
                                                            value=Name(lineno=26, col_offset=26, end_lineno=26, end_col_offset=30, id='self', ctx=Load()),
                                                            attr='env',
                                                            ctx=Load(),
                                                        ),
                                                        attr='ref',
                                                        ctx=Load(),
                                                    ),
                                                    args=[Constant(lineno=26, col_offset=39, end_lineno=26, end_col_offset=76, value='membership.membership_products_tree', kind=None)],
                                                    keywords=[],
                                                ),
                                                attr='id',
                                                ctx=Load(),
                                            ),
                                            type_comment=None,
                                        ),
                                    ],
                                ),
                            ],
                            orelse=[],
                        ),
                        Return(
                            lineno=27,
                            col_offset=8,
                            end_lineno=27,
                            end_col_offset=123,
                            value=Call(
                                lineno=27,
                                col_offset=15,
                                end_lineno=27,
                                end_col_offset=123,
                                func=Attribute(
                                    lineno=27,
                                    col_offset=15,
                                    end_lineno=27,
                                    end_col_offset=51,
                                    value=Call(
                                        lineno=27,
                                        col_offset=15,
                                        end_lineno=27,
                                        end_col_offset=35,
                                        func=Name(lineno=27, col_offset=15, end_lineno=27, end_col_offset=20, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=27, col_offset=21, end_lineno=27, end_col_offset=28, id='Product', ctx=Load()),
                                            Name(lineno=27, col_offset=30, end_lineno=27, end_col_offset=34, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='fields_view_get',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[
                                    keyword(
                                        lineno=27,
                                        col_offset=52,
                                        end_lineno=27,
                                        end_col_offset=67,
                                        arg='view_id',
                                        value=Name(lineno=27, col_offset=60, end_lineno=27, end_col_offset=67, id='view_id', ctx=Load()),
                                    ),
                                    keyword(
                                        lineno=27,
                                        col_offset=69,
                                        end_lineno=27,
                                        end_col_offset=88,
                                        arg='view_type',
                                        value=Name(lineno=27, col_offset=79, end_lineno=27, end_col_offset=88, id='view_type', ctx=Load()),
                                    ),
                                    keyword(
                                        lineno=27,
                                        col_offset=90,
                                        end_lineno=27,
                                        end_col_offset=105,
                                        arg='toolbar',
                                        value=Name(lineno=27, col_offset=98, end_lineno=27, end_col_offset=105, id='toolbar', ctx=Load()),
                                    ),
                                    keyword(
                                        lineno=27,
                                        col_offset=107,
                                        end_lineno=27,
                                        end_col_offset=122,
                                        arg='submenu',
                                        value=Name(lineno=27, col_offset=115, end_lineno=27, end_col_offset=122, id='submenu', ctx=Load()),
                                    ),
                                ],
                            ),
                        ),
                    ],
                    decorator_list=[
                        Attribute(
                            lineno=20,
                            col_offset=5,
                            end_lineno=20,
                            end_col_offset=14,
                            value=Name(lineno=20, col_offset=5, end_lineno=20, end_col_offset=8, id='api', ctx=Load()),
                            attr='model',
                            ctx=Load(),
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
