Module(
    body=[
        Import(
            lineno=2,
            col_offset=0,
            end_lineno=2,
            end_col_offset=11,
            names=[alias(name='json', asname=None)],
        ),
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=21,
            module='odoo',
            names=[alias(name='http', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=5,
            col_offset=0,
            end_lineno=5,
            end_col_offset=60,
            module='odoo.addons.website.controllers.form',
            names=[alias(name='WebsiteForm', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=6,
            col_offset=0,
            end_lineno=6,
            end_col_offset=29,
            module='odoo.http',
            names=[alias(name='request', asname=None)],
            level=0,
        ),
        ClassDef(
            lineno=9,
            col_offset=0,
            end_lineno=18,
            end_col_offset=88,
            name='ContactController',
            bases=[Name(lineno=9, col_offset=24, end_lineno=9, end_col_offset=35, id='WebsiteForm', ctx=Load())],
            keywords=[],
            body=[
                FunctionDef(
                    lineno=11,
                    col_offset=4,
                    end_lineno=18,
                    end_col_offset=88,
                    name='_handle_website_form',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=11, col_offset=29, end_lineno=11, end_col_offset=33, arg='self', annotation=None, type_comment=None),
                            arg(lineno=11, col_offset=35, end_lineno=11, end_col_offset=45, arg='model_name', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=arg(lineno=11, col_offset=49, end_lineno=11, end_col_offset=55, arg='kwargs', annotation=None, type_comment=None),
                        defaults=[],
                    ),
                    body=[
                        If(
                            lineno=12,
                            col_offset=8,
                            end_lineno=16,
                            end_col_offset=73,
                            test=Compare(
                                lineno=12,
                                col_offset=11,
                                end_lineno=12,
                                end_col_offset=35,
                                left=Name(lineno=12, col_offset=11, end_lineno=12, end_col_offset=21, id='model_name', ctx=Load()),
                                ops=[Eq()],
                                comparators=[Constant(lineno=12, col_offset=25, end_lineno=12, end_col_offset=35, value='crm.lead', kind=None)],
                            ),
                            body=[
                                Assign(
                                    lineno=16,
                                    col_offset=12,
                                    end_lineno=16,
                                    end_col_offset=73,
                                    targets=[
                                        Subscript(
                                            lineno=16,
                                            col_offset=12,
                                            end_lineno=16,
                                            end_col_offset=39,
                                            value=Attribute(
                                                lineno=16,
                                                col_offset=12,
                                                end_lineno=16,
                                                end_col_offset=26,
                                                value=Name(lineno=16, col_offset=12, end_lineno=16, end_col_offset=19, id='request', ctx=Load()),
                                                attr='params',
                                                ctx=Load(),
                                            ),
                                            slice=Constant(lineno=16, col_offset=27, end_lineno=16, end_col_offset=38, value='reveal_ip', kind=None),
                                            ctx=Store(),
                                        ),
                                    ],
                                    value=Attribute(
                                        lineno=16,
                                        col_offset=42,
                                        end_lineno=16,
                                        end_col_offset=73,
                                        value=Attribute(
                                            lineno=16,
                                            col_offset=42,
                                            end_lineno=16,
                                            end_col_offset=61,
                                            value=Name(lineno=16, col_offset=42, end_lineno=16, end_col_offset=49, id='request', ctx=Load()),
                                            attr='httprequest',
                                            ctx=Load(),
                                        ),
                                        attr='remote_addr',
                                        ctx=Load(),
                                    ),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[],
                        ),
                        Return(
                            lineno=18,
                            col_offset=8,
                            end_lineno=18,
                            end_col_offset=88,
                            value=Call(
                                lineno=18,
                                col_offset=15,
                                end_lineno=18,
                                end_col_offset=88,
                                func=Attribute(
                                    lineno=18,
                                    col_offset=15,
                                    end_lineno=18,
                                    end_col_offset=66,
                                    value=Call(
                                        lineno=18,
                                        col_offset=15,
                                        end_lineno=18,
                                        end_col_offset=45,
                                        func=Name(lineno=18, col_offset=15, end_lineno=18, end_col_offset=20, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=18, col_offset=21, end_lineno=18, end_col_offset=38, id='ContactController', ctx=Load()),
                                            Name(lineno=18, col_offset=40, end_lineno=18, end_col_offset=44, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='_handle_website_form',
                                    ctx=Load(),
                                ),
                                args=[Name(lineno=18, col_offset=67, end_lineno=18, end_col_offset=77, id='model_name', ctx=Load())],
                                keywords=[
                                    keyword(
                                        lineno=18,
                                        col_offset=79,
                                        end_lineno=18,
                                        end_col_offset=87,
                                        arg=None,
                                        value=Name(lineno=18, col_offset=81, end_lineno=18, end_col_offset=87, id='kwargs', ctx=Load()),
                                    ),
                                ],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
