Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=34,
            module='odoo',
            names=[
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
                alias(name='_', asname=None),
            ],
            level=0,
        ),
        ImportFrom(
            lineno=5,
            col_offset=0,
            end_lineno=5,
            end_col_offset=37,
            module='odoo.exceptions',
            names=[alias(name='UserError', asname=None)],
            level=0,
        ),
        ClassDef(
            lineno=8,
            col_offset=0,
            end_lineno=26,
            end_col_offset=51,
            name='StockQuant',
            bases=[
                Attribute(
                    lineno=8,
                    col_offset=17,
                    end_lineno=8,
                    end_col_offset=29,
                    value=Name(lineno=8, col_offset=17, end_lineno=8, end_col_offset=23, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=9,
                    col_offset=4,
                    end_lineno=9,
                    end_col_offset=28,
                    targets=[Name(lineno=9, col_offset=4, end_lineno=9, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=9, col_offset=15, end_lineno=9, end_col_offset=28, value='stock.quant', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=11,
                    col_offset=4,
                    end_lineno=11,
                    end_col_offset=81,
                    targets=[Name(lineno=11, col_offset=4, end_lineno=11, end_col_offset=18, id='is_subcontract', ctx=Store())],
                    value=Call(
                        lineno=11,
                        col_offset=21,
                        end_lineno=11,
                        end_col_offset=81,
                        func=Attribute(
                            lineno=11,
                            col_offset=21,
                            end_lineno=11,
                            end_col_offset=35,
                            value=Name(lineno=11, col_offset=21, end_lineno=11, end_col_offset=27, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=11,
                                col_offset=36,
                                end_lineno=11,
                                end_col_offset=47,
                                arg='store',
                                value=Constant(lineno=11, col_offset=42, end_lineno=11, end_col_offset=47, value=False, kind=None),
                            ),
                            keyword(
                                lineno=11,
                                col_offset=49,
                                end_lineno=11,
                                end_col_offset=80,
                                arg='search',
                                value=Constant(lineno=11, col_offset=56, end_lineno=11, end_col_offset=80, value='_search_is_subcontract', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=13,
                    col_offset=4,
                    end_lineno=26,
                    end_col_offset=51,
                    name='_search_is_subcontract',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=13, col_offset=31, end_lineno=13, end_col_offset=35, arg='self', annotation=None, type_comment=None),
                            arg(lineno=13, col_offset=37, end_lineno=13, end_col_offset=45, arg='operator', annotation=None, type_comment=None),
                            arg(lineno=13, col_offset=47, end_lineno=13, end_col_offset=52, arg='value', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        If(
                            lineno=14,
                            col_offset=8,
                            end_lineno=15,
                            end_col_offset=57,
                            test=BoolOp(
                                lineno=14,
                                col_offset=11,
                                end_lineno=14,
                                end_col_offset=69,
                                op=Or(),
                                values=[
                                    Compare(
                                        lineno=14,
                                        col_offset=11,
                                        end_lineno=14,
                                        end_col_offset=38,
                                        left=Name(lineno=14, col_offset=11, end_lineno=14, end_col_offset=19, id='operator', ctx=Load()),
                                        ops=[NotIn()],
                                        comparators=[
                                            List(
                                                lineno=14,
                                                col_offset=27,
                                                end_lineno=14,
                                                end_col_offset=38,
                                                elts=[
                                                    Constant(lineno=14, col_offset=28, end_lineno=14, end_col_offset=31, value='=', kind=None),
                                                    Constant(lineno=14, col_offset=33, end_lineno=14, end_col_offset=37, value='!=', kind=None),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                    ),
                                    UnaryOp(
                                        lineno=14,
                                        col_offset=42,
                                        end_lineno=14,
                                        end_col_offset=69,
                                        op=Not(),
                                        operand=Call(
                                            lineno=14,
                                            col_offset=46,
                                            end_lineno=14,
                                            end_col_offset=69,
                                            func=Name(lineno=14, col_offset=46, end_lineno=14, end_col_offset=56, id='isinstance', ctx=Load()),
                                            args=[
                                                Name(lineno=14, col_offset=57, end_lineno=14, end_col_offset=62, id='value', ctx=Load()),
                                                Name(lineno=14, col_offset=64, end_lineno=14, end_col_offset=68, id='bool', ctx=Load()),
                                            ],
                                            keywords=[],
                                        ),
                                    ),
                                ],
                            ),
                            body=[
                                Raise(
                                    lineno=15,
                                    col_offset=12,
                                    end_lineno=15,
                                    end_col_offset=57,
                                    exc=Call(
                                        lineno=15,
                                        col_offset=18,
                                        end_lineno=15,
                                        end_col_offset=57,
                                        func=Name(lineno=15, col_offset=18, end_lineno=15, end_col_offset=27, id='UserError', ctx=Load()),
                                        args=[
                                            Call(
                                                lineno=15,
                                                col_offset=28,
                                                end_lineno=15,
                                                end_col_offset=56,
                                                func=Name(lineno=15, col_offset=28, end_lineno=15, end_col_offset=29, id='_', ctx=Load()),
                                                args=[Constant(lineno=15, col_offset=30, end_lineno=15, end_col_offset=55, value='Operation not supported', kind=None)],
                                                keywords=[],
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                    cause=None,
                                ),
                            ],
                            orelse=[],
                        ),
                        Assign(
                            lineno=17,
                            col_offset=8,
                            end_lineno=17,
                            end_col_offset=93,
                            targets=[Name(lineno=17, col_offset=8, end_lineno=17, end_col_offset=29, id='subcontract_locations', ctx=Store())],
                            value=Attribute(
                                lineno=17,
                                col_offset=32,
                                end_lineno=17,
                                end_col_offset=93,
                                value=Call(
                                    lineno=17,
                                    col_offset=32,
                                    end_lineno=17,
                                    end_col_offset=66,
                                    func=Attribute(
                                        lineno=17,
                                        col_offset=32,
                                        end_lineno=17,
                                        end_col_offset=62,
                                        value=Subscript(
                                            lineno=17,
                                            col_offset=32,
                                            end_lineno=17,
                                            end_col_offset=55,
                                            value=Attribute(
                                                lineno=17,
                                                col_offset=32,
                                                end_lineno=17,
                                                end_col_offset=40,
                                                value=Name(lineno=17, col_offset=32, end_lineno=17, end_col_offset=36, id='self', ctx=Load()),
                                                attr='env',
                                                ctx=Load(),
                                            ),
                                            slice=Constant(lineno=17, col_offset=41, end_lineno=17, end_col_offset=54, value='res.company', kind=None),
                                            ctx=Load(),
                                        ),
                                        attr='search',
                                        ctx=Load(),
                                    ),
                                    args=[List(lineno=17, col_offset=63, end_lineno=17, end_col_offset=65, elts=[], ctx=Load())],
                                    keywords=[],
                                ),
                                attr='subcontracting_location_id',
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=19,
                            col_offset=8,
                            end_lineno=21,
                            end_col_offset=14,
                            targets=[Name(lineno=19, col_offset=8, end_lineno=19, end_col_offset=17, id='quant_ids', ctx=Store())],
                            value=Attribute(
                                lineno=19,
                                col_offset=20,
                                end_lineno=21,
                                end_col_offset=14,
                                value=Call(
                                    lineno=19,
                                    col_offset=20,
                                    end_lineno=21,
                                    end_col_offset=10,
                                    func=Attribute(
                                        lineno=19,
                                        col_offset=20,
                                        end_lineno=19,
                                        end_col_offset=50,
                                        value=Subscript(
                                            lineno=19,
                                            col_offset=20,
                                            end_lineno=19,
                                            end_col_offset=43,
                                            value=Attribute(
                                                lineno=19,
                                                col_offset=20,
                                                end_lineno=19,
                                                end_col_offset=28,
                                                value=Name(lineno=19, col_offset=20, end_lineno=19, end_col_offset=24, id='self', ctx=Load()),
                                                attr='env',
                                                ctx=Load(),
                                            ),
                                            slice=Constant(lineno=19, col_offset=29, end_lineno=19, end_col_offset=42, value='stock.quant', kind=None),
                                            ctx=Load(),
                                        ),
                                        attr='search',
                                        ctx=Load(),
                                    ),
                                    args=[
                                        List(
                                            lineno=19,
                                            col_offset=51,
                                            end_lineno=21,
                                            end_col_offset=9,
                                            elts=[
                                                Tuple(
                                                    lineno=20,
                                                    col_offset=12,
                                                    end_lineno=20,
                                                    end_col_offset=60,
                                                    elts=[
                                                        Constant(lineno=20, col_offset=13, end_lineno=20, end_col_offset=26, value='location_id', kind=None),
                                                        Constant(lineno=20, col_offset=28, end_lineno=20, end_col_offset=32, value='in', kind=None),
                                                        Attribute(
                                                            lineno=20,
                                                            col_offset=34,
                                                            end_lineno=20,
                                                            end_col_offset=59,
                                                            value=Name(lineno=20, col_offset=34, end_lineno=20, end_col_offset=55, id='subcontract_locations', ctx=Load()),
                                                            attr='ids',
                                                            ctx=Load(),
                                                        ),
                                                    ],
                                                    ctx=Load(),
                                                ),
                                            ],
                                            ctx=Load(),
                                        ),
                                    ],
                                    keywords=[],
                                ),
                                attr='ids',
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        If(
                            lineno=22,
                            col_offset=8,
                            end_lineno=25,
                            end_col_offset=34,
                            test=BoolOp(
                                lineno=22,
                                col_offset=11,
                                end_lineno=22,
                                end_col_offset=87,
                                op=Or(),
                                values=[
                                    BoolOp(
                                        lineno=22,
                                        col_offset=12,
                                        end_lineno=22,
                                        end_col_offset=46,
                                        op=And(),
                                        values=[
                                            Compare(
                                                lineno=22,
                                                col_offset=12,
                                                end_lineno=22,
                                                end_col_offset=28,
                                                left=Name(lineno=22, col_offset=12, end_lineno=22, end_col_offset=20, id='operator', ctx=Load()),
                                                ops=[Eq()],
                                                comparators=[Constant(lineno=22, col_offset=24, end_lineno=22, end_col_offset=28, value='!=', kind=None)],
                                            ),
                                            Compare(
                                                lineno=22,
                                                col_offset=33,
                                                end_lineno=22,
                                                end_col_offset=46,
                                                left=Name(lineno=22, col_offset=33, end_lineno=22, end_col_offset=38, id='value', ctx=Load()),
                                                ops=[Is()],
                                                comparators=[Constant(lineno=22, col_offset=42, end_lineno=22, end_col_offset=46, value=True, kind=None)],
                                            ),
                                        ],
                                    ),
                                    BoolOp(
                                        lineno=22,
                                        col_offset=52,
                                        end_lineno=22,
                                        end_col_offset=86,
                                        op=And(),
                                        values=[
                                            Compare(
                                                lineno=22,
                                                col_offset=52,
                                                end_lineno=22,
                                                end_col_offset=67,
                                                left=Name(lineno=22, col_offset=52, end_lineno=22, end_col_offset=60, id='operator', ctx=Load()),
                                                ops=[Eq()],
                                                comparators=[Constant(lineno=22, col_offset=64, end_lineno=22, end_col_offset=67, value='=', kind=None)],
                                            ),
                                            Compare(
                                                lineno=22,
                                                col_offset=72,
                                                end_lineno=22,
                                                end_col_offset=86,
                                                left=Name(lineno=22, col_offset=72, end_lineno=22, end_col_offset=77, id='value', ctx=Load()),
                                                ops=[Is()],
                                                comparators=[Constant(lineno=22, col_offset=81, end_lineno=22, end_col_offset=86, value=False, kind=None)],
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                            body=[
                                Assign(
                                    lineno=23,
                                    col_offset=12,
                                    end_lineno=23,
                                    end_col_offset=38,
                                    targets=[Name(lineno=23, col_offset=12, end_lineno=23, end_col_offset=27, id='domain_operator', ctx=Store())],
                                    value=Constant(lineno=23, col_offset=30, end_lineno=23, end_col_offset=38, value='not in', kind=None),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[
                                Assign(
                                    lineno=25,
                                    col_offset=12,
                                    end_lineno=25,
                                    end_col_offset=34,
                                    targets=[Name(lineno=25, col_offset=12, end_lineno=25, end_col_offset=27, id='domain_operator', ctx=Store())],
                                    value=Constant(lineno=25, col_offset=30, end_lineno=25, end_col_offset=34, value='in', kind=None),
                                    type_comment=None,
                                ),
                            ],
                        ),
                        Return(
                            lineno=26,
                            col_offset=8,
                            end_lineno=26,
                            end_col_offset=51,
                            value=List(
                                lineno=26,
                                col_offset=15,
                                end_lineno=26,
                                end_col_offset=51,
                                elts=[
                                    Tuple(
                                        lineno=26,
                                        col_offset=16,
                                        end_lineno=26,
                                        end_col_offset=50,
                                        elts=[
                                            Constant(lineno=26, col_offset=17, end_lineno=26, end_col_offset=21, value='id', kind=None),
                                            Name(lineno=26, col_offset=23, end_lineno=26, end_col_offset=38, id='domain_operator', ctx=Load()),
                                            Name(lineno=26, col_offset=40, end_lineno=26, end_col_offset=49, id='quant_ids', ctx=Load()),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                ctx=Load(),
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
