Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=41,
            module='odoo',
            names=[
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
                alias(name='_', asname=None),
                alias(name='tools', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=43,
            end_col_offset=21,
            name='MassMailing',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=18,
                    end_lineno=7,
                    end_col_offset=30,
                    value=Name(lineno=7, col_offset=18, end_lineno=7, end_col_offset=24, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=29,
                    targets=[Name(lineno=8, col_offset=4, end_lineno=8, end_col_offset=9, id='_name', ctx=Store())],
                    value=Constant(lineno=8, col_offset=12, end_lineno=8, end_col_offset=29, value='mailing.mailing', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=9,
                    col_offset=4,
                    end_lineno=9,
                    end_col_offset=32,
                    targets=[Name(lineno=9, col_offset=4, end_lineno=9, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=9, col_offset=15, end_lineno=9, end_col_offset=32, value='mailing.mailing', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=11,
                    col_offset=4,
                    end_lineno=11,
                    end_col_offset=73,
                    targets=[Name(lineno=11, col_offset=4, end_lineno=11, end_col_offset=13, id='use_leads', ctx=Store())],
                    value=Call(
                        lineno=11,
                        col_offset=16,
                        end_lineno=11,
                        end_col_offset=73,
                        func=Attribute(
                            lineno=11,
                            col_offset=16,
                            end_lineno=11,
                            end_col_offset=30,
                            value=Name(lineno=11, col_offset=16, end_lineno=11, end_col_offset=22, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=11, col_offset=31, end_lineno=11, end_col_offset=42, value='Use Leads', kind=None)],
                        keywords=[
                            keyword(
                                lineno=11,
                                col_offset=44,
                                end_lineno=11,
                                end_col_offset=72,
                                arg='compute',
                                value=Constant(lineno=11, col_offset=52, end_lineno=11, end_col_offset=72, value='_compute_use_leads', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=12,
                    col_offset=4,
                    end_lineno=12,
                    end_col_offset=140,
                    targets=[Name(lineno=12, col_offset=4, end_lineno=12, end_col_offset=18, id='crm_lead_count', ctx=Store())],
                    value=Call(
                        lineno=12,
                        col_offset=21,
                        end_lineno=12,
                        end_col_offset=140,
                        func=Attribute(
                            lineno=12,
                            col_offset=21,
                            end_lineno=12,
                            end_col_offset=35,
                            value=Name(lineno=12, col_offset=21, end_lineno=12, end_col_offset=27, id='fields', ctx=Load()),
                            attr='Integer',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=12, col_offset=36, end_lineno=12, end_col_offset=63, value='Leads/Opportunities Count', kind=None)],
                        keywords=[
                            keyword(
                                lineno=12,
                                col_offset=65,
                                end_lineno=12,
                                end_col_offset=104,
                                arg='groups',
                                value=Constant(lineno=12, col_offset=72, end_lineno=12, end_col_offset=104, value='sales_team.group_sale_salesman', kind=None),
                            ),
                            keyword(
                                lineno=12,
                                col_offset=106,
                                end_lineno=12,
                                end_col_offset=139,
                                arg='compute',
                                value=Constant(lineno=12, col_offset=114, end_lineno=12, end_col_offset=139, value='_compute_crm_lead_count', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=14,
                    col_offset=4,
                    end_lineno=15,
                    end_col_offset=70,
                    name='_compute_use_leads',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=14, col_offset=27, end_lineno=14, end_col_offset=31, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=15,
                            col_offset=8,
                            end_lineno=15,
                            end_col_offset=70,
                            targets=[
                                Attribute(
                                    lineno=15,
                                    col_offset=8,
                                    end_lineno=15,
                                    end_col_offset=22,
                                    value=Name(lineno=15, col_offset=8, end_lineno=15, end_col_offset=12, id='self', ctx=Load()),
                                    attr='use_leads',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=15,
                                col_offset=25,
                                end_lineno=15,
                                end_col_offset=70,
                                func=Attribute(
                                    lineno=15,
                                    col_offset=25,
                                    end_lineno=15,
                                    end_col_offset=48,
                                    value=Attribute(
                                        lineno=15,
                                        col_offset=25,
                                        end_lineno=15,
                                        end_col_offset=38,
                                        value=Attribute(
                                            lineno=15,
                                            col_offset=25,
                                            end_lineno=15,
                                            end_col_offset=33,
                                            value=Name(lineno=15, col_offset=25, end_lineno=15, end_col_offset=29, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        attr='user',
                                        ctx=Load(),
                                    ),
                                    attr='has_group',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=15, col_offset=49, end_lineno=15, end_col_offset=69, value='crm.group_use_lead', kind=None)],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=17,
                    col_offset=4,
                    end_lineno=24,
                    end_col_offset=87,
                    name='_compute_crm_lead_count',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=17, col_offset=32, end_lineno=17, end_col_offset=36, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=18,
                            col_offset=8,
                            end_lineno=21,
                            end_col_offset=9,
                            targets=[Name(lineno=18, col_offset=8, end_lineno=18, end_col_offset=17, id='lead_data', ctx=Store())],
                            value=Call(
                                lineno=18,
                                col_offset=20,
                                end_lineno=21,
                                end_col_offset=9,
                                func=Attribute(
                                    lineno=18,
                                    col_offset=20,
                                    end_lineno=18,
                                    end_col_offset=83,
                                    value=Call(
                                        lineno=18,
                                        col_offset=20,
                                        end_lineno=18,
                                        end_col_offset=72,
                                        func=Attribute(
                                            lineno=18,
                                            col_offset=20,
                                            end_lineno=18,
                                            end_col_offset=53,
                                            value=Subscript(
                                                lineno=18,
                                                col_offset=20,
                                                end_lineno=18,
                                                end_col_offset=40,
                                                value=Attribute(
                                                    lineno=18,
                                                    col_offset=20,
                                                    end_lineno=18,
                                                    end_col_offset=28,
                                                    value=Name(lineno=18, col_offset=20, end_lineno=18, end_col_offset=24, id='self', ctx=Load()),
                                                    attr='env',
                                                    ctx=Load(),
                                                ),
                                                slice=Constant(lineno=18, col_offset=29, end_lineno=18, end_col_offset=39, value='crm.lead', kind=None),
                                                ctx=Load(),
                                            ),
                                            attr='with_context',
                                            ctx=Load(),
                                        ),
                                        args=[],
                                        keywords=[
                                            keyword(
                                                lineno=18,
                                                col_offset=54,
                                                end_lineno=18,
                                                end_col_offset=71,
                                                arg='active_test',
                                                value=Constant(lineno=18, col_offset=66, end_lineno=18, end_col_offset=71, value=False, kind=None),
                                            ),
                                        ],
                                    ),
                                    attr='read_group',
                                    ctx=Load(),
                                ),
                                args=[
                                    List(
                                        lineno=19,
                                        col_offset=12,
                                        end_lineno=19,
                                        end_col_offset=53,
                                        elts=[
                                            Tuple(
                                                lineno=19,
                                                col_offset=13,
                                                end_lineno=19,
                                                end_col_offset=52,
                                                elts=[
                                                    Constant(lineno=19, col_offset=14, end_lineno=19, end_col_offset=25, value='source_id', kind=None),
                                                    Constant(lineno=19, col_offset=27, end_lineno=19, end_col_offset=31, value='in', kind=None),
                                                    Attribute(
                                                        lineno=19,
                                                        col_offset=33,
                                                        end_lineno=19,
                                                        end_col_offset=51,
                                                        value=Attribute(
                                                            lineno=19,
                                                            col_offset=33,
                                                            end_lineno=19,
                                                            end_col_offset=47,
                                                            value=Name(lineno=19, col_offset=33, end_lineno=19, end_col_offset=37, id='self', ctx=Load()),
                                                            attr='source_id',
                                                            ctx=Load(),
                                                        ),
                                                        attr='ids',
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                    List(
                                        lineno=20,
                                        col_offset=12,
                                        end_lineno=20,
                                        end_col_offset=25,
                                        elts=[Constant(lineno=20, col_offset=13, end_lineno=20, end_col_offset=24, value='source_id', kind=None)],
                                        ctx=Load(),
                                    ),
                                    List(
                                        lineno=20,
                                        col_offset=27,
                                        end_lineno=20,
                                        end_col_offset=40,
                                        elts=[Constant(lineno=20, col_offset=28, end_lineno=20, end_col_offset=39, value='source_id', kind=None)],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=22,
                            col_offset=8,
                            end_lineno=22,
                            end_col_offset=94,
                            targets=[Name(lineno=22, col_offset=8, end_lineno=22, end_col_offset=19, id='mapped_data', ctx=Store())],
                            value=DictComp(
                                lineno=22,
                                col_offset=22,
                                end_lineno=22,
                                end_col_offset=94,
                                key=Subscript(
                                    lineno=22,
                                    col_offset=23,
                                    end_lineno=22,
                                    end_col_offset=44,
                                    value=Subscript(
                                        lineno=22,
                                        col_offset=23,
                                        end_lineno=22,
                                        end_col_offset=41,
                                        value=Name(lineno=22, col_offset=23, end_lineno=22, end_col_offset=28, id='datum', ctx=Load()),
                                        slice=Constant(lineno=22, col_offset=29, end_lineno=22, end_col_offset=40, value='source_id', kind=None),
                                        ctx=Load(),
                                    ),
                                    slice=Constant(lineno=22, col_offset=42, end_lineno=22, end_col_offset=43, value=0, kind=None),
                                    ctx=Load(),
                                ),
                                value=Subscript(
                                    lineno=22,
                                    col_offset=46,
                                    end_lineno=22,
                                    end_col_offset=70,
                                    value=Name(lineno=22, col_offset=46, end_lineno=22, end_col_offset=51, id='datum', ctx=Load()),
                                    slice=Constant(lineno=22, col_offset=52, end_lineno=22, end_col_offset=69, value='source_id_count', kind=None),
                                    ctx=Load(),
                                ),
                                generators=[
                                    comprehension(
                                        target=Name(lineno=22, col_offset=75, end_lineno=22, end_col_offset=80, id='datum', ctx=Store()),
                                        iter=Name(lineno=22, col_offset=84, end_lineno=22, end_col_offset=93, id='lead_data', ctx=Load()),
                                        ifs=[],
                                        is_async=0,
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                        For(
                            lineno=23,
                            col_offset=8,
                            end_lineno=24,
                            end_col_offset=87,
                            target=Name(lineno=23, col_offset=12, end_lineno=23, end_col_offset=24, id='mass_mailing', ctx=Store()),
                            iter=Name(lineno=23, col_offset=28, end_lineno=23, end_col_offset=32, id='self', ctx=Load()),
                            body=[
                                Assign(
                                    lineno=24,
                                    col_offset=12,
                                    end_lineno=24,
                                    end_col_offset=87,
                                    targets=[
                                        Attribute(
                                            lineno=24,
                                            col_offset=12,
                                            end_lineno=24,
                                            end_col_offset=39,
                                            value=Name(lineno=24, col_offset=12, end_lineno=24, end_col_offset=24, id='mass_mailing', ctx=Load()),
                                            attr='crm_lead_count',
                                            ctx=Store(),
                                        ),
                                    ],
                                    value=Call(
                                        lineno=24,
                                        col_offset=42,
                                        end_lineno=24,
                                        end_col_offset=87,
                                        func=Attribute(
                                            lineno=24,
                                            col_offset=42,
                                            end_lineno=24,
                                            end_col_offset=57,
                                            value=Name(lineno=24, col_offset=42, end_lineno=24, end_col_offset=53, id='mapped_data', ctx=Load()),
                                            attr='get',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Attribute(
                                                lineno=24,
                                                col_offset=58,
                                                end_lineno=24,
                                                end_col_offset=83,
                                                value=Attribute(
                                                    lineno=24,
                                                    col_offset=58,
                                                    end_lineno=24,
                                                    end_col_offset=80,
                                                    value=Name(lineno=24, col_offset=58, end_lineno=24, end_col_offset=70, id='mass_mailing', ctx=Load()),
                                                    attr='source_id',
                                                    ctx=Load(),
                                                ),
                                                attr='id',
                                                ctx=Load(),
                                            ),
                                            Constant(lineno=24, col_offset=85, end_lineno=24, end_col_offset=86, value=0, kind=None),
                                        ],
                                        keywords=[],
                                    ),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[],
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=26,
                    col_offset=4,
                    end_lineno=32,
                    end_col_offset=21,
                    name='action_redirect_to_leads_and_opportunities',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=26, col_offset=51, end_lineno=26, end_col_offset=55, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=27,
                            col_offset=8,
                            end_lineno=27,
                            end_col_offset=91,
                            targets=[Name(lineno=27, col_offset=8, end_lineno=27, end_col_offset=12, id='view', ctx=Store())],
                            value=IfExp(
                                lineno=27,
                                col_offset=15,
                                end_lineno=27,
                                end_col_offset=91,
                                test=Attribute(
                                    lineno=27,
                                    col_offset=43,
                                    end_lineno=27,
                                    end_col_offset=57,
                                    value=Name(lineno=27, col_offset=43, end_lineno=27, end_col_offset=47, id='self', ctx=Load()),
                                    attr='use_leads',
                                    ctx=Load(),
                                ),
                                body=Constant(lineno=27, col_offset=15, end_lineno=27, end_col_offset=39, value='crm.crm_lead_all_leads', kind=None),
                                orelse=Constant(lineno=27, col_offset=63, end_lineno=27, end_col_offset=91, value='crm.crm_lead_opportunities', kind=None),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=28,
                            col_offset=8,
                            end_lineno=28,
                            end_col_offset=52,
                            targets=[Name(lineno=28, col_offset=8, end_lineno=28, end_col_offset=14, id='action', ctx=Store())],
                            value=Subscript(
                                lineno=28,
                                col_offset=17,
                                end_lineno=28,
                                end_col_offset=52,
                                value=Call(
                                    lineno=28,
                                    col_offset=17,
                                    end_lineno=28,
                                    end_col_offset=49,
                                    func=Attribute(
                                        lineno=28,
                                        col_offset=17,
                                        end_lineno=28,
                                        end_col_offset=47,
                                        value=Call(
                                            lineno=28,
                                            col_offset=17,
                                            end_lineno=28,
                                            end_col_offset=42,
                                            func=Attribute(
                                                lineno=28,
                                                col_offset=17,
                                                end_lineno=28,
                                                end_col_offset=40,
                                                value=Call(
                                                    lineno=28,
                                                    col_offset=17,
                                                    end_lineno=28,
                                                    end_col_offset=35,
                                                    func=Attribute(
                                                        lineno=28,
                                                        col_offset=17,
                                                        end_lineno=28,
                                                        end_col_offset=29,
                                                        value=Attribute(
                                                            lineno=28,
                                                            col_offset=17,
                                                            end_lineno=28,
                                                            end_col_offset=25,
                                                            value=Name(lineno=28, col_offset=17, end_lineno=28, end_col_offset=21, id='self', ctx=Load()),
                                                            attr='env',
                                                            ctx=Load(),
                                                        ),
                                                        attr='ref',
                                                        ctx=Load(),
                                                    ),
                                                    args=[Name(lineno=28, col_offset=30, end_lineno=28, end_col_offset=34, id='view', ctx=Load())],
                                                    keywords=[],
                                                ),
                                                attr='sudo',
                                                ctx=Load(),
                                            ),
                                            args=[],
                                            keywords=[],
                                        ),
                                        attr='read',
                                        ctx=Load(),
                                    ),
                                    args=[],
                                    keywords=[],
                                ),
                                slice=Constant(lineno=28, col_offset=50, end_lineno=28, end_col_offset=51, value=0, kind=None),
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=29,
                            col_offset=8,
                            end_lineno=29,
                            end_col_offset=69,
                            targets=[
                                Subscript(
                                    lineno=29,
                                    col_offset=8,
                                    end_lineno=29,
                                    end_col_offset=27,
                                    value=Name(lineno=29, col_offset=8, end_lineno=29, end_col_offset=14, id='action', ctx=Load()),
                                    slice=Constant(lineno=29, col_offset=15, end_lineno=29, end_col_offset=26, value='view_mode', kind=None),
                                    ctx=Store(),
                                ),
                            ],
                            value=Constant(lineno=29, col_offset=30, end_lineno=29, end_col_offset=69, value='tree,kanban,graph,pivot,form,calendar', kind=None),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=30,
                            col_offset=8,
                            end_lineno=30,
                            end_col_offset=68,
                            targets=[
                                Subscript(
                                    lineno=30,
                                    col_offset=8,
                                    end_lineno=30,
                                    end_col_offset=24,
                                    value=Name(lineno=30, col_offset=8, end_lineno=30, end_col_offset=14, id='action', ctx=Load()),
                                    slice=Constant(lineno=30, col_offset=15, end_lineno=30, end_col_offset=23, value='domain', kind=None),
                                    ctx=Store(),
                                ),
                            ],
                            value=List(
                                lineno=30,
                                col_offset=27,
                                end_lineno=30,
                                end_col_offset=68,
                                elts=[
                                    Tuple(
                                        lineno=30,
                                        col_offset=28,
                                        end_lineno=30,
                                        end_col_offset=67,
                                        elts=[
                                            Constant(lineno=30, col_offset=29, end_lineno=30, end_col_offset=40, value='source_id', kind=None),
                                            Constant(lineno=30, col_offset=42, end_lineno=30, end_col_offset=46, value='in', kind=None),
                                            Attribute(
                                                lineno=30,
                                                col_offset=48,
                                                end_lineno=30,
                                                end_col_offset=66,
                                                value=Attribute(
                                                    lineno=30,
                                                    col_offset=48,
                                                    end_lineno=30,
                                                    end_col_offset=62,
                                                    value=Name(lineno=30, col_offset=48, end_lineno=30, end_col_offset=52, id='self', ctx=Load()),
                                                    attr='source_id',
                                                    ctx=Load(),
                                                ),
                                                attr='ids',
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=31,
                            col_offset=8,
                            end_lineno=31,
                            end_col_offset=67,
                            targets=[
                                Subscript(
                                    lineno=31,
                                    col_offset=8,
                                    end_lineno=31,
                                    end_col_offset=25,
                                    value=Name(lineno=31, col_offset=8, end_lineno=31, end_col_offset=14, id='action', ctx=Load()),
                                    slice=Constant(lineno=31, col_offset=15, end_lineno=31, end_col_offset=24, value='context', kind=None),
                                    ctx=Store(),
                                ),
                            ],
                            value=Dict(
                                lineno=31,
                                col_offset=28,
                                end_lineno=31,
                                end_col_offset=67,
                                keys=[
                                    Constant(lineno=31, col_offset=29, end_lineno=31, end_col_offset=42, value='active_test', kind=None),
                                    Constant(lineno=31, col_offset=51, end_lineno=31, end_col_offset=59, value='create', kind=None),
                                ],
                                values=[
                                    Constant(lineno=31, col_offset=44, end_lineno=31, end_col_offset=49, value=False, kind=None),
                                    Constant(lineno=31, col_offset=61, end_lineno=31, end_col_offset=66, value=False, kind=None),
                                ],
                            ),
                            type_comment=None,
                        ),
                        Return(
                            lineno=32,
                            col_offset=8,
                            end_lineno=32,
                            end_col_offset=21,
                            value=Name(lineno=32, col_offset=15, end_lineno=32, end_col_offset=21, id='action', ctx=Load()),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=34,
                    col_offset=4,
                    end_lineno=43,
                    end_col_offset=21,
                    name='_prepare_statistics_email_values',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=34, col_offset=41, end_lineno=34, end_col_offset=45, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=35,
                            col_offset=8,
                            end_lineno=35,
                            end_col_offset=25,
                            value=Call(
                                lineno=35,
                                col_offset=8,
                                end_lineno=35,
                                end_col_offset=25,
                                func=Attribute(
                                    lineno=35,
                                    col_offset=8,
                                    end_lineno=35,
                                    end_col_offset=23,
                                    value=Name(lineno=35, col_offset=8, end_lineno=35, end_col_offset=12, id='self', ctx=Load()),
                                    attr='ensure_one',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=36,
                            col_offset=8,
                            end_lineno=36,
                            end_col_offset=76,
                            targets=[Name(lineno=36, col_offset=8, end_lineno=36, end_col_offset=14, id='values', ctx=Store())],
                            value=Call(
                                lineno=36,
                                col_offset=17,
                                end_lineno=36,
                                end_col_offset=76,
                                func=Attribute(
                                    lineno=36,
                                    col_offset=17,
                                    end_lineno=36,
                                    end_col_offset=74,
                                    value=Call(
                                        lineno=36,
                                        col_offset=17,
                                        end_lineno=36,
                                        end_col_offset=41,
                                        func=Name(lineno=36, col_offset=17, end_lineno=36, end_col_offset=22, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=36, col_offset=23, end_lineno=36, end_col_offset=34, id='MassMailing', ctx=Load()),
                                            Name(lineno=36, col_offset=36, end_lineno=36, end_col_offset=40, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='_prepare_statistics_email_values',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        If(
                            lineno=37,
                            col_offset=8,
                            end_lineno=38,
                            end_col_offset=25,
                            test=UnaryOp(
                                lineno=37,
                                col_offset=11,
                                end_lineno=37,
                                end_col_offset=27,
                                op=Not(),
                                operand=Attribute(
                                    lineno=37,
                                    col_offset=15,
                                    end_lineno=37,
                                    end_col_offset=27,
                                    value=Name(lineno=37, col_offset=15, end_lineno=37, end_col_offset=19, id='self', ctx=Load()),
                                    attr='user_id',
                                    ctx=Load(),
                                ),
                            ),
                            body=[
                                Return(
                                    lineno=38,
                                    col_offset=12,
                                    end_lineno=38,
                                    end_col_offset=25,
                                    value=Name(lineno=38, col_offset=19, end_lineno=38, end_col_offset=25, id='values', ctx=Load()),
                                ),
                            ],
                            orelse=[],
                        ),
                        Assign(
                            lineno=39,
                            col_offset=8,
                            end_lineno=42,
                            end_col_offset=9,
                            targets=[
                                Subscript(
                                    lineno=39,
                                    col_offset=8,
                                    end_lineno=39,
                                    end_col_offset=41,
                                    value=Subscript(
                                        lineno=39,
                                        col_offset=8,
                                        end_lineno=39,
                                        end_col_offset=29,
                                        value=Subscript(
                                            lineno=39,
                                            col_offset=8,
                                            end_lineno=39,
                                            end_col_offset=26,
                                            value=Name(lineno=39, col_offset=8, end_lineno=39, end_col_offset=14, id='values', ctx=Load()),
                                            slice=Constant(lineno=39, col_offset=15, end_lineno=39, end_col_offset=25, value='kpi_data', kind=None),
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=39, col_offset=27, end_lineno=39, end_col_offset=28, value=1, kind=None),
                                        ctx=Load(),
                                    ),
                                    slice=Constant(lineno=39, col_offset=30, end_lineno=39, end_col_offset=40, value='kpi_col1', kind=None),
                                    ctx=Store(),
                                ),
                            ],
                            value=Dict(
                                lineno=39,
                                col_offset=44,
                                end_lineno=42,
                                end_col_offset=9,
                                keys=[
                                    Constant(lineno=40, col_offset=12, end_lineno=40, end_col_offset=19, value='value', kind=None),
                                    Constant(lineno=41, col_offset=12, end_lineno=41, end_col_offset=26, value='col_subtitle', kind=None),
                                ],
                                values=[
                                    Call(
                                        lineno=40,
                                        col_offset=21,
                                        end_lineno=40,
                                        end_col_offset=84,
                                        func=Attribute(
                                            lineno=40,
                                            col_offset=21,
                                            end_lineno=40,
                                            end_col_offset=52,
                                            value=Name(lineno=40, col_offset=21, end_lineno=40, end_col_offset=26, id='tools', ctx=Load()),
                                            attr='format_decimalized_number',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Attribute(
                                                lineno=40,
                                                col_offset=53,
                                                end_lineno=40,
                                                end_col_offset=72,
                                                value=Name(lineno=40, col_offset=53, end_lineno=40, end_col_offset=57, id='self', ctx=Load()),
                                                attr='crm_lead_count',
                                                ctx=Load(),
                                            ),
                                        ],
                                        keywords=[
                                            keyword(
                                                lineno=40,
                                                col_offset=74,
                                                end_lineno=40,
                                                end_col_offset=83,
                                                arg='decimal',
                                                value=Constant(lineno=40, col_offset=82, end_lineno=40, end_col_offset=83, value=0, kind=None),
                                            ),
                                        ],
                                    ),
                                    Call(
                                        lineno=41,
                                        col_offset=28,
                                        end_lineno=41,
                                        end_col_offset=38,
                                        func=Name(lineno=41, col_offset=28, end_lineno=41, end_col_offset=29, id='_', ctx=Load()),
                                        args=[Constant(lineno=41, col_offset=30, end_lineno=41, end_col_offset=37, value='LEADS', kind=None)],
                                        keywords=[],
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                        Return(
                            lineno=43,
                            col_offset=8,
                            end_lineno=43,
                            end_col_offset=21,
                            value=Name(lineno=43, col_offset=15, end_lineno=43, end_col_offset=21, id='values', ctx=Load()),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
