Module(
    body=[
        Import(
            lineno=2,
            col_offset=0,
            end_lineno=2,
            end_col_offset=13,
            names=[alias(name='base64', asname=None)],
        ),
        ImportFrom(
            lineno=3,
            col_offset=0,
            end_lineno=3,
            end_col_offset=22,
            module='io',
            names=[alias(name='BytesIO', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=36,
            module='odoo',
            names=[
                alias(name='api', asname=None),
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=46,
            end_col_offset=9,
            name='BaseImportModule',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=23,
                    end_lineno=7,
                    end_col_offset=44,
                    value=Name(lineno=7, col_offset=23, end_lineno=7, end_col_offset=29, id='models', ctx=Load()),
                    attr='TransientModel',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Expr(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=25,
                    value=Constant(lineno=8, col_offset=4, end_lineno=8, end_col_offset=25, value=' Import Module ', kind=None),
                ),
                Assign(
                    lineno=9,
                    col_offset=4,
                    end_lineno=9,
                    end_col_offset=32,
                    targets=[Name(lineno=9, col_offset=4, end_lineno=9, end_col_offset=9, id='_name', ctx=Store())],
                    value=Constant(lineno=9, col_offset=12, end_lineno=9, end_col_offset=32, value='base.import.module', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=10,
                    col_offset=4,
                    end_lineno=10,
                    end_col_offset=34,
                    targets=[Name(lineno=10, col_offset=4, end_lineno=10, end_col_offset=16, id='_description', ctx=Store())],
                    value=Constant(lineno=10, col_offset=19, end_lineno=10, end_col_offset=34, value='Import Module', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=12,
                    col_offset=4,
                    end_lineno=12,
                    end_col_offset=91,
                    targets=[Name(lineno=12, col_offset=4, end_lineno=12, end_col_offset=15, id='module_file', ctx=Store())],
                    value=Call(
                        lineno=12,
                        col_offset=18,
                        end_lineno=12,
                        end_col_offset=91,
                        func=Attribute(
                            lineno=12,
                            col_offset=18,
                            end_lineno=12,
                            end_col_offset=31,
                            value=Name(lineno=12, col_offset=18, end_lineno=12, end_col_offset=24, id='fields', ctx=Load()),
                            attr='Binary',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=12,
                                col_offset=32,
                                end_lineno=12,
                                end_col_offset=57,
                                arg='string',
                                value=Constant(lineno=12, col_offset=39, end_lineno=12, end_col_offset=57, value='Module .ZIP file', kind=None),
                            ),
                            keyword(
                                lineno=12,
                                col_offset=59,
                                end_lineno=12,
                                end_col_offset=72,
                                arg='required',
                                value=Constant(lineno=12, col_offset=68, end_lineno=12, end_col_offset=72, value=True, kind=None),
                            ),
                            keyword(
                                lineno=12,
                                col_offset=74,
                                end_lineno=12,
                                end_col_offset=90,
                                arg='attachment',
                                value=Constant(lineno=12, col_offset=85, end_lineno=12, end_col_offset=90, value=False, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=13,
                    col_offset=4,
                    end_lineno=13,
                    end_col_offset=114,
                    targets=[Name(lineno=13, col_offset=4, end_lineno=13, end_col_offset=9, id='state', ctx=Store())],
                    value=Call(
                        lineno=13,
                        col_offset=12,
                        end_lineno=13,
                        end_col_offset=114,
                        func=Attribute(
                            lineno=13,
                            col_offset=12,
                            end_lineno=13,
                            end_col_offset=28,
                            value=Name(lineno=13, col_offset=12, end_lineno=13, end_col_offset=18, id='fields', ctx=Load()),
                            attr='Selection',
                            ctx=Load(),
                        ),
                        args=[
                            List(
                                lineno=13,
                                col_offset=29,
                                end_lineno=13,
                                end_col_offset=65,
                                elts=[
                                    Tuple(
                                        lineno=13,
                                        col_offset=30,
                                        end_lineno=13,
                                        end_col_offset=46,
                                        elts=[
                                            Constant(lineno=13, col_offset=31, end_lineno=13, end_col_offset=37, value='init', kind=None),
                                            Constant(lineno=13, col_offset=39, end_lineno=13, end_col_offset=45, value='init', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                    Tuple(
                                        lineno=13,
                                        col_offset=48,
                                        end_lineno=13,
                                        end_col_offset=64,
                                        elts=[
                                            Constant(lineno=13, col_offset=49, end_lineno=13, end_col_offset=55, value='done', kind=None),
                                            Constant(lineno=13, col_offset=57, end_lineno=13, end_col_offset=63, value='done', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                ctx=Load(),
                            ),
                        ],
                        keywords=[
                            keyword(
                                lineno=13,
                                col_offset=67,
                                end_lineno=13,
                                end_col_offset=82,
                                arg='string',
                                value=Constant(lineno=13, col_offset=74, end_lineno=13, end_col_offset=82, value='Status', kind=None),
                            ),
                            keyword(
                                lineno=13,
                                col_offset=84,
                                end_lineno=13,
                                end_col_offset=97,
                                arg='readonly',
                                value=Constant(lineno=13, col_offset=93, end_lineno=13, end_col_offset=97, value=True, kind=None),
                            ),
                            keyword(
                                lineno=13,
                                col_offset=99,
                                end_lineno=13,
                                end_col_offset=113,
                                arg='default',
                                value=Constant(lineno=13, col_offset=107, end_lineno=13, end_col_offset=113, value='init', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=14,
                    col_offset=4,
                    end_lineno=14,
                    end_col_offset=34,
                    targets=[Name(lineno=14, col_offset=4, end_lineno=14, end_col_offset=18, id='import_message', ctx=Store())],
                    value=Call(
                        lineno=14,
                        col_offset=21,
                        end_lineno=14,
                        end_col_offset=34,
                        func=Attribute(
                            lineno=14,
                            col_offset=21,
                            end_lineno=14,
                            end_col_offset=32,
                            value=Name(lineno=14, col_offset=21, end_lineno=14, end_col_offset=27, id='fields', ctx=Load()),
                            attr='Text',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=15,
                    col_offset=4,
                    end_lineno=15,
                    end_col_offset=127,
                    targets=[Name(lineno=15, col_offset=4, end_lineno=15, end_col_offset=9, id='force', ctx=Store())],
                    value=Call(
                        lineno=15,
                        col_offset=12,
                        end_lineno=15,
                        end_col_offset=127,
                        func=Attribute(
                            lineno=15,
                            col_offset=12,
                            end_lineno=15,
                            end_col_offset=26,
                            value=Name(lineno=15, col_offset=12, end_lineno=15, end_col_offset=18, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=15,
                                col_offset=27,
                                end_lineno=15,
                                end_col_offset=46,
                                arg='string',
                                value=Constant(lineno=15, col_offset=34, end_lineno=15, end_col_offset=46, value='Force init', kind=None),
                            ),
                            keyword(
                                lineno=15,
                                col_offset=48,
                                end_lineno=15,
                                end_col_offset=126,
                                arg='help',
                                value=Constant(lineno=15, col_offset=53, end_lineno=15, end_col_offset=126, value="Force init mode even if installed. (will update `noupdate='1'` records)", kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=17,
                    col_offset=4,
                    end_lineno=35,
                    end_col_offset=9,
                    name='import_module',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=17, col_offset=22, end_lineno=17, end_col_offset=26, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=18,
                            col_offset=8,
                            end_lineno=18,
                            end_col_offset=25,
                            value=Call(
                                lineno=18,
                                col_offset=8,
                                end_lineno=18,
                                end_col_offset=25,
                                func=Attribute(
                                    lineno=18,
                                    col_offset=8,
                                    end_lineno=18,
                                    end_col_offset=23,
                                    value=Name(lineno=18, col_offset=8, end_lineno=18, end_col_offset=12, id='self', ctx=Load()),
                                    attr='ensure_one',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=19,
                            col_offset=8,
                            end_lineno=19,
                            end_col_offset=47,
                            targets=[Name(lineno=19, col_offset=8, end_lineno=19, end_col_offset=16, id='IrModule', ctx=Store())],
                            value=Subscript(
                                lineno=19,
                                col_offset=19,
                                end_lineno=19,
                                end_col_offset=47,
                                value=Attribute(
                                    lineno=19,
                                    col_offset=19,
                                    end_lineno=19,
                                    end_col_offset=27,
                                    value=Name(lineno=19, col_offset=19, end_lineno=19, end_col_offset=23, id='self', ctx=Load()),
                                    attr='env',
                                    ctx=Load(),
                                ),
                                slice=Constant(lineno=19, col_offset=28, end_lineno=19, end_col_offset=46, value='ir.module.module', kind=None),
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=20,
                            col_offset=8,
                            end_lineno=20,
                            end_col_offset=55,
                            targets=[Name(lineno=20, col_offset=8, end_lineno=20, end_col_offset=16, id='zip_data', ctx=Store())],
                            value=Call(
                                lineno=20,
                                col_offset=19,
                                end_lineno=20,
                                end_col_offset=55,
                                func=Attribute(
                                    lineno=20,
                                    col_offset=19,
                                    end_lineno=20,
                                    end_col_offset=37,
                                    value=Name(lineno=20, col_offset=19, end_lineno=20, end_col_offset=25, id='base64', ctx=Load()),
                                    attr='decodebytes',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=20,
                                        col_offset=38,
                                        end_lineno=20,
                                        end_col_offset=54,
                                        value=Name(lineno=20, col_offset=38, end_lineno=20, end_col_offset=42, id='self', ctx=Load()),
                                        attr='module_file',
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=21,
                            col_offset=8,
                            end_lineno=21,
                            end_col_offset=22,
                            targets=[Name(lineno=21, col_offset=8, end_lineno=21, end_col_offset=10, id='fp', ctx=Store())],
                            value=Call(
                                lineno=21,
                                col_offset=13,
                                end_lineno=21,
                                end_col_offset=22,
                                func=Name(lineno=21, col_offset=13, end_lineno=21, end_col_offset=20, id='BytesIO', ctx=Load()),
                                args=[],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=22,
                            col_offset=8,
                            end_lineno=22,
                            end_col_offset=26,
                            value=Call(
                                lineno=22,
                                col_offset=8,
                                end_lineno=22,
                                end_col_offset=26,
                                func=Attribute(
                                    lineno=22,
                                    col_offset=8,
                                    end_lineno=22,
                                    end_col_offset=16,
                                    value=Name(lineno=22, col_offset=8, end_lineno=22, end_col_offset=10, id='fp', ctx=Load()),
                                    attr='write',
                                    ctx=Load(),
                                ),
                                args=[Name(lineno=22, col_offset=17, end_lineno=22, end_col_offset=25, id='zip_data', ctx=Load())],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=23,
                            col_offset=8,
                            end_lineno=23,
                            end_col_offset=59,
                            targets=[Name(lineno=23, col_offset=8, end_lineno=23, end_col_offset=11, id='res', ctx=Store())],
                            value=Call(
                                lineno=23,
                                col_offset=14,
                                end_lineno=23,
                                end_col_offset=59,
                                func=Attribute(
                                    lineno=23,
                                    col_offset=14,
                                    end_lineno=23,
                                    end_col_offset=37,
                                    value=Name(lineno=23, col_offset=14, end_lineno=23, end_col_offset=22, id='IrModule', ctx=Load()),
                                    attr='import_zipfile',
                                    ctx=Load(),
                                ),
                                args=[Name(lineno=23, col_offset=38, end_lineno=23, end_col_offset=40, id='fp', ctx=Load())],
                                keywords=[
                                    keyword(
                                        lineno=23,
                                        col_offset=42,
                                        end_lineno=23,
                                        end_col_offset=58,
                                        arg='force',
                                        value=Attribute(
                                            lineno=23,
                                            col_offset=48,
                                            end_lineno=23,
                                            end_col_offset=58,
                                            value=Name(lineno=23, col_offset=48, end_lineno=23, end_col_offset=52, id='self', ctx=Load()),
                                            attr='force',
                                            ctx=Load(),
                                        ),
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=24,
                            col_offset=8,
                            end_lineno=24,
                            end_col_offset=63,
                            value=Call(
                                lineno=24,
                                col_offset=8,
                                end_lineno=24,
                                end_col_offset=63,
                                func=Attribute(
                                    lineno=24,
                                    col_offset=8,
                                    end_lineno=24,
                                    end_col_offset=18,
                                    value=Name(lineno=24, col_offset=8, end_lineno=24, end_col_offset=12, id='self', ctx=Load()),
                                    attr='write',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=24,
                                        col_offset=19,
                                        end_lineno=24,
                                        end_col_offset=62,
                                        keys=[
                                            Constant(lineno=24, col_offset=20, end_lineno=24, end_col_offset=27, value='state', kind=None),
                                            Constant(lineno=24, col_offset=37, end_lineno=24, end_col_offset=53, value='import_message', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=24, col_offset=29, end_lineno=24, end_col_offset=35, value='done', kind=None),
                                            Subscript(
                                                lineno=24,
                                                col_offset=55,
                                                end_lineno=24,
                                                end_col_offset=61,
                                                value=Name(lineno=24, col_offset=55, end_lineno=24, end_col_offset=58, id='res', ctx=Load()),
                                                slice=Constant(lineno=24, col_offset=59, end_lineno=24, end_col_offset=60, value=0, kind=None),
                                                ctx=Load(),
                                            ),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=25,
                            col_offset=8,
                            end_lineno=25,
                            end_col_offset=60,
                            targets=[Name(lineno=25, col_offset=8, end_lineno=25, end_col_offset=15, id='context', ctx=Store())],
                            value=Call(
                                lineno=25,
                                col_offset=18,
                                end_lineno=25,
                                end_col_offset=60,
                                func=Name(lineno=25, col_offset=18, end_lineno=25, end_col_offset=22, id='dict', ctx=Load()),
                                args=[
                                    Attribute(
                                        lineno=25,
                                        col_offset=23,
                                        end_lineno=25,
                                        end_col_offset=39,
                                        value=Attribute(
                                            lineno=25,
                                            col_offset=23,
                                            end_lineno=25,
                                            end_col_offset=31,
                                            value=Name(lineno=25, col_offset=23, end_lineno=25, end_col_offset=27, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        attr='context',
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[
                                    keyword(
                                        lineno=25,
                                        col_offset=41,
                                        end_lineno=25,
                                        end_col_offset=59,
                                        arg='module_name',
                                        value=Subscript(
                                            lineno=25,
                                            col_offset=53,
                                            end_lineno=25,
                                            end_col_offset=59,
                                            value=Name(lineno=25, col_offset=53, end_lineno=25, end_col_offset=56, id='res', ctx=Load()),
                                            slice=Constant(lineno=25, col_offset=57, end_lineno=25, end_col_offset=58, value=1, kind=None),
                                            ctx=Load(),
                                        ),
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                        Return(
                            lineno=27,
                            col_offset=8,
                            end_lineno=35,
                            end_col_offset=9,
                            value=Dict(
                                lineno=27,
                                col_offset=15,
                                end_lineno=35,
                                end_col_offset=9,
                                keys=[
                                    Constant(lineno=28, col_offset=12, end_lineno=28, end_col_offset=18, value='name', kind=None),
                                    Constant(lineno=29, col_offset=12, end_lineno=29, end_col_offset=23, value='view_mode', kind=None),
                                    Constant(lineno=30, col_offset=12, end_lineno=30, end_col_offset=20, value='target', kind=None),
                                    Constant(lineno=31, col_offset=12, end_lineno=31, end_col_offset=20, value='res_id', kind=None),
                                    Constant(lineno=32, col_offset=12, end_lineno=32, end_col_offset=23, value='res_model', kind=None),
                                    Constant(lineno=33, col_offset=12, end_lineno=33, end_col_offset=18, value='type', kind=None),
                                    Constant(lineno=34, col_offset=12, end_lineno=34, end_col_offset=21, value='context', kind=None),
                                ],
                                values=[
                                    Constant(lineno=28, col_offset=20, end_lineno=28, end_col_offset=35, value='Import Module', kind=None),
                                    Constant(lineno=29, col_offset=25, end_lineno=29, end_col_offset=31, value='form', kind=None),
                                    Constant(lineno=30, col_offset=22, end_lineno=30, end_col_offset=27, value='new', kind=None),
                                    Attribute(
                                        lineno=31,
                                        col_offset=22,
                                        end_lineno=31,
                                        end_col_offset=29,
                                        value=Name(lineno=31, col_offset=22, end_lineno=31, end_col_offset=26, id='self', ctx=Load()),
                                        attr='id',
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=32, col_offset=25, end_lineno=32, end_col_offset=45, value='base.import.module', kind=None),
                                    Constant(lineno=33, col_offset=20, end_lineno=33, end_col_offset=43, value='ir.actions.act_window', kind=None),
                                    Name(lineno=34, col_offset=23, end_lineno=34, end_col_offset=30, id='context', ctx=Load()),
                                ],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=37,
                    col_offset=4,
                    end_lineno=46,
                    end_col_offset=9,
                    name='action_module_open',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=37, col_offset=27, end_lineno=37, end_col_offset=31, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=38,
                            col_offset=8,
                            end_lineno=38,
                            end_col_offset=25,
                            value=Call(
                                lineno=38,
                                col_offset=8,
                                end_lineno=38,
                                end_col_offset=25,
                                func=Attribute(
                                    lineno=38,
                                    col_offset=8,
                                    end_lineno=38,
                                    end_col_offset=23,
                                    value=Name(lineno=38, col_offset=8, end_lineno=38, end_col_offset=12, id='self', ctx=Load()),
                                    attr='ensure_one',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Return(
                            lineno=39,
                            col_offset=8,
                            end_lineno=46,
                            end_col_offset=9,
                            value=Dict(
                                lineno=39,
                                col_offset=15,
                                end_lineno=46,
                                end_col_offset=9,
                                keys=[
                                    Constant(lineno=40, col_offset=12, end_lineno=40, end_col_offset=20, value='domain', kind=None),
                                    Constant(lineno=41, col_offset=12, end_lineno=41, end_col_offset=18, value='name', kind=None),
                                    Constant(lineno=42, col_offset=12, end_lineno=42, end_col_offset=23, value='view_mode', kind=None),
                                    Constant(lineno=43, col_offset=12, end_lineno=43, end_col_offset=23, value='res_model', kind=None),
                                    Constant(lineno=44, col_offset=12, end_lineno=44, end_col_offset=21, value='view_id', kind=None),
                                    Constant(lineno=45, col_offset=12, end_lineno=45, end_col_offset=18, value='type', kind=None),
                                ],
                                values=[
                                    List(
                                        lineno=40,
                                        col_offset=22,
                                        end_lineno=40,
                                        end_col_offset=79,
                                        elts=[
                                            Tuple(
                                                lineno=40,
                                                col_offset=23,
                                                end_lineno=40,
                                                end_col_offset=78,
                                                elts=[
                                                    Constant(lineno=40, col_offset=24, end_lineno=40, end_col_offset=30, value='name', kind=None),
                                                    Constant(lineno=40, col_offset=32, end_lineno=40, end_col_offset=36, value='in', kind=None),
                                                    Call(
                                                        lineno=40,
                                                        col_offset=38,
                                                        end_lineno=40,
                                                        end_col_offset=77,
                                                        func=Attribute(
                                                            lineno=40,
                                                            col_offset=38,
                                                            end_lineno=40,
                                                            end_col_offset=58,
                                                            value=Attribute(
                                                                lineno=40,
                                                                col_offset=38,
                                                                end_lineno=40,
                                                                end_col_offset=54,
                                                                value=Attribute(
                                                                    lineno=40,
                                                                    col_offset=38,
                                                                    end_lineno=40,
                                                                    end_col_offset=46,
                                                                    value=Name(lineno=40, col_offset=38, end_lineno=40, end_col_offset=42, id='self', ctx=Load()),
                                                                    attr='env',
                                                                    ctx=Load(),
                                                                ),
                                                                attr='context',
                                                                ctx=Load(),
                                                            ),
                                                            attr='get',
                                                            ctx=Load(),
                                                        ),
                                                        args=[
                                                            Constant(lineno=40, col_offset=59, end_lineno=40, end_col_offset=72, value='module_name', kind=None),
                                                            List(lineno=40, col_offset=74, end_lineno=40, end_col_offset=76, elts=[], ctx=Load()),
                                                        ],
                                                        keywords=[],
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=41, col_offset=20, end_lineno=41, end_col_offset=29, value='Modules', kind=None),
                                    Constant(lineno=42, col_offset=25, end_lineno=42, end_col_offset=36, value='tree,form', kind=None),
                                    Constant(lineno=43, col_offset=25, end_lineno=43, end_col_offset=43, value='ir.module.module', kind=None),
                                    Constant(lineno=44, col_offset=23, end_lineno=44, end_col_offset=28, value=False, kind=None),
                                    Constant(lineno=45, col_offset=20, end_lineno=45, end_col_offset=43, value='ir.actions.act_window', kind=None),
                                ],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
