Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=36,
            module='odoo',
            names=[
                alias(name='api', asname=None),
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=21,
            end_col_offset=95,
            name='PeopleSeniority',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=22,
                    end_lineno=7,
                    end_col_offset=34,
                    value=Name(lineno=7, col_offset=22, end_lineno=7, end_col_offset=28, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Expr(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=38,
                    value=Constant(lineno=8, col_offset=4, end_lineno=8, end_col_offset=38, value=' Seniority for People Rules ', kind=None),
                ),
                Assign(
                    lineno=9,
                    col_offset=4,
                    end_lineno=9,
                    end_col_offset=36,
                    targets=[Name(lineno=9, col_offset=4, end_lineno=9, end_col_offset=9, id='_name', ctx=Store())],
                    value=Constant(lineno=9, col_offset=12, end_lineno=9, end_col_offset=36, value='crm.iap.lead.seniority', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=10,
                    col_offset=4,
                    end_lineno=10,
                    end_col_offset=37,
                    targets=[Name(lineno=10, col_offset=4, end_lineno=10, end_col_offset=16, id='_description', ctx=Store())],
                    value=Constant(lineno=10, col_offset=19, end_lineno=10, end_col_offset=37, value='People Seniority', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=12,
                    col_offset=4,
                    end_lineno=12,
                    end_col_offset=68,
                    targets=[Name(lineno=12, col_offset=4, end_lineno=12, end_col_offset=8, id='name', ctx=Store())],
                    value=Call(
                        lineno=12,
                        col_offset=11,
                        end_lineno=12,
                        end_col_offset=68,
                        func=Attribute(
                            lineno=12,
                            col_offset=11,
                            end_lineno=12,
                            end_col_offset=22,
                            value=Name(lineno=12, col_offset=11, end_lineno=12, end_col_offset=17, id='fields', ctx=Load()),
                            attr='Char',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=12,
                                col_offset=23,
                                end_lineno=12,
                                end_col_offset=36,
                                arg='string',
                                value=Constant(lineno=12, col_offset=30, end_lineno=12, end_col_offset=36, value='Name', kind=None),
                            ),
                            keyword(
                                lineno=12,
                                col_offset=38,
                                end_lineno=12,
                                end_col_offset=51,
                                arg='required',
                                value=Constant(lineno=12, col_offset=47, end_lineno=12, end_col_offset=51, value=True, kind=None),
                            ),
                            keyword(
                                lineno=12,
                                col_offset=53,
                                end_lineno=12,
                                end_col_offset=67,
                                arg='translate',
                                value=Constant(lineno=12, col_offset=63, end_lineno=12, end_col_offset=67, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=13,
                    col_offset=4,
                    end_lineno=13,
                    end_col_offset=42,
                    targets=[Name(lineno=13, col_offset=4, end_lineno=13, end_col_offset=13, id='reveal_id', ctx=Store())],
                    value=Call(
                        lineno=13,
                        col_offset=16,
                        end_lineno=13,
                        end_col_offset=42,
                        func=Attribute(
                            lineno=13,
                            col_offset=16,
                            end_lineno=13,
                            end_col_offset=27,
                            value=Name(lineno=13, col_offset=16, end_lineno=13, end_col_offset=22, id='fields', ctx=Load()),
                            attr='Char',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=13,
                                col_offset=28,
                                end_lineno=13,
                                end_col_offset=41,
                                arg='required',
                                value=Constant(lineno=13, col_offset=37, end_lineno=13, end_col_offset=41, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=15,
                    col_offset=4,
                    end_lineno=17,
                    end_col_offset=5,
                    targets=[Name(lineno=15, col_offset=4, end_lineno=15, end_col_offset=20, id='_sql_constraints', ctx=Store())],
                    value=List(
                        lineno=15,
                        col_offset=23,
                        end_lineno=17,
                        end_col_offset=5,
                        elts=[
                            Tuple(
                                lineno=16,
                                col_offset=8,
                                end_lineno=16,
                                end_col_offset=62,
                                elts=[
                                    Constant(lineno=16, col_offset=9, end_lineno=16, end_col_offset=20, value='name_uniq', kind=None),
                                    Constant(lineno=16, col_offset=22, end_lineno=16, end_col_offset=37, value='unique (name)', kind=None),
                                    Constant(lineno=16, col_offset=39, end_lineno=16, end_col_offset=61, value='Name already exists!', kind=None),
                                ],
                                ctx=Load(),
                            ),
                        ],
                        ctx=Load(),
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=20,
                    col_offset=4,
                    end_lineno=21,
                    end_col_offset=95,
                    name='name_get',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=20, col_offset=17, end_lineno=20, end_col_offset=21, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Return(
                            lineno=21,
                            col_offset=8,
                            end_lineno=21,
                            end_col_offset=95,
                            value=ListComp(
                                lineno=21,
                                col_offset=15,
                                end_lineno=21,
                                end_col_offset=95,
                                elt=Tuple(
                                    lineno=21,
                                    col_offset=16,
                                    end_lineno=21,
                                    end_col_offset=72,
                                    elts=[
                                        Attribute(
                                            lineno=21,
                                            col_offset=17,
                                            end_lineno=21,
                                            end_col_offset=29,
                                            value=Name(lineno=21, col_offset=17, end_lineno=21, end_col_offset=26, id='seniority', ctx=Load()),
                                            attr='id',
                                            ctx=Load(),
                                        ),
                                        Call(
                                            lineno=21,
                                            col_offset=31,
                                            end_lineno=21,
                                            end_col_offset=71,
                                            func=Attribute(
                                                lineno=21,
                                                col_offset=31,
                                                end_lineno=21,
                                                end_col_offset=69,
                                                value=Call(
                                                    lineno=21,
                                                    col_offset=31,
                                                    end_lineno=21,
                                                    end_col_offset=63,
                                                    func=Attribute(
                                                        lineno=21,
                                                        col_offset=31,
                                                        end_lineno=21,
                                                        end_col_offset=53,
                                                        value=Attribute(
                                                            lineno=21,
                                                            col_offset=31,
                                                            end_lineno=21,
                                                            end_col_offset=45,
                                                            value=Name(lineno=21, col_offset=31, end_lineno=21, end_col_offset=40, id='seniority', ctx=Load()),
                                                            attr='name',
                                                            ctx=Load(),
                                                        ),
                                                        attr='replace',
                                                        ctx=Load(),
                                                    ),
                                                    args=[
                                                        Constant(lineno=21, col_offset=54, end_lineno=21, end_col_offset=57, value='_', kind=None),
                                                        Constant(lineno=21, col_offset=59, end_lineno=21, end_col_offset=62, value=' ', kind=None),
                                                    ],
                                                    keywords=[],
                                                ),
                                                attr='title',
                                                ctx=Load(),
                                            ),
                                            args=[],
                                            keywords=[],
                                        ),
                                    ],
                                    ctx=Load(),
                                ),
                                generators=[
                                    comprehension(
                                        target=Name(lineno=21, col_offset=77, end_lineno=21, end_col_offset=86, id='seniority', ctx=Store()),
                                        iter=Name(lineno=21, col_offset=90, end_lineno=21, end_col_offset=94, id='self', ctx=Load()),
                                        ifs=[],
                                        is_async=0,
                                    ),
                                ],
                            ),
                        ),
                    ],
                    decorator_list=[
                        Call(
                            lineno=19,
                            col_offset=5,
                            end_lineno=19,
                            end_col_offset=24,
                            func=Attribute(
                                lineno=19,
                                col_offset=5,
                                end_lineno=19,
                                end_col_offset=16,
                                value=Name(lineno=19, col_offset=5, end_lineno=19, end_col_offset=8, id='api', ctx=Load()),
                                attr='depends',
                                ctx=Load(),
                            ),
                            args=[Constant(lineno=19, col_offset=17, end_lineno=19, end_col_offset=23, value='name', kind=None)],
                            keywords=[],
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
