Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=23,
            module='odoo',
            names=[alias(name='models', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=5,
            col_offset=0,
            end_lineno=5,
            end_col_offset=43,
            module='odoo.modules.loading',
            names=[alias(name='force_demo', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=6,
            col_offset=0,
            end_lineno=6,
            end_col_offset=69,
            module='odoo.addons.base.models.ir_module',
            names=[alias(name='assert_log_admin_access', asname=None)],
            level=0,
        ),
        ClassDef(
            lineno=9,
            col_offset=0,
            end_lineno=21,
            end_col_offset=9,
            name='IrDemo',
            bases=[
                Attribute(
                    lineno=9,
                    col_offset=13,
                    end_lineno=9,
                    end_col_offset=34,
                    value=Name(lineno=9, col_offset=13, end_lineno=9, end_col_offset=19, id='models', ctx=Load()),
                    attr='TransientModel',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=11,
                    col_offset=4,
                    end_lineno=11,
                    end_col_offset=21,
                    targets=[Name(lineno=11, col_offset=4, end_lineno=11, end_col_offset=9, id='_name', ctx=Store())],
                    value=Constant(lineno=11, col_offset=12, end_lineno=11, end_col_offset=21, value='ir.demo', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=12,
                    col_offset=4,
                    end_lineno=12,
                    end_col_offset=25,
                    targets=[Name(lineno=12, col_offset=4, end_lineno=12, end_col_offset=16, id='_description', ctx=Store())],
                    value=Constant(lineno=12, col_offset=19, end_lineno=12, end_col_offset=25, value='Demo', kind=None),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=15,
                    col_offset=4,
                    end_lineno=21,
                    end_col_offset=9,
                    name='install_demo',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=15, col_offset=21, end_lineno=15, end_col_offset=25, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=16,
                            col_offset=8,
                            end_lineno=16,
                            end_col_offset=31,
                            value=Call(
                                lineno=16,
                                col_offset=8,
                                end_lineno=16,
                                end_col_offset=31,
                                func=Name(lineno=16, col_offset=8, end_lineno=16, end_col_offset=18, id='force_demo', ctx=Load()),
                                args=[
                                    Attribute(
                                        lineno=16,
                                        col_offset=19,
                                        end_lineno=16,
                                        end_col_offset=30,
                                        value=Attribute(
                                            lineno=16,
                                            col_offset=19,
                                            end_lineno=16,
                                            end_col_offset=27,
                                            value=Name(lineno=16, col_offset=19, end_lineno=16, end_col_offset=23, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        attr='cr',
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Return(
                            lineno=17,
                            col_offset=8,
                            end_lineno=21,
                            end_col_offset=9,
                            value=Dict(
                                lineno=17,
                                col_offset=15,
                                end_lineno=21,
                                end_col_offset=9,
                                keys=[
                                    Constant(lineno=18, col_offset=12, end_lineno=18, end_col_offset=18, value='type', kind=None),
                                    Constant(lineno=19, col_offset=12, end_lineno=19, end_col_offset=20, value='target', kind=None),
                                    Constant(lineno=20, col_offset=12, end_lineno=20, end_col_offset=17, value='url', kind=None),
                                ],
                                values=[
                                    Constant(lineno=18, col_offset=20, end_lineno=18, end_col_offset=40, value='ir.actions.act_url', kind=None),
                                    Constant(lineno=19, col_offset=22, end_lineno=19, end_col_offset=28, value='self', kind=None),
                                    Constant(lineno=20, col_offset=19, end_lineno=20, end_col_offset=25, value='/web', kind=None),
                                ],
                            ),
                        ),
                    ],
                    decorator_list=[Name(lineno=14, col_offset=5, end_lineno=14, end_col_offset=28, id='assert_log_admin_access', ctx=Load())],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
