Module(
    body=[
        Import(
            lineno=3,
            col_offset=0,
            end_lineno=3,
            end_col_offset=17,
            names=[alias(name='odoo.tests', asname=None)],
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=71,
            end_col_offset=66,
            name='TestUi',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=13,
                    end_lineno=7,
                    end_col_offset=32,
                    value=Attribute(
                        lineno=7,
                        col_offset=13,
                        end_lineno=7,
                        end_col_offset=23,
                        value=Name(lineno=7, col_offset=13, end_lineno=7, end_col_offset=17, id='odoo', ctx=Load()),
                        attr='tests',
                        ctx=Load(),
                    ),
                    attr='HttpCase',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                FunctionDef(
                    lineno=9,
                    col_offset=4,
                    end_lineno=71,
                    end_col_offset=66,
                    name='test_01_free_delivery_when_exceed_threshold',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=9, col_offset=52, end_lineno=9, end_col_offset=56, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=12,
                            col_offset=8,
                            end_lineno=20,
                            end_col_offset=10,
                            value=Call(
                                lineno=12,
                                col_offset=8,
                                end_lineno=20,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=12,
                                    col_offset=8,
                                    end_lineno=12,
                                    end_col_offset=48,
                                    value=Call(
                                        lineno=12,
                                        col_offset=8,
                                        end_lineno=12,
                                        end_col_offset=42,
                                        func=Attribute(
                                            lineno=12,
                                            col_offset=8,
                                            end_lineno=12,
                                            end_col_offset=20,
                                            value=Attribute(
                                                lineno=12,
                                                col_offset=8,
                                                end_lineno=12,
                                                end_col_offset=16,
                                                value=Name(lineno=12, col_offset=8, end_lineno=12, end_col_offset=12, id='self', ctx=Load()),
                                                attr='env',
                                                ctx=Load(),
                                            ),
                                            attr='ref',
                                            ctx=Load(),
                                        ),
                                        args=[Constant(lineno=12, col_offset=21, end_lineno=12, end_col_offset=41, value='base.partner_admin', kind=None)],
                                        keywords=[],
                                    ),
                                    attr='write',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=12,
                                        col_offset=49,
                                        end_lineno=20,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=13, col_offset=12, end_lineno=13, end_col_offset=20, value='street', kind=None),
                                            Constant(lineno=14, col_offset=12, end_lineno=14, end_col_offset=18, value='city', kind=None),
                                            Constant(lineno=15, col_offset=12, end_lineno=15, end_col_offset=17, value='zip', kind=None),
                                            Constant(lineno=16, col_offset=12, end_lineno=16, end_col_offset=24, value='country_id', kind=None),
                                            Constant(lineno=17, col_offset=12, end_lineno=17, end_col_offset=22, value='state_id', kind=None),
                                            Constant(lineno=18, col_offset=12, end_lineno=18, end_col_offset=19, value='phone', kind=None),
                                            Constant(lineno=19, col_offset=12, end_lineno=19, end_col_offset=19, value='email', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=13, col_offset=22, end_lineno=13, end_col_offset=35, value='215 Vine St', kind=None),
                                            Constant(lineno=14, col_offset=20, end_lineno=14, end_col_offset=30, value='Scranton', kind=None),
                                            Constant(lineno=15, col_offset=19, end_lineno=15, end_col_offset=26, value='18503', kind=None),
                                            Attribute(
                                                lineno=16,
                                                col_offset=26,
                                                end_lineno=16,
                                                end_col_offset=52,
                                                value=Call(
                                                    lineno=16,
                                                    col_offset=26,
                                                    end_lineno=16,
                                                    end_col_offset=49,
                                                    func=Attribute(
                                                        lineno=16,
                                                        col_offset=26,
                                                        end_lineno=16,
                                                        end_col_offset=38,
                                                        value=Attribute(
                                                            lineno=16,
                                                            col_offset=26,
                                                            end_lineno=16,
                                                            end_col_offset=34,
                                                            value=Name(lineno=16, col_offset=26, end_lineno=16, end_col_offset=30, id='self', ctx=Load()),
                                                            attr='env',
                                                            ctx=Load(),
                                                        ),
                                                        attr='ref',
                                                        ctx=Load(),
                                                    ),
                                                    args=[Constant(lineno=16, col_offset=39, end_lineno=16, end_col_offset=48, value='base.us', kind=None)],
                                                    keywords=[],
                                                ),
                                                attr='id',
                                                ctx=Load(),
                                            ),
                                            Attribute(
                                                lineno=17,
                                                col_offset=24,
                                                end_lineno=17,
                                                end_col_offset=59,
                                                value=Call(
                                                    lineno=17,
                                                    col_offset=24,
                                                    end_lineno=17,
                                                    end_col_offset=56,
                                                    func=Attribute(
                                                        lineno=17,
                                                        col_offset=24,
                                                        end_lineno=17,
                                                        end_col_offset=36,
                                                        value=Attribute(
                                                            lineno=17,
                                                            col_offset=24,
                                                            end_lineno=17,
                                                            end_col_offset=32,
                                                            value=Name(lineno=17, col_offset=24, end_lineno=17, end_col_offset=28, id='self', ctx=Load()),
                                                            attr='env',
                                                            ctx=Load(),
                                                        ),
                                                        attr='ref',
                                                        ctx=Load(),
                                                    ),
                                                    args=[Constant(lineno=17, col_offset=37, end_lineno=17, end_col_offset=55, value='base.state_us_39', kind=None)],
                                                    keywords=[],
                                                ),
                                                attr='id',
                                                ctx=Load(),
                                            ),
                                            Constant(lineno=18, col_offset=21, end_lineno=18, end_col_offset=38, value='+1 555-555-5555', kind=None),
                                            Constant(lineno=19, col_offset=21, end_lineno=19, end_col_offset=52, value='admin@yourcompany.example.com', kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=22,
                            col_offset=8,
                            end_lineno=25,
                            end_col_offset=10,
                            targets=[Name(lineno=22, col_offset=8, end_lineno=22, end_col_offset=20, id='office_chair', ctx=Store())],
                            value=Call(
                                lineno=22,
                                col_offset=23,
                                end_lineno=25,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=22,
                                    col_offset=23,
                                    end_lineno=22,
                                    end_col_offset=57,
                                    value=Subscript(
                                        lineno=22,
                                        col_offset=23,
                                        end_lineno=22,
                                        end_col_offset=50,
                                        value=Attribute(
                                            lineno=22,
                                            col_offset=23,
                                            end_lineno=22,
                                            end_col_offset=31,
                                            value=Name(lineno=22, col_offset=23, end_lineno=22, end_col_offset=27, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=22, col_offset=32, end_lineno=22, end_col_offset=49, value='product.product', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=22,
                                        col_offset=58,
                                        end_lineno=25,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=23, col_offset=12, end_lineno=23, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=24, col_offset=12, end_lineno=24, end_col_offset=24, value='list_price', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=23, col_offset=20, end_lineno=23, end_col_offset=45, value='Office Chair Black TEST', kind=None),
                                            Constant(lineno=24, col_offset=26, end_lineno=24, end_col_offset=31, value=12.5, kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=26,
                            col_offset=8,
                            end_lineno=31,
                            end_col_offset=10,
                            value=Call(
                                lineno=26,
                                col_offset=8,
                                end_lineno=31,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=26,
                                    col_offset=8,
                                    end_lineno=26,
                                    end_col_offset=60,
                                    value=Call(
                                        lineno=26,
                                        col_offset=8,
                                        end_lineno=26,
                                        end_col_offset=54,
                                        func=Attribute(
                                            lineno=26,
                                            col_offset=8,
                                            end_lineno=26,
                                            end_col_offset=20,
                                            value=Attribute(
                                                lineno=26,
                                                col_offset=8,
                                                end_lineno=26,
                                                end_col_offset=16,
                                                value=Name(lineno=26, col_offset=8, end_lineno=26, end_col_offset=12, id='self', ctx=Load()),
                                                attr='env',
                                                ctx=Load(),
                                            ),
                                            attr='ref',
                                            ctx=Load(),
                                        ),
                                        args=[Constant(lineno=26, col_offset=21, end_lineno=26, end_col_offset=53, value='delivery.free_delivery_carrier', kind=None)],
                                        keywords=[],
                                    ),
                                    attr='write',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=26,
                                        col_offset=61,
                                        end_lineno=31,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=27, col_offset=12, end_lineno=27, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=28, col_offset=12, end_lineno=28, end_col_offset=25, value='fixed_price', kind=None),
                                            Constant(lineno=29, col_offset=12, end_lineno=29, end_col_offset=23, value='free_over', kind=None),
                                            Constant(lineno=30, col_offset=12, end_lineno=30, end_col_offset=20, value='amount', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=27, col_offset=20, end_lineno=27, end_col_offset=47, value='Delivery Now Free Over 10', kind=None),
                                            Constant(lineno=28, col_offset=27, end_lineno=28, end_col_offset=28, value=2, kind=None),
                                            Constant(lineno=29, col_offset=25, end_lineno=29, end_col_offset=29, value=True, kind=None),
                                            Constant(lineno=30, col_offset=22, end_lineno=30, end_col_offset=24, value=10, kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=32,
                            col_offset=8,
                            end_lineno=39,
                            end_col_offset=10,
                            targets=[
                                Attribute(
                                    lineno=32,
                                    col_offset=8,
                                    end_lineno=32,
                                    end_col_offset=35,
                                    value=Name(lineno=32, col_offset=8, end_lineno=32, end_col_offset=12, id='self', ctx=Load()),
                                    attr='product_delivery_poste',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=32,
                                col_offset=38,
                                end_lineno=39,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=32,
                                    col_offset=38,
                                    end_lineno=32,
                                    end_col_offset=72,
                                    value=Subscript(
                                        lineno=32,
                                        col_offset=38,
                                        end_lineno=32,
                                        end_col_offset=65,
                                        value=Attribute(
                                            lineno=32,
                                            col_offset=38,
                                            end_lineno=32,
                                            end_col_offset=46,
                                            value=Name(lineno=32, col_offset=38, end_lineno=32, end_col_offset=42, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=32, col_offset=47, end_lineno=32, end_col_offset=64, value='product.product', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=32,
                                        col_offset=73,
                                        end_lineno=39,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=33, col_offset=12, end_lineno=33, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=34, col_offset=12, end_lineno=34, end_col_offset=18, value='type', kind=None),
                                            Constant(lineno=35, col_offset=12, end_lineno=35, end_col_offset=22, value='categ_id', kind=None),
                                            Constant(lineno=36, col_offset=12, end_lineno=36, end_col_offset=21, value='sale_ok', kind=None),
                                            Constant(lineno=37, col_offset=12, end_lineno=37, end_col_offset=25, value='purchase_ok', kind=None),
                                            Constant(lineno=38, col_offset=12, end_lineno=38, end_col_offset=24, value='list_price', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=33, col_offset=20, end_lineno=33, end_col_offset=31, value='The Poste', kind=None),
                                            Constant(lineno=34, col_offset=20, end_lineno=34, end_col_offset=29, value='service', kind=None),
                                            Attribute(
                                                lineno=35,
                                                col_offset=24,
                                                end_lineno=35,
                                                end_col_offset=79,
                                                value=Call(
                                                    lineno=35,
                                                    col_offset=24,
                                                    end_lineno=35,
                                                    end_col_offset=76,
                                                    func=Attribute(
                                                        lineno=35,
                                                        col_offset=24,
                                                        end_lineno=35,
                                                        end_col_offset=36,
                                                        value=Attribute(
                                                            lineno=35,
                                                            col_offset=24,
                                                            end_lineno=35,
                                                            end_col_offset=32,
                                                            value=Name(lineno=35, col_offset=24, end_lineno=35, end_col_offset=28, id='self', ctx=Load()),
                                                            attr='env',
                                                            ctx=Load(),
                                                        ),
                                                        attr='ref',
                                                        ctx=Load(),
                                                    ),
                                                    args=[Constant(lineno=35, col_offset=37, end_lineno=35, end_col_offset=75, value='delivery.product_category_deliveries', kind=None)],
                                                    keywords=[],
                                                ),
                                                attr='id',
                                                ctx=Load(),
                                            ),
                                            Constant(lineno=36, col_offset=23, end_lineno=36, end_col_offset=28, value=False, kind=None),
                                            Constant(lineno=37, col_offset=27, end_lineno=37, end_col_offset=32, value=False, kind=None),
                                            Constant(lineno=38, col_offset=26, end_lineno=38, end_col_offset=30, value=20.0, kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=40,
                            col_offset=8,
                            end_lineno=47,
                            end_col_offset=10,
                            targets=[
                                Attribute(
                                    lineno=40,
                                    col_offset=8,
                                    end_lineno=40,
                                    end_col_offset=20,
                                    value=Name(lineno=40, col_offset=8, end_lineno=40, end_col_offset=12, id='self', ctx=Load()),
                                    attr='carrier',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=40,
                                col_offset=23,
                                end_lineno=47,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=40,
                                    col_offset=23,
                                    end_lineno=40,
                                    end_col_offset=58,
                                    value=Subscript(
                                        lineno=40,
                                        col_offset=23,
                                        end_lineno=40,
                                        end_col_offset=51,
                                        value=Attribute(
                                            lineno=40,
                                            col_offset=23,
                                            end_lineno=40,
                                            end_col_offset=31,
                                            value=Name(lineno=40, col_offset=23, end_lineno=40, end_col_offset=27, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=40, col_offset=32, end_lineno=40, end_col_offset=50, value='delivery.carrier', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=40,
                                        col_offset=59,
                                        end_lineno=47,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=41, col_offset=12, end_lineno=41, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=42, col_offset=12, end_lineno=42, end_col_offset=22, value='sequence', kind=None),
                                            Constant(lineno=43, col_offset=12, end_lineno=43, end_col_offset=25, value='fixed_price', kind=None),
                                            Constant(lineno=44, col_offset=12, end_lineno=44, end_col_offset=27, value='delivery_type', kind=None),
                                            Constant(lineno=45, col_offset=12, end_lineno=45, end_col_offset=24, value='product_id', kind=None),
                                            Constant(lineno=46, col_offset=12, end_lineno=46, end_col_offset=31, value='website_published', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=41, col_offset=20, end_lineno=41, end_col_offset=31, value='The Poste', kind=None),
                                            Constant(lineno=42, col_offset=24, end_lineno=42, end_col_offset=28, value=9999, kind=None),
                                            Constant(lineno=43, col_offset=27, end_lineno=43, end_col_offset=31, value=20.0, kind=None),
                                            Constant(lineno=44, col_offset=29, end_lineno=44, end_col_offset=43, value='base_on_rule', kind=None),
                                            Attribute(
                                                lineno=45,
                                                col_offset=26,
                                                end_lineno=45,
                                                end_col_offset=56,
                                                value=Attribute(
                                                    lineno=45,
                                                    col_offset=26,
                                                    end_lineno=45,
                                                    end_col_offset=53,
                                                    value=Name(lineno=45, col_offset=26, end_lineno=45, end_col_offset=30, id='self', ctx=Load()),
                                                    attr='product_delivery_poste',
                                                    ctx=Load(),
                                                ),
                                                attr='id',
                                                ctx=Load(),
                                            ),
                                            Constant(lineno=46, col_offset=33, end_lineno=46, end_col_offset=37, value=True, kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=48,
                            col_offset=8,
                            end_lineno=63,
                            end_col_offset=11,
                            value=Call(
                                lineno=48,
                                col_offset=8,
                                end_lineno=63,
                                end_col_offset=11,
                                func=Attribute(
                                    lineno=48,
                                    col_offset=8,
                                    end_lineno=48,
                                    end_col_offset=46,
                                    value=Subscript(
                                        lineno=48,
                                        col_offset=8,
                                        end_lineno=48,
                                        end_col_offset=39,
                                        value=Attribute(
                                            lineno=48,
                                            col_offset=8,
                                            end_lineno=48,
                                            end_col_offset=16,
                                            value=Name(lineno=48, col_offset=8, end_lineno=48, end_col_offset=12, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=48, col_offset=17, end_lineno=48, end_col_offset=38, value='delivery.price.rule', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    List(
                                        lineno=48,
                                        col_offset=47,
                                        end_lineno=63,
                                        end_col_offset=10,
                                        elts=[
                                            Dict(
                                                lineno=48,
                                                col_offset=48,
                                                end_lineno=52,
                                                end_col_offset=9,
                                                keys=[
                                                    Constant(lineno=49, col_offset=12, end_lineno=49, end_col_offset=24, value='carrier_id', kind=None),
                                                    Constant(lineno=50, col_offset=12, end_lineno=50, end_col_offset=23, value='max_value', kind=None),
                                                    Constant(lineno=51, col_offset=12, end_lineno=51, end_col_offset=29, value='list_base_price', kind=None),
                                                ],
                                                values=[
                                                    Attribute(
                                                        lineno=49,
                                                        col_offset=26,
                                                        end_lineno=49,
                                                        end_col_offset=41,
                                                        value=Attribute(
                                                            lineno=49,
                                                            col_offset=26,
                                                            end_lineno=49,
                                                            end_col_offset=38,
                                                            value=Name(lineno=49, col_offset=26, end_lineno=49, end_col_offset=30, id='self', ctx=Load()),
                                                            attr='carrier',
                                                            ctx=Load(),
                                                        ),
                                                        attr='id',
                                                        ctx=Load(),
                                                    ),
                                                    Constant(lineno=50, col_offset=25, end_lineno=50, end_col_offset=26, value=5, kind=None),
                                                    Constant(lineno=51, col_offset=31, end_lineno=51, end_col_offset=33, value=20, kind=None),
                                                ],
                                            ),
                                            Dict(
                                                lineno=52,
                                                col_offset=11,
                                                end_lineno=57,
                                                end_col_offset=9,
                                                keys=[
                                                    Constant(lineno=53, col_offset=12, end_lineno=53, end_col_offset=24, value='carrier_id', kind=None),
                                                    Constant(lineno=54, col_offset=12, end_lineno=54, end_col_offset=22, value='operator', kind=None),
                                                    Constant(lineno=55, col_offset=12, end_lineno=55, end_col_offset=23, value='max_value', kind=None),
                                                    Constant(lineno=56, col_offset=12, end_lineno=56, end_col_offset=29, value='list_base_price', kind=None),
                                                ],
                                                values=[
                                                    Attribute(
                                                        lineno=53,
                                                        col_offset=26,
                                                        end_lineno=53,
                                                        end_col_offset=41,
                                                        value=Attribute(
                                                            lineno=53,
                                                            col_offset=26,
                                                            end_lineno=53,
                                                            end_col_offset=38,
                                                            value=Name(lineno=53, col_offset=26, end_lineno=53, end_col_offset=30, id='self', ctx=Load()),
                                                            attr='carrier',
                                                            ctx=Load(),
                                                        ),
                                                        attr='id',
                                                        ctx=Load(),
                                                    ),
                                                    Constant(lineno=54, col_offset=24, end_lineno=54, end_col_offset=28, value='>=', kind=None),
                                                    Constant(lineno=55, col_offset=25, end_lineno=55, end_col_offset=26, value=5, kind=None),
                                                    Constant(lineno=56, col_offset=31, end_lineno=56, end_col_offset=33, value=50, kind=None),
                                                ],
                                            ),
                                            Dict(
                                                lineno=57,
                                                col_offset=11,
                                                end_lineno=63,
                                                end_col_offset=9,
                                                keys=[
                                                    Constant(lineno=58, col_offset=12, end_lineno=58, end_col_offset=24, value='carrier_id', kind=None),
                                                    Constant(lineno=59, col_offset=12, end_lineno=59, end_col_offset=22, value='operator', kind=None),
                                                    Constant(lineno=60, col_offset=12, end_lineno=60, end_col_offset=23, value='max_value', kind=None),
                                                    Constant(lineno=61, col_offset=12, end_lineno=61, end_col_offset=22, value='variable', kind=None),
                                                    Constant(lineno=62, col_offset=12, end_lineno=62, end_col_offset=29, value='list_base_price', kind=None),
                                                ],
                                                values=[
                                                    Attribute(
                                                        lineno=58,
                                                        col_offset=26,
                                                        end_lineno=58,
                                                        end_col_offset=41,
                                                        value=Attribute(
                                                            lineno=58,
                                                            col_offset=26,
                                                            end_lineno=58,
                                                            end_col_offset=38,
                                                            value=Name(lineno=58, col_offset=26, end_lineno=58, end_col_offset=30, id='self', ctx=Load()),
                                                            attr='carrier',
                                                            ctx=Load(),
                                                        ),
                                                        attr='id',
                                                        ctx=Load(),
                                                    ),
                                                    Constant(lineno=59, col_offset=24, end_lineno=59, end_col_offset=28, value='>=', kind=None),
                                                    Constant(lineno=60, col_offset=25, end_lineno=60, end_col_offset=28, value=300, kind=None),
                                                    Constant(lineno=61, col_offset=24, end_lineno=61, end_col_offset=31, value='price', kind=None),
                                                    Constant(lineno=62, col_offset=31, end_lineno=62, end_col_offset=32, value=0, kind=None),
                                                ],
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=65,
                            col_offset=8,
                            end_lineno=65,
                            end_col_offset=106,
                            value=Call(
                                lineno=65,
                                col_offset=8,
                                end_lineno=65,
                                end_col_offset=106,
                                func=Attribute(
                                    lineno=65,
                                    col_offset=8,
                                    end_lineno=65,
                                    end_col_offset=42,
                                    value=Subscript(
                                        lineno=65,
                                        col_offset=8,
                                        end_lineno=65,
                                        end_col_offset=35,
                                        value=Attribute(
                                            lineno=65,
                                            col_offset=8,
                                            end_lineno=65,
                                            end_col_offset=16,
                                            value=Name(lineno=65, col_offset=8, end_lineno=65, end_col_offset=12, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=65, col_offset=17, end_lineno=65, end_col_offset=34, value='account.journal', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=65,
                                        col_offset=43,
                                        end_lineno=65,
                                        end_col_offset=105,
                                        keys=[
                                            Constant(lineno=65, col_offset=44, end_lineno=65, end_col_offset=50, value='name', kind=None),
                                            Constant(lineno=65, col_offset=67, end_lineno=65, end_col_offset=73, value='type', kind=None),
                                            Constant(lineno=65, col_offset=83, end_lineno=65, end_col_offset=89, value='code', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=65, col_offset=52, end_lineno=65, end_col_offset=65, value='Cash - Test', kind=None),
                                            Constant(lineno=65, col_offset=75, end_lineno=65, end_col_offset=81, value='cash', kind=None),
                                            Constant(lineno=65, col_offset=91, end_lineno=65, end_col_offset=104, value='CASH - Test', kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=69,
                            col_offset=8,
                            end_lineno=69,
                            end_col_offset=82,
                            value=Call(
                                lineno=69,
                                col_offset=8,
                                end_lineno=69,
                                end_col_offset=82,
                                func=Attribute(
                                    lineno=69,
                                    col_offset=8,
                                    end_lineno=69,
                                    end_col_offset=63,
                                    value=Call(
                                        lineno=69,
                                        col_offset=8,
                                        end_lineno=69,
                                        end_col_offset=57,
                                        func=Attribute(
                                            lineno=69,
                                            col_offset=8,
                                            end_lineno=69,
                                            end_col_offset=20,
                                            value=Attribute(
                                                lineno=69,
                                                col_offset=8,
                                                end_lineno=69,
                                                end_col_offset=16,
                                                value=Name(lineno=69, col_offset=8, end_lineno=69, end_col_offset=12, id='self', ctx=Load()),
                                                attr='env',
                                                ctx=Load(),
                                            ),
                                            attr='ref',
                                            ctx=Load(),
                                        ),
                                        args=[Constant(lineno=69, col_offset=21, end_lineno=69, end_col_offset=56, value='payment.payment_acquirer_transfer', kind=None)],
                                        keywords=[],
                                    ),
                                    attr='write',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=69,
                                        col_offset=64,
                                        end_lineno=69,
                                        end_col_offset=81,
                                        keys=[Constant(lineno=69, col_offset=65, end_lineno=69, end_col_offset=72, value='state', kind=None)],
                                        values=[Constant(lineno=69, col_offset=74, end_lineno=69, end_col_offset=80, value='test', kind=None)],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=71,
                            col_offset=8,
                            end_lineno=71,
                            end_col_offset=66,
                            value=Call(
                                lineno=71,
                                col_offset=8,
                                end_lineno=71,
                                end_col_offset=66,
                                func=Attribute(
                                    lineno=71,
                                    col_offset=8,
                                    end_lineno=71,
                                    end_col_offset=23,
                                    value=Name(lineno=71, col_offset=8, end_lineno=71, end_col_offset=12, id='self', ctx=Load()),
                                    attr='start_tour',
                                    ctx=Load(),
                                ),
                                args=[
                                    Constant(lineno=71, col_offset=24, end_lineno=71, end_col_offset=27, value='/', kind=None),
                                    Constant(lineno=71, col_offset=29, end_lineno=71, end_col_offset=50, value='check_free_delivery', kind=None),
                                ],
                                keywords=[
                                    keyword(
                                        lineno=71,
                                        col_offset=52,
                                        end_lineno=71,
                                        end_col_offset=65,
                                        arg='login',
                                        value=Constant(lineno=71, col_offset=58, end_lineno=71, end_col_offset=65, value='admin', kind=None),
                                    ),
                                ],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[
                Call(
                    lineno=6,
                    col_offset=1,
                    end_lineno=6,
                    end_col_offset=49,
                    func=Attribute(
                        lineno=6,
                        col_offset=1,
                        end_lineno=6,
                        end_col_offset=18,
                        value=Attribute(
                            lineno=6,
                            col_offset=1,
                            end_lineno=6,
                            end_col_offset=11,
                            value=Name(lineno=6, col_offset=1, end_lineno=6, end_col_offset=5, id='odoo', ctx=Load()),
                            attr='tests',
                            ctx=Load(),
                        ),
                        attr='tagged',
                        ctx=Load(),
                    ),
                    args=[
                        Constant(lineno=6, col_offset=19, end_lineno=6, end_col_offset=33, value='post_install', kind=None),
                        Constant(lineno=6, col_offset=35, end_lineno=6, end_col_offset=48, value='-at_install', kind=None),
                    ],
                    keywords=[],
                ),
            ],
        ),
    ],
    type_ignores=[],
)
