Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=31,
            module='odoo',
            names=[
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=13,
            end_col_offset=86,
            name='LunchLocation',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=20,
                    end_lineno=7,
                    end_col_offset=32,
                    value=Name(lineno=7, col_offset=20, end_lineno=7, end_col_offset=26, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=28,
                    targets=[Name(lineno=8, col_offset=4, end_lineno=8, end_col_offset=9, id='_name', ctx=Store())],
                    value=Constant(lineno=8, col_offset=12, end_lineno=8, end_col_offset=28, value='lunch.location', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=9,
                    col_offset=4,
                    end_lineno=9,
                    end_col_offset=36,
                    targets=[Name(lineno=9, col_offset=4, end_lineno=9, end_col_offset=16, id='_description', ctx=Store())],
                    value=Constant(lineno=9, col_offset=19, end_lineno=9, end_col_offset=36, value='Lunch Locations', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=11,
                    col_offset=4,
                    end_lineno=11,
                    end_col_offset=54,
                    targets=[Name(lineno=11, col_offset=4, end_lineno=11, end_col_offset=8, id='name', ctx=Store())],
                    value=Call(
                        lineno=11,
                        col_offset=11,
                        end_lineno=11,
                        end_col_offset=54,
                        func=Attribute(
                            lineno=11,
                            col_offset=11,
                            end_lineno=11,
                            end_col_offset=22,
                            value=Name(lineno=11, col_offset=11, end_lineno=11, end_col_offset=17, id='fields', ctx=Load()),
                            attr='Char',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=11, col_offset=23, end_lineno=11, end_col_offset=38, value='Location Name', kind=None)],
                        keywords=[
                            keyword(
                                lineno=11,
                                col_offset=40,
                                end_lineno=11,
                                end_col_offset=53,
                                arg='required',
                                value=Constant(lineno=11, col_offset=49, end_lineno=11, end_col_offset=53, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=12,
                    col_offset=4,
                    end_lineno=12,
                    end_col_offset=36,
                    targets=[Name(lineno=12, col_offset=4, end_lineno=12, end_col_offset=11, id='address', ctx=Store())],
                    value=Call(
                        lineno=12,
                        col_offset=14,
                        end_lineno=12,
                        end_col_offset=36,
                        func=Attribute(
                            lineno=12,
                            col_offset=14,
                            end_lineno=12,
                            end_col_offset=25,
                            value=Name(lineno=12, col_offset=14, end_lineno=12, end_col_offset=20, id='fields', ctx=Load()),
                            attr='Text',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=12, col_offset=26, end_lineno=12, end_col_offset=35, value='Address', kind=None)],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=13,
                    col_offset=4,
                    end_lineno=13,
                    end_col_offset=86,
                    targets=[Name(lineno=13, col_offset=4, end_lineno=13, end_col_offset=14, id='company_id', ctx=Store())],
                    value=Call(
                        lineno=13,
                        col_offset=17,
                        end_lineno=13,
                        end_col_offset=86,
                        func=Attribute(
                            lineno=13,
                            col_offset=17,
                            end_lineno=13,
                            end_col_offset=32,
                            value=Name(lineno=13, col_offset=17, end_lineno=13, end_col_offset=23, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=13, col_offset=33, end_lineno=13, end_col_offset=46, value='res.company', kind=None)],
                        keywords=[
                            keyword(
                                lineno=13,
                                col_offset=48,
                                end_lineno=13,
                                end_col_offset=85,
                                arg='default',
                                value=Lambda(
                                    lineno=13,
                                    col_offset=56,
                                    end_lineno=13,
                                    end_col_offset=85,
                                    args=arguments(
                                        posonlyargs=[],
                                        args=[arg(lineno=13, col_offset=63, end_lineno=13, end_col_offset=67, arg='self', annotation=None, type_comment=None)],
                                        vararg=None,
                                        kwonlyargs=[],
                                        kw_defaults=[],
                                        kwarg=None,
                                        defaults=[],
                                    ),
                                    body=Attribute(
                                        lineno=13,
                                        col_offset=69,
                                        end_lineno=13,
                                        end_col_offset=85,
                                        value=Attribute(
                                            lineno=13,
                                            col_offset=69,
                                            end_lineno=13,
                                            end_col_offset=77,
                                            value=Name(lineno=13, col_offset=69, end_lineno=13, end_col_offset=73, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        attr='company',
                                        ctx=Load(),
                                    ),
                                ),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
