Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=39,
            module='odoo',
            names=[
                alias(name='api', asname=None),
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
                alias(name='_', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=64,
            end_col_offset=9,
            name='BaseLanguageInstall',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=26,
                    end_lineno=7,
                    end_col_offset=47,
                    value=Name(lineno=7, col_offset=26, end_lineno=7, end_col_offset=32, id='models', ctx=Load()),
                    attr='TransientModel',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=35,
                    targets=[Name(lineno=8, col_offset=4, end_lineno=8, end_col_offset=9, id='_name', ctx=Store())],
                    value=Constant(lineno=8, col_offset=12, end_lineno=8, end_col_offset=35, value='base.language.install', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=9,
                    col_offset=4,
                    end_lineno=9,
                    end_col_offset=37,
                    targets=[Name(lineno=9, col_offset=4, end_lineno=9, end_col_offset=16, id='_description', ctx=Store())],
                    value=Constant(lineno=9, col_offset=19, end_lineno=9, end_col_offset=37, value='Install Language', kind=None),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=12,
                    col_offset=4,
                    end_lineno=19,
                    end_col_offset=20,
                    name='_default_language',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=12, col_offset=26, end_lineno=12, end_col_offset=30, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=13,
                            col_offset=8,
                            end_lineno=15,
                            end_col_offset=11,
                            value=Constant(lineno=13, col_offset=8, end_lineno=15, end_col_offset=11, value=" Display the selected language when using the 'Update Terms' action\n            from the language list view\n        ", kind=None),
                        ),
                        If(
                            lineno=16,
                            col_offset=8,
                            end_lineno=18,
                            end_col_offset=28,
                            test=Compare(
                                lineno=16,
                                col_offset=11,
                                end_lineno=16,
                                end_col_offset=58,
                                left=Call(
                                    lineno=16,
                                    col_offset=11,
                                    end_lineno=16,
                                    end_col_offset=44,
                                    func=Attribute(
                                        lineno=16,
                                        col_offset=11,
                                        end_lineno=16,
                                        end_col_offset=28,
                                        value=Attribute(
                                            lineno=16,
                                            col_offset=11,
                                            end_lineno=16,
                                            end_col_offset=24,
                                            value=Name(lineno=16, col_offset=11, end_lineno=16, end_col_offset=15, id='self', ctx=Load()),
                                            attr='_context',
                                            ctx=Load(),
                                        ),
                                        attr='get',
                                        ctx=Load(),
                                    ),
                                    args=[Constant(lineno=16, col_offset=29, end_lineno=16, end_col_offset=43, value='active_model', kind=None)],
                                    keywords=[],
                                ),
                                ops=[Eq()],
                                comparators=[Constant(lineno=16, col_offset=48, end_lineno=16, end_col_offset=58, value='res.lang', kind=None)],
                            ),
                            body=[
                                Assign(
                                    lineno=17,
                                    col_offset=12,
                                    end_lineno=17,
                                    end_col_offset=78,
                                    targets=[Name(lineno=17, col_offset=12, end_lineno=17, end_col_offset=16, id='lang', ctx=Store())],
                                    value=Call(
                                        lineno=17,
                                        col_offset=19,
                                        end_lineno=17,
                                        end_col_offset=78,
                                        func=Attribute(
                                            lineno=17,
                                            col_offset=19,
                                            end_lineno=17,
                                            end_col_offset=46,
                                            value=Subscript(
                                                lineno=17,
                                                col_offset=19,
                                                end_lineno=17,
                                                end_col_offset=39,
                                                value=Attribute(
                                                    lineno=17,
                                                    col_offset=19,
                                                    end_lineno=17,
                                                    end_col_offset=27,
                                                    value=Name(lineno=17, col_offset=19, end_lineno=17, end_col_offset=23, id='self', ctx=Load()),
                                                    attr='env',
                                                    ctx=Load(),
                                                ),
                                                slice=Constant(lineno=17, col_offset=28, end_lineno=17, end_col_offset=38, value='res.lang', kind=None),
                                                ctx=Load(),
                                            ),
                                            attr='browse',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Call(
                                                lineno=17,
                                                col_offset=47,
                                                end_lineno=17,
                                                end_col_offset=77,
                                                func=Attribute(
                                                    lineno=17,
                                                    col_offset=47,
                                                    end_lineno=17,
                                                    end_col_offset=64,
                                                    value=Attribute(
                                                        lineno=17,
                                                        col_offset=47,
                                                        end_lineno=17,
                                                        end_col_offset=60,
                                                        value=Name(lineno=17, col_offset=47, end_lineno=17, end_col_offset=51, id='self', ctx=Load()),
                                                        attr='_context',
                                                        ctx=Load(),
                                                    ),
                                                    attr='get',
                                                    ctx=Load(),
                                                ),
                                                args=[Constant(lineno=17, col_offset=65, end_lineno=17, end_col_offset=76, value='active_id', kind=None)],
                                                keywords=[],
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                    type_comment=None,
                                ),
                                Return(
                                    lineno=18,
                                    col_offset=12,
                                    end_lineno=18,
                                    end_col_offset=28,
                                    value=Attribute(
                                        lineno=18,
                                        col_offset=19,
                                        end_lineno=18,
                                        end_col_offset=28,
                                        value=Name(lineno=18, col_offset=19, end_lineno=18, end_col_offset=23, id='lang', ctx=Load()),
                                        attr='code',
                                        ctx=Load(),
                                    ),
                                ),
                            ],
                            orelse=[],
                        ),
                        Return(
                            lineno=19,
                            col_offset=8,
                            end_lineno=19,
                            end_col_offset=20,
                            value=Constant(lineno=19, col_offset=15, end_lineno=19, end_col_offset=20, value=False, kind=None),
                        ),
                    ],
                    decorator_list=[
                        Attribute(
                            lineno=11,
                            col_offset=5,
                            end_lineno=11,
                            end_col_offset=14,
                            value=Name(lineno=11, col_offset=5, end_lineno=11, end_col_offset=8, id='api', ctx=Load()),
                            attr='model',
                            ctx=Load(),
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=22,
                    col_offset=4,
                    end_lineno=23,
                    end_col_offset=91,
                    name='_get_languages',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=22, col_offset=23, end_lineno=22, end_col_offset=27, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Return(
                            lineno=23,
                            col_offset=8,
                            end_lineno=23,
                            end_col_offset=91,
                            value=ListComp(
                                lineno=23,
                                col_offset=15,
                                end_lineno=23,
                                end_col_offset=91,
                                elt=List(
                                    lineno=23,
                                    col_offset=16,
                                    end_lineno=23,
                                    end_col_offset=28,
                                    elts=[
                                        Name(lineno=23, col_offset=17, end_lineno=23, end_col_offset=21, id='code', ctx=Load()),
                                        Name(lineno=23, col_offset=23, end_lineno=23, end_col_offset=27, id='name', ctx=Load()),
                                    ],
                                    ctx=Load(),
                                ),
                                generators=[
                                    comprehension(
                                        target=Tuple(
                                            lineno=23,
                                            col_offset=33,
                                            end_lineno=23,
                                            end_col_offset=50,
                                            elts=[
                                                Name(lineno=23, col_offset=33, end_lineno=23, end_col_offset=37, id='code', ctx=Store()),
                                                Name(lineno=23, col_offset=39, end_lineno=23, end_col_offset=40, id='_', ctx=Store()),
                                                Name(lineno=23, col_offset=42, end_lineno=23, end_col_offset=46, id='name', ctx=Store()),
                                                Starred(
                                                    lineno=23,
                                                    col_offset=48,
                                                    end_lineno=23,
                                                    end_col_offset=50,
                                                    value=Name(lineno=23, col_offset=49, end_lineno=23, end_col_offset=50, id='_', ctx=Store()),
                                                    ctx=Store(),
                                                ),
                                            ],
                                            ctx=Store(),
                                        ),
                                        iter=Call(
                                            lineno=23,
                                            col_offset=54,
                                            end_lineno=23,
                                            end_col_offset=90,
                                            func=Attribute(
                                                lineno=23,
                                                col_offset=54,
                                                end_lineno=23,
                                                end_col_offset=88,
                                                value=Subscript(
                                                    lineno=23,
                                                    col_offset=54,
                                                    end_lineno=23,
                                                    end_col_offset=74,
                                                    value=Attribute(
                                                        lineno=23,
                                                        col_offset=54,
                                                        end_lineno=23,
                                                        end_col_offset=62,
                                                        value=Name(lineno=23, col_offset=54, end_lineno=23, end_col_offset=58, id='self', ctx=Load()),
                                                        attr='env',
                                                        ctx=Load(),
                                                    ),
                                                    slice=Constant(lineno=23, col_offset=63, end_lineno=23, end_col_offset=73, value='res.lang', kind=None),
                                                    ctx=Load(),
                                                ),
                                                attr='get_available',
                                                ctx=Load(),
                                            ),
                                            args=[],
                                            keywords=[],
                                        ),
                                        ifs=[],
                                        is_async=0,
                                    ),
                                ],
                            ),
                        ),
                    ],
                    decorator_list=[
                        Attribute(
                            lineno=21,
                            col_offset=5,
                            end_lineno=21,
                            end_col_offset=14,
                            value=Name(lineno=21, col_offset=5, end_lineno=21, end_col_offset=8, id='api', ctx=Load()),
                            attr='model',
                            ctx=Load(),
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
                Assign(
                    lineno=25,
                    col_offset=4,
                    end_lineno=26,
                    end_col_offset=54,
                    targets=[Name(lineno=25, col_offset=4, end_lineno=25, end_col_offset=8, id='lang', ctx=Store())],
                    value=Call(
                        lineno=25,
                        col_offset=11,
                        end_lineno=26,
                        end_col_offset=54,
                        func=Attribute(
                            lineno=25,
                            col_offset=11,
                            end_lineno=25,
                            end_col_offset=27,
                            value=Name(lineno=25, col_offset=11, end_lineno=25, end_col_offset=17, id='fields', ctx=Load()),
                            attr='Selection',
                            ctx=Load(),
                        ),
                        args=[Name(lineno=25, col_offset=28, end_lineno=25, end_col_offset=42, id='_get_languages', ctx=Load())],
                        keywords=[
                            keyword(
                                lineno=25,
                                col_offset=44,
                                end_lineno=25,
                                end_col_offset=61,
                                arg='string',
                                value=Constant(lineno=25, col_offset=51, end_lineno=25, end_col_offset=61, value='Language', kind=None),
                            ),
                            keyword(
                                lineno=25,
                                col_offset=63,
                                end_lineno=25,
                                end_col_offset=76,
                                arg='required',
                                value=Constant(lineno=25, col_offset=72, end_lineno=25, end_col_offset=76, value=True, kind=None),
                            ),
                            keyword(
                                lineno=26,
                                col_offset=28,
                                end_lineno=26,
                                end_col_offset=53,
                                arg='default',
                                value=Name(lineno=26, col_offset=36, end_lineno=26, end_col_offset=53, id='_default_language', ctx=Load()),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=27,
                    col_offset=4,
                    end_lineno=29,
                    end_col_offset=145,
                    targets=[Name(lineno=27, col_offset=4, end_lineno=27, end_col_offset=13, id='overwrite', ctx=Store())],
                    value=Call(
                        lineno=27,
                        col_offset=16,
                        end_lineno=29,
                        end_col_offset=145,
                        func=Attribute(
                            lineno=27,
                            col_offset=16,
                            end_lineno=27,
                            end_col_offset=30,
                            value=Name(lineno=27, col_offset=16, end_lineno=27, end_col_offset=22, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=27, col_offset=31, end_lineno=27, end_col_offset=57, value='Overwrite Existing Terms', kind=None)],
                        keywords=[
                            keyword(
                                lineno=28,
                                col_offset=31,
                                end_lineno=28,
                                end_col_offset=43,
                                arg='default',
                                value=Constant(lineno=28, col_offset=39, end_lineno=28, end_col_offset=43, value=True, kind=None),
                            ),
                            keyword(
                                lineno=29,
                                col_offset=31,
                                end_lineno=29,
                                end_col_offset=144,
                                arg='help',
                                value=Constant(lineno=29, col_offset=36, end_lineno=29, end_col_offset=144, value='If you check this box, your customized translations will be overwritten and replaced by the official ones.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=30,
                    col_offset=4,
                    end_lineno=31,
                    end_col_offset=76,
                    targets=[Name(lineno=30, col_offset=4, end_lineno=30, end_col_offset=9, id='state', ctx=Store())],
                    value=Call(
                        lineno=30,
                        col_offset=12,
                        end_lineno=31,
                        end_col_offset=76,
                        func=Attribute(
                            lineno=30,
                            col_offset=12,
                            end_lineno=30,
                            end_col_offset=28,
                            value=Name(lineno=30, col_offset=12, end_lineno=30, end_col_offset=18, id='fields', ctx=Load()),
                            attr='Selection',
                            ctx=Load(),
                        ),
                        args=[
                            List(
                                lineno=30,
                                col_offset=29,
                                end_lineno=30,
                                end_col_offset=65,
                                elts=[
                                    Tuple(
                                        lineno=30,
                                        col_offset=30,
                                        end_lineno=30,
                                        end_col_offset=46,
                                        elts=[
                                            Constant(lineno=30, col_offset=31, end_lineno=30, end_col_offset=37, value='init', kind=None),
                                            Constant(lineno=30, col_offset=39, end_lineno=30, end_col_offset=45, value='init', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                    Tuple(
                                        lineno=30,
                                        col_offset=48,
                                        end_lineno=30,
                                        end_col_offset=64,
                                        elts=[
                                            Constant(lineno=30, col_offset=49, end_lineno=30, end_col_offset=55, value='done', kind=None),
                                            Constant(lineno=30, col_offset=57, end_lineno=30, end_col_offset=63, value='done', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                ctx=Load(),
                            ),
                        ],
                        keywords=[
                            keyword(
                                lineno=31,
                                col_offset=29,
                                end_lineno=31,
                                end_col_offset=44,
                                arg='string',
                                value=Constant(lineno=31, col_offset=36, end_lineno=31, end_col_offset=44, value='Status', kind=None),
                            ),
                            keyword(
                                lineno=31,
                                col_offset=46,
                                end_lineno=31,
                                end_col_offset=59,
                                arg='readonly',
                                value=Constant(lineno=31, col_offset=55, end_lineno=31, end_col_offset=59, value=True, kind=None),
                            ),
                            keyword(
                                lineno=31,
                                col_offset=61,
                                end_lineno=31,
                                end_col_offset=75,
                                arg='default',
                                value=Constant(lineno=31, col_offset=69, end_lineno=31, end_col_offset=75, value='init', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=33,
                    col_offset=4,
                    end_lineno=51,
                    end_col_offset=9,
                    name='lang_install',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=33, col_offset=21, end_lineno=33, end_col_offset=25, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=34,
                            col_offset=8,
                            end_lineno=34,
                            end_col_offset=25,
                            value=Call(
                                lineno=34,
                                col_offset=8,
                                end_lineno=34,
                                end_col_offset=25,
                                func=Attribute(
                                    lineno=34,
                                    col_offset=8,
                                    end_lineno=34,
                                    end_col_offset=23,
                                    value=Name(lineno=34, col_offset=8, end_lineno=34, end_col_offset=12, id='self', ctx=Load()),
                                    attr='ensure_one',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=35,
                            col_offset=8,
                            end_lineno=35,
                            end_col_offset=81,
                            targets=[Name(lineno=35, col_offset=8, end_lineno=35, end_col_offset=12, id='mods', ctx=Store())],
                            value=Call(
                                lineno=35,
                                col_offset=15,
                                end_lineno=35,
                                end_col_offset=81,
                                func=Attribute(
                                    lineno=35,
                                    col_offset=15,
                                    end_lineno=35,
                                    end_col_offset=50,
                                    value=Subscript(
                                        lineno=35,
                                        col_offset=15,
                                        end_lineno=35,
                                        end_col_offset=43,
                                        value=Attribute(
                                            lineno=35,
                                            col_offset=15,
                                            end_lineno=35,
                                            end_col_offset=23,
                                            value=Name(lineno=35, col_offset=15, end_lineno=35, end_col_offset=19, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=35, col_offset=24, end_lineno=35, end_col_offset=42, value='ir.module.module', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='search',
                                    ctx=Load(),
                                ),
                                args=[
                                    List(
                                        lineno=35,
                                        col_offset=51,
                                        end_lineno=35,
                                        end_col_offset=80,
                                        elts=[
                                            Tuple(
                                                lineno=35,
                                                col_offset=52,
                                                end_lineno=35,
                                                end_col_offset=79,
                                                elts=[
                                                    Constant(lineno=35, col_offset=53, end_lineno=35, end_col_offset=60, value='state', kind=None),
                                                    Constant(lineno=35, col_offset=62, end_lineno=35, end_col_offset=65, value='=', kind=None),
                                                    Constant(lineno=35, col_offset=67, end_lineno=35, end_col_offset=78, value='installed', kind=None),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=36,
                            col_offset=8,
                            end_lineno=36,
                            end_col_offset=54,
                            value=Call(
                                lineno=36,
                                col_offset=8,
                                end_lineno=36,
                                end_col_offset=54,
                                func=Attribute(
                                    lineno=36,
                                    col_offset=8,
                                    end_lineno=36,
                                    end_col_offset=43,
                                    value=Subscript(
                                        lineno=36,
                                        col_offset=8,
                                        end_lineno=36,
                                        end_col_offset=28,
                                        value=Attribute(
                                            lineno=36,
                                            col_offset=8,
                                            end_lineno=36,
                                            end_col_offset=16,
                                            value=Name(lineno=36, col_offset=8, end_lineno=36, end_col_offset=12, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=36, col_offset=17, end_lineno=36, end_col_offset=27, value='res.lang', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='_activate_lang',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=36,
                                        col_offset=44,
                                        end_lineno=36,
                                        end_col_offset=53,
                                        value=Name(lineno=36, col_offset=44, end_lineno=36, end_col_offset=48, id='self', ctx=Load()),
                                        attr='lang',
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=37,
                            col_offset=8,
                            end_lineno=37,
                            end_col_offset=60,
                            value=Call(
                                lineno=37,
                                col_offset=8,
                                end_lineno=37,
                                end_col_offset=60,
                                func=Attribute(
                                    lineno=37,
                                    col_offset=8,
                                    end_lineno=37,
                                    end_col_offset=33,
                                    value=Name(lineno=37, col_offset=8, end_lineno=37, end_col_offset=12, id='mods', ctx=Load()),
                                    attr='_update_translations',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=37,
                                        col_offset=34,
                                        end_lineno=37,
                                        end_col_offset=43,
                                        value=Name(lineno=37, col_offset=34, end_lineno=37, end_col_offset=38, id='self', ctx=Load()),
                                        attr='lang',
                                        ctx=Load(),
                                    ),
                                    Attribute(
                                        lineno=37,
                                        col_offset=45,
                                        end_lineno=37,
                                        end_col_offset=59,
                                        value=Name(lineno=37, col_offset=45, end_lineno=37, end_col_offset=49, id='self', ctx=Load()),
                                        attr='overwrite',
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=38,
                            col_offset=8,
                            end_lineno=38,
                            end_col_offset=27,
                            targets=[
                                Attribute(
                                    lineno=38,
                                    col_offset=8,
                                    end_lineno=38,
                                    end_col_offset=18,
                                    value=Name(lineno=38, col_offset=8, end_lineno=38, end_col_offset=12, id='self', ctx=Load()),
                                    attr='state',
                                    ctx=Store(),
                                ),
                            ],
                            value=Constant(lineno=38, col_offset=21, end_lineno=38, end_col_offset=27, value='done', kind=None),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=39,
                            col_offset=8,
                            end_lineno=39,
                            end_col_offset=53,
                            value=Call(
                                lineno=39,
                                col_offset=8,
                                end_lineno=39,
                                end_col_offset=53,
                                func=Attribute(
                                    lineno=39,
                                    col_offset=8,
                                    end_lineno=39,
                                    end_col_offset=27,
                                    value=Attribute(
                                        lineno=39,
                                        col_offset=8,
                                        end_lineno=39,
                                        end_col_offset=19,
                                        value=Attribute(
                                            lineno=39,
                                            col_offset=8,
                                            end_lineno=39,
                                            end_col_offset=16,
                                            value=Name(lineno=39, col_offset=8, end_lineno=39, end_col_offset=12, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        attr='cr',
                                        ctx=Load(),
                                    ),
                                    attr='execute',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=39, col_offset=28, end_lineno=39, end_col_offset=52, value='ANALYZE ir_translation', kind=None)],
                                keywords=[],
                            ),
                        ),
                        Return(
                            lineno=41,
                            col_offset=8,
                            end_lineno=51,
                            end_col_offset=9,
                            value=Dict(
                                lineno=41,
                                col_offset=15,
                                end_lineno=51,
                                end_col_offset=9,
                                keys=[
                                    Constant(lineno=42, col_offset=12, end_lineno=42, end_col_offset=18, value='name', kind=None),
                                    Constant(lineno=43, col_offset=12, end_lineno=43, end_col_offset=23, value='view_mode', kind=None),
                                    Constant(lineno=44, col_offset=12, end_lineno=44, end_col_offset=21, value='view_id', kind=None),
                                    Constant(lineno=45, col_offset=12, end_lineno=45, end_col_offset=23, value='res_model', kind=None),
                                    Constant(lineno=46, col_offset=12, end_lineno=46, end_col_offset=20, value='domain', kind=None),
                                    Constant(lineno=47, col_offset=12, end_lineno=47, end_col_offset=21, value='context', kind=None),
                                    Constant(lineno=48, col_offset=12, end_lineno=48, end_col_offset=18, value='type', kind=None),
                                    Constant(lineno=49, col_offset=12, end_lineno=49, end_col_offset=20, value='target', kind=None),
                                    Constant(lineno=50, col_offset=12, end_lineno=50, end_col_offset=20, value='res_id', kind=None),
                                ],
                                values=[
                                    Call(
                                        lineno=42,
                                        col_offset=20,
                                        end_lineno=42,
                                        end_col_offset=38,
                                        func=Name(lineno=42, col_offset=20, end_lineno=42, end_col_offset=21, id='_', ctx=Load()),
                                        args=[Constant(lineno=42, col_offset=22, end_lineno=42, end_col_offset=37, value='Language Pack', kind=None)],
                                        keywords=[],
                                    ),
                                    Constant(lineno=43, col_offset=25, end_lineno=43, end_col_offset=31, value='form', kind=None),
                                    Constant(lineno=44, col_offset=23, end_lineno=44, end_col_offset=28, value=False, kind=None),
                                    Constant(lineno=45, col_offset=25, end_lineno=45, end_col_offset=48, value='base.language.install', kind=None),
                                    List(lineno=46, col_offset=22, end_lineno=46, end_col_offset=24, elts=[], ctx=Load()),
                                    Call(
                                        lineno=47,
                                        col_offset=23,
                                        end_lineno=47,
                                        end_col_offset=63,
                                        func=Name(lineno=47, col_offset=23, end_lineno=47, end_col_offset=27, id='dict', ctx=Load()),
                                        args=[
                                            Attribute(
                                                lineno=47,
                                                col_offset=28,
                                                end_lineno=47,
                                                end_col_offset=41,
                                                value=Name(lineno=47, col_offset=28, end_lineno=47, end_col_offset=32, id='self', ctx=Load()),
                                                attr='_context',
                                                ctx=Load(),
                                            ),
                                        ],
                                        keywords=[
                                            keyword(
                                                lineno=47,
                                                col_offset=43,
                                                end_lineno=47,
                                                end_col_offset=62,
                                                arg='active_ids',
                                                value=Attribute(
                                                    lineno=47,
                                                    col_offset=54,
                                                    end_lineno=47,
                                                    end_col_offset=62,
                                                    value=Name(lineno=47, col_offset=54, end_lineno=47, end_col_offset=58, id='self', ctx=Load()),
                                                    attr='ids',
                                                    ctx=Load(),
                                                ),
                                            ),
                                        ],
                                    ),
                                    Constant(lineno=48, col_offset=20, end_lineno=48, end_col_offset=43, value='ir.actions.act_window', kind=None),
                                    Constant(lineno=49, col_offset=22, end_lineno=49, end_col_offset=27, value='new', kind=None),
                                    Attribute(
                                        lineno=50,
                                        col_offset=22,
                                        end_lineno=50,
                                        end_col_offset=29,
                                        value=Name(lineno=50, col_offset=22, end_lineno=50, end_col_offset=26, id='self', ctx=Load()),
                                        attr='id',
                                        ctx=Load(),
                                    ),
                                ],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=53,
                    col_offset=4,
                    end_lineno=57,
                    end_col_offset=9,
                    name='reload',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=53, col_offset=15, end_lineno=53, end_col_offset=19, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Return(
                            lineno=54,
                            col_offset=8,
                            end_lineno=57,
                            end_col_offset=9,
                            value=Dict(
                                lineno=54,
                                col_offset=15,
                                end_lineno=57,
                                end_col_offset=9,
                                keys=[
                                    Constant(lineno=55, col_offset=12, end_lineno=55, end_col_offset=18, value='type', kind=None),
                                    Constant(lineno=56, col_offset=12, end_lineno=56, end_col_offset=17, value='tag', kind=None),
                                ],
                                values=[
                                    Constant(lineno=55, col_offset=20, end_lineno=55, end_col_offset=39, value='ir.actions.client', kind=None),
                                    Constant(lineno=56, col_offset=19, end_lineno=56, end_col_offset=27, value='reload', kind=None),
                                ],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=59,
                    col_offset=4,
                    end_lineno=64,
                    end_col_offset=9,
                    name='switch_lang',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=59, col_offset=20, end_lineno=59, end_col_offset=24, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=60,
                            col_offset=8,
                            end_lineno=60,
                            end_col_offset=38,
                            targets=[
                                Attribute(
                                    lineno=60,
                                    col_offset=8,
                                    end_lineno=60,
                                    end_col_offset=26,
                                    value=Attribute(
                                        lineno=60,
                                        col_offset=8,
                                        end_lineno=60,
                                        end_col_offset=21,
                                        value=Attribute(
                                            lineno=60,
                                            col_offset=8,
                                            end_lineno=60,
                                            end_col_offset=16,
                                            value=Name(lineno=60, col_offset=8, end_lineno=60, end_col_offset=12, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        attr='user',
                                        ctx=Load(),
                                    ),
                                    attr='lang',
                                    ctx=Store(),
                                ),
                            ],
                            value=Attribute(
                                lineno=60,
                                col_offset=29,
                                end_lineno=60,
                                end_col_offset=38,
                                value=Name(lineno=60, col_offset=29, end_lineno=60, end_col_offset=33, id='self', ctx=Load()),
                                attr='lang',
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        Return(
                            lineno=61,
                            col_offset=8,
                            end_lineno=64,
                            end_col_offset=9,
                            value=Dict(
                                lineno=61,
                                col_offset=15,
                                end_lineno=64,
                                end_col_offset=9,
                                keys=[
                                    Constant(lineno=62, col_offset=12, end_lineno=62, end_col_offset=18, value='type', kind=None),
                                    Constant(lineno=63, col_offset=12, end_lineno=63, end_col_offset=17, value='tag', kind=None),
                                ],
                                values=[
                                    Constant(lineno=62, col_offset=20, end_lineno=62, end_col_offset=39, value='ir.actions.client', kind=None),
                                    Constant(lineno=63, col_offset=19, end_lineno=63, end_col_offset=35, value='reload_context', kind=None),
                                ],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
