Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=34,
            module='odoo',
            names=[
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
                alias(name='_', asname=None),
            ],
            level=0,
        ),
        ImportFrom(
            lineno=5,
            col_offset=0,
            end_lineno=5,
            end_col_offset=39,
            module='odoo.exceptions',
            names=[alias(name='AccessError', asname=None)],
            level=0,
        ),
        ClassDef(
            lineno=8,
            col_offset=0,
            end_lineno=29,
            end_col_offset=18,
            name='Digest',
            bases=[
                Attribute(
                    lineno=8,
                    col_offset=13,
                    end_lineno=8,
                    end_col_offset=25,
                    value=Name(lineno=8, col_offset=13, end_lineno=8, end_col_offset=19, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=9,
                    col_offset=4,
                    end_lineno=9,
                    end_col_offset=30,
                    targets=[Name(lineno=9, col_offset=4, end_lineno=9, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=9, col_offset=15, end_lineno=9, end_col_offset=30, value='digest.digest', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=11,
                    col_offset=4,
                    end_lineno=11,
                    end_col_offset=52,
                    targets=[Name(lineno=11, col_offset=4, end_lineno=11, end_col_offset=22, id='kpi_all_sale_total', ctx=Store())],
                    value=Call(
                        lineno=11,
                        col_offset=25,
                        end_lineno=11,
                        end_col_offset=52,
                        func=Attribute(
                            lineno=11,
                            col_offset=25,
                            end_lineno=11,
                            end_col_offset=39,
                            value=Name(lineno=11, col_offset=25, end_lineno=11, end_col_offset=31, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=11, col_offset=40, end_lineno=11, end_col_offset=51, value='All Sales', kind=None)],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=12,
                    col_offset=4,
                    end_lineno=12,
                    end_col_offset=87,
                    targets=[Name(lineno=12, col_offset=4, end_lineno=12, end_col_offset=28, id='kpi_all_sale_total_value', ctx=Store())],
                    value=Call(
                        lineno=12,
                        col_offset=31,
                        end_lineno=12,
                        end_col_offset=87,
                        func=Attribute(
                            lineno=12,
                            col_offset=31,
                            end_lineno=12,
                            end_col_offset=46,
                            value=Name(lineno=12, col_offset=31, end_lineno=12, end_col_offset=37, id='fields', ctx=Load()),
                            attr='Monetary',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=12,
                                col_offset=47,
                                end_lineno=12,
                                end_col_offset=86,
                                arg='compute',
                                value=Constant(lineno=12, col_offset=55, end_lineno=12, end_col_offset=86, value='_compute_kpi_sale_total_value', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=14,
                    col_offset=4,
                    end_lineno=24,
                    end_col_offset=119,
                    name='_compute_kpi_sale_total_value',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=14, col_offset=38, end_lineno=14, end_col_offset=42, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        If(
                            lineno=15,
                            col_offset=8,
                            end_lineno=16,
                            end_col_offset=94,
                            test=UnaryOp(
                                lineno=15,
                                col_offset=11,
                                end_lineno=15,
                                end_col_offset=82,
                                op=Not(),
                                operand=Call(
                                    lineno=15,
                                    col_offset=15,
                                    end_lineno=15,
                                    end_col_offset=82,
                                    func=Attribute(
                                        lineno=15,
                                        col_offset=15,
                                        end_lineno=15,
                                        end_col_offset=38,
                                        value=Attribute(
                                            lineno=15,
                                            col_offset=15,
                                            end_lineno=15,
                                            end_col_offset=28,
                                            value=Attribute(
                                                lineno=15,
                                                col_offset=15,
                                                end_lineno=15,
                                                end_col_offset=23,
                                                value=Name(lineno=15, col_offset=15, end_lineno=15, end_col_offset=19, id='self', ctx=Load()),
                                                attr='env',
                                                ctx=Load(),
                                            ),
                                            attr='user',
                                            ctx=Load(),
                                        ),
                                        attr='has_group',
                                        ctx=Load(),
                                    ),
                                    args=[Constant(lineno=15, col_offset=39, end_lineno=15, end_col_offset=81, value='sales_team.group_sale_salesman_all_leads', kind=None)],
                                    keywords=[],
                                ),
                            ),
                            body=[
                                Raise(
                                    lineno=16,
                                    col_offset=12,
                                    end_lineno=16,
                                    end_col_offset=94,
                                    exc=Call(
                                        lineno=16,
                                        col_offset=18,
                                        end_lineno=16,
                                        end_col_offset=94,
                                        func=Name(lineno=16, col_offset=18, end_lineno=16, end_col_offset=29, id='AccessError', ctx=Load()),
                                        args=[
                                            Call(
                                                lineno=16,
                                                col_offset=30,
                                                end_lineno=16,
                                                end_col_offset=93,
                                                func=Name(lineno=16, col_offset=30, end_lineno=16, end_col_offset=31, id='_', ctx=Load()),
                                                args=[Constant(lineno=16, col_offset=32, end_lineno=16, end_col_offset=92, value="Do not have access, skip this data for user's digest email", kind=None)],
                                                keywords=[],
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                    cause=None,
                                ),
                            ],
                            orelse=[],
                        ),
                        For(
                            lineno=17,
                            col_offset=8,
                            end_lineno=24,
                            end_col_offset=119,
                            target=Name(lineno=17, col_offset=12, end_lineno=17, end_col_offset=18, id='record', ctx=Store()),
                            iter=Name(lineno=17, col_offset=22, end_lineno=17, end_col_offset=26, id='self', ctx=Load()),
                            body=[
                                Assign(
                                    lineno=18,
                                    col_offset=12,
                                    end_lineno=18,
                                    end_col_offset=70,
                                    targets=[
                                        Tuple(
                                            lineno=18,
                                            col_offset=12,
                                            end_lineno=18,
                                            end_col_offset=31,
                                            elts=[
                                                Name(lineno=18, col_offset=12, end_lineno=18, end_col_offset=17, id='start', ctx=Store()),
                                                Name(lineno=18, col_offset=19, end_lineno=18, end_col_offset=22, id='end', ctx=Store()),
                                                Name(lineno=18, col_offset=24, end_lineno=18, end_col_offset=31, id='company', ctx=Store()),
                                            ],
                                            ctx=Store(),
                                        ),
                                    ],
                                    value=Call(
                                        lineno=18,
                                        col_offset=34,
                                        end_lineno=18,
                                        end_col_offset=70,
                                        func=Attribute(
                                            lineno=18,
                                            col_offset=34,
                                            end_lineno=18,
                                            end_col_offset=68,
                                            value=Name(lineno=18, col_offset=34, end_lineno=18, end_col_offset=40, id='record', ctx=Load()),
                                            attr='_get_kpi_compute_parameters',
                                            ctx=Load(),
                                        ),
                                        args=[],
                                        keywords=[],
                                    ),
                                    type_comment=None,
                                ),
                                Assign(
                                    lineno=19,
                                    col_offset=12,
                                    end_lineno=23,
                                    end_col_offset=83,
                                    targets=[Name(lineno=19, col_offset=12, end_lineno=19, end_col_offset=30, id='all_channels_sales', ctx=Store())],
                                    value=Call(
                                        lineno=19,
                                        col_offset=33,
                                        end_lineno=23,
                                        end_col_offset=83,
                                        func=Attribute(
                                            lineno=19,
                                            col_offset=33,
                                            end_lineno=19,
                                            end_col_offset=67,
                                            value=Subscript(
                                                lineno=19,
                                                col_offset=33,
                                                end_lineno=19,
                                                end_col_offset=56,
                                                value=Attribute(
                                                    lineno=19,
                                                    col_offset=33,
                                                    end_lineno=19,
                                                    end_col_offset=41,
                                                    value=Name(lineno=19, col_offset=33, end_lineno=19, end_col_offset=37, id='self', ctx=Load()),
                                                    attr='env',
                                                    ctx=Load(),
                                                ),
                                                slice=Constant(lineno=19, col_offset=42, end_lineno=19, end_col_offset=55, value='sale.report', kind=None),
                                                ctx=Load(),
                                            ),
                                            attr='read_group',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            List(
                                                lineno=19,
                                                col_offset=68,
                                                end_lineno=23,
                                                end_col_offset=48,
                                                elts=[
                                                    Tuple(
                                                        lineno=20,
                                                        col_offset=16,
                                                        end_lineno=20,
                                                        end_col_offset=37,
                                                        elts=[
                                                            Constant(lineno=20, col_offset=17, end_lineno=20, end_col_offset=23, value='date', kind=None),
                                                            Constant(lineno=20, col_offset=25, end_lineno=20, end_col_offset=29, value='>=', kind=None),
                                                            Name(lineno=20, col_offset=31, end_lineno=20, end_col_offset=36, id='start', ctx=Load()),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                    Tuple(
                                                        lineno=21,
                                                        col_offset=16,
                                                        end_lineno=21,
                                                        end_col_offset=34,
                                                        elts=[
                                                            Constant(lineno=21, col_offset=17, end_lineno=21, end_col_offset=23, value='date', kind=None),
                                                            Constant(lineno=21, col_offset=25, end_lineno=21, end_col_offset=28, value='<', kind=None),
                                                            Name(lineno=21, col_offset=30, end_lineno=21, end_col_offset=33, id='end', ctx=Load()),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                    Tuple(
                                                        lineno=22,
                                                        col_offset=16,
                                                        end_lineno=22,
                                                        end_col_offset=64,
                                                        elts=[
                                                            Constant(lineno=22, col_offset=17, end_lineno=22, end_col_offset=24, value='state', kind=None),
                                                            Constant(lineno=22, col_offset=26, end_lineno=22, end_col_offset=34, value='not in', kind=None),
                                                            List(
                                                                lineno=22,
                                                                col_offset=36,
                                                                end_lineno=22,
                                                                end_col_offset=63,
                                                                elts=[
                                                                    Constant(lineno=22, col_offset=37, end_lineno=22, end_col_offset=44, value='draft', kind=None),
                                                                    Constant(lineno=22, col_offset=46, end_lineno=22, end_col_offset=54, value='cancel', kind=None),
                                                                    Constant(lineno=22, col_offset=56, end_lineno=22, end_col_offset=62, value='sent', kind=None),
                                                                ],
                                                                ctx=Load(),
                                                            ),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                    Tuple(
                                                        lineno=23,
                                                        col_offset=16,
                                                        end_lineno=23,
                                                        end_col_offset=47,
                                                        elts=[
                                                            Constant(lineno=23, col_offset=17, end_lineno=23, end_col_offset=29, value='company_id', kind=None),
                                                            Constant(lineno=23, col_offset=31, end_lineno=23, end_col_offset=34, value='=', kind=None),
                                                            Attribute(
                                                                lineno=23,
                                                                col_offset=36,
                                                                end_lineno=23,
                                                                end_col_offset=46,
                                                                value=Name(lineno=23, col_offset=36, end_lineno=23, end_col_offset=43, id='company', ctx=Load()),
                                                                attr='id',
                                                                ctx=Load(),
                                                            ),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                            List(
                                                lineno=23,
                                                col_offset=50,
                                                end_lineno=23,
                                                end_col_offset=65,
                                                elts=[Constant(lineno=23, col_offset=51, end_lineno=23, end_col_offset=64, value='price_total', kind=None)],
                                                ctx=Load(),
                                            ),
                                            List(
                                                lineno=23,
                                                col_offset=67,
                                                end_lineno=23,
                                                end_col_offset=82,
                                                elts=[Constant(lineno=23, col_offset=68, end_lineno=23, end_col_offset=81, value='price_total', kind=None)],
                                                ctx=Load(),
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                    type_comment=None,
                                ),
                                Assign(
                                    lineno=24,
                                    col_offset=12,
                                    end_lineno=24,
                                    end_col_offset=119,
                                    targets=[
                                        Attribute(
                                            lineno=24,
                                            col_offset=12,
                                            end_lineno=24,
                                            end_col_offset=43,
                                            value=Name(lineno=24, col_offset=12, end_lineno=24, end_col_offset=18, id='record', ctx=Load()),
                                            attr='kpi_all_sale_total_value',
                                            ctx=Store(),
                                        ),
                                    ],
                                    value=Call(
                                        lineno=24,
                                        col_offset=46,
                                        end_lineno=24,
                                        end_col_offset=119,
                                        func=Name(lineno=24, col_offset=46, end_lineno=24, end_col_offset=49, id='sum', ctx=Load()),
                                        args=[
                                            ListComp(
                                                lineno=24,
                                                col_offset=50,
                                                end_lineno=24,
                                                end_col_offset=118,
                                                elt=Subscript(
                                                    lineno=24,
                                                    col_offset=51,
                                                    end_lineno=24,
                                                    end_col_offset=78,
                                                    value=Name(lineno=24, col_offset=51, end_lineno=24, end_col_offset=63, id='channel_sale', ctx=Load()),
                                                    slice=Constant(lineno=24, col_offset=64, end_lineno=24, end_col_offset=77, value='price_total', kind=None),
                                                    ctx=Load(),
                                                ),
                                                generators=[
                                                    comprehension(
                                                        target=Name(lineno=24, col_offset=83, end_lineno=24, end_col_offset=95, id='channel_sale', ctx=Store()),
                                                        iter=Name(lineno=24, col_offset=99, end_lineno=24, end_col_offset=117, id='all_channels_sales', ctx=Load()),
                                                        ifs=[],
                                                        is_async=0,
                                                    ),
                                                ],
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[],
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=26,
                    col_offset=4,
                    end_lineno=29,
                    end_col_offset=18,
                    name='_compute_kpis_actions',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=26, col_offset=30, end_lineno=26, end_col_offset=34, arg='self', annotation=None, type_comment=None),
                            arg(lineno=26, col_offset=36, end_lineno=26, end_col_offset=43, arg='company', annotation=None, type_comment=None),
                            arg(lineno=26, col_offset=45, end_lineno=26, end_col_offset=49, arg='user', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=27,
                            col_offset=8,
                            end_lineno=27,
                            end_col_offset=70,
                            targets=[Name(lineno=27, col_offset=8, end_lineno=27, end_col_offset=11, id='res', ctx=Store())],
                            value=Call(
                                lineno=27,
                                col_offset=14,
                                end_lineno=27,
                                end_col_offset=70,
                                func=Attribute(
                                    lineno=27,
                                    col_offset=14,
                                    end_lineno=27,
                                    end_col_offset=55,
                                    value=Call(
                                        lineno=27,
                                        col_offset=14,
                                        end_lineno=27,
                                        end_col_offset=33,
                                        func=Name(lineno=27, col_offset=14, end_lineno=27, end_col_offset=19, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=27, col_offset=20, end_lineno=27, end_col_offset=26, id='Digest', ctx=Load()),
                                            Name(lineno=27, col_offset=28, end_lineno=27, end_col_offset=32, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='_compute_kpis_actions',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=27, col_offset=56, end_lineno=27, end_col_offset=63, id='company', ctx=Load()),
                                    Name(lineno=27, col_offset=65, end_lineno=27, end_col_offset=69, id='user', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=28,
                            col_offset=8,
                            end_lineno=28,
                            end_col_offset=127,
                            targets=[
                                Subscript(
                                    lineno=28,
                                    col_offset=8,
                                    end_lineno=28,
                                    end_col_offset=33,
                                    value=Name(lineno=28, col_offset=8, end_lineno=28, end_col_offset=11, id='res', ctx=Load()),
                                    slice=Constant(lineno=28, col_offset=12, end_lineno=28, end_col_offset=32, value='kpi_all_sale_total', kind=None),
                                    ctx=Store(),
                                ),
                            ],
                            value=BinOp(
                                lineno=28,
                                col_offset=36,
                                end_lineno=28,
                                end_col_offset=127,
                                left=Constant(lineno=28, col_offset=36, end_lineno=28, end_col_offset=86, value='sale.report_all_channels_sales_action&menu_id=%s', kind=None),
                                op=Mod(),
                                right=Attribute(
                                    lineno=28,
                                    col_offset=89,
                                    end_lineno=28,
                                    end_col_offset=127,
                                    value=Call(
                                        lineno=28,
                                        col_offset=89,
                                        end_lineno=28,
                                        end_col_offset=124,
                                        func=Attribute(
                                            lineno=28,
                                            col_offset=89,
                                            end_lineno=28,
                                            end_col_offset=101,
                                            value=Attribute(
                                                lineno=28,
                                                col_offset=89,
                                                end_lineno=28,
                                                end_col_offset=97,
                                                value=Name(lineno=28, col_offset=89, end_lineno=28, end_col_offset=93, id='self', ctx=Load()),
                                                attr='env',
                                                ctx=Load(),
                                            ),
                                            attr='ref',
                                            ctx=Load(),
                                        ),
                                        args=[Constant(lineno=28, col_offset=102, end_lineno=28, end_col_offset=123, value='sale.sale_menu_root', kind=None)],
                                        keywords=[],
                                    ),
                                    attr='id',
                                    ctx=Load(),
                                ),
                            ),
                            type_comment=None,
                        ),
                        Return(
                            lineno=29,
                            col_offset=8,
                            end_lineno=29,
                            end_col_offset=18,
                            value=Name(lineno=29, col_offset=15, end_lineno=29, end_col_offset=18, id='res', ctx=Load()),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
