Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=63,
            module='odoo.addons.phone_validation.tools',
            names=[alias(name='phone_validation', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=5,
            col_offset=0,
            end_lineno=5,
            end_col_offset=67,
            module='odoo.addons.mass_mailing_sms.tests.common',
            names=[alias(name='MassSMSCommon', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=6,
            col_offset=0,
            end_lineno=6,
            end_col_offset=46,
            module='odoo.addons.test_mail.tests',
            names=[alias(name='common', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=7,
            col_offset=0,
            end_lineno=7,
            end_col_offset=73,
            module='odoo.addons.test_mass_mailing.tests.common',
            names=[alias(name='TestMassMailCommon', asname=None)],
            level=0,
        ),
        ClassDef(
            lineno=10,
            col_offset=0,
            end_lineno=45,
            end_col_offset=47,
            name='TestMailFullCommon',
            bases=[
                Name(lineno=10, col_offset=25, end_lineno=10, end_col_offset=43, id='TestMassMailCommon', ctx=Load()),
                Name(lineno=10, col_offset=45, end_lineno=10, end_col_offset=58, id='MassSMSCommon', ctx=Load()),
            ],
            keywords=[],
            body=[
                FunctionDef(
                    lineno=13,
                    col_offset=4,
                    end_lineno=25,
                    end_col_offset=10,
                    name='setUpClass',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=13, col_offset=19, end_lineno=13, end_col_offset=22, arg='cls', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=14,
                            col_offset=8,
                            end_lineno=14,
                            end_col_offset=51,
                            value=Call(
                                lineno=14,
                                col_offset=8,
                                end_lineno=14,
                                end_col_offset=51,
                                func=Attribute(
                                    lineno=14,
                                    col_offset=8,
                                    end_lineno=14,
                                    end_col_offset=49,
                                    value=Call(
                                        lineno=14,
                                        col_offset=8,
                                        end_lineno=14,
                                        end_col_offset=38,
                                        func=Name(lineno=14, col_offset=8, end_lineno=14, end_col_offset=13, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=14, col_offset=14, end_lineno=14, end_col_offset=32, id='TestMailFullCommon', ctx=Load()),
                                            Name(lineno=14, col_offset=34, end_lineno=14, end_col_offset=37, id='cls', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='setUpClass',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=16,
                            col_offset=8,
                            end_lineno=25,
                            end_col_offset=10,
                            targets=[
                                Attribute(
                                    lineno=16,
                                    col_offset=8,
                                    end_lineno=16,
                                    end_col_offset=23,
                                    value=Name(lineno=16, col_offset=8, end_lineno=16, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='mailing_sms',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=16,
                                col_offset=26,
                                end_lineno=25,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=16,
                                    col_offset=26,
                                    end_lineno=16,
                                    end_col_offset=89,
                                    value=Call(
                                        lineno=16,
                                        col_offset=26,
                                        end_lineno=16,
                                        end_col_offset=82,
                                        func=Attribute(
                                            lineno=16,
                                            col_offset=26,
                                            end_lineno=16,
                                            end_col_offset=62,
                                            value=Subscript(
                                                lineno=16,
                                                col_offset=26,
                                                end_lineno=16,
                                                end_col_offset=52,
                                                value=Attribute(
                                                    lineno=16,
                                                    col_offset=26,
                                                    end_lineno=16,
                                                    end_col_offset=33,
                                                    value=Name(lineno=16, col_offset=26, end_lineno=16, end_col_offset=29, id='cls', ctx=Load()),
                                                    attr='env',
                                                    ctx=Load(),
                                                ),
                                                slice=Constant(lineno=16, col_offset=34, end_lineno=16, end_col_offset=51, value='mailing.mailing', kind=None),
                                                ctx=Load(),
                                            ),
                                            attr='with_user',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Attribute(
                                                lineno=16,
                                                col_offset=63,
                                                end_lineno=16,
                                                end_col_offset=81,
                                                value=Name(lineno=16, col_offset=63, end_lineno=16, end_col_offset=66, id='cls', ctx=Load()),
                                                attr='user_marketing',
                                                ctx=Load(),
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=16,
                                        col_offset=90,
                                        end_lineno=25,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=17, col_offset=12, end_lineno=17, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=18, col_offset=12, end_lineno=18, end_col_offset=21, value='subject', kind=None),
                                            Constant(lineno=19, col_offset=12, end_lineno=19, end_col_offset=30, value='mailing_model_id', kind=None),
                                            Constant(lineno=20, col_offset=12, end_lineno=20, end_col_offset=26, value='mailing_type', kind=None),
                                            Constant(lineno=21, col_offset=12, end_lineno=21, end_col_offset=28, value='mailing_domain', kind=None),
                                            Constant(lineno=22, col_offset=12, end_lineno=22, end_col_offset=28, value='body_plaintext', kind=None),
                                            Constant(lineno=23, col_offset=12, end_lineno=23, end_col_offset=28, value='sms_force_send', kind=None),
                                            Constant(lineno=24, col_offset=12, end_lineno=24, end_col_offset=35, value='sms_allow_unsubscribe', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=17, col_offset=20, end_lineno=17, end_col_offset=30, value='XMas SMS', kind=None),
                                            Constant(lineno=18, col_offset=23, end_lineno=18, end_col_offset=51, value='Xmas SMS for {object.name}', kind=None),
                                            Attribute(
                                                lineno=19,
                                                col_offset=32,
                                                end_lineno=19,
                                                end_col_offset=76,
                                                value=Call(
                                                    lineno=19,
                                                    col_offset=32,
                                                    end_lineno=19,
                                                    end_col_offset=73,
                                                    func=Attribute(
                                                        lineno=19,
                                                        col_offset=32,
                                                        end_lineno=19,
                                                        end_col_offset=56,
                                                        value=Subscript(
                                                            lineno=19,
                                                            col_offset=32,
                                                            end_lineno=19,
                                                            end_col_offset=51,
                                                            value=Attribute(
                                                                lineno=19,
                                                                col_offset=32,
                                                                end_lineno=19,
                                                                end_col_offset=39,
                                                                value=Name(lineno=19, col_offset=32, end_lineno=19, end_col_offset=35, id='cls', ctx=Load()),
                                                                attr='env',
                                                                ctx=Load(),
                                                            ),
                                                            slice=Constant(lineno=19, col_offset=40, end_lineno=19, end_col_offset=50, value='ir.model', kind=None),
                                                            ctx=Load(),
                                                        ),
                                                        attr='_get',
                                                        ctx=Load(),
                                                    ),
                                                    args=[Constant(lineno=19, col_offset=57, end_lineno=19, end_col_offset=72, value='mail.test.sms', kind=None)],
                                                    keywords=[],
                                                ),
                                                attr='id',
                                                ctx=Load(),
                                            ),
                                            Constant(lineno=20, col_offset=28, end_lineno=20, end_col_offset=33, value='sms', kind=None),
                                            BinOp(
                                                lineno=21,
                                                col_offset=30,
                                                end_lineno=21,
                                                end_col_offset=73,
                                                left=Constant(lineno=21, col_offset=30, end_lineno=21, end_col_offset=34, value='%s', kind=None),
                                                op=Mod(),
                                                right=Call(
                                                    lineno=21,
                                                    col_offset=37,
                                                    end_lineno=21,
                                                    end_col_offset=73,
                                                    func=Name(lineno=21, col_offset=37, end_lineno=21, end_col_offset=41, id='repr', ctx=Load()),
                                                    args=[
                                                        List(
                                                            lineno=21,
                                                            col_offset=42,
                                                            end_lineno=21,
                                                            end_col_offset=72,
                                                            elts=[
                                                                Tuple(
                                                                    lineno=21,
                                                                    col_offset=43,
                                                                    end_lineno=21,
                                                                    end_col_offset=71,
                                                                    elts=[
                                                                        Constant(lineno=21, col_offset=44, end_lineno=21, end_col_offset=50, value='name', kind=None),
                                                                        Constant(lineno=21, col_offset=52, end_lineno=21, end_col_offset=59, value='ilike', kind=None),
                                                                        Constant(lineno=21, col_offset=61, end_lineno=21, end_col_offset=70, value='SMSTest', kind=None),
                                                                    ],
                                                                    ctx=Load(),
                                                                ),
                                                            ],
                                                            ctx=Load(),
                                                        ),
                                                    ],
                                                    keywords=[],
                                                ),
                                            ),
                                            Constant(lineno=22, col_offset=30, end_lineno=22, end_col_offset=172, value='Dear {{ object.display_name }} this is a mass SMS with two links http://www.odoo.com/smstest and http://www.odoo.com/smstest/{{ object.id }}', kind=None),
                                            Constant(lineno=23, col_offset=30, end_lineno=23, end_col_offset=34, value=True, kind=None),
                                            Constant(lineno=24, col_offset=37, end_lineno=24, end_col_offset=41, value=True, kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[Name(lineno=12, col_offset=5, end_lineno=12, end_col_offset=16, id='classmethod', ctx=Load())],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=28,
                    col_offset=4,
                    end_lineno=45,
                    end_col_offset=47,
                    name='_create_mailing_sms_test_records',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=28, col_offset=41, end_lineno=28, end_col_offset=44, arg='cls', annotation=None, type_comment=None),
                            arg(lineno=28, col_offset=46, end_lineno=28, end_col_offset=51, arg='model', annotation=None, type_comment=None),
                            arg(lineno=28, col_offset=69, end_lineno=28, end_col_offset=77, arg='partners', annotation=None, type_comment=None),
                            arg(lineno=28, col_offset=84, end_lineno=28, end_col_offset=89, arg='count', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[
                            Constant(lineno=28, col_offset=52, end_lineno=28, end_col_offset=67, value='mail.test.sms', kind=None),
                            Constant(lineno=28, col_offset=78, end_lineno=28, end_col_offset=82, value=None, kind=None),
                            Constant(lineno=28, col_offset=90, end_lineno=28, end_col_offset=91, value=1, kind=None),
                        ],
                    ),
                    body=[
                        Expr(
                            lineno=29,
                            col_offset=8,
                            end_lineno=29,
                            end_col_offset=72,
                            value=Constant(lineno=29, col_offset=8, end_lineno=29, end_col_offset=72, value=' Helper to create data. Currently simple, to be improved. ', kind=None),
                        ),
                        Assign(
                            lineno=30,
                            col_offset=8,
                            end_lineno=30,
                            end_col_offset=30,
                            targets=[Name(lineno=30, col_offset=8, end_lineno=30, end_col_offset=13, id='Model', ctx=Store())],
                            value=Subscript(
                                lineno=30,
                                col_offset=16,
                                end_lineno=30,
                                end_col_offset=30,
                                value=Attribute(
                                    lineno=30,
                                    col_offset=16,
                                    end_lineno=30,
                                    end_col_offset=23,
                                    value=Name(lineno=30, col_offset=16, end_lineno=30, end_col_offset=19, id='cls', ctx=Load()),
                                    attr='env',
                                    ctx=Load(),
                                ),
                                slice=Name(lineno=30, col_offset=24, end_lineno=30, end_col_offset=29, id='model', ctx=Load()),
                                ctx=Load(),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=31,
                            col_offset=8,
                            end_lineno=31,
                            end_col_offset=70,
                            targets=[Name(lineno=31, col_offset=8, end_lineno=31, end_col_offset=19, id='phone_field', ctx=Store())],
                            value=IfExp(
                                lineno=31,
                                col_offset=22,
                                end_lineno=31,
                                end_col_offset=70,
                                test=Compare(
                                    lineno=31,
                                    col_offset=37,
                                    end_lineno=31,
                                    end_col_offset=57,
                                    left=Constant(lineno=31, col_offset=37, end_lineno=31, end_col_offset=48, value='phone_nbr', kind=None),
                                    ops=[In()],
                                    comparators=[Name(lineno=31, col_offset=52, end_lineno=31, end_col_offset=57, id='Model', ctx=Load())],
                                ),
                                body=Constant(lineno=31, col_offset=22, end_lineno=31, end_col_offset=33, value='phone_nbr', kind=None),
                                orelse=Constant(lineno=31, col_offset=63, end_lineno=31, end_col_offset=70, value='phone', kind=None),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=32,
                            col_offset=8,
                            end_lineno=32,
                            end_col_offset=81,
                            targets=[Name(lineno=32, col_offset=8, end_lineno=32, end_col_offset=21, id='partner_field', ctx=Store())],
                            value=IfExp(
                                lineno=32,
                                col_offset=24,
                                end_lineno=32,
                                end_col_offset=81,
                                test=Compare(
                                    lineno=32,
                                    col_offset=41,
                                    end_lineno=32,
                                    end_col_offset=63,
                                    left=Constant(lineno=32, col_offset=41, end_lineno=32, end_col_offset=54, value='customer_id', kind=None),
                                    ops=[In()],
                                    comparators=[Name(lineno=32, col_offset=58, end_lineno=32, end_col_offset=63, id='Model', ctx=Load())],
                                ),
                                body=Constant(lineno=32, col_offset=24, end_lineno=32, end_col_offset=37, value='customer_id', kind=None),
                                orelse=Constant(lineno=32, col_offset=69, end_lineno=32, end_col_offset=81, value='partner_id', kind=None),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=34,
                            col_offset=8,
                            end_lineno=34,
                            end_col_offset=22,
                            targets=[Name(lineno=34, col_offset=8, end_lineno=34, end_col_offset=17, id='vals_list', ctx=Store())],
                            value=List(lineno=34, col_offset=20, end_lineno=34, end_col_offset=22, elts=[], ctx=Load()),
                            type_comment=None,
                        ),
                        For(
                            lineno=35,
                            col_offset=8,
                            end_lineno=43,
                            end_col_offset=34,
                            target=Name(lineno=35, col_offset=12, end_lineno=35, end_col_offset=15, id='idx', ctx=Store()),
                            iter=Call(
                                lineno=35,
                                col_offset=19,
                                end_lineno=35,
                                end_col_offset=31,
                                func=Name(lineno=35, col_offset=19, end_lineno=35, end_col_offset=24, id='range', ctx=Load()),
                                args=[Name(lineno=35, col_offset=25, end_lineno=35, end_col_offset=30, id='count', ctx=Load())],
                                keywords=[],
                            ),
                            body=[
                                Assign(
                                    lineno=36,
                                    col_offset=12,
                                    end_lineno=39,
                                    end_col_offset=13,
                                    targets=[Name(lineno=36, col_offset=12, end_lineno=36, end_col_offset=16, id='vals', ctx=Store())],
                                    value=Dict(
                                        lineno=36,
                                        col_offset=19,
                                        end_lineno=39,
                                        end_col_offset=13,
                                        keys=[
                                            Constant(lineno=37, col_offset=16, end_lineno=37, end_col_offset=22, value='name', kind=None),
                                            Name(lineno=38, col_offset=16, end_lineno=38, end_col_offset=27, id='phone_field', ctx=Load()),
                                        ],
                                        values=[
                                            BinOp(
                                                lineno=37,
                                                col_offset=24,
                                                end_lineno=37,
                                                end_col_offset=50,
                                                left=Constant(lineno=37, col_offset=24, end_lineno=37, end_col_offset=44, value='SMSTestRecord_%02d', kind=None),
                                                op=Mod(),
                                                right=Name(lineno=37, col_offset=47, end_lineno=37, end_col_offset=50, id='idx', ctx=Load()),
                                            ),
                                            BinOp(
                                                lineno=38,
                                                col_offset=29,
                                                end_lineno=38,
                                                end_col_offset=58,
                                                left=Constant(lineno=38, col_offset=29, end_lineno=38, end_col_offset=45, value='045600%02d%02d', kind=None),
                                                op=Mod(),
                                                right=Tuple(
                                                    lineno=38,
                                                    col_offset=48,
                                                    end_lineno=38,
                                                    end_col_offset=58,
                                                    elts=[
                                                        Name(lineno=38, col_offset=49, end_lineno=38, end_col_offset=52, id='idx', ctx=Load()),
                                                        Name(lineno=38, col_offset=54, end_lineno=38, end_col_offset=57, id='idx', ctx=Load()),
                                                    ],
                                                    ctx=Load(),
                                                ),
                                            ),
                                        ],
                                    ),
                                    type_comment=None,
                                ),
                                If(
                                    lineno=40,
                                    col_offset=12,
                                    end_lineno=41,
                                    end_col_offset=67,
                                    test=Name(lineno=40, col_offset=15, end_lineno=40, end_col_offset=23, id='partners', ctx=Load()),
                                    body=[
                                        Assign(
                                            lineno=41,
                                            col_offset=16,
                                            end_lineno=41,
                                            end_col_offset=67,
                                            targets=[
                                                Subscript(
                                                    lineno=41,
                                                    col_offset=16,
                                                    end_lineno=41,
                                                    end_col_offset=35,
                                                    value=Name(lineno=41, col_offset=16, end_lineno=41, end_col_offset=20, id='vals', ctx=Load()),
                                                    slice=Name(lineno=41, col_offset=21, end_lineno=41, end_col_offset=34, id='partner_field', ctx=Load()),
                                                    ctx=Store(),
                                                ),
                                            ],
                                            value=Subscript(
                                                lineno=41,
                                                col_offset=38,
                                                end_lineno=41,
                                                end_col_offset=67,
                                                value=Name(lineno=41, col_offset=38, end_lineno=41, end_col_offset=46, id='partners', ctx=Load()),
                                                slice=BinOp(
                                                    lineno=41,
                                                    col_offset=47,
                                                    end_lineno=41,
                                                    end_col_offset=66,
                                                    left=Name(lineno=41, col_offset=47, end_lineno=41, end_col_offset=50, id='idx', ctx=Load()),
                                                    op=Mod(),
                                                    right=Call(
                                                        lineno=41,
                                                        col_offset=53,
                                                        end_lineno=41,
                                                        end_col_offset=66,
                                                        func=Name(lineno=41, col_offset=53, end_lineno=41, end_col_offset=56, id='len', ctx=Load()),
                                                        args=[Name(lineno=41, col_offset=57, end_lineno=41, end_col_offset=65, id='partners', ctx=Load())],
                                                        keywords=[],
                                                    ),
                                                ),
                                                ctx=Load(),
                                            ),
                                            type_comment=None,
                                        ),
                                    ],
                                    orelse=[],
                                ),
                                Expr(
                                    lineno=43,
                                    col_offset=12,
                                    end_lineno=43,
                                    end_col_offset=34,
                                    value=Call(
                                        lineno=43,
                                        col_offset=12,
                                        end_lineno=43,
                                        end_col_offset=34,
                                        func=Attribute(
                                            lineno=43,
                                            col_offset=12,
                                            end_lineno=43,
                                            end_col_offset=28,
                                            value=Name(lineno=43, col_offset=12, end_lineno=43, end_col_offset=21, id='vals_list', ctx=Load()),
                                            attr='append',
                                            ctx=Load(),
                                        ),
                                        args=[Name(lineno=43, col_offset=29, end_lineno=43, end_col_offset=33, id='vals', ctx=Load())],
                                        keywords=[],
                                    ),
                                ),
                            ],
                            orelse=[],
                            type_comment=None,
                        ),
                        Return(
                            lineno=45,
                            col_offset=8,
                            end_lineno=45,
                            end_col_offset=47,
                            value=Call(
                                lineno=45,
                                col_offset=15,
                                end_lineno=45,
                                end_col_offset=47,
                                func=Attribute(
                                    lineno=45,
                                    col_offset=15,
                                    end_lineno=45,
                                    end_col_offset=36,
                                    value=Subscript(
                                        lineno=45,
                                        col_offset=15,
                                        end_lineno=45,
                                        end_col_offset=29,
                                        value=Attribute(
                                            lineno=45,
                                            col_offset=15,
                                            end_lineno=45,
                                            end_col_offset=22,
                                            value=Name(lineno=45, col_offset=15, end_lineno=45, end_col_offset=18, id='cls', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Name(lineno=45, col_offset=23, end_lineno=45, end_col_offset=28, id='model', ctx=Load()),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[Name(lineno=45, col_offset=37, end_lineno=45, end_col_offset=46, id='vals_list', ctx=Load())],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[Name(lineno=27, col_offset=5, end_lineno=27, end_col_offset=16, id='classmethod', ctx=Load())],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
        ClassDef(
            lineno=48,
            col_offset=0,
            end_lineno=56,
            end_col_offset=9,
            name='TestMailFullRecipients',
            bases=[
                Attribute(
                    lineno=48,
                    col_offset=29,
                    end_lineno=48,
                    end_col_offset=50,
                    value=Name(lineno=48, col_offset=29, end_lineno=48, end_col_offset=35, id='common', ctx=Load()),
                    attr='TestRecipients',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                FunctionDef(
                    lineno=51,
                    col_offset=4,
                    end_lineno=56,
                    end_col_offset=9,
                    name='setUpClass',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=51, col_offset=19, end_lineno=51, end_col_offset=22, arg='cls', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=52,
                            col_offset=8,
                            end_lineno=52,
                            end_col_offset=55,
                            value=Call(
                                lineno=52,
                                col_offset=8,
                                end_lineno=52,
                                end_col_offset=55,
                                func=Attribute(
                                    lineno=52,
                                    col_offset=8,
                                    end_lineno=52,
                                    end_col_offset=53,
                                    value=Call(
                                        lineno=52,
                                        col_offset=8,
                                        end_lineno=52,
                                        end_col_offset=42,
                                        func=Name(lineno=52, col_offset=8, end_lineno=52, end_col_offset=13, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=52, col_offset=14, end_lineno=52, end_col_offset=36, id='TestMailFullRecipients', ctx=Load()),
                                            Name(lineno=52, col_offset=38, end_lineno=52, end_col_offset=41, id='cls', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='setUpClass',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=53,
                            col_offset=8,
                            end_lineno=56,
                            end_col_offset=9,
                            targets=[
                                Attribute(
                                    lineno=53,
                                    col_offset=8,
                                    end_lineno=53,
                                    end_col_offset=27,
                                    value=Name(lineno=53, col_offset=8, end_lineno=53, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='partner_numbers',
                                    ctx=Store(),
                                ),
                            ],
                            value=ListComp(
                                lineno=53,
                                col_offset=30,
                                end_lineno=56,
                                end_col_offset=9,
                                elt=Call(
                                    lineno=54,
                                    col_offset=12,
                                    end_lineno=54,
                                    end_col_offset=134,
                                    func=Attribute(
                                        lineno=54,
                                        col_offset=12,
                                        end_lineno=54,
                                        end_col_offset=41,
                                        value=Name(lineno=54, col_offset=12, end_lineno=54, end_col_offset=28, id='phone_validation', ctx=Load()),
                                        attr='phone_format',
                                        ctx=Load(),
                                    ),
                                    args=[
                                        Attribute(
                                            lineno=54,
                                            col_offset=42,
                                            end_lineno=54,
                                            end_col_offset=56,
                                            value=Name(lineno=54, col_offset=42, end_lineno=54, end_col_offset=49, id='partner', ctx=Load()),
                                            attr='mobile',
                                            ctx=Load(),
                                        ),
                                        Attribute(
                                            lineno=54,
                                            col_offset=58,
                                            end_lineno=54,
                                            end_col_offset=81,
                                            value=Attribute(
                                                lineno=54,
                                                col_offset=58,
                                                end_lineno=54,
                                                end_col_offset=76,
                                                value=Name(lineno=54, col_offset=58, end_lineno=54, end_col_offset=65, id='partner', ctx=Load()),
                                                attr='country_id',
                                                ctx=Load(),
                                            ),
                                            attr='code',
                                            ctx=Load(),
                                        ),
                                        Attribute(
                                            lineno=54,
                                            col_offset=83,
                                            end_lineno=54,
                                            end_col_offset=112,
                                            value=Attribute(
                                                lineno=54,
                                                col_offset=83,
                                                end_lineno=54,
                                                end_col_offset=101,
                                                value=Name(lineno=54, col_offset=83, end_lineno=54, end_col_offset=90, id='partner', ctx=Load()),
                                                attr='country_id',
                                                ctx=Load(),
                                            ),
                                            attr='phone_code',
                                            ctx=Load(),
                                        ),
                                    ],
                                    keywords=[
                                        keyword(
                                            lineno=54,
                                            col_offset=114,
                                            end_lineno=54,
                                            end_col_offset=133,
                                            arg='force_format',
                                            value=Constant(lineno=54, col_offset=127, end_lineno=54, end_col_offset=133, value='E164', kind=None),
                                        ),
                                    ],
                                ),
                                generators=[
                                    comprehension(
                                        target=Name(lineno=55, col_offset=16, end_lineno=55, end_col_offset=23, id='partner', ctx=Store()),
                                        iter=BinOp(
                                            lineno=55,
                                            col_offset=28,
                                            end_lineno=55,
                                            end_col_offset=57,
                                            left=Attribute(
                                                lineno=55,
                                                col_offset=28,
                                                end_lineno=55,
                                                end_col_offset=41,
                                                value=Name(lineno=55, col_offset=28, end_lineno=55, end_col_offset=31, id='cls', ctx=Load()),
                                                attr='partner_1',
                                                ctx=Load(),
                                            ),
                                            op=BitOr(),
                                            right=Attribute(
                                                lineno=55,
                                                col_offset=44,
                                                end_lineno=55,
                                                end_col_offset=57,
                                                value=Name(lineno=55, col_offset=44, end_lineno=55, end_col_offset=47, id='cls', ctx=Load()),
                                                attr='partner_2',
                                                ctx=Load(),
                                            ),
                                        ),
                                        ifs=[],
                                        is_async=0,
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[Name(lineno=50, col_offset=5, end_lineno=50, end_col_offset=16, id='classmethod', ctx=Load())],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
