Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=34,
            module='dateutil',
            names=[alias(name='relativedelta', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=5,
            col_offset=0,
            end_lineno=5,
            end_col_offset=36,
            module='odoo',
            names=[
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
                alias(name='api', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=8,
            col_offset=0,
            end_lineno=42,
            end_col_offset=21,
            name='LeadTest',
            bases=[
                Attribute(
                    lineno=8,
                    col_offset=15,
                    end_lineno=8,
                    end_col_offset=27,
                    value=Name(lineno=8, col_offset=15, end_lineno=8, end_col_offset=21, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=9,
                    col_offset=4,
                    end_lineno=9,
                    end_col_offset=39,
                    targets=[Name(lineno=9, col_offset=4, end_lineno=9, end_col_offset=9, id='_name', ctx=Store())],
                    value=Constant(lineno=9, col_offset=12, end_lineno=9, end_col_offset=39, value='base.automation.lead.test', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=10,
                    col_offset=4,
                    end_lineno=10,
                    end_col_offset=40,
                    targets=[Name(lineno=10, col_offset=4, end_lineno=10, end_col_offset=16, id='_description', ctx=Store())],
                    value=Constant(lineno=10, col_offset=19, end_lineno=10, end_col_offset=40, value='Automated Rule Test', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=12,
                    col_offset=4,
                    end_lineno=12,
                    end_col_offset=67,
                    targets=[Name(lineno=12, col_offset=4, end_lineno=12, end_col_offset=8, id='name', ctx=Store())],
                    value=Call(
                        lineno=12,
                        col_offset=11,
                        end_lineno=12,
                        end_col_offset=67,
                        func=Attribute(
                            lineno=12,
                            col_offset=11,
                            end_lineno=12,
                            end_col_offset=22,
                            value=Name(lineno=12, col_offset=11, end_lineno=12, end_col_offset=17, id='fields', ctx=Load()),
                            attr='Char',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=12,
                                col_offset=23,
                                end_lineno=12,
                                end_col_offset=39,
                                arg='string',
                                value=Constant(lineno=12, col_offset=30, end_lineno=12, end_col_offset=39, value='Subject', kind=None),
                            ),
                            keyword(
                                lineno=12,
                                col_offset=41,
                                end_lineno=12,
                                end_col_offset=54,
                                arg='required',
                                value=Constant(lineno=12, col_offset=50, end_lineno=12, end_col_offset=54, value=True, kind=None),
                            ),
                            keyword(
                                lineno=12,
                                col_offset=56,
                                end_lineno=12,
                                end_col_offset=66,
                                arg='index',
                                value=Constant(lineno=12, col_offset=62, end_lineno=12, end_col_offset=66, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=13,
                    col_offset=4,
                    end_lineno=13,
                    end_col_offset=64,
                    targets=[Name(lineno=13, col_offset=4, end_lineno=13, end_col_offset=11, id='user_id', ctx=Store())],
                    value=Call(
                        lineno=13,
                        col_offset=14,
                        end_lineno=13,
                        end_col_offset=64,
                        func=Attribute(
                            lineno=13,
                            col_offset=14,
                            end_lineno=13,
                            end_col_offset=29,
                            value=Name(lineno=13, col_offset=14, end_lineno=13, end_col_offset=20, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=13, col_offset=30, end_lineno=13, end_col_offset=41, value='res.users', kind=None)],
                        keywords=[
                            keyword(
                                lineno=13,
                                col_offset=43,
                                end_lineno=13,
                                end_col_offset=63,
                                arg='string',
                                value=Constant(lineno=13, col_offset=50, end_lineno=13, end_col_offset=63, value='Responsible', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=14,
                    col_offset=4,
                    end_lineno=16,
                    end_col_offset=77,
                    targets=[Name(lineno=14, col_offset=4, end_lineno=14, end_col_offset=9, id='state', ctx=Store())],
                    value=Call(
                        lineno=14,
                        col_offset=12,
                        end_lineno=16,
                        end_col_offset=77,
                        func=Attribute(
                            lineno=14,
                            col_offset=12,
                            end_lineno=14,
                            end_col_offset=28,
                            value=Name(lineno=14, col_offset=12, end_lineno=14, end_col_offset=18, id='fields', ctx=Load()),
                            attr='Selection',
                            ctx=Load(),
                        ),
                        args=[
                            List(
                                lineno=14,
                                col_offset=29,
                                end_lineno=15,
                                end_col_offset=73,
                                elts=[
                                    Tuple(
                                        lineno=14,
                                        col_offset=30,
                                        end_lineno=14,
                                        end_col_offset=46,
                                        elts=[
                                            Constant(lineno=14, col_offset=31, end_lineno=14, end_col_offset=38, value='draft', kind=None),
                                            Constant(lineno=14, col_offset=40, end_lineno=14, end_col_offset=45, value='New', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                    Tuple(
                                        lineno=14,
                                        col_offset=48,
                                        end_lineno=14,
                                        end_col_offset=71,
                                        elts=[
                                            Constant(lineno=14, col_offset=49, end_lineno=14, end_col_offset=57, value='cancel', kind=None),
                                            Constant(lineno=14, col_offset=59, end_lineno=14, end_col_offset=70, value='Cancelled', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                    Tuple(
                                        lineno=14,
                                        col_offset=73,
                                        end_lineno=14,
                                        end_col_offset=96,
                                        elts=[
                                            Constant(lineno=14, col_offset=74, end_lineno=14, end_col_offset=80, value='open', kind=None),
                                            Constant(lineno=14, col_offset=82, end_lineno=14, end_col_offset=95, value='In Progress', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                    Tuple(
                                        lineno=15,
                                        col_offset=30,
                                        end_lineno=15,
                                        end_col_offset=52,
                                        elts=[
                                            Constant(lineno=15, col_offset=31, end_lineno=15, end_col_offset=40, value='pending', kind=None),
                                            Constant(lineno=15, col_offset=42, end_lineno=15, end_col_offset=51, value='Pending', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                    Tuple(
                                        lineno=15,
                                        col_offset=54,
                                        end_lineno=15,
                                        end_col_offset=72,
                                        elts=[
                                            Constant(lineno=15, col_offset=55, end_lineno=15, end_col_offset=61, value='done', kind=None),
                                            Constant(lineno=15, col_offset=63, end_lineno=15, end_col_offset=71, value='Closed', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                ctx=Load(),
                            ),
                        ],
                        keywords=[
                            keyword(
                                lineno=16,
                                col_offset=29,
                                end_lineno=16,
                                end_col_offset=44,
                                arg='string',
                                value=Constant(lineno=16, col_offset=36, end_lineno=16, end_col_offset=44, value='Status', kind=None),
                            ),
                            keyword(
                                lineno=16,
                                col_offset=46,
                                end_lineno=16,
                                end_col_offset=59,
                                arg='readonly',
                                value=Constant(lineno=16, col_offset=55, end_lineno=16, end_col_offset=59, value=True, kind=None),
                            ),
                            keyword(
                                lineno=16,
                                col_offset=61,
                                end_lineno=16,
                                end_col_offset=76,
                                arg='default',
                                value=Constant(lineno=16, col_offset=69, end_lineno=16, end_col_offset=76, value='draft', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=17,
                    col_offset=4,
                    end_lineno=17,
                    end_col_offset=41,
                    targets=[Name(lineno=17, col_offset=4, end_lineno=17, end_col_offset=10, id='active', ctx=Store())],
                    value=Call(
                        lineno=17,
                        col_offset=13,
                        end_lineno=17,
                        end_col_offset=41,
                        func=Attribute(
                            lineno=17,
                            col_offset=13,
                            end_lineno=17,
                            end_col_offset=27,
                            value=Name(lineno=17, col_offset=13, end_lineno=17, end_col_offset=19, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=17,
                                col_offset=28,
                                end_lineno=17,
                                end_col_offset=40,
                                arg='default',
                                value=Constant(lineno=17, col_offset=36, end_lineno=17, end_col_offset=40, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=18,
                    col_offset=4,
                    end_lineno=18,
                    end_col_offset=65,
                    targets=[Name(lineno=18, col_offset=4, end_lineno=18, end_col_offset=14, id='partner_id', ctx=Store())],
                    value=Call(
                        lineno=18,
                        col_offset=17,
                        end_lineno=18,
                        end_col_offset=65,
                        func=Attribute(
                            lineno=18,
                            col_offset=17,
                            end_lineno=18,
                            end_col_offset=32,
                            value=Name(lineno=18, col_offset=17, end_lineno=18, end_col_offset=23, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=18, col_offset=33, end_lineno=18, end_col_offset=46, value='res.partner', kind=None)],
                        keywords=[
                            keyword(
                                lineno=18,
                                col_offset=48,
                                end_lineno=18,
                                end_col_offset=64,
                                arg='string',
                                value=Constant(lineno=18, col_offset=55, end_lineno=18, end_col_offset=64, value='Partner', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=19,
                    col_offset=4,
                    end_lineno=19,
                    end_col_offset=75,
                    targets=[Name(lineno=19, col_offset=4, end_lineno=19, end_col_offset=20, id='date_action_last', ctx=Store())],
                    value=Call(
                        lineno=19,
                        col_offset=23,
                        end_lineno=19,
                        end_col_offset=75,
                        func=Attribute(
                            lineno=19,
                            col_offset=23,
                            end_lineno=19,
                            end_col_offset=38,
                            value=Name(lineno=19, col_offset=23, end_lineno=19, end_col_offset=29, id='fields', ctx=Load()),
                            attr='Datetime',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=19,
                                col_offset=39,
                                end_lineno=19,
                                end_col_offset=59,
                                arg='string',
                                value=Constant(lineno=19, col_offset=46, end_lineno=19, end_col_offset=59, value='Last Action', kind=None),
                            ),
                            keyword(
                                lineno=19,
                                col_offset=61,
                                end_lineno=19,
                                end_col_offset=74,
                                arg='readonly',
                                value=Constant(lineno=19, col_offset=70, end_lineno=19, end_col_offset=74, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=20,
                    col_offset=4,
                    end_lineno=20,
                    end_col_offset=79,
                    targets=[Name(lineno=20, col_offset=4, end_lineno=20, end_col_offset=12, id='employee', ctx=Store())],
                    value=Call(
                        lineno=20,
                        col_offset=15,
                        end_lineno=20,
                        end_col_offset=79,
                        func=Attribute(
                            lineno=20,
                            col_offset=15,
                            end_lineno=20,
                            end_col_offset=29,
                            value=Name(lineno=20, col_offset=15, end_lineno=20, end_col_offset=21, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=20,
                                col_offset=30,
                                end_lineno=20,
                                end_col_offset=66,
                                arg='compute',
                                value=Constant(lineno=20, col_offset=38, end_lineno=20, end_col_offset=66, value='_compute_employee_deadline', kind=None),
                            ),
                            keyword(
                                lineno=20,
                                col_offset=68,
                                end_lineno=20,
                                end_col_offset=78,
                                arg='store',
                                value=Constant(lineno=20, col_offset=74, end_lineno=20, end_col_offset=78, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=21,
                    col_offset=4,
                    end_lineno=21,
                    end_col_offset=70,
                    targets=[Name(lineno=21, col_offset=4, end_lineno=21, end_col_offset=12, id='line_ids', ctx=Store())],
                    value=Call(
                        lineno=21,
                        col_offset=15,
                        end_lineno=21,
                        end_col_offset=70,
                        func=Attribute(
                            lineno=21,
                            col_offset=15,
                            end_lineno=21,
                            end_col_offset=30,
                            value=Name(lineno=21, col_offset=15, end_lineno=21, end_col_offset=21, id='fields', ctx=Load()),
                            attr='One2many',
                            ctx=Load(),
                        ),
                        args=[
                            Constant(lineno=21, col_offset=31, end_lineno=21, end_col_offset=58, value='base.automation.line.test', kind=None),
                            Constant(lineno=21, col_offset=60, end_lineno=21, end_col_offset=69, value='lead_id', kind=None),
                        ],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=23,
                    col_offset=4,
                    end_lineno=23,
                    end_col_offset=31,
                    targets=[Name(lineno=23, col_offset=4, end_lineno=23, end_col_offset=12, id='priority', ctx=Store())],
                    value=Call(
                        lineno=23,
                        col_offset=15,
                        end_lineno=23,
                        end_col_offset=31,
                        func=Attribute(
                            lineno=23,
                            col_offset=15,
                            end_lineno=23,
                            end_col_offset=29,
                            value=Name(lineno=23, col_offset=15, end_lineno=23, end_col_offset=21, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=24,
                    col_offset=4,
                    end_lineno=24,
                    end_col_offset=79,
                    targets=[Name(lineno=24, col_offset=4, end_lineno=24, end_col_offset=12, id='deadline', ctx=Store())],
                    value=Call(
                        lineno=24,
                        col_offset=15,
                        end_lineno=24,
                        end_col_offset=79,
                        func=Attribute(
                            lineno=24,
                            col_offset=15,
                            end_lineno=24,
                            end_col_offset=29,
                            value=Name(lineno=24, col_offset=15, end_lineno=24, end_col_offset=21, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=24,
                                col_offset=30,
                                end_lineno=24,
                                end_col_offset=66,
                                arg='compute',
                                value=Constant(lineno=24, col_offset=38, end_lineno=24, end_col_offset=66, value='_compute_employee_deadline', kind=None),
                            ),
                            keyword(
                                lineno=24,
                                col_offset=68,
                                end_lineno=24,
                                end_col_offset=78,
                                arg='store',
                                value=Constant(lineno=24, col_offset=74, end_lineno=24, end_col_offset=78, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=25,
                    col_offset=4,
                    end_lineno=25,
                    end_col_offset=74,
                    targets=[Name(lineno=25, col_offset=4, end_lineno=25, end_col_offset=24, id='is_assigned_to_admin', ctx=Store())],
                    value=Call(
                        lineno=25,
                        col_offset=27,
                        end_lineno=25,
                        end_col_offset=74,
                        func=Attribute(
                            lineno=25,
                            col_offset=27,
                            end_lineno=25,
                            end_col_offset=41,
                            value=Name(lineno=25, col_offset=27, end_lineno=25, end_col_offset=33, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=25,
                                col_offset=42,
                                end_lineno=25,
                                end_col_offset=73,
                                arg='string',
                                value=Constant(lineno=25, col_offset=49, end_lineno=25, end_col_offset=73, value='Assigned to admin user', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=28,
                    col_offset=4,
                    end_lineno=35,
                    end_col_offset=90,
                    name='_compute_employee_deadline',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=28, col_offset=35, end_lineno=28, end_col_offset=39, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        For(
                            lineno=30,
                            col_offset=8,
                            end_lineno=35,
                            end_col_offset=90,
                            target=Name(lineno=30, col_offset=12, end_lineno=30, end_col_offset=18, id='record', ctx=Store()),
                            iter=Name(lineno=30, col_offset=22, end_lineno=30, end_col_offset=26, id='self', ctx=Load()),
                            body=[
                                Assign(
                                    lineno=31,
                                    col_offset=12,
                                    end_lineno=31,
                                    end_col_offset=56,
                                    targets=[
                                        Attribute(
                                            lineno=31,
                                            col_offset=12,
                                            end_lineno=31,
                                            end_col_offset=27,
                                            value=Name(lineno=31, col_offset=12, end_lineno=31, end_col_offset=18, id='record', ctx=Load()),
                                            attr='employee',
                                            ctx=Store(),
                                        ),
                                    ],
                                    value=Attribute(
                                        lineno=31,
                                        col_offset=30,
                                        end_lineno=31,
                                        end_col_offset=56,
                                        value=Attribute(
                                            lineno=31,
                                            col_offset=30,
                                            end_lineno=31,
                                            end_col_offset=47,
                                            value=Name(lineno=31, col_offset=30, end_lineno=31, end_col_offset=36, id='record', ctx=Load()),
                                            attr='partner_id',
                                            ctx=Load(),
                                        ),
                                        attr='employee',
                                        ctx=Load(),
                                    ),
                                    type_comment=None,
                                ),
                                If(
                                    lineno=32,
                                    col_offset=12,
                                    end_lineno=35,
                                    end_col_offset=90,
                                    test=UnaryOp(
                                        lineno=32,
                                        col_offset=15,
                                        end_lineno=32,
                                        end_col_offset=34,
                                        op=Not(),
                                        operand=Attribute(
                                            lineno=32,
                                            col_offset=19,
                                            end_lineno=32,
                                            end_col_offset=34,
                                            value=Name(lineno=32, col_offset=19, end_lineno=32, end_col_offset=25, id='record', ctx=Load()),
                                            attr='priority',
                                            ctx=Load(),
                                        ),
                                    ),
                                    body=[
                                        Assign(
                                            lineno=33,
                                            col_offset=16,
                                            end_lineno=33,
                                            end_col_offset=39,
                                            targets=[
                                                Attribute(
                                                    lineno=33,
                                                    col_offset=16,
                                                    end_lineno=33,
                                                    end_col_offset=31,
                                                    value=Name(lineno=33, col_offset=16, end_lineno=33, end_col_offset=22, id='record', ctx=Load()),
                                                    attr='deadline',
                                                    ctx=Store(),
                                                ),
                                            ],
                                            value=Constant(lineno=33, col_offset=34, end_lineno=33, end_col_offset=39, value=False, kind=None),
                                            type_comment=None,
                                        ),
                                    ],
                                    orelse=[
                                        Assign(
                                            lineno=35,
                                            col_offset=16,
                                            end_lineno=35,
                                            end_col_offset=90,
                                            targets=[
                                                Attribute(
                                                    lineno=35,
                                                    col_offset=16,
                                                    end_lineno=35,
                                                    end_col_offset=31,
                                                    value=Name(lineno=35, col_offset=16, end_lineno=35, end_col_offset=22, id='record', ctx=Load()),
                                                    attr='deadline',
                                                    ctx=Store(),
                                                ),
                                            ],
                                            value=BinOp(
                                                lineno=35,
                                                col_offset=34,
                                                end_lineno=35,
                                                end_col_offset=90,
                                                left=Attribute(
                                                    lineno=35,
                                                    col_offset=34,
                                                    end_lineno=35,
                                                    end_col_offset=52,
                                                    value=Name(lineno=35, col_offset=34, end_lineno=35, end_col_offset=40, id='record', ctx=Load()),
                                                    attr='create_date',
                                                    ctx=Load(),
                                                ),
                                                op=Add(),
                                                right=Call(
                                                    lineno=35,
                                                    col_offset=55,
                                                    end_lineno=35,
                                                    end_col_offset=90,
                                                    func=Attribute(
                                                        lineno=35,
                                                        col_offset=55,
                                                        end_lineno=35,
                                                        end_col_offset=82,
                                                        value=Name(lineno=35, col_offset=55, end_lineno=35, end_col_offset=68, id='relativedelta', ctx=Load()),
                                                        attr='relativedelta',
                                                        ctx=Load(),
                                                    ),
                                                    args=[],
                                                    keywords=[
                                                        keyword(
                                                            lineno=35,
                                                            col_offset=83,
                                                            end_lineno=35,
                                                            end_col_offset=89,
                                                            arg='days',
                                                            value=Constant(lineno=35, col_offset=88, end_lineno=35, end_col_offset=89, value=3, kind=None),
                                                        ),
                                                    ],
                                                ),
                                            ),
                                            type_comment=None,
                                        ),
                                    ],
                                ),
                            ],
                            orelse=[],
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[
                        Call(
                            lineno=27,
                            col_offset=5,
                            end_lineno=27,
                            end_col_offset=51,
                            func=Attribute(
                                lineno=27,
                                col_offset=5,
                                end_lineno=27,
                                end_col_offset=16,
                                value=Name(lineno=27, col_offset=5, end_lineno=27, end_col_offset=8, id='api', ctx=Load()),
                                attr='depends',
                                ctx=Load(),
                            ),
                            args=[
                                Constant(lineno=27, col_offset=17, end_lineno=27, end_col_offset=38, value='partner_id.employee', kind=None),
                                Constant(lineno=27, col_offset=40, end_lineno=27, end_col_offset=50, value='priority', kind=None),
                            ],
                            keywords=[],
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=37,
                    col_offset=4,
                    end_lineno=42,
                    end_col_offset=21,
                    name='write',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=37, col_offset=14, end_lineno=37, end_col_offset=18, arg='self', annotation=None, type_comment=None),
                            arg(lineno=37, col_offset=20, end_lineno=37, end_col_offset=24, arg='vals', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=38,
                            col_offset=8,
                            end_lineno=38,
                            end_col_offset=36,
                            targets=[Name(lineno=38, col_offset=8, end_lineno=38, end_col_offset=14, id='result', ctx=Store())],
                            value=Call(
                                lineno=38,
                                col_offset=17,
                                end_lineno=38,
                                end_col_offset=36,
                                func=Attribute(
                                    lineno=38,
                                    col_offset=17,
                                    end_lineno=38,
                                    end_col_offset=30,
                                    value=Call(
                                        lineno=38,
                                        col_offset=17,
                                        end_lineno=38,
                                        end_col_offset=24,
                                        func=Name(lineno=38, col_offset=17, end_lineno=38, end_col_offset=22, id='super', ctx=Load()),
                                        args=[],
                                        keywords=[],
                                    ),
                                    attr='write',
                                    ctx=Load(),
                                ),
                                args=[Name(lineno=38, col_offset=31, end_lineno=38, end_col_offset=35, id='vals', ctx=Load())],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=41,
                            col_offset=8,
                            end_lineno=41,
                            end_col_offset=31,
                            value=Call(
                                lineno=41,
                                col_offset=8,
                                end_lineno=41,
                                end_col_offset=31,
                                func=Attribute(
                                    lineno=41,
                                    col_offset=8,
                                    end_lineno=41,
                                    end_col_offset=19,
                                    value=Name(lineno=41, col_offset=8, end_lineno=41, end_col_offset=12, id='self', ctx=Load()),
                                    attr='mapped',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=41, col_offset=20, end_lineno=41, end_col_offset=30, value='employee', kind=None)],
                                keywords=[],
                            ),
                        ),
                        Return(
                            lineno=42,
                            col_offset=8,
                            end_lineno=42,
                            end_col_offset=21,
                            value=Name(lineno=42, col_offset=15, end_lineno=42, end_col_offset=21, id='result', ctx=Load()),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
        ClassDef(
            lineno=45,
            col_offset=0,
            end_lineno=51,
            end_col_offset=42,
            name='LineTest',
            bases=[
                Attribute(
                    lineno=45,
                    col_offset=15,
                    end_lineno=45,
                    end_col_offset=27,
                    value=Name(lineno=45, col_offset=15, end_lineno=45, end_col_offset=21, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=46,
                    col_offset=4,
                    end_lineno=46,
                    end_col_offset=39,
                    targets=[Name(lineno=46, col_offset=4, end_lineno=46, end_col_offset=9, id='_name', ctx=Store())],
                    value=Constant(lineno=46, col_offset=12, end_lineno=46, end_col_offset=39, value='base.automation.line.test', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=47,
                    col_offset=4,
                    end_lineno=47,
                    end_col_offset=45,
                    targets=[Name(lineno=47, col_offset=4, end_lineno=47, end_col_offset=16, id='_description', ctx=Store())],
                    value=Constant(lineno=47, col_offset=19, end_lineno=47, end_col_offset=45, value='Automated Rule Line Test', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=49,
                    col_offset=4,
                    end_lineno=49,
                    end_col_offset=24,
                    targets=[Name(lineno=49, col_offset=4, end_lineno=49, end_col_offset=8, id='name', ctx=Store())],
                    value=Call(
                        lineno=49,
                        col_offset=11,
                        end_lineno=49,
                        end_col_offset=24,
                        func=Attribute(
                            lineno=49,
                            col_offset=11,
                            end_lineno=49,
                            end_col_offset=22,
                            value=Name(lineno=49, col_offset=11, end_lineno=49, end_col_offset=17, id='fields', ctx=Load()),
                            attr='Char',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=50,
                    col_offset=4,
                    end_lineno=50,
                    end_col_offset=78,
                    targets=[Name(lineno=50, col_offset=4, end_lineno=50, end_col_offset=11, id='lead_id', ctx=Store())],
                    value=Call(
                        lineno=50,
                        col_offset=14,
                        end_lineno=50,
                        end_col_offset=78,
                        func=Attribute(
                            lineno=50,
                            col_offset=14,
                            end_lineno=50,
                            end_col_offset=29,
                            value=Name(lineno=50, col_offset=14, end_lineno=50, end_col_offset=20, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=50, col_offset=30, end_lineno=50, end_col_offset=57, value='base.automation.lead.test', kind=None)],
                        keywords=[
                            keyword(
                                lineno=50,
                                col_offset=59,
                                end_lineno=50,
                                end_col_offset=77,
                                arg='ondelete',
                                value=Constant(lineno=50, col_offset=68, end_lineno=50, end_col_offset=77, value='cascade', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=51,
                    col_offset=4,
                    end_lineno=51,
                    end_col_offset=42,
                    targets=[Name(lineno=51, col_offset=4, end_lineno=51, end_col_offset=11, id='user_id', ctx=Store())],
                    value=Call(
                        lineno=51,
                        col_offset=14,
                        end_lineno=51,
                        end_col_offset=42,
                        func=Attribute(
                            lineno=51,
                            col_offset=14,
                            end_lineno=51,
                            end_col_offset=29,
                            value=Name(lineno=51, col_offset=14, end_lineno=51, end_col_offset=20, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=51, col_offset=30, end_lineno=51, end_col_offset=41, value='res.users', kind=None)],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
        ClassDef(
            lineno=54,
            col_offset=0,
            end_lineno=59,
            end_col_offset=82,
            name='ModelWithAccess',
            bases=[
                Attribute(
                    lineno=54,
                    col_offset=22,
                    end_lineno=54,
                    end_col_offset=34,
                    value=Name(lineno=54, col_offset=22, end_lineno=54, end_col_offset=28, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=55,
                    col_offset=4,
                    end_lineno=55,
                    end_col_offset=39,
                    targets=[Name(lineno=55, col_offset=4, end_lineno=55, end_col_offset=9, id='_name', ctx=Store())],
                    value=Constant(lineno=55, col_offset=12, end_lineno=55, end_col_offset=39, value='base.automation.link.test', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=56,
                    col_offset=4,
                    end_lineno=56,
                    end_col_offset=45,
                    targets=[Name(lineno=56, col_offset=4, end_lineno=56, end_col_offset=16, id='_description', ctx=Store())],
                    value=Constant(lineno=56, col_offset=19, end_lineno=56, end_col_offset=45, value='Automated Rule Link Test', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=58,
                    col_offset=4,
                    end_lineno=58,
                    end_col_offset=24,
                    targets=[Name(lineno=58, col_offset=4, end_lineno=58, end_col_offset=8, id='name', ctx=Store())],
                    value=Call(
                        lineno=58,
                        col_offset=11,
                        end_lineno=58,
                        end_col_offset=24,
                        func=Attribute(
                            lineno=58,
                            col_offset=11,
                            end_lineno=58,
                            end_col_offset=22,
                            value=Name(lineno=58, col_offset=11, end_lineno=58, end_col_offset=17, id='fields', ctx=Load()),
                            attr='Char',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=59,
                    col_offset=4,
                    end_lineno=59,
                    end_col_offset=82,
                    targets=[Name(lineno=59, col_offset=4, end_lineno=59, end_col_offset=13, id='linked_id', ctx=Store())],
                    value=Call(
                        lineno=59,
                        col_offset=16,
                        end_lineno=59,
                        end_col_offset=82,
                        func=Attribute(
                            lineno=59,
                            col_offset=16,
                            end_lineno=59,
                            end_col_offset=31,
                            value=Name(lineno=59, col_offset=16, end_lineno=59, end_col_offset=22, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=59, col_offset=32, end_lineno=59, end_col_offset=61, value='base.automation.linked.test', kind=None)],
                        keywords=[
                            keyword(
                                lineno=59,
                                col_offset=63,
                                end_lineno=59,
                                end_col_offset=81,
                                arg='ondelete',
                                value=Constant(lineno=59, col_offset=72, end_lineno=59, end_col_offset=81, value='cascade', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
        ClassDef(
            lineno=62,
            col_offset=0,
            end_lineno=67,
            end_col_offset=33,
            name='ModelWithoutAccess',
            bases=[
                Attribute(
                    lineno=62,
                    col_offset=25,
                    end_lineno=62,
                    end_col_offset=37,
                    value=Name(lineno=62, col_offset=25, end_lineno=62, end_col_offset=31, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=63,
                    col_offset=4,
                    end_lineno=63,
                    end_col_offset=41,
                    targets=[Name(lineno=63, col_offset=4, end_lineno=63, end_col_offset=9, id='_name', ctx=Store())],
                    value=Constant(lineno=63, col_offset=12, end_lineno=63, end_col_offset=41, value='base.automation.linked.test', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=64,
                    col_offset=4,
                    end_lineno=64,
                    end_col_offset=47,
                    targets=[Name(lineno=64, col_offset=4, end_lineno=64, end_col_offset=16, id='_description', ctx=Store())],
                    value=Constant(lineno=64, col_offset=19, end_lineno=64, end_col_offset=47, value='Automated Rule Linked Test', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=66,
                    col_offset=4,
                    end_lineno=66,
                    end_col_offset=24,
                    targets=[Name(lineno=66, col_offset=4, end_lineno=66, end_col_offset=8, id='name', ctx=Store())],
                    value=Call(
                        lineno=66,
                        col_offset=11,
                        end_lineno=66,
                        end_col_offset=24,
                        func=Attribute(
                            lineno=66,
                            col_offset=11,
                            end_lineno=66,
                            end_col_offset=22,
                            value=Name(lineno=66, col_offset=11, end_lineno=66, end_col_offset=17, id='fields', ctx=Load()),
                            attr='Char',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=67,
                    col_offset=4,
                    end_lineno=67,
                    end_col_offset=33,
                    targets=[Name(lineno=67, col_offset=4, end_lineno=67, end_col_offset=17, id='another_field', ctx=Store())],
                    value=Call(
                        lineno=67,
                        col_offset=20,
                        end_lineno=67,
                        end_col_offset=33,
                        func=Attribute(
                            lineno=67,
                            col_offset=20,
                            end_lineno=67,
                            end_col_offset=31,
                            value=Name(lineno=67, col_offset=20, end_lineno=67, end_col_offset=26, id='fields', ctx=Load()),
                            attr='Char',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[],
                    ),
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
