Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=46,
            module='odoo',
            names=[
                alias(name='api', asname=None),
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
                alias(name='tools', asname=None),
                alias(name='_', asname=None),
            ],
            level=0,
        ),
        Import(
            lineno=5,
            col_offset=0,
            end_lineno=5,
            end_col_offset=18,
            names=[alias(name='odoo.addons', asname=None)],
        ),
        Import(
            lineno=7,
            col_offset=0,
            end_lineno=7,
            end_col_offset=14,
            names=[alias(name='logging', asname=None)],
        ),
        Import(
            lineno=8,
            col_offset=0,
            end_lineno=8,
            end_col_offset=10,
            names=[alias(name='sys', asname=None)],
        ),
        Assign(
            lineno=9,
            col_offset=0,
            end_lineno=9,
            end_col_offset=37,
            targets=[Name(lineno=9, col_offset=0, end_lineno=9, end_col_offset=7, id='_logger', ctx=Store())],
            value=Call(
                lineno=9,
                col_offset=10,
                end_lineno=9,
                end_col_offset=37,
                func=Attribute(
                    lineno=9,
                    col_offset=10,
                    end_lineno=9,
                    end_col_offset=27,
                    value=Name(lineno=9, col_offset=10, end_lineno=9, end_col_offset=17, id='logging', ctx=Load()),
                    attr='getLogger',
                    ctx=Load(),
                ),
                args=[Name(lineno=9, col_offset=28, end_lineno=9, end_col_offset=36, id='__name__', ctx=Load())],
                keywords=[],
            ),
            type_comment=None,
        ),
        FunctionDef(
            lineno=12,
            col_offset=0,
            end_lineno=14,
            end_col_offset=22,
            name='get_precision',
            args=arguments(
                posonlyargs=[],
                args=[arg(lineno=12, col_offset=18, end_lineno=12, end_col_offset=29, arg='application', annotation=None, type_comment=None)],
                vararg=None,
                kwonlyargs=[],
                kw_defaults=[],
                kwarg=None,
                defaults=[],
            ),
            body=[
                Expr(
                    lineno=13,
                    col_offset=4,
                    end_lineno=13,
                    end_col_offset=122,
                    value=Call(
                        lineno=13,
                        col_offset=4,
                        end_lineno=13,
                        end_col_offset=122,
                        func=Attribute(
                            lineno=13,
                            col_offset=4,
                            end_lineno=13,
                            end_col_offset=19,
                            value=Name(lineno=13, col_offset=4, end_lineno=13, end_col_offset=11, id='_logger', ctx=Load()),
                            attr='warning',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=13, col_offset=20, end_lineno=13, end_col_offset=121, value='Deprecated call to decimal_precision.get_precision(<application>), use digits=<application> instead', kind=None)],
                        keywords=[],
                    ),
                ),
                Return(
                    lineno=14,
                    col_offset=4,
                    end_lineno=14,
                    end_col_offset=22,
                    value=Name(lineno=14, col_offset=11, end_lineno=14, end_col_offset=22, id='application', ctx=Load()),
                ),
            ],
            decorator_list=[],
            returns=None,
            type_comment=None,
        ),
        ClassDef(
            lineno=17,
            col_offset=0,
            end_lineno=67,
            end_col_offset=13,
            name='DecimalPrecision',
            bases=[
                Attribute(
                    lineno=17,
                    col_offset=23,
                    end_lineno=17,
                    end_col_offset=35,
                    value=Name(lineno=17, col_offset=23, end_lineno=17, end_col_offset=29, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=18,
                    col_offset=4,
                    end_lineno=18,
                    end_col_offset=31,
                    targets=[Name(lineno=18, col_offset=4, end_lineno=18, end_col_offset=9, id='_name', ctx=Store())],
                    value=Constant(lineno=18, col_offset=12, end_lineno=18, end_col_offset=31, value='decimal.precision', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=19,
                    col_offset=4,
                    end_lineno=19,
                    end_col_offset=38,
                    targets=[Name(lineno=19, col_offset=4, end_lineno=19, end_col_offset=16, id='_description', ctx=Store())],
                    value=Constant(lineno=19, col_offset=19, end_lineno=19, end_col_offset=38, value='Decimal Precision', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=21,
                    col_offset=4,
                    end_lineno=21,
                    end_col_offset=58,
                    targets=[Name(lineno=21, col_offset=4, end_lineno=21, end_col_offset=8, id='name', ctx=Store())],
                    value=Call(
                        lineno=21,
                        col_offset=11,
                        end_lineno=21,
                        end_col_offset=58,
                        func=Attribute(
                            lineno=21,
                            col_offset=11,
                            end_lineno=21,
                            end_col_offset=22,
                            value=Name(lineno=21, col_offset=11, end_lineno=21, end_col_offset=17, id='fields', ctx=Load()),
                            attr='Char',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=21, col_offset=23, end_lineno=21, end_col_offset=30, value='Usage', kind=None)],
                        keywords=[
                            keyword(
                                lineno=21,
                                col_offset=32,
                                end_lineno=21,
                                end_col_offset=42,
                                arg='index',
                                value=Constant(lineno=21, col_offset=38, end_lineno=21, end_col_offset=42, value=True, kind=None),
                            ),
                            keyword(
                                lineno=21,
                                col_offset=44,
                                end_lineno=21,
                                end_col_offset=57,
                                arg='required',
                                value=Constant(lineno=21, col_offset=53, end_lineno=21, end_col_offset=57, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=22,
                    col_offset=4,
                    end_lineno=22,
                    end_col_offset=63,
                    targets=[Name(lineno=22, col_offset=4, end_lineno=22, end_col_offset=10, id='digits', ctx=Store())],
                    value=Call(
                        lineno=22,
                        col_offset=13,
                        end_lineno=22,
                        end_col_offset=63,
                        func=Attribute(
                            lineno=22,
                            col_offset=13,
                            end_lineno=22,
                            end_col_offset=27,
                            value=Name(lineno=22, col_offset=13, end_lineno=22, end_col_offset=19, id='fields', ctx=Load()),
                            attr='Integer',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=22, col_offset=28, end_lineno=22, end_col_offset=36, value='Digits', kind=None)],
                        keywords=[
                            keyword(
                                lineno=22,
                                col_offset=38,
                                end_lineno=22,
                                end_col_offset=51,
                                arg='required',
                                value=Constant(lineno=22, col_offset=47, end_lineno=22, end_col_offset=51, value=True, kind=None),
                            ),
                            keyword(
                                lineno=22,
                                col_offset=53,
                                end_lineno=22,
                                end_col_offset=62,
                                arg='default',
                                value=Constant(lineno=22, col_offset=61, end_lineno=22, end_col_offset=62, value=2, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=24,
                    col_offset=4,
                    end_lineno=26,
                    end_col_offset=5,
                    targets=[Name(lineno=24, col_offset=4, end_lineno=24, end_col_offset=20, id='_sql_constraints', ctx=Store())],
                    value=List(
                        lineno=24,
                        col_offset=23,
                        end_lineno=26,
                        end_col_offset=5,
                        elts=[
                            Tuple(
                                lineno=25,
                                col_offset=8,
                                end_lineno=25,
                                end_col_offset=97,
                                elts=[
                                    Constant(lineno=25, col_offset=9, end_lineno=25, end_col_offset=20, value='name_uniq', kind=None),
                                    Constant(lineno=25, col_offset=22, end_lineno=25, end_col_offset=37, value='unique (name)', kind=None),
                                    Constant(lineno=25, col_offset=39, end_lineno=25, end_col_offset=96, value='Only one value can be defined for each given usage!', kind=None),
                                ],
                                ctx=Load(),
                            ),
                        ],
                        ctx=Load(),
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=30,
                    col_offset=4,
                    end_lineno=34,
                    end_col_offset=35,
                    name='precision_get',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=30, col_offset=22, end_lineno=30, end_col_offset=26, arg='self', annotation=None, type_comment=None),
                            arg(lineno=30, col_offset=28, end_lineno=30, end_col_offset=39, arg='application', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=31,
                            col_offset=8,
                            end_lineno=31,
                            end_col_offset=38,
                            value=Call(
                                lineno=31,
                                col_offset=8,
                                end_lineno=31,
                                end_col_offset=38,
                                func=Attribute(
                                    lineno=31,
                                    col_offset=8,
                                    end_lineno=31,
                                    end_col_offset=18,
                                    value=Name(lineno=31, col_offset=8, end_lineno=31, end_col_offset=12, id='self', ctx=Load()),
                                    attr='flush',
                                    ctx=Load(),
                                ),
                                args=[
                                    List(
                                        lineno=31,
                                        col_offset=19,
                                        end_lineno=31,
                                        end_col_offset=37,
                                        elts=[
                                            Constant(lineno=31, col_offset=20, end_lineno=31, end_col_offset=26, value='name', kind=None),
                                            Constant(lineno=31, col_offset=28, end_lineno=31, end_col_offset=36, value='digits', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=32,
                            col_offset=8,
                            end_lineno=32,
                            end_col_offset=97,
                            value=Call(
                                lineno=32,
                                col_offset=8,
                                end_lineno=32,
                                end_col_offset=97,
                                func=Attribute(
                                    lineno=32,
                                    col_offset=8,
                                    end_lineno=32,
                                    end_col_offset=27,
                                    value=Attribute(
                                        lineno=32,
                                        col_offset=8,
                                        end_lineno=32,
                                        end_col_offset=19,
                                        value=Attribute(
                                            lineno=32,
                                            col_offset=8,
                                            end_lineno=32,
                                            end_col_offset=16,
                                            value=Name(lineno=32, col_offset=8, end_lineno=32, end_col_offset=12, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        attr='cr',
                                        ctx=Load(),
                                    ),
                                    attr='execute',
                                    ctx=Load(),
                                ),
                                args=[
                                    Constant(lineno=32, col_offset=28, end_lineno=32, end_col_offset=80, value='select digits from decimal_precision where name=%s', kind=None),
                                    Tuple(
                                        lineno=32,
                                        col_offset=82,
                                        end_lineno=32,
                                        end_col_offset=96,
                                        elts=[Name(lineno=32, col_offset=83, end_lineno=32, end_col_offset=94, id='application', ctx=Load())],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=33,
                            col_offset=8,
                            end_lineno=33,
                            end_col_offset=36,
                            targets=[Name(lineno=33, col_offset=8, end_lineno=33, end_col_offset=11, id='res', ctx=Store())],
                            value=Call(
                                lineno=33,
                                col_offset=14,
                                end_lineno=33,
                                end_col_offset=36,
                                func=Attribute(
                                    lineno=33,
                                    col_offset=14,
                                    end_lineno=33,
                                    end_col_offset=34,
                                    value=Attribute(
                                        lineno=33,
                                        col_offset=14,
                                        end_lineno=33,
                                        end_col_offset=25,
                                        value=Attribute(
                                            lineno=33,
                                            col_offset=14,
                                            end_lineno=33,
                                            end_col_offset=22,
                                            value=Name(lineno=33, col_offset=14, end_lineno=33, end_col_offset=18, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        attr='cr',
                                        ctx=Load(),
                                    ),
                                    attr='fetchone',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Return(
                            lineno=34,
                            col_offset=8,
                            end_lineno=34,
                            end_col_offset=35,
                            value=IfExp(
                                lineno=34,
                                col_offset=15,
                                end_lineno=34,
                                end_col_offset=35,
                                test=Name(lineno=34, col_offset=25, end_lineno=34, end_col_offset=28, id='res', ctx=Load()),
                                body=Subscript(
                                    lineno=34,
                                    col_offset=15,
                                    end_lineno=34,
                                    end_col_offset=21,
                                    value=Name(lineno=34, col_offset=15, end_lineno=34, end_col_offset=18, id='res', ctx=Load()),
                                    slice=Constant(lineno=34, col_offset=19, end_lineno=34, end_col_offset=20, value=0, kind=None),
                                    ctx=Load(),
                                ),
                                orelse=Constant(lineno=34, col_offset=34, end_lineno=34, end_col_offset=35, value=2, kind=None),
                            ),
                        ),
                    ],
                    decorator_list=[
                        Attribute(
                            lineno=28,
                            col_offset=5,
                            end_lineno=28,
                            end_col_offset=14,
                            value=Name(lineno=28, col_offset=5, end_lineno=28, end_col_offset=8, id='api', ctx=Load()),
                            attr='model',
                            ctx=Load(),
                        ),
                        Call(
                            lineno=29,
                            col_offset=5,
                            end_lineno=29,
                            end_col_offset=34,
                            func=Attribute(
                                lineno=29,
                                col_offset=5,
                                end_lineno=29,
                                end_col_offset=19,
                                value=Name(lineno=29, col_offset=5, end_lineno=29, end_col_offset=10, id='tools', ctx=Load()),
                                attr='ormcache',
                                ctx=Load(),
                            ),
                            args=[Constant(lineno=29, col_offset=20, end_lineno=29, end_col_offset=33, value='application', kind=None)],
                            keywords=[],
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=37,
                    col_offset=4,
                    end_lineno=40,
                    end_col_offset=18,
                    name='create',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=37, col_offset=15, end_lineno=37, end_col_offset=19, arg='self', annotation=None, type_comment=None),
                            arg(lineno=37, col_offset=21, end_lineno=37, end_col_offset=30, arg='vals_list', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=38,
                            col_offset=8,
                            end_lineno=38,
                            end_col_offset=61,
                            targets=[Name(lineno=38, col_offset=8, end_lineno=38, end_col_offset=11, id='res', ctx=Store())],
                            value=Call(
                                lineno=38,
                                col_offset=14,
                                end_lineno=38,
                                end_col_offset=61,
                                func=Attribute(
                                    lineno=38,
                                    col_offset=14,
                                    end_lineno=38,
                                    end_col_offset=50,
                                    value=Call(
                                        lineno=38,
                                        col_offset=14,
                                        end_lineno=38,
                                        end_col_offset=43,
                                        func=Name(lineno=38, col_offset=14, end_lineno=38, end_col_offset=19, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=38, col_offset=20, end_lineno=38, end_col_offset=36, id='DecimalPrecision', ctx=Load()),
                                            Name(lineno=38, col_offset=38, end_lineno=38, end_col_offset=42, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[Name(lineno=38, col_offset=51, end_lineno=38, end_col_offset=60, id='vals_list', ctx=Load())],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=39,
                            col_offset=8,
                            end_lineno=39,
                            end_col_offset=27,
                            value=Call(
                                lineno=39,
                                col_offset=8,
                                end_lineno=39,
                                end_col_offset=27,
                                func=Attribute(
                                    lineno=39,
                                    col_offset=8,
                                    end_lineno=39,
                                    end_col_offset=25,
                                    value=Name(lineno=39, col_offset=8, end_lineno=39, end_col_offset=12, id='self', ctx=Load()),
                                    attr='clear_caches',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Return(
                            lineno=40,
                            col_offset=8,
                            end_lineno=40,
                            end_col_offset=18,
                            value=Name(lineno=40, col_offset=15, end_lineno=40, end_col_offset=18, id='res', ctx=Load()),
                        ),
                    ],
                    decorator_list=[
                        Attribute(
                            lineno=36,
                            col_offset=5,
                            end_lineno=36,
                            end_col_offset=27,
                            value=Name(lineno=36, col_offset=5, end_lineno=36, end_col_offset=8, id='api', ctx=Load()),
                            attr='model_create_multi',
                            ctx=Load(),
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=42,
                    col_offset=4,
                    end_lineno=45,
                    end_col_offset=18,
                    name='write',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=42, col_offset=14, end_lineno=42, end_col_offset=18, arg='self', annotation=None, type_comment=None),
                            arg(lineno=42, col_offset=20, end_lineno=42, end_col_offset=24, arg='data', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=43,
                            col_offset=8,
                            end_lineno=43,
                            end_col_offset=55,
                            targets=[Name(lineno=43, col_offset=8, end_lineno=43, end_col_offset=11, id='res', ctx=Store())],
                            value=Call(
                                lineno=43,
                                col_offset=14,
                                end_lineno=43,
                                end_col_offset=55,
                                func=Attribute(
                                    lineno=43,
                                    col_offset=14,
                                    end_lineno=43,
                                    end_col_offset=49,
                                    value=Call(
                                        lineno=43,
                                        col_offset=14,
                                        end_lineno=43,
                                        end_col_offset=43,
                                        func=Name(lineno=43, col_offset=14, end_lineno=43, end_col_offset=19, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=43, col_offset=20, end_lineno=43, end_col_offset=36, id='DecimalPrecision', ctx=Load()),
                                            Name(lineno=43, col_offset=38, end_lineno=43, end_col_offset=42, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='write',
                                    ctx=Load(),
                                ),
                                args=[Name(lineno=43, col_offset=50, end_lineno=43, end_col_offset=54, id='data', ctx=Load())],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=44,
                            col_offset=8,
                            end_lineno=44,
                            end_col_offset=27,
                            value=Call(
                                lineno=44,
                                col_offset=8,
                                end_lineno=44,
                                end_col_offset=27,
                                func=Attribute(
                                    lineno=44,
                                    col_offset=8,
                                    end_lineno=44,
                                    end_col_offset=25,
                                    value=Name(lineno=44, col_offset=8, end_lineno=44, end_col_offset=12, id='self', ctx=Load()),
                                    attr='clear_caches',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Return(
                            lineno=45,
                            col_offset=8,
                            end_lineno=45,
                            end_col_offset=18,
                            value=Name(lineno=45, col_offset=15, end_lineno=45, end_col_offset=18, id='res', ctx=Load()),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=47,
                    col_offset=4,
                    end_lineno=50,
                    end_col_offset=18,
                    name='unlink',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=47, col_offset=15, end_lineno=47, end_col_offset=19, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=48,
                            col_offset=8,
                            end_lineno=48,
                            end_col_offset=52,
                            targets=[Name(lineno=48, col_offset=8, end_lineno=48, end_col_offset=11, id='res', ctx=Store())],
                            value=Call(
                                lineno=48,
                                col_offset=14,
                                end_lineno=48,
                                end_col_offset=52,
                                func=Attribute(
                                    lineno=48,
                                    col_offset=14,
                                    end_lineno=48,
                                    end_col_offset=50,
                                    value=Call(
                                        lineno=48,
                                        col_offset=14,
                                        end_lineno=48,
                                        end_col_offset=43,
                                        func=Name(lineno=48, col_offset=14, end_lineno=48, end_col_offset=19, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=48, col_offset=20, end_lineno=48, end_col_offset=36, id='DecimalPrecision', ctx=Load()),
                                            Name(lineno=48, col_offset=38, end_lineno=48, end_col_offset=42, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='unlink',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=49,
                            col_offset=8,
                            end_lineno=49,
                            end_col_offset=27,
                            value=Call(
                                lineno=49,
                                col_offset=8,
                                end_lineno=49,
                                end_col_offset=27,
                                func=Attribute(
                                    lineno=49,
                                    col_offset=8,
                                    end_lineno=49,
                                    end_col_offset=25,
                                    value=Name(lineno=49, col_offset=8, end_lineno=49, end_col_offset=12, id='self', ctx=Load()),
                                    attr='clear_caches',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Return(
                            lineno=50,
                            col_offset=8,
                            end_lineno=50,
                            end_col_offset=18,
                            value=Name(lineno=50, col_offset=15, end_lineno=50, end_col_offset=18, id='res', ctx=Load()),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=53,
                    col_offset=4,
                    end_lineno=67,
                    end_col_offset=13,
                    name='_onchange_digits_warning',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=53, col_offset=33, end_lineno=53, end_col_offset=37, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        If(
                            lineno=54,
                            col_offset=8,
                            end_lineno=67,
                            end_col_offset=13,
                            test=Compare(
                                lineno=54,
                                col_offset=11,
                                end_lineno=54,
                                end_col_offset=44,
                                left=Attribute(
                                    lineno=54,
                                    col_offset=11,
                                    end_lineno=54,
                                    end_col_offset=22,
                                    value=Name(lineno=54, col_offset=11, end_lineno=54, end_col_offset=15, id='self', ctx=Load()),
                                    attr='digits',
                                    ctx=Load(),
                                ),
                                ops=[Lt()],
                                comparators=[
                                    Attribute(
                                        lineno=54,
                                        col_offset=25,
                                        end_lineno=54,
                                        end_col_offset=44,
                                        value=Attribute(
                                            lineno=54,
                                            col_offset=25,
                                            end_lineno=54,
                                            end_col_offset=37,
                                            value=Name(lineno=54, col_offset=25, end_lineno=54, end_col_offset=29, id='self', ctx=Load()),
                                            attr='_origin',
                                            ctx=Load(),
                                        ),
                                        attr='digits',
                                        ctx=Load(),
                                    ),
                                ],
                            ),
                            body=[
                                Return(
                                    lineno=55,
                                    col_offset=12,
                                    end_lineno=67,
                                    end_col_offset=13,
                                    value=Dict(
                                        lineno=55,
                                        col_offset=19,
                                        end_lineno=67,
                                        end_col_offset=13,
                                        keys=[Constant(lineno=56, col_offset=16, end_lineno=56, end_col_offset=25, value='warning', kind=None)],
                                        values=[
                                            Dict(
                                                lineno=56,
                                                col_offset=27,
                                                end_lineno=66,
                                                end_col_offset=17,
                                                keys=[
                                                    Constant(lineno=57, col_offset=20, end_lineno=57, end_col_offset=27, value='title', kind=None),
                                                    Constant(lineno=58, col_offset=20, end_lineno=58, end_col_offset=29, value='message', kind=None),
                                                ],
                                                values=[
                                                    Call(
                                                        lineno=57,
                                                        col_offset=29,
                                                        end_lineno=57,
                                                        end_col_offset=59,
                                                        func=Name(lineno=57, col_offset=29, end_lineno=57, end_col_offset=30, id='_', ctx=Load()),
                                                        args=[
                                                            Constant(lineno=57, col_offset=31, end_lineno=57, end_col_offset=47, value='Warning for %s', kind=None),
                                                            Attribute(
                                                                lineno=57,
                                                                col_offset=49,
                                                                end_lineno=57,
                                                                end_col_offset=58,
                                                                value=Name(lineno=57, col_offset=49, end_lineno=57, end_col_offset=53, id='self', ctx=Load()),
                                                                attr='name',
                                                                ctx=Load(),
                                                            ),
                                                        ],
                                                        keywords=[],
                                                    ),
                                                    Call(
                                                        lineno=58,
                                                        col_offset=31,
                                                        end_lineno=65,
                                                        end_col_offset=21,
                                                        func=Name(lineno=58, col_offset=31, end_lineno=58, end_col_offset=32, id='_', ctx=Load()),
                                                        args=[
                                                            Constant(lineno=59, col_offset=24, end_lineno=63, end_col_offset=106, value="The precision has been reduced for %s.\nNote that existing data WON'T be updated by this change.\n\nAs decimal precisions impact the whole system, this may cause critical issues.\nE.g. reducing the precision could disturb your financial balance.\n\nTherefore, changing decimal precisions in a running database is not recommended.", kind=None),
                                                            Attribute(
                                                                lineno=64,
                                                                col_offset=24,
                                                                end_lineno=64,
                                                                end_col_offset=33,
                                                                value=Name(lineno=64, col_offset=24, end_lineno=64, end_col_offset=28, id='self', ctx=Load()),
                                                                attr='name',
                                                                ctx=Load(),
                                                            ),
                                                        ],
                                                        keywords=[],
                                                    ),
                                                ],
                                            ),
                                        ],
                                    ),
                                ),
                            ],
                            orelse=[],
                        ),
                    ],
                    decorator_list=[
                        Call(
                            lineno=52,
                            col_offset=5,
                            end_lineno=52,
                            end_col_offset=27,
                            func=Attribute(
                                lineno=52,
                                col_offset=5,
                                end_lineno=52,
                                end_col_offset=17,
                                value=Name(lineno=52, col_offset=5, end_lineno=52, end_col_offset=8, id='api', ctx=Load()),
                                attr='onchange',
                                ctx=Load(),
                            ),
                            args=[Constant(lineno=52, col_offset=18, end_lineno=52, end_col_offset=26, value='digits', kind=None)],
                            keywords=[],
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
        Assign(
            lineno=70,
            col_offset=0,
            end_lineno=70,
            end_col_offset=61,
            targets=[Name(lineno=70, col_offset=0, end_lineno=70, end_col_offset=2, id='dp', ctx=Store())],
            value=Subscript(
                lineno=70,
                col_offset=5,
                end_lineno=70,
                end_col_offset=61,
                value=Attribute(
                    lineno=70,
                    col_offset=5,
                    end_lineno=70,
                    end_col_offset=16,
                    value=Name(lineno=70, col_offset=5, end_lineno=70, end_col_offset=8, id='sys', ctx=Load()),
                    attr='modules',
                    ctx=Load(),
                ),
                slice=Constant(lineno=70, col_offset=17, end_lineno=70, end_col_offset=60, value='odoo.addons.base.models.decimal_precision', kind=None),
                ctx=Load(),
            ),
            type_comment=None,
        ),
        Assign(
            lineno=71,
            col_offset=0,
            end_lineno=71,
            end_col_offset=34,
            targets=[
                Attribute(
                    lineno=71,
                    col_offset=0,
                    end_lineno=71,
                    end_col_offset=29,
                    value=Attribute(
                        lineno=71,
                        col_offset=0,
                        end_lineno=71,
                        end_col_offset=11,
                        value=Name(lineno=71, col_offset=0, end_lineno=71, end_col_offset=4, id='odoo', ctx=Load()),
                        attr='addons',
                        ctx=Load(),
                    ),
                    attr='decimal_precision',
                    ctx=Store(),
                ),
            ],
            value=Name(lineno=71, col_offset=32, end_lineno=71, end_col_offset=34, id='dp', ctx=Load()),
            type_comment=None,
        ),
        Assign(
            lineno=72,
            col_offset=0,
            end_lineno=72,
            end_col_offset=49,
            targets=[
                Subscript(
                    lineno=72,
                    col_offset=0,
                    end_lineno=72,
                    end_col_offset=44,
                    value=Attribute(
                        lineno=72,
                        col_offset=0,
                        end_lineno=72,
                        end_col_offset=11,
                        value=Name(lineno=72, col_offset=0, end_lineno=72, end_col_offset=3, id='sys', ctx=Load()),
                        attr='modules',
                        ctx=Load(),
                    ),
                    slice=Constant(lineno=72, col_offset=12, end_lineno=72, end_col_offset=43, value='odoo.addons.decimal_precision', kind=None),
                    ctx=Store(),
                ),
            ],
            value=Name(lineno=72, col_offset=47, end_lineno=72, end_col_offset=49, id='dp', ctx=Load()),
            type_comment=None,
        ),
        Assign(
            lineno=73,
            col_offset=0,
            end_lineno=73,
            end_col_offset=52,
            targets=[
                Subscript(
                    lineno=73,
                    col_offset=0,
                    end_lineno=73,
                    end_col_offset=47,
                    value=Attribute(
                        lineno=73,
                        col_offset=0,
                        end_lineno=73,
                        end_col_offset=11,
                        value=Name(lineno=73, col_offset=0, end_lineno=73, end_col_offset=3, id='sys', ctx=Load()),
                        attr='modules',
                        ctx=Load(),
                    ),
                    slice=Constant(lineno=73, col_offset=12, end_lineno=73, end_col_offset=46, value='openerp.addons.decimal_precision', kind=None),
                    ctx=Store(),
                ),
            ],
            value=Name(lineno=73, col_offset=50, end_lineno=73, end_col_offset=52, id='dp', ctx=Load()),
            type_comment=None,
        ),
    ],
    type_ignores=[],
)
