Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=111,
            module='odoo.addons.sale.tests.test_sale_product_attribute_value_config',
            names=[alias(name='TestSaleProductAttributeValueCommon', asname=None)],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=100,
            end_col_offset=10,
            name='TestSaleCouponCommon',
            bases=[Name(lineno=7, col_offset=27, end_lineno=7, end_col_offset=62, id='TestSaleProductAttributeValueCommon', ctx=Load())],
            keywords=[],
            body=[
                FunctionDef(
                    lineno=10,
                    col_offset=4,
                    end_lineno=100,
                    end_col_offset=10,
                    name='setUpClass',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=10, col_offset=19, end_lineno=10, end_col_offset=22, arg='cls', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=11,
                            col_offset=8,
                            end_lineno=11,
                            end_col_offset=53,
                            value=Call(
                                lineno=11,
                                col_offset=8,
                                end_lineno=11,
                                end_col_offset=53,
                                func=Attribute(
                                    lineno=11,
                                    col_offset=8,
                                    end_lineno=11,
                                    end_col_offset=51,
                                    value=Call(
                                        lineno=11,
                                        col_offset=8,
                                        end_lineno=11,
                                        end_col_offset=40,
                                        func=Name(lineno=11, col_offset=8, end_lineno=11, end_col_offset=13, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=11, col_offset=14, end_lineno=11, end_col_offset=34, id='TestSaleCouponCommon', ctx=Load()),
                                            Name(lineno=11, col_offset=36, end_lineno=11, end_col_offset=39, id='cls', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='setUpClass',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=14,
                            col_offset=8,
                            end_lineno=14,
                            end_col_offset=32,
                            targets=[
                                Attribute(
                                    lineno=14,
                                    col_offset=8,
                                    end_lineno=14,
                                    end_col_offset=26,
                                    value=Name(lineno=14, col_offset=8, end_lineno=14, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='currency_ratio',
                                    ctx=Store(),
                                ),
                            ],
                            value=Constant(lineno=14, col_offset=29, end_lineno=14, end_col_offset=32, value=1.0, kind=None),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=15,
                            col_offset=8,
                            end_lineno=15,
                            end_col_offset=48,
                            targets=[Name(lineno=15, col_offset=8, end_lineno=15, end_col_offset=17, id='pricelist', ctx=Store())],
                            value=Call(
                                lineno=15,
                                col_offset=20,
                                end_lineno=15,
                                end_col_offset=48,
                                func=Attribute(
                                    lineno=15,
                                    col_offset=20,
                                    end_lineno=15,
                                    end_col_offset=31,
                                    value=Attribute(
                                        lineno=15,
                                        col_offset=20,
                                        end_lineno=15,
                                        end_col_offset=27,
                                        value=Name(lineno=15, col_offset=20, end_lineno=15, end_col_offset=23, id='cls', ctx=Load()),
                                        attr='env',
                                        ctx=Load(),
                                    ),
                                    attr='ref',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=15, col_offset=32, end_lineno=15, end_col_offset=47, value='product.list0', kind=None)],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=16,
                            col_offset=8,
                            end_lineno=16,
                            end_col_offset=71,
                            targets=[
                                Attribute(
                                    lineno=16,
                                    col_offset=8,
                                    end_lineno=16,
                                    end_col_offset=29,
                                    value=Name(lineno=16, col_offset=8, end_lineno=16, end_col_offset=17, id='pricelist', ctx=Load()),
                                    attr='currency_id',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=16,
                                col_offset=32,
                                end_lineno=16,
                                end_col_offset=71,
                                func=Attribute(
                                    lineno=16,
                                    col_offset=32,
                                    end_lineno=16,
                                    end_col_offset=51,
                                    value=Name(lineno=16, col_offset=32, end_lineno=16, end_col_offset=35, id='cls', ctx=Load()),
                                    attr='_setup_currency',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=16,
                                        col_offset=52,
                                        end_lineno=16,
                                        end_col_offset=70,
                                        value=Name(lineno=16, col_offset=52, end_lineno=16, end_col_offset=55, id='cls', ctx=Load()),
                                        attr='currency_ratio',
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=19,
                            col_offset=8,
                            end_lineno=19,
                            end_col_offset=69,
                            value=Call(
                                lineno=19,
                                col_offset=8,
                                end_lineno=19,
                                end_col_offset=69,
                                func=Attribute(
                                    lineno=19,
                                    col_offset=8,
                                    end_lineno=19,
                                    end_col_offset=50,
                                    value=Call(
                                        lineno=19,
                                        col_offset=8,
                                        end_lineno=19,
                                        end_col_offset=44,
                                        func=Attribute(
                                            lineno=19,
                                            col_offset=8,
                                            end_lineno=19,
                                            end_col_offset=40,
                                            value=Subscript(
                                                lineno=19,
                                                col_offset=8,
                                                end_lineno=19,
                                                end_col_offset=33,
                                                value=Attribute(
                                                    lineno=19,
                                                    col_offset=8,
                                                    end_lineno=19,
                                                    end_col_offset=15,
                                                    value=Name(lineno=19, col_offset=8, end_lineno=19, end_col_offset=11, id='cls', ctx=Load()),
                                                    attr='env',
                                                    ctx=Load(),
                                                ),
                                                slice=Constant(lineno=19, col_offset=16, end_lineno=19, end_col_offset=32, value='coupon.program', kind=None),
                                                ctx=Load(),
                                            ),
                                            attr='search',
                                            ctx=Load(),
                                        ),
                                        args=[List(lineno=19, col_offset=41, end_lineno=19, end_col_offset=43, elts=[], ctx=Load())],
                                        keywords=[],
                                    ),
                                    attr='write',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=19,
                                        col_offset=51,
                                        end_lineno=19,
                                        end_col_offset=68,
                                        keys=[Constant(lineno=19, col_offset=52, end_lineno=19, end_col_offset=60, value='active', kind=None)],
                                        values=[Constant(lineno=19, col_offset=62, end_lineno=19, end_col_offset=67, value=False, kind=None)],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=22,
                            col_offset=8,
                            end_lineno=25,
                            end_col_offset=10,
                            targets=[
                                Attribute(
                                    lineno=22,
                                    col_offset=8,
                                    end_lineno=22,
                                    end_col_offset=17,
                                    value=Name(lineno=22, col_offset=8, end_lineno=22, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='steve',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=22,
                                col_offset=20,
                                end_lineno=25,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=22,
                                    col_offset=20,
                                    end_lineno=22,
                                    end_col_offset=49,
                                    value=Subscript(
                                        lineno=22,
                                        col_offset=20,
                                        end_lineno=22,
                                        end_col_offset=42,
                                        value=Attribute(
                                            lineno=22,
                                            col_offset=20,
                                            end_lineno=22,
                                            end_col_offset=27,
                                            value=Name(lineno=22, col_offset=20, end_lineno=22, end_col_offset=23, id='cls', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=22, col_offset=28, end_lineno=22, end_col_offset=41, value='res.partner', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=22,
                                        col_offset=50,
                                        end_lineno=25,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=23, col_offset=12, end_lineno=23, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=24, col_offset=12, end_lineno=24, end_col_offset=19, value='email', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=23, col_offset=20, end_lineno=23, end_col_offset=35, value='Steve Bucknor', kind=None),
                                            Constant(lineno=24, col_offset=21, end_lineno=24, end_col_offset=48, value='steve.bucknor@example.com', kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=27,
                            col_offset=8,
                            end_lineno=29,
                            end_col_offset=10,
                            targets=[
                                Attribute(
                                    lineno=27,
                                    col_offset=8,
                                    end_lineno=27,
                                    end_col_offset=23,
                                    value=Name(lineno=27, col_offset=8, end_lineno=27, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='empty_order',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=27,
                                col_offset=26,
                                end_lineno=29,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=27,
                                    col_offset=26,
                                    end_lineno=27,
                                    end_col_offset=54,
                                    value=Subscript(
                                        lineno=27,
                                        col_offset=26,
                                        end_lineno=27,
                                        end_col_offset=47,
                                        value=Attribute(
                                            lineno=27,
                                            col_offset=26,
                                            end_lineno=27,
                                            end_col_offset=33,
                                            value=Name(lineno=27, col_offset=26, end_lineno=27, end_col_offset=29, id='cls', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=27, col_offset=34, end_lineno=27, end_col_offset=46, value='sale.order', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=27,
                                        col_offset=55,
                                        end_lineno=29,
                                        end_col_offset=9,
                                        keys=[Constant(lineno=28, col_offset=12, end_lineno=28, end_col_offset=24, value='partner_id', kind=None)],
                                        values=[
                                            Attribute(
                                                lineno=28,
                                                col_offset=26,
                                                end_lineno=28,
                                                end_col_offset=38,
                                                value=Attribute(
                                                    lineno=28,
                                                    col_offset=26,
                                                    end_lineno=28,
                                                    end_col_offset=35,
                                                    value=Name(lineno=28, col_offset=26, end_lineno=28, end_col_offset=29, id='cls', ctx=Load()),
                                                    attr='steve',
                                                    ctx=Load(),
                                                ),
                                                attr='id',
                                                ctx=Load(),
                                            ),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=31,
                            col_offset=8,
                            end_lineno=31,
                            end_col_offset=58,
                            targets=[
                                Attribute(
                                    lineno=31,
                                    col_offset=8,
                                    end_lineno=31,
                                    end_col_offset=20,
                                    value=Name(lineno=31, col_offset=8, end_lineno=31, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='uom_unit',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=31,
                                col_offset=23,
                                end_lineno=31,
                                end_col_offset=58,
                                func=Attribute(
                                    lineno=31,
                                    col_offset=23,
                                    end_lineno=31,
                                    end_col_offset=34,
                                    value=Attribute(
                                        lineno=31,
                                        col_offset=23,
                                        end_lineno=31,
                                        end_col_offset=30,
                                        value=Name(lineno=31, col_offset=23, end_lineno=31, end_col_offset=26, id='cls', ctx=Load()),
                                        attr='env',
                                        ctx=Load(),
                                    ),
                                    attr='ref',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=31, col_offset=35, end_lineno=31, end_col_offset=57, value='uom.product_uom_unit', kind=None)],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=34,
                            col_offset=8,
                            end_lineno=39,
                            end_col_offset=10,
                            targets=[
                                Attribute(
                                    lineno=34,
                                    col_offset=8,
                                    end_lineno=34,
                                    end_col_offset=25,
                                    value=Name(lineno=34, col_offset=8, end_lineno=34, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='tax_15pc_excl',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=34,
                                col_offset=28,
                                end_lineno=39,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=34,
                                    col_offset=28,
                                    end_lineno=34,
                                    end_col_offset=57,
                                    value=Subscript(
                                        lineno=34,
                                        col_offset=28,
                                        end_lineno=34,
                                        end_col_offset=50,
                                        value=Attribute(
                                            lineno=34,
                                            col_offset=28,
                                            end_lineno=34,
                                            end_col_offset=35,
                                            value=Name(lineno=34, col_offset=28, end_lineno=34, end_col_offset=31, id='cls', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=34, col_offset=36, end_lineno=34, end_col_offset=49, value='account.tax', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=34,
                                        col_offset=58,
                                        end_lineno=39,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=35, col_offset=12, end_lineno=35, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=36, col_offset=12, end_lineno=36, end_col_offset=25, value='amount_type', kind=None),
                                            Constant(lineno=37, col_offset=12, end_lineno=37, end_col_offset=20, value='amount', kind=None),
                                            Constant(lineno=38, col_offset=12, end_lineno=38, end_col_offset=26, value='type_tax_use', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=35, col_offset=20, end_lineno=35, end_col_offset=29, value='Tax 15%', kind=None),
                                            Constant(lineno=36, col_offset=27, end_lineno=36, end_col_offset=36, value='percent', kind=None),
                                            Constant(lineno=37, col_offset=22, end_lineno=37, end_col_offset=24, value=15, kind=None),
                                            Constant(lineno=38, col_offset=28, end_lineno=38, end_col_offset=34, value='sale', kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=41,
                            col_offset=8,
                            end_lineno=46,
                            end_col_offset=10,
                            targets=[
                                Attribute(
                                    lineno=41,
                                    col_offset=8,
                                    end_lineno=41,
                                    end_col_offset=25,
                                    value=Name(lineno=41, col_offset=8, end_lineno=41, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='tax_10pc_incl',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=41,
                                col_offset=28,
                                end_lineno=46,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=41,
                                    col_offset=28,
                                    end_lineno=41,
                                    end_col_offset=57,
                                    value=Subscript(
                                        lineno=41,
                                        col_offset=28,
                                        end_lineno=41,
                                        end_col_offset=50,
                                        value=Attribute(
                                            lineno=41,
                                            col_offset=28,
                                            end_lineno=41,
                                            end_col_offset=35,
                                            value=Name(lineno=41, col_offset=28, end_lineno=41, end_col_offset=31, id='cls', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=41, col_offset=36, end_lineno=41, end_col_offset=49, value='account.tax', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=41,
                                        col_offset=58,
                                        end_lineno=46,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=42, col_offset=12, end_lineno=42, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=43, col_offset=12, end_lineno=43, end_col_offset=25, value='amount_type', kind=None),
                                            Constant(lineno=44, col_offset=12, end_lineno=44, end_col_offset=20, value='amount', kind=None),
                                            Constant(lineno=45, col_offset=12, end_lineno=45, end_col_offset=27, value='price_include', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=42, col_offset=20, end_lineno=42, end_col_offset=34, value='10% Tax incl', kind=None),
                                            Constant(lineno=43, col_offset=27, end_lineno=43, end_col_offset=36, value='percent', kind=None),
                                            Constant(lineno=44, col_offset=22, end_lineno=44, end_col_offset=24, value=10, kind=None),
                                            Constant(lineno=45, col_offset=29, end_lineno=45, end_col_offset=33, value=True, kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=49,
                            col_offset=8,
                            end_lineno=54,
                            end_col_offset=10,
                            targets=[
                                Attribute(
                                    lineno=49,
                                    col_offset=8,
                                    end_lineno=49,
                                    end_col_offset=21,
                                    value=Name(lineno=49, col_offset=8, end_lineno=49, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='product_A',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=49,
                                col_offset=24,
                                end_lineno=54,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=49,
                                    col_offset=24,
                                    end_lineno=49,
                                    end_col_offset=57,
                                    value=Subscript(
                                        lineno=49,
                                        col_offset=24,
                                        end_lineno=49,
                                        end_col_offset=50,
                                        value=Attribute(
                                            lineno=49,
                                            col_offset=24,
                                            end_lineno=49,
                                            end_col_offset=31,
                                            value=Name(lineno=49, col_offset=24, end_lineno=49, end_col_offset=27, id='cls', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=49, col_offset=32, end_lineno=49, end_col_offset=49, value='product.product', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=49,
                                        col_offset=58,
                                        end_lineno=54,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=50, col_offset=12, end_lineno=50, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=51, col_offset=12, end_lineno=51, end_col_offset=24, value='list_price', kind=None),
                                            Constant(lineno=52, col_offset=12, end_lineno=52, end_col_offset=21, value='sale_ok', kind=None),
                                            Constant(lineno=53, col_offset=12, end_lineno=53, end_col_offset=22, value='taxes_id', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=50, col_offset=20, end_lineno=50, end_col_offset=31, value='Product A', kind=None),
                                            Constant(lineno=51, col_offset=26, end_lineno=51, end_col_offset=29, value=100, kind=None),
                                            Constant(lineno=52, col_offset=23, end_lineno=52, end_col_offset=27, value=True, kind=None),
                                            List(
                                                lineno=53,
                                                col_offset=24,
                                                end_lineno=53,
                                                end_col_offset=56,
                                                elts=[
                                                    Tuple(
                                                        lineno=53,
                                                        col_offset=25,
                                                        end_lineno=53,
                                                        end_col_offset=55,
                                                        elts=[
                                                            Constant(lineno=53, col_offset=26, end_lineno=53, end_col_offset=27, value=6, kind=None),
                                                            Constant(lineno=53, col_offset=29, end_lineno=53, end_col_offset=30, value=0, kind=None),
                                                            List(
                                                                lineno=53,
                                                                col_offset=32,
                                                                end_lineno=53,
                                                                end_col_offset=54,
                                                                elts=[
                                                                    Attribute(
                                                                        lineno=53,
                                                                        col_offset=33,
                                                                        end_lineno=53,
                                                                        end_col_offset=53,
                                                                        value=Attribute(
                                                                            lineno=53,
                                                                            col_offset=33,
                                                                            end_lineno=53,
                                                                            end_col_offset=50,
                                                                            value=Name(lineno=53, col_offset=33, end_lineno=53, end_col_offset=36, id='cls', ctx=Load()),
                                                                            attr='tax_15pc_excl',
                                                                            ctx=Load(),
                                                                        ),
                                                                        attr='id',
                                                                        ctx=Load(),
                                                                    ),
                                                                ],
                                                                ctx=Load(),
                                                            ),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=56,
                            col_offset=8,
                            end_lineno=61,
                            end_col_offset=10,
                            targets=[
                                Attribute(
                                    lineno=56,
                                    col_offset=8,
                                    end_lineno=56,
                                    end_col_offset=21,
                                    value=Name(lineno=56, col_offset=8, end_lineno=56, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='product_B',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=56,
                                col_offset=24,
                                end_lineno=61,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=56,
                                    col_offset=24,
                                    end_lineno=56,
                                    end_col_offset=57,
                                    value=Subscript(
                                        lineno=56,
                                        col_offset=24,
                                        end_lineno=56,
                                        end_col_offset=50,
                                        value=Attribute(
                                            lineno=56,
                                            col_offset=24,
                                            end_lineno=56,
                                            end_col_offset=31,
                                            value=Name(lineno=56, col_offset=24, end_lineno=56, end_col_offset=27, id='cls', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=56, col_offset=32, end_lineno=56, end_col_offset=49, value='product.product', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=56,
                                        col_offset=58,
                                        end_lineno=61,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=57, col_offset=12, end_lineno=57, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=58, col_offset=12, end_lineno=58, end_col_offset=24, value='list_price', kind=None),
                                            Constant(lineno=59, col_offset=12, end_lineno=59, end_col_offset=21, value='sale_ok', kind=None),
                                            Constant(lineno=60, col_offset=12, end_lineno=60, end_col_offset=22, value='taxes_id', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=57, col_offset=20, end_lineno=57, end_col_offset=31, value='Product B', kind=None),
                                            Constant(lineno=58, col_offset=26, end_lineno=58, end_col_offset=27, value=5, kind=None),
                                            Constant(lineno=59, col_offset=23, end_lineno=59, end_col_offset=27, value=True, kind=None),
                                            List(
                                                lineno=60,
                                                col_offset=24,
                                                end_lineno=60,
                                                end_col_offset=56,
                                                elts=[
                                                    Tuple(
                                                        lineno=60,
                                                        col_offset=25,
                                                        end_lineno=60,
                                                        end_col_offset=55,
                                                        elts=[
                                                            Constant(lineno=60, col_offset=26, end_lineno=60, end_col_offset=27, value=6, kind=None),
                                                            Constant(lineno=60, col_offset=29, end_lineno=60, end_col_offset=30, value=0, kind=None),
                                                            List(
                                                                lineno=60,
                                                                col_offset=32,
                                                                end_lineno=60,
                                                                end_col_offset=54,
                                                                elts=[
                                                                    Attribute(
                                                                        lineno=60,
                                                                        col_offset=33,
                                                                        end_lineno=60,
                                                                        end_col_offset=53,
                                                                        value=Attribute(
                                                                            lineno=60,
                                                                            col_offset=33,
                                                                            end_lineno=60,
                                                                            end_col_offset=50,
                                                                            value=Name(lineno=60, col_offset=33, end_lineno=60, end_col_offset=36, id='cls', ctx=Load()),
                                                                            attr='tax_15pc_excl',
                                                                            ctx=Load(),
                                                                        ),
                                                                        attr='id',
                                                                        ctx=Load(),
                                                                    ),
                                                                ],
                                                                ctx=Load(),
                                                            ),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=63,
                            col_offset=8,
                            end_lineno=69,
                            end_col_offset=10,
                            targets=[
                                Attribute(
                                    lineno=63,
                                    col_offset=8,
                                    end_lineno=63,
                                    end_col_offset=21,
                                    value=Name(lineno=63, col_offset=8, end_lineno=63, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='product_C',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=63,
                                col_offset=24,
                                end_lineno=69,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=63,
                                    col_offset=24,
                                    end_lineno=63,
                                    end_col_offset=57,
                                    value=Subscript(
                                        lineno=63,
                                        col_offset=24,
                                        end_lineno=63,
                                        end_col_offset=50,
                                        value=Attribute(
                                            lineno=63,
                                            col_offset=24,
                                            end_lineno=63,
                                            end_col_offset=31,
                                            value=Name(lineno=63, col_offset=24, end_lineno=63, end_col_offset=27, id='cls', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=63, col_offset=32, end_lineno=63, end_col_offset=49, value='product.product', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=63,
                                        col_offset=58,
                                        end_lineno=69,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=64, col_offset=12, end_lineno=64, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=65, col_offset=12, end_lineno=65, end_col_offset=24, value='list_price', kind=None),
                                            Constant(lineno=66, col_offset=12, end_lineno=66, end_col_offset=21, value='sale_ok', kind=None),
                                            Constant(lineno=67, col_offset=12, end_lineno=67, end_col_offset=22, value='taxes_id', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=64, col_offset=20, end_lineno=64, end_col_offset=31, value='Product C', kind=None),
                                            Constant(lineno=65, col_offset=26, end_lineno=65, end_col_offset=29, value=100, kind=None),
                                            Constant(lineno=66, col_offset=23, end_lineno=66, end_col_offset=27, value=True, kind=None),
                                            List(
                                                lineno=67,
                                                col_offset=24,
                                                end_lineno=67,
                                                end_col_offset=36,
                                                elts=[
                                                    Tuple(
                                                        lineno=67,
                                                        col_offset=25,
                                                        end_lineno=67,
                                                        end_col_offset=35,
                                                        elts=[
                                                            Constant(lineno=67, col_offset=26, end_lineno=67, end_col_offset=27, value=6, kind=None),
                                                            Constant(lineno=67, col_offset=29, end_lineno=67, end_col_offset=30, value=0, kind=None),
                                                            List(lineno=67, col_offset=32, end_lineno=67, end_col_offset=34, elts=[], ctx=Load()),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=73,
                            col_offset=8,
                            end_lineno=80,
                            end_col_offset=10,
                            targets=[
                                Attribute(
                                    lineno=73,
                                    col_offset=8,
                                    end_lineno=73,
                                    end_col_offset=39,
                                    value=Name(lineno=73, col_offset=8, end_lineno=73, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='immediate_promotion_program',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=73,
                                col_offset=42,
                                end_lineno=80,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=73,
                                    col_offset=42,
                                    end_lineno=73,
                                    end_col_offset=74,
                                    value=Subscript(
                                        lineno=73,
                                        col_offset=42,
                                        end_lineno=73,
                                        end_col_offset=67,
                                        value=Attribute(
                                            lineno=73,
                                            col_offset=42,
                                            end_lineno=73,
                                            end_col_offset=49,
                                            value=Name(lineno=73, col_offset=42, end_lineno=73, end_col_offset=45, id='cls', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=73, col_offset=50, end_lineno=73, end_col_offset=66, value='coupon.program', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=73,
                                        col_offset=75,
                                        end_lineno=80,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=74, col_offset=12, end_lineno=74, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=75, col_offset=12, end_lineno=75, end_col_offset=30, value='promo_code_usage', kind=None),
                                            Constant(lineno=76, col_offset=12, end_lineno=76, end_col_offset=25, value='reward_type', kind=None),
                                            Constant(lineno=77, col_offset=12, end_lineno=77, end_col_offset=31, value='reward_product_id', kind=None),
                                            Constant(lineno=78, col_offset=12, end_lineno=78, end_col_offset=34, value='rule_products_domain', kind=None),
                                            Constant(lineno=79, col_offset=12, end_lineno=79, end_col_offset=20, value='active', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=74, col_offset=20, end_lineno=74, end_col_offset=47, value='Buy A + 1 B, 1 B are free', kind=None),
                                            Constant(lineno=75, col_offset=32, end_lineno=75, end_col_offset=48, value='no_code_needed', kind=None),
                                            Constant(lineno=76, col_offset=27, end_lineno=76, end_col_offset=36, value='product', kind=None),
                                            Attribute(
                                                lineno=77,
                                                col_offset=33,
                                                end_lineno=77,
                                                end_col_offset=49,
                                                value=Attribute(
                                                    lineno=77,
                                                    col_offset=33,
                                                    end_lineno=77,
                                                    end_col_offset=46,
                                                    value=Name(lineno=77, col_offset=33, end_lineno=77, end_col_offset=36, id='cls', ctx=Load()),
                                                    attr='product_B',
                                                    ctx=Load(),
                                                ),
                                                attr='id',
                                                ctx=Load(),
                                            ),
                                            BinOp(
                                                lineno=78,
                                                col_offset=36,
                                                end_lineno=78,
                                                end_col_offset=79,
                                                left=Constant(lineno=78, col_offset=36, end_lineno=78, end_col_offset=58, value="[('id', 'in', [%s])]", kind=None),
                                                op=Mod(),
                                                right=Attribute(
                                                    lineno=78,
                                                    col_offset=62,
                                                    end_lineno=78,
                                                    end_col_offset=78,
                                                    value=Attribute(
                                                        lineno=78,
                                                        col_offset=62,
                                                        end_lineno=78,
                                                        end_col_offset=75,
                                                        value=Name(lineno=78, col_offset=62, end_lineno=78, end_col_offset=65, id='cls', ctx=Load()),
                                                        attr='product_A',
                                                        ctx=Load(),
                                                    ),
                                                    attr='id',
                                                    ctx=Load(),
                                                ),
                                            ),
                                            Constant(lineno=79, col_offset=22, end_lineno=79, end_col_offset=26, value=True, kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=82,
                            col_offset=8,
                            end_lineno=89,
                            end_col_offset=10,
                            targets=[
                                Attribute(
                                    lineno=82,
                                    col_offset=8,
                                    end_lineno=82,
                                    end_col_offset=34,
                                    value=Name(lineno=82, col_offset=8, end_lineno=82, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='code_promotion_program',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=82,
                                col_offset=37,
                                end_lineno=89,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=82,
                                    col_offset=37,
                                    end_lineno=82,
                                    end_col_offset=69,
                                    value=Subscript(
                                        lineno=82,
                                        col_offset=37,
                                        end_lineno=82,
                                        end_col_offset=62,
                                        value=Attribute(
                                            lineno=82,
                                            col_offset=37,
                                            end_lineno=82,
                                            end_col_offset=44,
                                            value=Name(lineno=82, col_offset=37, end_lineno=82, end_col_offset=40, id='cls', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=82, col_offset=45, end_lineno=82, end_col_offset=61, value='coupon.program', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=82,
                                        col_offset=70,
                                        end_lineno=89,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=83, col_offset=12, end_lineno=83, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=84, col_offset=12, end_lineno=84, end_col_offset=30, value='promo_code_usage', kind=None),
                                            Constant(lineno=85, col_offset=12, end_lineno=85, end_col_offset=25, value='reward_type', kind=None),
                                            Constant(lineno=86, col_offset=12, end_lineno=86, end_col_offset=31, value='reward_product_id', kind=None),
                                            Constant(lineno=87, col_offset=12, end_lineno=87, end_col_offset=34, value='rule_products_domain', kind=None),
                                            Constant(lineno=88, col_offset=12, end_lineno=88, end_col_offset=20, value='active', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=83, col_offset=20, end_lineno=83, end_col_offset=55, value='Buy 1 A + Enter code, 1 A is free', kind=None),
                                            Constant(lineno=84, col_offset=32, end_lineno=84, end_col_offset=45, value='code_needed', kind=None),
                                            Constant(lineno=85, col_offset=27, end_lineno=85, end_col_offset=36, value='product', kind=None),
                                            Attribute(
                                                lineno=86,
                                                col_offset=33,
                                                end_lineno=86,
                                                end_col_offset=49,
                                                value=Attribute(
                                                    lineno=86,
                                                    col_offset=33,
                                                    end_lineno=86,
                                                    end_col_offset=46,
                                                    value=Name(lineno=86, col_offset=33, end_lineno=86, end_col_offset=36, id='cls', ctx=Load()),
                                                    attr='product_A',
                                                    ctx=Load(),
                                                ),
                                                attr='id',
                                                ctx=Load(),
                                            ),
                                            BinOp(
                                                lineno=87,
                                                col_offset=36,
                                                end_lineno=87,
                                                end_col_offset=79,
                                                left=Constant(lineno=87, col_offset=36, end_lineno=87, end_col_offset=58, value="[('id', 'in', [%s])]", kind=None),
                                                op=Mod(),
                                                right=Attribute(
                                                    lineno=87,
                                                    col_offset=62,
                                                    end_lineno=87,
                                                    end_col_offset=78,
                                                    value=Attribute(
                                                        lineno=87,
                                                        col_offset=62,
                                                        end_lineno=87,
                                                        end_col_offset=75,
                                                        value=Name(lineno=87, col_offset=62, end_lineno=87, end_col_offset=65, id='cls', ctx=Load()),
                                                        attr='product_A',
                                                        ctx=Load(),
                                                    ),
                                                    attr='id',
                                                    ctx=Load(),
                                                ),
                                            ),
                                            Constant(lineno=88, col_offset=22, end_lineno=88, end_col_offset=26, value=True, kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=91,
                            col_offset=8,
                            end_lineno=100,
                            end_col_offset=10,
                            targets=[
                                Attribute(
                                    lineno=91,
                                    col_offset=8,
                                    end_lineno=91,
                                    end_col_offset=48,
                                    value=Name(lineno=91, col_offset=8, end_lineno=91, end_col_offset=11, id='cls', ctx=Load()),
                                    attr='code_promotion_program_with_discount',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=91,
                                col_offset=51,
                                end_lineno=100,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=91,
                                    col_offset=51,
                                    end_lineno=91,
                                    end_col_offset=83,
                                    value=Subscript(
                                        lineno=91,
                                        col_offset=51,
                                        end_lineno=91,
                                        end_col_offset=76,
                                        value=Attribute(
                                            lineno=91,
                                            col_offset=51,
                                            end_lineno=91,
                                            end_col_offset=58,
                                            value=Name(lineno=91, col_offset=51, end_lineno=91, end_col_offset=54, id='cls', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=91, col_offset=59, end_lineno=91, end_col_offset=75, value='coupon.program', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=91,
                                        col_offset=84,
                                        end_lineno=100,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=92, col_offset=12, end_lineno=92, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=93, col_offset=12, end_lineno=93, end_col_offset=30, value='promo_code_usage', kind=None),
                                            Constant(lineno=94, col_offset=12, end_lineno=94, end_col_offset=25, value='reward_type', kind=None),
                                            Constant(lineno=95, col_offset=12, end_lineno=95, end_col_offset=27, value='discount_type', kind=None),
                                            Constant(lineno=96, col_offset=12, end_lineno=96, end_col_offset=33, value='discount_percentage', kind=None),
                                            Constant(lineno=97, col_offset=12, end_lineno=97, end_col_offset=34, value='rule_products_domain', kind=None),
                                            Constant(lineno=98, col_offset=12, end_lineno=98, end_col_offset=20, value='active', kind=None),
                                            Constant(lineno=99, col_offset=12, end_lineno=99, end_col_offset=31, value='discount_apply_on', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=92, col_offset=20, end_lineno=92, end_col_offset=68, value='Buy 1 C + Enter code, 10 percent discount on C', kind=None),
                                            Constant(lineno=93, col_offset=32, end_lineno=93, end_col_offset=45, value='code_needed', kind=None),
                                            Constant(lineno=94, col_offset=27, end_lineno=94, end_col_offset=37, value='discount', kind=None),
                                            Constant(lineno=95, col_offset=29, end_lineno=95, end_col_offset=41, value='percentage', kind=None),
                                            Constant(lineno=96, col_offset=35, end_lineno=96, end_col_offset=37, value=10, kind=None),
                                            BinOp(
                                                lineno=97,
                                                col_offset=36,
                                                end_lineno=97,
                                                end_col_offset=79,
                                                left=Constant(lineno=97, col_offset=36, end_lineno=97, end_col_offset=58, value="[('id', 'in', [%s])]", kind=None),
                                                op=Mod(),
                                                right=Attribute(
                                                    lineno=97,
                                                    col_offset=62,
                                                    end_lineno=97,
                                                    end_col_offset=78,
                                                    value=Attribute(
                                                        lineno=97,
                                                        col_offset=62,
                                                        end_lineno=97,
                                                        end_col_offset=75,
                                                        value=Name(lineno=97, col_offset=62, end_lineno=97, end_col_offset=65, id='cls', ctx=Load()),
                                                        attr='product_C',
                                                        ctx=Load(),
                                                    ),
                                                    attr='id',
                                                    ctx=Load(),
                                                ),
                                            ),
                                            Constant(lineno=98, col_offset=22, end_lineno=98, end_col_offset=26, value=True, kind=None),
                                            Constant(lineno=99, col_offset=33, end_lineno=99, end_col_offset=43, value='on_order', kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[Name(lineno=9, col_offset=5, end_lineno=9, end_col_offset=16, id='classmethod', ctx=Load())],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
