Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=36,
            module='odoo',
            names=[
                alias(name='api', asname=None),
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=17,
            end_col_offset=59,
            name='EventType',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=16,
                    end_lineno=7,
                    end_col_offset=28,
                    value=Name(lineno=7, col_offset=16, end_lineno=7, end_col_offset=22, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=27,
                    targets=[Name(lineno=8, col_offset=4, end_lineno=8, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=8, col_offset=15, end_lineno=8, end_col_offset=27, value='event.type', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=10,
                    col_offset=4,
                    end_lineno=12,
                    end_col_offset=35,
                    targets=[Name(lineno=10, col_offset=4, end_lineno=10, end_col_offset=14, id='booth_menu', ctx=Store())],
                    value=Call(
                        lineno=10,
                        col_offset=17,
                        end_lineno=12,
                        end_col_offset=35,
                        func=Attribute(
                            lineno=10,
                            col_offset=17,
                            end_lineno=10,
                            end_col_offset=31,
                            value=Name(lineno=10, col_offset=17, end_lineno=10, end_col_offset=23, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=11,
                                col_offset=8,
                                end_lineno=11,
                                end_col_offset=34,
                                arg='string',
                                value=Constant(lineno=11, col_offset=15, end_lineno=11, end_col_offset=34, value='Booths on Website', kind=None),
                            ),
                            keyword(
                                lineno=11,
                                col_offset=36,
                                end_lineno=11,
                                end_col_offset=65,
                                arg='compute',
                                value=Constant(lineno=11, col_offset=44, end_lineno=11, end_col_offset=65, value='_compute_booth_menu', kind=None),
                            ),
                            keyword(
                                lineno=12,
                                col_offset=8,
                                end_lineno=12,
                                end_col_offset=22,
                                arg='readonly',
                                value=Constant(lineno=12, col_offset=17, end_lineno=12, end_col_offset=22, value=False, kind=None),
                            ),
                            keyword(
                                lineno=12,
                                col_offset=24,
                                end_lineno=12,
                                end_col_offset=34,
                                arg='store',
                                value=Constant(lineno=12, col_offset=30, end_lineno=12, end_col_offset=34, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=15,
                    col_offset=4,
                    end_lineno=17,
                    end_col_offset=59,
                    name='_compute_booth_menu',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=15, col_offset=28, end_lineno=15, end_col_offset=32, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        For(
                            lineno=16,
                            col_offset=8,
                            end_lineno=17,
                            end_col_offset=59,
                            target=Name(lineno=16, col_offset=12, end_lineno=16, end_col_offset=22, id='event_type', ctx=Store()),
                            iter=Name(lineno=16, col_offset=26, end_lineno=16, end_col_offset=30, id='self', ctx=Load()),
                            body=[
                                Assign(
                                    lineno=17,
                                    col_offset=12,
                                    end_lineno=17,
                                    end_col_offset=59,
                                    targets=[
                                        Attribute(
                                            lineno=17,
                                            col_offset=12,
                                            end_lineno=17,
                                            end_col_offset=33,
                                            value=Name(lineno=17, col_offset=12, end_lineno=17, end_col_offset=22, id='event_type', ctx=Load()),
                                            attr='booth_menu',
                                            ctx=Store(),
                                        ),
                                    ],
                                    value=Attribute(
                                        lineno=17,
                                        col_offset=36,
                                        end_lineno=17,
                                        end_col_offset=59,
                                        value=Name(lineno=17, col_offset=36, end_lineno=17, end_col_offset=46, id='event_type', ctx=Load()),
                                        attr='website_menu',
                                        ctx=Load(),
                                    ),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[],
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[
                        Call(
                            lineno=14,
                            col_offset=5,
                            end_lineno=14,
                            end_col_offset=32,
                            func=Attribute(
                                lineno=14,
                                col_offset=5,
                                end_lineno=14,
                                end_col_offset=16,
                                value=Name(lineno=14, col_offset=5, end_lineno=14, end_col_offset=8, id='api', ctx=Load()),
                                attr='depends',
                                ctx=Load(),
                            ),
                            args=[Constant(lineno=14, col_offset=17, end_lineno=14, end_col_offset=31, value='website_menu', kind=None)],
                            keywords=[],
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
