Module(
    body=[
        ImportFrom(
            lineno=3,
            col_offset=0,
            end_lineno=3,
            end_col_offset=31,
            module='odoo',
            names=[
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=6,
            col_offset=0,
            end_lineno=16,
            end_col_offset=47,
            name='ProductTemplate',
            bases=[
                Attribute(
                    lineno=6,
                    col_offset=22,
                    end_lineno=6,
                    end_col_offset=34,
                    value=Name(lineno=6, col_offset=22, end_lineno=6, end_col_offset=28, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Expr(
                    lineno=7,
                    col_offset=4,
                    end_lineno=10,
                    end_col_offset=44,
                    value=Constant(lineno=7, col_offset=4, end_lineno=10, end_col_offset=44, value=' Product Template inheritance to add an optional email.template to a\n    product.template. When validating an invoice, an email will be send to the\n    customer based on this template. The customer will receive an email for each\n    product linked to an email template. ', kind=None),
                ),
                Assign(
                    lineno=11,
                    col_offset=4,
                    end_lineno=11,
                    end_col_offset=33,
                    targets=[Name(lineno=11, col_offset=4, end_lineno=11, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=11, col_offset=15, end_lineno=11, end_col_offset=33, value='product.template', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=13,
                    col_offset=4,
                    end_lineno=16,
                    end_col_offset=47,
                    targets=[Name(lineno=13, col_offset=4, end_lineno=13, end_col_offset=21, id='email_template_id', ctx=Store())],
                    value=Call(
                        lineno=13,
                        col_offset=24,
                        end_lineno=16,
                        end_col_offset=47,
                        func=Attribute(
                            lineno=13,
                            col_offset=24,
                            end_lineno=13,
                            end_col_offset=39,
                            value=Name(lineno=13, col_offset=24, end_lineno=13, end_col_offset=30, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=13, col_offset=40, end_lineno=13, end_col_offset=55, value='mail.template', kind=None)],
                        keywords=[
                            keyword(
                                lineno=13,
                                col_offset=57,
                                end_lineno=13,
                                end_col_offset=88,
                                arg='string',
                                value=Constant(lineno=13, col_offset=64, end_lineno=13, end_col_offset=88, value='Product Email Template', kind=None),
                            ),
                            keyword(
                                lineno=14,
                                col_offset=8,
                                end_lineno=16,
                                end_col_offset=46,
                                arg='help',
                                value=Constant(lineno=14, col_offset=13, end_lineno=16, end_col_offset=46, value='When validating an invoice, an email will be sent to the customer based on this template. The customer will receive an email for each product linked to an email template.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
