Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=46,
            module='odoo',
            names=[
                alias(name='api', asname=None),
                alias(name='models', asname=None),
                alias(name='fields', asname=None),
                alias(name='tools', asname=None),
                alias(name='_', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=10,
            end_col_offset=71,
            name='MailActivityType',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=23,
                    end_lineno=7,
                    end_col_offset=35,
                    value=Name(lineno=7, col_offset=23, end_lineno=7, end_col_offset=29, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=35,
                    targets=[Name(lineno=8, col_offset=4, end_lineno=8, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=8, col_offset=15, end_lineno=8, end_col_offset=35, value='mail.activity.type', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=10,
                    col_offset=4,
                    end_lineno=10,
                    end_col_offset=71,
                    targets=[Name(lineno=10, col_offset=4, end_lineno=10, end_col_offset=12, id='category', ctx=Store())],
                    value=Call(
                        lineno=10,
                        col_offset=15,
                        end_lineno=10,
                        end_col_offset=71,
                        func=Attribute(
                            lineno=10,
                            col_offset=15,
                            end_lineno=10,
                            end_col_offset=31,
                            value=Name(lineno=10, col_offset=15, end_lineno=10, end_col_offset=21, id='fields', ctx=Load()),
                            attr='Selection',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=10,
                                col_offset=32,
                                end_lineno=10,
                                end_col_offset=70,
                                arg='selection_add',
                                value=List(
                                    lineno=10,
                                    col_offset=46,
                                    end_lineno=10,
                                    end_col_offset=70,
                                    elts=[
                                        Tuple(
                                            lineno=10,
                                            col_offset=47,
                                            end_lineno=10,
                                            end_col_offset=69,
                                            elts=[
                                                Constant(lineno=10, col_offset=48, end_lineno=10, end_col_offset=57, value='meeting', kind=None),
                                                Constant(lineno=10, col_offset=59, end_lineno=10, end_col_offset=68, value='Meeting', kind=None),
                                            ],
                                            ctx=Load(),
                                        ),
                                    ],
                                    ctx=Load(),
                                ),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
        ClassDef(
            lineno=13,
            col_offset=0,
            end_lineno=48,
            end_col_offset=18,
            name='MailActivity',
            bases=[
                Attribute(
                    lineno=13,
                    col_offset=19,
                    end_lineno=13,
                    end_col_offset=31,
                    value=Name(lineno=13, col_offset=19, end_lineno=13, end_col_offset=25, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=14,
                    col_offset=4,
                    end_lineno=14,
                    end_col_offset=30,
                    targets=[Name(lineno=14, col_offset=4, end_lineno=14, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=14, col_offset=15, end_lineno=14, end_col_offset=30, value='mail.activity', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=16,
                    col_offset=4,
                    end_lineno=16,
                    end_col_offset=104,
                    targets=[Name(lineno=16, col_offset=4, end_lineno=16, end_col_offset=21, id='calendar_event_id', ctx=Store())],
                    value=Call(
                        lineno=16,
                        col_offset=24,
                        end_lineno=16,
                        end_col_offset=104,
                        func=Attribute(
                            lineno=16,
                            col_offset=24,
                            end_lineno=16,
                            end_col_offset=39,
                            value=Name(lineno=16, col_offset=24, end_lineno=16, end_col_offset=30, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=16, col_offset=40, end_lineno=16, end_col_offset=56, value='calendar.event', kind=None)],
                        keywords=[
                            keyword(
                                lineno=16,
                                col_offset=58,
                                end_lineno=16,
                                end_col_offset=83,
                                arg='string',
                                value=Constant(lineno=16, col_offset=65, end_lineno=16, end_col_offset=83, value='Calendar Meeting', kind=None),
                            ),
                            keyword(
                                lineno=16,
                                col_offset=85,
                                end_lineno=16,
                                end_col_offset=103,
                                arg='ondelete',
                                value=Constant(lineno=16, col_offset=94, end_lineno=16, end_col_offset=103, value='cascade', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=18,
                    col_offset=4,
                    end_lineno=29,
                    end_col_offset=21,
                    name='action_create_calendar_event',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=18, col_offset=37, end_lineno=18, end_col_offset=41, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=19,
                            col_offset=8,
                            end_lineno=19,
                            end_col_offset=25,
                            value=Call(
                                lineno=19,
                                col_offset=8,
                                end_lineno=19,
                                end_col_offset=25,
                                func=Attribute(
                                    lineno=19,
                                    col_offset=8,
                                    end_lineno=19,
                                    end_col_offset=23,
                                    value=Name(lineno=19, col_offset=8, end_lineno=19, end_col_offset=12, id='self', ctx=Load()),
                                    attr='ensure_one',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=20,
                            col_offset=8,
                            end_lineno=20,
                            end_col_offset=93,
                            targets=[Name(lineno=20, col_offset=8, end_lineno=20, end_col_offset=14, id='action', ctx=Store())],
                            value=Call(
                                lineno=20,
                                col_offset=17,
                                end_lineno=20,
                                end_col_offset=93,
                                func=Attribute(
                                    lineno=20,
                                    col_offset=17,
                                    end_lineno=20,
                                    end_col_offset=59,
                                    value=Subscript(
                                        lineno=20,
                                        col_offset=17,
                                        end_lineno=20,
                                        end_col_offset=47,
                                        value=Attribute(
                                            lineno=20,
                                            col_offset=17,
                                            end_lineno=20,
                                            end_col_offset=25,
                                            value=Name(lineno=20, col_offset=17, end_lineno=20, end_col_offset=21, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=20, col_offset=26, end_lineno=20, end_col_offset=46, value='ir.actions.actions', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='_for_xml_id',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=20, col_offset=60, end_lineno=20, end_col_offset=92, value='calendar.action_calendar_event', kind=None)],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=21,
                            col_offset=8,
                            end_lineno=28,
                            end_col_offset=9,
                            targets=[
                                Subscript(
                                    lineno=21,
                                    col_offset=8,
                                    end_lineno=21,
                                    end_col_offset=25,
                                    value=Name(lineno=21, col_offset=8, end_lineno=21, end_col_offset=14, id='action', ctx=Load()),
                                    slice=Constant(lineno=21, col_offset=15, end_lineno=21, end_col_offset=24, value='context', kind=None),
                                    ctx=Store(),
                                ),
                            ],
                            value=Dict(
                                lineno=21,
                                col_offset=28,
                                end_lineno=28,
                                end_col_offset=9,
                                keys=[
                                    Constant(lineno=22, col_offset=12, end_lineno=22, end_col_offset=38, value='default_activity_type_id', kind=None),
                                    Constant(lineno=23, col_offset=12, end_lineno=23, end_col_offset=28, value='default_res_id', kind=None),
                                    Constant(lineno=24, col_offset=12, end_lineno=24, end_col_offset=31, value='default_res_model', kind=None),
                                    Constant(lineno=25, col_offset=12, end_lineno=25, end_col_offset=26, value='default_name', kind=None),
                                    Constant(lineno=26, col_offset=12, end_lineno=26, end_col_offset=33, value='default_description', kind=None),
                                    Constant(lineno=27, col_offset=12, end_lineno=27, end_col_offset=34, value='default_activity_ids', kind=None),
                                ],
                                values=[
                                    Attribute(
                                        lineno=22,
                                        col_offset=40,
                                        end_lineno=22,
                                        end_col_offset=64,
                                        value=Attribute(
                                            lineno=22,
                                            col_offset=40,
                                            end_lineno=22,
                                            end_col_offset=61,
                                            value=Name(lineno=22, col_offset=40, end_lineno=22, end_col_offset=44, id='self', ctx=Load()),
                                            attr='activity_type_id',
                                            ctx=Load(),
                                        ),
                                        attr='id',
                                        ctx=Load(),
                                    ),
                                    Call(
                                        lineno=23,
                                        col_offset=30,
                                        end_lineno=23,
                                        end_col_offset=68,
                                        func=Attribute(
                                            lineno=23,
                                            col_offset=30,
                                            end_lineno=23,
                                            end_col_offset=50,
                                            value=Attribute(
                                                lineno=23,
                                                col_offset=30,
                                                end_lineno=23,
                                                end_col_offset=46,
                                                value=Attribute(
                                                    lineno=23,
                                                    col_offset=30,
                                                    end_lineno=23,
                                                    end_col_offset=38,
                                                    value=Name(lineno=23, col_offset=30, end_lineno=23, end_col_offset=34, id='self', ctx=Load()),
                                                    attr='env',
                                                    ctx=Load(),
                                                ),
                                                attr='context',
                                                ctx=Load(),
                                            ),
                                            attr='get',
                                            ctx=Load(),
                                        ),
                                        args=[Constant(lineno=23, col_offset=51, end_lineno=23, end_col_offset=67, value='default_res_id', kind=None)],
                                        keywords=[],
                                    ),
                                    Call(
                                        lineno=24,
                                        col_offset=33,
                                        end_lineno=24,
                                        end_col_offset=74,
                                        func=Attribute(
                                            lineno=24,
                                            col_offset=33,
                                            end_lineno=24,
                                            end_col_offset=53,
                                            value=Attribute(
                                                lineno=24,
                                                col_offset=33,
                                                end_lineno=24,
                                                end_col_offset=49,
                                                value=Attribute(
                                                    lineno=24,
                                                    col_offset=33,
                                                    end_lineno=24,
                                                    end_col_offset=41,
                                                    value=Name(lineno=24, col_offset=33, end_lineno=24, end_col_offset=37, id='self', ctx=Load()),
                                                    attr='env',
                                                    ctx=Load(),
                                                ),
                                                attr='context',
                                                ctx=Load(),
                                            ),
                                            attr='get',
                                            ctx=Load(),
                                        ),
                                        args=[Constant(lineno=24, col_offset=54, end_lineno=24, end_col_offset=73, value='default_res_model', kind=None)],
                                        keywords=[],
                                    ),
                                    BoolOp(
                                        lineno=25,
                                        col_offset=28,
                                        end_lineno=25,
                                        end_col_offset=57,
                                        op=Or(),
                                        values=[
                                            Attribute(
                                                lineno=25,
                                                col_offset=28,
                                                end_lineno=25,
                                                end_col_offset=40,
                                                value=Name(lineno=25, col_offset=28, end_lineno=25, end_col_offset=32, id='self', ctx=Load()),
                                                attr='summary',
                                                ctx=Load(),
                                            ),
                                            Attribute(
                                                lineno=25,
                                                col_offset=44,
                                                end_lineno=25,
                                                end_col_offset=57,
                                                value=Name(lineno=25, col_offset=44, end_lineno=25, end_col_offset=48, id='self', ctx=Load()),
                                                attr='res_name',
                                                ctx=Load(),
                                            ),
                                        ],
                                    ),
                                    BoolOp(
                                        lineno=26,
                                        col_offset=35,
                                        end_lineno=26,
                                        end_col_offset=94,
                                        op=Or(),
                                        values=[
                                            BoolOp(
                                                lineno=26,
                                                col_offset=35,
                                                end_lineno=26,
                                                end_col_offset=88,
                                                op=And(),
                                                values=[
                                                    Attribute(
                                                        lineno=26,
                                                        col_offset=35,
                                                        end_lineno=26,
                                                        end_col_offset=44,
                                                        value=Name(lineno=26, col_offset=35, end_lineno=26, end_col_offset=39, id='self', ctx=Load()),
                                                        attr='note',
                                                        ctx=Load(),
                                                    ),
                                                    Call(
                                                        lineno=26,
                                                        col_offset=49,
                                                        end_lineno=26,
                                                        end_col_offset=88,
                                                        func=Attribute(
                                                            lineno=26,
                                                            col_offset=49,
                                                            end_lineno=26,
                                                            end_col_offset=86,
                                                            value=Call(
                                                                lineno=26,
                                                                col_offset=49,
                                                                end_lineno=26,
                                                                end_col_offset=80,
                                                                func=Attribute(
                                                                    lineno=26,
                                                                    col_offset=49,
                                                                    end_lineno=26,
                                                                    end_col_offset=69,
                                                                    value=Name(lineno=26, col_offset=49, end_lineno=26, end_col_offset=54, id='tools', ctx=Load()),
                                                                    attr='html2plaintext',
                                                                    ctx=Load(),
                                                                ),
                                                                args=[
                                                                    Attribute(
                                                                        lineno=26,
                                                                        col_offset=70,
                                                                        end_lineno=26,
                                                                        end_col_offset=79,
                                                                        value=Name(lineno=26, col_offset=70, end_lineno=26, end_col_offset=74, id='self', ctx=Load()),
                                                                        attr='note',
                                                                        ctx=Load(),
                                                                    ),
                                                                ],
                                                                keywords=[],
                                                            ),
                                                            attr='strip',
                                                            ctx=Load(),
                                                        ),
                                                        args=[],
                                                        keywords=[],
                                                    ),
                                                ],
                                            ),
                                            Constant(lineno=26, col_offset=92, end_lineno=26, end_col_offset=94, value='', kind=None),
                                        ],
                                    ),
                                    List(
                                        lineno=27,
                                        col_offset=36,
                                        end_lineno=27,
                                        end_col_offset=54,
                                        elts=[
                                            Tuple(
                                                lineno=27,
                                                col_offset=37,
                                                end_lineno=27,
                                                end_col_offset=53,
                                                elts=[
                                                    Constant(lineno=27, col_offset=38, end_lineno=27, end_col_offset=39, value=6, kind=None),
                                                    Constant(lineno=27, col_offset=41, end_lineno=27, end_col_offset=42, value=0, kind=None),
                                                    Attribute(
                                                        lineno=27,
                                                        col_offset=44,
                                                        end_lineno=27,
                                                        end_col_offset=52,
                                                        value=Name(lineno=27, col_offset=44, end_lineno=27, end_col_offset=48, id='self', ctx=Load()),
                                                        attr='ids',
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                        Return(
                            lineno=29,
                            col_offset=8,
                            end_lineno=29,
                            end_col_offset=21,
                            value=Name(lineno=29, col_offset=15, end_lineno=29, end_col_offset=21, id='action', ctx=Load()),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=31,
                    col_offset=4,
                    end_lineno=42,
                    end_col_offset=35,
                    name='_action_done',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=31, col_offset=21, end_lineno=31, end_col_offset=25, arg='self', annotation=None, type_comment=None),
                            arg(lineno=31, col_offset=27, end_lineno=31, end_col_offset=35, arg='feedback', annotation=None, type_comment=None),
                            arg(lineno=31, col_offset=43, end_lineno=31, end_col_offset=57, arg='attachment_ids', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[
                            Constant(lineno=31, col_offset=36, end_lineno=31, end_col_offset=41, value=False, kind=None),
                            Constant(lineno=31, col_offset=58, end_lineno=31, end_col_offset=63, value=False, kind=None),
                        ],
                    ),
                    body=[
                        Assign(
                            lineno=32,
                            col_offset=8,
                            end_lineno=32,
                            end_col_offset=49,
                            targets=[Name(lineno=32, col_offset=8, end_lineno=32, end_col_offset=14, id='events', ctx=Store())],
                            value=Call(
                                lineno=32,
                                col_offset=17,
                                end_lineno=32,
                                end_col_offset=49,
                                func=Attribute(
                                    lineno=32,
                                    col_offset=17,
                                    end_lineno=32,
                                    end_col_offset=28,
                                    value=Name(lineno=32, col_offset=17, end_lineno=32, end_col_offset=21, id='self', ctx=Load()),
                                    attr='mapped',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=32, col_offset=29, end_lineno=32, end_col_offset=48, value='calendar_event_id', kind=None)],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=33,
                            col_offset=8,
                            end_lineno=33,
                            end_col_offset=119,
                            targets=[
                                Tuple(
                                    lineno=33,
                                    col_offset=8,
                                    end_lineno=33,
                                    end_col_offset=28,
                                    elts=[
                                        Name(lineno=33, col_offset=8, end_lineno=33, end_col_offset=16, id='messages', ctx=Store()),
                                        Name(lineno=33, col_offset=18, end_lineno=33, end_col_offset=28, id='activities', ctx=Store()),
                                    ],
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=33,
                                col_offset=31,
                                end_lineno=33,
                                end_col_offset=119,
                                func=Attribute(
                                    lineno=33,
                                    col_offset=31,
                                    end_lineno=33,
                                    end_col_offset=69,
                                    value=Call(
                                        lineno=33,
                                        col_offset=31,
                                        end_lineno=33,
                                        end_col_offset=56,
                                        func=Name(lineno=33, col_offset=31, end_lineno=33, end_col_offset=36, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=33, col_offset=37, end_lineno=33, end_col_offset=49, id='MailActivity', ctx=Load()),
                                            Name(lineno=33, col_offset=51, end_lineno=33, end_col_offset=55, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='_action_done',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[
                                    keyword(
                                        lineno=33,
                                        col_offset=70,
                                        end_lineno=33,
                                        end_col_offset=87,
                                        arg='feedback',
                                        value=Name(lineno=33, col_offset=79, end_lineno=33, end_col_offset=87, id='feedback', ctx=Load()),
                                    ),
                                    keyword(
                                        lineno=33,
                                        col_offset=89,
                                        end_lineno=33,
                                        end_col_offset=118,
                                        arg='attachment_ids',
                                        value=Name(lineno=33, col_offset=104, end_lineno=33, end_col_offset=118, id='attachment_ids', ctx=Load()),
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                        If(
                            lineno=34,
                            col_offset=8,
                            end_lineno=41,
                            end_col_offset=57,
                            test=Name(lineno=34, col_offset=11, end_lineno=34, end_col_offset=19, id='feedback', ctx=Load()),
                            body=[
                                For(
                                    lineno=35,
                                    col_offset=12,
                                    end_lineno=41,
                                    end_col_offset=57,
                                    target=Name(lineno=35, col_offset=16, end_lineno=35, end_col_offset=21, id='event', ctx=Store()),
                                    iter=Name(lineno=35, col_offset=25, end_lineno=35, end_col_offset=31, id='events', ctx=Load()),
                                    body=[
                                        Assign(
                                            lineno=36,
                                            col_offset=16,
                                            end_lineno=36,
                                            end_col_offset=47,
                                            targets=[Name(lineno=36, col_offset=16, end_lineno=36, end_col_offset=27, id='description', ctx=Store())],
                                            value=Attribute(
                                                lineno=36,
                                                col_offset=30,
                                                end_lineno=36,
                                                end_col_offset=47,
                                                value=Name(lineno=36, col_offset=30, end_lineno=36, end_col_offset=35, id='event', ctx=Load()),
                                                attr='description',
                                                ctx=Load(),
                                            ),
                                            type_comment=None,
                                        ),
                                        Assign(
                                            lineno=37,
                                            col_offset=16,
                                            end_lineno=40,
                                            end_col_offset=17,
                                            targets=[Name(lineno=37, col_offset=16, end_lineno=37, end_col_offset=27, id='description', ctx=Store())],
                                            value=BinOp(
                                                lineno=37,
                                                col_offset=30,
                                                end_lineno=40,
                                                end_col_offset=17,
                                                left=Constant(lineno=37, col_offset=30, end_lineno=37, end_col_offset=42, value='%s<br />%s', kind=None),
                                                op=Mod(),
                                                right=Tuple(
                                                    lineno=37,
                                                    col_offset=45,
                                                    end_lineno=40,
                                                    end_col_offset=17,
                                                    elts=[
                                                        IfExp(
                                                            lineno=38,
                                                            col_offset=20,
                                                            end_lineno=38,
                                                            end_col_offset=79,
                                                            test=UnaryOp(
                                                                lineno=38,
                                                                col_offset=35,
                                                                end_lineno=38,
                                                                end_col_offset=71,
                                                                op=Not(),
                                                                operand=Call(
                                                                    lineno=38,
                                                                    col_offset=39,
                                                                    end_lineno=38,
                                                                    end_col_offset=71,
                                                                    func=Attribute(
                                                                        lineno=38,
                                                                        col_offset=39,
                                                                        end_lineno=38,
                                                                        end_col_offset=58,
                                                                        value=Name(lineno=38, col_offset=39, end_lineno=38, end_col_offset=44, id='tools', ctx=Load()),
                                                                        attr='is_html_empty',
                                                                        ctx=Load(),
                                                                    ),
                                                                    args=[Name(lineno=38, col_offset=59, end_lineno=38, end_col_offset=70, id='description', ctx=Load())],
                                                                    keywords=[],
                                                                ),
                                                            ),
                                                            body=Name(lineno=38, col_offset=20, end_lineno=38, end_col_offset=31, id='description', ctx=Load()),
                                                            orelse=Constant(lineno=38, col_offset=77, end_lineno=38, end_col_offset=79, value='', kind=None),
                                                        ),
                                                        IfExp(
                                                            lineno=39,
                                                            col_offset=20,
                                                            end_lineno=39,
                                                            end_col_offset=108,
                                                            test=Name(lineno=39, col_offset=92, end_lineno=39, end_col_offset=100, id='feedback', ctx=Load()),
                                                            body=Call(
                                                                lineno=39,
                                                                col_offset=20,
                                                                end_lineno=39,
                                                                end_col_offset=88,
                                                                func=Name(lineno=39, col_offset=20, end_lineno=39, end_col_offset=21, id='_', ctx=Load()),
                                                                args=[Constant(lineno=39, col_offset=22, end_lineno=39, end_col_offset=46, value='Feedback: %(feedback)s', kind=None)],
                                                                keywords=[
                                                                    keyword(
                                                                        lineno=39,
                                                                        col_offset=48,
                                                                        end_lineno=39,
                                                                        end_col_offset=87,
                                                                        arg='feedback',
                                                                        value=Call(
                                                                            lineno=39,
                                                                            col_offset=57,
                                                                            end_lineno=39,
                                                                            end_col_offset=87,
                                                                            func=Attribute(
                                                                                lineno=39,
                                                                                col_offset=57,
                                                                                end_lineno=39,
                                                                                end_col_offset=77,
                                                                                value=Name(lineno=39, col_offset=57, end_lineno=39, end_col_offset=62, id='tools', ctx=Load()),
                                                                                attr='plaintext2html',
                                                                                ctx=Load(),
                                                                            ),
                                                                            args=[Name(lineno=39, col_offset=78, end_lineno=39, end_col_offset=86, id='feedback', ctx=Load())],
                                                                            keywords=[],
                                                                        ),
                                                                    ),
                                                                ],
                                                            ),
                                                            orelse=Constant(lineno=39, col_offset=106, end_lineno=39, end_col_offset=108, value='', kind=None),
                                                        ),
                                                    ],
                                                    ctx=Load(),
                                                ),
                                            ),
                                            type_comment=None,
                                        ),
                                        Expr(
                                            lineno=41,
                                            col_offset=16,
                                            end_lineno=41,
                                            end_col_offset=57,
                                            value=Call(
                                                lineno=41,
                                                col_offset=16,
                                                end_lineno=41,
                                                end_col_offset=57,
                                                func=Attribute(
                                                    lineno=41,
                                                    col_offset=16,
                                                    end_lineno=41,
                                                    end_col_offset=27,
                                                    value=Name(lineno=41, col_offset=16, end_lineno=41, end_col_offset=21, id='event', ctx=Load()),
                                                    attr='write',
                                                    ctx=Load(),
                                                ),
                                                args=[
                                                    Dict(
                                                        lineno=41,
                                                        col_offset=28,
                                                        end_lineno=41,
                                                        end_col_offset=56,
                                                        keys=[Constant(lineno=41, col_offset=29, end_lineno=41, end_col_offset=42, value='description', kind=None)],
                                                        values=[Name(lineno=41, col_offset=44, end_lineno=41, end_col_offset=55, id='description', ctx=Load())],
                                                    ),
                                                ],
                                                keywords=[],
                                            ),
                                        ),
                                    ],
                                    orelse=[],
                                    type_comment=None,
                                ),
                            ],
                            orelse=[],
                        ),
                        Return(
                            lineno=42,
                            col_offset=8,
                            end_lineno=42,
                            end_col_offset=35,
                            value=Tuple(
                                lineno=42,
                                col_offset=15,
                                end_lineno=42,
                                end_col_offset=35,
                                elts=[
                                    Name(lineno=42, col_offset=15, end_lineno=42, end_col_offset=23, id='messages', ctx=Load()),
                                    Name(lineno=42, col_offset=25, end_lineno=42, end_col_offset=35, id='activities', ctx=Load()),
                                ],
                                ctx=Load(),
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=44,
                    col_offset=4,
                    end_lineno=48,
                    end_col_offset=18,
                    name='unlink_w_meeting',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=44, col_offset=25, end_lineno=44, end_col_offset=29, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=45,
                            col_offset=8,
                            end_lineno=45,
                            end_col_offset=49,
                            targets=[Name(lineno=45, col_offset=8, end_lineno=45, end_col_offset=14, id='events', ctx=Store())],
                            value=Call(
                                lineno=45,
                                col_offset=17,
                                end_lineno=45,
                                end_col_offset=49,
                                func=Attribute(
                                    lineno=45,
                                    col_offset=17,
                                    end_lineno=45,
                                    end_col_offset=28,
                                    value=Name(lineno=45, col_offset=17, end_lineno=45, end_col_offset=21, id='self', ctx=Load()),
                                    attr='mapped',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=45, col_offset=29, end_lineno=45, end_col_offset=48, value='calendar_event_id', kind=None)],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=46,
                            col_offset=8,
                            end_lineno=46,
                            end_col_offset=27,
                            targets=[Name(lineno=46, col_offset=8, end_lineno=46, end_col_offset=11, id='res', ctx=Store())],
                            value=Call(
                                lineno=46,
                                col_offset=14,
                                end_lineno=46,
                                end_col_offset=27,
                                func=Attribute(
                                    lineno=46,
                                    col_offset=14,
                                    end_lineno=46,
                                    end_col_offset=25,
                                    value=Name(lineno=46, col_offset=14, end_lineno=46, end_col_offset=18, id='self', ctx=Load()),
                                    attr='unlink',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=47,
                            col_offset=8,
                            end_lineno=47,
                            end_col_offset=23,
                            value=Call(
                                lineno=47,
                                col_offset=8,
                                end_lineno=47,
                                end_col_offset=23,
                                func=Attribute(
                                    lineno=47,
                                    col_offset=8,
                                    end_lineno=47,
                                    end_col_offset=21,
                                    value=Name(lineno=47, col_offset=8, end_lineno=47, end_col_offset=14, id='events', ctx=Load()),
                                    attr='unlink',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Return(
                            lineno=48,
                            col_offset=8,
                            end_lineno=48,
                            end_col_offset=18,
                            value=Name(lineno=48, col_offset=15, end_lineno=48, end_col_offset=18, id='res', ctx=Load()),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
