Module(
    body=[
        Import(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=14,
            names=[alias(name='logging', asname=None)],
        ),
        ImportFrom(
            lineno=5,
            col_offset=0,
            end_lineno=5,
            end_col_offset=28,
            module='threading',
            names=[alias(name='Thread', asname=None)],
            level=0,
        ),
        Import(
            lineno=6,
            col_offset=0,
            end_lineno=6,
            end_col_offset=11,
            names=[alias(name='time', asname=None)],
        ),
        ImportFrom(
            lineno=8,
            col_offset=0,
            end_lineno=8,
            end_col_offset=72,
            module='odoo.addons.hw_drivers.main',
            names=[
                alias(name='drivers', asname=None),
                alias(name='interfaces', asname=None),
                alias(name='iot_devices', asname=None),
            ],
            level=0,
        ),
        Assign(
            lineno=10,
            col_offset=0,
            end_lineno=10,
            end_col_offset=37,
            targets=[Name(lineno=10, col_offset=0, end_lineno=10, end_col_offset=7, id='_logger', ctx=Store())],
            value=Call(
                lineno=10,
                col_offset=10,
                end_lineno=10,
                end_col_offset=37,
                func=Attribute(
                    lineno=10,
                    col_offset=10,
                    end_lineno=10,
                    end_col_offset=27,
                    value=Name(lineno=10, col_offset=10, end_lineno=10, end_col_offset=17, id='logging', ctx=Load()),
                    attr='getLogger',
                    ctx=Load(),
                ),
                args=[Name(lineno=10, col_offset=28, end_lineno=10, end_col_offset=36, id='__name__', ctx=Load())],
                keywords=[],
            ),
            type_comment=None,
        ),
        ClassDef(
            lineno=13,
            col_offset=0,
            end_lineno=17,
            end_col_offset=28,
            name='InterfaceMetaClass',
            bases=[Name(lineno=13, col_offset=25, end_lineno=13, end_col_offset=29, id='type', ctx=Load())],
            keywords=[],
            body=[
                FunctionDef(
                    lineno=14,
                    col_offset=4,
                    end_lineno=17,
                    end_col_offset=28,
                    name='__new__',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=14, col_offset=16, end_lineno=14, end_col_offset=19, arg='cls', annotation=None, type_comment=None),
                            arg(lineno=14, col_offset=21, end_lineno=14, end_col_offset=28, arg='clsname', annotation=None, type_comment=None),
                            arg(lineno=14, col_offset=30, end_lineno=14, end_col_offset=35, arg='bases', annotation=None, type_comment=None),
                            arg(lineno=14, col_offset=37, end_lineno=14, end_col_offset=42, arg='attrs', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=15,
                            col_offset=8,
                            end_lineno=15,
                            end_col_offset=90,
                            targets=[Name(lineno=15, col_offset=8, end_lineno=15, end_col_offset=21, id='new_interface', ctx=Store())],
                            value=Call(
                                lineno=15,
                                col_offset=24,
                                end_lineno=15,
                                end_col_offset=90,
                                func=Attribute(
                                    lineno=15,
                                    col_offset=24,
                                    end_lineno=15,
                                    end_col_offset=62,
                                    value=Call(
                                        lineno=15,
                                        col_offset=24,
                                        end_lineno=15,
                                        end_col_offset=54,
                                        func=Name(lineno=15, col_offset=24, end_lineno=15, end_col_offset=29, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=15, col_offset=30, end_lineno=15, end_col_offset=48, id='InterfaceMetaClass', ctx=Load()),
                                            Name(lineno=15, col_offset=50, end_lineno=15, end_col_offset=53, id='cls', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='__new__',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=15, col_offset=63, end_lineno=15, end_col_offset=66, id='cls', ctx=Load()),
                                    Name(lineno=15, col_offset=68, end_lineno=15, end_col_offset=75, id='clsname', ctx=Load()),
                                    Name(lineno=15, col_offset=77, end_lineno=15, end_col_offset=82, id='bases', ctx=Load()),
                                    Name(lineno=15, col_offset=84, end_lineno=15, end_col_offset=89, id='attrs', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=16,
                            col_offset=8,
                            end_lineno=16,
                            end_col_offset=43,
                            targets=[
                                Subscript(
                                    lineno=16,
                                    col_offset=8,
                                    end_lineno=16,
                                    end_col_offset=27,
                                    value=Name(lineno=16, col_offset=8, end_lineno=16, end_col_offset=18, id='interfaces', ctx=Load()),
                                    slice=Name(lineno=16, col_offset=19, end_lineno=16, end_col_offset=26, id='clsname', ctx=Load()),
                                    ctx=Store(),
                                ),
                            ],
                            value=Name(lineno=16, col_offset=30, end_lineno=16, end_col_offset=43, id='new_interface', ctx=Load()),
                            type_comment=None,
                        ),
                        Return(
                            lineno=17,
                            col_offset=8,
                            end_lineno=17,
                            end_col_offset=28,
                            value=Name(lineno=17, col_offset=15, end_lineno=17, end_col_offset=28, id='new_interface', ctx=Load()),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
        ClassDef(
            lineno=20,
            col_offset=0,
            end_lineno=70,
            end_col_offset=35,
            name='Interface',
            bases=[Name(lineno=20, col_offset=16, end_lineno=20, end_col_offset=22, id='Thread', ctx=Load())],
            keywords=[
                keyword(
                    lineno=20,
                    col_offset=24,
                    end_lineno=20,
                    end_col_offset=52,
                    arg='metaclass',
                    value=Name(lineno=20, col_offset=34, end_lineno=20, end_col_offset=52, id='InterfaceMetaClass', ctx=Load()),
                ),
            ],
            body=[
                Assign(
                    lineno=21,
                    col_offset=4,
                    end_lineno=21,
                    end_col_offset=19,
                    targets=[Name(lineno=21, col_offset=4, end_lineno=21, end_col_offset=15, id='_loop_delay', ctx=Store())],
                    value=Constant(lineno=21, col_offset=18, end_lineno=21, end_col_offset=19, value=3, kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=22,
                    col_offset=4,
                    end_lineno=22,
                    end_col_offset=26,
                    targets=[Name(lineno=22, col_offset=4, end_lineno=22, end_col_offset=21, id='_detected_devices', ctx=Store())],
                    value=Dict(lineno=22, col_offset=24, end_lineno=22, end_col_offset=26, keys=[], values=[]),
                    type_comment=None,
                ),
                Assign(
                    lineno=23,
                    col_offset=4,
                    end_lineno=23,
                    end_col_offset=24,
                    targets=[Name(lineno=23, col_offset=4, end_lineno=23, end_col_offset=19, id='connection_type', ctx=Store())],
                    value=Constant(lineno=23, col_offset=22, end_lineno=23, end_col_offset=24, value='', kind=None),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=25,
                    col_offset=4,
                    end_lineno=27,
                    end_col_offset=136,
                    name='__init__',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=25, col_offset=17, end_lineno=25, end_col_offset=21, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=26,
                            col_offset=8,
                            end_lineno=26,
                            end_col_offset=41,
                            value=Call(
                                lineno=26,
                                col_offset=8,
                                end_lineno=26,
                                end_col_offset=41,
                                func=Attribute(
                                    lineno=26,
                                    col_offset=8,
                                    end_lineno=26,
                                    end_col_offset=39,
                                    value=Call(
                                        lineno=26,
                                        col_offset=8,
                                        end_lineno=26,
                                        end_col_offset=30,
                                        func=Name(lineno=26, col_offset=8, end_lineno=26, end_col_offset=13, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=26, col_offset=14, end_lineno=26, end_col_offset=23, id='Interface', ctx=Load()),
                                            Name(lineno=26, col_offset=25, end_lineno=26, end_col_offset=29, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='__init__',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=27,
                            col_offset=8,
                            end_lineno=27,
                            end_col_offset=136,
                            targets=[
                                Attribute(
                                    lineno=27,
                                    col_offset=8,
                                    end_lineno=27,
                                    end_col_offset=20,
                                    value=Name(lineno=27, col_offset=8, end_lineno=27, end_col_offset=12, id='self', ctx=Load()),
                                    attr='drivers',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=27,
                                col_offset=23,
                                end_lineno=27,
                                end_col_offset=136,
                                func=Name(lineno=27, col_offset=23, end_lineno=27, end_col_offset=29, id='sorted', ctx=Load()),
                                args=[
                                    ListComp(
                                        lineno=27,
                                        col_offset=30,
                                        end_lineno=27,
                                        end_col_offset=95,
                                        elt=Name(lineno=27, col_offset=31, end_lineno=27, end_col_offset=32, id='d', ctx=Load()),
                                        generators=[
                                            comprehension(
                                                target=Name(lineno=27, col_offset=37, end_lineno=27, end_col_offset=38, id='d', ctx=Store()),
                                                iter=Name(lineno=27, col_offset=42, end_lineno=27, end_col_offset=49, id='drivers', ctx=Load()),
                                                ifs=[
                                                    Compare(
                                                        lineno=27,
                                                        col_offset=53,
                                                        end_lineno=27,
                                                        end_col_offset=94,
                                                        left=Attribute(
                                                            lineno=27,
                                                            col_offset=53,
                                                            end_lineno=27,
                                                            end_col_offset=70,
                                                            value=Name(lineno=27, col_offset=53, end_lineno=27, end_col_offset=54, id='d', ctx=Load()),
                                                            attr='connection_type',
                                                            ctx=Load(),
                                                        ),
                                                        ops=[Eq()],
                                                        comparators=[
                                                            Attribute(
                                                                lineno=27,
                                                                col_offset=74,
                                                                end_lineno=27,
                                                                end_col_offset=94,
                                                                value=Name(lineno=27, col_offset=74, end_lineno=27, end_col_offset=78, id='self', ctx=Load()),
                                                                attr='connection_type',
                                                                ctx=Load(),
                                                            ),
                                                        ],
                                                    ),
                                                ],
                                                is_async=0,
                                            ),
                                        ],
                                    ),
                                ],
                                keywords=[
                                    keyword(
                                        lineno=27,
                                        col_offset=97,
                                        end_lineno=27,
                                        end_col_offset=121,
                                        arg='key',
                                        value=Lambda(
                                            lineno=27,
                                            col_offset=101,
                                            end_lineno=27,
                                            end_col_offset=121,
                                            args=arguments(
                                                posonlyargs=[],
                                                args=[arg(lineno=27, col_offset=108, end_lineno=27, end_col_offset=109, arg='d', annotation=None, type_comment=None)],
                                                vararg=None,
                                                kwonlyargs=[],
                                                kw_defaults=[],
                                                kwarg=None,
                                                defaults=[],
                                            ),
                                            body=Attribute(
                                                lineno=27,
                                                col_offset=111,
                                                end_lineno=27,
                                                end_col_offset=121,
                                                value=Name(lineno=27, col_offset=111, end_lineno=27, end_col_offset=112, id='d', ctx=Load()),
                                                attr='priority',
                                                ctx=Load(),
                                            ),
                                        ),
                                    ),
                                    keyword(
                                        lineno=27,
                                        col_offset=123,
                                        end_lineno=27,
                                        end_col_offset=135,
                                        arg='reverse',
                                        value=Constant(lineno=27, col_offset=131, end_lineno=27, end_col_offset=135, value=True, kind=None),
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=29,
                    col_offset=4,
                    end_lineno=34,
                    end_col_offset=40,
                    name='run',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=29, col_offset=12, end_lineno=29, end_col_offset=16, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        While(
                            lineno=30,
                            col_offset=8,
                            end_lineno=34,
                            end_col_offset=40,
                            test=BoolOp(
                                lineno=30,
                                col_offset=14,
                                end_lineno=30,
                                end_col_offset=51,
                                op=And(),
                                values=[
                                    Attribute(
                                        lineno=30,
                                        col_offset=14,
                                        end_lineno=30,
                                        end_col_offset=34,
                                        value=Name(lineno=30, col_offset=14, end_lineno=30, end_col_offset=18, id='self', ctx=Load()),
                                        attr='connection_type',
                                        ctx=Load(),
                                    ),
                                    Attribute(
                                        lineno=30,
                                        col_offset=39,
                                        end_lineno=30,
                                        end_col_offset=51,
                                        value=Name(lineno=30, col_offset=39, end_lineno=30, end_col_offset=43, id='self', ctx=Load()),
                                        attr='drivers',
                                        ctx=Load(),
                                    ),
                                ],
                            ),
                            body=[
                                Expr(
                                    lineno=31,
                                    col_offset=12,
                                    end_lineno=31,
                                    end_col_offset=55,
                                    value=Call(
                                        lineno=31,
                                        col_offset=12,
                                        end_lineno=31,
                                        end_col_offset=55,
                                        func=Attribute(
                                            lineno=31,
                                            col_offset=12,
                                            end_lineno=31,
                                            end_col_offset=35,
                                            value=Name(lineno=31, col_offset=12, end_lineno=31, end_col_offset=16, id='self', ctx=Load()),
                                            attr='update_iot_devices',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Call(
                                                lineno=31,
                                                col_offset=36,
                                                end_lineno=31,
                                                end_col_offset=54,
                                                func=Attribute(
                                                    lineno=31,
                                                    col_offset=36,
                                                    end_lineno=31,
                                                    end_col_offset=52,
                                                    value=Name(lineno=31, col_offset=36, end_lineno=31, end_col_offset=40, id='self', ctx=Load()),
                                                    attr='get_devices',
                                                    ctx=Load(),
                                                ),
                                                args=[],
                                                keywords=[],
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                ),
                                If(
                                    lineno=32,
                                    col_offset=12,
                                    end_lineno=33,
                                    end_col_offset=21,
                                    test=UnaryOp(
                                        lineno=32,
                                        col_offset=15,
                                        end_lineno=32,
                                        end_col_offset=35,
                                        op=Not(),
                                        operand=Attribute(
                                            lineno=32,
                                            col_offset=19,
                                            end_lineno=32,
                                            end_col_offset=35,
                                            value=Name(lineno=32, col_offset=19, end_lineno=32, end_col_offset=23, id='self', ctx=Load()),
                                            attr='_loop_delay',
                                            ctx=Load(),
                                        ),
                                    ),
                                    body=[Break(lineno=33, col_offset=16, end_lineno=33, end_col_offset=21)],
                                    orelse=[],
                                ),
                                Expr(
                                    lineno=34,
                                    col_offset=12,
                                    end_lineno=34,
                                    end_col_offset=40,
                                    value=Call(
                                        lineno=34,
                                        col_offset=12,
                                        end_lineno=34,
                                        end_col_offset=40,
                                        func=Attribute(
                                            lineno=34,
                                            col_offset=12,
                                            end_lineno=34,
                                            end_col_offset=22,
                                            value=Name(lineno=34, col_offset=12, end_lineno=34, end_col_offset=16, id='time', ctx=Load()),
                                            attr='sleep',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            Attribute(
                                                lineno=34,
                                                col_offset=23,
                                                end_lineno=34,
                                                end_col_offset=39,
                                                value=Name(lineno=34, col_offset=23, end_lineno=34, end_col_offset=27, id='self', ctx=Load()),
                                                attr='_loop_delay',
                                                ctx=Load(),
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                ),
                            ],
                            orelse=[],
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=36,
                    col_offset=4,
                    end_lineno=67,
                    end_col_offset=25,
                    name='update_iot_devices',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=36, col_offset=27, end_lineno=36, end_col_offset=31, arg='self', annotation=None, type_comment=None),
                            arg(lineno=36, col_offset=33, end_lineno=36, end_col_offset=40, arg='devices', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[Dict(lineno=36, col_offset=41, end_lineno=36, end_col_offset=43, keys=[], values=[])],
                    ),
                    body=[
                        Assign(
                            lineno=37,
                            col_offset=8,
                            end_lineno=37,
                            end_col_offset=55,
                            targets=[Name(lineno=37, col_offset=8, end_lineno=37, end_col_offset=13, id='added', ctx=Store())],
                            value=BinOp(
                                lineno=37,
                                col_offset=16,
                                end_lineno=37,
                                end_col_offset=55,
                                left=Call(
                                    lineno=37,
                                    col_offset=16,
                                    end_lineno=37,
                                    end_col_offset=30,
                                    func=Attribute(
                                        lineno=37,
                                        col_offset=16,
                                        end_lineno=37,
                                        end_col_offset=28,
                                        value=Name(lineno=37, col_offset=16, end_lineno=37, end_col_offset=23, id='devices', ctx=Load()),
                                        attr='keys',
                                        ctx=Load(),
                                    ),
                                    args=[],
                                    keywords=[],
                                ),
                                op=Sub(),
                                right=Attribute(
                                    lineno=37,
                                    col_offset=33,
                                    end_lineno=37,
                                    end_col_offset=55,
                                    value=Name(lineno=37, col_offset=33, end_lineno=37, end_col_offset=37, id='self', ctx=Load()),
                                    attr='_detected_devices',
                                    ctx=Load(),
                                ),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=38,
                            col_offset=8,
                            end_lineno=38,
                            end_col_offset=57,
                            targets=[Name(lineno=38, col_offset=8, end_lineno=38, end_col_offset=15, id='removed', ctx=Store())],
                            value=BinOp(
                                lineno=38,
                                col_offset=18,
                                end_lineno=38,
                                end_col_offset=57,
                                left=Attribute(
                                    lineno=38,
                                    col_offset=18,
                                    end_lineno=38,
                                    end_col_offset=40,
                                    value=Name(lineno=38, col_offset=18, end_lineno=38, end_col_offset=22, id='self', ctx=Load()),
                                    attr='_detected_devices',
                                    ctx=Load(),
                                ),
                                op=Sub(),
                                right=Call(
                                    lineno=38,
                                    col_offset=43,
                                    end_lineno=38,
                                    end_col_offset=57,
                                    func=Attribute(
                                        lineno=38,
                                        col_offset=43,
                                        end_lineno=38,
                                        end_col_offset=55,
                                        value=Name(lineno=38, col_offset=43, end_lineno=38, end_col_offset=50, id='devices', ctx=Load()),
                                        attr='keys',
                                        ctx=Load(),
                                    ),
                                    args=[],
                                    keywords=[],
                                ),
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=48,
                            col_offset=8,
                            end_lineno=48,
                            end_col_offset=47,
                            targets=[
                                Attribute(
                                    lineno=48,
                                    col_offset=8,
                                    end_lineno=48,
                                    end_col_offset=30,
                                    value=Name(lineno=48, col_offset=8, end_lineno=48, end_col_offset=12, id='self', ctx=Load()),
                                    attr='_detected_devices',
                                    ctx=Store(),
                                ),
                            ],
                            value=Call(
                                lineno=48,
                                col_offset=33,
                                end_lineno=48,
                                end_col_offset=47,
                                func=Attribute(
                                    lineno=48,
                                    col_offset=33,
                                    end_lineno=48,
                                    end_col_offset=45,
                                    value=Name(lineno=48, col_offset=33, end_lineno=48, end_col_offset=40, id='devices', ctx=Load()),
                                    attr='keys',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        For(
                            lineno=50,
                            col_offset=8,
                            end_lineno=53,
                            end_col_offset=73,
                            target=Name(lineno=50, col_offset=12, end_lineno=50, end_col_offset=22, id='identifier', ctx=Store()),
                            iter=Name(lineno=50, col_offset=26, end_lineno=50, end_col_offset=33, id='removed', ctx=Load()),
                            body=[
                                If(
                                    lineno=51,
                                    col_offset=12,
                                    end_lineno=53,
                                    end_col_offset=73,
                                    test=Compare(
                                        lineno=51,
                                        col_offset=15,
                                        end_lineno=51,
                                        end_col_offset=40,
                                        left=Name(lineno=51, col_offset=15, end_lineno=51, end_col_offset=25, id='identifier', ctx=Load()),
                                        ops=[In()],
                                        comparators=[Name(lineno=51, col_offset=29, end_lineno=51, end_col_offset=40, id='iot_devices', ctx=Load())],
                                    ),
                                    body=[
                                        Expr(
                                            lineno=52,
                                            col_offset=16,
                                            end_lineno=52,
                                            end_col_offset=52,
                                            value=Call(
                                                lineno=52,
                                                col_offset=16,
                                                end_lineno=52,
                                                end_col_offset=52,
                                                func=Attribute(
                                                    lineno=52,
                                                    col_offset=16,
                                                    end_lineno=52,
                                                    end_col_offset=50,
                                                    value=Subscript(
                                                        lineno=52,
                                                        col_offset=16,
                                                        end_lineno=52,
                                                        end_col_offset=39,
                                                        value=Name(lineno=52, col_offset=16, end_lineno=52, end_col_offset=27, id='iot_devices', ctx=Load()),
                                                        slice=Name(lineno=52, col_offset=28, end_lineno=52, end_col_offset=38, id='identifier', ctx=Load()),
                                                        ctx=Load(),
                                                    ),
                                                    attr='disconnect',
                                                    ctx=Load(),
                                                ),
                                                args=[],
                                                keywords=[],
                                            ),
                                        ),
                                        Expr(
                                            lineno=53,
                                            col_offset=16,
                                            end_lineno=53,
                                            end_col_offset=73,
                                            value=Call(
                                                lineno=53,
                                                col_offset=16,
                                                end_lineno=53,
                                                end_col_offset=73,
                                                func=Attribute(
                                                    lineno=53,
                                                    col_offset=16,
                                                    end_lineno=53,
                                                    end_col_offset=28,
                                                    value=Name(lineno=53, col_offset=16, end_lineno=53, end_col_offset=23, id='_logger', ctx=Load()),
                                                    attr='info',
                                                    ctx=Load(),
                                                ),
                                                args=[
                                                    Constant(lineno=53, col_offset=29, end_lineno=53, end_col_offset=60, value='Device %s is now disconnected', kind=None),
                                                    Name(lineno=53, col_offset=62, end_lineno=53, end_col_offset=72, id='identifier', ctx=Load()),
                                                ],
                                                keywords=[],
                                            ),
                                        ),
                                    ],
                                    orelse=[],
                                ),
                            ],
                            orelse=[],
                            type_comment=None,
                        ),
                        For(
                            lineno=55,
                            col_offset=8,
                            end_lineno=67,
                            end_col_offset=25,
                            target=Name(lineno=55, col_offset=12, end_lineno=55, end_col_offset=22, id='identifier', ctx=Store()),
                            iter=Name(lineno=55, col_offset=26, end_lineno=55, end_col_offset=31, id='added', ctx=Load()),
                            body=[
                                For(
                                    lineno=56,
                                    col_offset=12,
                                    end_lineno=67,
                                    end_col_offset=25,
                                    target=Name(lineno=56, col_offset=16, end_lineno=56, end_col_offset=22, id='driver', ctx=Store()),
                                    iter=Attribute(
                                        lineno=56,
                                        col_offset=26,
                                        end_lineno=56,
                                        end_col_offset=38,
                                        value=Name(lineno=56, col_offset=26, end_lineno=56, end_col_offset=30, id='self', ctx=Load()),
                                        attr='drivers',
                                        ctx=Load(),
                                    ),
                                    body=[
                                        If(
                                            lineno=57,
                                            col_offset=16,
                                            end_lineno=67,
                                            end_col_offset=25,
                                            test=Call(
                                                lineno=57,
                                                col_offset=19,
                                                end_lineno=57,
                                                end_col_offset=56,
                                                func=Attribute(
                                                    lineno=57,
                                                    col_offset=19,
                                                    end_lineno=57,
                                                    end_col_offset=35,
                                                    value=Name(lineno=57, col_offset=19, end_lineno=57, end_col_offset=25, id='driver', ctx=Load()),
                                                    attr='supported',
                                                    ctx=Load(),
                                                ),
                                                args=[
                                                    Subscript(
                                                        lineno=57,
                                                        col_offset=36,
                                                        end_lineno=57,
                                                        end_col_offset=55,
                                                        value=Name(lineno=57, col_offset=36, end_lineno=57, end_col_offset=43, id='devices', ctx=Load()),
                                                        slice=Name(lineno=57, col_offset=44, end_lineno=57, end_col_offset=54, id='identifier', ctx=Load()),
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                keywords=[],
                                            ),
                                            body=[
                                                Expr(
                                                    lineno=58,
                                                    col_offset=20,
                                                    end_lineno=58,
                                                    end_col_offset=74,
                                                    value=Call(
                                                        lineno=58,
                                                        col_offset=20,
                                                        end_lineno=58,
                                                        end_col_offset=74,
                                                        func=Attribute(
                                                            lineno=58,
                                                            col_offset=20,
                                                            end_lineno=58,
                                                            end_col_offset=32,
                                                            value=Name(lineno=58, col_offset=20, end_lineno=58, end_col_offset=27, id='_logger', ctx=Load()),
                                                            attr='info',
                                                            ctx=Load(),
                                                        ),
                                                        args=[
                                                            Constant(lineno=58, col_offset=33, end_lineno=58, end_col_offset=61, value='Device %s is now connected', kind=None),
                                                            Name(lineno=58, col_offset=63, end_lineno=58, end_col_offset=73, id='identifier', ctx=Load()),
                                                        ],
                                                        keywords=[],
                                                    ),
                                                ),
                                                Assign(
                                                    lineno=59,
                                                    col_offset=20,
                                                    end_lineno=59,
                                                    end_col_offset=63,
                                                    targets=[Name(lineno=59, col_offset=20, end_lineno=59, end_col_offset=21, id='d', ctx=Store())],
                                                    value=Call(
                                                        lineno=59,
                                                        col_offset=24,
                                                        end_lineno=59,
                                                        end_col_offset=63,
                                                        func=Name(lineno=59, col_offset=24, end_lineno=59, end_col_offset=30, id='driver', ctx=Load()),
                                                        args=[
                                                            Name(lineno=59, col_offset=31, end_lineno=59, end_col_offset=41, id='identifier', ctx=Load()),
                                                            Subscript(
                                                                lineno=59,
                                                                col_offset=43,
                                                                end_lineno=59,
                                                                end_col_offset=62,
                                                                value=Name(lineno=59, col_offset=43, end_lineno=59, end_col_offset=50, id='devices', ctx=Load()),
                                                                slice=Name(lineno=59, col_offset=51, end_lineno=59, end_col_offset=61, id='identifier', ctx=Load()),
                                                                ctx=Load(),
                                                            ),
                                                        ],
                                                        keywords=[],
                                                    ),
                                                    type_comment=None,
                                                ),
                                                Assign(
                                                    lineno=60,
                                                    col_offset=20,
                                                    end_lineno=60,
                                                    end_col_offset=35,
                                                    targets=[
                                                        Attribute(
                                                            lineno=60,
                                                            col_offset=20,
                                                            end_lineno=60,
                                                            end_col_offset=28,
                                                            value=Name(lineno=60, col_offset=20, end_lineno=60, end_col_offset=21, id='d', ctx=Load()),
                                                            attr='daemon',
                                                            ctx=Store(),
                                                        ),
                                                    ],
                                                    value=Constant(lineno=60, col_offset=31, end_lineno=60, end_col_offset=35, value=True, kind=None),
                                                    type_comment=None,
                                                ),
                                                Assign(
                                                    lineno=61,
                                                    col_offset=20,
                                                    end_lineno=61,
                                                    end_col_offset=47,
                                                    targets=[
                                                        Subscript(
                                                            lineno=61,
                                                            col_offset=20,
                                                            end_lineno=61,
                                                            end_col_offset=43,
                                                            value=Name(lineno=61, col_offset=20, end_lineno=61, end_col_offset=31, id='iot_devices', ctx=Load()),
                                                            slice=Name(lineno=61, col_offset=32, end_lineno=61, end_col_offset=42, id='identifier', ctx=Load()),
                                                            ctx=Store(),
                                                        ),
                                                    ],
                                                    value=Name(lineno=61, col_offset=46, end_lineno=61, end_col_offset=47, id='d', ctx=Load()),
                                                    type_comment=None,
                                                ),
                                                Expr(
                                                    lineno=66,
                                                    col_offset=20,
                                                    end_lineno=66,
                                                    end_col_offset=29,
                                                    value=Call(
                                                        lineno=66,
                                                        col_offset=20,
                                                        end_lineno=66,
                                                        end_col_offset=29,
                                                        func=Attribute(
                                                            lineno=66,
                                                            col_offset=20,
                                                            end_lineno=66,
                                                            end_col_offset=27,
                                                            value=Name(lineno=66, col_offset=20, end_lineno=66, end_col_offset=21, id='d', ctx=Load()),
                                                            attr='start',
                                                            ctx=Load(),
                                                        ),
                                                        args=[],
                                                        keywords=[],
                                                    ),
                                                ),
                                                Break(lineno=67, col_offset=20, end_lineno=67, end_col_offset=25),
                                            ],
                                            orelse=[],
                                        ),
                                    ],
                                    orelse=[],
                                    type_comment=None,
                                ),
                            ],
                            orelse=[],
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=69,
                    col_offset=4,
                    end_lineno=70,
                    end_col_offset=35,
                    name='get_devices',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=69, col_offset=20, end_lineno=69, end_col_offset=24, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Raise(
                            lineno=70,
                            col_offset=8,
                            end_lineno=70,
                            end_col_offset=35,
                            exc=Call(
                                lineno=70,
                                col_offset=14,
                                end_lineno=70,
                                end_col_offset=35,
                                func=Name(lineno=70, col_offset=14, end_lineno=70, end_col_offset=33, id='NotImplementedError', ctx=Load()),
                                args=[],
                                keywords=[],
                            ),
                            cause=None,
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
