Module(
    body=[
        ImportFrom(
            lineno=1,
            col_offset=0,
            end_lineno=1,
            end_col_offset=34,
            module='odoo',
            names=[
                alias(name='models', asname=None),
                alias(name='fields', asname=None),
                alias(name='_', asname=None),
            ],
            level=0,
        ),
        ImportFrom(
            lineno=2,
            col_offset=0,
            end_lineno=2,
            end_col_offset=37,
            module='odoo.exceptions',
            names=[alias(name='UserError', asname=None)],
            level=0,
        ),
        ClassDef(
            lineno=5,
            col_offset=0,
            end_lineno=23,
            end_col_offset=54,
            name='ValidateAccountMove',
            bases=[
                Attribute(
                    lineno=5,
                    col_offset=26,
                    end_lineno=5,
                    end_col_offset=47,
                    value=Name(lineno=5, col_offset=26, end_lineno=5, end_col_offset=32, id='models', ctx=Load()),
                    attr='TransientModel',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=6,
                    col_offset=4,
                    end_lineno=6,
                    end_col_offset=35,
                    targets=[Name(lineno=6, col_offset=4, end_lineno=6, end_col_offset=9, id='_name', ctx=Store())],
                    value=Constant(lineno=6, col_offset=12, end_lineno=6, end_col_offset=35, value='validate.account.move', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=7,
                    col_offset=4,
                    end_lineno=7,
                    end_col_offset=42,
                    targets=[Name(lineno=7, col_offset=4, end_lineno=7, end_col_offset=16, id='_description', ctx=Store())],
                    value=Constant(lineno=7, col_offset=19, end_lineno=7, end_col_offset=42, value='Validate Account Move', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=9,
                    col_offset=4,
                    end_lineno=9,
                    end_col_offset=153,
                    targets=[Name(lineno=9, col_offset=4, end_lineno=9, end_col_offset=14, id='force_post', ctx=Store())],
                    value=Call(
                        lineno=9,
                        col_offset=17,
                        end_lineno=9,
                        end_col_offset=153,
                        func=Attribute(
                            lineno=9,
                            col_offset=17,
                            end_lineno=9,
                            end_col_offset=31,
                            value=Name(lineno=9, col_offset=17, end_lineno=9, end_col_offset=23, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=9,
                                col_offset=32,
                                end_lineno=9,
                                end_col_offset=46,
                                arg='string',
                                value=Constant(lineno=9, col_offset=39, end_lineno=9, end_col_offset=46, value='Force', kind=None),
                            ),
                            keyword(
                                lineno=9,
                                col_offset=48,
                                end_lineno=9,
                                end_col_offset=152,
                                arg='help',
                                value=Constant(lineno=9, col_offset=53, end_lineno=9, end_col_offset=152, value='Entries in the future are set to be auto-posted by default. Check this checkbox to post them now.', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=11,
                    col_offset=4,
                    end_lineno=23,
                    end_col_offset=54,
                    name='validate_move',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=11, col_offset=22, end_lineno=11, end_col_offset=26, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        If(
                            lineno=12,
                            col_offset=8,
                            end_lineno=17,
                            end_col_offset=68,
                            test=Compare(
                                lineno=12,
                                col_offset=11,
                                end_lineno=12,
                                end_col_offset=62,
                                left=Call(
                                    lineno=12,
                                    col_offset=11,
                                    end_lineno=12,
                                    end_col_offset=44,
                                    func=Attribute(
                                        lineno=12,
                                        col_offset=11,
                                        end_lineno=12,
                                        end_col_offset=28,
                                        value=Attribute(
                                            lineno=12,
                                            col_offset=11,
                                            end_lineno=12,
                                            end_col_offset=24,
                                            value=Name(lineno=12, col_offset=11, end_lineno=12, end_col_offset=15, id='self', ctx=Load()),
                                            attr='_context',
                                            ctx=Load(),
                                        ),
                                        attr='get',
                                        ctx=Load(),
                                    ),
                                    args=[Constant(lineno=12, col_offset=29, end_lineno=12, end_col_offset=43, value='active_model', kind=None)],
                                    keywords=[],
                                ),
                                ops=[Eq()],
                                comparators=[Constant(lineno=12, col_offset=48, end_lineno=12, end_col_offset=62, value='account.move', kind=None)],
                            ),
                            body=[
                                Assign(
                                    lineno=13,
                                    col_offset=12,
                                    end_lineno=13,
                                    end_col_offset=97,
                                    targets=[Name(lineno=13, col_offset=12, end_lineno=13, end_col_offset=18, id='domain', ctx=Store())],
                                    value=List(
                                        lineno=13,
                                        col_offset=21,
                                        end_lineno=13,
                                        end_col_offset=97,
                                        elts=[
                                            Tuple(
                                                lineno=13,
                                                col_offset=22,
                                                end_lineno=13,
                                                end_col_offset=71,
                                                elts=[
                                                    Constant(lineno=13, col_offset=23, end_lineno=13, end_col_offset=27, value='id', kind=None),
                                                    Constant(lineno=13, col_offset=29, end_lineno=13, end_col_offset=33, value='in', kind=None),
                                                    Call(
                                                        lineno=13,
                                                        col_offset=35,
                                                        end_lineno=13,
                                                        end_col_offset=70,
                                                        func=Attribute(
                                                            lineno=13,
                                                            col_offset=35,
                                                            end_lineno=13,
                                                            end_col_offset=52,
                                                            value=Attribute(
                                                                lineno=13,
                                                                col_offset=35,
                                                                end_lineno=13,
                                                                end_col_offset=48,
                                                                value=Name(lineno=13, col_offset=35, end_lineno=13, end_col_offset=39, id='self', ctx=Load()),
                                                                attr='_context',
                                                                ctx=Load(),
                                                            ),
                                                            attr='get',
                                                            ctx=Load(),
                                                        ),
                                                        args=[
                                                            Constant(lineno=13, col_offset=53, end_lineno=13, end_col_offset=65, value='active_ids', kind=None),
                                                            List(lineno=13, col_offset=67, end_lineno=13, end_col_offset=69, elts=[], ctx=Load()),
                                                        ],
                                                        keywords=[],
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                            Tuple(
                                                lineno=13,
                                                col_offset=73,
                                                end_lineno=13,
                                                end_col_offset=96,
                                                elts=[
                                                    Constant(lineno=13, col_offset=74, end_lineno=13, end_col_offset=81, value='state', kind=None),
                                                    Constant(lineno=13, col_offset=83, end_lineno=13, end_col_offset=86, value='=', kind=None),
                                                    Constant(lineno=13, col_offset=88, end_lineno=13, end_col_offset=95, value='draft', kind=None),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[
                                If(
                                    lineno=14,
                                    col_offset=8,
                                    end_lineno=17,
                                    end_col_offset=68,
                                    test=Compare(
                                        lineno=14,
                                        col_offset=13,
                                        end_lineno=14,
                                        end_col_offset=67,
                                        left=Call(
                                            lineno=14,
                                            col_offset=13,
                                            end_lineno=14,
                                            end_col_offset=46,
                                            func=Attribute(
                                                lineno=14,
                                                col_offset=13,
                                                end_lineno=14,
                                                end_col_offset=30,
                                                value=Attribute(
                                                    lineno=14,
                                                    col_offset=13,
                                                    end_lineno=14,
                                                    end_col_offset=26,
                                                    value=Name(lineno=14, col_offset=13, end_lineno=14, end_col_offset=17, id='self', ctx=Load()),
                                                    attr='_context',
                                                    ctx=Load(),
                                                ),
                                                attr='get',
                                                ctx=Load(),
                                            ),
                                            args=[Constant(lineno=14, col_offset=31, end_lineno=14, end_col_offset=45, value='active_model', kind=None)],
                                            keywords=[],
                                        ),
                                        ops=[Eq()],
                                        comparators=[Constant(lineno=14, col_offset=50, end_lineno=14, end_col_offset=67, value='account.journal', kind=None)],
                                    ),
                                    body=[
                                        Assign(
                                            lineno=15,
                                            col_offset=12,
                                            end_lineno=15,
                                            end_col_offset=99,
                                            targets=[Name(lineno=15, col_offset=12, end_lineno=15, end_col_offset=18, id='domain', ctx=Store())],
                                            value=List(
                                                lineno=15,
                                                col_offset=21,
                                                end_lineno=15,
                                                end_col_offset=99,
                                                elts=[
                                                    Tuple(
                                                        lineno=15,
                                                        col_offset=22,
                                                        end_lineno=15,
                                                        end_col_offset=73,
                                                        elts=[
                                                            Constant(lineno=15, col_offset=23, end_lineno=15, end_col_offset=35, value='journal_id', kind=None),
                                                            Constant(lineno=15, col_offset=37, end_lineno=15, end_col_offset=40, value='=', kind=None),
                                                            Call(
                                                                lineno=15,
                                                                col_offset=42,
                                                                end_lineno=15,
                                                                end_col_offset=72,
                                                                func=Attribute(
                                                                    lineno=15,
                                                                    col_offset=42,
                                                                    end_lineno=15,
                                                                    end_col_offset=59,
                                                                    value=Attribute(
                                                                        lineno=15,
                                                                        col_offset=42,
                                                                        end_lineno=15,
                                                                        end_col_offset=55,
                                                                        value=Name(lineno=15, col_offset=42, end_lineno=15, end_col_offset=46, id='self', ctx=Load()),
                                                                        attr='_context',
                                                                        ctx=Load(),
                                                                    ),
                                                                    attr='get',
                                                                    ctx=Load(),
                                                                ),
                                                                args=[Constant(lineno=15, col_offset=60, end_lineno=15, end_col_offset=71, value='active_id', kind=None)],
                                                                keywords=[],
                                                            ),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                    Tuple(
                                                        lineno=15,
                                                        col_offset=75,
                                                        end_lineno=15,
                                                        end_col_offset=98,
                                                        elts=[
                                                            Constant(lineno=15, col_offset=76, end_lineno=15, end_col_offset=83, value='state', kind=None),
                                                            Constant(lineno=15, col_offset=85, end_lineno=15, end_col_offset=88, value='=', kind=None),
                                                            Constant(lineno=15, col_offset=90, end_lineno=15, end_col_offset=97, value='draft', kind=None),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                            type_comment=None,
                                        ),
                                    ],
                                    orelse=[
                                        Raise(
                                            lineno=17,
                                            col_offset=12,
                                            end_lineno=17,
                                            end_col_offset=68,
                                            exc=Call(
                                                lineno=17,
                                                col_offset=18,
                                                end_lineno=17,
                                                end_col_offset=68,
                                                func=Name(lineno=17, col_offset=18, end_lineno=17, end_col_offset=27, id='UserError', ctx=Load()),
                                                args=[
                                                    Call(
                                                        lineno=17,
                                                        col_offset=28,
                                                        end_lineno=17,
                                                        end_col_offset=67,
                                                        func=Name(lineno=17, col_offset=28, end_lineno=17, end_col_offset=29, id='_', ctx=Load()),
                                                        args=[Constant(lineno=17, col_offset=30, end_lineno=17, end_col_offset=66, value="Missing 'active_model' in context.", kind=None)],
                                                        keywords=[],
                                                    ),
                                                ],
                                                keywords=[],
                                            ),
                                            cause=None,
                                        ),
                                    ],
                                ),
                            ],
                        ),
                        Assign(
                            lineno=19,
                            col_offset=8,
                            end_lineno=19,
                            end_col_offset=76,
                            targets=[Name(lineno=19, col_offset=8, end_lineno=19, end_col_offset=13, id='moves', ctx=Store())],
                            value=Call(
                                lineno=19,
                                col_offset=16,
                                end_lineno=19,
                                end_col_offset=76,
                                func=Attribute(
                                    lineno=19,
                                    col_offset=16,
                                    end_lineno=19,
                                    end_col_offset=64,
                                    value=Call(
                                        lineno=19,
                                        col_offset=16,
                                        end_lineno=19,
                                        end_col_offset=55,
                                        func=Attribute(
                                            lineno=19,
                                            col_offset=16,
                                            end_lineno=19,
                                            end_col_offset=47,
                                            value=Subscript(
                                                lineno=19,
                                                col_offset=16,
                                                end_lineno=19,
                                                end_col_offset=40,
                                                value=Attribute(
                                                    lineno=19,
                                                    col_offset=16,
                                                    end_lineno=19,
                                                    end_col_offset=24,
                                                    value=Name(lineno=19, col_offset=16, end_lineno=19, end_col_offset=20, id='self', ctx=Load()),
                                                    attr='env',
                                                    ctx=Load(),
                                                ),
                                                slice=Constant(lineno=19, col_offset=25, end_lineno=19, end_col_offset=39, value='account.move', kind=None),
                                                ctx=Load(),
                                            ),
                                            attr='search',
                                            ctx=Load(),
                                        ),
                                        args=[Name(lineno=19, col_offset=48, end_lineno=19, end_col_offset=54, id='domain', ctx=Load())],
                                        keywords=[],
                                    ),
                                    attr='filtered',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=19, col_offset=65, end_lineno=19, end_col_offset=75, value='line_ids', kind=None)],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        If(
                            lineno=20,
                            col_offset=8,
                            end_lineno=21,
                            end_col_offset=88,
                            test=UnaryOp(
                                lineno=20,
                                col_offset=11,
                                end_lineno=20,
                                end_col_offset=20,
                                op=Not(),
                                operand=Name(lineno=20, col_offset=15, end_lineno=20, end_col_offset=20, id='moves', ctx=Load()),
                            ),
                            body=[
                                Raise(
                                    lineno=21,
                                    col_offset=12,
                                    end_lineno=21,
                                    end_col_offset=88,
                                    exc=Call(
                                        lineno=21,
                                        col_offset=18,
                                        end_lineno=21,
                                        end_col_offset=88,
                                        func=Name(lineno=21, col_offset=18, end_lineno=21, end_col_offset=27, id='UserError', ctx=Load()),
                                        args=[
                                            Call(
                                                lineno=21,
                                                col_offset=28,
                                                end_lineno=21,
                                                end_col_offset=87,
                                                func=Name(lineno=21, col_offset=28, end_lineno=21, end_col_offset=29, id='_', ctx=Load()),
                                                args=[Constant(lineno=21, col_offset=30, end_lineno=21, end_col_offset=86, value='There are no journal items in the draft state to post.', kind=None)],
                                                keywords=[],
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                    cause=None,
                                ),
                            ],
                            orelse=[],
                        ),
                        Expr(
                            lineno=22,
                            col_offset=8,
                            end_lineno=22,
                            end_col_offset=40,
                            value=Call(
                                lineno=22,
                                col_offset=8,
                                end_lineno=22,
                                end_col_offset=40,
                                func=Attribute(
                                    lineno=22,
                                    col_offset=8,
                                    end_lineno=22,
                                    end_col_offset=19,
                                    value=Name(lineno=22, col_offset=8, end_lineno=22, end_col_offset=13, id='moves', ctx=Load()),
                                    attr='_post',
                                    ctx=Load(),
                                ),
                                args=[
                                    UnaryOp(
                                        lineno=22,
                                        col_offset=20,
                                        end_lineno=22,
                                        end_col_offset=39,
                                        op=Not(),
                                        operand=Attribute(
                                            lineno=22,
                                            col_offset=24,
                                            end_lineno=22,
                                            end_col_offset=39,
                                            value=Name(lineno=22, col_offset=24, end_lineno=22, end_col_offset=28, id='self', ctx=Load()),
                                            attr='force_post',
                                            ctx=Load(),
                                        ),
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Return(
                            lineno=23,
                            col_offset=8,
                            end_lineno=23,
                            end_col_offset=54,
                            value=Dict(
                                lineno=23,
                                col_offset=15,
                                end_lineno=23,
                                end_col_offset=54,
                                keys=[Constant(lineno=23, col_offset=16, end_lineno=23, end_col_offset=22, value='type', kind=None)],
                                values=[Constant(lineno=23, col_offset=24, end_lineno=23, end_col_offset=53, value='ir.actions.act_window_close', kind=None)],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
