Module(
    body=[
        Import(
            lineno=2,
            col_offset=0,
            end_lineno=2,
            end_col_offset=17,
            names=[alias(name='odoo.tests', asname=None)],
        ),
        ClassDef(
            lineno=6,
            col_offset=0,
            end_lineno=31,
            end_col_offset=76,
            name='TestWebsiteControllerArgs',
            bases=[
                Attribute(
                    lineno=6,
                    col_offset=32,
                    end_lineno=6,
                    end_col_offset=51,
                    value=Attribute(
                        lineno=6,
                        col_offset=32,
                        end_lineno=6,
                        end_col_offset=42,
                        value=Name(lineno=6, col_offset=32, end_lineno=6, end_col_offset=36, id='odoo', ctx=Load()),
                        attr='tests',
                        ctx=Load(),
                    ),
                    attr='HttpCase',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                FunctionDef(
                    lineno=8,
                    col_offset=4,
                    end_lineno=31,
                    end_col_offset=76,
                    name='test_crawl_args',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=8, col_offset=24, end_lineno=8, end_col_offset=28, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=9,
                            col_offset=8,
                            end_lineno=9,
                            end_col_offset=79,
                            targets=[Name(lineno=9, col_offset=8, end_lineno=9, end_col_offset=11, id='req', ctx=Store())],
                            value=Call(
                                lineno=9,
                                col_offset=14,
                                end_lineno=9,
                                end_col_offset=79,
                                func=Attribute(
                                    lineno=9,
                                    col_offset=14,
                                    end_lineno=9,
                                    end_col_offset=27,
                                    value=Name(lineno=9, col_offset=14, end_lineno=9, end_col_offset=18, id='self', ctx=Load()),
                                    attr='url_open',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=9, col_offset=28, end_lineno=9, end_col_offset=78, value='/ignore_args/converter/valueA/?b=valueB&c=valueC', kind=None)],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=10,
                            col_offset=8,
                            end_lineno=10,
                            end_col_offset=46,
                            value=Call(
                                lineno=10,
                                col_offset=8,
                                end_lineno=10,
                                end_col_offset=46,
                                func=Attribute(
                                    lineno=10,
                                    col_offset=8,
                                    end_lineno=10,
                                    end_col_offset=24,
                                    value=Name(lineno=10, col_offset=8, end_lineno=10, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=10,
                                        col_offset=25,
                                        end_lineno=10,
                                        end_col_offset=40,
                                        value=Name(lineno=10, col_offset=25, end_lineno=10, end_col_offset=28, id='req', ctx=Load()),
                                        attr='status_code',
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=10, col_offset=42, end_lineno=10, end_col_offset=45, value=200, kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=11,
                            col_offset=8,
                            end_lineno=11,
                            end_col_offset=91,
                            value=Call(
                                lineno=11,
                                col_offset=8,
                                end_lineno=11,
                                end_col_offset=91,
                                func=Attribute(
                                    lineno=11,
                                    col_offset=8,
                                    end_lineno=11,
                                    end_col_offset=24,
                                    value=Name(lineno=11, col_offset=8, end_lineno=11, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Call(
                                        lineno=11,
                                        col_offset=25,
                                        end_lineno=11,
                                        end_col_offset=35,
                                        func=Attribute(
                                            lineno=11,
                                            col_offset=25,
                                            end_lineno=11,
                                            end_col_offset=33,
                                            value=Name(lineno=11, col_offset=25, end_lineno=11, end_col_offset=28, id='req', ctx=Load()),
                                            attr='json',
                                            ctx=Load(),
                                        ),
                                        args=[],
                                        keywords=[],
                                    ),
                                    Dict(
                                        lineno=11,
                                        col_offset=37,
                                        end_lineno=11,
                                        end_col_offset=90,
                                        keys=[
                                            Constant(lineno=11, col_offset=38, end_lineno=11, end_col_offset=41, value='a', kind=None),
                                            Constant(lineno=11, col_offset=53, end_lineno=11, end_col_offset=56, value='b', kind=None),
                                            Constant(lineno=11, col_offset=68, end_lineno=11, end_col_offset=72, value='kw', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=11, col_offset=43, end_lineno=11, end_col_offset=51, value='valueA', kind=None),
                                            Constant(lineno=11, col_offset=58, end_lineno=11, end_col_offset=66, value='valueB', kind=None),
                                            Dict(
                                                lineno=11,
                                                col_offset=74,
                                                end_lineno=11,
                                                end_col_offset=89,
                                                keys=[Constant(lineno=11, col_offset=75, end_lineno=11, end_col_offset=78, value='c', kind=None)],
                                                values=[Constant(lineno=11, col_offset=80, end_lineno=11, end_col_offset=88, value='valueC', kind=None)],
                                            ),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=13,
                            col_offset=8,
                            end_lineno=13,
                            end_col_offset=83,
                            targets=[Name(lineno=13, col_offset=8, end_lineno=13, end_col_offset=11, id='req', ctx=Store())],
                            value=Call(
                                lineno=13,
                                col_offset=14,
                                end_lineno=13,
                                end_col_offset=83,
                                func=Attribute(
                                    lineno=13,
                                    col_offset=14,
                                    end_lineno=13,
                                    end_col_offset=27,
                                    value=Name(lineno=13, col_offset=14, end_lineno=13, end_col_offset=18, id='self', ctx=Load()),
                                    attr='url_open',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=13, col_offset=28, end_lineno=13, end_col_offset=82, value='/ignore_args/converter/valueA/nokw?b=valueB&c=valueC', kind=None)],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=14,
                            col_offset=8,
                            end_lineno=14,
                            end_col_offset=46,
                            value=Call(
                                lineno=14,
                                col_offset=8,
                                end_lineno=14,
                                end_col_offset=46,
                                func=Attribute(
                                    lineno=14,
                                    col_offset=8,
                                    end_lineno=14,
                                    end_col_offset=24,
                                    value=Name(lineno=14, col_offset=8, end_lineno=14, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=14,
                                        col_offset=25,
                                        end_lineno=14,
                                        end_col_offset=40,
                                        value=Name(lineno=14, col_offset=25, end_lineno=14, end_col_offset=28, id='req', ctx=Load()),
                                        attr='status_code',
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=14, col_offset=42, end_lineno=14, end_col_offset=45, value=200, kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=15,
                            col_offset=8,
                            end_lineno=15,
                            end_col_offset=68,
                            value=Call(
                                lineno=15,
                                col_offset=8,
                                end_lineno=15,
                                end_col_offset=68,
                                func=Attribute(
                                    lineno=15,
                                    col_offset=8,
                                    end_lineno=15,
                                    end_col_offset=24,
                                    value=Name(lineno=15, col_offset=8, end_lineno=15, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Call(
                                        lineno=15,
                                        col_offset=25,
                                        end_lineno=15,
                                        end_col_offset=35,
                                        func=Attribute(
                                            lineno=15,
                                            col_offset=25,
                                            end_lineno=15,
                                            end_col_offset=33,
                                            value=Name(lineno=15, col_offset=25, end_lineno=15, end_col_offset=28, id='req', ctx=Load()),
                                            attr='json',
                                            ctx=Load(),
                                        ),
                                        args=[],
                                        keywords=[],
                                    ),
                                    Dict(
                                        lineno=15,
                                        col_offset=37,
                                        end_lineno=15,
                                        end_col_offset=67,
                                        keys=[
                                            Constant(lineno=15, col_offset=38, end_lineno=15, end_col_offset=41, value='a', kind=None),
                                            Constant(lineno=15, col_offset=53, end_lineno=15, end_col_offset=56, value='b', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=15, col_offset=43, end_lineno=15, end_col_offset=51, value='valueA', kind=None),
                                            Constant(lineno=15, col_offset=58, end_lineno=15, end_col_offset=66, value='valueB', kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=17,
                            col_offset=8,
                            end_lineno=17,
                            end_col_offset=83,
                            targets=[Name(lineno=17, col_offset=8, end_lineno=17, end_col_offset=11, id='req', ctx=Store())],
                            value=Call(
                                lineno=17,
                                col_offset=14,
                                end_lineno=17,
                                end_col_offset=83,
                                func=Attribute(
                                    lineno=17,
                                    col_offset=14,
                                    end_lineno=17,
                                    end_col_offset=27,
                                    value=Name(lineno=17, col_offset=14, end_lineno=17, end_col_offset=18, id='self', ctx=Load()),
                                    attr='url_open',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=17, col_offset=28, end_lineno=17, end_col_offset=82, value='/ignore_args/converteronly/valueA/?b=valueB&c=valueC', kind=None)],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=18,
                            col_offset=8,
                            end_lineno=18,
                            end_col_offset=46,
                            value=Call(
                                lineno=18,
                                col_offset=8,
                                end_lineno=18,
                                end_col_offset=46,
                                func=Attribute(
                                    lineno=18,
                                    col_offset=8,
                                    end_lineno=18,
                                    end_col_offset=24,
                                    value=Name(lineno=18, col_offset=8, end_lineno=18, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=18,
                                        col_offset=25,
                                        end_lineno=18,
                                        end_col_offset=40,
                                        value=Name(lineno=18, col_offset=25, end_lineno=18, end_col_offset=28, id='req', ctx=Load()),
                                        attr='status_code',
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=18, col_offset=42, end_lineno=18, end_col_offset=45, value=200, kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=19,
                            col_offset=8,
                            end_lineno=19,
                            end_col_offset=65,
                            value=Call(
                                lineno=19,
                                col_offset=8,
                                end_lineno=19,
                                end_col_offset=65,
                                func=Attribute(
                                    lineno=19,
                                    col_offset=8,
                                    end_lineno=19,
                                    end_col_offset=24,
                                    value=Name(lineno=19, col_offset=8, end_lineno=19, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Call(
                                        lineno=19,
                                        col_offset=25,
                                        end_lineno=19,
                                        end_col_offset=35,
                                        func=Attribute(
                                            lineno=19,
                                            col_offset=25,
                                            end_lineno=19,
                                            end_col_offset=33,
                                            value=Name(lineno=19, col_offset=25, end_lineno=19, end_col_offset=28, id='req', ctx=Load()),
                                            attr='json',
                                            ctx=Load(),
                                        ),
                                        args=[],
                                        keywords=[],
                                    ),
                                    Dict(
                                        lineno=19,
                                        col_offset=37,
                                        end_lineno=19,
                                        end_col_offset=64,
                                        keys=[
                                            Constant(lineno=19, col_offset=38, end_lineno=19, end_col_offset=41, value='a', kind=None),
                                            Constant(lineno=19, col_offset=53, end_lineno=19, end_col_offset=57, value='kw', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=19, col_offset=43, end_lineno=19, end_col_offset=51, value='valueA', kind=None),
                                            Constant(lineno=19, col_offset=59, end_lineno=19, end_col_offset=63, value=None, kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=21,
                            col_offset=8,
                            end_lineno=21,
                            end_col_offset=66,
                            targets=[Name(lineno=21, col_offset=8, end_lineno=21, end_col_offset=11, id='req', ctx=Store())],
                            value=Call(
                                lineno=21,
                                col_offset=14,
                                end_lineno=21,
                                end_col_offset=66,
                                func=Attribute(
                                    lineno=21,
                                    col_offset=14,
                                    end_lineno=21,
                                    end_col_offset=27,
                                    value=Name(lineno=21, col_offset=14, end_lineno=21, end_col_offset=18, id='self', ctx=Load()),
                                    attr='url_open',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=21, col_offset=28, end_lineno=21, end_col_offset=65, value='/ignore_args/none?a=valueA&b=valueB', kind=None)],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=22,
                            col_offset=8,
                            end_lineno=22,
                            end_col_offset=46,
                            value=Call(
                                lineno=22,
                                col_offset=8,
                                end_lineno=22,
                                end_col_offset=46,
                                func=Attribute(
                                    lineno=22,
                                    col_offset=8,
                                    end_lineno=22,
                                    end_col_offset=24,
                                    value=Name(lineno=22, col_offset=8, end_lineno=22, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=22,
                                        col_offset=25,
                                        end_lineno=22,
                                        end_col_offset=40,
                                        value=Name(lineno=22, col_offset=25, end_lineno=22, end_col_offset=28, id='req', ctx=Load()),
                                        attr='status_code',
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=22, col_offset=42, end_lineno=22, end_col_offset=45, value=200, kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=23,
                            col_offset=8,
                            end_lineno=23,
                            end_col_offset=61,
                            value=Call(
                                lineno=23,
                                col_offset=8,
                                end_lineno=23,
                                end_col_offset=61,
                                func=Attribute(
                                    lineno=23,
                                    col_offset=8,
                                    end_lineno=23,
                                    end_col_offset=24,
                                    value=Name(lineno=23, col_offset=8, end_lineno=23, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Call(
                                        lineno=23,
                                        col_offset=25,
                                        end_lineno=23,
                                        end_col_offset=35,
                                        func=Attribute(
                                            lineno=23,
                                            col_offset=25,
                                            end_lineno=23,
                                            end_col_offset=33,
                                            value=Name(lineno=23, col_offset=25, end_lineno=23, end_col_offset=28, id='req', ctx=Load()),
                                            attr='json',
                                            ctx=Load(),
                                        ),
                                        args=[],
                                        keywords=[],
                                    ),
                                    Dict(
                                        lineno=23,
                                        col_offset=37,
                                        end_lineno=23,
                                        end_col_offset=60,
                                        keys=[
                                            Constant(lineno=23, col_offset=38, end_lineno=23, end_col_offset=41, value='a', kind=None),
                                            Constant(lineno=23, col_offset=49, end_lineno=23, end_col_offset=53, value='kw', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=23, col_offset=43, end_lineno=23, end_col_offset=47, value=None, kind=None),
                                            Constant(lineno=23, col_offset=55, end_lineno=23, end_col_offset=59, value=None, kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=25,
                            col_offset=8,
                            end_lineno=25,
                            end_col_offset=63,
                            targets=[Name(lineno=25, col_offset=8, end_lineno=25, end_col_offset=11, id='req', ctx=Store())],
                            value=Call(
                                lineno=25,
                                col_offset=14,
                                end_lineno=25,
                                end_col_offset=63,
                                func=Attribute(
                                    lineno=25,
                                    col_offset=14,
                                    end_lineno=25,
                                    end_col_offset=27,
                                    value=Name(lineno=25, col_offset=14, end_lineno=25, end_col_offset=18, id='self', ctx=Load()),
                                    attr='url_open',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=25, col_offset=28, end_lineno=25, end_col_offset=62, value='/ignore_args/a?a=valueA&b=valueB', kind=None)],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=26,
                            col_offset=8,
                            end_lineno=26,
                            end_col_offset=46,
                            value=Call(
                                lineno=26,
                                col_offset=8,
                                end_lineno=26,
                                end_col_offset=46,
                                func=Attribute(
                                    lineno=26,
                                    col_offset=8,
                                    end_lineno=26,
                                    end_col_offset=24,
                                    value=Name(lineno=26, col_offset=8, end_lineno=26, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=26,
                                        col_offset=25,
                                        end_lineno=26,
                                        end_col_offset=40,
                                        value=Name(lineno=26, col_offset=25, end_lineno=26, end_col_offset=28, id='req', ctx=Load()),
                                        attr='status_code',
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=26, col_offset=42, end_lineno=26, end_col_offset=45, value=200, kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=27,
                            col_offset=8,
                            end_lineno=27,
                            end_col_offset=65,
                            value=Call(
                                lineno=27,
                                col_offset=8,
                                end_lineno=27,
                                end_col_offset=65,
                                func=Attribute(
                                    lineno=27,
                                    col_offset=8,
                                    end_lineno=27,
                                    end_col_offset=24,
                                    value=Name(lineno=27, col_offset=8, end_lineno=27, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Call(
                                        lineno=27,
                                        col_offset=25,
                                        end_lineno=27,
                                        end_col_offset=35,
                                        func=Attribute(
                                            lineno=27,
                                            col_offset=25,
                                            end_lineno=27,
                                            end_col_offset=33,
                                            value=Name(lineno=27, col_offset=25, end_lineno=27, end_col_offset=28, id='req', ctx=Load()),
                                            attr='json',
                                            ctx=Load(),
                                        ),
                                        args=[],
                                        keywords=[],
                                    ),
                                    Dict(
                                        lineno=27,
                                        col_offset=37,
                                        end_lineno=27,
                                        end_col_offset=64,
                                        keys=[
                                            Constant(lineno=27, col_offset=38, end_lineno=27, end_col_offset=41, value='a', kind=None),
                                            Constant(lineno=27, col_offset=53, end_lineno=27, end_col_offset=57, value='kw', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=27, col_offset=43, end_lineno=27, end_col_offset=51, value='valueA', kind=None),
                                            Constant(lineno=27, col_offset=59, end_lineno=27, end_col_offset=63, value=None, kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=29,
                            col_offset=8,
                            end_lineno=29,
                            end_col_offset=64,
                            targets=[Name(lineno=29, col_offset=8, end_lineno=29, end_col_offset=11, id='req', ctx=Store())],
                            value=Call(
                                lineno=29,
                                col_offset=14,
                                end_lineno=29,
                                end_col_offset=64,
                                func=Attribute(
                                    lineno=29,
                                    col_offset=14,
                                    end_lineno=29,
                                    end_col_offset=27,
                                    value=Name(lineno=29, col_offset=14, end_lineno=29, end_col_offset=18, id='self', ctx=Load()),
                                    attr='url_open',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=29, col_offset=28, end_lineno=29, end_col_offset=63, value='/ignore_args/kw?a=valueA&b=valueB', kind=None)],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=30,
                            col_offset=8,
                            end_lineno=30,
                            end_col_offset=46,
                            value=Call(
                                lineno=30,
                                col_offset=8,
                                end_lineno=30,
                                end_col_offset=46,
                                func=Attribute(
                                    lineno=30,
                                    col_offset=8,
                                    end_lineno=30,
                                    end_col_offset=24,
                                    value=Name(lineno=30, col_offset=8, end_lineno=30, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=30,
                                        col_offset=25,
                                        end_lineno=30,
                                        end_col_offset=40,
                                        value=Name(lineno=30, col_offset=25, end_lineno=30, end_col_offset=28, id='req', ctx=Load()),
                                        attr='status_code',
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=30, col_offset=42, end_lineno=30, end_col_offset=45, value=200, kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=31,
                            col_offset=8,
                            end_lineno=31,
                            end_col_offset=76,
                            value=Call(
                                lineno=31,
                                col_offset=8,
                                end_lineno=31,
                                end_col_offset=76,
                                func=Attribute(
                                    lineno=31,
                                    col_offset=8,
                                    end_lineno=31,
                                    end_col_offset=24,
                                    value=Name(lineno=31, col_offset=8, end_lineno=31, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Call(
                                        lineno=31,
                                        col_offset=25,
                                        end_lineno=31,
                                        end_col_offset=35,
                                        func=Attribute(
                                            lineno=31,
                                            col_offset=25,
                                            end_lineno=31,
                                            end_col_offset=33,
                                            value=Name(lineno=31, col_offset=25, end_lineno=31, end_col_offset=28, id='req', ctx=Load()),
                                            attr='json',
                                            ctx=Load(),
                                        ),
                                        args=[],
                                        keywords=[],
                                    ),
                                    Dict(
                                        lineno=31,
                                        col_offset=37,
                                        end_lineno=31,
                                        end_col_offset=75,
                                        keys=[
                                            Constant(lineno=31, col_offset=38, end_lineno=31, end_col_offset=41, value='a', kind=None),
                                            Constant(lineno=31, col_offset=53, end_lineno=31, end_col_offset=57, value='kw', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=31, col_offset=43, end_lineno=31, end_col_offset=51, value='valueA', kind=None),
                                            Dict(
                                                lineno=31,
                                                col_offset=59,
                                                end_lineno=31,
                                                end_col_offset=74,
                                                keys=[Constant(lineno=31, col_offset=60, end_lineno=31, end_col_offset=63, value='b', kind=None)],
                                                values=[Constant(lineno=31, col_offset=65, end_lineno=31, end_col_offset=73, value='valueB', kind=None)],
                                            ),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[
                Call(
                    lineno=5,
                    col_offset=1,
                    end_lineno=5,
                    end_col_offset=56,
                    func=Attribute(
                        lineno=5,
                        col_offset=1,
                        end_lineno=5,
                        end_col_offset=25,
                        value=Attribute(
                            lineno=5,
                            col_offset=1,
                            end_lineno=5,
                            end_col_offset=18,
                            value=Attribute(
                                lineno=5,
                                col_offset=1,
                                end_lineno=5,
                                end_col_offset=11,
                                value=Name(lineno=5, col_offset=1, end_lineno=5, end_col_offset=5, id='odoo', ctx=Load()),
                                attr='tests',
                                ctx=Load(),
                            ),
                            attr='common',
                            ctx=Load(),
                        ),
                        attr='tagged',
                        ctx=Load(),
                    ),
                    args=[
                        Constant(lineno=5, col_offset=26, end_lineno=5, end_col_offset=40, value='post_install', kind=None),
                        Constant(lineno=5, col_offset=42, end_lineno=5, end_col_offset=55, value='-at_install', kind=None),
                    ],
                    keywords=[],
                ),
            ],
        ),
    ],
    type_ignores=[],
)
