Module(
    body=[
        ImportFrom(
            lineno=3,
            col_offset=0,
            end_lineno=3,
            end_col_offset=33,
            module='freezegun',
            names=[alias(name='freeze_time', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=5,
            col_offset=0,
            end_lineno=5,
            end_col_offset=29,
            module='odoo.tests',
            names=[alias(name='tagged', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=6,
            col_offset=0,
            end_lineno=6,
            end_col_offset=80,
            module='odoo.addons.project.tests.test_project_update_flow',
            names=[alias(name='TestProjectUpdate', asname=None)],
            level=0,
        ),
        ClassDef(
            lineno=9,
            col_offset=0,
            end_lineno=31,
            end_col_offset=156,
            name='TestProjectUpdateSaleTimesheet',
            bases=[Name(lineno=9, col_offset=37, end_lineno=9, end_col_offset=54, id='TestProjectUpdate', ctx=Load())],
            keywords=[],
            body=[
                FunctionDef(
                    lineno=11,
                    col_offset=4,
                    end_lineno=18,
                    end_col_offset=149,
                    name='test_project_update_description_profitability',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=11, col_offset=54, end_lineno=11, end_col_offset=58, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=12,
                            col_offset=8,
                            end_lineno=12,
                            end_col_offset=47,
                            targets=[
                                Attribute(
                                    lineno=12,
                                    col_offset=8,
                                    end_lineno=12,
                                    end_col_offset=40,
                                    value=Attribute(
                                        lineno=12,
                                        col_offset=8,
                                        end_lineno=12,
                                        end_col_offset=25,
                                        value=Name(lineno=12, col_offset=8, end_lineno=12, end_col_offset=12, id='self', ctx=Load()),
                                        attr='project_pigs',
                                        ctx=Load(),
                                    ),
                                    attr='allow_billable',
                                    ctx=Store(),
                                ),
                            ],
                            value=Constant(lineno=12, col_offset=43, end_lineno=12, end_col_offset=47, value=True, kind=None),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=13,
                            col_offset=8,
                            end_lineno=13,
                            end_col_offset=92,
                            targets=[Name(lineno=13, col_offset=8, end_lineno=13, end_col_offset=23, id='template_values', ctx=Store())],
                            value=Call(
                                lineno=13,
                                col_offset=26,
                                end_lineno=13,
                                end_col_offset=92,
                                func=Attribute(
                                    lineno=13,
                                    col_offset=26,
                                    end_lineno=13,
                                    end_col_offset=73,
                                    value=Subscript(
                                        lineno=13,
                                        col_offset=26,
                                        end_lineno=13,
                                        end_col_offset=52,
                                        value=Attribute(
                                            lineno=13,
                                            col_offset=26,
                                            end_lineno=13,
                                            end_col_offset=34,
                                            value=Name(lineno=13, col_offset=26, end_lineno=13, end_col_offset=30, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=13, col_offset=35, end_lineno=13, end_col_offset=51, value='project.update', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='_get_template_values',
                                    ctx=Load(),
                                ),
                                args=[
                                    Attribute(
                                        lineno=13,
                                        col_offset=74,
                                        end_lineno=13,
                                        end_col_offset=91,
                                        value=Name(lineno=13, col_offset=74, end_lineno=13, end_col_offset=78, id='self', ctx=Load()),
                                        attr='project_pigs',
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=14,
                            col_offset=8,
                            end_lineno=14,
                            end_col_offset=141,
                            value=Call(
                                lineno=14,
                                col_offset=8,
                                end_lineno=14,
                                end_col_offset=141,
                                func=Attribute(
                                    lineno=14,
                                    col_offset=8,
                                    end_lineno=14,
                                    end_col_offset=24,
                                    value=Name(lineno=14, col_offset=8, end_lineno=14, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Subscript(
                                        lineno=14,
                                        col_offset=25,
                                        end_lineno=14,
                                        end_col_offset=66,
                                        value=Subscript(
                                            lineno=14,
                                            col_offset=25,
                                            end_lineno=14,
                                            end_col_offset=57,
                                            value=Name(lineno=14, col_offset=25, end_lineno=14, end_col_offset=40, id='template_values', ctx=Load()),
                                            slice=Constant(lineno=14, col_offset=41, end_lineno=14, end_col_offset=56, value='profitability', kind=None),
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=14, col_offset=58, end_lineno=14, end_col_offset=65, value='costs', kind=None),
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=14, col_offset=68, end_lineno=14, end_col_offset=79, value='$\xa00.00', kind=None),
                                    Constant(lineno=14, col_offset=81, end_lineno=14, end_col_offset=140, value='Project costs used in the template should be well defined', kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=15,
                            col_offset=8,
                            end_lineno=15,
                            end_col_offset=147,
                            value=Call(
                                lineno=15,
                                col_offset=8,
                                end_lineno=15,
                                end_col_offset=147,
                                func=Attribute(
                                    lineno=15,
                                    col_offset=8,
                                    end_lineno=15,
                                    end_col_offset=24,
                                    value=Name(lineno=15, col_offset=8, end_lineno=15, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Subscript(
                                        lineno=15,
                                        col_offset=25,
                                        end_lineno=15,
                                        end_col_offset=69,
                                        value=Subscript(
                                            lineno=15,
                                            col_offset=25,
                                            end_lineno=15,
                                            end_col_offset=57,
                                            value=Name(lineno=15, col_offset=25, end_lineno=15, end_col_offset=40, id='template_values', ctx=Load()),
                                            slice=Constant(lineno=15, col_offset=41, end_lineno=15, end_col_offset=56, value='profitability', kind=None),
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=15, col_offset=58, end_lineno=15, end_col_offset=68, value='revenues', kind=None),
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=15, col_offset=71, end_lineno=15, end_col_offset=82, value='$\xa00.00', kind=None),
                                    Constant(lineno=15, col_offset=84, end_lineno=15, end_col_offset=146, value='Project revenues used in the template should be well defined', kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=16,
                            col_offset=8,
                            end_lineno=16,
                            end_col_offset=125,
                            value=Call(
                                lineno=16,
                                col_offset=8,
                                end_lineno=16,
                                end_col_offset=125,
                                func=Attribute(
                                    lineno=16,
                                    col_offset=8,
                                    end_lineno=16,
                                    end_col_offset=24,
                                    value=Name(lineno=16, col_offset=8, end_lineno=16, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Subscript(
                                        lineno=16,
                                        col_offset=25,
                                        end_lineno=16,
                                        end_col_offset=67,
                                        value=Subscript(
                                            lineno=16,
                                            col_offset=25,
                                            end_lineno=16,
                                            end_col_offset=57,
                                            value=Name(lineno=16, col_offset=25, end_lineno=16, end_col_offset=40, id='template_values', ctx=Load()),
                                            slice=Constant(lineno=16, col_offset=41, end_lineno=16, end_col_offset=56, value='profitability', kind=None),
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=16, col_offset=58, end_lineno=16, end_col_offset=66, value='margin', kind=None),
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=16, col_offset=69, end_lineno=16, end_col_offset=70, value=0, kind=None),
                                    Constant(lineno=16, col_offset=72, end_lineno=16, end_col_offset=124, value='Margin used in the template should be well defined', kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=17,
                            col_offset=8,
                            end_lineno=17,
                            end_col_offset=155,
                            value=Call(
                                lineno=17,
                                col_offset=8,
                                end_lineno=17,
                                end_col_offset=155,
                                func=Attribute(
                                    lineno=17,
                                    col_offset=8,
                                    end_lineno=17,
                                    end_col_offset=24,
                                    value=Name(lineno=17, col_offset=8, end_lineno=17, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Subscript(
                                        lineno=17,
                                        col_offset=25,
                                        end_lineno=17,
                                        end_col_offset=77,
                                        value=Subscript(
                                            lineno=17,
                                            col_offset=25,
                                            end_lineno=17,
                                            end_col_offset=57,
                                            value=Name(lineno=17, col_offset=25, end_lineno=17, end_col_offset=40, id='template_values', ctx=Load()),
                                            slice=Constant(lineno=17, col_offset=41, end_lineno=17, end_col_offset=56, value='profitability', kind=None),
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=17, col_offset=58, end_lineno=17, end_col_offset=76, value='margin_formatted', kind=None),
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=17, col_offset=79, end_lineno=17, end_col_offset=90, value='$\xa00.00', kind=None),
                                    Constant(lineno=17, col_offset=92, end_lineno=17, end_col_offset=154, value='Margin formatted used in the template should be well defined', kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                        Expr(
                            lineno=18,
                            col_offset=8,
                            end_lineno=18,
                            end_col_offset=149,
                            value=Call(
                                lineno=18,
                                col_offset=8,
                                end_lineno=18,
                                end_col_offset=149,
                                func=Attribute(
                                    lineno=18,
                                    col_offset=8,
                                    end_lineno=18,
                                    end_col_offset=24,
                                    value=Name(lineno=18, col_offset=8, end_lineno=18, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Subscript(
                                        lineno=18,
                                        col_offset=25,
                                        end_lineno=18,
                                        end_col_offset=78,
                                        value=Subscript(
                                            lineno=18,
                                            col_offset=25,
                                            end_lineno=18,
                                            end_col_offset=57,
                                            value=Name(lineno=18, col_offset=25, end_lineno=18, end_col_offset=40, id='template_values', ctx=Load()),
                                            slice=Constant(lineno=18, col_offset=41, end_lineno=18, end_col_offset=56, value='profitability', kind=None),
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=18, col_offset=58, end_lineno=18, end_col_offset=77, value='margin_percentage', kind=None),
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=18, col_offset=80, end_lineno=18, end_col_offset=83, value='0', kind=None),
                                    Constant(lineno=18, col_offset=85, end_lineno=18, end_col_offset=148, value='Margin percentage used in the template should be well defined', kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=20,
                    col_offset=4,
                    end_lineno=31,
                    end_col_offset=156,
                    name='test_project_update_panel_profitability_no_billable',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=20, col_offset=60, end_lineno=20, end_col_offset=64, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=21,
                            col_offset=8,
                            end_lineno=21,
                            end_col_offset=55,
                            targets=[Name(lineno=21, col_offset=8, end_lineno=21, end_col_offset=18, id='panel_data', ctx=Store())],
                            value=Call(
                                lineno=21,
                                col_offset=21,
                                end_lineno=21,
                                end_col_offset=55,
                                func=Attribute(
                                    lineno=21,
                                    col_offset=21,
                                    end_lineno=21,
                                    end_col_offset=53,
                                    value=Attribute(
                                        lineno=21,
                                        col_offset=21,
                                        end_lineno=21,
                                        end_col_offset=38,
                                        value=Name(lineno=21, col_offset=21, end_lineno=21, end_col_offset=25, id='self', ctx=Load()),
                                        attr='project_pigs',
                                        ctx=Load(),
                                    ),
                                    attr='get_panel_data',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=22,
                            col_offset=8,
                            end_lineno=22,
                            end_col_offset=129,
                            value=Call(
                                lineno=22,
                                col_offset=8,
                                end_lineno=22,
                                end_col_offset=129,
                                func=Attribute(
                                    lineno=22,
                                    col_offset=8,
                                    end_lineno=22,
                                    end_col_offset=24,
                                    value=Name(lineno=22, col_offset=8, end_lineno=22, end_col_offset=12, id='self', ctx=Load()),
                                    attr='assertEqual',
                                    ctx=Load(),
                                ),
                                args=[
                                    Subscript(
                                        lineno=22,
                                        col_offset=25,
                                        end_lineno=22,
                                        end_col_offset=76,
                                        value=Subscript(
                                            lineno=22,
                                            col_offset=25,
                                            end_lineno=22,
                                            end_col_offset=58,
                                            value=Name(lineno=22, col_offset=25, end_lineno=22, end_col_offset=35, id='panel_data', ctx=Load()),
                                            slice=Constant(lineno=22, col_offset=36, end_lineno=22, end_col_offset=57, value='profitability_items', kind=None),
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=22, col_offset=59, end_lineno=22, end_col_offset=75, value='allow_billable', kind=None),
                                        ctx=Load(),
                                    ),
                                    Constant(lineno=22, col_offset=78, end_lineno=22, end_col_offset=83, value=False, kind=None),
                                    Constant(lineno=22, col_offset=85, end_lineno=22, end_col_offset=128, value='Project should not be billable by default', kind=None),
                                ],
                                keywords=[],
                            ),
                        ),
                        Try(
                            lineno=23,
                            col_offset=8,
                            end_lineno=26,
                            end_col_offset=156,
                            body=[
                                Expr(
                                    lineno=24,
                                    col_offset=12,
                                    end_lineno=24,
                                    end_col_offset=53,
                                    value=Call(
                                        lineno=24,
                                        col_offset=12,
                                        end_lineno=24,
                                        end_col_offset=53,
                                        func=Attribute(
                                            lineno=24,
                                            col_offset=12,
                                            end_lineno=24,
                                            end_col_offset=51,
                                            value=Attribute(
                                                lineno=24,
                                                col_offset=12,
                                                end_lineno=24,
                                                end_col_offset=29,
                                                value=Name(lineno=24, col_offset=12, end_lineno=24, end_col_offset=16, id='self', ctx=Load()),
                                                attr='project_pigs',
                                                ctx=Load(),
                                            ),
                                            attr='action_view_timesheet',
                                            ctx=Load(),
                                        ),
                                        args=[],
                                        keywords=[],
                                    ),
                                ),
                            ],
                            handlers=[
                                ExceptHandler(
                                    lineno=25,
                                    col_offset=8,
                                    end_lineno=26,
                                    end_col_offset=156,
                                    type=Name(lineno=25, col_offset=15, end_lineno=25, end_col_offset=24, id='Exception', ctx=Load()),
                                    name='e',
                                    body=[
                                        Raise(
                                            lineno=26,
                                            col_offset=12,
                                            end_lineno=26,
                                            end_col_offset=156,
                                            exc=Call(
                                                lineno=26,
                                                col_offset=18,
                                                end_lineno=26,
                                                end_col_offset=156,
                                                func=Name(lineno=26, col_offset=18, end_lineno=26, end_col_offset=32, id='AssertionError', ctx=Load()),
                                                args=[
                                                    BinOp(
                                                        lineno=26,
                                                        col_offset=33,
                                                        end_lineno=26,
                                                        end_col_offset=155,
                                                        left=Constant(lineno=26, col_offset=33, end_lineno=26, end_col_offset=143, value='Error raised unexpectedly while calling the action defined in profitalities action panel data ! Exception : ', kind=None),
                                                        op=Add(),
                                                        right=Subscript(
                                                            lineno=26,
                                                            col_offset=146,
                                                            end_lineno=26,
                                                            end_col_offset=155,
                                                            value=Attribute(
                                                                lineno=26,
                                                                col_offset=146,
                                                                end_lineno=26,
                                                                end_col_offset=152,
                                                                value=Name(lineno=26, col_offset=146, end_lineno=26, end_col_offset=147, id='e', ctx=Load()),
                                                                attr='args',
                                                                ctx=Load(),
                                                            ),
                                                            slice=Constant(lineno=26, col_offset=153, end_lineno=26, end_col_offset=154, value=0, kind=None),
                                                            ctx=Load(),
                                                        ),
                                                    ),
                                                ],
                                                keywords=[],
                                            ),
                                            cause=None,
                                        ),
                                    ],
                                ),
                            ],
                            orelse=[],
                            finalbody=[],
                        ),
                        Try(
                            lineno=28,
                            col_offset=8,
                            end_lineno=31,
                            end_col_offset=156,
                            body=[
                                Expr(
                                    lineno=29,
                                    col_offset=12,
                                    end_lineno=29,
                                    end_col_offset=53,
                                    value=Call(
                                        lineno=29,
                                        col_offset=12,
                                        end_lineno=29,
                                        end_col_offset=53,
                                        func=Attribute(
                                            lineno=29,
                                            col_offset=12,
                                            end_lineno=29,
                                            end_col_offset=51,
                                            value=Attribute(
                                                lineno=29,
                                                col_offset=12,
                                                end_lineno=29,
                                                end_col_offset=29,
                                                value=Name(lineno=29, col_offset=12, end_lineno=29, end_col_offset=16, id='self', ctx=Load()),
                                                attr='project_pigs',
                                                ctx=Load(),
                                            ),
                                            attr='action_view_timesheet',
                                            ctx=Load(),
                                        ),
                                        args=[],
                                        keywords=[],
                                    ),
                                ),
                            ],
                            handlers=[
                                ExceptHandler(
                                    lineno=30,
                                    col_offset=8,
                                    end_lineno=31,
                                    end_col_offset=156,
                                    type=Name(lineno=30, col_offset=15, end_lineno=30, end_col_offset=24, id='Exception', ctx=Load()),
                                    name='e',
                                    body=[
                                        Raise(
                                            lineno=31,
                                            col_offset=12,
                                            end_lineno=31,
                                            end_col_offset=156,
                                            exc=Call(
                                                lineno=31,
                                                col_offset=18,
                                                end_lineno=31,
                                                end_col_offset=156,
                                                func=Name(lineno=31, col_offset=18, end_lineno=31, end_col_offset=32, id='AssertionError', ctx=Load()),
                                                args=[
                                                    BinOp(
                                                        lineno=31,
                                                        col_offset=33,
                                                        end_lineno=31,
                                                        end_col_offset=155,
                                                        left=Constant(lineno=31, col_offset=33, end_lineno=31, end_col_offset=143, value='Error raised unexpectedly while calling the action defined in profitalities action panel data ! Exception : ', kind=None),
                                                        op=Add(),
                                                        right=Subscript(
                                                            lineno=31,
                                                            col_offset=146,
                                                            end_lineno=31,
                                                            end_col_offset=155,
                                                            value=Attribute(
                                                                lineno=31,
                                                                col_offset=146,
                                                                end_lineno=31,
                                                                end_col_offset=152,
                                                                value=Name(lineno=31, col_offset=146, end_lineno=31, end_col_offset=147, id='e', ctx=Load()),
                                                                attr='args',
                                                                ctx=Load(),
                                                            ),
                                                            slice=Constant(lineno=31, col_offset=153, end_lineno=31, end_col_offset=154, value=0, kind=None),
                                                            ctx=Load(),
                                                        ),
                                                    ),
                                                ],
                                                keywords=[],
                                            ),
                                            cause=None,
                                        ),
                                    ],
                                ),
                            ],
                            orelse=[],
                            finalbody=[],
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[
                Call(
                    lineno=8,
                    col_offset=1,
                    end_lineno=8,
                    end_col_offset=38,
                    func=Name(lineno=8, col_offset=1, end_lineno=8, end_col_offset=7, id='tagged', ctx=Load()),
                    args=[
                        Constant(lineno=8, col_offset=8, end_lineno=8, end_col_offset=21, value='-at_install', kind=None),
                        Constant(lineno=8, col_offset=23, end_lineno=8, end_col_offset=37, value='post_install', kind=None),
                    ],
                    keywords=[],
                ),
            ],
        ),
    ],
    type_ignores=[],
)
