Module(
    body=[
        ImportFrom(
            lineno=3,
            col_offset=0,
            end_lineno=3,
            end_col_offset=39,
            module='odoo',
            names=[
                alias(name='models', asname=None),
                alias(name='fields', asname=None),
                alias(name='api', asname=None),
                alias(name='_', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=6,
            col_offset=0,
            end_lineno=65,
            end_col_offset=19,
            name='ResPartnerBank',
            bases=[
                Attribute(
                    lineno=6,
                    col_offset=21,
                    end_lineno=6,
                    end_col_offset=33,
                    value=Name(lineno=6, col_offset=21, end_lineno=6, end_col_offset=27, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=7,
                    col_offset=4,
                    end_lineno=7,
                    end_col_offset=33,
                    targets=[Name(lineno=7, col_offset=4, end_lineno=7, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=7, col_offset=15, end_lineno=7, end_col_offset=33, value='res.partner.bank', kind=None),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=9,
                    col_offset=4,
                    end_lineno=28,
                    end_col_offset=126,
                    name='_get_qr_vals',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=9, col_offset=21, end_lineno=9, end_col_offset=25, arg='self', annotation=None, type_comment=None),
                            arg(lineno=9, col_offset=27, end_lineno=9, end_col_offset=36, arg='qr_method', annotation=None, type_comment=None),
                            arg(lineno=9, col_offset=38, end_lineno=9, end_col_offset=44, arg='amount', annotation=None, type_comment=None),
                            arg(lineno=9, col_offset=46, end_lineno=9, end_col_offset=54, arg='currency', annotation=None, type_comment=None),
                            arg(lineno=9, col_offset=56, end_lineno=9, end_col_offset=70, arg='debtor_partner', annotation=None, type_comment=None),
                            arg(lineno=9, col_offset=72, end_lineno=9, end_col_offset=90, arg='free_communication', annotation=None, type_comment=None),
                            arg(lineno=9, col_offset=92, end_lineno=9, end_col_offset=116, arg='structured_communication', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        If(
                            lineno=10,
                            col_offset=8,
                            end_lineno=27,
                            end_col_offset=31,
                            test=Compare(
                                lineno=10,
                                col_offset=11,
                                end_lineno=10,
                                end_col_offset=32,
                                left=Name(lineno=10, col_offset=11, end_lineno=10, end_col_offset=20, id='qr_method', ctx=Load()),
                                ops=[Eq()],
                                comparators=[Constant(lineno=10, col_offset=24, end_lineno=10, end_col_offset=32, value='sct_qr', kind=None)],
                            ),
                            body=[
                                Assign(
                                    lineno=11,
                                    col_offset=12,
                                    end_lineno=11,
                                    end_col_offset=88,
                                    targets=[Name(lineno=11, col_offset=12, end_lineno=11, end_col_offset=19, id='comment', ctx=Store())],
                                    value=IfExp(
                                        lineno=11,
                                        col_offset=22,
                                        end_lineno=11,
                                        end_col_offset=88,
                                        test=UnaryOp(
                                            lineno=11,
                                            col_offset=52,
                                            end_lineno=11,
                                            end_col_offset=80,
                                            op=Not(),
                                            operand=Name(lineno=11, col_offset=56, end_lineno=11, end_col_offset=80, id='structured_communication', ctx=Load()),
                                        ),
                                        body=BoolOp(
                                            lineno=11,
                                            col_offset=23,
                                            end_lineno=11,
                                            end_col_offset=47,
                                            op=Or(),
                                            values=[
                                                Name(lineno=11, col_offset=23, end_lineno=11, end_col_offset=41, id='free_communication', ctx=Load()),
                                                Constant(lineno=11, col_offset=45, end_lineno=11, end_col_offset=47, value='', kind=None),
                                            ],
                                        ),
                                        orelse=Constant(lineno=11, col_offset=86, end_lineno=11, end_col_offset=88, value='', kind=None),
                                    ),
                                    type_comment=None,
                                ),
                                Assign(
                                    lineno=13,
                                    col_offset=12,
                                    end_lineno=26,
                                    end_col_offset=13,
                                    targets=[Name(lineno=13, col_offset=12, end_lineno=13, end_col_offset=24, id='qr_code_vals', ctx=Store())],
                                    value=List(
                                        lineno=13,
                                        col_offset=27,
                                        end_lineno=26,
                                        end_col_offset=13,
                                        elts=[
                                            Constant(lineno=14, col_offset=16, end_lineno=14, end_col_offset=21, value='BCD', kind=None),
                                            Constant(lineno=15, col_offset=16, end_lineno=15, end_col_offset=21, value='002', kind=None),
                                            Constant(lineno=16, col_offset=16, end_lineno=16, end_col_offset=19, value='1', kind=None),
                                            Constant(lineno=17, col_offset=16, end_lineno=17, end_col_offset=21, value='SCT', kind=None),
                                            BoolOp(
                                                lineno=18,
                                                col_offset=16,
                                                end_lineno=18,
                                                end_col_offset=35,
                                                op=Or(),
                                                values=[
                                                    Attribute(
                                                        lineno=18,
                                                        col_offset=16,
                                                        end_lineno=18,
                                                        end_col_offset=29,
                                                        value=Name(lineno=18, col_offset=16, end_lineno=18, end_col_offset=20, id='self', ctx=Load()),
                                                        attr='bank_bic',
                                                        ctx=Load(),
                                                    ),
                                                    Constant(lineno=18, col_offset=33, end_lineno=18, end_col_offset=35, value='', kind=None),
                                                ],
                                            ),
                                            Subscript(
                                                lineno=19,
                                                col_offset=16,
                                                end_lineno=19,
                                                end_col_offset=67,
                                                value=BoolOp(
                                                    lineno=19,
                                                    col_offset=17,
                                                    end_lineno=19,
                                                    end_col_offset=61,
                                                    op=Or(),
                                                    values=[
                                                        Attribute(
                                                            lineno=19,
                                                            col_offset=17,
                                                            end_lineno=19,
                                                            end_col_offset=37,
                                                            value=Name(lineno=19, col_offset=17, end_lineno=19, end_col_offset=21, id='self', ctx=Load()),
                                                            attr='acc_holder_name',
                                                            ctx=Load(),
                                                        ),
                                                        Attribute(
                                                            lineno=19,
                                                            col_offset=41,
                                                            end_lineno=19,
                                                            end_col_offset=61,
                                                            value=Attribute(
                                                                lineno=19,
                                                                col_offset=41,
                                                                end_lineno=19,
                                                                end_col_offset=56,
                                                                value=Name(lineno=19, col_offset=41, end_lineno=19, end_col_offset=45, id='self', ctx=Load()),
                                                                attr='partner_id',
                                                                ctx=Load(),
                                                            ),
                                                            attr='name',
                                                            ctx=Load(),
                                                        ),
                                                    ],
                                                ),
                                                slice=Slice(
                                                    lineno=19,
                                                    col_offset=63,
                                                    end_lineno=19,
                                                    end_col_offset=66,
                                                    lower=None,
                                                    upper=Constant(lineno=19, col_offset=64, end_lineno=19, end_col_offset=66, value=71, kind=None),
                                                    step=None,
                                                ),
                                                ctx=Load(),
                                            ),
                                            Attribute(
                                                lineno=20,
                                                col_offset=16,
                                                end_lineno=20,
                                                end_col_offset=41,
                                                value=Name(lineno=20, col_offset=16, end_lineno=20, end_col_offset=20, id='self', ctx=Load()),
                                                attr='sanitized_acc_number',
                                                ctx=Load(),
                                            ),
                                            BinOp(
                                                lineno=21,
                                                col_offset=16,
                                                end_lineno=21,
                                                end_col_offset=43,
                                                left=Attribute(
                                                    lineno=21,
                                                    col_offset=16,
                                                    end_lineno=21,
                                                    end_col_offset=29,
                                                    value=Name(lineno=21, col_offset=16, end_lineno=21, end_col_offset=24, id='currency', ctx=Load()),
                                                    attr='name',
                                                    ctx=Load(),
                                                ),
                                                op=Add(),
                                                right=Call(
                                                    lineno=21,
                                                    col_offset=32,
                                                    end_lineno=21,
                                                    end_col_offset=43,
                                                    func=Name(lineno=21, col_offset=32, end_lineno=21, end_col_offset=35, id='str', ctx=Load()),
                                                    args=[Name(lineno=21, col_offset=36, end_lineno=21, end_col_offset=42, id='amount', ctx=Load())],
                                                    keywords=[],
                                                ),
                                            ),
                                            Constant(lineno=22, col_offset=16, end_lineno=22, end_col_offset=18, value='', kind=None),
                                            Subscript(
                                                lineno=23,
                                                col_offset=16,
                                                end_lineno=23,
                                                end_col_offset=53,
                                                value=BoolOp(
                                                    lineno=23,
                                                    col_offset=17,
                                                    end_lineno=23,
                                                    end_col_offset=47,
                                                    op=Or(),
                                                    values=[
                                                        Name(lineno=23, col_offset=17, end_lineno=23, end_col_offset=41, id='structured_communication', ctx=Load()),
                                                        Constant(lineno=23, col_offset=45, end_lineno=23, end_col_offset=47, value='', kind=None),
                                                    ],
                                                ),
                                                slice=Slice(
                                                    lineno=23,
                                                    col_offset=49,
                                                    end_lineno=23,
                                                    end_col_offset=52,
                                                    lower=None,
                                                    upper=Constant(lineno=23, col_offset=50, end_lineno=23, end_col_offset=52, value=36, kind=None),
                                                    step=None,
                                                ),
                                                ctx=Load(),
                                            ),
                                            Subscript(
                                                lineno=24,
                                                col_offset=16,
                                                end_lineno=24,
                                                end_col_offset=29,
                                                value=Name(lineno=24, col_offset=16, end_lineno=24, end_col_offset=23, id='comment', ctx=Load()),
                                                slice=Slice(
                                                    lineno=24,
                                                    col_offset=24,
                                                    end_lineno=24,
                                                    end_col_offset=28,
                                                    lower=None,
                                                    upper=Constant(lineno=24, col_offset=25, end_lineno=24, end_col_offset=28, value=141, kind=None),
                                                    step=None,
                                                ),
                                                ctx=Load(),
                                            ),
                                            Constant(lineno=25, col_offset=16, end_lineno=25, end_col_offset=18, value='', kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                    type_comment=None,
                                ),
                                Return(
                                    lineno=27,
                                    col_offset=12,
                                    end_lineno=27,
                                    end_col_offset=31,
                                    value=Name(lineno=27, col_offset=19, end_lineno=27, end_col_offset=31, id='qr_code_vals', ctx=Load()),
                                ),
                            ],
                            orelse=[],
                        ),
                        Return(
                            lineno=28,
                            col_offset=8,
                            end_lineno=28,
                            end_col_offset=126,
                            value=Call(
                                lineno=28,
                                col_offset=15,
                                end_lineno=28,
                                end_col_offset=126,
                                func=Attribute(
                                    lineno=28,
                                    col_offset=15,
                                    end_lineno=28,
                                    end_col_offset=35,
                                    value=Call(
                                        lineno=28,
                                        col_offset=15,
                                        end_lineno=28,
                                        end_col_offset=22,
                                        func=Name(lineno=28, col_offset=15, end_lineno=28, end_col_offset=20, id='super', ctx=Load()),
                                        args=[],
                                        keywords=[],
                                    ),
                                    attr='_get_qr_vals',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=28, col_offset=36, end_lineno=28, end_col_offset=45, id='qr_method', ctx=Load()),
                                    Name(lineno=28, col_offset=47, end_lineno=28, end_col_offset=53, id='amount', ctx=Load()),
                                    Name(lineno=28, col_offset=55, end_lineno=28, end_col_offset=63, id='currency', ctx=Load()),
                                    Name(lineno=28, col_offset=65, end_lineno=28, end_col_offset=79, id='debtor_partner', ctx=Load()),
                                    Name(lineno=28, col_offset=81, end_lineno=28, end_col_offset=99, id='free_communication', ctx=Load()),
                                    Name(lineno=28, col_offset=101, end_lineno=28, end_col_offset=125, id='structured_communication', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=30,
                    col_offset=4,
                    end_lineno=39,
                    end_col_offset=144,
                    name='_get_qr_code_generation_params',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=30, col_offset=39, end_lineno=30, end_col_offset=43, arg='self', annotation=None, type_comment=None),
                            arg(lineno=30, col_offset=45, end_lineno=30, end_col_offset=54, arg='qr_method', annotation=None, type_comment=None),
                            arg(lineno=30, col_offset=56, end_lineno=30, end_col_offset=62, arg='amount', annotation=None, type_comment=None),
                            arg(lineno=30, col_offset=64, end_lineno=30, end_col_offset=72, arg='currency', annotation=None, type_comment=None),
                            arg(lineno=30, col_offset=74, end_lineno=30, end_col_offset=88, arg='debtor_partner', annotation=None, type_comment=None),
                            arg(lineno=30, col_offset=90, end_lineno=30, end_col_offset=108, arg='free_communication', annotation=None, type_comment=None),
                            arg(lineno=30, col_offset=110, end_lineno=30, end_col_offset=134, arg='structured_communication', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        If(
                            lineno=31,
                            col_offset=8,
                            end_lineno=38,
                            end_col_offset=13,
                            test=Compare(
                                lineno=31,
                                col_offset=11,
                                end_lineno=31,
                                end_col_offset=32,
                                left=Name(lineno=31, col_offset=11, end_lineno=31, end_col_offset=20, id='qr_method', ctx=Load()),
                                ops=[Eq()],
                                comparators=[Constant(lineno=31, col_offset=24, end_lineno=31, end_col_offset=32, value='sct_qr', kind=None)],
                            ),
                            body=[
                                Return(
                                    lineno=32,
                                    col_offset=12,
                                    end_lineno=38,
                                    end_col_offset=13,
                                    value=Dict(
                                        lineno=32,
                                        col_offset=19,
                                        end_lineno=38,
                                        end_col_offset=13,
                                        keys=[
                                            Constant(lineno=33, col_offset=16, end_lineno=33, end_col_offset=30, value='barcode_type', kind=None),
                                            Constant(lineno=34, col_offset=16, end_lineno=34, end_col_offset=23, value='width', kind=None),
                                            Constant(lineno=35, col_offset=16, end_lineno=35, end_col_offset=24, value='height', kind=None),
                                            Constant(lineno=36, col_offset=16, end_lineno=36, end_col_offset=31, value='humanreadable', kind=None),
                                            Constant(lineno=37, col_offset=16, end_lineno=37, end_col_offset=23, value='value', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=33, col_offset=32, end_lineno=33, end_col_offset=36, value='QR', kind=None),
                                            Constant(lineno=34, col_offset=25, end_lineno=34, end_col_offset=28, value=128, kind=None),
                                            Constant(lineno=35, col_offset=26, end_lineno=35, end_col_offset=29, value=128, kind=None),
                                            Constant(lineno=36, col_offset=33, end_lineno=36, end_col_offset=34, value=1, kind=None),
                                            Call(
                                                lineno=37,
                                                col_offset=25,
                                                end_lineno=37,
                                                end_col_offset=144,
                                                func=Attribute(
                                                    lineno=37,
                                                    col_offset=25,
                                                    end_lineno=37,
                                                    end_col_offset=34,
                                                    value=Constant(lineno=37, col_offset=25, end_lineno=37, end_col_offset=29, value='\n', kind=None),
                                                    attr='join',
                                                    ctx=Load(),
                                                ),
                                                args=[
                                                    Call(
                                                        lineno=37,
                                                        col_offset=35,
                                                        end_lineno=37,
                                                        end_col_offset=143,
                                                        func=Attribute(
                                                            lineno=37,
                                                            col_offset=35,
                                                            end_lineno=37,
                                                            end_col_offset=52,
                                                            value=Name(lineno=37, col_offset=35, end_lineno=37, end_col_offset=39, id='self', ctx=Load()),
                                                            attr='_get_qr_vals',
                                                            ctx=Load(),
                                                        ),
                                                        args=[
                                                            Name(lineno=37, col_offset=53, end_lineno=37, end_col_offset=62, id='qr_method', ctx=Load()),
                                                            Name(lineno=37, col_offset=64, end_lineno=37, end_col_offset=70, id='amount', ctx=Load()),
                                                            Name(lineno=37, col_offset=72, end_lineno=37, end_col_offset=80, id='currency', ctx=Load()),
                                                            Name(lineno=37, col_offset=82, end_lineno=37, end_col_offset=96, id='debtor_partner', ctx=Load()),
                                                            Name(lineno=37, col_offset=98, end_lineno=37, end_col_offset=116, id='free_communication', ctx=Load()),
                                                            Name(lineno=37, col_offset=118, end_lineno=37, end_col_offset=142, id='structured_communication', ctx=Load()),
                                                        ],
                                                        keywords=[],
                                                    ),
                                                ],
                                                keywords=[],
                                            ),
                                        ],
                                    ),
                                ),
                            ],
                            orelse=[],
                        ),
                        Return(
                            lineno=39,
                            col_offset=8,
                            end_lineno=39,
                            end_col_offset=144,
                            value=Call(
                                lineno=39,
                                col_offset=15,
                                end_lineno=39,
                                end_col_offset=144,
                                func=Attribute(
                                    lineno=39,
                                    col_offset=15,
                                    end_lineno=39,
                                    end_col_offset=53,
                                    value=Call(
                                        lineno=39,
                                        col_offset=15,
                                        end_lineno=39,
                                        end_col_offset=22,
                                        func=Name(lineno=39, col_offset=15, end_lineno=39, end_col_offset=20, id='super', ctx=Load()),
                                        args=[],
                                        keywords=[],
                                    ),
                                    attr='_get_qr_code_generation_params',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=39, col_offset=54, end_lineno=39, end_col_offset=63, id='qr_method', ctx=Load()),
                                    Name(lineno=39, col_offset=65, end_lineno=39, end_col_offset=71, id='amount', ctx=Load()),
                                    Name(lineno=39, col_offset=73, end_lineno=39, end_col_offset=81, id='currency', ctx=Load()),
                                    Name(lineno=39, col_offset=83, end_lineno=39, end_col_offset=97, id='debtor_partner', ctx=Load()),
                                    Name(lineno=39, col_offset=99, end_lineno=39, end_col_offset=117, id='free_communication', ctx=Load()),
                                    Name(lineno=39, col_offset=119, end_lineno=39, end_col_offset=143, id='structured_communication', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=41,
                    col_offset=4,
                    end_lineno=52,
                    end_col_offset=81,
                    name='_eligible_for_qr_code',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=41, col_offset=30, end_lineno=41, end_col_offset=34, arg='self', annotation=None, type_comment=None),
                            arg(lineno=41, col_offset=36, end_lineno=41, end_col_offset=45, arg='qr_method', annotation=None, type_comment=None),
                            arg(lineno=41, col_offset=47, end_lineno=41, end_col_offset=61, arg='debtor_partner', annotation=None, type_comment=None),
                            arg(lineno=41, col_offset=63, end_lineno=41, end_col_offset=71, arg='currency', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        If(
                            lineno=42,
                            col_offset=8,
                            end_lineno=50,
                            end_col_offset=122,
                            test=Compare(
                                lineno=42,
                                col_offset=11,
                                end_lineno=42,
                                end_col_offset=32,
                                left=Name(lineno=42, col_offset=11, end_lineno=42, end_col_offset=20, id='qr_method', ctx=Load()),
                                ops=[Eq()],
                                comparators=[Constant(lineno=42, col_offset=24, end_lineno=42, end_col_offset=32, value='sct_qr', kind=None)],
                            ),
                            body=[
                                Assign(
                                    lineno=46,
                                    col_offset=12,
                                    end_lineno=46,
                                    end_col_offset=90,
                                    targets=[Name(lineno=46, col_offset=12, end_lineno=46, end_col_offset=30, id='sepa_country_codes', ctx=Store())],
                                    value=Call(
                                        lineno=46,
                                        col_offset=33,
                                        end_lineno=46,
                                        end_col_offset=90,
                                        func=Attribute(
                                            lineno=46,
                                            col_offset=33,
                                            end_lineno=46,
                                            end_col_offset=82,
                                            value=Attribute(
                                                lineno=46,
                                                col_offset=33,
                                                end_lineno=46,
                                                end_col_offset=75,
                                                value=Call(
                                                    lineno=46,
                                                    col_offset=33,
                                                    end_lineno=46,
                                                    end_col_offset=63,
                                                    func=Attribute(
                                                        lineno=46,
                                                        col_offset=33,
                                                        end_lineno=46,
                                                        end_col_offset=45,
                                                        value=Attribute(
                                                            lineno=46,
                                                            col_offset=33,
                                                            end_lineno=46,
                                                            end_col_offset=41,
                                                            value=Name(lineno=46, col_offset=33, end_lineno=46, end_col_offset=37, id='self', ctx=Load()),
                                                            attr='env',
                                                            ctx=Load(),
                                                        ),
                                                        attr='ref',
                                                        ctx=Load(),
                                                    ),
                                                    args=[Constant(lineno=46, col_offset=46, end_lineno=46, end_col_offset=62, value='base.sepa_zone', kind=None)],
                                                    keywords=[],
                                                ),
                                                attr='country_ids',
                                                ctx=Load(),
                                            ),
                                            attr='mapped',
                                            ctx=Load(),
                                        ),
                                        args=[Constant(lineno=46, col_offset=83, end_lineno=46, end_col_offset=89, value='code', kind=None)],
                                        keywords=[],
                                    ),
                                    type_comment=None,
                                ),
                                Assign(
                                    lineno=47,
                                    col_offset=12,
                                    end_lineno=47,
                                    end_col_offset=119,
                                    targets=[Name(lineno=47, col_offset=12, end_lineno=47, end_col_offset=26, id='non_iban_codes', ctx=Store())],
                                    value=Set(
                                        lineno=47,
                                        col_offset=29,
                                        end_lineno=47,
                                        end_col_offset=119,
                                        elts=[
                                            Constant(lineno=47, col_offset=30, end_lineno=47, end_col_offset=34, value='AX', kind=None),
                                            Constant(lineno=47, col_offset=36, end_lineno=47, end_col_offset=40, value='NC', kind=None),
                                            Constant(lineno=47, col_offset=42, end_lineno=47, end_col_offset=46, value='YT', kind=None),
                                            Constant(lineno=47, col_offset=48, end_lineno=47, end_col_offset=52, value='TF', kind=None),
                                            Constant(lineno=47, col_offset=54, end_lineno=47, end_col_offset=58, value='BL', kind=None),
                                            Constant(lineno=47, col_offset=60, end_lineno=47, end_col_offset=64, value='RE', kind=None),
                                            Constant(lineno=47, col_offset=66, end_lineno=47, end_col_offset=70, value='MF', kind=None),
                                            Constant(lineno=47, col_offset=72, end_lineno=47, end_col_offset=76, value='GP', kind=None),
                                            Constant(lineno=47, col_offset=78, end_lineno=47, end_col_offset=82, value='PM', kind=None),
                                            Constant(lineno=47, col_offset=84, end_lineno=47, end_col_offset=88, value='PF', kind=None),
                                            Constant(lineno=47, col_offset=90, end_lineno=47, end_col_offset=94, value='GF', kind=None),
                                            Constant(lineno=47, col_offset=96, end_lineno=47, end_col_offset=100, value='MQ', kind=None),
                                            Constant(lineno=47, col_offset=102, end_lineno=47, end_col_offset=106, value='JE', kind=None),
                                            Constant(lineno=47, col_offset=108, end_lineno=47, end_col_offset=112, value='GG', kind=None),
                                            Constant(lineno=47, col_offset=114, end_lineno=47, end_col_offset=118, value='IM', kind=None),
                                        ],
                                    ),
                                    type_comment=None,
                                ),
                                Assign(
                                    lineno=48,
                                    col_offset=12,
                                    end_lineno=48,
                                    end_col_offset=97,
                                    targets=[Name(lineno=48, col_offset=12, end_lineno=48, end_col_offset=27, id='sepa_iban_codes', ctx=Store())],
                                    value=SetComp(
                                        lineno=48,
                                        col_offset=30,
                                        end_lineno=48,
                                        end_col_offset=97,
                                        elt=Name(lineno=48, col_offset=31, end_lineno=48, end_col_offset=35, id='code', ctx=Load()),
                                        generators=[
                                            comprehension(
                                                target=Name(lineno=48, col_offset=40, end_lineno=48, end_col_offset=44, id='code', ctx=Store()),
                                                iter=Name(lineno=48, col_offset=48, end_lineno=48, end_col_offset=66, id='sepa_country_codes', ctx=Load()),
                                                ifs=[
                                                    Compare(
                                                        lineno=48,
                                                        col_offset=70,
                                                        end_lineno=48,
                                                        end_col_offset=96,
                                                        left=Name(lineno=48, col_offset=70, end_lineno=48, end_col_offset=74, id='code', ctx=Load()),
                                                        ops=[NotIn()],
                                                        comparators=[Name(lineno=48, col_offset=82, end_lineno=48, end_col_offset=96, id='non_iban_codes', ctx=Load())],
                                                    ),
                                                ],
                                                is_async=0,
                                            ),
                                        ],
                                    ),
                                    type_comment=None,
                                ),
                                Return(
                                    lineno=50,
                                    col_offset=12,
                                    end_lineno=50,
                                    end_col_offset=122,
                                    value=BoolOp(
                                        lineno=50,
                                        col_offset=19,
                                        end_lineno=50,
                                        end_col_offset=122,
                                        op=And(),
                                        values=[
                                            Compare(
                                                lineno=50,
                                                col_offset=19,
                                                end_lineno=50,
                                                end_col_offset=41,
                                                left=Attribute(
                                                    lineno=50,
                                                    col_offset=19,
                                                    end_lineno=50,
                                                    end_col_offset=32,
                                                    value=Name(lineno=50, col_offset=19, end_lineno=50, end_col_offset=27, id='currency', ctx=Load()),
                                                    attr='name',
                                                    ctx=Load(),
                                                ),
                                                ops=[Eq()],
                                                comparators=[Constant(lineno=50, col_offset=36, end_lineno=50, end_col_offset=41, value='EUR', kind=None)],
                                            ),
                                            Compare(
                                                lineno=50,
                                                col_offset=46,
                                                end_lineno=50,
                                                end_col_offset=69,
                                                left=Attribute(
                                                    lineno=50,
                                                    col_offset=46,
                                                    end_lineno=50,
                                                    end_col_offset=59,
                                                    value=Name(lineno=50, col_offset=46, end_lineno=50, end_col_offset=50, id='self', ctx=Load()),
                                                    attr='acc_type',
                                                    ctx=Load(),
                                                ),
                                                ops=[Eq()],
                                                comparators=[Constant(lineno=50, col_offset=63, end_lineno=50, end_col_offset=69, value='iban', kind=None)],
                                            ),
                                            Compare(
                                                lineno=50,
                                                col_offset=74,
                                                end_lineno=50,
                                                end_col_offset=122,
                                                left=Subscript(
                                                    lineno=50,
                                                    col_offset=74,
                                                    end_lineno=50,
                                                    end_col_offset=103,
                                                    value=Attribute(
                                                        lineno=50,
                                                        col_offset=74,
                                                        end_lineno=50,
                                                        end_col_offset=99,
                                                        value=Name(lineno=50, col_offset=74, end_lineno=50, end_col_offset=78, id='self', ctx=Load()),
                                                        attr='sanitized_acc_number',
                                                        ctx=Load(),
                                                    ),
                                                    slice=Slice(
                                                        lineno=50,
                                                        col_offset=100,
                                                        end_lineno=50,
                                                        end_col_offset=102,
                                                        lower=None,
                                                        upper=Constant(lineno=50, col_offset=101, end_lineno=50, end_col_offset=102, value=2, kind=None),
                                                        step=None,
                                                    ),
                                                    ctx=Load(),
                                                ),
                                                ops=[In()],
                                                comparators=[Name(lineno=50, col_offset=107, end_lineno=50, end_col_offset=122, id='sepa_iban_codes', ctx=Load())],
                                            ),
                                        ],
                                    ),
                                ),
                            ],
                            orelse=[],
                        ),
                        Return(
                            lineno=52,
                            col_offset=8,
                            end_lineno=52,
                            end_col_offset=81,
                            value=Call(
                                lineno=52,
                                col_offset=15,
                                end_lineno=52,
                                end_col_offset=81,
                                func=Attribute(
                                    lineno=52,
                                    col_offset=15,
                                    end_lineno=52,
                                    end_col_offset=44,
                                    value=Call(
                                        lineno=52,
                                        col_offset=15,
                                        end_lineno=52,
                                        end_col_offset=22,
                                        func=Name(lineno=52, col_offset=15, end_lineno=52, end_col_offset=20, id='super', ctx=Load()),
                                        args=[],
                                        keywords=[],
                                    ),
                                    attr='_eligible_for_qr_code',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=52, col_offset=45, end_lineno=52, end_col_offset=54, id='qr_method', ctx=Load()),
                                    Name(lineno=52, col_offset=56, end_lineno=52, end_col_offset=70, id='debtor_partner', ctx=Load()),
                                    Name(lineno=52, col_offset=72, end_lineno=52, end_col_offset=80, id='currency', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=54,
                    col_offset=4,
                    end_lineno=59,
                    end_col_offset=139,
                    name='_check_for_qr_code_errors',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=54, col_offset=34, end_lineno=54, end_col_offset=38, arg='self', annotation=None, type_comment=None),
                            arg(lineno=54, col_offset=40, end_lineno=54, end_col_offset=49, arg='qr_method', annotation=None, type_comment=None),
                            arg(lineno=54, col_offset=51, end_lineno=54, end_col_offset=57, arg='amount', annotation=None, type_comment=None),
                            arg(lineno=54, col_offset=59, end_lineno=54, end_col_offset=67, arg='currency', annotation=None, type_comment=None),
                            arg(lineno=54, col_offset=69, end_lineno=54, end_col_offset=83, arg='debtor_partner', annotation=None, type_comment=None),
                            arg(lineno=54, col_offset=85, end_lineno=54, end_col_offset=103, arg='free_communication', annotation=None, type_comment=None),
                            arg(lineno=54, col_offset=105, end_lineno=54, end_col_offset=129, arg='structured_communication', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        If(
                            lineno=55,
                            col_offset=8,
                            end_lineno=57,
                            end_col_offset=115,
                            test=Compare(
                                lineno=55,
                                col_offset=11,
                                end_lineno=55,
                                end_col_offset=32,
                                left=Name(lineno=55, col_offset=11, end_lineno=55, end_col_offset=20, id='qr_method', ctx=Load()),
                                ops=[Eq()],
                                comparators=[Constant(lineno=55, col_offset=24, end_lineno=55, end_col_offset=32, value='sct_qr', kind=None)],
                            ),
                            body=[
                                If(
                                    lineno=56,
                                    col_offset=12,
                                    end_lineno=57,
                                    end_col_offset=115,
                                    test=BoolOp(
                                        lineno=56,
                                        col_offset=15,
                                        end_lineno=56,
                                        end_col_offset=68,
                                        op=And(),
                                        values=[
                                            UnaryOp(
                                                lineno=56,
                                                col_offset=15,
                                                end_lineno=56,
                                                end_col_offset=39,
                                                op=Not(),
                                                operand=Attribute(
                                                    lineno=56,
                                                    col_offset=19,
                                                    end_lineno=56,
                                                    end_col_offset=39,
                                                    value=Name(lineno=56, col_offset=19, end_lineno=56, end_col_offset=23, id='self', ctx=Load()),
                                                    attr='acc_holder_name',
                                                    ctx=Load(),
                                                ),
                                            ),
                                            UnaryOp(
                                                lineno=56,
                                                col_offset=44,
                                                end_lineno=56,
                                                end_col_offset=68,
                                                op=Not(),
                                                operand=Attribute(
                                                    lineno=56,
                                                    col_offset=48,
                                                    end_lineno=56,
                                                    end_col_offset=68,
                                                    value=Attribute(
                                                        lineno=56,
                                                        col_offset=48,
                                                        end_lineno=56,
                                                        end_col_offset=63,
                                                        value=Name(lineno=56, col_offset=48, end_lineno=56, end_col_offset=52, id='self', ctx=Load()),
                                                        attr='partner_id',
                                                        ctx=Load(),
                                                    ),
                                                    attr='name',
                                                    ctx=Load(),
                                                ),
                                            ),
                                        ],
                                    ),
                                    body=[
                                        Return(
                                            lineno=57,
                                            col_offset=16,
                                            end_lineno=57,
                                            end_col_offset=115,
                                            value=Call(
                                                lineno=57,
                                                col_offset=23,
                                                end_lineno=57,
                                                end_col_offset=115,
                                                func=Name(lineno=57, col_offset=23, end_lineno=57, end_col_offset=24, id='_', ctx=Load()),
                                                args=[Constant(lineno=57, col_offset=25, end_lineno=57, end_col_offset=114, value='The account receiving the payment must have an account holder name or partner name set.', kind=None)],
                                                keywords=[],
                                            ),
                                        ),
                                    ],
                                    orelse=[],
                                ),
                            ],
                            orelse=[],
                        ),
                        Return(
                            lineno=59,
                            col_offset=8,
                            end_lineno=59,
                            end_col_offset=139,
                            value=Call(
                                lineno=59,
                                col_offset=15,
                                end_lineno=59,
                                end_col_offset=139,
                                func=Attribute(
                                    lineno=59,
                                    col_offset=15,
                                    end_lineno=59,
                                    end_col_offset=48,
                                    value=Call(
                                        lineno=59,
                                        col_offset=15,
                                        end_lineno=59,
                                        end_col_offset=22,
                                        func=Name(lineno=59, col_offset=15, end_lineno=59, end_col_offset=20, id='super', ctx=Load()),
                                        args=[],
                                        keywords=[],
                                    ),
                                    attr='_check_for_qr_code_errors',
                                    ctx=Load(),
                                ),
                                args=[
                                    Name(lineno=59, col_offset=49, end_lineno=59, end_col_offset=58, id='qr_method', ctx=Load()),
                                    Name(lineno=59, col_offset=60, end_lineno=59, end_col_offset=66, id='amount', ctx=Load()),
                                    Name(lineno=59, col_offset=68, end_lineno=59, end_col_offset=76, id='currency', ctx=Load()),
                                    Name(lineno=59, col_offset=78, end_lineno=59, end_col_offset=92, id='debtor_partner', ctx=Load()),
                                    Name(lineno=59, col_offset=94, end_lineno=59, end_col_offset=112, id='free_communication', ctx=Load()),
                                    Name(lineno=59, col_offset=114, end_lineno=59, end_col_offset=138, id='structured_communication', ctx=Load()),
                                ],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=62,
                    col_offset=4,
                    end_lineno=65,
                    end_col_offset=19,
                    name='_get_available_qr_methods',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=62, col_offset=34, end_lineno=62, end_col_offset=38, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=63,
                            col_offset=8,
                            end_lineno=63,
                            end_col_offset=50,
                            targets=[Name(lineno=63, col_offset=8, end_lineno=63, end_col_offset=12, id='rslt', ctx=Store())],
                            value=Call(
                                lineno=63,
                                col_offset=15,
                                end_lineno=63,
                                end_col_offset=50,
                                func=Attribute(
                                    lineno=63,
                                    col_offset=15,
                                    end_lineno=63,
                                    end_col_offset=48,
                                    value=Call(
                                        lineno=63,
                                        col_offset=15,
                                        end_lineno=63,
                                        end_col_offset=22,
                                        func=Name(lineno=63, col_offset=15, end_lineno=63, end_col_offset=20, id='super', ctx=Load()),
                                        args=[],
                                        keywords=[],
                                    ),
                                    attr='_get_available_qr_methods',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=64,
                            col_offset=8,
                            end_lineno=64,
                            end_col_offset=65,
                            value=Call(
                                lineno=64,
                                col_offset=8,
                                end_lineno=64,
                                end_col_offset=65,
                                func=Attribute(
                                    lineno=64,
                                    col_offset=8,
                                    end_lineno=64,
                                    end_col_offset=19,
                                    value=Name(lineno=64, col_offset=8, end_lineno=64, end_col_offset=12, id='rslt', ctx=Load()),
                                    attr='append',
                                    ctx=Load(),
                                ),
                                args=[
                                    Tuple(
                                        lineno=64,
                                        col_offset=20,
                                        end_lineno=64,
                                        end_col_offset=64,
                                        elts=[
                                            Constant(lineno=64, col_offset=21, end_lineno=64, end_col_offset=29, value='sct_qr', kind=None),
                                            Call(
                                                lineno=64,
                                                col_offset=31,
                                                end_lineno=64,
                                                end_col_offset=59,
                                                func=Name(lineno=64, col_offset=31, end_lineno=64, end_col_offset=32, id='_', ctx=Load()),
                                                args=[Constant(lineno=64, col_offset=33, end_lineno=64, end_col_offset=58, value='SEPA Credit Transfer QR', kind=None)],
                                                keywords=[],
                                            ),
                                            Constant(lineno=64, col_offset=61, end_lineno=64, end_col_offset=63, value=20, kind=None),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Return(
                            lineno=65,
                            col_offset=8,
                            end_lineno=65,
                            end_col_offset=19,
                            value=Name(lineno=65, col_offset=15, end_lineno=65, end_col_offset=19, id='rslt', ctx=Load()),
                        ),
                    ],
                    decorator_list=[
                        Attribute(
                            lineno=61,
                            col_offset=5,
                            end_lineno=61,
                            end_col_offset=14,
                            value=Name(lineno=61, col_offset=5, end_lineno=61, end_col_offset=8, id='api', ctx=Load()),
                            attr='model',
                            ctx=Load(),
                        ),
                    ],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
