Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=46,
            module='odoo.tests.common',
            names=[
                alias(name='tagged', asname=None),
                alias(name='HttpCase', asname=None),
            ],
            level=0,
        ),
        ClassDef(
            lineno=8,
            col_offset=0,
            end_lineno=39,
            end_col_offset=33,
            name='TestMailFullComposer',
            bases=[Name(lineno=8, col_offset=27, end_lineno=8, end_col_offset=35, id='HttpCase', ctx=Load())],
            keywords=[],
            body=[
                FunctionDef(
                    lineno=10,
                    col_offset=4,
                    end_lineno=39,
                    end_col_offset=33,
                    name='test_full_composer_tour',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=10, col_offset=32, end_lineno=10, end_col_offset=36, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Expr(
                            lineno=11,
                            col_offset=8,
                            end_lineno=17,
                            end_col_offset=10,
                            value=Call(
                                lineno=11,
                                col_offset=8,
                                end_lineno=17,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=11,
                                    col_offset=8,
                                    end_lineno=11,
                                    end_col_offset=40,
                                    value=Subscript(
                                        lineno=11,
                                        col_offset=8,
                                        end_lineno=11,
                                        end_col_offset=33,
                                        value=Attribute(
                                            lineno=11,
                                            col_offset=8,
                                            end_lineno=11,
                                            end_col_offset=16,
                                            value=Name(lineno=11, col_offset=8, end_lineno=11, end_col_offset=12, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=11, col_offset=17, end_lineno=11, end_col_offset=32, value='mail.template', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=11,
                                        col_offset=41,
                                        end_lineno=17,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=12, col_offset=12, end_lineno=12, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=13, col_offset=12, end_lineno=13, end_col_offset=24, value='partner_to', kind=None),
                                            Constant(lineno=14, col_offset=12, end_lineno=14, end_col_offset=18, value='lang', kind=None),
                                            Constant(lineno=15, col_offset=12, end_lineno=15, end_col_offset=25, value='auto_delete', kind=None),
                                            Constant(lineno=16, col_offset=12, end_lineno=16, end_col_offset=22, value='model_id', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=12, col_offset=20, end_lineno=12, end_col_offset=35, value='Test template', kind=None),
                                            Constant(lineno=13, col_offset=26, end_lineno=13, end_col_offset=40, value='${object.id}', kind=None),
                                            Constant(lineno=14, col_offset=20, end_lineno=14, end_col_offset=36, value='${object.lang}', kind=None),
                                            Constant(lineno=15, col_offset=27, end_lineno=15, end_col_offset=31, value=True, kind=None),
                                            Call(
                                                lineno=16,
                                                col_offset=24,
                                                end_lineno=16,
                                                end_col_offset=58,
                                                func=Attribute(
                                                    lineno=16,
                                                    col_offset=24,
                                                    end_lineno=16,
                                                    end_col_offset=32,
                                                    value=Name(lineno=16, col_offset=24, end_lineno=16, end_col_offset=28, id='self', ctx=Load()),
                                                    attr='ref',
                                                    ctx=Load(),
                                                ),
                                                args=[Constant(lineno=16, col_offset=33, end_lineno=16, end_col_offset=57, value='base.model_res_partner', kind=None)],
                                                keywords=[],
                                            ),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                        ),
                        Assign(
                            lineno=18,
                            col_offset=8,
                            end_lineno=26,
                            end_col_offset=10,
                            targets=[Name(lineno=18, col_offset=8, end_lineno=18, end_col_offset=17, id='test_user', ctx=Store())],
                            value=Call(
                                lineno=18,
                                col_offset=20,
                                end_lineno=26,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=18,
                                    col_offset=20,
                                    end_lineno=18,
                                    end_col_offset=48,
                                    value=Subscript(
                                        lineno=18,
                                        col_offset=20,
                                        end_lineno=18,
                                        end_col_offset=41,
                                        value=Attribute(
                                            lineno=18,
                                            col_offset=20,
                                            end_lineno=18,
                                            end_col_offset=28,
                                            value=Name(lineno=18, col_offset=20, end_lineno=18, end_col_offset=24, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=18, col_offset=29, end_lineno=18, end_col_offset=40, value='res.users', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=18,
                                        col_offset=49,
                                        end_lineno=26,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=19, col_offset=12, end_lineno=19, end_col_offset=19, value='email', kind=None),
                                            Constant(lineno=20, col_offset=12, end_lineno=20, end_col_offset=23, value='groups_id', kind=None),
                                            Constant(lineno=23, col_offset=12, end_lineno=23, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=24, col_offset=12, end_lineno=24, end_col_offset=19, value='login', kind=None),
                                            Constant(lineno=25, col_offset=12, end_lineno=25, end_col_offset=22, value='password', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=19, col_offset=21, end_lineno=19, end_col_offset=44, value='testuser@testuser.com', kind=None),
                                            List(
                                                lineno=20,
                                                col_offset=25,
                                                end_lineno=22,
                                                end_col_offset=13,
                                                elts=[
                                                    Tuple(
                                                        lineno=21,
                                                        col_offset=16,
                                                        end_lineno=21,
                                                        end_col_offset=93,
                                                        elts=[
                                                            Constant(lineno=21, col_offset=17, end_lineno=21, end_col_offset=18, value=6, kind=None),
                                                            Constant(lineno=21, col_offset=20, end_lineno=21, end_col_offset=21, value=0, kind=None),
                                                            List(
                                                                lineno=21,
                                                                col_offset=23,
                                                                end_lineno=21,
                                                                end_col_offset=92,
                                                                elts=[
                                                                    Call(
                                                                        lineno=21,
                                                                        col_offset=24,
                                                                        end_lineno=21,
                                                                        end_col_offset=51,
                                                                        func=Attribute(
                                                                            lineno=21,
                                                                            col_offset=24,
                                                                            end_lineno=21,
                                                                            end_col_offset=32,
                                                                            value=Name(lineno=21, col_offset=24, end_lineno=21, end_col_offset=28, id='self', ctx=Load()),
                                                                            attr='ref',
                                                                            ctx=Load(),
                                                                        ),
                                                                        args=[Constant(lineno=21, col_offset=33, end_lineno=21, end_col_offset=50, value='base.group_user', kind=None)],
                                                                        keywords=[],
                                                                    ),
                                                                    Call(
                                                                        lineno=21,
                                                                        col_offset=53,
                                                                        end_lineno=21,
                                                                        end_col_offset=91,
                                                                        func=Attribute(
                                                                            lineno=21,
                                                                            col_offset=53,
                                                                            end_lineno=21,
                                                                            end_col_offset=61,
                                                                            value=Name(lineno=21, col_offset=53, end_lineno=21, end_col_offset=57, id='self', ctx=Load()),
                                                                            attr='ref',
                                                                            ctx=Load(),
                                                                        ),
                                                                        args=[Constant(lineno=21, col_offset=62, end_lineno=21, end_col_offset=90, value='base.group_partner_manager', kind=None)],
                                                                        keywords=[],
                                                                    ),
                                                                ],
                                                                ctx=Load(),
                                                            ),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                            Constant(lineno=23, col_offset=20, end_lineno=23, end_col_offset=31, value='Test User', kind=None),
                                            Constant(lineno=24, col_offset=21, end_lineno=24, end_col_offset=31, value='testuser', kind=None),
                                            Constant(lineno=25, col_offset=24, end_lineno=25, end_col_offset=34, value='testuser', kind=None),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=28,
                            col_offset=8,
                            end_lineno=35,
                            end_col_offset=10,
                            targets=[Name(lineno=28, col_offset=8, end_lineno=28, end_col_offset=24, id='automated_action', ctx=Store())],
                            value=Call(
                                lineno=28,
                                col_offset=27,
                                end_lineno=35,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=28,
                                    col_offset=27,
                                    end_lineno=28,
                                    end_col_offset=61,
                                    value=Subscript(
                                        lineno=28,
                                        col_offset=27,
                                        end_lineno=28,
                                        end_col_offset=54,
                                        value=Attribute(
                                            lineno=28,
                                            col_offset=27,
                                            end_lineno=28,
                                            end_col_offset=35,
                                            value=Name(lineno=28, col_offset=27, end_lineno=28, end_col_offset=31, id='self', ctx=Load()),
                                            attr='env',
                                            ctx=Load(),
                                        ),
                                        slice=Constant(lineno=28, col_offset=36, end_lineno=28, end_col_offset=53, value='base.automation', kind=None),
                                        ctx=Load(),
                                    ),
                                    attr='create',
                                    ctx=Load(),
                                ),
                                args=[
                                    Dict(
                                        lineno=28,
                                        col_offset=62,
                                        end_lineno=35,
                                        end_col_offset=9,
                                        keys=[
                                            Constant(lineno=29, col_offset=12, end_lineno=29, end_col_offset=18, value='name', kind=None),
                                            Constant(lineno=30, col_offset=12, end_lineno=30, end_col_offset=20, value='active', kind=None),
                                            Constant(lineno=31, col_offset=12, end_lineno=31, end_col_offset=21, value='trigger', kind=None),
                                            Constant(lineno=32, col_offset=12, end_lineno=32, end_col_offset=33, value='on_change_field_ids', kind=None),
                                            Constant(lineno=33, col_offset=12, end_lineno=33, end_col_offset=19, value='state', kind=None),
                                            Constant(lineno=34, col_offset=12, end_lineno=34, end_col_offset=22, value='model_id', kind=None),
                                        ],
                                        values=[
                                            Constant(lineno=29, col_offset=20, end_lineno=29, end_col_offset=26, value='Test', kind=None),
                                            Constant(lineno=30, col_offset=22, end_lineno=30, end_col_offset=26, value=True, kind=None),
                                            Constant(lineno=31, col_offset=23, end_lineno=31, end_col_offset=34, value='on_change', kind=None),
                                            Tuple(
                                                lineno=32,
                                                col_offset=35,
                                                end_lineno=32,
                                                end_col_offset=97,
                                                elts=[
                                                    Constant(lineno=32, col_offset=36, end_lineno=32, end_col_offset=37, value=4, kind=None),
                                                    Call(
                                                        lineno=32,
                                                        col_offset=39,
                                                        end_lineno=32,
                                                        end_col_offset=95,
                                                        func=Attribute(
                                                            lineno=32,
                                                            col_offset=39,
                                                            end_lineno=32,
                                                            end_col_offset=47,
                                                            value=Name(lineno=32, col_offset=39, end_lineno=32, end_col_offset=43, id='self', ctx=Load()),
                                                            attr='ref',
                                                            ctx=Load(),
                                                        ),
                                                        args=[Constant(lineno=32, col_offset=48, end_lineno=32, end_col_offset=94, value='mail.field_mail_compose_message__template_id', kind=None)],
                                                        keywords=[],
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                            Constant(lineno=33, col_offset=21, end_lineno=33, end_col_offset=27, value='code', kind=None),
                                            Attribute(
                                                lineno=34,
                                                col_offset=24,
                                                end_lineno=34,
                                                end_col_offset=74,
                                                value=Call(
                                                    lineno=34,
                                                    col_offset=24,
                                                    end_lineno=34,
                                                    end_col_offset=71,
                                                    func=Attribute(
                                                        lineno=34,
                                                        col_offset=24,
                                                        end_lineno=34,
                                                        end_col_offset=36,
                                                        value=Attribute(
                                                            lineno=34,
                                                            col_offset=24,
                                                            end_lineno=34,
                                                            end_col_offset=32,
                                                            value=Name(lineno=34, col_offset=24, end_lineno=34, end_col_offset=28, id='self', ctx=Load()),
                                                            attr='env',
                                                            ctx=Load(),
                                                        ),
                                                        attr='ref',
                                                        ctx=Load(),
                                                    ),
                                                    args=[Constant(lineno=34, col_offset=37, end_lineno=34, end_col_offset=70, value='mail.model_mail_compose_message', kind=None)],
                                                    keywords=[],
                                                ),
                                                attr='id',
                                                ctx=Load(),
                                            ),
                                        ],
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Expr(
                            lineno=37,
                            col_offset=8,
                            end_lineno=37,
                            end_col_offset=155,
                            value=Call(
                                lineno=37,
                                col_offset=8,
                                end_lineno=37,
                                end_col_offset=155,
                                func=Attribute(
                                    lineno=37,
                                    col_offset=8,
                                    end_lineno=37,
                                    end_col_offset=23,
                                    value=Name(lineno=37, col_offset=8, end_lineno=37, end_col_offset=12, id='self', ctx=Load()),
                                    attr='start_tour',
                                    ctx=Load(),
                                ),
                                args=[
                                    BinOp(
                                        lineno=37,
                                        col_offset=24,
                                        end_lineno=37,
                                        end_col_offset=77,
                                        left=Constant(lineno=37, col_offset=24, end_lineno=37, end_col_offset=54, value='/web#id=%d&model=res.partner', kind=None),
                                        op=Mod(),
                                        right=Attribute(
                                            lineno=37,
                                            col_offset=57,
                                            end_lineno=37,
                                            end_col_offset=77,
                                            value=Name(lineno=37, col_offset=57, end_lineno=37, end_col_offset=66, id='test_user', ctx=Load()),
                                            attr='partner_id',
                                            ctx=Load(),
                                        ),
                                    ),
                                    Constant(lineno=37, col_offset=79, end_lineno=37, end_col_offset=136, value='mail/static/tests/tours/mail_full_composer_test_tour.js', kind=None),
                                ],
                                keywords=[
                                    keyword(
                                        lineno=37,
                                        col_offset=138,
                                        end_lineno=37,
                                        end_col_offset=154,
                                        arg='login',
                                        value=Constant(lineno=37, col_offset=144, end_lineno=37, end_col_offset=154, value='testuser', kind=None),
                                    ),
                                ],
                            ),
                        ),
                        Expr(
                            lineno=39,
                            col_offset=8,
                            end_lineno=39,
                            end_col_offset=33,
                            value=Call(
                                lineno=39,
                                col_offset=8,
                                end_lineno=39,
                                end_col_offset=33,
                                func=Attribute(
                                    lineno=39,
                                    col_offset=8,
                                    end_lineno=39,
                                    end_col_offset=31,
                                    value=Name(lineno=39, col_offset=8, end_lineno=39, end_col_offset=24, id='automated_action', ctx=Load()),
                                    attr='unlink',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[],
                            ),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[
                Call(
                    lineno=7,
                    col_offset=1,
                    end_lineno=7,
                    end_col_offset=55,
                    func=Name(lineno=7, col_offset=1, end_lineno=7, end_col_offset=7, id='tagged', ctx=Load()),
                    args=[
                        Constant(lineno=7, col_offset=8, end_lineno=7, end_col_offset=21, value='-at_install', kind=None),
                        Constant(lineno=7, col_offset=23, end_lineno=7, end_col_offset=37, value='post_install', kind=None),
                        Constant(lineno=7, col_offset=39, end_lineno=7, end_col_offset=54, value='mail_composer', kind=None),
                    ],
                    keywords=[],
                ),
            ],
        ),
    ],
    type_ignores=[],
)
