Module(
    body=[
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=35,
            module='collections',
            names=[alias(name='defaultdict', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=5,
            col_offset=0,
            end_lineno=5,
            end_col_offset=31,
            module='operator',
            names=[alias(name='itemgetter', asname=None)],
            level=0,
        ),
        ImportFrom(
            lineno=7,
            col_offset=0,
            end_lineno=7,
            end_col_offset=43,
            module='odoo',
            names=[
                alias(name='exceptions', asname=None),
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
            ],
            level=0,
        ),
        ImportFrom(
            lineno=8,
            col_offset=0,
            end_lineno=8,
            end_col_offset=30,
            module='odoo.tools',
            names=[alias(name='groupby', asname=None)],
            level=0,
        ),
        ClassDef(
            lineno=11,
            col_offset=0,
            end_lineno=55,
            end_col_offset=29,
            name='MailMessage',
            bases=[
                Attribute(
                    lineno=11,
                    col_offset=18,
                    end_lineno=11,
                    end_col_offset=30,
                    value=Name(lineno=11, col_offset=18, end_lineno=11, end_col_offset=24, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Expr(
                    lineno=12,
                    col_offset=4,
                    end_lineno=14,
                    end_col_offset=16,
                    value=Constant(lineno=12, col_offset=4, end_lineno=14, end_col_offset=16, value=' Override MailMessage class in order to add a new type: SMS messages.\n    Those messages comes with their own notification method, using SMS\n    gateway. ', kind=None),
                ),
                Assign(
                    lineno=15,
                    col_offset=4,
                    end_lineno=15,
                    end_col_offset=29,
                    targets=[Name(lineno=15, col_offset=4, end_lineno=15, end_col_offset=12, id='_inherit', ctx=Store())],
                    value=Constant(lineno=15, col_offset=15, end_lineno=15, end_col_offset=29, value='mail.message', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=17,
                    col_offset=4,
                    end_lineno=19,
                    end_col_offset=76,
                    targets=[Name(lineno=17, col_offset=4, end_lineno=17, end_col_offset=16, id='message_type', ctx=Store())],
                    value=Call(
                        lineno=17,
                        col_offset=19,
                        end_lineno=19,
                        end_col_offset=76,
                        func=Attribute(
                            lineno=17,
                            col_offset=19,
                            end_lineno=17,
                            end_col_offset=35,
                            value=Name(lineno=17, col_offset=19, end_lineno=17, end_col_offset=25, id='fields', ctx=Load()),
                            attr='Selection',
                            ctx=Load(),
                        ),
                        args=[],
                        keywords=[
                            keyword(
                                lineno=17,
                                col_offset=36,
                                end_lineno=19,
                                end_col_offset=5,
                                arg='selection_add',
                                value=List(
                                    lineno=17,
                                    col_offset=50,
                                    end_lineno=19,
                                    end_col_offset=5,
                                    elts=[
                                        Tuple(
                                            lineno=18,
                                            col_offset=8,
                                            end_lineno=18,
                                            end_col_offset=22,
                                            elts=[
                                                Constant(lineno=18, col_offset=9, end_lineno=18, end_col_offset=14, value='sms', kind=None),
                                                Constant(lineno=18, col_offset=16, end_lineno=18, end_col_offset=21, value='SMS', kind=None),
                                            ],
                                            ctx=Load(),
                                        ),
                                    ],
                                    ctx=Load(),
                                ),
                            ),
                            keyword(
                                lineno=19,
                                col_offset=7,
                                end_lineno=19,
                                end_col_offset=75,
                                arg='ondelete',
                                value=Dict(
                                    lineno=19,
                                    col_offset=16,
                                    end_lineno=19,
                                    end_col_offset=75,
                                    keys=[Constant(lineno=19, col_offset=17, end_lineno=19, end_col_offset=22, value='sms', kind=None)],
                                    values=[
                                        Lambda(
                                            lineno=19,
                                            col_offset=24,
                                            end_lineno=19,
                                            end_col_offset=74,
                                            args=arguments(
                                                posonlyargs=[],
                                                args=[arg(lineno=19, col_offset=31, end_lineno=19, end_col_offset=35, arg='recs', annotation=None, type_comment=None)],
                                                vararg=None,
                                                kwonlyargs=[],
                                                kw_defaults=[],
                                                kwarg=None,
                                                defaults=[],
                                            ),
                                            body=Call(
                                                lineno=19,
                                                col_offset=37,
                                                end_lineno=19,
                                                end_col_offset=74,
                                                func=Attribute(
                                                    lineno=19,
                                                    col_offset=37,
                                                    end_lineno=19,
                                                    end_col_offset=47,
                                                    value=Name(lineno=19, col_offset=37, end_lineno=19, end_col_offset=41, id='recs', ctx=Load()),
                                                    attr='write',
                                                    ctx=Load(),
                                                ),
                                                args=[
                                                    Dict(
                                                        lineno=19,
                                                        col_offset=48,
                                                        end_lineno=19,
                                                        end_col_offset=73,
                                                        keys=[Constant(lineno=19, col_offset=49, end_lineno=19, end_col_offset=63, value='message_type', kind=None)],
                                                        values=[Constant(lineno=19, col_offset=65, end_lineno=19, end_col_offset=72, value='email', kind=None)],
                                                    ),
                                                ],
                                                keywords=[],
                                            ),
                                        ),
                                    ],
                                ),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=20,
                    col_offset=4,
                    end_lineno=22,
                    end_col_offset=25,
                    targets=[Name(lineno=20, col_offset=4, end_lineno=20, end_col_offset=17, id='has_sms_error', ctx=Store())],
                    value=Call(
                        lineno=20,
                        col_offset=20,
                        end_lineno=22,
                        end_col_offset=25,
                        func=Attribute(
                            lineno=20,
                            col_offset=20,
                            end_lineno=20,
                            end_col_offset=34,
                            value=Name(lineno=20, col_offset=20, end_lineno=20, end_col_offset=26, id='fields', ctx=Load()),
                            attr='Boolean',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=21, col_offset=8, end_lineno=21, end_col_offset=23, value='Has SMS error', kind=None)],
                        keywords=[
                            keyword(
                                lineno=21,
                                col_offset=25,
                                end_lineno=21,
                                end_col_offset=57,
                                arg='compute',
                                value=Constant(lineno=21, col_offset=33, end_lineno=21, end_col_offset=57, value='_compute_has_sms_error', kind=None),
                            ),
                            keyword(
                                lineno=21,
                                col_offset=59,
                                end_lineno=21,
                                end_col_offset=89,
                                arg='search',
                                value=Constant(lineno=21, col_offset=66, end_lineno=21, end_col_offset=89, value='_search_has_sms_error', kind=None),
                            ),
                            keyword(
                                lineno=22,
                                col_offset=8,
                                end_lineno=22,
                                end_col_offset=24,
                                arg='help',
                                value=Constant(lineno=22, col_offset=13, end_lineno=22, end_col_offset=24, value='Has error', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=24,
                    col_offset=4,
                    end_lineno=30,
                    end_col_offset=74,
                    name='_compute_has_sms_error',
                    args=arguments(
                        posonlyargs=[],
                        args=[arg(lineno=24, col_offset=31, end_lineno=24, end_col_offset=35, arg='self', annotation=None, type_comment=None)],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        Assign(
                            lineno=25,
                            col_offset=8,
                            end_lineno=28,
                            end_col_offset=81,
                            targets=[Name(lineno=25, col_offset=8, end_lineno=25, end_col_offset=35, id='sms_error_from_notification', ctx=Store())],
                            value=Call(
                                lineno=25,
                                col_offset=38,
                                end_lineno=28,
                                end_col_offset=81,
                                func=Attribute(
                                    lineno=25,
                                    col_offset=38,
                                    end_lineno=28,
                                    end_col_offset=62,
                                    value=Call(
                                        lineno=25,
                                        col_offset=38,
                                        end_lineno=28,
                                        end_col_offset=55,
                                        func=Attribute(
                                            lineno=25,
                                            col_offset=38,
                                            end_lineno=25,
                                            end_col_offset=81,
                                            value=Call(
                                                lineno=25,
                                                col_offset=38,
                                                end_lineno=25,
                                                end_col_offset=74,
                                                func=Attribute(
                                                    lineno=25,
                                                    col_offset=38,
                                                    end_lineno=25,
                                                    end_col_offset=72,
                                                    value=Subscript(
                                                        lineno=25,
                                                        col_offset=38,
                                                        end_lineno=25,
                                                        end_col_offset=67,
                                                        value=Attribute(
                                                            lineno=25,
                                                            col_offset=38,
                                                            end_lineno=25,
                                                            end_col_offset=46,
                                                            value=Name(lineno=25, col_offset=38, end_lineno=25, end_col_offset=42, id='self', ctx=Load()),
                                                            attr='env',
                                                            ctx=Load(),
                                                        ),
                                                        slice=Constant(lineno=25, col_offset=47, end_lineno=25, end_col_offset=66, value='mail.notification', kind=None),
                                                        ctx=Load(),
                                                    ),
                                                    attr='sudo',
                                                    ctx=Load(),
                                                ),
                                                args=[],
                                                keywords=[],
                                            ),
                                            attr='search',
                                            ctx=Load(),
                                        ),
                                        args=[
                                            List(
                                                lineno=25,
                                                col_offset=82,
                                                end_lineno=28,
                                                end_col_offset=54,
                                                elts=[
                                                    Tuple(
                                                        lineno=26,
                                                        col_offset=12,
                                                        end_lineno=26,
                                                        end_col_offset=45,
                                                        elts=[
                                                            Constant(lineno=26, col_offset=13, end_lineno=26, end_col_offset=32, value='notification_type', kind=None),
                                                            Constant(lineno=26, col_offset=34, end_lineno=26, end_col_offset=37, value='=', kind=None),
                                                            Constant(lineno=26, col_offset=39, end_lineno=26, end_col_offset=44, value='sms', kind=None),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                    Tuple(
                                                        lineno=27,
                                                        col_offset=12,
                                                        end_lineno=27,
                                                        end_col_offset=47,
                                                        elts=[
                                                            Constant(lineno=27, col_offset=13, end_lineno=27, end_col_offset=30, value='mail_message_id', kind=None),
                                                            Constant(lineno=27, col_offset=32, end_lineno=27, end_col_offset=36, value='in', kind=None),
                                                            Attribute(
                                                                lineno=27,
                                                                col_offset=38,
                                                                end_lineno=27,
                                                                end_col_offset=46,
                                                                value=Name(lineno=27, col_offset=38, end_lineno=27, end_col_offset=42, id='self', ctx=Load()),
                                                                attr='ids',
                                                                ctx=Load(),
                                                            ),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                    Tuple(
                                                        lineno=28,
                                                        col_offset=12,
                                                        end_lineno=28,
                                                        end_col_offset=53,
                                                        elts=[
                                                            Constant(lineno=28, col_offset=13, end_lineno=28, end_col_offset=34, value='notification_status', kind=None),
                                                            Constant(lineno=28, col_offset=36, end_lineno=28, end_col_offset=39, value='=', kind=None),
                                                            Constant(lineno=28, col_offset=41, end_lineno=28, end_col_offset=52, value='exception', kind=None),
                                                        ],
                                                        ctx=Load(),
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='mapped',
                                    ctx=Load(),
                                ),
                                args=[Constant(lineno=28, col_offset=63, end_lineno=28, end_col_offset=80, value='mail_message_id', kind=None)],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        For(
                            lineno=29,
                            col_offset=8,
                            end_lineno=30,
                            end_col_offset=74,
                            target=Name(lineno=29, col_offset=12, end_lineno=29, end_col_offset=19, id='message', ctx=Store()),
                            iter=Name(lineno=29, col_offset=23, end_lineno=29, end_col_offset=27, id='self', ctx=Load()),
                            body=[
                                Assign(
                                    lineno=30,
                                    col_offset=12,
                                    end_lineno=30,
                                    end_col_offset=74,
                                    targets=[
                                        Attribute(
                                            lineno=30,
                                            col_offset=12,
                                            end_lineno=30,
                                            end_col_offset=33,
                                            value=Name(lineno=30, col_offset=12, end_lineno=30, end_col_offset=19, id='message', ctx=Load()),
                                            attr='has_sms_error',
                                            ctx=Store(),
                                        ),
                                    ],
                                    value=Compare(
                                        lineno=30,
                                        col_offset=36,
                                        end_lineno=30,
                                        end_col_offset=74,
                                        left=Name(lineno=30, col_offset=36, end_lineno=30, end_col_offset=43, id='message', ctx=Load()),
                                        ops=[In()],
                                        comparators=[Name(lineno=30, col_offset=47, end_lineno=30, end_col_offset=74, id='sms_error_from_notification', ctx=Load())],
                                    ),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[],
                            type_comment=None,
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=32,
                    col_offset=4,
                    end_lineno=35,
                    end_col_offset=35,
                    name='_search_has_sms_error',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=32, col_offset=30, end_lineno=32, end_col_offset=34, arg='self', annotation=None, type_comment=None),
                            arg(lineno=32, col_offset=36, end_lineno=32, end_col_offset=44, arg='operator', annotation=None, type_comment=None),
                            arg(lineno=32, col_offset=46, end_lineno=32, end_col_offset=53, arg='operand', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[],
                    ),
                    body=[
                        If(
                            lineno=33,
                            col_offset=8,
                            end_lineno=34,
                            end_col_offset=136,
                            test=BoolOp(
                                lineno=33,
                                col_offset=11,
                                end_lineno=33,
                                end_col_offset=38,
                                op=And(),
                                values=[
                                    Compare(
                                        lineno=33,
                                        col_offset=11,
                                        end_lineno=33,
                                        end_col_offset=26,
                                        left=Name(lineno=33, col_offset=11, end_lineno=33, end_col_offset=19, id='operator', ctx=Load()),
                                        ops=[Eq()],
                                        comparators=[Constant(lineno=33, col_offset=23, end_lineno=33, end_col_offset=26, value='=', kind=None)],
                                    ),
                                    Name(lineno=33, col_offset=31, end_lineno=33, end_col_offset=38, id='operand', ctx=Load()),
                                ],
                            ),
                            body=[
                                Return(
                                    lineno=34,
                                    col_offset=12,
                                    end_lineno=34,
                                    end_col_offset=136,
                                    value=List(
                                        lineno=34,
                                        col_offset=19,
                                        end_lineno=34,
                                        end_col_offset=136,
                                        elts=[
                                            Constant(lineno=34, col_offset=20, end_lineno=34, end_col_offset=23, value='&', kind=None),
                                            Tuple(
                                                lineno=34,
                                                col_offset=25,
                                                end_lineno=34,
                                                end_col_offset=83,
                                                elts=[
                                                    Constant(lineno=34, col_offset=26, end_lineno=34, end_col_offset=64, value='notification_ids.notification_status', kind=None),
                                                    Constant(lineno=34, col_offset=66, end_lineno=34, end_col_offset=69, value='=', kind=None),
                                                    Constant(lineno=34, col_offset=71, end_lineno=34, end_col_offset=82, value='exception', kind=None),
                                                ],
                                                ctx=Load(),
                                            ),
                                            Tuple(
                                                lineno=34,
                                                col_offset=85,
                                                end_lineno=34,
                                                end_col_offset=135,
                                                elts=[
                                                    Constant(lineno=34, col_offset=86, end_lineno=34, end_col_offset=122, value='notification_ids.notification_type', kind=None),
                                                    Constant(lineno=34, col_offset=124, end_lineno=34, end_col_offset=127, value='=', kind=None),
                                                    Constant(lineno=34, col_offset=129, end_lineno=34, end_col_offset=134, value='sms', kind=None),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                ),
                            ],
                            orelse=[],
                        ),
                        Raise(
                            lineno=35,
                            col_offset=8,
                            end_lineno=35,
                            end_col_offset=35,
                            exc=Call(
                                lineno=35,
                                col_offset=14,
                                end_lineno=35,
                                end_col_offset=35,
                                func=Name(lineno=35, col_offset=14, end_lineno=35, end_col_offset=33, id='NotImplementedError', ctx=Load()),
                                args=[],
                                keywords=[],
                            ),
                            cause=None,
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
                FunctionDef(
                    lineno=37,
                    col_offset=4,
                    end_lineno=55,
                    end_col_offset=29,
                    name='message_format',
                    args=arguments(
                        posonlyargs=[],
                        args=[
                            arg(lineno=37, col_offset=23, end_lineno=37, end_col_offset=27, arg='self', annotation=None, type_comment=None),
                            arg(lineno=37, col_offset=29, end_lineno=37, end_col_offset=41, arg='format_reply', annotation=None, type_comment=None),
                        ],
                        vararg=None,
                        kwonlyargs=[],
                        kw_defaults=[],
                        kwarg=None,
                        defaults=[Constant(lineno=37, col_offset=42, end_lineno=37, end_col_offset=46, value=True, kind=None)],
                    ),
                    body=[
                        Expr(
                            lineno=38,
                            col_offset=8,
                            end_lineno=42,
                            end_col_offset=11,
                            value=Constant(lineno=38, col_offset=8, end_lineno=42, end_col_offset=11, value=' Override in order to retrieves data about SMS (recipient name and\n            SMS status)\n\n        TDE FIXME: clean the overall message_format thingy\n        ', kind=None),
                        ),
                        Assign(
                            lineno=43,
                            col_offset=8,
                            end_lineno=43,
                            end_col_offset=91,
                            targets=[Name(lineno=43, col_offset=8, end_lineno=43, end_col_offset=22, id='message_values', ctx=Store())],
                            value=Call(
                                lineno=43,
                                col_offset=25,
                                end_lineno=43,
                                end_col_offset=91,
                                func=Attribute(
                                    lineno=43,
                                    col_offset=25,
                                    end_lineno=43,
                                    end_col_offset=64,
                                    value=Call(
                                        lineno=43,
                                        col_offset=25,
                                        end_lineno=43,
                                        end_col_offset=49,
                                        func=Name(lineno=43, col_offset=25, end_lineno=43, end_col_offset=30, id='super', ctx=Load()),
                                        args=[
                                            Name(lineno=43, col_offset=31, end_lineno=43, end_col_offset=42, id='MailMessage', ctx=Load()),
                                            Name(lineno=43, col_offset=44, end_lineno=43, end_col_offset=48, id='self', ctx=Load()),
                                        ],
                                        keywords=[],
                                    ),
                                    attr='message_format',
                                    ctx=Load(),
                                ),
                                args=[],
                                keywords=[
                                    keyword(
                                        lineno=43,
                                        col_offset=65,
                                        end_lineno=43,
                                        end_col_offset=90,
                                        arg='format_reply',
                                        value=Name(lineno=43, col_offset=78, end_lineno=43, end_col_offset=90, id='format_reply', ctx=Load()),
                                    ),
                                ],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=44,
                            col_offset=8,
                            end_lineno=47,
                            end_col_offset=10,
                            targets=[Name(lineno=44, col_offset=8, end_lineno=44, end_col_offset=29, id='all_sms_notifications', ctx=Store())],
                            value=Call(
                                lineno=44,
                                col_offset=32,
                                end_lineno=47,
                                end_col_offset=10,
                                func=Attribute(
                                    lineno=44,
                                    col_offset=32,
                                    end_lineno=44,
                                    end_col_offset=75,
                                    value=Call(
                                        lineno=44,
                                        col_offset=32,
                                        end_lineno=44,
                                        end_col_offset=68,
                                        func=Attribute(
                                            lineno=44,
                                            col_offset=32,
                                            end_lineno=44,
                                            end_col_offset=66,
                                            value=Subscript(
                                                lineno=44,
                                                col_offset=32,
                                                end_lineno=44,
                                                end_col_offset=61,
                                                value=Attribute(
                                                    lineno=44,
                                                    col_offset=32,
                                                    end_lineno=44,
                                                    end_col_offset=40,
                                                    value=Name(lineno=44, col_offset=32, end_lineno=44, end_col_offset=36, id='self', ctx=Load()),
                                                    attr='env',
                                                    ctx=Load(),
                                                ),
                                                slice=Constant(lineno=44, col_offset=41, end_lineno=44, end_col_offset=60, value='mail.notification', kind=None),
                                                ctx=Load(),
                                            ),
                                            attr='sudo',
                                            ctx=Load(),
                                        ),
                                        args=[],
                                        keywords=[],
                                    ),
                                    attr='search',
                                    ctx=Load(),
                                ),
                                args=[
                                    List(
                                        lineno=44,
                                        col_offset=76,
                                        end_lineno=47,
                                        end_col_offset=9,
                                        elts=[
                                            Tuple(
                                                lineno=45,
                                                col_offset=12,
                                                end_lineno=45,
                                                end_col_offset=72,
                                                elts=[
                                                    Constant(lineno=45, col_offset=13, end_lineno=45, end_col_offset=30, value='mail_message_id', kind=None),
                                                    Constant(lineno=45, col_offset=32, end_lineno=45, end_col_offset=36, value='in', kind=None),
                                                    ListComp(
                                                        lineno=45,
                                                        col_offset=38,
                                                        end_lineno=45,
                                                        end_col_offset=71,
                                                        elt=Subscript(
                                                            lineno=45,
                                                            col_offset=39,
                                                            end_lineno=45,
                                                            end_col_offset=46,
                                                            value=Name(lineno=45, col_offset=39, end_lineno=45, end_col_offset=40, id='r', ctx=Load()),
                                                            slice=Constant(lineno=45, col_offset=41, end_lineno=45, end_col_offset=45, value='id', kind=None),
                                                            ctx=Load(),
                                                        ),
                                                        generators=[
                                                            comprehension(
                                                                target=Name(lineno=45, col_offset=51, end_lineno=45, end_col_offset=52, id='r', ctx=Store()),
                                                                iter=Name(lineno=45, col_offset=56, end_lineno=45, end_col_offset=70, id='message_values', ctx=Load()),
                                                                ifs=[],
                                                                is_async=0,
                                                            ),
                                                        ],
                                                    ),
                                                ],
                                                ctx=Load(),
                                            ),
                                            Tuple(
                                                lineno=46,
                                                col_offset=12,
                                                end_lineno=46,
                                                end_col_offset=45,
                                                elts=[
                                                    Constant(lineno=46, col_offset=13, end_lineno=46, end_col_offset=32, value='notification_type', kind=None),
                                                    Constant(lineno=46, col_offset=34, end_lineno=46, end_col_offset=37, value='=', kind=None),
                                                    Constant(lineno=46, col_offset=39, end_lineno=46, end_col_offset=44, value='sms', kind=None),
                                                ],
                                                ctx=Load(),
                                            ),
                                        ],
                                        ctx=Load(),
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        Assign(
                            lineno=48,
                            col_offset=8,
                            end_lineno=48,
                            end_col_offset=82,
                            targets=[Name(lineno=48, col_offset=8, end_lineno=48, end_col_offset=22, id='msgid_to_notif', ctx=Store())],
                            value=Call(
                                lineno=48,
                                col_offset=25,
                                end_lineno=48,
                                end_col_offset=82,
                                func=Name(lineno=48, col_offset=25, end_lineno=48, end_col_offset=36, id='defaultdict', ctx=Load()),
                                args=[
                                    Lambda(
                                        lineno=48,
                                        col_offset=37,
                                        end_lineno=48,
                                        end_col_offset=81,
                                        args=arguments(posonlyargs=[], args=[], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]),
                                        body=Call(
                                            lineno=48,
                                            col_offset=45,
                                            end_lineno=48,
                                            end_col_offset=81,
                                            func=Attribute(
                                                lineno=48,
                                                col_offset=45,
                                                end_lineno=48,
                                                end_col_offset=79,
                                                value=Subscript(
                                                    lineno=48,
                                                    col_offset=45,
                                                    end_lineno=48,
                                                    end_col_offset=74,
                                                    value=Attribute(
                                                        lineno=48,
                                                        col_offset=45,
                                                        end_lineno=48,
                                                        end_col_offset=53,
                                                        value=Name(lineno=48, col_offset=45, end_lineno=48, end_col_offset=49, id='self', ctx=Load()),
                                                        attr='env',
                                                        ctx=Load(),
                                                    ),
                                                    slice=Constant(lineno=48, col_offset=54, end_lineno=48, end_col_offset=73, value='mail.notification', kind=None),
                                                    ctx=Load(),
                                                ),
                                                attr='sudo',
                                                ctx=Load(),
                                            ),
                                            args=[],
                                            keywords=[],
                                        ),
                                    ),
                                ],
                                keywords=[],
                            ),
                            type_comment=None,
                        ),
                        For(
                            lineno=49,
                            col_offset=8,
                            end_lineno=50,
                            end_col_offset=61,
                            target=Name(lineno=49, col_offset=12, end_lineno=49, end_col_offset=17, id='notif', ctx=Store()),
                            iter=Name(lineno=49, col_offset=21, end_lineno=49, end_col_offset=42, id='all_sms_notifications', ctx=Load()),
                            body=[
                                AugAssign(
                                    lineno=50,
                                    col_offset=12,
                                    end_lineno=50,
                                    end_col_offset=61,
                                    target=Subscript(
                                        lineno=50,
                                        col_offset=12,
                                        end_lineno=50,
                                        end_col_offset=52,
                                        value=Name(lineno=50, col_offset=12, end_lineno=50, end_col_offset=26, id='msgid_to_notif', ctx=Load()),
                                        slice=Attribute(
                                            lineno=50,
                                            col_offset=27,
                                            end_lineno=50,
                                            end_col_offset=51,
                                            value=Attribute(
                                                lineno=50,
                                                col_offset=27,
                                                end_lineno=50,
                                                end_col_offset=48,
                                                value=Name(lineno=50, col_offset=27, end_lineno=50, end_col_offset=32, id='notif', ctx=Load()),
                                                attr='mail_message_id',
                                                ctx=Load(),
                                            ),
                                            attr='id',
                                            ctx=Load(),
                                        ),
                                        ctx=Store(),
                                    ),
                                    op=Add(),
                                    value=Name(lineno=50, col_offset=56, end_lineno=50, end_col_offset=61, id='notif', ctx=Load()),
                                ),
                            ],
                            orelse=[],
                            type_comment=None,
                        ),
                        For(
                            lineno=52,
                            col_offset=8,
                            end_lineno=54,
                            end_col_offset=50,
                            target=Name(lineno=52, col_offset=12, end_lineno=52, end_col_offset=19, id='message', ctx=Store()),
                            iter=Name(lineno=52, col_offset=23, end_lineno=52, end_col_offset=37, id='message_values', ctx=Load()),
                            body=[
                                Assign(
                                    lineno=53,
                                    col_offset=12,
                                    end_lineno=53,
                                    end_col_offset=177,
                                    targets=[Name(lineno=53, col_offset=12, end_lineno=53, end_col_offset=29, id='customer_sms_data', ctx=Store())],
                                    value=ListComp(
                                        lineno=53,
                                        col_offset=32,
                                        end_lineno=53,
                                        end_col_offset=177,
                                        elt=Tuple(
                                            lineno=53,
                                            col_offset=33,
                                            end_lineno=53,
                                            end_col_offset=125,
                                            elts=[
                                                Attribute(
                                                    lineno=53,
                                                    col_offset=34,
                                                    end_lineno=53,
                                                    end_col_offset=42,
                                                    value=Name(lineno=53, col_offset=34, end_lineno=53, end_col_offset=39, id='notif', ctx=Load()),
                                                    attr='id',
                                                    ctx=Load(),
                                                ),
                                                BoolOp(
                                                    lineno=53,
                                                    col_offset=44,
                                                    end_lineno=53,
                                                    end_col_offset=97,
                                                    op=Or(),
                                                    values=[
                                                        Attribute(
                                                            lineno=53,
                                                            col_offset=44,
                                                            end_lineno=53,
                                                            end_col_offset=77,
                                                            value=Attribute(
                                                                lineno=53,
                                                                col_offset=44,
                                                                end_lineno=53,
                                                                end_col_offset=64,
                                                                value=Name(lineno=53, col_offset=44, end_lineno=53, end_col_offset=49, id='notif', ctx=Load()),
                                                                attr='res_partner_id',
                                                                ctx=Load(),
                                                            ),
                                                            attr='display_name',
                                                            ctx=Load(),
                                                        ),
                                                        Attribute(
                                                            lineno=53,
                                                            col_offset=81,
                                                            end_lineno=53,
                                                            end_col_offset=97,
                                                            value=Name(lineno=53, col_offset=81, end_lineno=53, end_col_offset=86, id='notif', ctx=Load()),
                                                            attr='sms_number',
                                                            ctx=Load(),
                                                        ),
                                                    ],
                                                ),
                                                Attribute(
                                                    lineno=53,
                                                    col_offset=99,
                                                    end_lineno=53,
                                                    end_col_offset=124,
                                                    value=Name(lineno=53, col_offset=99, end_lineno=53, end_col_offset=104, id='notif', ctx=Load()),
                                                    attr='notification_status',
                                                    ctx=Load(),
                                                ),
                                            ],
                                            ctx=Load(),
                                        ),
                                        generators=[
                                            comprehension(
                                                target=Name(lineno=53, col_offset=130, end_lineno=53, end_col_offset=135, id='notif', ctx=Store()),
                                                iter=Call(
                                                    lineno=53,
                                                    col_offset=139,
                                                    end_lineno=53,
                                                    end_col_offset=176,
                                                    func=Attribute(
                                                        lineno=53,
                                                        col_offset=139,
                                                        end_lineno=53,
                                                        end_col_offset=157,
                                                        value=Name(lineno=53, col_offset=139, end_lineno=53, end_col_offset=153, id='msgid_to_notif', ctx=Load()),
                                                        attr='get',
                                                        ctx=Load(),
                                                    ),
                                                    args=[
                                                        Subscript(
                                                            lineno=53,
                                                            col_offset=158,
                                                            end_lineno=53,
                                                            end_col_offset=171,
                                                            value=Name(lineno=53, col_offset=158, end_lineno=53, end_col_offset=165, id='message', ctx=Load()),
                                                            slice=Constant(lineno=53, col_offset=166, end_lineno=53, end_col_offset=170, value='id', kind=None),
                                                            ctx=Load(),
                                                        ),
                                                        List(lineno=53, col_offset=173, end_lineno=53, end_col_offset=175, elts=[], ctx=Load()),
                                                    ],
                                                    keywords=[],
                                                ),
                                                ifs=[],
                                                is_async=0,
                                            ),
                                        ],
                                    ),
                                    type_comment=None,
                                ),
                                Assign(
                                    lineno=54,
                                    col_offset=12,
                                    end_lineno=54,
                                    end_col_offset=50,
                                    targets=[
                                        Subscript(
                                            lineno=54,
                                            col_offset=12,
                                            end_lineno=54,
                                            end_col_offset=30,
                                            value=Name(lineno=54, col_offset=12, end_lineno=54, end_col_offset=19, id='message', ctx=Load()),
                                            slice=Constant(lineno=54, col_offset=20, end_lineno=54, end_col_offset=29, value='sms_ids', kind=None),
                                            ctx=Store(),
                                        ),
                                    ],
                                    value=Name(lineno=54, col_offset=33, end_lineno=54, end_col_offset=50, id='customer_sms_data', ctx=Load()),
                                    type_comment=None,
                                ),
                            ],
                            orelse=[],
                            type_comment=None,
                        ),
                        Return(
                            lineno=55,
                            col_offset=8,
                            end_lineno=55,
                            end_col_offset=29,
                            value=Name(lineno=55, col_offset=15, end_lineno=55, end_col_offset=29, id='message_values', ctx=Load()),
                        ),
                    ],
                    decorator_list=[],
                    returns=None,
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
