Module(
    body=[
        ImportFrom(
            lineno=3,
            col_offset=0,
            end_lineno=3,
            end_col_offset=31,
            module='odoo',
            names=[
                alias(name='fields', asname=None),
                alias(name='models', asname=None),
            ],
            level=0,
        ),
        ImportFrom(
            lineno=4,
            col_offset=0,
            end_lineno=4,
            end_col_offset=47,
            module='odoo.tools.translate',
            names=[alias(name='html_translate', asname=None)],
            level=0,
        ),
        ClassDef(
            lineno=7,
            col_offset=0,
            end_lineno=22,
            end_col_offset=61,
            name='DigestTip',
            bases=[
                Attribute(
                    lineno=7,
                    col_offset=16,
                    end_lineno=7,
                    end_col_offset=28,
                    value=Name(lineno=7, col_offset=16, end_lineno=7, end_col_offset=22, id='models', ctx=Load()),
                    attr='Model',
                    ctx=Load(),
                ),
            ],
            keywords=[],
            body=[
                Assign(
                    lineno=8,
                    col_offset=4,
                    end_lineno=8,
                    end_col_offset=24,
                    targets=[Name(lineno=8, col_offset=4, end_lineno=8, end_col_offset=9, id='_name', ctx=Store())],
                    value=Constant(lineno=8, col_offset=12, end_lineno=8, end_col_offset=24, value='digest.tip', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=9,
                    col_offset=4,
                    end_lineno=9,
                    end_col_offset=32,
                    targets=[Name(lineno=9, col_offset=4, end_lineno=9, end_col_offset=16, id='_description', ctx=Store())],
                    value=Constant(lineno=9, col_offset=19, end_lineno=9, end_col_offset=32, value='Digest Tips', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=10,
                    col_offset=4,
                    end_lineno=10,
                    end_col_offset=23,
                    targets=[Name(lineno=10, col_offset=4, end_lineno=10, end_col_offset=10, id='_order', ctx=Store())],
                    value=Constant(lineno=10, col_offset=13, end_lineno=10, end_col_offset=23, value='sequence', kind=None),
                    type_comment=None,
                ),
                Assign(
                    lineno=12,
                    col_offset=4,
                    end_lineno=14,
                    end_col_offset=74,
                    targets=[Name(lineno=12, col_offset=4, end_lineno=12, end_col_offset=12, id='sequence', ctx=Store())],
                    value=Call(
                        lineno=12,
                        col_offset=15,
                        end_lineno=14,
                        end_col_offset=74,
                        func=Attribute(
                            lineno=12,
                            col_offset=15,
                            end_lineno=12,
                            end_col_offset=29,
                            value=Name(lineno=12, col_offset=15, end_lineno=12, end_col_offset=21, id='fields', ctx=Load()),
                            attr='Integer',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=13, col_offset=8, end_lineno=13, end_col_offset=18, value='Sequence', kind=None)],
                        keywords=[
                            keyword(
                                lineno=13,
                                col_offset=20,
                                end_lineno=13,
                                end_col_offset=29,
                                arg='default',
                                value=Constant(lineno=13, col_offset=28, end_lineno=13, end_col_offset=29, value=1, kind=None),
                            ),
                            keyword(
                                lineno=14,
                                col_offset=8,
                                end_lineno=14,
                                end_col_offset=73,
                                arg='help',
                                value=Constant(lineno=14, col_offset=13, end_lineno=14, end_col_offset=73, value='Used to display digest tip in email template base on order', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=15,
                    col_offset=4,
                    end_lineno=15,
                    end_col_offset=46,
                    targets=[Name(lineno=15, col_offset=4, end_lineno=15, end_col_offset=8, id='name', ctx=Store())],
                    value=Call(
                        lineno=15,
                        col_offset=11,
                        end_lineno=15,
                        end_col_offset=46,
                        func=Attribute(
                            lineno=15,
                            col_offset=11,
                            end_lineno=15,
                            end_col_offset=22,
                            value=Name(lineno=15, col_offset=11, end_lineno=15, end_col_offset=17, id='fields', ctx=Load()),
                            attr='Char',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=15, col_offset=23, end_lineno=15, end_col_offset=29, value='Name', kind=None)],
                        keywords=[
                            keyword(
                                lineno=15,
                                col_offset=31,
                                end_lineno=15,
                                end_col_offset=45,
                                arg='translate',
                                value=Constant(lineno=15, col_offset=41, end_lineno=15, end_col_offset=45, value=True, kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=16,
                    col_offset=4,
                    end_lineno=18,
                    end_col_offset=54,
                    targets=[Name(lineno=16, col_offset=4, end_lineno=16, end_col_offset=12, id='user_ids', ctx=Store())],
                    value=Call(
                        lineno=16,
                        col_offset=15,
                        end_lineno=18,
                        end_col_offset=54,
                        func=Attribute(
                            lineno=16,
                            col_offset=15,
                            end_lineno=16,
                            end_col_offset=31,
                            value=Name(lineno=16, col_offset=15, end_lineno=16, end_col_offset=21, id='fields', ctx=Load()),
                            attr='Many2many',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=17, col_offset=8, end_lineno=17, end_col_offset=19, value='res.users', kind=None)],
                        keywords=[
                            keyword(
                                lineno=17,
                                col_offset=21,
                                end_lineno=17,
                                end_col_offset=40,
                                arg='string',
                                value=Constant(lineno=17, col_offset=28, end_lineno=17, end_col_offset=40, value='Recipients', kind=None),
                            ),
                            keyword(
                                lineno=18,
                                col_offset=8,
                                end_lineno=18,
                                end_col_offset=53,
                                arg='help',
                                value=Constant(lineno=18, col_offset=13, end_lineno=18, end_col_offset=53, value='Users having already received this tip', kind=None),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=19,
                    col_offset=4,
                    end_lineno=19,
                    end_col_offset=78,
                    targets=[Name(lineno=19, col_offset=4, end_lineno=19, end_col_offset=19, id='tip_description', ctx=Store())],
                    value=Call(
                        lineno=19,
                        col_offset=22,
                        end_lineno=19,
                        end_col_offset=78,
                        func=Attribute(
                            lineno=19,
                            col_offset=22,
                            end_lineno=19,
                            end_col_offset=33,
                            value=Name(lineno=19, col_offset=22, end_lineno=19, end_col_offset=28, id='fields', ctx=Load()),
                            attr='Html',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=19, col_offset=34, end_lineno=19, end_col_offset=51, value='Tip description', kind=None)],
                        keywords=[
                            keyword(
                                lineno=19,
                                col_offset=53,
                                end_lineno=19,
                                end_col_offset=77,
                                arg='translate',
                                value=Name(lineno=19, col_offset=63, end_lineno=19, end_col_offset=77, id='html_translate', ctx=Load()),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
                Assign(
                    lineno=20,
                    col_offset=4,
                    end_lineno=22,
                    end_col_offset=61,
                    targets=[Name(lineno=20, col_offset=4, end_lineno=20, end_col_offset=12, id='group_id', ctx=Store())],
                    value=Call(
                        lineno=20,
                        col_offset=15,
                        end_lineno=22,
                        end_col_offset=61,
                        func=Attribute(
                            lineno=20,
                            col_offset=15,
                            end_lineno=20,
                            end_col_offset=30,
                            value=Name(lineno=20, col_offset=15, end_lineno=20, end_col_offset=21, id='fields', ctx=Load()),
                            attr='Many2one',
                            ctx=Load(),
                        ),
                        args=[Constant(lineno=21, col_offset=8, end_lineno=21, end_col_offset=20, value='res.groups', kind=None)],
                        keywords=[
                            keyword(
                                lineno=21,
                                col_offset=22,
                                end_lineno=21,
                                end_col_offset=47,
                                arg='string',
                                value=Constant(lineno=21, col_offset=29, end_lineno=21, end_col_offset=47, value='Authorized Group', kind=None),
                            ),
                            keyword(
                                lineno=22,
                                col_offset=8,
                                end_lineno=22,
                                end_col_offset=60,
                                arg='default',
                                value=Lambda(
                                    lineno=22,
                                    col_offset=16,
                                    end_lineno=22,
                                    end_col_offset=60,
                                    args=arguments(
                                        posonlyargs=[],
                                        args=[arg(lineno=22, col_offset=23, end_lineno=22, end_col_offset=27, arg='self', annotation=None, type_comment=None)],
                                        vararg=None,
                                        kwonlyargs=[],
                                        kw_defaults=[],
                                        kwarg=None,
                                        defaults=[],
                                    ),
                                    body=Call(
                                        lineno=22,
                                        col_offset=29,
                                        end_lineno=22,
                                        end_col_offset=60,
                                        func=Attribute(
                                            lineno=22,
                                            col_offset=29,
                                            end_lineno=22,
                                            end_col_offset=41,
                                            value=Attribute(
                                                lineno=22,
                                                col_offset=29,
                                                end_lineno=22,
                                                end_col_offset=37,
                                                value=Name(lineno=22, col_offset=29, end_lineno=22, end_col_offset=33, id='self', ctx=Load()),
                                                attr='env',
                                                ctx=Load(),
                                            ),
                                            attr='ref',
                                            ctx=Load(),
                                        ),
                                        args=[Constant(lineno=22, col_offset=42, end_lineno=22, end_col_offset=59, value='base.group_user', kind=None)],
                                        keywords=[],
                                    ),
                                ),
                            ),
                        ],
                    ),
                    type_comment=None,
                ),
            ],
            decorator_list=[],
        ),
    ],
    type_ignores=[],
)
